#!/usr/bin/env node
// Regenerates docs/SUNO.md from tools/music/jobs.json so the copy-paste sheet can never drift
// from what was actually generated locally.
//
//   node tools/music/build_suno_doc.mjs

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(new URL('../..', import.meta.url).pathname);
const jobs = JSON.parse(await readFile(path.join(ROOT, 'tools/music/jobs.json'), 'utf8'));
let results = {};
try { results = JSON.parse(await readFile(path.join(ROOT, 'tools/music/results.json'), 'utf8')); } catch {}

const HEADER = `# WHO FIGHTS — SUNO prompt sheet

Every track in the game's music library, as a **Style** block and (for the sung ones) a **Lyrics**
block. Paste the Style block into SUNO's *Style / Description* box and the Lyrics block into its
*Lyrics* box. Nothing needs editing first.

**You do not need this file.** The whole library already exists, generated locally with ACE-Step —
see \`docs/MUSIC.md\`. This sheet is here so you can regenerate any track on SUNO if you prefer its
take on it.

**Where a replacement goes**

\`\`\`
gms/3d/whofights/audio/music/<id>.mp3
\`\`\`

Save it under exactly the \`<id>\` shown in each section heading and it drops straight in — the game
reads \`data/music.json\`, which points at that filename. If your SUNO take is a different length,
fix the \`seconds\` field for that track in \`data/music.json\` (or re-run
\`node tools/music/build_manifest.mjs\` after updating \`tools/music/results.json\`); the fade/loop
runtime uses it.

**Instrumentals**: tick SUNO's *Instrumental* switch and leave Lyrics empty. Every instrumental
Style block below also says "no vocals" in words, because ACE-Step needed telling twice and SUNO
occasionally does too.

**Lengths.** Beds are 100–135 s and are meant to loop, not to be sat through. The stings are 20–25 s
and must resolve and stop. Do not let SUNO give you an 8-minute version of a bed — a take that runs
to the length cap stops rather than ends, and it will sound broken in game.

---
`;

const groups = [
  ['§1 — Instrumental beds', j => j.kind === 'instrumental' && j.seconds > 40],
  ['§2 — Instrumental stings (short, must resolve and stop)', j => j.kind === 'instrumental' && j.seconds <= 40],
  ['§3 — Tavern songs (with lyrics)', j => j.kind === 'song'],
];

let out = HEADER;
for (const [heading, pred] of groups) {
  out += `\n## ${heading}\n`;
  for (const j of jobs.filter(pred)) {
    const r = results[j.id];
    const got = r?.pass ? ` — local take: ${r.seconds}s` : '';
    out += `\n### \`${j.id}\` — ${j.title}\n\n`;
    out += `*${j.mood}, target ${j.seconds}s${got}*\n\n`;
    out += `**Style**\n\n\`\`\`\n${j.prompt}\n\`\`\`\n\n`;
    if (j.lyrics) out += `**Lyrics**\n\n\`\`\`\n${j.lyrics}\n\`\`\`\n\n`;
    else out += `**Lyrics** — none. Instrumental.\n\n`;
  }
}

out += `\n---\n\n_Generated by \`tools/music/build_suno_doc.mjs\` from \`tools/music/jobs.json\`. Edit the jobs file, not this._\n`;

await writeFile(path.join(ROOT, 'docs/SUNO.md'), out);
console.log(`docs/SUNO.md — ${jobs.length} entries`);
