#!/usr/bin/env node
// Regenerates docs/SUNO.md from tools/music/jobs.json so the copy-paste sheet can never drift
// from what was actually generated locally.
//
//   node tools/music/build_suno_doc.mjs

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(new URL('../..', import.meta.url).pathname);
const jobs = JSON.parse(await readFile(path.join(ROOT, 'tools/music/jobs.json'), 'utf8'));
let results = {};
try { results = JSON.parse(await readFile(path.join(ROOT, 'tools/music/results.json'), 'utf8')); } catch {}

const HEADER = `# WHO FIGHTS — prompt and lyric record

**The record of what the music library is and how it was made.** Every track, its exact prompt, its
exact lyrics, and the settings used. Regenerate any of it — locally or on Suno — from this file.

**Nothing here was generated on Suno.** The whole library came from **ACE-Step 1.5 turbo** running
locally on \`http://localhost:8001\`. The Suno path was attempted and **the browser automation was
refused by the permission classifier on the first call**, so no Suno tab was opened, no generation
run, and no credits spent. If Aaron wants Suno takes, that permission has to be granted first; the
browser recipe is in \`../../2d/skyhammer/docs/MUSIC_NOTES.md\` and the prompts below drop straight
into it.

## Settings used (ACE-Step, all 25 tracks)

| field | value |
|---|---|
| endpoint | \`POST http://localhost:8001/release_task\` → poll \`/query_result\` → fetch \`/v1/audio?path=\` |
| model | \`acestep-v15-turbo\` (the plist default) |
| \`inference_steps\` | **4** |
| \`batch_size\` | 1 |
| \`thinking\` | **true** for the sung tracks, **false** for instrumentals |
| \`audio_duration\` | per track below — 20–135 s, all well inside the 480 s cap |
| \`vocal_language\` | \`en\` |
| \`audio_format\` | \`mp3\` (48 kHz stereo 128 k raw, shipped at 32 kHz mono 56 k) |

## If you regenerate on Suno instead

Save the take as \`audio/music/<id>.mp3\` — the id in each heading below — and it drops straight in;
the game reads \`data/music.json\`, which points at that filename. Then set that track's
\`"source": "suno"\` in \`tools/music/jobs.json\` and re-run
\`node tools/music/build_manifest.mjs\` so the manifest records where it came from.

Suno wants a **shorter, tag-like** style string than the ACE-Step prompts below; trim them. For the
instrumentals, tick Suno's *Instrumental* switch as well as saying "no vocals" in the text. **Set
Duration explicitly — never leave it on Auto**: a take that runs to the 8:00 cap stops rather than
ends, and these are loops.

## The vocal recipe that worked

Voice character comes from the **prompt**, never from lyric tags — \`(male)\` / \`(female)\` /
\`(crowd)\` / \`(both)\` inline in the lyrics only help place vocals across sections. The one thing
that mattered most: **ask for one close-miked lead and a thin arrangement.** A full band plus a
crowd singing in unison comes back as mud. Two of the eight songs were regenerated for exactly this
and the fix was to demand "ONE clear lead vocal, close-miked and mixed loud right at the front […]
plenty of space, no wall of noise, diction is the priority".

---
`;

const groups = [
  ['§1 — Instrumental beds', j => j.kind === 'instrumental' && j.seconds > 40],
  ['§2 — Instrumental stings (short, must resolve and stop)', j => j.kind === 'instrumental' && j.seconds <= 40],
  ['§3 — Tavern songs (with lyrics)', j => j.kind === 'song'],
];

let out = HEADER;
for (const [heading, pred] of groups) {
  out += `\n## ${heading}\n`;
  for (const j of jobs.filter(pred)) {
    const r = results[j.id];
    const got = r?.pass ? ` — local take: ${r.seconds}s` : '';
    out += `\n### \`${j.id}\` — ${j.title}\n\n`;
    out += `*${j.mood}, target ${j.seconds}s${got}*\n\n`;
    out += `**Style**\n\n\`\`\`\n${j.prompt}\n\`\`\`\n\n`;
    if (j.lyrics) out += `**Lyrics**\n\n\`\`\`\n${j.lyrics}\n\`\`\`\n\n`;
    else out += `**Lyrics** — none. Instrumental.\n\n`;
  }
}

out += `\n---\n\n_Generated by \`tools/music/build_suno_doc.mjs\` from \`tools/music/jobs.json\`. Edit the jobs file, not this._\n`;

await writeFile(path.join(ROOT, 'docs/SUNO.md'), out);
console.log(`docs/SUNO.md — ${jobs.length} entries`);
