// Generated by tools/build_music_manifest.mjs. Missing files are tolerated: audio.js
// simply stays silent for any id whose mp3 is absent.
export const MUSIC = {
  menu:    'assets/audio/menu.mp3',
  fight1:  'assets/audio/fight1.mp3',
  fight2:  'assets/audio/fight2.mp3',
  fight3:  'assets/audio/fight3.mp3',
  boss:    'assets/audio/boss.mp3',
  final:   'assets/audio/final.mp3',
  victory: 'assets/audio/victory.mp3',
};
