// Generated by gen_monsters.py — every monster clip that has ever been
// rendered, plus which one the game plays. Edit through the debug panel
// (Monsters tab) rather than by hand.
window.MonsterVariants = {
  "clips": {
    "attack:bone_collector": {
      "selected": "videos/monster_attack_bone_collector_v3.mp4",
      "variants": [
        {
          "bytes": 236955,
          "created": "2026-05-17 03:38:40",
          "file": "monster_attack_bone_collector.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 40.0,
          "src": "videos/monster_attack_bone_collector.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 340948,
          "created": "2026-08-11 10:36:39",
          "durationSecs": 232.4,
          "file": "monster_attack_bone_collector_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a stooped figure in a long dark travelling coat carrying a heavy worn leather bag is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 65.0,
          "src": "videos/monster_attack_bone_collector_v2.mp4",
          "start": "images/monster_attack_bone_collector_start.jpg"
        },
        {
          "bytes": 336585,
          "created": "2026-08-11 10:48:39",
          "file": "monster_attack_bone_collector_v3.mp4",
          "flags": [],
          "n": 3,
          "note": "recovered from disk",
          "prompt": "",
          "score": 37.0,
          "src": "videos/monster_attack_bone_collector_v3.mp4",
          "start": "images/monster_attack_bone_collector_start.jpg"
        }
      ]
    },
    "attack:crawling_thing": {
      "selected": "videos/monster_attack_crawling_thing_v2.mp4",
      "variants": [
        {
          "bytes": 148697,
          "created": "2026-05-17 03:45:41",
          "file": "monster_attack_crawling_thing.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 60,
          "src": "videos/monster_attack_crawling_thing.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 198446,
          "created": "2026-08-11 10:44:45",
          "durationSecs": 245.2,
          "file": "monster_attack_crawling_thing_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a long dark humanoid shape on all fours, limbs too long, crawling low along the floor is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_crawling_thing_v2.mp4",
          "start": "images/monster_attack_crawling_thing_start.jpg"
        }
      ]
    },
    "attack:faceless_doctor": {
      "selected": "videos/monster_attack_faceless_doctor_v3.mp4",
      "variants": [
        {
          "bytes": 176430,
          "created": "2026-05-17 03:31:40",
          "file": "monster_attack_faceless_doctor.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 35.4,
          "src": "videos/monster_attack_faceless_doctor.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 202713,
          "created": "2026-08-11 10:28:58",
          "durationSecs": 237.1,
          "file": "monster_attack_faceless_doctor_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall slim figure in a long dark physician's coat with a brass stethoscope, a high collar, and only a smooth blank featureless shape above the collar is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_faceless_doctor_v2.mp4",
          "start": "images/monster_attack_faceless_doctor_start.jpg"
        },
        {
          "bytes": 73066,
          "created": "2026-08-11 11:04:55",
          "file": "monster_attack_faceless_doctor_v3.mp4",
          "flags": [],
          "n": 3,
          "note": "recovered from disk",
          "prompt": "",
          "score": 60,
          "src": "videos/monster_attack_faceless_doctor_v3.mp4",
          "start": "images/monster_attack_faceless_doctor_start.jpg"
        }
      ]
    },
    "attack:hollow_one": {
      "selected": "videos/monster_attack_hollow_one_v2.mp4",
      "variants": [
        {
          "bytes": 205337,
          "created": "2026-05-16 14:24:39",
          "file": "monster_attack_hollow_one.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 60,
          "src": "videos/monster_attack_hollow_one.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 162234,
          "created": "2026-08-11 10:21:07",
          "durationSecs": 224.2,
          "file": "monster_attack_hollow_one_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall figure in a long dark heavy coat with a deep dark hood pulled up so the face is completely hidden in shadow is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 65.6,
          "src": "videos/monster_attack_hollow_one_v2.mp4",
          "start": "images/monster_attack_hollow_one_start.jpg"
        }
      ]
    },
    "attack:lost_child": {
      "selected": "videos/monster_attack_lost_child_v2.mp4",
      "variants": [
        {
          "bytes": 206788,
          "created": "2026-05-16 13:59:42",
          "file": "monster_attack_lost_child.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 44.6,
          "src": "videos/monster_attack_lost_child.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 321664,
          "created": "2026-08-11 09:50:44",
          "durationSecs": 237.6,
          "file": "monster_attack_lost_child_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a small child of about eight in a dirty dark navy coat and dark hood, dark hair partly covering the face is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 68.3,
          "src": "videos/monster_attack_lost_child_v2.mp4",
          "start": "images/monster_attack_lost_child_start.jpg"
        }
      ]
    },
    "attack:mourning_groom": {
      "selected": "videos/monster_attack_mourning_groom_v2.mp4",
      "variants": [
        {
          "bytes": 279201,
          "created": "2026-05-17 03:53:05",
          "file": "monster_attack_mourning_groom.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 48.1,
          "src": "videos/monster_attack_mourning_groom.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 235005,
          "created": "2026-08-11 11:08:48",
          "durationSecs": 233.1,
          "file": "monster_attack_mourning_groom_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall man in a formal black wedding suit with neatly combed dark hair and a small white boutonniere on his lapel, hollow eyes is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_mourning_groom_v2.mp4",
          "start": "images/monster_attack_mourning_groom_start.jpg"
        }
      ]
    },
    "attack:pale_woman": {
      "selected": "videos/monster_attack_pale_woman_v2.mp4",
      "variants": [
        {
          "bytes": 170777,
          "created": "2026-05-16 01:07:57",
          "file": "monster_attack_pale_woman.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 60,
          "src": "videos/monster_attack_pale_woman.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 292485,
          "created": "2026-08-11 09:35:32",
          "durationSecs": 222.6,
          "file": "monster_attack_pale_woman_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall pale-faced woman wrapped in a dark grey shawl over a long dark dress, with long dark hair down past her shoulders is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 52.2,
          "src": "videos/monster_attack_pale_woman_v2.mp4",
          "start": "images/monster_attack_pale_woman_start.jpg"
        }
      ]
    },
    "attack:paper_mask": {
      "selected": "videos/monster_attack_paper_mask_v3.mp4",
      "variants": [
        {
          "bytes": 127389,
          "created": "2026-05-17 04:00:18",
          "file": "monster_attack_paper_mask.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 41.0,
          "src": "videos/monster_attack_paper_mask.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 217253,
          "created": "2026-08-11 11:16:04",
          "durationSecs": 218.0,
          "file": "monster_attack_paper_mask_v2.mp4",
          "flags": [
            "runaway"
          ],
          "n": 2,
          "note": "",
          "prompt": "a slim figure in a long dark coat whose whole face is covered by a flat folded sheet of white paper is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 20,
          "src": "videos/monster_attack_paper_mask_v2.mp4",
          "start": "images/monster_attack_paper_mask_start.jpg"
        },
        {
          "bytes": 172208,
          "created": "2026-08-11 11:49:39",
          "durationSecs": 238.1,
          "file": "monster_attack_paper_mask_v3.mp4",
          "flags": [],
          "n": 3,
          "note": "",
          "prompt": "a slim figure in a long dark coat whose whole face is covered by a flat folded sheet of white paper is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_paper_mask_v3.mp4",
          "start": "images/monster_attack_paper_mask_start.jpg"
        }
      ]
    },
    "attack:previous_tenant": {
      "selected": "videos/monster_attack_previous_tenant_v2.mp4",
      "variants": [
        {
          "bytes": 223062,
          "created": "2026-05-16 14:04:55",
          "file": "monster_attack_previous_tenant.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 44.5,
          "src": "videos/monster_attack_previous_tenant.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 368336,
          "created": "2026-08-11 09:58:15",
          "durationSecs": 226.4,
          "file": "monster_attack_previous_tenant_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a gaunt elderly man in a dark brown wool suit and dark waistcoat, neatly combed dark grey hair and hollow shadowed eyes is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 42.4,
          "src": "videos/monster_attack_previous_tenant_v2.mp4",
          "start": "images/monster_attack_previous_tenant_start.jpg"
        }
      ]
    },
    "attack:red_lady": {
      "selected": "videos/monster_attack_red_lady_v2.mp4",
      "variants": [
        {
          "bytes": 187540,
          "created": "2026-05-17 04:07:37",
          "file": "monster_attack_red_lady.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 45.2,
          "src": "videos/monster_attack_red_lady.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 220331,
          "created": "2026-08-11 11:23:24",
          "durationSecs": 212.8,
          "file": "monster_attack_red_lady_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall woman in a long deep crimson red evening dress with dark hair worn up is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 49.8,
          "src": "videos/monster_attack_red_lady_v2.mp4",
          "start": "images/monster_attack_red_lady_start.jpg"
        }
      ]
    },
    "attack:silent_companion": {
      "selected": "videos/monster_attack_silent_companion_v2.mp4",
      "variants": [
        {
          "bytes": 177064,
          "created": "2026-05-16 14:17:32",
          "file": "monster_attack_silent_companion.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 34.2,
          "src": "videos/monster_attack_silent_companion.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 266629,
          "created": "2026-08-11 10:13:32",
          "durationSecs": 223.7,
          "file": "monster_attack_silent_companion_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a slim figure in a charcoal-grey dressing gown with long dark hair hanging over the face is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_silent_companion_v2.mp4",
          "start": "images/monster_attack_silent_companion_start.jpg"
        }
      ]
    },
    "attack:white_shadow": {
      "selected": "videos/monster_attack_white_shadow_v2.mp4",
      "variants": [
        {
          "bytes": 176330,
          "created": "2026-05-16 14:10:55",
          "file": "monster_attack_white_shadow.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 48.5,
          "src": "videos/monster_attack_white_shadow.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 142091,
          "created": "2026-08-11 10:05:51",
          "durationSecs": 218.5,
          "file": "monster_attack_white_shadow_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall featureless jet-black humanoid silhouette like a perfect ink-cut shape, no face, no surface detail is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_white_shadow_v2.mp4",
          "start": "images/monster_attack_white_shadow_start.jpg"
        }
      ]
    },
    "release:bone_collector": {
      "selected": "videos/monster_release_bone_collector_v2.mp4",
      "variants": [
        {
          "bytes": 213125,
          "created": "2026-05-17 03:35:10",
          "file": "monster_release_bone_collector.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 42.5,
          "src": "videos/monster_release_bone_collector.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 165771,
          "created": "2026-08-11 10:32:44",
          "durationSecs": 224.4,
          "file": "monster_release_bone_collector_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a stooped figure in a long dark travelling coat carrying a heavy worn leather bag is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 22.2,
          "src": "videos/monster_release_bone_collector_v2.mp4",
          "start": "images/monster_release_bone_collector_start.jpg"
        }
      ]
    },
    "release:crawling_thing": {
      "selected": "videos/monster_release_crawling_thing_v2.mp4",
      "variants": [
        {
          "bytes": 135228,
          "created": "2026-05-17 03:42:10",
          "file": "monster_release_crawling_thing.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 16.6,
          "src": "videos/monster_release_crawling_thing.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 162060,
          "created": "2026-08-11 10:40:40",
          "durationSecs": 238.1,
          "file": "monster_release_crawling_thing_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a long dark humanoid shape on all fours, limbs too long, crawling low along the floor is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 31.9,
          "src": "videos/monster_release_crawling_thing_v2.mp4",
          "start": "images/monster_release_crawling_thing_start.jpg"
        }
      ]
    },
    "release:faceless_doctor": {
      "selected": "videos/monster_release_faceless_doctor_v3.mp4",
      "variants": [
        {
          "bytes": 135074,
          "created": "2026-05-17 03:28:15",
          "file": "monster_release_faceless_doctor.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 27.2,
          "src": "videos/monster_release_faceless_doctor.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 106978,
          "created": "2026-08-11 10:24:58",
          "durationSecs": 228.7,
          "file": "monster_release_faceless_doctor_v2.mp4",
          "flags": [
            "static"
          ],
          "n": 2,
          "note": "",
          "prompt": "a tall slim figure in a long dark physician's coat with a brass stethoscope, a high collar, and only a smooth blank featureless shape above the collar is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": -25.2,
          "src": "videos/monster_release_faceless_doctor_v2.mp4",
          "start": "images/monster_release_faceless_doctor_start.jpg"
        },
        {
          "bytes": 130943,
          "created": "2026-08-11 10:52:44",
          "file": "monster_release_faceless_doctor_v3.mp4",
          "flags": [],
          "n": 3,
          "note": "recovered from disk",
          "prompt": "",
          "score": 27.1,
          "src": "videos/monster_release_faceless_doctor_v3.mp4",
          "start": "images/monster_release_faceless_doctor_start.jpg"
        }
      ]
    },
    "release:hollow_one": {
      "selected": "videos/monster_release_hollow_one_v2.mp4",
      "variants": [
        {
          "bytes": 133462,
          "created": "2026-05-16 14:21:02",
          "file": "monster_release_hollow_one.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 60,
          "src": "videos/monster_release_hollow_one.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 144233,
          "created": "2026-08-11 10:17:22",
          "durationSecs": 225.9,
          "file": "monster_release_hollow_one_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall figure in a long dark heavy coat with a deep dark hood pulled up so the face is completely hidden in shadow is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 41.7,
          "src": "videos/monster_release_hollow_one_v2.mp4",
          "start": "images/monster_release_hollow_one_start.jpg"
        }
      ]
    },
    "release:lost_child": {
      "selected": "videos/monster_release_lost_child_v2.mp4",
      "variants": [
        {
          "bytes": 257439,
          "created": "2026-05-16 13:57:36",
          "file": "monster_release_lost_child.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 45.0,
          "src": "videos/monster_release_lost_child.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 126389,
          "created": "2026-08-11 09:42:58",
          "durationSecs": 219.5,
          "file": "monster_release_lost_child_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a small child of about eight in a dirty dark navy coat and dark hood, dark hair partly covering the face is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 23.8,
          "src": "videos/monster_release_lost_child_v2.mp4",
          "start": "images/monster_release_lost_child_start.jpg"
        }
      ]
    },
    "release:mourning_groom": {
      "selected": "videos/monster_release_mourning_groom_v2.mp4",
      "variants": [
        {
          "bytes": 252398,
          "created": "2026-05-17 03:49:23",
          "file": "monster_release_mourning_groom.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 69.2,
          "src": "videos/monster_release_mourning_groom.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 126103,
          "created": "2026-08-11 11:01:12",
          "durationSecs": 252.5,
          "file": "monster_release_mourning_groom_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall man in a formal black wedding suit with neatly combed dark hair and a small white boutonniere on his lapel, hollow eyes is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 27.1,
          "src": "videos/monster_release_mourning_groom_v2.mp4",
          "start": "images/monster_release_mourning_groom_start.jpg"
        }
      ]
    },
    "release:pale_woman": {
      "selected": "videos/monster_release_pale_woman_v2.mp4",
      "variants": [
        {
          "bytes": 332491,
          "created": "2026-05-16 01:04:32",
          "file": "monster_release_pale_woman.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 50.1,
          "src": "videos/monster_release_pale_woman.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 157574,
          "created": "2026-08-11 09:28:06",
          "durationSecs": 255.4,
          "file": "monster_release_pale_woman_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall pale-faced woman wrapped in a dark grey shawl over a long dark dress, with long dark hair down past her shoulders is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 42.7,
          "src": "videos/monster_release_pale_woman_v2.mp4",
          "start": "images/monster_release_pale_woman_start.jpg"
        }
      ]
    },
    "release:paper_mask": {
      "selected": "videos/monster_release_paper_mask_v2.mp4",
      "variants": [
        {
          "bytes": 177942,
          "created": "2026-05-17 03:56:42",
          "file": "monster_release_paper_mask.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 48.4,
          "src": "videos/monster_release_paper_mask.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 106276,
          "created": "2026-08-11 11:12:23",
          "durationSecs": 214.6,
          "file": "monster_release_paper_mask_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a slim figure in a long dark coat whose whole face is covered by a flat folded sheet of white paper is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 18.8,
          "src": "videos/monster_release_paper_mask_v2.mp4",
          "start": "images/monster_release_paper_mask_start.jpg"
        }
      ]
    },
    "release:previous_tenant": {
      "selected": "videos/monster_release_previous_tenant_v2.mp4",
      "variants": [
        {
          "bytes": 203069,
          "created": "2026-05-16 14:02:13",
          "file": "monster_release_previous_tenant.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 50.6,
          "src": "videos/monster_release_previous_tenant.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 148553,
          "created": "2026-08-11 09:54:24",
          "durationSecs": 218.9,
          "file": "monster_release_previous_tenant_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a gaunt elderly man in a dark brown wool suit and dark waistcoat, neatly combed dark grey hair and hollow shadowed eyes is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 27.2,
          "src": "videos/monster_release_previous_tenant_v2.mp4",
          "start": "images/monster_release_previous_tenant_start.jpg"
        }
      ]
    },
    "release:red_lady": {
      "selected": "videos/monster_release_red_lady_v2.mp4",
      "variants": [
        {
          "bytes": 269002,
          "created": "2026-05-17 04:04:00",
          "file": "monster_release_red_lady.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 48.5,
          "src": "videos/monster_release_red_lady.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 142927,
          "created": "2026-08-11 11:19:49",
          "durationSecs": 221.2,
          "file": "monster_release_red_lady_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall woman in a long deep crimson red evening dress with dark hair worn up is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 25.8,
          "src": "videos/monster_release_red_lady_v2.mp4",
          "start": "images/monster_release_red_lady_start.jpg"
        }
      ]
    },
    "release:silent_companion": {
      "selected": "videos/monster_release_silent_companion_v2.mp4",
      "variants": [
        {
          "bytes": 180211,
          "created": "2026-05-16 14:14:14",
          "file": "monster_release_silent_companion.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 43.3,
          "src": "videos/monster_release_silent_companion.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 103473,
          "created": "2026-08-11 10:09:46",
          "durationSecs": 233.8,
          "file": "monster_release_silent_companion_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a slim figure in a charcoal-grey dressing gown with long dark hair hanging over the face is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 29.4,
          "src": "videos/monster_release_silent_companion_v2.mp4",
          "start": "images/monster_release_silent_companion_start.jpg"
        }
      ]
    },
    "release:white_shadow": {
      "selected": "videos/monster_release_white_shadow_v2.mp4",
      "variants": [
        {
          "bytes": 187174,
          "created": "2026-05-16 14:07:49",
          "file": "monster_release_white_shadow.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 45.6,
          "src": "videos/monster_release_white_shadow.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 137097,
          "created": "2026-08-11 10:02:10",
          "durationSecs": 231.4,
          "file": "monster_release_white_shadow_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall featureless jet-black humanoid silhouette like a perfect ink-cut shape, no face, no surface detail is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature stays clearly lit and readable against the corridor, the creature does not change shape, no other people, no gore",
          "score": 33.3,
          "src": "videos/monster_release_white_shadow_v2.mp4",
          "start": "images/monster_release_white_shadow_start.jpg"
        }
      ]
    }
  },
  "game": "the_horrors",
  "generated": "2026-08-11 11:49:39",
  "monsters": [
    {
      "attackRef": "ref/monster_pale_woman_attack.jpg",
      "id": "pale_woman",
      "name": "the pale woman",
      "ref": "ref/monster_pale_woman.jpg"
    },
    {
      "attackRef": "ref/monster_lost_child_attack.jpg",
      "id": "lost_child",
      "name": "the lost child",
      "ref": "ref/monster_lost_child.jpg"
    },
    {
      "attackRef": "ref/monster_previous_tenant_attack.jpg",
      "id": "previous_tenant",
      "name": "the previous tenant",
      "ref": "ref/monster_previous_tenant.jpg"
    },
    {
      "attackRef": "ref/monster_white_shadow_attack.jpg",
      "id": "white_shadow",
      "name": "the white shadow",
      "ref": "ref/monster_white_shadow.jpg"
    },
    {
      "attackRef": "ref/monster_silent_companion_attack.jpg",
      "id": "silent_companion",
      "name": "the silent companion",
      "ref": "ref/monster_silent_companion.jpg"
    },
    {
      "attackRef": "ref/monster_hollow_one_attack.jpg",
      "id": "hollow_one",
      "name": "the hollow one",
      "ref": "ref/monster_hollow_one.jpg"
    },
    {
      "attackRef": "ref/monster_faceless_doctor_attack.jpg",
      "id": "faceless_doctor",
      "name": "the faceless doctor",
      "ref": "ref/monster_faceless_doctor.jpg"
    },
    {
      "attackRef": "ref/monster_bone_collector_attack.jpg",
      "id": "bone_collector",
      "name": "the bone collector",
      "ref": "ref/monster_bone_collector.jpg"
    },
    {
      "attackRef": "ref/monster_crawling_thing_attack.jpg",
      "id": "crawling_thing",
      "name": "the crawling thing",
      "ref": "ref/monster_crawling_thing.jpg"
    },
    {
      "attackRef": "ref/monster_mourning_groom_attack.jpg",
      "id": "mourning_groom",
      "name": "the mourning groom",
      "ref": "ref/monster_mourning_groom.jpg"
    },
    {
      "attackRef": "ref/monster_paper_mask_attack.jpg",
      "id": "paper_mask",
      "name": "the paper mask",
      "ref": "ref/monster_paper_mask.jpg"
    },
    {
      "attackRef": "ref/monster_red_lady_attack.jpg",
      "id": "red_lady",
      "name": "the red lady",
      "ref": "ref/monster_red_lady.jpg"
    }
  ],
  "zoom": {
    "videos/monster_attack_bone_collector_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_bone_collector_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_crawling_thing_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_faceless_doctor_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_faceless_doctor_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_hollow_one_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_lost_child_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_mourning_groom_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_pale_woman_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_paper_mask_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_paper_mask_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_previous_tenant_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_red_lady_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_silent_companion_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_white_shadow_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    }
  }
};
