import {CDP} from './cdp.mjs';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const c=await CDP.launch({gpu:true});
const url=process.env.TRANSPORT_URL||'http://127.0.0.1:8888/gms/3d/idle-transport2/';
const out=process.env.TRANSPORT_OUTPUT_DIR||fileURLToPath(new URL('../docs/verification/',import.meta.url));mkdirSync(out,{recursive:true});
const checks=[];
async function measure(){return c.eval(`new Promise(resolve=>{const samples=[];let last=performance.now(),first=transport2.scenes.debug.frames,start=last;function run(now){samples.push(now-last);last=now;if(samples.length<120)requestAnimationFrame(run);else{samples.sort((a,b)=>a-b);const d=transport2.scenes.debug;resolve({p50:samples[60],p95:samples[114],renderFps:(d.frames-first)*1000/(now-start),dpr:d.dpr,drawCalls:d.drawCalls,source:d.sourceSize,graphics:d.graphics,staticInstances:d.staticInstances,rendererCount:d.rendererCount})}}requestAnimationFrame(run)})`);}
async function capture(name){await c.eval(`document.querySelector('#toast-stack').style.opacity='0'`);const{data}=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(out+'/'+name+'.png',Buffer.from(data,'base64'));}
try{
 await c.viewport(412,915,2.625,true);await c.goto(url);assert(await c.waitFor('transport2?.scenes?.debug.graphics',20000));await c.frames(15);await capture('challenge-fresh-phone');
 await c.eval(`(()=>{const s=JSON.parse(transport2.game.exportSave());s.cash=1e10;s.totalEarned=1e12;s.unlockedRegions=['meadow','industrial','coastal','alpine','aerospace'];for(const r of Object.values(s.routes)){r.unlocked=true;r.manager=true;r.fleet=7;r.level=20;}transport2.game.importSave(JSON.stringify(s));})()`);await c.frames(20);
 const meadow=await measure();assert.equal(meadow.rendererCount,1);assert(meadow.dpr<=1.75);assert(meadow.source.width<=850&&meadow.source.height<=850,'phone backing buffer stays bounded');assert(meadow.renderFps>=20,'hardware Chrome renders at least twenty paints/sec');checks.push('high-DPR phone has one bounded renderer and keeps painting');await capture('challenge-active-phone');
 const series=[];
 for(let cycle=0;cycle<3;cycle++)for(const region of ['industrial','coastal','alpine','aerospace','meadow']){await c.eval(`transport2.game.action('selectRegion',${JSON.stringify(region)})`);await c.frames(3);series.push(await c.eval('({...transport2.scenes.debug.graphics,staticInstances:transport2.scenes.debug.staticInstances})'));}
 const ends=[series[4],series[9],series[14]];for(const sample of ends)assert.equal(sample.staticInstances,meadow.staticInstances,'cached business detail survives rebuilding its district');assert(ends[2].textures<=ends[0].textures+2,'district rebuild releases private textures');assert(ends[2].geometries<=ends[0].geometries+4,'district rebuild releases private geometry');checks.push('repeated district changes keep GPU texture and geometry counts stable');
 for(const region of ['industrial','coastal','alpine','aerospace']){await c.eval(`transport2.game.action('selectRegion',${JSON.stringify(region)});transport2.scenes.overview()`);await c.frames(15);await capture('challenge-'+region+'-phone');}
 await c.eval(`transport2.game.action('selectRegion','meadow');transport2.scenes.focus('grain',true)`);await c.frames(90);await capture('challenge-pin-phone');
 await c.eval(`transport2.scenes.overview();document.querySelector('#network-filter').click()`);await c.frames(15);const network=await measure();assert.equal(await c.eval('transport2.scenes.debug.district.siteIds.length'),15);checks.push('all fifteen business district remains active in one renderer');
 await c.viewport(1440,1050,1,false);await c.frames(15);await capture('challenge-network-desktop');
 await c.viewport(412,915,2.625,true);await c.eval(`transport2.game.action('selectRegion','meadow');if(document.querySelector('#network-filter').getAttribute('aria-pressed')==='true')document.querySelector('#network-filter').click();window.__qualityTick=transport2.game.tick;transport2.game.tick=()=>{};transport2.game.state.routes.grain.progress=.3;transport2.scenes.focus('grain',false);document.querySelector('#operations-scroll').scrollTop=0`);await c.eval('new Promise(r=>setTimeout(r,3100))');await c.frames(90);
 const followA=await c.eval('transport2.scenes.debug.audit().heroCameraPosition');const screenA=await c.eval('transport2.scenes.debug.follow.leaderScreen');assert(screenA[0]>.2&&screenA[0]<.8&&screenA[1]>.2&&screenA[1]<.8,'featured truck is framed in the visible center: '+screenA);await capture('challenge-truck-tour-phone');await c.eval('transport2.game.state.routes.grain.progress=.4');await c.frames(90);const followB=await c.eval('transport2.scenes.debug.audit().heroCameraPosition');assert(Math.hypot(...followA.map((n,i)=>n-followB[i]))>1,'director follows physical truck motion');const screenB=await c.eval('transport2.scenes.debug.follow.leaderScreen');assert(screenB[0]>.2&&screenB[0]<.8&&screenB[1]>.2&&screenB[1]<.8,'moving featured truck remains framed: '+screenB);checks.push('cinematic tour follows and keeps the actual route vehicle in frame');
 await c.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await c.eval("transport2.scenes.focus('grain',false)");await c.frames(10);const stillA=await c.eval('transport2.scenes.debug.audit().heroCameraPosition');await c.eval('transport2.game.state.routes.grain.progress=.7');await c.frames(10);const stillB=await c.eval('transport2.scenes.debug.audit().heroCameraPosition');assert(Math.hypot(...stillA.map((n,i)=>n-stillB[i]))<.01,'reduced motion keeps business camera stationary');checks.push('reduced-motion preference replaces truck following with a steady business camera');await c.eval('transport2.game.tick=window.__qualityTick;delete window.__qualityTick');
 assert.equal(c.errors.length,0,c.errors.join('\n'));writeFileSync(out+'/quality-report.json',JSON.stringify({url,checks,meadow,network,resources:ends,errors:c.errors},null,2));console.log(JSON.stringify({checks,meadow,network,resources:ends}));
}finally{c.close();}
