import {REGIONS, ROUTES, RESEARCH, CONTRACTS, POLICIES, ITEMS, SEASON_BUSINESSES, SEASON_MILESTONES, createGame} from './economy.mjs?v=20261003-business3';
import {createScenes} from './scenes.mjs?v=20261003-business3';
import {createTapInteraction} from './tap.mjs?v=20261003-business3';
const $=s=>document.querySelector(s);
const money=value=>{if(value>=1e12)return '$'+(value/1e12).toFixed(2)+'T';if(value>=1e9)return '$'+(value/1e9).toFixed(2)+'B';if(value>=1e6)return '$'+(value/1e6).toFixed(2)+'M';if(value>=1e4)return '$'+(value/1e3).toFixed(1)+'K';return '$'+Math.floor(value).toLocaleString('en-US');};
const count=value=>value>=1e6?(value/1e6).toFixed(1)+'M':Math.floor(value).toLocaleString('en-US');
const game=createGame();let focused=null,pinned=false,tab='world',listMode='region',lastStructure='',renderClock=0, audioContext,lastPlanningHTML='',quantity='1',infoRoute=null,managerRoute=null;
function toast(message,error=false){if(!message)return;const node=document.createElement('div');node.className='toast'+(error?' error':'');node.textContent=message;$('#toast-stack').append(node);while($('#toast-stack').children.length>(matchMedia('(max-width:580px)').matches?1:2))$('#toast-stack').firstElementChild.remove();setTimeout(()=>node.remove(),4200);}
function sound(){if(!game.state.settings.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(520,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(780,audioContext.currentTime+.09);g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.18);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.2);}catch{}}
const scenes=createScenes({hero:$('#hero-view'),getGame:()=>game,onFocus:(id,locked)=>{focused=id;pinned=locked;updateFocus();}});
window.transport2={game,scenes};
function act(type,id){if(type==='selectRegion'||type==='unlockRegion')listMode='region';const result=game.action(type==='managerUpgrade'?'manager':type,id,['upgrade','fleet','storage'].includes(type)?quantity==='max'?'max':Number(quantity):1);if(!result.ok)toast(result.message,true);else if(type==='dispatch')sound();if(type==='quality')scenes.setQuality(game.state.settings.quality);render(true);if(result.ok&&(type==='selectRegion'||type==='unlockRegion'))$('#operations-scroll').scrollTo({top:0,behavior:'instant'});return result;}
function updateFocus(){const route=ROUTES.find(r=>r.id===focused);if(!route)return;const region=REGIONS.find(r=>r.id===route.region);$('#hero-region').textContent=region.name.toUpperCase()+' / '+route.cargo.toUpperCase();$('#hero-title').textContent=route.name;$('#hero-detail').textContent=route.from+' → '+route.to;$('#journey-caption').textContent=route.cargo.toUpperCase()+' IN MOTION'+(pinned?' / CAMERA PINNED':' / AUTO TOUR');$('#scene-number').textContent='SITE / '+String(ROUTES.indexOf(route)+1).padStart(2,'0');$('#hero-pin').classList.toggle('active',pinned);$('#hero-pin').setAttribute('aria-pressed',String(pinned));$('#hero-pin span').textContent=pinned?'Camera pinned':'Pin camera';$('#tour-button').classList.toggle('active',!pinned);$('#tour-button').setAttribute('aria-pressed',String(!pinned));document.querySelectorAll('.route-card').forEach(el=>el.classList.toggle('is-focused',el.dataset.route===focused));document.querySelectorAll('.route-camera').forEach(el=>{const active=el.dataset.id===focused&&pinned;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});}
const productionIcon=route=>({farm:'🌾',timber:'🌲',quarry:'⛏',factory:'⚙',harbor:'⚓',oil:'🛢',alpine:'🏔',airport:'✈',space:'🚀'}[route.kind]||'▧');
function routeHTML(route){
 const s=game.state.routes[route.id],open=s.unlocked;
 return `<article class="route-card business-scene ${open?'':'route-locked'}" data-route="${route.id}"><div class="route-view" data-scene="${route.id}" role="img" aria-label="3D live view of ${route.name}"></div><div class="business-name"><h3>${route.name}</h3></div><div class="business-view-actions"><button class="route-info" data-info="${route.id}" aria-label="Information about ${route.name}" title="Business information">i</button>${open?`<button class="route-camera" data-camera="${route.id}" data-id="${route.id}" title="Pin main camera to ${route.name}" aria-label="Pin main camera to ${route.name}" aria-pressed="false">⌖</button>`:''}</div>${open?`<div class="business-controls"><div class="route-actions"><button class="upgrade" data-action="upgrade" data-id="${route.id}" aria-label="Upgrade ${route.name} production" title="Upgrade production"><span>+ ${productionIcon(route)}</span><small data-field="upgradeCost"></small></button><button data-action="fleet" data-id="${route.id}" aria-label="Add ${route.name} vehicles" title="Expand fleet"><span>+ 🚚</span><small data-field="fleetCost"></small></button><button data-action="storage" data-id="${route.id}" aria-label="Expand ${route.name} storage" title="Expand storage"><span>+ ▣</span><small data-field="storageCost"></small></button><button data-action="manager" data-id="${route.id}" aria-label="Manage ${route.name} manager" title="Hire or develop manager"><span>🕴</span><small data-field="managerCost"></small></button></div><div class="quantity-controls" role="group" aria-label="Purchase quantity">${['1','10','max'].map(q=>`<button data-quantity="${q}" aria-pressed="${quantity===q}" title="Buy ${q==='max'?'maximum affordable':q} upgrades">${q==='max'?'MAX':'×'+q}</button>`).join('')}</div></div><div class="business-progress" aria-label="Journey progress"><span data-field="progress"></span></div>`:`<button class="primary business-unlock" data-action="unlockRoute" data-id="${route.id}">${route.id==='grain'?'Start company':'Open business'} · ${money(route.unlockCost)} ↗</button>`}</article>`;
}

const map=`<div class="map-visual" aria-label="Five regions connected across a world map"><svg viewBox="0 0 300 125" role="img"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#7fa5a5" stroke-opacity=".1"/></pattern></defs><rect width="300" height="125" fill="url(#grid)"/><path d="M16 74L35 44 57 32 80 40 98 27 126 29 143 45 170 31 192 42 215 33 247 56 279 59 283 84 264 95 233 84 211 103 180 92 156 106 125 88 108 103 74 89 44 96Z" fill="#3a6060" stroke="#729180" stroke-width=".6"/><path d="M47 73L98 62 154 75 207 51 259 72" fill="none" stroke="#d1e791" stroke-width="1.2" stroke-dasharray="3 5"/>${REGIONS.map((r,i)=>`<g data-map-region="${r.id}"><circle cx="${[47,98,154,207,259][i]}" cy="${[73,62,75,51,72][i]}" r="6" fill="${r.color}"/><circle cx="${[47,98,154,207,259][i]}" cy="${[73,62,75,51,72][i]}" r="10" fill="none" stroke="${r.color}" stroke-opacity=".4"/></g>`).join('')}</svg><span class="map-caption">FIVE REGIONS / ONE CONNECTED WORLD</span></div>`;
function planningHTML(){const state=game.state;if(tab==='season')return seasonHTML();if(tab==='fleet')return fleetHTML();if(tab==='world')return map+REGIONS.map((r,i)=>{const open=state.unlockedRegions.includes(r.id),selected=state.region===r.id,previous=i===0||state.unlockedRegions.includes(REGIONS[i-1].id);return `<article class="region-item ${selected?'selected':''}"><div class="region-item-heading"><h3>${r.name}</h3><span class="region-number">0${i+1}</span></div><p>${r.subtitle}</p>${open?`<button data-action="selectRegion" data-id="${r.id}" ${selected?'disabled':''}>${selected?'Current operations · '+ROUTES.filter(x=>x.region===r.id&&state.routes[x.id].unlocked).length+'/3 routes':'View region →'}</button>`:`<div class="requirement">${previous?`${count(state.deliveries)} / ${count(r.requireDeliveries)} deliveries`:'Open '+REGIONS[i-1].name+' first'}</div><button data-action="unlockRegion" data-id="${r.id}" ${!previous||state.deliveries<r.requireDeliveries||state.cash<r.unlockCost?'disabled':''}>Unlock · ${money(r.unlockCost)} ↗</button>`}</article>`;}).join('');if(tab==='research')return '<p class="panel-intro">Better decisions. Better journeys. Every improvement benefits your whole company.</p>'+RESEARCH.map(r=>{const done=state.research.includes(r.id),requires=r.requires&&!state.research.includes(r.requires);return `<article class="research-item"><h3>${r.name}</h3><p>${r.description}</p>${done?'<span class="complete">✓ Running across your network</span>':`<button data-action="research" data-id="${r.id}" ${requires||state.cash<r.cost?'disabled':''}>${requires?'Requires '+RESEARCH.find(x=>x.id===r.requires)?.name:money(r.cost)+' · Research ↗'}</button>`}</article>`;}).join('');return '<p class="panel-intro">Make the miles count. Reach company milestones and collect your reward.</p>'+CONTRACTS.map(c=>{const s=game.contractStatus(c.id);return `<article class="contract-item"><h3>${c.name}</h3><p>${c.description}</p><div class="contract-progress"><span>${count(Math.min(s.current,s.target))} / ${count(s.target)}</span><span>${money(c.reward)} reward</span></div><div class="progress-track"><span style="width:${Math.min(100,s.current/s.target*100)}%"></span></div>${s.claimed?'<span class="complete">✓ Reward collected</span>':`<button class="${s.complete?'primary':'secondary'}" data-action="claimContract" data-id="${c.id}" ${!s.complete?'disabled':''}>${s.complete?'Collect '+money(c.reward)+' ↗':'In progress'}</button>`}</article>`;}).join('');}
function render(force=false){const state=game.state;const hasCompany=Object.values(state.routes).some(r=>r.unlocked);if((game.tapInfo?.().remaining||0)<=0)delete $('#tap-hint').dataset.combo;$('#tap-hint').classList.toggle('operating',hasCompany);const event=state.event;$('#event-banner').hidden=!event;if(event){$('#event-title').textContent=event.title+' · '+Math.ceil(event.remaining)+'s';$('#event-description').textContent=event.description;$('#event-claim').textContent='Claim '+money(event.reward);} $('#cash').textContent=money(state.cash);$('#income').textContent=money(ROUTES.reduce((n,r)=>n+game.stats(r.id).income,0));$('#deliveries').textContent=count(state.deliveries);$('#legacy').textContent='+'+count(state.prestige*15)+'%';const region=REGIONS.find(r=>r.id===state.region);$('#region-title').textContent=listMode==='all'?'All operations':region.name;$('#network-filter').textContent=listMode==='all'?'This region':'All operations';$('#network-filter').setAttribute('aria-pressed',String(listMode==='all'));const key=listMode+'|'+state.region+'|'+ROUTES.map(r=>Number(state.routes[r.id].unlocked)).join('');if(key!==lastStructure){lastStructure=key;const routes=ROUTES.filter(r=>listMode==='all'?(state.routes[r.id].unlocked||(!hasCompany&&r.region===state.region)):r.region===state.region);$('#route-list').innerHTML=routes.map(routeHTML).join('');scenes.setRoutes(routes.map(r=>({id:r.id,element:document.querySelector(`[data-scene="${r.id}"]`)})));updateFocus();force=true;}for(const row of document.querySelectorAll('.route-card')){
 const id=row.dataset.route,s=state.routes[id],stats=game.stats(id);
 if(!s.unlocked){row.querySelector('button[data-action]').disabled=state.cash<ROUTES.find(r=>r.id===id).unlockCost;continue;}
 row.querySelector('[data-field="progress"]').style.width=stats.progress*100+'%';
 for(const type of ['upgrade','fleet','storage','manager']){
  const quote=purchaseQuote(type,id),button=row.querySelector(`[data-action="${type}"]`),field=row.querySelector(`[data-field="${type}Cost"]`);
  field.textContent=type==='manager'&&s.manager?'LEVEL '+(stats.managerLevel||s.managerLevel||1):quote.maxed?'MAX':quote.count===0?'—':(quote.count>1?'×'+quote.count+' · ':'')+money(quote.cost);
  button.disabled=type==='manager'&&s.manager?false:!quote.affordable;
  button.classList.toggle('managed',type==='manager'&&s.manager);
  button.title=type==='manager'&&s.manager?'Open manager office':`${type==='upgrade'?'Production':type==='fleet'?'Vehicles':type==='storage'?'Storage':'Manager'} · ${money(quote.cost)}`;
 }
 row.querySelectorAll('[data-quantity]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.quantity===quantity)));
}
{const html=planningHTML();if(html!==lastPlanningHTML){const panel=$('#planning-panel'),scroll=panel.scrollTop,pageX=window.scrollX,pageY=window.scrollY,active=document.activeElement,focusAction=panel.contains(active)?active.dataset.action:null,focusId=panel.contains(active)?active.dataset.id:null;panel.innerHTML=html;lastPlanningHTML=html;panel.scrollTop=scroll;if(focusAction){const replacement=Array.from(panel.querySelectorAll('[data-action]')).find(b=>b.dataset.action===focusAction&&b.dataset.id===focusId);if(replacement&&!replacement.disabled)replacement.focus({preventScroll:true});}if(window.scrollX!==pageX||window.scrollY!==pageY)window.scrollTo({left:pageX,top:pageY,behavior:'instant'});}}refreshBusinessDialogs();$('#contract-dot').style.display=CONTRACTS.some(c=>{const s=game.contractStatus(c.id);return s.complete&&!s.claimed;})?'block':'none';const prestige=game.prestigeInfo();$('#prestige-copy').textContent=prestige.available?`Your next company earns +${prestige.reward*15}% permanent fares. Ready for a fresh horizon?`:prestige.requirement;$('#prestige-button').disabled=!prestige.available;$('#journey-caption').textContent=focused?ROUTES.find(r=>r.id===focused)?.cargo.toUpperCase()+' IN MOTION'+(pinned?' / CAMERA PINNED':' / AUTO TOUR'):'';$('#quality-select').value=state.settings.quality;$('#sound-button').textContent=state.settings.sound?'On':'Off';const persisted=game.persistenceAvailable!==false;$('#save-detail').textContent=persisted?'Last saved '+new Date(state.lastSaved).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · Saved locally on this device':'Browser storage unavailable. Export a backup to keep your company.';$('#save-status').textContent=persisted?'Progress saved on this device':'Saving unavailable · Export a backup';}
function openDialog(id){$(id).showModal();}
document.addEventListener('click',event=>{const quantityButton=event.target.closest('[data-quantity]');if(quantityButton){quantity=quantityButton.dataset.quantity;render(true);return;}const info=event.target.closest('[data-info]');if(info){infoRoute=info.dataset.info;refreshBusinessDialogs();openDialog('#route-dialog');return;}const action=event.target.closest('[data-action]');if(action){if(action.dataset.action==='manager'&&game.state.routes[action.dataset.id]?.manager){managerRoute=action.dataset.id;refreshBusinessDialogs();openDialog('#manager-dialog');return;}act(action.dataset.action,action.dataset.id);return;}const camera=event.target.closest('[data-camera]');if(camera){const already=pinned&&focused===camera.dataset.camera;scenes.focus(already?null:camera.dataset.camera,!already);return;}const tabButton=event.target.closest('[data-tab]');if(tabButton){tab=tabButton.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});render(true);}if(event.target.closest('.close-dialog'))event.target.closest('dialog').close();});
$('#network-filter').onclick=()=>{listMode=listMode==='region'?'all':'region';render(true);updateCockpit();};
$('#event-claim').onclick=()=>act('claimEvent');
$('#tour-button').onclick=()=>scenes.focus(null,false);$('#hero-pin').onclick=()=>scenes.focus(pinned?null:focused,!pinned);$('#help-button').onclick=()=>openDialog('#guide-dialog');$('#settings-button').onclick=()=>{render(true);openDialog('#settings-dialog');};$('#world-shortcut').onclick=()=>{tab='world';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));render(true);$('.dispatch-board').scrollIntoView({behavior:'smooth',block:'start'});};$('#quality-select').onchange=e=>act('quality',e.target.value);$('#sound-button').onclick=()=>{act('sound');sound();};$('#export-button').onclick=()=>{const blob=new Blob([game.exportSave()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nightshift-company-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Company backup exported.');};$('#import-button').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>100000){toast('Save file is too large.',true);e.target.value='';return;}const result=game.importSave(await file.text());if(!result.ok)toast(result.message,true);else{lastStructure='';scenes.setQuality(game.state.settings.quality);render(true);}e.target.value='';};$('#prestige-button').onclick=()=>{const info=game.prestigeInfo();$('#prestige-confirm-copy').textContent=`Earn ${info.reward} reputation point${info.reward===1?'':'s'} and add ${info.reward*15}% to every future fare.`;openDialog('#prestige-dialog');};$('#confirm-prestige').onclick=()=>{act('prestige');$('#prestige-dialog').close();scenes.focus(null,false);};
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
game.subscribe(event=>{if(event.type==='work'){render(true);return;}if(event.type==='seasonTap'){render(true);seasonCoinFeedback(event.earned);return;}if(event.type==='delivery'){if(game.state.settings.sound&&event.id===focused)sound();return;}if(event.message)toast(event.message,event.type==='warning');render(true);});
let lastTime=performance.now(),hiddenAt=0;
function frame(now){if(!document.hidden&&!hiddenAt){game.tick(Math.min(1,(now-lastTime)/1000));renderClock++;if(renderClock%12===0)render();}lastTime=now;requestAnimationFrame(frame);}
function suspendSimulation(){if(hiddenAt)return;hiddenAt=Date.now();game.save();}
function resumeSimulation(){if(document.hidden)return;const awayStart=hiddenAt;hiddenAt=0;if(awayStart){const cap=game.state.research.includes('nightshift')?28800:14400;game.resumeAway?.(Math.min(cap,Math.max(0,(Date.now()-awayStart)/1000)));}lastTime=performance.now();render(true);}
document.addEventListener('visibilitychange',()=>document.hidden?suspendSimulation():resumeSimulation());
window.addEventListener('pagehide',suspendSimulation);
window.addEventListener('pageshow',resumeSimulation);
document.addEventListener('freeze',suspendSimulation);
document.addEventListener('resume',resumeSimulation);
window.addEventListener('resize',()=>scenes.resize());
scenes.setQuality(game.state.settings.quality);render(true);requestAnimationFrame(frame);
if(game.offlineReport.cash>0)setTimeout(()=>toast(`Welcome back. Your managers completed ${count(game.offlineReport.deliveries)} deliveries and earned ${money(game.offlineReport.cash)} while you were away.`),1000);
if(game.persistenceAvailable===false)setTimeout(()=>toast('Browser saving is unavailable. Export your company backup from Settings.',true),1200);

// The cockpit stays outside the scrolling list. Its height follows scroll directly,
// without a transition or a second animation clock that could trail the scenes.
const operationsScroll=$('#operations-scroll');
function updateCockpit(){
 const portrait=matchMedia('(max-width:580px)').matches;
 const active=Array.from(document.querySelectorAll('.route-card')).filter(row=>game.state.routes[row.dataset.route]?.unlocked).length;
 const full=portrait?Math.min(230,innerHeight*.29):350;
 const compact=portrait?(active>=3?118:156):220;
 const progress=Math.min(1,operationsScroll.scrollTop/120);
 document.documentElement.style.setProperty('--hero-height',`${full+(compact-full)*progress}px`);
 document.documentElement.style.setProperty('--collapse-offset',`${Math.min(120,operationsScroll.scrollTop)}px`);
 document.body.classList.toggle('cockpit-compact',progress>.5);
}
operationsScroll.addEventListener('scroll',updateCockpit,{passive:true});
window.addEventListener('resize',updateCockpit);
game.subscribe(event=>{if(event.type!=='delivery')updateCockpit();});
updateCockpit();

createTapInteraction({element:$('.hero-panel'),earn:()=>game.action('work'),onTap:({x,y,combo})=>{scenes.celebrateTap?.(x,y);sound();$('#tap-hint').classList.add('tapped');if(combo>1){$('#tap-hint').dataset.combo=combo.toFixed(1)+'× momentum';}else delete $('#tap-hint').dataset.combo;}});
function fleetHTML(){
 const owned=ROUTES.filter(r=>game.state.routes[r.id].unlocked);
 if(!owned.length)return toolsHTML('character',2)+'<p class="panel-intro">Your first company begins with a tap. Earn $60 in the main scene, buy Golden Harvest, then choose how its fleet runs.</p>';
 return toolsHTML('character',2)+'<p class="panel-intro">Faster runs open regions sooner. Heavy loads grow your treasury. Changes begin with the next departure.</p>'+owned.map(r=>{const s=game.state.routes[r.id],info=game.stats(r.id);return `<article class="fleet-plan"><div class="fleet-plan-heading"><h3>${r.name}</h3><span>${info.masteryLevel?'★'.repeat(info.masteryLevel):'NEW FLEET'}</span></div><div class="policy-options">${POLICIES.map(p=>`<button data-action="policy" data-id="${r.id}:${p.id}" aria-pressed="${(s.queuedPolicy||s.policy)===p.id}" title="${p.description}">${p.name}<small>${p.id==='express'?'−20% time · −15% fare':p.id==='heavy'?'+30% time · +60% fare':'Balanced journeys'}</small></button>`).join('')}</div><p class="policy-note">${s.queuedPolicy?`Next departure: ${POLICIES.find(p=>p.id===s.queuedPolicy)?.name}`:`Running ${POLICIES.find(p=>p.id===s.policy)?.name||'Steady'} · ${Math.round(info.duration)}s per journey`}</p><div class="mastery-heading"><span>Route mastery · +${Math.round((info.masteryBonus||0)*100)}% fares</span><span>${info.nextMastery?count(s.deliveries)+' / '+count(info.nextMastery):'Mastered'}</span></div><div class="progress-track"><span style="width:${Math.min(100,(info.masteryProgress||0)*100)}%"></span></div></article>`;}).join('');
}

function purchaseQuote(type,id){
 if(game.quote)return game.quote(type,id,type==='manager'?1:quantity==='max'?'max':Number(quantity));
 const info=game.stats(id),s=game.state.routes[id],cost=info[type+'Cost']||0;
 return {cost,count:1,affordable:game.state.cash>=cost&&!(type==='upgrade'&&s.level>=200)&&!(type==='fleet'&&s.fleet>=30),maxed:false};
}
function toolsHTML(target,slots){
 const inventory=game.state.inventory||[],equipment=game.state.equipment||{character:[],businesses:{},managers:{}};
 const [kind,id]=target.split(':'),attached=kind==='character'?equipment.character||[]:kind==='business'?equipment.businesses?.[id]||[]:equipment.managers?.[id]||[];
 const allowed=ITEMS.filter(item=>item.slot===kind&&inventory.includes(item.id));
 return `<div class="tool-heading"><h3>${kind==='manager'?'Manager tools':kind==='business'?'Business tools':'Personal tools'}</h3><span>${attached.length} / ${slots} slots</span></div>${!allowed.length?'<p class="fine-print">Earn permanent tools from season milestones. Each tool can be attached to one place at a time.</p>':allowed.map(item=>{const owned=attached.includes(item.id),used=(equipment.character||[]).includes(item.id)||Object.values(equipment.businesses||{}).some(a=>a.includes(item.id))||Object.values(equipment.managers||{}).some(a=>a.includes(item.id));return `<article class="tool-item"><div><strong>${item.name}</strong><p>${item.description}</p></div><button data-action="${owned||used?'detach':'equip'}" data-id="${owned||used?item.id:item.id+'|'+target}" ${!owned&&!used&&attached.length>=slots?'disabled':''}>${owned?'Detach':used?'Detach elsewhere':'Attach'}</button></article>`;}).join('')}`;
}
function routeInfoHTML(id){
 const route=ROUTES.find(r=>r.id===id),s=game.state.routes[id],info=game.stats(id);
 if(!s.unlocked)return `<p>${route.from} → ${route.to}</p><p>Start moving ${route.cargo.toLowerCase()} with this business. Tap the main scene to raise your first capital.</p><button class="primary" data-action="unlockRoute" data-id="${id}" ${game.state.cash<route.unlockCost?'disabled':''}>Open business · ${money(route.unlockCost)}</button>`;
 return `<p class="route-endpoints">${route.from} → ${route.to}</p><div class="business-stats"><div><span>Income / second</span><strong>${money(info.income)}</strong></div><div><span>Next delivery</span><strong>${money(info.payout)}</strong></div><div><span>Production</span><strong>Level ${info.productionLevel||s.level}</strong></div><div><span>Storage</span><strong>Level ${info.storageLevel??s.storageLevel??0}</strong></div><div><span>Vehicles</span><strong>${s.fleet} / 30</strong></div><div><span>Deliveries</span><strong>${count(s.deliveries)}</strong></div><div><span>Cargo capacity</span><strong>${(info.capacity||0).toFixed(1)}</strong></div><div><span>Production rate</span><strong>${(info.productionRate||0).toFixed(2)} / sec</strong></div><div><span>Cargo stock</span><strong>${Math.round((info.stockRatio||0)*100)}%</strong></div><div><span>Manager</span><strong>${s.manager?'Level '+(info.managerLevel||s.managerLevel||1):'Not hired'}</strong></div></div><p class="fine-print">${Math.round(info.duration)}s journey · ${Math.round(info.automaticRate*100)}% automatic fare · +${Math.round((info.masteryBonus||0)*100)}% route mastery fares</p><button class="primary" data-action="dispatch" data-id="${id}" ${!info.dispatchReady?'disabled':''}>Dispatch · +30% journey</button><div class="dialog-section"><h3>Dispatch policy</h3><div class="policy-options">${POLICIES.map(p=>`<button data-action="policy" data-id="${id}:${p.id}" aria-pressed="${(s.queuedPolicy||s.policy)===p.id}" title="${p.description}">${p.name}<small>${p.description}</small></button>`).join('')}</div><p class="fine-print">Policy changes take effect on the next departure.</p></div><div class="dialog-section">${toolsHTML('business:'+id,2)}</div>`;
}
function managerHTML(id){
 const route=ROUTES.find(r=>r.id===id),s=game.state.routes[id],info=game.stats(id);if(!s.manager)return `<p>This business has no manager yet. Hire one to collect full fares and continue earning while away.</p><button class="primary" data-action="manager" data-id="${id}" ${game.state.cash<info.managerCost?'disabled':''}>Hire manager · ${money(info.managerCost)}</button>`;const level=info.managerLevel||s.managerLevel||1,slots=info.managerSlots||1,cost=info.managerUpgradeCost||info.managerCost;
 return `<div class="manager-profile"><span class="manager-avatar">🕴</span><div><h3>${route.name} manager</h3><p>Level ${level} / 5 · ${slots} tool slot${slots===1?'':'s'}</p></div></div><p>Collect full fares automatically and earn while away. Develop this manager to increase efficiency and unlock more tool slots at levels 3 and 5.</p><button class="primary" data-action="managerUpgrade" data-id="${id}" ${level>=5||game.state.cash<cost?'disabled':''}>${level>=5?'Fully developed':'Upgrade manager · '+money(cost)}</button><div class="dialog-section">${toolsHTML('manager:'+id,slots)}</div>`;
}
function replacePreservingFocus(element,html){
 if(element.dataset.html===html)return;
 const active=document.activeElement,action=element.contains(active)?active.dataset.action:null,id=element.contains(active)?active.dataset.id:null,scroll=element.closest('dialog')?.scrollTop||0;
 element.innerHTML=html;element.dataset.html=html;
 if(action){const replacement=Array.from(element.querySelectorAll('[data-action]')).find(b=>b.dataset.action===action&&b.dataset.id===id);if(replacement&&!replacement.disabled)replacement.focus({preventScroll:true});}
 if(element.closest('dialog'))element.closest('dialog').scrollTop=scroll;
}
function refreshBusinessDialogs(){
 if(infoRoute){$('#route-dialog-title').textContent=ROUTES.find(r=>r.id===infoRoute).name;replacePreservingFocus($('#route-dialog-content'),routeInfoHTML(infoRoute));}
 if(managerRoute){$('#manager-dialog-title').textContent='Manager office';replacePreservingFocus($('#manager-dialog-content'),managerHTML(managerRoute));}
}
function seasonHTML(){
 const info=game.seasonInfo?.()||{},run=game.state.season?.run;
 const calendar=info.startsAt&&info.endsAt?new Date(info.startsAt).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' – '+new Date(info.endsAt).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})+' UTC':'Oct 15 – Nov 2 UTC';
 const head=`<div class="season-header"><span class="eyebrow">SPECIAL OPERATIONS / 8 MINUTES</span><h3>${info.name||'Midnight Harvest'}</h3><p>A separate seasonal company. Grow three special businesses before the shift ends and bring permanent rewards back to your main network.</p><span class="season-calendar">${info.active?'SEASON LIVE':'ANNUAL SEASON'} · ${calendar}</span></div>`;
 if(!run)return head+`<p class="fine-print">${info.active?'The seasonal window is open.':info.schedule||'Practice is always available.'} Rewards can be collected once, including in practice.</p><button class="primary" data-action="seasonStart">Start ${info.active?'season':'practice'} shift ↗</button>`+seasonRewardsHTML(null);
 return head+`<div class="season-score"><div><span>Time left</span><strong>${Math.floor(run.remaining/60)}:${String(Math.floor(run.remaining%60)).padStart(2,'0')}</strong></div><div><span>Shift coins</span><strong>${count(run.coins)}</strong></div></div><button class="primary season-tap" data-action="seasonTap" ${run.remaining<=0?'disabled':''}>✦ Work the seasonal shift</button>`+SEASON_BUSINESSES.map((b,i)=>{const s=run.businesses[b.id],stats=game.seasonStats(b.id),previous=i===0||run.businesses[SEASON_BUSINESSES[i-1].id].unlocked;return `<article class="season-business"><span class="season-business-icon">${b.icon||({pumpkins:'🎃',candy:'🍬',ghost:'👻'}[b.id])||'✦'}</span><div><h3>${b.name}</h3><p>${s.unlocked?'Level '+s.level+' · '+count(stats.income)+' coins / sec':b.description||'Open a seasonal business'}</p></div><button data-action="${s.unlocked?'seasonUpgrade':'seasonUnlock'}" data-id="${b.id}" ${run.remaining<=0||!previous||(s.unlocked&&s.level>=50)||run.coins<(s.unlocked?stats.upgradeCost:b.unlockCost)?'disabled':''}>${s.unlocked?'↑ '+count(stats.upgradeCost):'Open '+count(b.unlockCost)}</button>${s.unlocked?`<div class="progress-track"><span style="width:${Math.min(100,s.progress*100)}%"></span></div>`:''}</article>`;}).join('')+seasonRewardsHTML(run)+(run.remaining<=0?'<button class="secondary" data-action="seasonStart">Start another practice shift ↗</button>':'');
}
function seasonRewardsHTML(run){return `<div class="dialog-section"><h3>Permanent milestones</h3>${SEASON_MILESTONES.map(m=>{const earned=run?.totalEarned||0,claimed=game.state.season?.claimedRewards?.includes(m.id),complete=earned>=m.target;return `<article class="season-milestone"><h4>${m.name}</h4><p>${m.description||'Earn '+count(m.target)+' seasonal coins.'}</p><p class="season-reward-detail">${ITEMS.find(item=>item.id===m.item)?.name||'Permanent keepsake'} · ${ITEMS.find(item=>item.id===m.item)?.description||'A lasting company advantage'}</p><div class="contract-progress"><span>${count(Math.min(earned,m.target))} / ${count(m.target)}</span><span>${claimed?'✓ Permanent reward earned':''}</span></div><div class="progress-track"><span style="width:${Math.min(100,earned/m.target*100)}%"></span></div>${!claimed?`<button data-action="seasonClaim" data-id="${m.id}" ${!complete?'disabled':''}>${complete?'Collect permanent reward':'Keep growing'}</button>`:''}</article>`;}).join('')}</div>`;}

function seasonCoinFeedback(earned){
 const button=document.querySelector('.season-tap');if(!button||!Number.isFinite(earned))return;
 const rect=button.getBoundingClientRect(),coin=document.createElement('span');coin.className='season-coin';coin.textContent='+'+(earned<10?earned.toFixed(1):count(earned))+' coins';coin.style.left=(rect.left+rect.width/2)+'px';coin.style.top=(rect.top+rect.height/2)+'px';document.body.append(coin);setTimeout(()=>coin.remove(),850);
}
