// Interactable station blocks: Fabricator, Reflow Oven, Cache, Sleep Pod. State is keyed by block cell "x,y,z".
import { BLOCKS } from '../../data/blocks.js';
import { Inventory } from '../inventory.js';
import { newOven, ovenTick } from './oven.js';
import { rollLoot } from '../../data/loot.js';

export const STATION_KEYS = { fabricator: 'fabricator', reflow_oven: 'oven', cache: 'cache', sleep_pod: 'pod' };
export const CACHE_SLOTS = 27;
const REACH = 6.5;

export class Stations {
  constructor(ctx, game) {
    this.ctx = ctx;
    this.game = game;
    this.map = new Map();
    this.panel = null;
    this.ui = null;           // lazily imported ./ui.js (DOM only)
  }

  typeOf(mat) { return STATION_KEYS[BLOCKS[mat]?.key] || null; }
  key(x, y, z) { return `${x},${y},${z}`; }

  get(type, x, y, z) {
    const k = this.key(x, y, z);
    let s = this.map.get(k);
    if (!s || s.type !== type) {
      if (type === 'oven') s = newOven();
      else if (type === 'cache') s = this.newCache(x, y, z, !s);
      else return { type };
      this.map.set(k, s);
    }
    return s;
  }

  // A cache with no saved state was generated by the world: it rolls deterministic loot the first time.
  newCache(x, y, z, worldGen = true) {
    const inv = new Inventory(this.game.items, null, CACHE_SLOTS);
    if (worldGen) {
      const seed = this.ctx.world?.seed ?? this.ctx.session?.meta?.seed ?? 'synthwild';
      const biome = this.ctx.world?.biomeAt?.(x + 0.5, z + 0.5) || 'forest';
      for (const l of rollLoot(this.game.items, seed, x, y, z, biome)) {
        inv.slots[l.slot] = { id: l.id, n: l.n, f: 0, ...(l.dur != null ? { dur: l.dur } : {}) };
      }
    }
    return { type: 'cache', inv };
  }

  // Player-placed caches start empty so they never roll loot.
  onPlace(ev) {
    if (this.typeOf(ev?.mat) !== 'cache' || !ev.minSub) return;
    const lo = ev.minSub.map((v) => v >> 2), hi = ev.maxSub.map((v) => (v - 1) >> 2);
    if ((hi[0] - lo[0] + 1) * (hi[1] - lo[1] + 1) * (hi[2] - lo[2] + 1) > 4096) return;
    for (let x = lo[0]; x <= hi[0]; x++) for (let y = lo[1]; y <= hi[1]; y++) for (let z = lo[2]; z <= hi[2]; z++) {
      const k = this.key(x, y, z);
      if (!this.map.has(k) && this.ctx.world?.getCell?.(x, y, z) === ev.mat) this.map.set(k, this.newCache(x, y, z, false));
    }
  }

  // Secondary on a block. hit = world.raycast result. Returns true if a station consumed the action.
  useBlock(hit) {
    if (!hit?.sub) return false;
    const [x, y, z] = hit.sub.map((v) => v >> 2);
    const mat = hit.mat ?? this.ctx.world?.getCell?.(x, y, z);
    const type = this.typeOf(mat);
    if (!type) return false;
    if (this.game.survival.dead) return true;
    if (type === 'pod') { this.sleep(x, y, z); return true; }
    this.open(type, x, y, z);
    return true;
  }

  async open(type, x = null, y = null, z = null) {
    this.close();
    this.ui ||= await import('./ui.js');
    const state = x == null ? { type } : this.get(type, x, y, z);
    const at = x == null ? null : { x, y, z, mat: this.ctx.world?.getCell?.(x, y, z) };
    this.panel = this.ui.openStation(this.ctx, this.game, { type, state, at, onClose: () => { this.panel = null; } });
    this.ctx.bus?.emit?.('ui:open', { panel: 'station:' + type });
    return this.panel;
  }
  openHand() { return this.open('hand'); }
  close() { this.panel?.close(); this.panel = null; }
  get isOpen() { return !!this.panel; }

  // For lane 5's inventory "Fabricate" tab: hand fabrication rendered into their container.
  async mountFab(container, station = null) {
    this.ui ||= await import('./ui.js');
    return this.ui.mountFab(this.ctx, this.game, container, station);
  }

  sleep(x, y, z) {
    const ctx = this.ctx, g = this.game;
    const night = ctx.sky?.isNight && !ctx.settings?.get?.('alwaysDay');
    const spot = { x: x + 0.5, y: y + 1, z: z + 0.5 };
    if (night) {
      const near = g.mobs.list.find((m) => m.def.hostile && !m.dying && m.pos.distanceTo(new ctx.THREE.Vector3(spot.x, spot.y, spot.z)) < 8);
      if (near) { this.say(`You can't sleep: a ${near.def.name} is nearby!`, 'warn'); return false; }
      g.setSpawn(spot);
      ctx.sky?.setTime?.(0.01);
      ctx.bus?.emit?.('player:sleep', { pos: spot, skipped: true });
      this.say('Suit recharged. Good morning! Spawn point set.', 'ok');
      return true;
    }
    g.setSpawn(spot);
    ctx.bus?.emit?.('player:sleep', { pos: spot, skipped: false });
    this.say('Spawn point set. Sleep here at night to skip it.', 'ok');
    return true;
  }

  async say(text, kind = 'info') {
    try { (await import('../../ui/dom.js')).toast(text, { kind }); } catch { console.log('[station]', text); }
  }

  update(dt) {
    for (const s of this.map.values()) if (s.type === 'oven') ovenTick(s, dt, this.game.items);
    const p = this.panel;
    if (!p) return;
    p.update?.(dt);
    const at = p.at, P = this.ctx.player?.pos;
    if (at && (this.ctx.world?.getCell?.(at.x, at.y, at.z) !== at.mat ||
      (P && Math.hypot(P.x - at.x - 0.5, P.y + 1 - at.y - 0.5, P.z - at.z - 0.5) > REACH))) this.close();
  }

  // A station block was broken: spill its contents.
  onBreak(ev) {
    const w = this.ctx.world;
    if (!ev?.minSub) return;
    const lo = ev.minSub.map((v) => v >> 2), hi = ev.maxSub.map((v) => (v - 1) >> 2);
    // An unopened world cache broken as a single block still spills its loot.
    const cacheMat = ev.removed?.find((r) => this.typeOf(r.mat) === 'cache');
    if (cacheMat && lo[0] === hi[0] && lo[1] === hi[1] && lo[2] === hi[2] && !this.map.has(this.key(...lo))) {
      this.spill(this.newCache(...lo, true), lo[0] + 0.5, lo[1] + 0.5, lo[2] + 0.5);
    }
    if (!this.map.size) return;
    for (const [k, s] of [...this.map]) {
      const [x, y, z] = k.split(',').map(Number);
      if (x < lo[0] || x > hi[0] || y < lo[1] || y > hi[1] || z < lo[2] || z > hi[2]) continue;
      const mat = w?.getCell?.(x, y, z);
      if (mat != null && this.typeOf(mat) === s.type) continue;
      this.spill(s, x + 0.5, y + 0.5, z + 0.5);
      this.map.delete(k);
      if (this.panel?.at && this.key(this.panel.at.x, this.panel.at.y, this.panel.at.z) === k) this.close();
    }
  }

  spill(s, x, y, z) {
    const d = this.game.drops;
    const slots = s.type === 'cache' ? s.inv.slots : s.type === 'oven' ? [s.in, s.fuel, s.out] : [];
    for (const sl of slots) {
      if (!sl) continue;
      const n = sl.n + (sl.f || 0) / 64;
      const drop = d.spawnItem(sl.id, n, x, y, z);
      if (drop && sl.dur != null) drop.dur = sl.dur;
    }
  }

  serialize() {
    const out = [];
    for (const [k, s] of this.map) {
      if (s.type === 'cache') out.push({ k, type: 'cache', slots: s.inv.serialize().slots });
      else if (s.type === 'oven') out.push({ k, ...s });
    }
    return out;
  }
  load(list) {
    this.close();
    this.map.clear();
    for (const e of list || []) {
      if (e.type === 'cache') {
        const inv = new Inventory(this.game.items, null, CACHE_SLOTS);
        inv.load({ slots: e.slots, sel: 0 });
        this.map.set(e.k, { type: 'cache', inv });
      } else if (e.type === 'oven') {
        const { k, ...o } = e;
        this.map.set(k, { ...newOven(), ...o });
      }
    }
  }
  clear() { this.close(); this.map.clear(); }
}
