// Interactable station blocks: Fabricator, Reflow Oven, Cache, Sleep Pod. State is keyed by block cell "x,y,z".
import { BLOCKS } from '../../data/blocks.js';
import { Inventory } from '../inventory.js';
import { newOven, ovenTick } from './oven.js';
import { rollLoot } from '../../data/loot.js';

export const STATION_KEYS = { fabricator: 'fabricator', reflow_oven: 'oven', cache: 'cache', sleep_pod: 'pod' };
export const CACHE_SLOTS = 27;
const REACH = 6.5;

export class Stations {
  constructor(ctx, game) {
    this.ctx = ctx;
    this.game = game;
    this.map = new Map();
    this.panel = null;
    this.ui = null;           // lazily imported ./ui.js (DOM only)
  }

  typeOf(mat) { return STATION_KEYS[BLOCKS[mat]?.key] || null; }
  key(x, y, z) { return `${x},${y},${z}`; }

  get(type, x, y, z) {
    const k = this.key(x, y, z);
    let s = this.map.get(k);
    if (!s || s.type !== type) {
      if (type === 'oven') s = newOven();
      else if (type === 'cache') s = this.newCache(x, y, z, !s);
      else return { type };
      this.map.set(k, s);
    }
    return s;
  }

  // A cache with no saved state was generated by the world: it rolls deterministic loot the first time.
  newCache(x, y, z, worldGen = true) {
    const inv = new Inventory(this.game.items, null, CACHE_SLOTS);
    if (worldGen) {
      const seed = this.ctx.world?.seed ?? this.ctx.session?.meta?.seed ?? 'synthwild';
      const biome = this.ctx.world?.biomeAt?.(x + 0.5, z + 0.5) || 'forest';
      const near = this.ctx.world?.structuresNear?.(x + 0.5, z + 0.5, 32) || [];
      const ns = near.sort((a, b) => a.dist - b.dist)[0];
      const st = ns ? (ns.starter ? 'starter' : ns.kind) : null;
      for (const l of rollLoot(this.game.items, seed, x, y, z, biome, CACHE_SLOTS, st)) {
        inv.slots[l.slot] = { id: l.id, n: l.n, f: 0, ...(l.dur != null ? { dur: l.dur } : {}) };
      }
    }
    return { type: 'cache', inv };
  }

  // Sub count of `type` station material in a cell (0..64). Refined cells are scanned.
  subsOf(x, y, z, type) {
    const w = this.ctx.world, v = w?.getCell?.(x, y, z);
    if (v == null) return 0;
    if (v !== -1) return this.typeOf(v) === type ? 64 : 0;
    if (!w.readBox) return 0;
    let n = 0;
    for (const m of w.readBox([x * 4, y * 4, z * 4], [x * 4 + 4, y * 4 + 4, z * 4 + 4]).data) if (this.typeOf(m) === type) n++;
    return n;
  }
  // Is there still a sleep pod under this spawn point? Unloaded cells can't be checked, so they pass.
  podAt(sp) {
    const x = Math.floor(sp.x), y = Math.floor(sp.y - 0.5), z = Math.floor(sp.z), w = this.ctx.world;
    if (!w || (w.isChunkLoaded && !w.isChunkLoaded(x >> 4, z >> 4))) return true;
    return this.subsOf(x, y, z, 'pod') > 0;
  }

  // Player-placed caches start empty so they never roll loot, at any scale.
  onPlace(ev) {
    if (this.typeOf(ev?.mat) !== 'cache' || !ev.minSub) return;
    const lo = ev.minSub.map((v) => v >> 2), hi = ev.maxSub.map((v) => (v - 1) >> 2);
    if ((hi[0] - lo[0] + 1) * (hi[1] - lo[1] + 1) * (hi[2] - lo[2] + 1) > 4096) return;
    for (let x = lo[0]; x <= hi[0]; x++) for (let y = lo[1]; y <= hi[1]; y++) for (let z = lo[2]; z <= hi[2]; z++) {
      const k = this.key(x, y, z);
      if (!this.map.has(k) && this.subsOf(x, y, z, 'cache')) this.map.set(k, this.newCache(x, y, z, false));
    }
  }

  // Secondary on a block. hit = world.raycast result. Returns true if a station consumed the action.
  useBlock(hit) {
    if (!hit?.sub) return false;
    const [x, y, z] = hit.sub.map((v) => v >> 2);
    const mat = hit.mat ?? this.ctx.world?.getCell?.(x, y, z);
    const type = this.typeOf(mat);
    if (!type) return false;
    if (this.game.survival.dead) return true;
    if (type === 'pod') { this.sleep(x, y, z); return true; }
    this.open(type, x, y, z);
    return true;
  }

  async open(type, x = null, y = null, z = null) {
    this.close();
    this.ui ||= await import('./ui.js');
    const state = x == null ? { type } : this.get(type, x, y, z);
    const at = x == null ? null : { x, y, z, mat: this.ctx.world?.getCell?.(x, y, z) };
    this.panel = this.ui.openStation(this.ctx, this.game, { type, state, at, onClose: () => { this.panel = null; } });
    this.ctx.bus?.emit?.('ui:open', { panel: 'station:' + type });
    return this.panel;
  }
  openHand() { return this.open('hand'); }
  close() { this.panel?.close(); this.panel = null; }
  get isOpen() { return !!this.panel; }

  // For lane 5's inventory "Fabricate" tab: hand fabrication rendered into their container.
  async mountFab(container, station = null) {
    this.ui ||= await import('./ui.js');
    return this.ui.mountFab(this.ctx, this.game, container, station);
  }

  sleep(x, y, z) {
    const ctx = this.ctx, g = this.game;
    const night = ctx.sky?.isNight && !ctx.settings?.get?.('alwaysDay');
    const spot = { x: x + 0.5, y: y + 1, z: z + 0.5 };
    if (night) {
      const near = g.mobs.list.find((m) => m.def.hostile && !m.dying && m.pos.distanceTo(new ctx.THREE.Vector3(spot.x, spot.y, spot.z)) < 8);
      if (near) { this.say(`You can't sleep: a ${near.def.name} is nearby!`, 'warn'); return false; }
      g.setSpawn(spot);
      ctx.sky?.setTime?.(0.01);
      ctx.bus?.emit?.('player:sleep', { pos: spot, skipped: true });
      this.say('Suit recharged. Good morning! Spawn point set.', 'ok');
      return true;
    }
    g.setSpawn(spot);
    ctx.bus?.emit?.('player:sleep', { pos: spot, skipped: false });
    this.say('Spawn point set. Sleep here at night to skip it.', 'ok');
    return true;
  }

  async say(text, kind = 'info') {
    try { (await import('../../ui/dom.js')).toast(text, { kind }); } catch { console.log('[station]', text); }
  }

  update(dt) {
    for (const s of this.map.values()) if (s.type === 'oven') ovenTick(s, dt, this.game.items);
    const p = this.panel;
    if (!p) return;
    p.update?.(dt);
    const at = p.at, P = this.ctx.player?.pos;
    if (at && (this.ctx.world?.getCell?.(at.x, at.y, at.z) !== at.mat ||
      (P && Math.hypot(P.x - at.x - 0.5, P.y + 1 - at.y - 0.5, P.z - at.z - 0.5) > REACH))) this.close();
  }

  // A station is one whole cell: the first break that removes any of it removes all of it, and its
  // contents (or a world cache's loot roll) spill exactly once.
  onBreak(ev) {
    if (!ev?.minSub) return;
    const lo = ev.minSub.map((v) => v >> 2), hi = ev.maxSub.map((v) => (v - 1) >> 2);
    const hitTypes = new Set((ev.removed || []).map((r) => this.typeOf(r.mat)).filter(Boolean));
    const single = lo[0] === hi[0] && lo[1] === hi[1] && lo[2] === hi[2];
    const done = new Set();
    const resolve = (x, y, z, type, s) => {
      const k = this.key(x, y, z);
      if (done.has(k)) return;
      done.add(k);
      const left = this.subsOf(x, y, z, type);
      if (left === 64 || (left && !hitTypes.has(type))) return;
      if (s) this.spill(s, x + 0.5, y + 0.5, z + 0.5);
      else if (type === 'cache') this.spill(this.newCache(x, y, z, true), x + 0.5, y + 0.5, z + 0.5);
      this.map.delete(k);
      if (left) this.clearRest(x, y, z, type);
      if (type === 'pod' && this.game.spawnPoint && !this.podAt(this.game.spawnPoint)) this.game.spawnPoint = null;
      if (this.panel?.at && this.key(this.panel.at.x, this.panel.at.y, this.panel.at.z) === k) this.close();
    };
    for (const [k, s] of [...this.map]) {
      const [x, y, z] = k.split(',').map(Number);
      if (x < lo[0] || x > hi[0] || y < lo[1] || y > hi[1] || z < lo[2] || z > hi[2]) continue;
      resolve(x, y, z, s.type, s);
    }
    if (!hitTypes.size) return;
    // Unmapped stations (fabricators, pods, unopened world caches): partial cuts anywhere, whole breaks of a single cell.
    if ((hi[0] - lo[0] + 1) * (hi[1] - lo[1] + 1) * (hi[2] - lo[2] + 1) > 512) return;
    for (let x = lo[0]; x <= hi[0]; x++) for (let y = lo[1]; y <= hi[1]; y++) for (let z = lo[2]; z <= hi[2]; z++) {
      for (const type of hitTypes) {
        if (this.subsOf(x, y, z, type) || single) resolve(x, y, z, type, null);
      }
    }
    if (hitTypes.has('pod') && this.game.spawnPoint && !this.podAt(this.game.spawnPoint)) this.game.spawnPoint = null;
  }

  // Remove what is left of a partly broken station and drop it as items.
  clearRest(x, y, z, type) {
    const w = this.ctx.world;
    if (!w?.readBox || !w.writeBox) return;
    const min = [x * 4, y * 4, z * 4], max = [x * 4 + 4, y * 4 + 4, z * 4 + 4];
    const data = w.readBox(min, max).data.map((m) => (this.typeOf(m) === type ? 0 : 255));
    const r = w.writeBox(min, max, data);
    if (r?.removed?.length) this.game.drops?.onBreak?.({ minSub: min, maxSub: max, removed: r.removed, src: 'station' });
  }

  spill(s, x, y, z) {
    const d = this.game.drops;
    const slots = s.type === 'cache' ? s.inv.slots : s.type === 'oven' ? [s.in, s.fuel, s.out] : [];
    for (const sl of slots) {
      if (!sl) continue;
      const n = sl.n + (sl.f || 0) / 64;
      const drop = d.spawnItem(sl.id, n, x, y, z);
      if (drop && sl.dur != null) drop.dur = sl.dur;
    }
  }

  serialize() {
    const out = [];
    for (const [k, s] of this.map) {
      if (s.type === 'cache') out.push({ k, type: 'cache', slots: s.inv.serialize().slots });
      else if (s.type === 'oven') out.push({ k, ...s });
    }
    return out;
  }
  load(list) {
    this.close();
    this.map.clear();
    for (const e of list || []) {
      if (e.type === 'cache') {
        const inv = new Inventory(this.game.items, null, CACHE_SLOTS);
        inv.load({ slots: e.slots, sel: 0 });
        this.map.set(e.k, { type: 'cache', inv });
      } else if (e.type === 'oven') {
        const { k, ...o } = e;
        this.map.set(k, { ...newOven(), ...o });
      }
    }
  }
  clear() { this.close(); this.map.clear(); }
}
