// Growth Journal goals. Survival is a gentle chain; build mode gets creative goals.
// Each goal is completed by an event matcher (`on: { event: fn(data, j) }`) or a polled check (`poll(j)`).
// j = { has(key), placedMat(ev, key), night, game, ctx, ... } built by journal/index.js.

export const SURVIVAL_GOALS = [
  { id: 'log', title: 'Break a carbon-bark log', hint: 'Hold break on a dark tree trunk. Bare hands work, just slowly.',
    on: { 'block:break': (e, j) => j.removedHas(e, 'carbon_log') } },
  { id: 'fabricator', title: 'Set up your Fabricator', hint: 'Your suit kit has a Fabricator. Place it, then use it to see what you can make. (4 planks make another.)',
    on: { 'block:place': (e, j) => j.placedIs(e, 'fabricator'), 'item:fabricate': (e) => e.key === 'fabricator' } },
  { id: 'outpost', title: 'Find a Grower Outpost', hint: 'The Growers left an outpost not far from where you woke up. Explore! Its Cache holds supplies.',
    poll: (j) => j.nearStructure(['outpost', 'starter'], 14) },
  { id: 'cutter', title: 'Make a Lattice Cutter', hint: 'Place your Fabricator and use it. A cutter needs planks and rods.',
    poll: (j) => j.hasAny(['lattice_cutter', 'basalt_cutter', 'ferrite_cutter', 'qubit_cutter']) },
  { id: 'till', title: 'Till a grow bed', hint: 'A Seed Scoop turns loam into a grow bed. Seeds sometimes drop from photomoss.',
    on: { 'farm:till': () => true } },
  { id: 'grain', title: 'Harvest Sun Grain', hint: 'Plant Sun Seeds on a grow bed in the light and wait for them to glow gold.',
    poll: (j) => j.has('sun_grain') },
  { id: 'glow', title: 'Light your first night with a Glowbulb', hint: 'Carbon nodule + a rod make Glowbulbs. Place one after dark: your suit charges in its light.',
    on: { 'block:place': (e, j) => j.dusk() && j.placedIs(e, 'glowbulb') } },
  { id: 'sleep', title: 'Sleep in a Sleep Pod', hint: 'Fibre Mesh (from bulls) and planks make a Sleep Pod. Sleep at night to skip it.',
    on: { 'player:sleep': (e) => e.skipped } },
  { id: 'bread', title: 'Bake Sun Bread', hint: 'Three Sun Grain hand-fabricate into Sun Bread: the best food around.',
    on: { 'item:fabricate': (e) => e.key === 'sun_bread' } },
  { id: 'ferrite', title: 'Find ferrite', hint: 'Dig down with a Basalt Cutter. Ferrite ore has rusty orange flecks.',
    poll: (j) => j.has('ore_ferrite') || j.has('ferrite_ingot') },
  { id: 'smelt', title: 'Smelt ferrite in a Reflow Oven', hint: 'Fabricate an oven from fractured matrix, then add ore and carbon as fuel.',
    poll: (j) => j.has('ferrite_ingot') },
  { id: 'shelter', title: 'Build a shelter', hint: 'Walls, a roof and a Glowbulb inside. Stand in it: no sky, but bright.',
    poll: (j) => j.inShelter() },
  { id: 'qubit', title: 'Mine a Qubit Crystal', hint: 'Deep down, below y 16, with a Ferrite Cutter. They glow cyan.',
    poll: (j) => j.has('qubit_crystal') },
  { id: 'qubittool', title: 'Fabricate a qubit tool', hint: 'Three crystals and two rods at a Fabricator. The best tools there are!',
    poll: (j) => j.hasAny(['qubit_cutter', 'qubit_saw', 'qubit_scoop', 'qubit_blade']) },
];

export const BUILD_GOALS = [
  { id: 'b_place', title: 'Place a block', hint: 'Every block is in your hotbar. Use place on any surface.',
    on: { 'block:place': (e) => e.mat > 0 } },
  { id: 'b_fill', title: 'Fill a volume', hint: 'Drag out a box (two fingers, or hold place and drag), then confirm.',
    on: { 'block:place': (e, j) => e.mode === 'fill' && j.boxCells(e) > 1 } },
  { id: 'b_hollow', title: 'Make a hollow box', hint: 'Switch the brush mode to Hollow, then drag a volume.',
    on: { 'block:place': (e) => e.mode === 'hollow' } },
  { id: 'b_shell', title: 'Try Shell mode', hint: 'Shell only writes the walls and leaves the inside alone.',
    on: { 'block:place': (e) => e.mode === 'shell' } },
  { id: 'b_replace', title: 'Try Replace mode', hint: 'Replace swaps every block in the box for your block.',
    on: { 'block:place': (e) => e.mode === 'replace' } },
  { id: 'b_tiny', title: 'Place a tiny ¼ block', hint: 'Pinch (or scroll) the scale down to ¼ for fine detail.',
    on: { 'block:place': (e, j) => j.boxSubs(e) === 1 } },
  { id: 'b_big', title: 'Stamp a giant block at scale 8', hint: 'Scale up to 8 and place: one tap, a huge cube.',
    on: { 'block:place': (e, j) => j.boxMin(e) >= 32 } },
  { id: 'b_copy', title: 'Copy something', hint: 'Select a volume and choose Copy.', on: { 'brush:copy': () => true } },
  { id: 'b_paste', title: 'Paste a copy', hint: 'After copying, place the ghost to stamp it down.', on: { 'block:place': (e) => e.mode === 'stamp' } },
  { id: 'b_undo', title: 'Undo a change', hint: 'Oops? Undo puts it back.', on: { 'brush:undo': () => true } },
  { id: 'b_pick', title: 'Pick a block with the eyedropper', hint: 'Use the eyedropper on any block to grab it.', on: { 'brush:pick': (e) => e.found } },
];
