// How to tell lookalikes apart: { pack: { 'idA|idB': text } }. c1_build writes item.differences both ways.
// Only pairs I'm confident about; general field marks, not real-world identification advice.
export default {
  snakes: {
    'coastal-taipan|inland-taipan': 'The coastal taipan lives in tropical coastal Queensland and New Guinea and is longer; the inland taipan lives in remote inland floodplains and its head turns glossy black in winter.',
    'eastern-brown-snake|inland-taipan': 'The eastern brown snake lives along the east coast, often near farms and towns; the inland taipan lives in remote semi-desert and darkens to a black head in winter.',
    'coastal-taipan|eastern-brown-snake': 'The coastal taipan is bigger, with a long pale "coffin-shaped" head and a large eye; the eastern brown snake has a small head barely wider than its neck.',
    'eastern-brown-snake|mulga-snake': 'The mulga snake is much heavier, with a broad head and scales that often look netted with dark edges; the eastern brown snake is slimmer with a small head and plain scales.',
    'dugite|eastern-brown-snake': 'They are close relatives that are told apart mostly by where they live: the dugite in south-western Australia, often with scattered black scales, and the eastern brown snake on the east coast.',
    'mulga-snake|red-bellied-black-snake': 'The red-bellied black snake is glossy black above with a red or pink belly; the mulga snake is brown to copper, with a cream or yellowish belly.',
    'copperhead|lowlands-copperhead': 'They are unrelated and live on different continents: the American copperhead is a pit viper with hourglass bands; the lowlands copperhead of south-eastern Australia is an elapid with no bold bands.',
    'keelback|rough-scaled-snake': 'Both have keeled scales; the harmless keelback has a small loreal scale between nostril and eye, which the venomous rough-scaled snake (an elapid) lacks. Experts often need a close look, so treat both with care.',
    'banded-krait|bandy-bandy': 'The banded krait of Asia has broad yellow and black bands and a ridged back; the small Australian bandy-bandy has black and white rings.',
    'carpet-python|diamond-python': 'The diamond python is a subspecies of the carpet python: mostly black with cream spots in rosettes, found around Sydney and Victoria; most other carpet pythons have brown blotches.',
    'black-headed-python|woma': 'The black-headed python has a glossy jet-black head and neck; the woma is the same shape but its head is pale, with dark patches only above the eyes.',
    'childrens-python|spotted-python': 'Both are small Antaresia pythons; the spotted python has bold dark blotches on a pale body, while the children\'s python is plainer brown with faint blotches.',
    'emerald-tree-boa|green-tree-python': 'They look almost identical; the emerald tree boa lives in South America and has white zig-zag marks, while the green tree python lives in New Guinea and Cape York and often has a white stripe or scattered white scales.',
    'beaked-sea-snake|yellow-bellied-sea-snake': 'The yellow-bellied sea snake has a sharp split between a black back and a yellow belly; the beaked sea snake is greyish with faint bands and a hooked snout.',
    'indian-cobra|king-cobra': 'The king cobra is far longer, with a narrower hood and pale chevron bands; the Indian cobra is smaller, with a wide hood bearing a spectacle mark.',
    'indian-cobra|monocled-cobra': 'The mark on the back of the hood tells them apart: a pair of "spectacles" on the Indian cobra, a single ring on the monocled cobra.',
    'banded-krait|common-krait': 'The banded krait has broad yellow and black bands; the common krait is glossy black with thin white crossbands.',
    'russells-viper|saw-scaled-viper': 'Russell\'s viper is much bigger, with three rows of dark chain-like spots; the small saw-scaled viper is sandy with pale zig-zag marks and makes a sizzling sound with its scales.',
    'burmese-python|reticulated-python': 'The reticulated python has a net-like pattern and orange eyes; the Burmese python has big dark blotches like giraffe patches and an arrow-shaped mark on its head.',
    'green-anaconda|reticulated-python': 'The green anaconda is olive with round black spots and lives in South American water; the reticulated python has a net-like pattern and lives in South-East Asia.',
    'african-rock-python|burmese-python': 'They look alike but live on different continents: the African rock python in Africa south of the Sahara, the Burmese python in South-East Asia (and invasive in Florida).',
    'black-mamba|eastern-green-mamba': 'The eastern green mamba is bright green; the black mamba is grey to olive-brown and is named for the black inside of its mouth.',
    'boomslang|eastern-green-mamba': 'The boomslang has very large eyes and a short, egg-shaped head; the green mamba has a long, coffin-shaped head and smaller eyes. Boomslangs can also be brown or black.',
    'gaboon-viper|puff-adder': 'The Gaboon viper lives in rainforest and has a pale head with a dark line and leafy geometric patterns; the puff adder lives in grassland and has neat pale chevrons.',
    'gaboon-viper|rhinoceros-viper': 'The rhinoceros viper has two or three pairs of horn-like scales on its nose and blue and green colours; the Gaboon viper has only small nose horns and browner colours.',
    'horned-viper|sidewinder': 'Both have horn-like scales over the eyes and move by sidewinding; the horned viper lives in the Sahara and Arabia, the sidewinder is a rattlesnake of North American deserts with a rattle on its tail.',
    'eastern-diamondback-rattlesnake|western-diamondback-rattlesnake': 'The western diamondback has a black-and-white ringed "coon tail" and lives in the south-west USA and Mexico; the eastern diamondback has cream-edged diamonds, a brown tail and lives in the south-east USA.',
    'copperhead|cottonmouth': 'The copperhead is lighter, with sharp hourglass bands; the cottonmouth is darker and thicker, swims high in the water and gapes to show a white mouth.',
    'eastern-coral-snake|milk-snake': 'In US coral snakes the red bands touch yellow bands and the snout is black; in milk snakes red touches black. The rhyme does not work outside the USA.',
    'eastern-coral-snake|scarlet-kingsnake': 'The scarlet kingsnake has a red snout and its red bands touch black; the coral snake has a black snout and its red bands touch yellow.',
    'milk-snake|scarlet-kingsnake': 'Both are harmless mimics; the scarlet kingsnake is smaller with a red snout, while the milk snake is bigger and often has blotches rather than complete rings.',
    'gopher-snake|western-diamondback-rattlesnake': 'The gopher snake has a narrow head, round pupils and no rattle, though it hisses and shakes its tail; the rattlesnake has a wide triangular head, vertical pupils and a rattle.',
    'common-european-adder|smooth-snake': 'The adder has a bold zig-zag down its back and red eyes with vertical pupils; the smooth snake has rows of small dark spots, round pupils and smooth scales.',
    'common-european-adder|grass-snake': 'The grass snake is longer and greener, with a yellow collar and round pupils; the adder is shorter and stockier, with a zig-zag stripe and vertical pupils.',
    'banded-krait|banded-sea-krait': 'The banded sea krait is blue-grey and black with a yellow lip and a paddle tail and lives on reefs; the banded krait is yellow and black and lives on land.',
  },
  spiders: {
    'sydney-funnel-web-spider|trapdoor-spider': 'The funnel-web is glossy black with a shiny head and lives in silk-lined burrows with trip-lines; trapdoor spiders are usually brown and duller, and many close their burrows with a lid.',
    'eastern-mouse-spider|sydney-funnel-web-spider': 'The mouse spider has a very high, domed head with huge jaws, and males often have a blue body; the funnel-web has a flatter, glossy head and long spinnerets at the back.',
    'black-widow|redback-spider': 'Both are widow spiders; the redback has a red stripe on its back, while the black widow usually has a red hourglass underneath and no stripe on top. They live on different continents.',
    'false-widow-spider|redback-spider': 'The false widow is brown with a cream skull-like pattern; the redback is glossy black with a red stripe.',
    'huntsman-spider|wolf-spider': 'Huntsmen are flat, with legs that spread sideways like a crab and live on walls and bark; wolf spiders are stockier, hold their legs under the body and hunt on the ground.',
    'australian-golden-orb-weaver|european-garden-spider': 'The golden orb-weaver is long and slender with banded, tufted legs and golden silk; the garden spider has a round abdomen with a white cross and makes white webs.',
    'st-andrews-cross-spider|wasp-spider': 'Both make zig-zag silk bands; the St Andrew\'s cross spider is Australian and arranges them in an X, while the European wasp spider has bold yellow and black stripes and a single vertical band.',
    'black-house-spider|redback-spider': 'The black house spider is dark brown-black with no red stripe and builds lacy funnel webs on buildings; the redback has a red stripe and builds messy tangled webs.',
    'black-widow|brown-widow': 'The brown widow is paler brown with an orange hourglass and spiky egg sacs; the black widow is glossy black with a red hourglass and smooth egg sacs.',
    'black-widow|false-widow-spider': 'The false widow is brown with cream markings and no red hourglass; the black widow is glossy black with a red hourglass underneath.',
    'goliath-birdeater|mexican-red-knee-tarantula': 'The goliath birdeater is huge and plain brown; the Mexican red-knee is smaller and black with orange bands at its leg joints.',
    'chilean-rose-tarantula|mexican-red-knee-tarantula': 'The red-knee has bright orange leg bands; the Chilean rose is plainer grey-brown with a pinkish sheen.',
    'wasp-spider|yellow-garden-spider': 'The wasp spider has many thin yellow and black stripes; the yellow garden spider is larger with big yellow patches on black. They live on different continents.',
    'bold-jumping-spider|zebra-jumping-spider': 'The zebra jumping spider is small with black and white stripes; the bold jumping spider is bigger, fuzzy black with white spots and green-blue jaws.',
    'bold-jumping-spider|regal-jumping-spider': 'They are close relatives; regal jumping spiders are larger and females are often orange or grey, while bold jumping spiders are black with a white triangle and spots.',
    'giant-house-spider|hobo-spider': 'They are very hard to tell apart by eye; the giant house spider is usually larger and longer-legged, while the hobo spider has a clearer herringbone pattern. Experts check the reproductive parts.',
    'gooty-sapphire-tarantula|indian-ornamental-tarantula': 'The Gooty sapphire is metallic blue all over; the Indian ornamental is grey, black and white with yellow under its front legs.',
    'jumping-spider|zebra-jumping-spider': 'The zebra jumping spider is one kind of jumping spider, with black and white stripes; "jumping spider" covers over 6,000 species.',
    'jumping-spider|peacock-spider': 'Peacock spiders are tiny Australian jumping spiders whose males have a bright fan on the abdomen; most other jumping spiders have no fan.',
    'goliath-birdeater|tarantula': 'The goliath birdeater is one kind of tarantula, the heaviest of all; "tarantula" covers about 1,000 species.',
    'mexican-red-knee-tarantula|tarantula': 'The Mexican red-knee is one kind of tarantula, black with orange leg bands; "tarantula" covers about 1,000 species.',
  },
  jellyfish: {
    'box-jellyfish|moon-jellyfish': 'The box jellyfish has a clear cube-shaped bell with long tentacles from each corner; the moon jellyfish has a flat saucer bell with four pale rings and a fringe of short tentacles.',
    'box-jellyfish|irukandji-jellyfish': 'Both are box jellyfish; the Chironex box jellyfish has a bell up to 30 cm with many tentacles per corner, while the Irukandji is about 1 cm with one tentacle per corner.',
    'bluebottle|portuguese-man-o-war': 'They are close relatives; the Atlantic Portuguese man o\' war is larger with many long tentacles, while the Pacific bluebottle is smaller with usually one long fishing tentacle.',
    'by-the-wind-sailor|portuguese-man-o-war': 'The by-the-wind sailor has a flat oval float with a stiff upright sail and short tentacles; the man o\' war has a balloon-like gas float and long stinging tentacles.',
    'blue-button|bluebottle': 'The blue button is a flat round disc with a ring of short blue tentacles; the bluebottle has a balloon float and a long trailing tentacle.',
    'blue-button|by-the-wind-sailor': 'The blue button is round and flat with no sail; the by-the-wind sailor is oval with a stiff clear sail on top.',
    'red-lionfish|stonefish': 'The lionfish is striped red and white with long feathery fins and swims in the open; the stonefish is lumpy and rock-coloured and lies still on the bottom.',
    'blue-ringed-octopus|geography-cone': 'One is a small octopus that flashes bright blue rings; the other is a sea snail with a patterned cone-shaped shell. Both are deadly and should never be handled.',
    'moon-jellyfish|warty-comb-jelly': 'The comb jelly has no stinging tentacles and shows rows of shimmering rainbow hairs; the moon jellyfish has a saucer bell with four rings and stinging tentacles.',
  },
  mushrooms: {
    'death-cap|field-mushroom': 'The death cap has white gills, a ring and a cup-like sac at the base of its stem, and often a greenish cap; the field mushroom has pink gills that turn brown and no sac. Never rely on this to forage.',
    'death-cap|destroying-angel': 'Both are deadly Amanitas with a ring and a cup at the base; the destroying angel is pure white, while the death cap\'s cap is usually yellow-green to olive.',
    'death-cap|paddy-straw-mushroom': 'Young death caps and paddy straw mushrooms are both egg-shaped in a cup; the paddy straw mushroom has pink gills and no ring, the death cap white gills and a ring. People have died from this mix-up.',
    'destroying-angel|field-mushroom': 'The destroying angel keeps white gills and has a cup at its stem base; the field mushroom\'s gills are pink and then brown, with no cup.',
    'fly-agaric|panther-cap': 'The fly agaric has a red or orange cap with white warts; the panther cap has a brown cap with white warts and a rim around the base of its stem.',
    'field-mushroom|yellow-stainer': 'The yellow stainer turns bright yellow when its stem base is scratched and smells of ink; the field mushroom does not.',
    'button-mushroom|field-mushroom': 'They are close relatives: the button mushroom is farmed and has two spores per gill cell, the field mushroom grows wild in pastures. They look very similar.',
    'golden-chanterelle|jack-o-lantern-mushroom': 'The chanterelle grows from soil and has blunt, forked ridges; the jack-o\'-lantern grows in clusters on wood and has true, sharp gills.',
    'ghost-fungus|jack-o-lantern-mushroom': 'Both glow and are close relatives; the ghost fungus is pale and fan-shaped and lives in Australia, the jack-o\'-lantern is bright orange and lives in Europe.',
    'common-morel|false-morel': 'The true morel has a honeycomb-pitted cap and is hollow inside from cap to stem; the false morel has a wrinkled, brain-like cap and is not hollow.',
    'common-stinkhorn|veiled-lady': 'The veiled lady has a lacy white net hanging from under its cap; the common stinkhorn has no net.',
  },
  bees: {
    'common-wasp|honey-bee': 'The honey bee is furry and golden-brown with a rounded body; the common wasp is shiny, bright yellow and black, with a narrow waist.',
    'honey-bee|marmalade-hoverfly': 'The hoverfly has one pair of wings, big eyes, short stubby antennae and hovers still; the honey bee has two pairs of wings and longer antennae.',
    'buff-tailed-bumblebee|red-tailed-bumblebee': 'The buff-tailed bumblebee has yellow bands and a pale tail; the red-tailed bumblebee is mostly black with an orange-red tail.',
    'buff-tailed-bumblebee|common-carder-bee': 'The common carder bee is smaller and gingery-brown all over; the buff-tailed bumblebee is black with yellow bands and a pale tail.',
    'common-wasp|german-wasp': 'They are almost identical; the German wasp usually has three tiny black dots on its face, while the common wasp has an anchor-shaped mark.',
    'common-wasp|european-hornet': 'The hornet is much bigger, with a brown and yellow body and a reddish head; the common wasp is smaller and bright yellow and black.',
    'common-wasp|marmalade-hoverfly': 'The hoverfly has one pair of wings, huge eyes and short antennae and hovers still; the wasp has two pairs of wings, a narrow waist and longer antennae.',
    'asian-giant-hornet|european-hornet': 'The Asian giant hornet is bigger, with a large orange head and dark-banded abdomen; the European hornet has a reddish-brown head and a mostly yellow abdomen.',
    'asian-hornet|european-hornet': 'The Asian hornet is darker, with a mostly black abdomen, an orange band near the tip and yellow leg tips; the European hornet is bigger with a mostly yellow abdomen.',
    'asian-giant-hornet|asian-hornet': 'The Asian giant hornet is much larger with an orange head and yellow-banded abdomen; the Asian hornet is smaller and mostly dark, with yellow leg tips.',
    'common-wasp|european-paper-wasp': 'The paper wasp is slimmer, dangles its legs in flight and has orange antennae; the common wasp is stockier and builds covered paper nests.',
    'buff-tailed-bumblebee|dark-edged-bee-fly': 'The bee-fly has a long straight beak, one pair of dark-edged wings and hovers to feed; the bumblebee has two pairs of wings and lands on flowers.',
  },
  birds: {
    'emu|southern-cassowary': 'The cassowary has a tall horny casque, a bright blue neck and red wattles and lives in rainforest; the emu is brown and shaggy with no casque and lives in open country.',
    'galah|sulphur-crested-cockatoo': 'The galah is pink and grey with a short pale crest; the sulphur-crested cockatoo is white with a long yellow crest.',
    'crimson-rosella|rainbow-lorikeet': 'The crimson rosella is red with blue cheeks and wings; the rainbow lorikeet has a blue head, orange chest and green back.',
    'budgerigar|cockatiel': 'The budgerigar is small and green and yellow with wavy black bars; the cockatiel is bigger and grey with a yellow face, orange cheeks and a tall crest.',
    'australian-magpie|pied-currawong': 'The currawong has yellow eyes and is mostly black with white patches on wings and tail; the magpie has red-brown eyes and a white nape.',
  },
  body: {
    'large-intestine|small-intestine': 'The small intestine is long (about 6 m) and narrow and absorbs most nutrients; the large intestine is shorter, wider and absorbs water.',
    'femur|humerus': 'The femur is the thigh bone and the longest bone in the body; the humerus is the upper arm bone.',
  },
  cats: {
    'oriental-shorthair|siamese': 'The Siamese has dark points and blue eyes; the Oriental Shorthair has the same build but comes in hundreds of solid colours and patterns, usually with green eyes.',
    'bengal|ocicat': 'The Bengal has wild leopard cat ancestry and often a glittery coat with rosettes; the Ocicat has no wild ancestry and has solid thumbprint spots.',
    'bengal|savannah': 'The Savannah is much taller and leggier, with huge ears, and descends from the serval; the Bengal is medium-sized and descends from the Asian leopard cat.',
    'cornish-rex|devon-rex': 'The Devon Rex has huge low-set ears, an elf-like face and a looser wavy coat; the Cornish Rex has a tight marcel-wave coat and a slim, arched, greyhound-like body.',
    'laperm|selkirk-rex': 'The Selkirk Rex is big and cobby with a thick plush curly coat; the LaPerm is lighter-built with a looser, springy coat.',
  },
  dishes: { 'sashimi|sushi': 'Sushi always includes vinegared rice; sashimi is sliced raw fish served without rice.' },
  flowers: { 'garden-pansy|sweet-violet': 'The pansy has large flowers with a dark "face"; the sweet violet has small purple flowers and a sweet scent.' },
  insects: {
    'monarch-butterfly|painted-lady': 'The monarch is orange with thick black veins; the painted lady is orange-brown with black and white spots near the wingtips.',
    'painted-lady|red-admiral': 'The red admiral is black with a red band and white spots; the painted lady is mostly orange-brown.',
    'old-world-swallowtail|ulysses-butterfly': 'The Old World swallowtail is yellow and black; the Ulysses butterfly is bright metallic blue and black.',
    'blue-morpho|ulysses-butterfly': 'The Ulysses butterfly has tails on its back wings and lives in Queensland and New Guinea; the blue morpho has no tails and lives in Central and South America.',
    'hercules-beetle|stag-beetle': 'The Hercules beetle male has a long horn from its head and thorax; the stag beetle male has huge antler-like jaws.',
    'european-mantis|orchid-mantis': 'The European mantis is green or brown and plain; the orchid mantis is pink and white with petal-shaped legs.',
    'leaf-insect|spiny-leaf-insect': 'The leaf insect is very flat and leaf-shaped; the spiny leaf insect is spiky and curls its tail like a scorpion.',
    'banded-demoiselle|emperor-dragonfly': 'The demoiselle is a damselfly: slim, folds its wings along its body at rest and males have dark wing bands; the emperor is a big dragonfly that rests with wings spread.',
    'green-grocer-cicada|periodical-cicada': 'The green grocer is a big green Australian cicada; the periodical cicada is black with red eyes and lives in the eastern USA.',
  },
  sea: {
    'beluga|narwhal': 'The narwhal male has a long spiral tusk and a mottled grey body; the beluga is all white with no tusk.',
    'big-belly-seahorse|leafy-seadragon': 'The leafy seadragon is covered in leaf-like flaps and cannot curl its tail; the seahorse has a curling tail for gripping and no leafy flaps.',
  },
  space: {
    'alpha-centauri|proxima-centauri': 'Proxima Centauri is a dim red dwarf you need a telescope to see; Alpha Centauri\'s two bright stars shine as one of the brightest points in the southern sky. Proxima belongs to the same system.',
    'andromeda-galaxy|milky-way': 'The Milky Way is our own galaxy, seen as a band across the sky; the Andromeda Galaxy is a separate, larger spiral about 2.5 million light years away.',
  },
};
