import { NOT_ID, INAT, WD } from './_common.mjs';

const f = (kind, stings, social) => ({ kind, stings, social });

export default {
  id: 'bees', title: 'Wasps, bees & hornets', theme: 'animals', icon: '🐝', kids: true, notice: NOT_ID,
  leakExempt: [],
  wikiD1: true, autoTaxo: ['family', 'genus'],
  factsMeta: {
    kind: { type: 'cat', label: 'Kind', values: ['Bee', 'Wasp', 'Hornet', 'Fly'], noClue: true },
    stings: { type: 'bool', label: 'Can sting', yes: 'Can sting', no: 'Cannot sting', clue: v => (v ? 'Females can sting.' : 'It cannot sting.') },
    social: { type: 'bool', label: 'Lives in colonies', yes: 'Lives in a colony', no: 'Lives alone', clue: v => (v ? 'It lives in a colony with a queen.' : 'It lives alone, not in a colony.') },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which insect is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"kind": {"ask": "Is the {lname} a bee, a wasp, a hornet or a fly?", "askReverse": "Which of these is a {lvalue}?", "stmt": "The {lname} is a {lvalue}."}, "stings": {"askBool": "Which of these can sting?", "stmt": "The {lname} can sting."}, "social": {"askBool": "Which of these lives in a colony with a queen?", "stmt": "The {lname} lives in a colony with a queen."}},
  sources: [INAT, WD],
  items: [
    { n: 'Honey bee', alt: ['western honey bee', 'European honey bee', 'honeybee'], sci: 'Apis mellifera', g: 'bee', f: f('Bee', true, true), d: 1, look: ['Common wasp', 'Marmalade hoverfly'],
      b: 'The bee that makes the honey we eat. A hive can hold tens of thousands of bees with one queen.',
      c: ['Workers do a "waggle dance" to show others where flowers are.', 'A worker dies after stinging a person because its sting is barbed.', 'Its wax is used for candles and polish.', 'It lives in hives looked after by beekeepers.', 'It makes a sweet golden food spread on toast.'] },
    { n: 'Buff-tailed bumblebee', alt: ['bumblebee', 'bumble bee'], sci: 'Bombus terrestris', g: 'bee', f: f('Bee', true, true), d: 1, look: ['Red-tailed bumblebee', 'Common carder bee'],
      b: 'A big, fuzzy bee common in Europe. It can fly in cooler weather than most bees by shivering to warm up.',
      c: ['It is used in greenhouses to pollinate tomatoes.', 'It shivers its flight muscles to warm up.', 'Its nests are often underground in old mouse holes.', 'It has a yellow band and a pale tail.', 'It is a big, round, furry bee.'] },
    { n: 'Red-tailed bumblebee', sci: 'Bombus lapidarius', g: 'bee', f: f('Bee', true, true), d: 2, look: ['Buff-tailed bumblebee'],
      b: 'A black bumblebee with a bright orange-red tail, common in European gardens.',
      c: ['It often nests under stones.', 'Males have yellow bands on the face.', 'It is common in British gardens.', 'Females are velvety black.', 'Its tail end is orange-red.'] },
    { n: 'Common carder bee', sci: 'Bombus pascuorum', g: 'bee', f: f('Bee', true, true), d: 3, look: ['Buff-tailed bumblebee'],
      b: 'A small gingery bumblebee that weaves moss into a nest above ground.',
      c: ['It combs moss to build its nest.', 'It nests above ground in long grass.', 'It is one of the last bumblebees still flying in autumn.', 'It is fluffy and ginger-brown all over.', 'It is a common bumblebee in Britain.'] },
    { n: 'Violet carpenter bee', alt: ['carpenter bee'], sci: 'Xylocopa violacea', g: 'bee', f: f('Bee', true, false), d: 2,
      b: 'A large, shiny black bee with purple-tinted wings. It chews tunnels in dead wood to make its nest.',
      c: ['It is one of the largest bees in Europe.', 'It sometimes "robs" nectar by biting a hole in the flower.', 'Its wings shine bluish-purple.', 'It chews nest tunnels in dead wood.', 'It is named after a woodworker.'] },
    { n: 'Leafcutter bee', sci: 'Megachile', g: 'bee', f: f('Bee', true, false), d: 2,
      b: 'A solitary bee that cuts neat circles out of leaves to line its nest cells.',
      c: ['It carries pollen on hairs under its belly.', 'It nests in hollow stems or holes in wood.', 'It lines each egg cell with plant pieces.', 'Gardeners find neat round holes in rose leaves.', 'It snips pieces out of leaves.'] },
    { n: 'Red mason bee', alt: ['mason bee'], sci: 'Osmia bicornis', g: 'bee', f: f('Bee', true, false), d: 2,
      b: 'A gingery solitary bee that nests in holes and seals each cell with mud. It loves bee hotels.',
      c: ['Females have two little horns on the face.', 'It often uses bee hotels.', 'It is an excellent pollinator of fruit trees.', 'It seals its nest cells with mud.', 'It is named after a builder who works with stone.'] },
    { n: 'Blue-banded bee', sci: 'Amegilla cingulata', g: 'bee', f: f('Bee', true, false), d: 2,
      b: 'An Australian bee with shiny blue stripes. It shakes pollen out of flowers by buzzing.',
      c: ['Males sleep clinging to plant stems by their jaws.', 'It "buzz pollinates" tomato flowers.', 'It is native to Australia.', 'It hovers in front of flowers.', 'Its body has shining blue stripes.'] },
    { n: 'Teddy bear bee', sci: 'Amegilla bombiformis', g: 'bee', f: f('Bee', true, false), d: 3,
      b: 'A round, golden-furred Australian bee that looks like a soft toy.',
      c: ['It nests in burrows in soil banks.', 'It buzz pollinates flowers.', 'It lives in eastern Australia.', 'It is covered in golden-brown fur.', 'It is named after a cuddly toy.'] },
    { n: 'Sugarbag bee', alt: ['stingless bee', 'Australian stingless bee'], sci: 'Tetragonula carbonaria', g: 'bee', f: f('Bee', false, true), d: 2,
      b: 'A tiny black Australian bee that cannot sting. Its hives make a small amount of tangy honey.',
      c: ['Its hive is built in a spiral shape.', 'Aboriginal people have collected its honey for thousands of years.', 'It is kept in small boxes in backyards.', 'It is tiny and black.', 'It cannot sting.'] },
    { n: 'Orchid bee', sci: 'Euglossa', g: 'bee', f: f('Bee', true, false), d: 3,
      b: 'Shiny metallic green or blue bees of tropical America. Males collect scents from orchids.',
      c: ['Males collect perfumes from orchids.', 'Their tongues can be longer than their bodies.', 'They live in Central and South American forests.', 'They shine like metal.', 'They are named after a famous flower.'] },
    { n: 'Common wasp', alt: ['yellowjacket', 'wasp'], sci: 'Vespula vulgaris', g: 'wasp', f: f('Wasp', true, true), d: 1, look: ['Honey bee', 'German wasp', 'European hornet', 'Marmalade hoverfly'],
      b: 'The yellow-and-black wasp that turns up at picnics in late summer. It builds paper nests from chewed wood.',
      c: ['Its nest is made of paper from chewed wood.', 'In late summer it hunts for sweet food at picnics.', 'It can sting many times.', 'It feeds insects to its young.', 'It is striped bright yellow and black.'] },
    { n: 'German wasp', alt: ['European wasp'], sci: 'Vespula germanica', g: 'wasp', f: f('Wasp', true, true), d: 2, look: ['Common wasp'],
      b: 'A yellowjacket wasp from Europe that has invaded Australia, New Zealand and the Americas.',
      c: ['It is an invasive pest in Australia and New Zealand.', 'In warm places, nests can survive the winter and grow huge.', 'It is almost identical to the common wasp.', 'Its face has three tiny black dots.', 'It is named after a European country.'] },
    { n: 'European hornet', alt: ['hornet'], sci: 'Vespa crabro', g: 'hornet', f: f('Hornet', true, true), d: 1, look: ['Common wasp', 'Asian giant hornet', 'Asian hornet'],
      b: 'The largest wasp in Europe. It is brown and yellow, and calmer than you might think.',
      c: ['It can fly and hunt at night.', 'It nests in hollow trees.', 'It is calmer than smaller wasps.', 'It is brown and yellow and very large.', 'It is the biggest wasp in Europe.'] },
    { n: 'Asian giant hornet', alt: ['northern giant hornet', 'murder hornet'], sci: 'Vespa mandarinia', g: 'hornet', f: f('Hornet', true, true), d: 1, look: ['European hornet', 'Asian hornet'],
      b: 'The largest wasp in the world, from East Asia. A small group can kill a whole hive of honey bees.',
      c: ['Japanese honey bees cook it to death in a ball of vibrating bees.', 'A few can wipe out a honey bee hive in hours.', 'It was nicknamed the "murder hornet" in the US.', 'Its head is big and orange.', 'It is the biggest wasp in the world.'] },
    { n: 'Asian hornet', alt: ['yellow-legged hornet'], sci: 'Vespa velutina', g: 'hornet', f: f('Hornet', true, true), d: 2, look: ['European hornet', 'Asian giant hornet'],
      b: 'A dark hornet from Asia with yellow legs. It has spread across Europe and hunts honey bees outside their hives.',
      c: ['It arrived in France around 2004 in pottery from China.', 'It hovers outside hives to catch honey bees.', 'Its nests are often high in trees.', 'It is dark with an orange face.', 'Its legs are yellow at the ends.'] },
    { n: 'Bald-faced hornet', sci: 'Dolichovespula maculata', g: 'wasp', f: f('Wasp', true, true), d: 2,
      b: 'A black-and-white wasp of North America that builds big grey paper nests in trees. It is really a yellowjacket, not a true hornet.',
      c: ['It is not a true hornet.', 'Its football-sized paper nests hang in trees.', 'It can squirt venom at eyes.', 'It is black and white, not yellow.', 'Its face is white.'] },
    { n: 'European paper wasp', alt: ['paper wasp'], sci: 'Polistes dominula', g: 'wasp', f: f('Wasp', true, true), d: 2, look: ['Common wasp'],
      b: 'A slim wasp that builds small, open, umbrella-shaped nests under roofs. It dangles its legs in flight.',
      c: ['Its nest hangs from a single stalk.', 'Its nest cells are open, with no paper cover.', 'It lets its legs dangle as it flies.', 'It is yellow and black and slimmer than a yellowjacket.', 'It builds its nest from a material you write on.'] },
    { n: 'Black and yellow mud dauber', alt: ['mud dauber'], sci: 'Sceliphron caementarium', g: 'wasp', f: f('Wasp', true, false), d: 2,
      b: 'A thin-waisted solitary wasp that builds nests of mud and stocks them with paralysed spiders.',
      c: ['It stocks its nest with paralysed spiders.', 'It rarely stings people.', 'Its waist is long and thread-thin.', 'It builds nest cells from wet earth.', 'It smears soil, which is in its name.'] },
    { n: 'Potter wasp', sci: 'Eumenes', g: 'wasp', f: f('Wasp', true, false), d: 3,
      b: 'A small solitary wasp that makes a tiny round pot of mud for each egg, stocked with caterpillars.',
      c: ['It fills each nest with paralysed caterpillars.', 'Its nest has a narrow neck like a jug.', 'Its nest is made of mud.', 'It is black and yellow with a thin waist.', 'Its nest looks like a tiny clay jar.'] },
    { n: 'Tarantula hawk', sci: 'Pepsis', g: 'wasp', f: f('Wasp', true, false), d: 2,
      b: 'A huge blue-black wasp with orange wings that hunts tarantulas. Its sting is one of the most painful of any insect.',
      c: ['Its sting ranks among the most painful in the world.', 'It is the state insect of New Mexico.', 'It lays an egg on a paralysed spider.', 'It has orange wings.', 'It hunts big hairy spiders.'] },
    { n: 'Eastern cicada killer', alt: ['cicada killer'], sci: 'Sphecius speciosus', g: 'wasp', f: f('Wasp', true, false), d: 3,
      b: 'A huge solitary wasp of North America that hunts cicadas and carries them back to its burrow.',
      c: ['It flies with prey heavier than itself.', 'It digs burrows in sandy soil.', 'Males are territorial but cannot sting.', 'It is one of the largest wasps in North America.', 'It hunts loud summer insects.'] },
    { n: 'Velvet ant', alt: ['cow killer'], sci: 'Dasymutilla occidentalis', g: 'wasp', f: f('Wasp', true, false), d: 3,
      b: 'A fuzzy red-and-black wingless insect that looks like an ant but is really a wasp. Its sting is very painful.',
      c: ['It is a wasp, not an ant.', 'Females have no wings.', 'Its sting is so painful it is nicknamed "cow killer".', 'It is covered in red and black fuzz.', 'It is named after a soft fabric and a small insect.'] },
    { n: 'Emerald cockroach wasp', alt: ['jewel wasp'], sci: 'Ampulex compressa', g: 'wasp', f: f('Wasp', true, false), d: 3,
      b: 'A shiny green wasp that stings a cockroach in the brain, then leads it to its burrow like a dog on a lead.',
      c: ['It leads its victim by the antenna.', 'It stings its prey right in the brain.', 'It lays an egg on a living roach.', 'It shines metallic green.', 'It is named after a green gem and a kitchen pest.'] },
    { n: 'Giant ichneumon wasp', sci: 'Megarhyssa', g: 'wasp', f: f('Wasp', false, false), d: 3,
      b: 'A wasp with a hair-thin egg-laying tube longer than its body. It drills into wood to lay eggs on grubs.',
      c: ['It can smell grubs inside a tree.', 'It drills through solid wood.', 'Females have an egg-laying tube longer than their body.', 'Despite its look, it does not sting people.', 'It is a very large, long wasp.'] },
    { n: 'Marmalade hoverfly', alt: ['hoverfly', 'hover fly'], sci: 'Episyrphus balteatus', g: 'fly', f: f('Fly', false, false), d: 1, look: ['Common wasp', 'Honey bee'],
      b: 'A harmless fly dressed up like a wasp. It hovers still in the air and cannot sting.',
      c: ['Its young eat aphids.', 'It has only one pair of wings, unlike wasps.', 'It has short, stubby antennae.', 'It hangs still in the air.', 'It is named after an orange jam.'] },
    { n: 'Dark-edged bee-fly', alt: ['bee-fly', 'bee fly'], sci: 'Bombylius major', g: 'fly', f: f('Fly', false, false), d: 3, look: ['Buff-tailed bumblebee'],
      b: 'A furry fly that looks like a bee, with a long straight beak for drinking nectar. Its young live in bees\' nests.',
      c: ['Its young feed in the nests of solitary bees.', 'It flicks its eggs towards bee nests.', 'It has a long, stiff, straight tongue.', 'It looks like a fluffy round bee.', 'It is really a fly.'] },
  ],
  fakes: ['Crimson mason hornet', 'Glass-winged honey wasp', 'Northern velvet bumblebee hornet', 'Striped thunder bee', 'Silver paper hornet', 'Golden digger hornet'],
  questions: [
    { kind: 'number', prompt: 'How many legs does a bee have?', answer: 6, unit: 'legs', tolerance: 0, explain: 'Bees are insects, and all insects have six legs.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do honey bees make that people eat?', answer: 'Honey', wrong: ['Jam', 'Milk', 'Syrup'], explain: 'They turn flower nectar into honey to feed the hive.', difficulty: 1 },
    { kind: 'tf', prompt: 'A honey bee worker usually dies after stinging a person.', answer: true, explain: 'Its barbed sting stays in our skin and tears away from the bee.', difficulty: 1 },
    { kind: 'tf', prompt: 'Hoverflies can sting.', answer: false, explain: 'Hoverflies are harmless flies that copy wasp colours.', difficulty: 1 },
    { kind: 'mc', prompt: 'What does a honey bee\'s "waggle dance" tell the other bees?', answer: 'Where to find flowers', wrong: ['That the queen is hungry', 'That it is time to sleep', 'That a storm is coming'], explain: 'The angle and length of the dance show direction and distance.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the largest wasp in the world?', answer: 'Asian giant hornet', wrong: ['European hornet', 'Tarantula hawk', 'Common wasp'], explain: 'Queens can be about 5 cm long.', difficulty: 2 },
    { kind: 'mc', prompt: 'How can you tell a hoverfly from a wasp?', answer: 'It has one pair of wings', wrong: ['It has eight legs', 'It has no eyes', 'It is always bigger'], explain: 'Flies have one pair of wings; wasps and bees have two.', difficulty: 2 },
    { kind: 'mc', prompt: 'What do common wasps build their nests from?', answer: 'Chewed wood', wrong: ['Wax', 'Mud', 'Leaves'], explain: 'They mix wood fibres with saliva to make paper.', difficulty: 2 },
    { kind: 'tf', prompt: 'Only female bees and wasps can sting.', answer: true, explain: 'The sting is a modified egg-laying tube, so males have none.', difficulty: 2 },
    { kind: 'mc', prompt: 'In a honey bee hive, which bee lays the eggs?', answer: 'The queen', wrong: ['The drones', 'The workers', 'The guards'], explain: 'One queen can lay over a thousand eggs a day.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do bees collect from flowers?', answer: 'Nectar and pollen', wrong: ['Leaves and twigs', 'Water and mud', 'Seeds and stones'], explain: 'Nectar becomes honey; pollen feeds the young.', difficulty: 1 },
    { kind: 'mc', prompt: 'Where do honey bees live?', answer: 'In a hive', wrong: ['In a web', 'In a burrow', 'In a shell'], explain: 'A hive can hold tens of thousands of bees.', difficulty: 1 },
    { kind: 'tf', prompt: 'Bees help plants make seeds by carrying pollen from flower to flower.', answer: true, explain: 'This is called pollination.', difficulty: 1 },
    { kind: 'mc', prompt: 'What colours are most wasps?', answer: 'Yellow and black', wrong: ['Red and blue', 'Green and white', 'Pink and purple'], explain: 'The bright colours warn that they can sting.', difficulty: 1 },
  ],
};
