import { INAT, WD, COMMONS, STATUS_META, addFacts } from './_common.mjs';

const AU = 'Australia', NZ = 'New Zealand', EU = 'Europe', AF = 'Africa', AS = 'Asia', AM = 'the Americas', NA = 'North America', SA = 'South America', AN = 'Antarctica', WW = 'many parts of the world';
const KINDS = ['Perching bird', 'Parrot', 'Bird of prey', 'Duck, goose or swan', 'Pheasant or fowl', 'Ratite', 'Penguin', 'Hummingbird', 'Kingfisher'];
const f = (region, flightless = false) => ({ region, flightless });

const PACK = {
  id: 'birds', title: 'Birds', theme: 'animals', icon: '🐦', kids: true,
  leakExempt: ['bird'],
  wikiD1: true, autoTaxo: ['family', 'genus'], status: true, audio: true,
  factsMeta: {
    region: { type: 'cat', label: 'Found in', clue: v => `It is found in ${v}.` },
    flightless: { type: 'bool', label: 'Flightless', yes: 'Cannot fly', no: 'Can fly', clue: v => (v ? 'It cannot fly.' : null) },
    status: STATUS_META,
    kind: { type: 'cat', label: 'Kind of bird', values: KINDS, noClue: true },
    massKg: { type: 'num', label: 'Typical adult weight', unit: 'kg', higherLabel: 'Heavier', noClue: true },
  },
  // kind comes from the iNat order (owls count as birds of prey); birds outside these groups have no kind
  taxoFacts: { kind: {
    Passeriformes: 'Perching bird', Psittaciformes: 'Parrot', Accipitriformes: 'Bird of prey', Falconiformes: 'Bird of prey',
    Cathartiformes: 'Bird of prey', Strigiformes: 'Bird of prey', Anatidae: 'Duck, goose or swan', Galliformes: 'Pheasant or fowl',
    Struthioniformes: 'Ratite', Casuariiformes: 'Ratite', Apterygiformes: 'Ratite', Sphenisciformes: 'Penguin',
    Trochilidae: 'Hummingbird', Alcedinidae: 'Kingfisher',
  } },
  wdCheck: { massKg: 'P2067' },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which bird is this?",
  tfImgPrompt: "This bird is {aName}.",
  tpl: {"region": {"ask": "Where does the {lname} live?", "askReverse": "Which of these birds lives in {value}?", "stmt": "The {lname} lives in {value}.", "exclusive": false}, "flightless": {"askBool": "Which of these birds cannot fly?", "stmt": "The {lname} cannot fly."}, "kind": {"ask": "What kind of bird is the {lname}?", "askReverse": "Which of these birds is {aValue}?", "stmt": "The {lname} is {aValue}."}, "massKg": {"askHigh": "Which of these birds is the heaviest?", "askLow": "Which of these birds is the lightest?", "askNumber": "About how much does {name} weigh, in kilograms?", "minRatio": 2}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD, COMMONS],
  items: [
    // ---- Australia & New Zealand ----
    { n: 'Emu', sci: 'Dromaius novaehollandiae', g: 'ratite', f: f(AU, true), d: 1, look: ['Ostrich', 'Southern cassowary'],
      b: 'Australia\'s tallest bird. It cannot fly, but it can run at about 50 km/h.',
      c: ['The father sits on the eggs and raises the chicks.', 'Its eggs are dark green.', 'In 1932, soldiers with machine guns lost a "war" against them.', 'It appears on Australia\'s coat of arms with the kangaroo.', 'It is the second-tallest bird in the world.'] },
    { n: 'Southern cassowary', alt: ['cassowary'], sci: 'Casuarius casuarius', g: 'ratite', f: f(AU, true), d: 1, look: ['Emu', 'Ostrich'],
      b: 'A huge flightless bird of rainforests in north Queensland and New Guinea. It has a tall helmet on its head and a dagger-like claw on each foot.',
      c: ['Its inner toe has a claw up to 12 cm long.', 'It spreads the seeds of many rainforest fruits.', 'The father raises the chicks.', 'Its neck is bright blue with red wattles.', 'It has a tall horny helmet called a casque.'] },
    { n: 'Laughing kookaburra', alt: ['kookaburra'], sci: 'Dacelo novaeguineae', g: 'kingfisher', f: f(AU), d: 1, look: ['Common kingfisher'],
      b: 'A big Australian kingfisher famous for its loud call that sounds like laughter.',
      c: ['It is the largest kingfisher in the world.', 'It eats snakes, lizards and mice.', 'Families call together at dawn and dusk.', 'A famous children\'s song has it sitting in an old gum tree.', 'Its call sounds like someone laughing.'] },
    { n: 'Sulphur-crested cockatoo', sci: 'Cacatua galerita', g: 'parrot', f: f(AU), d: 1, look: ['Galah'],
      b: 'A big, noisy white parrot with a yellow crest. In Sydney, some have learned to open wheelie bins.',
      c: ['Sydney birds have learned to open wheelie bins.', 'It can live for over 70 years in captivity.', 'A flock posts lookouts while the others feed.', 'It screeches very loudly.', 'It is white with a yellow crest.'] },
    { n: 'Galah', alt: ['pink and grey cockatoo', 'rose-breasted cockatoo'], sci: 'Eolophus roseicapilla', g: 'parrot', f: f(AU), d: 1, look: ['Sulphur-crested cockatoo'],
      b: 'A pink-and-grey cockatoo found all over Australia. Its name is also Australian slang for a silly person.',
      c: ['It often hangs upside down from power lines.', 'Its name is slang for a fool in Australia.', 'It is a kind of cockatoo.', 'It has a grey back and wings.', 'Its face and chest are bright pink.'] },
    { n: 'Rainbow lorikeet', sci: 'Trichoglossus moluccanus', g: 'parrot', f: f(AU), d: 1, look: ['Crimson rosella'],
      b: 'A brilliantly coloured parrot with a blue head, green back and orange chest. It drinks nectar with a brush-tipped tongue.',
      c: ['Its tongue has a brush tip for collecting nectar.', 'Flocks roost noisily in city trees at dusk.', 'It is an invasive pest in Perth and New Zealand.', 'It has a blue head and an orange chest.', 'It has many bright colours, like the sky after rain.'] },
    { n: 'Crimson rosella', sci: 'Platycercus elegans', g: 'parrot', f: f(AU), d: 2, look: ['Rainbow lorikeet'],
      b: 'A bright red parrot with blue cheeks and wings, common in forests of south-eastern Australia.',
      c: ['Young birds are mostly green.', 'It is common in the Blue Mountains.', 'It eats seeds and fruit.', 'Its cheeks and wings are blue.', 'It is a deep red colour.'] },
    { n: 'Budgerigar', alt: ['budgie', 'parakeet'], sci: 'Melopsittacus undulatus', g: 'parrot', f: f(AU), d: 1, look: ['Cockatiel'],
      b: 'A small green-and-yellow Australian parrot and one of the most popular pet birds in the world.',
      c: ['Wild ones fly in huge flocks across the outback.', 'Males have a blue patch above the beak.', 'Pet ones come in blue, white and yellow.', 'Some learn to say hundreds of words.', 'It is often kept in a cage as a pet and its name is often shortened.'] },
    { n: 'Cockatiel', sci: 'Nymphicus hollandicus', g: 'parrot', f: f(AU), d: 1, look: ['Budgerigar'],
      b: 'A small grey cockatoo with a yellow face, orange cheeks and a tall crest. It is a very popular pet.',
      c: ['It is the smallest member of the cockatoo family.', 'It can whistle tunes.', 'It lives in the Australian outback.', 'It has round orange cheek patches.', 'It has a tall, wispy crest.'] },
    { n: 'Australian magpie', sci: 'Gymnorhina tibicen', g: 'songbird', f: f(AU), d: 1, look: ['Eurasian magpie', 'Pied currawong'],
      b: 'A black-and-white Australian songbird with a beautiful warbling call. In spring, some swoop on people near their nests.',
      c: ['It can recognise individual human faces.', 'It is not related to the European bird of the same name.', 'Cyclists wear spikes on helmets in spring because of it.', 'Its song is a rich, flute-like warble.', 'It is black and white and swoops in spring.'] },
    { n: 'Pied currawong', sci: 'Strepera graculina', g: 'songbird', f: f(AU), d: 2, look: ['Australian magpie'],
      b: 'A big black bird with yellow eyes and white patches, found in eastern Australia. Its name copies its call.',
      c: ['Its name comes from its call.', 'It raids nests for eggs and chicks.', 'It has bright yellow eyes.', 'It has white patches on its wings and tail.', 'It is mostly black.'] },
    { n: 'Superb fairywren', alt: ['blue wren', 'superb blue wren'], sci: 'Malurus cyaneus', g: 'songbird', f: f(AU), d: 1,
      b: 'A tiny Australian bird with a cocked tail. Breeding males are bright blue and black.',
      c: ['Males bring yellow petals to females.', 'Mothers sing a "password" to their eggs.', 'Families have helpers that feed the chicks.', 'It holds its long tail upright.', 'The male is bright sky-blue.'] },
    { n: 'Superb lyrebird', alt: ['lyrebird'], sci: 'Menura novaehollandiae', g: 'songbird', f: f(AU), d: 1,
      b: 'An Australian bird famous for copying sounds, from other birds to chainsaws and camera shutters.',
      c: ['It appears on the Australian 10-cent coin.', 'It can copy chainsaws and camera shutters.', 'The male dances on a mound of earth.', 'Its tail is shaped like an old stringed instrument.', 'It is the world\'s best-known mimic bird.'] },
    { n: 'Tawny frogmouth', sci: 'Podargus strigoides', g: 'frogmouth', f: f(AU), d: 1, look: ['Barn owl'],
      b: 'A grey night bird that looks like an owl. By day it sits still and pretends to be a broken branch.',
      c: ['It is not an owl, though it looks like one.', 'By day it poses as a broken branch.', 'It catches insects at night.', 'It has a very wide mouth.', 'Its mouth is said to look like an amphibian\'s.'] },
    { n: 'Satin bowerbird', sci: 'Ptilonorhynchus violaceus', g: 'songbird', f: f(AU), d: 2,
      b: 'The male builds a stick bower and decorates it with blue objects, like bottle tops and pegs, to win a mate.',
      c: ['Males paint their bowers with chewed plant juice.', 'Males collect blue objects like straws and pegs.', 'The male has shiny blue-black feathers.', 'It has violet-blue eyes.', 'The male builds a bower to attract females.'] },
    { n: 'Australian pelican', sci: 'Pelecanus conspicillatus', g: 'waterbird', f: f(AU), d: 1,
      b: 'A big white-and-black waterbird with the longest bill of any bird. Its throat pouch holds fish.',
      c: ['It has the longest bill of any bird.', 'Flocks fly inland when outback lakes fill.', 'It herds fish together with others.', 'It scoops fish into a stretchy throat pouch.', 'It is a big black-and-white waterbird.'] },
    { n: 'Black swan', sci: 'Cygnus atratus', g: 'waterfowl', f: f(AU), d: 1, look: ['Mute swan'],
      b: 'A black swan with a red bill. It is the state bird of Western Australia.',
      c: ['It is the state emblem of Western Australia.', 'Europeans once thought it could not exist.', 'Its wing tips are white in flight.', 'It has a bright red bill.', 'It is a black waterbird with a long neck.'] },
    { n: 'Australian white ibis', alt: ['bin chicken', 'ibis'], sci: 'Threskiornis molucca', g: 'waterbird', f: f(AU), d: 1,
      b: 'A white bird with a bald black head and a long curved bill. In cities it raids rubbish bins, earning the nickname "bin chicken".',
      c: ['It is nicknamed the "bin chicken".', 'Its head and neck have no feathers.', 'Its bill curves downwards.', 'It is related to a bird sacred in ancient Egypt.', 'It is white with a black head.'] },
    { n: 'Wedge-tailed eagle', alt: ['wedgie'], sci: 'Aquila audax', g: 'raptor', f: f(AU), d: 2,
      b: 'Australia\'s largest bird of prey, with a diamond-shaped tail. It can take prey as big as young kangaroos.',
      c: ['It can catch young kangaroos.', 'Its wingspan can reach about 2.3 metres.', 'It often feeds on roadkill.', 'Its tail is shaped like a diamond.', 'It is Australia\'s biggest bird of prey.'] },
    { n: 'Willie wagtail', sci: 'Rhipidura leucophrys', g: 'songbird', f: f(AU), d: 2,
      b: 'A small black-and-white Australian bird that wags its tail from side to side. It bravely chases off much bigger birds.',
      c: ['It even attacks eagles near its nest.', 'It sings at night.', 'It is a kind of fantail.', 'It is black above and white below.', 'It flicks its tail from side to side.'] },
    { n: 'Noisy miner', sci: 'Manorina melanocephala', g: 'songbird', f: f(AU), d: 2,
      b: 'A grey honeyeater with a yellow patch behind its eye. Gangs of them chase other small birds out of gardens.',
      c: ['It is a native honeyeater, not the Indian bird with a similar name.', 'Gangs chase other birds away.', 'It has a yellow patch behind its eye.', 'It is grey with a black crown.', 'It is loud.'] },
    { n: 'Masked lapwing', alt: ['spur-winged plover', 'plover'], sci: 'Vanellus miles', g: 'wader', f: f(AU), d: 2,
      b: 'A loud, brave bird with yellow face wattles. It dive-bombs people who get close to its nest on footy ovals.',
      c: ['It has a sharp spur on each wing.', 'It nests on the ground, even on sports fields.', 'It dive-bombs people near its nest.', 'It has a yellow face.', 'It looks as if it is wearing a disguise.'] },
    { n: 'Brolga', sci: 'Antigone rubicunda', g: 'crane', f: f(AU), d: 2,
      b: 'A tall grey crane with a red head. Pairs perform graceful leaping dances.',
      c: ['It is Queensland\'s state bird.', 'Pairs perform leaping dances.', 'It has a red band on its head.', 'It is grey and very tall.', 'It is a kind of crane.'] },
    { n: 'Gouldian finch', alt: ['rainbow finch'], sci: 'Chloebia gouldiae', g: 'songbird', f: f(AU), d: 2,
      b: 'A tiny, brilliantly coloured finch of northern Australia with a purple chest and yellow belly.',
      c: ['Its head can be red, black or yellow.', 'It lives in tropical savanna in northern Australia.', 'It is named after the wife of John Gould.', 'Its chest is purple and its belly is yellow.', 'It is a tiny, very colourful finch.'] },
    { n: 'Little penguin', alt: ['fairy penguin', 'little blue penguin'], sci: 'Eudyptula minor', g: 'penguin', f: f(AU, true), d: 1, look: ['Emperor penguin'],
      b: 'The smallest penguin in the world. On Phillip Island, crowds watch them waddle up the beach at sunset.',
      c: ['Crowds watch its "parade" on Phillip Island.', 'It comes ashore after dark.', 'It lives in southern Australia and New Zealand.', 'Its back is slate blue.', 'It is the smallest penguin in the world.'] },
    { n: 'North Island brown kiwi', alt: ['kiwi'], sci: 'Apteryx mantelli', g: 'ratite', f: f(NZ, true), d: 1,
      b: 'A small flightless bird from New Zealand with hair-like feathers. It has nostrils at the tip of its long beak to sniff out worms.',
      c: ['Its nostrils are at the tip of its beak.', 'Its egg is huge, about a fifth of the mother\'s weight.', 'It comes out at night to sniff for worms.', 'It is New Zealand\'s national bird.', 'Its name is also used for a fuzzy brown fruit.'] },
    { n: 'Kea', sci: 'Nestor notabilis', g: 'parrot', f: f(NZ), d: 2, look: ['Kākāpō'],
      b: 'A clever, cheeky mountain parrot from New Zealand. It is known for pulling rubber off cars.',
      c: ['It solves puzzles as well as some apes.', 'It pulls rubber seals off cars.', 'Its wings are orange underneath.', 'It is the world\'s only alpine parrot.', 'It is an olive-green parrot from New Zealand.'] },
    { n: 'Kākāpō', alt: ['kakapo', 'owl parrot'], sci: 'Strigops habroptilus', g: 'parrot', f: f(NZ, true), d: 2, look: ['Kea'],
      b: 'A fat, flightless, night-time parrot from New Zealand. Fewer than 300 are left, and each one has a name.',
      c: ['Every living one has a name.', 'Males "boom" to call females from far away.', 'It is the heaviest parrot in the world.', 'It is nocturnal and smells musty-sweet.', 'It is a green parrot that cannot fly.'] },
    // ---- Rest of the world ----
    { n: 'Ostrich', alt: ['common ostrich'], sci: 'Struthio camelus', g: 'ratite', f: f(AF, true), d: 1, look: ['Emu', 'Southern cassowary'],
      b: 'The biggest bird in the world. It cannot fly, but it can run faster than any other bird.',
      c: ['It lays the largest eggs of any living bird.', 'It has only two toes on each foot.', 'It can run at about 70 km/h.', 'The myth says it buries its head in the sand.', 'It is the biggest bird in the world.'] },
    { n: 'Emperor penguin', sci: 'Aptenodytes forsteri', g: 'penguin', f: f(AN, true), d: 1, look: ['Little penguin'],
      b: 'The biggest penguin. Males keep the egg warm on their feet through the dark Antarctic winter.',
      c: ['It can dive deeper than 500 metres.', 'Huddles of males take turns on the cold outside.', 'Males balance the egg on their feet for about two months.', 'It breeds on Antarctic sea ice in winter.', 'It is the biggest penguin in the world.'] },
    { n: 'Atlantic puffin', alt: ['puffin'], sci: 'Fratercula arctica', g: 'seabird', f: f(EU), d: 1,
      b: 'A small black-and-white seabird with a colourful beak. It can carry many small fish in its beak at once.',
      c: ['It nests in burrows on clifftops.', 'It can hold over ten fish in its beak at once.', 'Its beak is brightest in the breeding season.', 'It is nicknamed the "sea parrot".', 'It has a big orange, blue and yellow beak.'] },
    { n: 'Bald eagle', sci: 'Haliaeetus leucocephalus', g: 'raptor', f: f(NA), d: 1, look: ['Golden eagle'],
      b: 'A big eagle with a white head and tail. It is the national bird of the United States.',
      c: ['Its nests can weigh over a tonne.', 'It often steals fish from ospreys.', 'It nearly died out because of the pesticide DDT.', 'It is the national bird of the USA.', 'Its head is white, not really without feathers.'] },
    { n: 'Golden eagle', sci: 'Aquila chrysaetos', g: 'raptor', f: f(WW), d: 2, look: ['Bald eagle', 'Wedge-tailed eagle'],
      b: 'A powerful brown eagle of mountains across the northern hemisphere. Hunters in Central Asia train them to catch foxes.',
      c: ['Kazakh hunters train it to catch foxes.', 'It is the national bird of Mexico.', 'It can dive at over 240 km/h.', 'It nests on cliffs in Scotland.', 'The back of its neck is a shining yellow-brown.'] },
    { n: 'Peregrine falcon', alt: ['peregrine'], sci: 'Falco peregrinus', g: 'raptor', f: f(WW), d: 1,
      b: 'The fastest animal on Earth. It dives on other birds at over 300 km/h.',
      c: ['It nests on skyscrapers in many cities.', 'It is found on every continent except Antarctica.', 'It strikes birds in mid-air with its feet.', 'It has a dark "moustache" stripe.', 'It is the fastest animal in the world.'] },
    { n: 'Osprey', alt: ['fish hawk'], sci: 'Pandion haliaetus', g: 'raptor', f: f(WW), d: 2,
      b: 'A bird of prey that eats almost only fish. It plunges feet-first into the water to catch them.',
      c: ['It can close its nostrils when it dives.', 'It turns fish head-first to carry them.', 'It lives on every continent except Antarctica.', 'It plunges feet-first into water.', 'It eats almost nothing but fish.'] },
    { n: 'Andean condor', sci: 'Vultur gryphus', g: 'raptor', f: f(SA), d: 2,
      b: 'A huge vulture of the Andes mountains with one of the largest wingspans of any bird. It can glide for hours without flapping.',
      c: ['One was tracked flying 170 km without flapping.', 'It can live for over 70 years.', 'Males have a fleshy comb on the head.', 'It is a symbol of several South American countries.', 'It soars over the mountains of South America.'] },
    { n: 'Secretary bird', alt: ['secretarybird'], sci: 'Sagittarius serpentarius', g: 'raptor', f: f(AF), d: 2,
      b: 'A long-legged African bird of prey that kills snakes by stamping on them.',
      c: ['It kicks with a force about five times its body weight.', 'It appears on the coat of arms of Sudan and South Africa.', 'It hunts on foot across the savanna.', 'It stamps on snakes to kill them.', 'Its head feathers look like quill pens behind an office worker\'s ear.'] },
    { n: 'Harpy eagle', sci: 'Harpia harpyja', g: 'raptor', f: f(SA), d: 2,
      b: 'A huge rainforest eagle of Central and South America. Its talons are as big as a bear\'s claws, and it catches sloths and monkeys.',
      c: ['Its back talons are about as long as a grizzly bear\'s claws.', 'It snatches sloths and monkeys from trees.', 'It has a grey crest that it can raise.', 'It is Panama\'s national bird.', 'It is named after a monster from Greek myth.'] },
    { n: 'Barn owl', sci: 'Tyto alba', g: 'owl', f: f(WW), d: 1, look: ['Tawny frogmouth', 'Snowy owl'],
      b: 'A pale owl with a heart-shaped face. It can find mice in total darkness just by listening.',
      c: ['One ear is higher than the other to help pinpoint sounds.', 'It screeches rather than hoots.', 'It is found on every continent except Antarctica.', 'It often nests in farm buildings.', 'It has a white, heart-shaped face.'] },
    { n: 'Snowy owl', sci: 'Bubo scandiacus', g: 'owl', f: f(WW), d: 1, look: ['Barn owl'],
      b: 'A big white owl of the Arctic. It hunts in daylight during the long summer days.',
      c: ['It hunts by day during the Arctic summer.', 'Its numbers rise and fall with lemmings.', 'Females have more dark spots than males.', 'Harry Potter\'s owl Hedwig is one.', 'It is a big white owl of the Arctic.'] },
    { n: 'Great horned owl', sci: 'Bubo virginianus', g: 'owl', f: f(AM), d: 2,
      b: 'A big, fierce owl of the Americas with feathery ear tufts. It even hunts skunks.',
      c: ['It is one of the few predators that eats skunks.', 'Its grip is very powerful.', 'It hoots deeply at night.', 'It has big feathery ear tufts.', 'It is a large owl of the Americas.'] },
    { n: 'Greater flamingo', alt: ['flamingo'], sci: 'Phoenicopterus roseus', g: 'waterbird', f: f(WW), d: 1,
      b: 'A tall pink bird that feeds with its head upside down. Its pink colour comes from the food it eats.',
      c: ['It feeds with its head upside down.', 'Its colour comes from pigments in shrimp and algae.', 'It often stands on one leg.', 'Thousands gather on salty lakes.', 'It is tall and pink.'] },
    { n: 'Scarlet macaw', sci: 'Ara macao', g: 'parrot', f: f(AM), d: 1, look: ['African grey parrot'],
      b: 'A big, bright red, yellow and blue parrot from Central and South American rainforests.',
      c: ['It eats clay from riverbanks.', 'It can live for over 50 years.', 'It is Honduras\'s national bird.', 'It has a long tail and a huge beak.', 'It is bright red with yellow and blue wings.'] },
    { n: 'African grey parrot', alt: ['grey parrot'], sci: 'Psittacus erithacus', g: 'parrot', f: f(AF), d: 2, look: ['Scarlet macaw'],
      b: 'A grey parrot with a red tail, famous as one of the best talking birds. One named Alex learned over 100 words.',
      c: ['A famous one named Alex knew colours, shapes and numbers.', 'It is endangered because of the pet trade.', 'It has a bright red tail.', 'It is one of the best talking birds.', 'It is a parrot coloured like ash.'] },
    { n: 'Toco toucan', alt: ['toucan'], sci: 'Ramphastos toco', g: 'toucan', f: f(SA), d: 1,
      b: 'A black bird with a huge orange beak, from South America. Its beak is light because it is hollow inside.',
      c: ['Its beak helps it lose heat.', 'Its beak is light because it is full of air spaces.', 'It sleeps with its beak tucked under its wing.', 'It is black with a white throat.', 'Its huge beak is bright orange.'] },
    { n: 'Bee hummingbird', sci: 'Mellisuga helenae', g: 'hummingbird', f: f(AM), d: 2, look: ['Ruby-throated hummingbird'],
      b: 'The smallest bird in the world, from Cuba. It weighs about as much as a paperclip.',
      c: ['It lays eggs the size of coffee beans.', 'It weighs about 2 grams.', 'It lives only in Cuba.', 'It hovers to drink nectar.', 'It is the smallest bird in the world.'] },
    { n: 'Ruby-throated hummingbird', alt: ['hummingbird'], sci: 'Archilochus colubris', g: 'hummingbird', f: f(NA), d: 1, look: ['Bee hummingbird'],
      b: 'A tiny bird that hovers at flowers. It flies non-stop across the Gulf of Mexico on migration.',
      c: ['It flies non-stop across the Gulf of Mexico.', 'Its heart can beat over 1,000 times a minute.', 'It can fly backwards.', 'Males have a glowing red throat.', 'It hovers in front of flowers.'] },
    { n: 'Resplendent quetzal', alt: ['quetzal'], sci: 'Pharomachrus mocinno', g: 'trogon', f: f(AM), d: 2,
      b: 'A shining green bird of Central American cloud forests. Males have tail streamers longer than their bodies.',
      c: ['Guatemala\'s money is named after it.', 'The Aztecs and Maya prized its feathers.', 'It loves wild avocados.', 'Males have very long tail streamers.', 'It is shining green with a red belly.'] },
    { n: 'Indian peafowl', alt: ['peacock', 'peahen', 'peafowl'], sci: 'Pavo cristatus', g: 'gamebird', f: f(AS), d: 1,
      b: 'The male, called a peacock, shows off a huge fan of tail feathers covered in eye-spots.',
      c: ['It is the national bird of India.', 'The female is mostly brown.', 'Its loud call sounds like someone shouting "help".', 'The male\'s train has about 200 eye-spot feathers.', 'The male spreads a huge colourful fan.'] },
    { n: 'Mandarin duck', sci: 'Aix galericulata', g: 'waterfowl', f: f(AS), d: 2, look: ['Mallard'],
      b: 'A beautiful duck from East Asia. The male has orange "sails" on its back and a colourful face.',
      c: ['It nests in holes in trees.', 'Ducklings jump from the nest high up.', 'It is a symbol of love in China.', 'The male has orange sail-like feathers on its back.', 'It is named after an official of imperial China.'] },
    { n: 'Mallard', alt: ['wild duck'], sci: 'Anas platyrhynchos', g: 'waterfowl', f: f(WW), d: 1, look: ['Mandarin duck'],
      b: 'The common wild duck of parks and ponds. Almost all farm ducks come from it.',
      c: ['Almost all farm ducks are descended from it.', 'Only the female gives a loud "quack".', 'The male has a white neck ring.', 'The male has a shiny green head.', 'It is the most common duck in park ponds.'] },
    { n: 'Mute swan', sci: 'Cygnus olor', g: 'waterfowl', f: f(EU), d: 1, look: ['Black swan'],
      b: 'A big white swan with an orange bill and a black knob. In Britain, the monarch can claim unmarked ones on open water.',
      c: ['Swan Upping counts them on the River Thames each year.', 'It hisses at people near its nest.', 'It has a black knob on its bill.', 'Its bill is orange.', 'It is a big white waterbird with a curved neck.'] },
    { n: 'Canada goose', sci: 'Branta canadensis', g: 'waterfowl', f: f(NA), d: 1,
      b: 'A big brown goose with a black neck and white chin strap. Flocks fly in V shapes.',
      c: ['It has been introduced to Britain and New Zealand.', 'Flocks fly in a V shape.', 'It honks loudly.', 'It has a white chin strap.', 'It is named after a big North American country.'] },
    { n: 'Wild turkey', alt: ['turkey'], sci: 'Meleagris gallopavo', g: 'gamebird', f: f(NA), d: 1,
      b: 'A big North American bird. Males puff up and fan their tails. Farm turkeys come from it.',
      c: ['Benjamin Franklin praised it over the bald eagle.', 'Unlike farm ones, wild ones can fly.', 'Males gobble loudly in spring.', 'It is eaten at Thanksgiving and Christmas.', 'Its name is also a country.'] },
    { n: 'Red junglefowl', alt: ['chicken', 'jungle fowl'], sci: 'Gallus gallus', g: 'gamebird', f: f(AS), d: 1,
      b: 'A wild bird of Asian forests and the ancestor of the chicken. There are more chickens than any other bird.',
      c: ['It was tamed in South-East Asia thousands of years ago.', 'Roosters crow at dawn.', 'It has a red comb on its head.', 'It is the wild ancestor of farmyard hens.', 'There are billions of its tame relatives.'] },
    { n: 'Rock dove', alt: ['pigeon', 'feral pigeon', 'rock pigeon'], sci: 'Columba livia', g: 'pigeon', f: f(WW), d: 1,
      b: 'The wild ancestor of the city pigeon. Pigeons can find their way home from hundreds of kilometres away.',
      c: ['Pigeons carried messages in both World Wars.', 'Homing ones can find their way home from far away.', 'It nests on buildings like sea cliffs.', 'It coos.', 'It is the grey bird of city squares.'] },
    { n: 'Greater roadrunner', alt: ['roadrunner'], sci: 'Geococcyx californianus', g: 'cuckoo', f: f(NA), d: 2,
      b: 'A fast desert cuckoo of the south-western USA and Mexico. It can run at about 30 km/h and kills rattlesnakes.',
      c: ['It is a kind of cuckoo.', 'It can kill and eat rattlesnakes.', 'It warms up in the morning by sunbathing.', 'A cartoon one always escaped Wile E. Coyote.', 'It runs along roads in the desert.'] },
    { n: 'Northern cardinal', alt: ['cardinal', 'redbird'], sci: 'Cardinalis cardinalis', g: 'songbird', f: f(NA), d: 1,
      b: 'A bright red songbird with a crest and a black face, common in gardens in the eastern USA.',
      c: ['It is the state bird of seven US states.', 'It sometimes attacks its own reflection.', 'The female is brown with red tints.', 'It has a crest and a black mask.', 'It is named after the red robes of church officials.'] },
    { n: 'American robin', sci: 'Turdus migratorius', g: 'songbird', f: f(NA), d: 2, look: ['European robin'],
      b: 'A big thrush with an orange breast, common on North American lawns. It is not closely related to the European robin.',
      c: ['It is really a kind of thrush.', 'Its eggs are a famous shade of blue.', 'It pulls worms from lawns.', 'Its breast is orange-red.', 'It shares its name with a smaller European bird.'] },
    { n: 'European robin', alt: ['robin', 'robin redbreast'], sci: 'Erithacus rubecula', g: 'songbird', f: f(EU), d: 1, look: ['American robin'],
      b: 'A small brown bird with an orange-red breast. It often follows gardeners to catch worms.',
      c: ['It sings all through winter.', 'It fiercely defends its territory.', 'It follows gardeners to catch worms.', 'It appears on many Christmas cards.', 'It has an orange-red breast.'] },
    { n: 'Blue jay', sci: 'Cyanocitta cristata', g: 'songbird', f: f(NA), d: 2,
      b: 'A loud, clever blue-and-white bird with a crest. It buries acorns and helps oak forests spread.',
      c: ['It buries thousands of acorns in autumn.', 'It can copy the call of hawks.', 'A Toronto baseball team is named after it.', 'It has a crest.', 'It is bright blue with white and black.'] },
    { n: 'House sparrow', alt: ['sparrow'], sci: 'Passer domesticus', g: 'songbird', f: f(WW), d: 1,
      b: 'A small brown bird that lives close to people almost everywhere. Its numbers have dropped in many cities.',
      c: ['It has been introduced to every continent except Antarctica.', 'Males have a black bib.', 'It takes dust baths.', 'It chirps in flocks around houses.', 'It is a small brown bird that lives near people.'] },
    { n: 'Common starling', alt: ['European starling', 'starling'], sci: 'Sturnus vulgaris', g: 'songbird', f: f(WW), d: 2,
      b: 'A speckled songbird whose huge flocks make swirling shapes in the sky called murmurations.',
      c: ['It was released in New York\'s Central Park in 1890.', 'It is a brilliant mimic.', 'Its feathers shine purple and green.', 'Huge flocks swirl at dusk in murmurations.', 'It is speckled with white dots like tiny lights in the sky.'] },
    { n: 'Barn swallow', alt: ['swallow'], sci: 'Hirundo rustica', g: 'songbird', f: f(WW), d: 1,
      b: 'A fast-flying bird with a long forked tail. It flies from Europe to Africa each winter.',
      c: ['British ones spend winter in South Africa.', 'It builds a cup nest of mud.', 'It catches insects in flight.', 'It has a red throat and a long forked tail.', 'It often nests in farm buildings.'] },
    { n: 'Common kingfisher', alt: ['kingfisher'], sci: 'Alcedo atthis', g: 'kingfisher', f: f(EU), d: 1, look: ['Laughing kookaburra'],
      b: 'A tiny, bright blue and orange bird that dives into rivers to catch fish.',
      c: ['The shape of its beak inspired the Japanese bullet train\'s nose.', 'It nests in tunnels in riverbanks.', 'It dives headfirst into water.', 'It is bright blue and orange.', 'It is named after royalty and catching fish.'] },
    { n: 'Eurasian blue tit', alt: ['blue tit'], sci: 'Cyanistes caeruleus', g: 'songbird', f: f(EU), d: 1,
      b: 'A tiny blue-and-yellow garden bird. It used to peck through foil milk bottle tops to drink the cream.',
      c: ['It learned to open milk bottles in Britain.', 'It often uses nest boxes.', 'It can hang upside down on feeders.', 'It has a blue cap and a yellow belly.', 'It is a tiny garden bird with a short name.'] },
    { n: 'Eurasian magpie', alt: ['magpie'], sci: 'Pica pica', g: 'crow', f: f(EU), d: 1, look: ['Australian magpie'],
      b: 'A black-and-white bird of the crow family with a long tail. It can recognise itself in a mirror.',
      c: ['It can recognise itself in a mirror.', 'Folklore says it steals shiny things.', 'A rhyme says "one for sorrow, two for joy".', 'It has a long, glossy tail.', 'It is black and white and in the crow family.'] },
    { n: 'Common raven', alt: ['raven'], sci: 'Corvus corax', g: 'crow', f: f(WW), d: 1,
      b: 'The biggest songbird in the world, all glossy black. Ravens are very clever and can solve puzzles.',
      c: ['Legend says Britain will fall if they leave the Tower of London.', 'It is the largest songbird in the world.', 'It can solve puzzles and plan ahead.', 'It croaks deeply.', 'It is a big, glossy black bird.'] },
    { n: 'Wandering albatross', alt: ['albatross'], sci: 'Diomedea exulans', g: 'seabird', f: f(AN), d: 2,
      b: 'The bird with the longest wings in the world, up to about 3.5 metres. It glides over the Southern Ocean for hours without flapping.',
      c: ['It can live for over 50 years.', 'It may fly over 100,000 km a year.', 'It glides for hours without flapping.', 'It has the longest wingspan of any living bird.', 'It roams over the Southern Ocean.'] },
    { n: 'Blue-footed booby', sci: 'Sula nebouxii', g: 'seabird', f: f(AM), d: 1,
      b: 'A seabird with bright blue feet. Males show off their feet in a high-stepping dance.',
      c: ['It dives into the sea from high up.', 'Many live on the Galápagos Islands.', 'Females prefer males with the brightest feet.', 'Males strut in a high-stepping dance.', 'Its feet are bright blue.'] },
    { n: 'Magnificent frigatebird', alt: ['frigatebird'], sci: 'Fregata magnificens', g: 'seabird', f: f(AM), d: 2,
      b: 'A seabird with long pointed wings. Males blow up a huge red throat pouch like a balloon.',
      c: ['It can stay in the air for weeks.', 'It steals food from other seabirds.', 'Its feathers are not waterproof.', 'Males puff up a red throat pouch like a balloon.', 'It is named after a fast warship.'] },
    { n: 'Grey heron', sci: 'Ardea cinerea', g: 'waterbird', f: f(WW), d: 2,
      b: 'A tall grey wading bird that stands still in shallow water, then stabs fish with its sharp beak.',
      c: ['It nests in colonies at the tops of trees.', 'It flies with its neck pulled back in an S.', 'It raids garden fish ponds.', 'It stands still waiting for fish.', 'It is tall, with grey feathers.'] },
    { n: 'White stork', sci: 'Ciconia ciconia', g: 'waterbird', f: f(EU), d: 1,
      b: 'A big white bird with black wings and a red beak. In stories it delivers babies.',
      c: ['It clatters its beak instead of calling.', 'It flies to Africa for winter.', 'It builds huge nests on rooftops and chimneys.', 'It has a long red beak and legs.', 'In stories it delivers new babies.'] },
    { n: 'Shoebill', alt: ['whale-headed stork'], sci: 'Balaeniceps rex', g: 'waterbird', f: f(AF), d: 2,
      b: 'A huge, grey, prehistoric-looking bird from African swamps with an enormous beak. It catches lungfish and even baby crocodiles.',
      c: ['It catches lungfish and even baby crocodiles.', 'It stands still for hours.', 'It claps its bill loudly.', 'It lives in swamps in East Africa.', 'Its giant beak is shaped like footwear.'] },
    { n: 'Great spotted woodpecker', alt: ['woodpecker'], sci: 'Dendrocopos major', g: 'woodpecker', f: f(EU), d: 1,
      b: 'A black-and-white woodpecker with red patches. It drums on trees so fast you can hear it across a wood.',
      c: ['Its tongue wraps round inside its skull.', 'It drums on dead branches to claim territory.', 'It visits garden bird feeders.', 'It has a red patch under its tail.', 'It hammers holes in trees.'] },
    { n: 'Common cuckoo', alt: ['cuckoo'], sci: 'Cuculus canorus', g: 'cuckoo', f: f(EU), d: 1,
      b: 'A grey bird that lays its eggs in other birds\' nests. Its chick pushes out the other eggs.',
      c: ['Its chick pushes the host\'s eggs out of the nest.', 'Its eggs can copy the colour of the host\'s eggs.', 'It flies to Africa for winter.', 'It lays its eggs in other birds\' nests.', 'Its call gave its name to a kind of clock.'] },
    { n: 'Great hornbill', sci: 'Buceros bicornis', g: 'hornbill', f: f(AS), d: 2,
      b: 'A huge Asian bird with a giant yellow beak and a helmet on top. The female seals herself inside a tree hole to nest.',
      c: ['The female seals herself into a tree hole with mud.', 'The male feeds her through a slit.', 'It has a hollow helmet on its beak called a casque.', 'It lives in forests of India and South-East Asia.', 'Its huge beak is yellow.'] },
    { n: 'Lilac-breasted roller', sci: 'Coracias caudatus', g: 'roller', f: f(AF), d: 2,
      b: 'A brilliantly coloured bird of the African savanna. It tumbles and rolls in the air during courtship.',
      c: ['It is often seen on safari in East Africa.', 'It perches on bare branches to spot prey.', 'It rolls and dives in display flights.', 'It has many bright colours.', 'Its chest is a pale purple colour.'] },
    { n: 'Greater bird-of-paradise', sci: 'Paradisaea apoda', g: 'songbird', f: f(AS), d: 2,
      b: 'A bird of New Guinea forests. Males show off huge golden plumes in group displays.',
      c: ['Early traders sold skins without feet, so Europeans thought it never landed.', 'Its scientific name means "footless".', 'Males gather to display in treetops.', 'Males have big golden plumes.', 'It lives in New Guinea.'] },
    { n: 'Arctic tern', sci: 'Sterna paradisaea', g: 'seabird', f: f(WW), d: 2,
      b: 'A small seabird with the longest migration of any animal, flying from the Arctic to the Antarctic and back every year.',
      c: ['It sees more daylight than any other animal.', 'It may fly about 70,000 km a year.', 'It dive-bombs people near its nest.', 'It has a red beak and a black cap.', 'It flies from pole to pole each year.'] },
    { n: 'Common nightingale', alt: ['nightingale'], sci: 'Luscinia megarhynchos', g: 'songbird', f: f(EU), d: 2,
      b: 'A plain brown songbird famous for its beautiful song, often sung at night.',
      c: ['Florence Nightingale shares its name.', 'Males sing at night to attract females.', 'It spends winter in Africa.', 'It is a plain brown bird.', 'It is famous for its beautiful song.'] },
    { n: 'Golden pheasant', sci: 'Chrysolophus pictus', g: 'gamebird', f: f(AS), d: 2,
      b: 'A dazzling pheasant from the mountains of China, with a golden crest and red body.',
      c: ['It comes from the mountains of western China.', 'Males have an orange cape they spread like a fan.', 'It spends most of its time on the ground.', 'The male has a red body and a long tail.', 'The male has a bright yellow crest.'] },
  ],
  fakes: ['Crimson-crowned kookaburra', 'Silver-tailed emu', 'Northern glass penguin', 'Spotted thunder owl', 'Ruby-billed toucanet eagle', 'Velvet fantail cockatoo', 'Golden-eyed storm finch'],
  questions: [
    { kind: 'mc', prompt: 'What is the biggest bird in the world?', answer: 'Ostrich', wrong: ['Emu', 'Wandering albatross', 'Bald eagle'], explain: 'Ostriches can stand about 2.7 m tall.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the smallest bird in the world?', answer: 'Bee hummingbird', wrong: ['House sparrow', 'Superb fairywren', 'Eurasian blue tit'], explain: 'It weighs about 2 g and lives in Cuba.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the fastest animal in the world?', answer: 'Peregrine falcon', wrong: ['Cheetah', 'Ostrich', 'Sailfish'], explain: 'Diving peregrines exceed 300 km/h.', difficulty: 1 },
    { kind: 'tf', prompt: 'Penguins can fly.', answer: false, explain: 'Penguins use their wings as flippers to "fly" underwater.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which bird lays its eggs in other birds\' nests?', answer: 'Common cuckoo', wrong: ['Barn swallow', 'European robin', 'Mallard'], explain: 'The host parents raise the cuckoo chick.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which bird has the longest wingspan?', answer: 'Wandering albatross', wrong: ['Andean condor', 'Bald eagle', 'Ostrich'], explain: 'Up to about 3.5 m from tip to tip.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which Australian bird is famous for copying sounds like chainsaws and cameras?', answer: 'Superb lyrebird', wrong: ['Laughing kookaburra', 'Galah', 'Emu'], explain: 'Males fill their songs with mimicry.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which bird makes the longest migration of any animal?', answer: 'Arctic tern', wrong: ['Barn swallow', 'Canada goose', 'White stork'], explain: 'It flies between the Arctic and the Antarctic each year.', difficulty: 2 },
    { kind: 'mc', prompt: 'Why are flamingos pink?', answer: 'Pigments in their food', wrong: ['They are born pink', 'Sunburn', 'Pink mud'], explain: 'Carotenoids in shrimp and algae colour their feathers.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which bird is the national bird of the United States?', answer: 'Bald eagle', wrong: ['Wild turkey', 'Northern cardinal', 'Golden eagle'], explain: 'It has been the national emblem since 1782.', difficulty: 1 },
    { kind: 'tf', prompt: 'Male emperor penguins keep their egg warm on their feet.', answer: true, explain: 'They huddle through the Antarctic winter for about two months.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which bird is the wild ancestor of the farmyard chicken?', answer: 'Red junglefowl', wrong: ['Wild turkey', 'Indian peafowl', 'Golden pheasant'], explain: 'It was domesticated in South-East Asia.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which bird lays the largest eggs of any living bird?', answer: 'Ostrich', wrong: ['Emu', 'Emperor penguin', 'Southern cassowary'], explain: 'An ostrich egg weighs about 1.4 kg.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which bird has nostrils at the tip of its beak?', answer: 'Kiwi', wrong: ['Toucan', 'Pelican', 'Emu'], explain: 'It sniffs out worms in the soil.', difficulty: 2 },
    { kind: 'tf', prompt: 'Birds are the only animals alive today with feathers.', answer: true, explain: 'Some dinosaurs had feathers too, and birds are living dinosaurs.', difficulty: 2 },
  ],
};

// Typical adult weight (both sexes), from each species' Wikipedia description; birds without a clear figure are left out.
addFacts(PACK.items, 'massKg', {
  Emu: 35, 'Southern cassowary': 45, 'Laughing kookaburra': 0.35, Galah: 0.31, 'Rainbow lorikeet': 0.12, Budgerigar: 0.035,
  'Australian magpie': 0.29, 'Pied currawong': 0.3, 'Superb fairywren': 0.01, 'Superb lyrebird': 1, 'Tawny frogmouth': 0.35,
  'Australian pelican': 6, 'Black swan': 6, 'Australian white ibis': 1.8, 'Wedge-tailed eagle': 3.5, 'Willie wagtail': 0.02,
  'Noisy miner': 0.075, 'Masked lapwing': 0.3, Brolga: 5.5, 'Little penguin': 1.5, 'North Island brown kiwi': 2.5, Kea: 0.9,
  'Kākāpō': 2, Ostrich: 100, 'Emperor penguin': 30, 'Atlantic puffin': 0.45, 'Bald eagle': 4.5, 'Golden eagle': 4.5,
  'Peregrine falcon': 0.8, Osprey: 1.5, 'Andean condor': 12, 'Secretary bird': 4, 'Harpy eagle': 7, 'Snowy owl': 2,
  'Great horned owl': 1.4, 'Greater flamingo': 3, 'Scarlet macaw': 1, 'African grey parrot': 0.45, 'Toco toucan': 0.54,
  'Bee hummingbird': 0.002, 'Ruby-throated hummingbird': 0.0035, 'Resplendent quetzal': 0.21, 'Indian peafowl': 4, Mallard: 1.1,
  'Mute swan': 10.5, 'Canada goose': 4.5, 'Wild turkey': 6, 'Red junglefowl': 1, 'Rock dove': 0.3, 'Greater roadrunner': 0.35,
  'Northern cardinal': 0.045, 'American robin': 0.077, 'European robin': 0.018, 'Blue jay': 0.085, 'House sparrow': 0.03,
  'Common starling': 0.08, 'Barn swallow': 0.019, 'Common kingfisher': 0.04, 'Eurasian blue tit': 0.011, 'Eurasian magpie': 0.22,
  'Common raven': 1.2, 'Wandering albatross': 9, 'Blue-footed booby': 1.5, 'Magnificent frigatebird': 1.35, 'Grey heron': 1.5,
  'White stork': 3.4, Shoebill: 5.5, 'Great spotted woodpecker': 0.085, 'Common cuckoo': 0.12, 'Great hornbill': 3,
  'Lilac-breasted roller': 0.1, 'Arctic tern': 0.1,
});

export default PACK;
