import { WD, COMMONS, addFacts } from './_common.mjs';

const OR = 'Organ', BO = 'Bone', MU = 'Muscle', CE = 'Cell', TI = 'Tissue';
const DIG = 'Digestive', CIR = 'Circulatory', RES = 'Respiratory', NER = 'Nervous', SKE = 'Skeletal', URI = 'Urinary', IMM = 'Immune', END = 'Endocrine', MUS = 'Muscular', SEN = 'Senses', INT = 'Skin';
const f = (kind, system, extra = {}) => ({ kind, system, ...extra });

const PACK = {
  id: 'body', title: 'Human body', theme: 'science', icon: '🫀', kids: true,
  noun: 'body part',
  leakExempt: [],
  media: 'wiki', photos: 1, depicts: 0,
  factsMeta: {
    kind: { type: 'cat', label: 'Kind', values: [OR, BO, MU, CE, TI], clue: v => `It is ${/^[AEIOU]/.test(v) ? 'an' : 'a'} ${v.toLowerCase()}.` },
    system: { type: 'cat', label: 'Body system', clue: v => `It is part of the ${v.toLowerCase()} system.` },
    massG: { type: 'num', label: 'Typical adult weight', unit: 'g', higherLabel: 'Heavier', noClue: true },
    count: { type: 'num', label: 'How many you have', unit: '', askNumber: '{name}: how many does a person usually have?', clue: v => `Most people have ${v} of these.` },
  },
  imgPrompt: "Which of these shows the {lname}?",
  nameImgPrompt: "Which part of the body is this?",
  tfImgPrompt: "This is the {lname}.",
  tpl: {"massG": {"askHigh": "Which of these weighs the most in an adult?", "askLow": "Which of these weighs the least in an adult?", "askNumber": "What is the typical weight of an adult's {name}, in grams?"}, "kind": {"ask": "What kind of body part is the {lname}?", "askReverse": "Which of these is a {lvalue}?", "stmt": "The {lname} is a {lvalue}."}, "system": {"ask": "Which body system is the {lname} part of?", "askReverse": "Which of these is part of the {lvalue} system?", "stmt": "The {lname} is part of the {lvalue} system."}, "count": {"askHigh": "Which of these do we have the most of?"}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Heart', wp: 'Heart', f: f(OR, CIR, { count: 1 }), d: 1, allowSvg: true,
      b: 'A muscle that pumps blood around your body. It beats about 100,000 times a day.',
      c: ['It has four chambers.', 'It beats about 100,000 times a day.', 'It is about the size of a fist.', 'It pumps blood around the body.', 'It is the shape drawn on Valentine\'s cards, more or less.'] },
    { n: 'Brain', wp: 'Human brain', f: f(OR, NER, { count: 1 }), d: 1, allowSvg: true,
      b: 'The control centre of your body. It has about 86 billion nerve cells.',
      c: ['It uses about 20% of the body\'s energy.', 'It contains about 86 billion neurons.', 'Its left side mostly controls the right side of the body.', 'It is protected by the skull.', 'You think with it.'] },
    { n: 'Lungs', alt: ['lung'], wp: 'Lung', f: f(OR, RES, { count: 2 }), d: 1, allowSvg: true,
      b: 'Two spongy organs that take in oxygen from the air and get rid of carbon dioxide.',
      c: ['The left one is smaller to make room for the heart.', 'They contain hundreds of millions of tiny air sacs called alveoli.', 'Smoking damages them.', 'They take oxygen from the air.', 'You breathe with them.'] },
    { n: 'Liver', noAutoImg: true, files: ['Gray1087-liver.png'], wp: 'Liver', f: f(OR, DIG, { count: 1 }), d: 1, allowSvg: true,
      b: 'The biggest organ inside the body. It cleans the blood, stores energy and makes bile. It can regrow if part is removed.',
      c: ['It can regrow after part of it is removed.', 'It makes bile to help digest fat.', 'It removes poisons from the blood.', 'It is the largest internal organ.', 'It sits under the right ribs.'] },
    { n: 'Kidneys', alt: ['kidney'], wp: 'Kidney', f: f(OR, URI, { count: 2 }), d: 1, allowSvg: true,
      b: 'Two bean-shaped organs that filter waste from the blood and make urine.',
      c: ['You can live with just one of them.', 'They filter about 180 litres of blood plasma a day.', 'They make urine.', 'They are near your lower back.', 'They are shaped like beans.'] },
    { n: 'Stomach', wp: 'Stomach', f: f(OR, DIG, { count: 1 }), d: 1, allowSvg: true,
      b: 'A stretchy bag of muscle that mixes food with acid to start breaking it down.',
      c: ['It makes a new lining every few days so its acid does not digest it.', 'Its acid is strong enough to dissolve some metals.', 'It growls when it is empty.', 'It churns food with acid.', 'Food goes here after you swallow.'] },
    { n: 'Small intestine', alt: ['small bowel'], wp: 'Small intestine', f: f(OR, DIG, { count: 1 }), d: 2, allowSvg: true, look: ['Large intestine'],
      b: 'A long, coiled tube where most food is digested and absorbed. It is about 6 metres long.',
      c: ['Its lining is covered in tiny finger-like villi.', 'Its first part is called the duodenum.', 'Most nutrients are absorbed here.', 'It is about 6 metres long.', 'Its name says it is the narrower part of the gut.'] },
    { n: 'Large intestine', alt: ['colon', 'large bowel'], wp: 'Large intestine', f: f(OR, DIG, { count: 1 }), d: 2, allowSvg: true, look: ['Small intestine'],
      b: 'The last part of the gut. It soaks up water and is home to trillions of helpful bacteria.',
      c: ['Trillions of bacteria live in it.', 'It soaks up water from waste.', 'The appendix hangs off it.', 'It is wider but shorter than the other part of the gut.', 'Its main part is called the colon.'] },
    { n: 'Skin', noAutoImg: true, files: ['Skin Layers Unlabeled.jpg'], wp: 'Human skin', f: f(OR, INT, { count: 1 }), d: 1, allowSvg: true,
      b: 'The biggest organ of the body. It protects us, keeps us at the right temperature and lets us feel touch.',
      c: ['We shed millions of its cells every day.', 'Melanin gives it its colour.', 'Sweat helps it cool us down.', 'It is the largest organ of the body.', 'It covers the outside of the body.'] },
    { n: 'Pancreas', wp: 'Pancreas', f: f(OR, END, { count: 1 }), d: 2, allowSvg: true,
      b: 'An organ behind the stomach that makes digestive juices and insulin, which controls blood sugar.',
      c: ['It lies behind the stomach.', 'People with type 1 diabetes have damage to it.', 'It makes digestive enzymes.', 'It makes insulin.', 'It controls blood sugar.'] },
    { n: 'Spleen', noAutoImg: true, files: ['Location of the spleen in the human body, without text.jpg'], wp: 'Spleen', f: f(OR, IMM, { count: 1 }), d: 2, allowSvg: true,
      b: 'An organ on the left side that filters old red blood cells and helps fight infection.',
      c: ['People can live without it.', 'It recycles old red blood cells.', 'It helps fight infections.', 'It sits under the left ribs.', 'Its name also means bad temper in old English.'] },
    { n: 'Bladder', alt: ['urinary bladder'], wp: 'Urinary bladder', f: f(OR, URI, { count: 1 }), d: 1, allowSvg: true,
      b: 'A stretchy bag that stores urine until you go to the toilet.',
      c: ['It is part of the urinary system.', 'It sits low in the pelvis.', 'It can hold about half a litre.', 'Its walls stretch as it fills.', 'Tubes called ureters bring urine to it.', 'It tells you when you need the toilet.', 'It stores wee.'] },
    { n: 'Appendix', wp: 'Appendix (anatomy)', f: f(OR, DIG, { count: 1 }), d: 2, allowSvg: true,
      b: 'A small tube attached to the large intestine. It can get inflamed and may need to be removed.',
      c: ['It may store helpful gut bacteria.', 'It is a small pouch about the size of a finger.', 'It is attached to the large intestine.', 'It is often removed when inflamed.', 'Its name also means the extra section at the end of a book.'] },
    { n: 'Gallbladder', wp: 'Gallbladder', f: f(OR, DIG, { count: 1 }), d: 3, allowSvg: true,
      b: 'A small pouch under the liver that stores bile to help digest fat.',
      c: ['Stones can form inside it.', 'It squeezes bile into the gut after fatty meals.', 'It sits under the liver.', 'People can live without it.', 'It stores bile.'] },
    { n: 'Thyroid', alt: ['thyroid gland'], wp: 'Thyroid', f: f(OR, END, { count: 1 }), d: 3, allowSvg: true,
      b: 'A butterfly-shaped gland in the neck that controls how fast the body uses energy.',
      c: ['It needs iodine to work.', 'It controls metabolism.', 'A swelling of it is called a goitre.', 'It is shaped like a butterfly.', 'It is a gland in your neck.'] },
    { n: 'Tongue', wp: 'Tongue', f: f(MU, DIG, { count: 1 }), d: 1, allowSvg: true,
      b: 'A muscly organ covered in taste buds. It helps you taste, chew, swallow and talk.',
      c: ['Its print is unique, like a fingerprint.', 'It is made of eight muscles.', 'It has thousands of taste buds.', 'It helps you speak.', 'You taste with it.'] },
    { n: 'Eye', alt: ['eyes', 'eyeball'], wp: 'Human eye', f: f(OR, SEN, { count: 2 }), d: 1, allowSvg: true,
      b: 'The organ of sight. Light passes through the lens and makes an upside-down picture that the brain flips.',
      c: ['The picture it makes is upside down; the brain flips it.', 'Its coloured part is the iris.', 'It has a blind spot where the nerve leaves.', 'Its black centre is the pupil.', 'You see with it.'] },
    { n: 'Ear', alt: ['ears'], wp: 'Ear', f: f(OR, SEN, { count: 2 }), d: 1, allowSvg: true,
      b: 'The organ of hearing and balance. Tiny bones inside pass sound vibrations to the inner ear.',
      c: ['It contains the smallest bones in the body.', 'Its inner part helps you balance.', 'The snail-shaped cochlea is inside it.', 'Its drum vibrates with sound.', 'You hear with it.'] },
    { n: 'Femur', alt: ['thigh bone', 'thighbone'], wp: 'Femur', f: f(BO, SKE, { count: 2 }), d: 2, allowSvg: true, look: ['Humerus'],
      b: 'The thigh bone, the longest and strongest bone in the body.',
      c: ['Its top end forms part of the hip joint.', 'Its bottom end forms part of the knee.', 'It is very hard to break.', 'It is about a quarter of your height.', 'Its ball fits into the hip socket.', 'It is the strongest bone.', 'It is in your thigh.', 'It is the longest bone in the body.'] },
    { n: 'Skull', noAutoImg: true, files: ['Human skull front simplified.PNG', 'Front View of Skull.jpg'], alt: ['cranium'], wp: 'Human skull', f: f(BO, SKE, { count: 1 }), d: 1, allowSvg: true,
      b: 'The bones of the head that protect the brain. Its only bone that moves is the lower jaw.',
      c: ['A baby\'s has soft spots that close as it grows.', 'It is made of 22 bones in adults.', 'Its only movable bone is the lower jaw.', 'It protects the brain.', 'It is the bony part of the head.'] },
    { n: 'Spine', alt: ['backbone', 'vertebral column', 'spinal column'], wp: 'Vertebral column', f: f(BO, SKE, { count: 1 }), d: 1, allowSvg: true,
      b: 'A column of 33 small bones called vertebrae that holds you up and protects the spinal cord.',
      c: ['It lets you bend and twist.', 'Discs of cartilage sit between its bones.', 'It is made of 33 vertebrae.', 'Its lowest part is the tailbone.', 'It protects the spinal cord.', 'It has natural S-shaped curves.', 'It runs down the middle of your back.'] },
    { n: 'Rib cage', alt: ['ribs'], wp: 'Rib cage', f: f(BO, SKE, { count: 1 }) /* one cage of 24 ribs */, d: 1, allowSvg: true,
      b: 'A cage of 24 curved bones that protects the heart and lungs.',
      c: ['Some of its lowest bones are called "floating" because they do not reach the front.', 'Most people have 12 pairs.', 'It moves when you breathe.', 'It protects the heart and lungs.', 'It is made of curved bones around your chest.'] },
    { n: 'Stapes', alt: ['stirrup'], wp: 'Stapes', f: f(BO, SEN, { count: 2 }), d: 3, allowSvg: true,
      b: 'The smallest bone in the body, deep in the ear. It is shaped like a stirrup.',
      c: ['It is about 3 mm long.', 'It passes sound to the inner ear.', 'It is one of three tiny bones in the ear.', 'It is the smallest bone in the body.', 'It is shaped like a horse-riding stirrup.'] },
    { n: 'Pelvis', alt: ['hip bone', 'hips'], wp: 'Pelvis', f: f(BO, SKE, { count: 1 }), d: 2, allowSvg: true,
      b: 'A basin-shaped ring of bones at the base of the spine that connects the legs to the body.',
      c: ['It is made of several bones joined together.', 'You sit on part of it.', 'Its name comes from the Latin for "basin".', 'It is wider in women to allow childbirth.', 'The thigh bones fit into its sockets.', 'It connects the spine to the legs.', 'It forms your hips.'] },
    { n: 'Clavicle', files: ['Gray200.png'], alt: ['collarbone', 'collar bone'], wp: 'Clavicle', f: f(BO, SKE, { count: 2 }), d: 2, allowSvg: true,
      b: 'The collarbone, a long thin bone between the shoulder and the breastbone. It is often broken in falls.',
      c: ['It is shaped like a long, flat S.', 'It helps hold the arm away from the body.', 'It is one of the most commonly broken bones.', 'Its name comes from the Latin for "little key".', 'It joins the shoulder blade to the breastbone.', 'You can feel it at the base of your neck.', 'It is called the collarbone.'] },
    { n: 'Patella', alt: ['kneecap'], wp: 'Patella', f: f(BO, SKE, { count: 2 }), d: 2, allowSvg: true,
      b: 'The kneecap, a small, flat bone that protects the front of the knee joint.',
      c: ['It slides in a groove as you bend your leg.', 'It is on the front of your leg.', 'Babies\' are made of cartilage at first.', 'It sits inside a tendon.', 'It protects the knee joint.', 'It is a small, round, flat bone.', 'It is called the kneecap.'] },
    { n: 'Humerus', files: ['Gray208.png'], alt: ['upper arm bone'], wp: 'Humerus', f: f(BO, SKE, { count: 2 }), d: 2, allowSvg: true, look: ['Femur'],
      b: 'The long bone of the upper arm. Knocking a nerve near it gives the tingle of your "funny bone".',
      c: ['Its ball fits into the shoulder socket.', 'Its name sounds like the word for being amusing.', 'Hitting the nerve near its end gives a tingle.', 'It is in your upper arm.', 'It connects the shoulder to the elbow.'] },
    { n: 'Diaphragm', wp: 'Thoracic diaphragm', f: f(MU, RES, { count: 1 }), d: 2, allowSvg: true,
      b: 'A dome-shaped sheet of muscle under the lungs. When it tightens, you breathe in. Hiccups are spasms of it.',
      c: ['It separates the chest from the belly.', 'It is shaped like a dome.', 'Hiccups are sudden spasms of it.', 'It is the main muscle for breathing.', 'It sits just below the lungs.'] },
    { n: 'Biceps', alt: ['bicep', 'biceps brachii'], wp: 'Biceps', f: f(MU, MUS, { count: 2 }), d: 1, allowSvg: true,
      b: 'The muscle at the front of the upper arm that bends your elbow. People flex it to show off.',
      c: ['Its name means "two heads".', 'It works with the triceps as a pair.', 'It bends the elbow.', 'People flex it to show strength.', 'It is on the front of the upper arm.'] },
    { n: 'Gluteus maximus', files: ['Gluteus maximus muscle.PNG', 'Gluteus maximus.png'], alt: ['glutes', 'buttock muscle'], wp: 'Gluteus maximus', f: f(MU, MUS, { count: 2 }), d: 2, allowSvg: true,
      b: 'The biggest muscle in the body, in the buttocks. It helps you stand up, climb and run.',
      c: ['It is one of three muscles of the same group.', 'It helps you stand up from sitting.', 'It straightens the hip when you run.', 'It helps you climb stairs.', 'It keeps you upright.', 'It is the largest muscle in the body.', 'You sit on it.', 'Its name means the biggest one in the buttocks.'] },
    { n: 'Red blood cell', alt: ['erythrocyte', 'red blood cells'], wp: 'Red blood cell', f: f(CE, CIR), d: 1, allowSvg: true, look: ['White blood cell'],
      b: 'Tiny disc-shaped cells that carry oxygen around the body. They are red because of a protein called haemoglobin.',
      c: ['They are shaped like discs dented in the middle.', 'There are millions in a single drop of blood.', 'They have no nucleus.', 'They live for about 120 days.', 'They are made in bone marrow.', 'Haemoglobin inside them carries oxygen.', 'They make blood red.'] },
    { n: 'White blood cell', alt: ['leukocyte', 'white blood cells'], wp: 'White blood cell', f: f(CE, IMM), d: 1, allowSvg: true, look: ['Red blood cell'],
      b: 'Cells in the blood that fight germs and help protect you from infections.',
      c: ['There are far fewer of them than red ones.', 'Their numbers rise when you are ill.', 'Some kinds make antibodies.', 'Some kinds swallow germs whole.', 'They are made in bone marrow.', 'They fight infections.', 'They are the germ-fighting cells in blood.'] },
    { n: 'Neuron', alt: ['nerve cell', 'neurone'], wp: 'Neuron', f: f(CE, NER), d: 2, allowSvg: true,
      b: 'A nerve cell that sends electrical signals around the body and brain.',
      c: ['It has branches called dendrites.', 'Messages jump between them using chemicals.', 'Your spinal cord is full of them.', 'Signals can travel along some at over 100 metres per second.', 'Its long tail is called an axon.', 'Gaps between them are called synapses.', 'The brain has about 86 billion of them.', 'It is a nerve cell.'] },
    { n: 'Tooth', alt: ['teeth'], wp: 'Human tooth', f: f(TI, DIG, { count: 32 }), d: 1, allowSvg: true,
      b: 'Teeth bite and chew food. Adults usually have 32, and their outer enamel is the hardest substance in the body.',
      c: ['Children have 20 of the first set.', 'Adults usually have 32.', 'Its enamel is the hardest substance in the body.', 'Dentists look after them.', 'You chew with them.'] },
    { n: 'Achilles tendon', alt: ['heel cord'], wp: 'Achilles tendon', f: f(TI, MUS, { count: 2 }), d: 2, allowSvg: true,
      b: 'The thickest and strongest tendon in the body. It connects the calf muscles to the heel bone.',
      c: ['It runs down the back of the lower leg.', 'It is used every time you walk or jump.', 'It is named after a Greek hero with one weak spot.', 'Sprinters sometimes tear it.', 'It lets you stand on tiptoe.', 'It joins the calf to the heel.', 'It is the strongest tendon in the body.'] },
    { n: 'Trachea', alt: ['windpipe'], wp: 'Trachea', f: f(OR, RES, { count: 1 }), d: 2, allowSvg: true,
      b: 'The windpipe, a tube held open by rings of cartilage that carries air to the lungs.',
      c: ['C-shaped rings of cartilage hold it open.', 'It splits into two bronchi.', 'A flap called the epiglottis covers it when you swallow.', 'It carries air to the lungs.', 'It is called the windpipe.'] },
  ],
  questions: [
    { kind: 'number', prompt: 'How many bones are in an adult human body?', answer: 206, unit: 'bones', tolerance: 0, explain: 'Babies have about 300; many fuse as they grow.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is the largest organ of the human body?', answer: 'Skin', wrong: ['Liver', 'Brain', 'Lungs'], explain: 'The liver is the largest internal organ.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the longest bone in the body?', answer: 'Femur', wrong: ['Humerus', 'Tibia', 'Spine'], explain: 'The femur, or thigh bone, is about a quarter of your height.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the smallest bone in the body?', answer: 'Stapes', wrong: ['Patella', 'Incus', 'Little toe bone'], explain: 'The stirrup bone in the middle ear is about 3 mm long.', difficulty: 2 },
    { kind: 'mc', prompt: 'What does the heart pump around the body?', answer: 'Blood', wrong: ['Air', 'Food', 'Water'], explain: 'Blood carries oxygen and food to every cell.', difficulty: 1 },
    { kind: 'number', prompt: 'How many chambers does the human heart have?', answer: 4, unit: 'chambers', tolerance: 0, explain: 'Two atria and two ventricles.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which organ do you breathe with?', answer: 'Lungs', wrong: ['Stomach', 'Kidneys', 'Liver'], explain: 'They swap oxygen and carbon dioxide.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which gas do we breathe out more of than we breathe in?', answer: 'Carbon dioxide', wrong: ['Oxygen', 'Nitrogen', 'Helium'], explain: 'Our cells make carbon dioxide as waste.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which organ makes insulin?', answer: 'Pancreas', wrong: ['Liver', 'Kidney', 'Heart'], explain: 'Insulin controls the level of sugar in the blood.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is the hardest substance in the human body?', answer: 'Tooth enamel', wrong: ['Bone', 'Fingernail', 'Hair'], explain: 'Enamel is mostly a hard mineral.', difficulty: 2 },
    { kind: 'number', prompt: 'How many teeth does an adult usually have?', answer: 32, unit: 'teeth', tolerance: 0, explain: 'Including four wisdom teeth.', difficulty: 2 },
    { kind: 'number', prompt: 'How many baby teeth do children have?', answer: 20, unit: 'teeth', tolerance: 0, explain: 'They are replaced by 32 adult teeth.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which blood cells carry oxygen?', answer: 'Red blood cells', wrong: ['White blood cells', 'Platelets', 'Nerve cells'], explain: 'Haemoglobin in them carries oxygen.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which blood cells fight germs?', answer: 'White blood cells', wrong: ['Red blood cells', 'Platelets', 'Skin cells'], explain: 'They are part of the immune system.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which tiny pieces in the blood help it clot when you cut yourself?', answer: 'Platelets', wrong: ['Red blood cells', 'Plasma', 'Neurons'], explain: 'They clump together to plug the wound.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the biggest muscle in the body?', answer: 'Gluteus maximus', wrong: ['Biceps', 'Heart', 'Tongue'], explain: 'It is the main muscle of the buttocks.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is the coloured part of the eye called?', answer: 'Iris', wrong: ['Pupil', 'Retina', 'Cornea'], explain: 'The pupil is the black hole in the middle of it.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which organ filters blood to make urine?', answer: 'Kidneys', wrong: ['Liver', 'Lungs', 'Heart'], explain: 'Urine is then stored in the bladder.', difficulty: 2 },
    { kind: 'mc', prompt: 'What does the skull protect?', answer: 'The brain', wrong: ['The heart', 'The lungs', 'The stomach'], explain: 'The rib cage protects the heart and lungs.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the normal human body temperature, roughly?', answer: '37 °C', wrong: ['30 °C', '42 °C', '25 °C'], explain: 'It varies a little through the day.', difficulty: 2 },
    { kind: 'mc', prompt: 'How many senses are traditionally counted?', answer: '5', wrong: ['3', '7', '10'], explain: 'Sight, hearing, smell, taste and touch; scientists count others too, like balance.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which part of the body do you smell with?', answer: 'Nose', wrong: ['Ears', 'Tongue', 'Fingers'], explain: 'Smell also helps you taste food.', difficulty: 1 },
    { kind: 'tf', prompt: 'You can live with only one kidney.', answer: true, explain: 'One healthy kidney can do the work of two.', difficulty: 2 },
    { kind: 'tf', prompt: 'Babies are born with more bones than adults.', answer: true, explain: 'About 300 bones fuse into 206.', difficulty: 2 },
    { kind: 'tf', prompt: 'Your heart is on the far left of your chest.', answer: false, explain: 'It sits near the middle, tilted slightly to the left.', difficulty: 3 },
    { kind: 'mc', prompt: 'Where in the body are red blood cells made?', answer: 'Bone marrow', wrong: ['The heart', 'The liver', 'The lungs'], explain: 'Marrow inside big bones makes millions every second.', difficulty: 2 },
    { kind: 'mc', prompt: 'What are the tiny air sacs in the lungs called?', answer: 'Alveoli', wrong: ['Villi', 'Neurons', 'Capillaries'], explain: 'Oxygen passes into the blood through their thin walls.', difficulty: 3 },
    { kind: 'mc', prompt: 'Which organ is the body\'s main chemical factory and can regrow?', answer: 'Liver', wrong: ['Heart', 'Brain', 'Spleen'], explain: 'It can regrow from as little as a quarter of its tissue.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is the name of the tube that carries food from your mouth to your stomach?', answer: 'Oesophagus', wrong: ['Trachea', 'Intestine', 'Artery'], explain: 'The trachea, or windpipe, carries air.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which blood vessels carry blood away from the heart?', answer: 'Arteries', wrong: ['Veins', 'Nerves', 'Tendons'], explain: 'Veins carry blood back to the heart.', difficulty: 2 },
    { kind: 'mc', prompt: 'What joins muscles to bones?', answer: 'Tendons', wrong: ['Ligaments', 'Nerves', 'Veins'], explain: 'Ligaments join bone to bone.', difficulty: 3 },
    { kind: 'order', prompt: 'Put the path of food in order.', answer: ['Mouth', 'Oesophagus', 'Stomach', 'Small intestine', 'Large intestine'], orderLabel: 'First to last', explain: 'Most nutrients are absorbed in the small intestine.', difficulty: 2 },
  ],
};

// Typical adult organ weights from Wikipedia (Lungs = both together; skin = ICRP tissue mass, no fat layer).
addFacts(PACK.items, 'massG', { Skin: 3300, Liver: 1500, Brain: 1300, Lungs: 1300, Heart: 300, Spleen: 130, Thyroid: 25 });

export default PACK;
