import { WD, COMMONS } from './_common.mjs';

const UK = 'United Kingdom', US = 'United States', TH = 'Thailand', RU = 'Russia', FR = 'France', TR = 'Turkey', JP = 'Japan', CA = 'Canada', EG = 'Egypt', NO = 'Norway', MM = 'Myanmar', AU = 'Australia', ET = 'Ethiopia', SG = 'Singapore', IR = 'Iran';
const f = (origin, coat) => ({ origin, coat });

export default {
  id: 'cats', title: 'Cat breeds', theme: 'animals', icon: '🐈', kids: true,
  leakExempt: ['cat', 'cats', 'breed'],
  media: 'wiki', photos: 3, depicts: 0, lname: 'asis',
  wdCheckLabel: { origin: 'P495' }, wdP31: ['Q43577'],
  factsMeta: {
    origin: { type: 'cat', label: 'Country of origin', clue: v => `The breed comes from ${v}.` },
    coat: { type: 'cat', label: 'Coat', values: ['Long', 'Medium', 'Short', 'Curly', 'Hairless'], clue: v => (v === 'Hairless' ? 'It has almost no fur.' : v === 'Curly' ? 'Its fur is curly or wavy.' : `Its fur is ${v.toLowerCase()}.`) },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which cat breed is this?",
  tfImgPrompt: "This cat is {aName}.",
  tpl: {"origin": {"ask": "Where does the {name} breed come from?", "askReverse": "Which of these breeds comes from {value}?", "stmt": "The {name} breed comes from {value}."}, "coat": {"ask": "What kind of coat does the {name} have?", "askReverse": "Which of these breeds has a {lvalue} coat?", "stmt": "The {name} has a {lvalue} coat."}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Persian', wp: 'Persian cat', alt: ['Persian cat'], f: f(IR, 'Long'), d: 1, look: ['Himalayan', 'Exotic Shorthair'],
      b: 'A fluffy cat with a long coat and a flat face. It is calm and loves to relax.',
      c: ['Its ancestors came from the country now called Iran.', 'It needs brushing every day.', 'Queen Victoria owned two.', 'It has a round face and a short, flat nose.', 'It has a very long, fluffy coat.'] },
    { n: 'Maine Coon', f: f(US, 'Long'), d: 1, look: ['Norwegian Forest Cat', 'Siberian'],
      b: 'One of the biggest cat breeds, with tufted ears and a bushy tail. It is friendly and loves water.',
      c: ['It is the state cat of Maine.', 'It often enjoys playing with water.', 'It has tufts of fur on the tips of its ears.', 'It is one of the largest pet cat breeds.', 'Its name includes a word for a racoon.'] },
    { n: 'Siamese', wp: 'Siamese cat', alt: ['Siamese cat'], f: f(TH, 'Short'), d: 1, look: ['Himalayan', 'Oriental Shorthair'],
      b: 'A slim, chatty cat with blue eyes and dark ears, face, paws and tail.',
      c: ['Its dark points are caused by a gene that responds to cold.', 'Kittens are born almost white.', 'It is very talkative and loud.', 'It has bright blue almond-shaped eyes.', 'It is named after the old name of Thailand.'] },
    { n: 'Ragdoll', f: f(US, 'Long'), d: 1, look: ['Birman'],
      b: 'A big, gentle cat with blue eyes that often goes floppy when you pick it up.',
      c: ['It was first bred in California in the 1960s.', 'It often follows its owner around like a dog.', 'It has blue eyes and darker points.', 'It goes limp when you pick it up.', 'It is named after a floppy toy.'] },
    { n: 'British Shorthair', f: f(UK, 'Short'), d: 1, look: ['Russian Blue', 'Chartreux'],
      b: 'A round, chunky cat with a thick, plush coat. The classic colour is blue-grey with copper eyes.',
      c: ['It may be the model for the Cheshire Cat.', 'Its ancestors may have arrived with the Romans.', 'It has copper or orange eyes.', 'The best-known colour is blue-grey.', 'It has a dense, short coat and comes from Britain.'] },
    { n: 'Bengal', wp: 'Bengal cat', alt: ['Bengal cat'], f: f(US, 'Short'), d: 1, look: ['Egyptian Mau', 'Ocicat', 'Savannah'],
      b: 'A spotted cat that looks like a little leopard. It was bred from wild leopard cats and pet cats.',
      c: ['It was bred from the wild Asian leopard cat.', 'Its coat can shimmer with a "glitter" effect.', 'It loves to climb and play in water.', 'It has spots or marbled patterns like a wild cat.', 'It shares its name with a tiger from India.'] },
    { n: 'Sphynx', wp: 'Sphynx cat', alt: ['Sphynx cat', 'Sphinx'], f: f(CA, 'Hairless'), d: 1, look: ['Devon Rex', 'Cornish Rex'],
      b: 'A cat with almost no fur and wrinkly skin. It feels warm and soft, like a peach.',
      c: ['It was first bred in Canada in the 1960s.', 'It feels warm, like a peach.', 'It needs regular baths.', 'It has big ears and wrinkly skin.', 'It has almost no fur.'] },
    { n: 'Abyssinian', wp: 'Abyssinian cat', alt: ['Abyssinian cat', 'Aby'], f: f(ET, 'Short'), d: 2, look: ['Somali', 'Singapura'],
      b: 'A slim, active cat with a ticked coat where each hair has bands of colour.',
      c: ['Each hair has several bands of colour.', 'It looks like cats in ancient Egyptian art.', 'It is very active and curious.', 'It has large ears and almond eyes.', 'It is named after an old name for Ethiopia.'] },
    { n: 'Scottish Fold', f: f(UK, 'Short'), d: 1,
      b: 'A cat whose ears fold forward and down, giving it an owl-like face. The fold comes from a gene that can cause joint problems.',
      c: ['All of them descend from a farm cat named Susie.', 'The gene that causes its look can harm joints.', 'It often sits up like an otter.', 'Its ears fold forward and down.', 'It comes from Scotland.'] },
    { n: 'Russian Blue', f: f(RU, 'Short'), d: 2, look: ['British Shorthair', 'Chartreux', 'Korat'],
      b: 'A slim, shy cat with a shimmering silver-blue coat and bright green eyes.',
      c: ['It is said to have come from the port of Arkhangelsk.', 'Its coat has silver-tipped hairs that shimmer.', 'It has vivid green eyes.', 'It is quiet and shy with strangers.', 'Its coat is grey-blue.', 'It is said to have been a favourite of the Tsars.', 'Its coat is thick and plush.'] },
    { n: 'Norwegian Forest Cat', alt: ['Wegie'], f: f(NO, 'Long'), d: 2, look: ['Maine Coon', 'Siberian'],
      b: 'A big, fluffy cat from Scandinavia with a waterproof coat. Legends say it pulled the goddess Freya\'s chariot.',
      c: ['Norse legends say it pulled the goddess Freya\'s chariot.', 'It can climb down trees head-first.', 'Its thick coat is waterproof.', 'It has a bushy tail and tufted ears.', 'It comes from Norway.'] },
    { n: 'Birman', f: f(MM, 'Long'), d: 2, look: ['Ragdoll'],
      b: 'A silky long-haired cat with blue eyes and pure white "gloves" on all four paws.',
      c: ['A legend links it to a temple in Burma.', 'It has blue eyes and darker points.', 'In France it is called the "Sacré de Birmanie".', 'Its four paws are pure white like gloves.', 'Its name comes from an old name for Myanmar.'] },
    { n: 'Burmese', wp: 'Burmese cat', alt: ['Burmese cat'], f: f(MM, 'Short'), d: 2, look: ['Bombay', 'Tonkinese'],
      b: 'A muscular, friendly cat with a glossy coat and golden eyes. All of them go back to one cat named Wong Mau.',
      c: ['The breed comes from one cat named Wong Mau.', 'It is surprisingly heavy for its size.', 'It has golden eyes.', 'Its coat is often a rich sable brown.', 'Its name comes from an old name for Myanmar.'] },
    { n: 'Devon Rex', f: f(UK, 'Curly'), d: 2, look: ['Cornish Rex', 'Sphynx'],
      b: 'An elf-like cat with huge ears and a short, wavy coat. It is playful and mischievous.',
      c: ['It was found in Buckfastleigh in 1960.', 'It is nicknamed the "poodle cat".', 'It has huge ears and big eyes.', 'Its short coat is wavy.', 'It comes from an English county in the south-west.'] },
    { n: 'Cornish Rex', f: f(UK, 'Curly'), d: 3, look: ['Devon Rex'],
      b: 'A slim cat with a short, tightly curled coat that feels like velvet. It can run very fast.',
      c: ['The first one was a kitten named Kallibunker.', 'Its coat has no outer guard hairs.', 'It has a slim body and arched back like a greyhound.', 'Its coat is tightly curled.', 'It comes from the county at the tip of south-west England.'] },
    { n: 'Oriental Shorthair', alt: ['Oriental'], f: f(TH, 'Short'), d: 3, look: ['Siamese'],
      b: 'A slim, long-legged cat with huge ears, closely related to the Siamese, but in hundreds of colours.',
      c: ['It comes in hundreds of colours and patterns.', 'It is very talkative.', 'It has very large ears.', 'It is a close relative of the Siamese.', 'It has short fur.'] },
    { n: 'Exotic Shorthair', alt: ['Exotic'], f: f(US, 'Short'), d: 3, look: ['Persian', 'British Shorthair'],
      b: 'Like a Persian with a short coat. Garfield is often said to look like one.',
      c: ['It was made by crossing Persians and American Shorthairs.', 'It is easier to groom than a Persian.', 'It has a flat face and round eyes.', 'It looks like a short-coated Persian.', 'Garfield is often said to look like one.'] },
    { n: 'American Shorthair', f: f(US, 'Short'), d: 3, look: ['British Shorthair'],
      b: 'A sturdy, easy-going cat whose ancestors came to North America on ships with early settlers.',
      c: ['Its ancestors hunted mice on settlers\' ships.', 'The silver tabby is its best-known colour.', 'It is sturdy and easy-going.', 'It has short, thick fur.', 'It comes from the USA.'] },
    { n: 'Turkish Angora', alt: ['Angora'], f: f(TR, 'Long'), d: 2, look: ['Turkish Van'],
      b: 'An elegant, silky-coated cat from Turkey, often pure white. Ankara Zoo has a breeding programme for it.',
      c: ['Ankara Zoo has bred it for decades.', 'White ones may be deaf, especially with blue eyes.', 'It often has eyes of two different colours.', 'Its coat is silky and is often pure white.', 'It comes from Turkey\'s capital region.', 'It is slim and graceful.', 'It is one of the oldest natural breeds.'] },
    { n: 'Turkish Van', alt: ['swimming cat'], f: f(TR, 'Medium'), d: 3, look: ['Turkish Angora'],
      b: 'A white cat with coloured patches on its head and tail, nicknamed "the swimming cat" because it likes water.',
      c: ['It is nicknamed "the swimming cat".', 'It has a water-resistant coat.', 'Its colour is only on its head and tail.', 'It is mostly white.', 'It is named after a big lake in Turkey.', 'Its coloured tail is often ringed.', 'It comes from the mountains of eastern Anatolia.', 'It is a large, muscular cat.'] },
    { n: 'Manx', wp: 'Manx cat', alt: ['Manx cat'], f: f('Isle of Man', 'Short'), d: 2, look: ['Japanese Bobtail'],
      b: 'A cat from the Isle of Man that is born with no tail or a very short one.',
      c: ['Its back legs are longer than its front legs.', 'Some have a tiny stump called a "stumpy".', 'It runs with a hopping, rabbit-like gait.', 'It appears on Isle of Man coins.', 'It has no tail.'] },
    { n: 'Egyptian Mau', alt: ['Mau'], f: f(EG, 'Short'), d: 2, look: ['Bengal', 'Ocicat'],
      b: 'A naturally spotted cat and one of the fastest pet cats. It has a worried-looking face.',
      c: ['It can run at around 48 km/h.', 'It has a loose flap of skin under its belly.', 'It has gooseberry-green eyes.', 'It has natural spots.', 'It comes from the land of the pharaohs.'] },
    { n: 'Savannah', wp: 'Savannah cat', alt: ['Savannah cat'], f: f(US, 'Short'), d: 2, look: ['Bengal'],
      b: 'A tall, spotted cat bred from a pet cat and a wild African serval. It can leap very high.',
      c: ['It was bred from a pet cat and a wild serval.', 'It can jump about 2.5 metres high.', 'It is one of the tallest cat breeds.', 'It has big ears and spots.', 'It is named after the African grasslands.'] },
    { n: 'Siberian', wp: 'Siberian cat', alt: ['Siberian cat', 'Siberian forest cat'], f: f(RU, 'Long'), d: 2, look: ['Maine Coon', 'Norwegian Forest Cat'],
      b: 'A strong, fluffy cat from the Russian forests with a triple-layer coat for the cold.',
      c: ['It is the national cat of Russia.', 'Its coat has three layers.', 'It is strong and a good jumper.', 'It has a fluffy mane around its neck.', 'It comes from a cold part of Russia.'] },
    { n: 'Japanese Bobtail', f: f(JP, 'Short'), d: 3, look: ['Manx'],
      b: 'A cat with a short, pom-pom tail. It is the cat on the Japanese good-luck "beckoning cat" statues.',
      c: ['Each one\'s tail is as unique as a fingerprint.', 'It inspired the "beckoning cat" lucky charm.', 'It is often white with red and black patches.', 'Its tail looks like a fluffy pom-pom.', 'It comes from Japan.', 'It is very chatty and has a soft voice.', 'It often sits with one paw raised.'] },
    { n: 'Himalayan', wp: 'Himalayan cat', alt: ['Himalayan cat', 'Colourpoint Persian'], f: f(US, 'Long'), d: 3, look: ['Persian', 'Siamese'],
      b: 'A long-haired cat with the flat face of a Persian and the blue eyes and dark points of a Siamese.',
      c: ['It was bred by crossing Persians and Siamese.', 'In Britain it is called the Colourpoint Persian.', 'It has blue eyes and dark points.', 'It has a long, fluffy coat.', 'It is named after a rabbit with similar markings and a mountain range.', 'It needs daily grooming.', 'Its face is flat.'] },
    { n: 'Tonkinese', wp: 'Tonkinese cat', alt: ['Tonk'], f: f(CA, 'Short'), d: 3, look: ['Burmese', 'Siamese'],
      b: 'A friendly cross between the Siamese and the Burmese, with aqua-coloured eyes.',
      c: ['It was developed in Canada.', 'It often has aqua-blue eyes.', 'It is a cross of two Asian breeds.', 'It is playful and friendly.', 'It is named after a region of Vietnam.'] },
    { n: 'Chartreux', f: f(FR, 'Short'), d: 3, look: ['British Shorthair', 'Russian Blue'],
      b: 'A sturdy blue-grey French cat with copper eyes and a smiling face. Legend links it with Carthusian monks.',
      c: ['Legend links it with Carthusian monks.', 'It rarely meows.', 'It has copper or orange eyes.', 'Its woolly coat is blue-grey.', 'It comes from France.'] },
    { n: 'Bombay', wp: 'Bombay cat', alt: ['Bombay cat'], f: f(US, 'Short'), d: 3, look: ['Burmese'],
      b: 'A sleek, all-black cat with copper eyes, bred to look like a mini black panther.',
      c: ['It was bred in Kentucky in the 1950s.', 'It was bred to look like a mini panther.', 'It has copper or golden eyes.', 'Its coat is glossy and jet black.', 'It is named after an Indian city now called Mumbai.'] },
    { n: 'Ocicat', f: f(US, 'Short'), d: 3, look: ['Bengal', 'Egyptian Mau'],
      b: 'A spotted cat that looks wild, but it has no wild cat in its family tree. It came from a Siamese–Abyssinian cross.',
      c: ['It has no wild ancestry at all.', 'It came from a Siamese and Abyssinian cross.', 'It is spotted like a wild cat.', 'It is very sociable.', 'It is named after the ocelot.'] },
    { n: 'Munchkin', wp: 'Munchkin cat', alt: ['Munchkin cat'], f: f(US, 'Short'), d: 2,
      b: 'A cat with very short legs caused by a natural gene. Some groups refuse to recognise it because of health worries.',
      c: ['Some cat groups refuse to recognise it.', 'It was found in Louisiana in 1983.', 'It is sometimes called the "sausage cat".', 'Its legs are very short.', 'It is named after characters in "The Wizard of Oz".'] },
    { n: 'Korat', f: f(TH, 'Short'), d: 3, look: ['Russian Blue'],
      b: 'A silver-blue cat from Thailand with green eyes. In Thailand it is a symbol of good luck, given as a wedding gift.',
      c: ['It appears in an old Thai book of cat poems.', 'It is given as a good-luck wedding gift.', 'Its face is heart-shaped.', 'It has a silver-blue coat and green eyes.', 'It is named after a Thai province.'] },
    { n: 'Australian Mist', f: f(AU, 'Short'), d: 3,
      b: 'A gentle spotted cat developed in Sydney in the 1970s. It is happy to live indoors.',
      c: ['Dr Truda Straede developed it.', 'It was first called the Spotted Mist.', 'It is happy to live indoors.', 'It has a soft spotted or marbled coat.', 'It was the first breed developed in Australia.', 'It was bred from Burmese, Abyssinian and moggy cats.', 'It is calm and loves to be handled.', 'Its coat has a misty veil of ticked hairs.'] },
    { n: 'Somali', wp: 'Somali cat', alt: ['Somali cat'], f: f(US, 'Long'), d: 3, look: ['Abyssinian'],
      b: 'A long-haired version of the Abyssinian, with a bushy fox-like tail.',
      c: ['It is a long-haired version of the Abyssinian.', 'It is nicknamed the "fox cat".', 'It has a big bushy tail.', 'Each hair has bands of colour.', 'It is named after a country next to Ethiopia.'] },
    { n: 'Singapura', wp: 'Singapura cat', alt: ['Singapura cat'], f: f(SG, 'Short'), d: 3, look: ['Abyssinian'],
      b: 'One of the smallest cat breeds, with big eyes and ears and a ticked sepia coat.',
      c: ['It is one of the smallest cat breeds.', 'Its name means "lion city".', 'It has very large eyes and ears.', 'Its coat is ticked like an Abyssinian\'s.', 'It is named after a small island country.'] },
    { n: 'LaPerm', f: f(US, 'Curly'), d: 3, look: ['Devon Rex', 'Selkirk Rex'],
      b: 'A cat with a loose, curly coat. The first one, Curly, was born bald on a farm in Oregon.',
      c: ['The first one was born on an Oregon farm in 1982.', 'Kittens may be born bald.', 'Its coat feels springy.', 'Its fur is curly.', 'It is named after a curly hairstyle.'] },
    { n: 'Selkirk Rex', f: f(US, 'Curly'), d: 3, look: ['LaPerm', 'Devon Rex'],
      b: 'A big, cuddly cat with a thick curly coat, first found in Montana in 1987.',
      c: ['The first one was found in Montana in 1987.', 'It comes in long and short coats.', 'Its whiskers are curly too.', 'Its coat is thick and curly.', 'It is sometimes called "the cat in sheep\'s clothing".'] },
  ],
  fakes: ['Alpine Snow Mau', 'Nordic Velvet Rex', 'Highland Curlpaw', 'Tasmanian Mist', 'Celtic Bluefold', 'Andean Shorthair', 'Moroccan Tufted Cat'],
  questions: [
    { kind: 'mc', prompt: 'Which cat breed has almost no fur?', answer: 'Sphynx', wrong: ['Persian', 'Maine Coon', 'Ragdoll'], explain: 'Sphynx cats have only fine down.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which cat breed is born without a tail?', answer: 'Manx', wrong: ['Siamese', 'Persian', 'Bengal'], explain: 'It comes from the Isle of Man.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which cat breed goes floppy when picked up?', answer: 'Ragdoll', wrong: ['Siamese', 'Abyssinian', 'Bengal'], explain: 'The name comes from this floppy habit.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which breed was bred from wild Asian leopard cats?', answer: 'Bengal', wrong: ['Ocicat', 'Egyptian Mau', 'Abyssinian'], explain: 'Bengals were crossed with leopard cats in the USA.', difficulty: 2 },
    { kind: 'mc', prompt: 'Siamese cats come from which country, once called Siam?', answer: 'Thailand', wrong: ['Japan', 'India', 'China'], explain: 'Siam was renamed Thailand in 1939.', difficulty: 2 },
    { kind: 'tf', prompt: 'Siamese kittens are born almost white.', answer: true, explain: 'Their darker points develop as they grow, in cooler parts of the body.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which breed is the state cat of Maine?', answer: 'Maine Coon', wrong: ['American Shorthair', 'Persian', 'Siberian'], explain: 'It developed among farm cats in Maine.', difficulty: 2 },
    { kind: 'tf', prompt: 'The Ocicat has wild ocelot ancestors.', answer: false, explain: 'It only looks wild; it came from Siamese and Abyssinian crosses.', difficulty: 3 },
    { kind: 'mc', prompt: 'A baby cat is called a…', answer: 'Kitten', wrong: ['Cub', 'Pup', 'Calf'], explain: 'Young cats are kittens.', difficulty: 1 },
    { kind: 'mc', prompt: 'What sound does a happy cat often make?', answer: 'Purr', wrong: ['Bark', 'Moo', 'Quack'], explain: 'Cats purr when they are relaxed.', difficulty: 1 },
    { kind: 'tf', prompt: 'Cats use their whiskers to help feel their way around.', answer: true, explain: 'Whiskers sense tiny movements in the air.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which cat breed has ears that fold forward?', answer: 'Scottish Fold', wrong: ['Siamese', 'Persian', 'Maine Coon'], explain: 'Its folded ears give it an owl-like face.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which cat breed is very fluffy with a flat face?', answer: 'Persian', wrong: ['Sphynx', 'Siamese', 'Bengal'], explain: 'Persians need brushing every day.', difficulty: 1 },
  ],
};
