import { WD, COMMONS } from './_common.mjs';

const TR = 'Triassic', JU = 'Jurassic', CR = 'Cretaceous', PG = 'Paleogene', NG = 'Neogene', QU = 'Quaternary', PE = 'Permian', DV = 'Devonian', CB = 'Carboniferous';
const C = 'Carnivore', H = 'Herbivore', O = 'Omnivore', P = 'Fish-eater';
const f = (period, mya, diet, dinosaur, lengthM, found, extra = {}) => ({ period, mya, diet, dinosaur, ...(lengthM ? { lengthM } : {}), found, ...extra });

export default {
  id: 'dinosaurs', title: 'Dinosaurs & prehistoric life', theme: 'animals', icon: '🦖', kids: true,
  noun: 'prehistoric animal', fakePrompt: 'Which of these prehistoric animals is made up?',
  leakExempt: ['dinosaur', 'saurus', 'sauru'],
  media: 'wiki', photos: 3, depicts: 0, lname: 'asis',
  ranges: { lengthM: [0.3, 40], mya: [0.004, 400], wingspanM: [0.5, 12] },
  factsMeta: {
    period: { type: 'cat', label: 'Period', values: [DV, CB, PE, TR, JU, CR, PG, NG, QU], clue: v => `It lived in the ${v} period.` },
    mya: { type: 'num', label: 'How long ago it lived', unit: 'million years ago', askNumber: 'About how many million years ago did {name} live?', higherLabel: 'Older', clue: v => (v < 1 ? 'It lived within the last million years.' : `It lived about ${v} million years ago.`) },
    diet: { type: 'cat', label: 'Diet', values: [C, H, O, P], clue: v => `It was a ${v.toLowerCase()}.` },
    dinosaur: { type: 'bool', label: 'A dinosaur', yes: 'Dinosaur', no: 'Not a dinosaur', clue: v => (v ? null : 'It was not a dinosaur.') },
    lengthM: { type: 'num', label: 'Length', unit: 'm', higherLabel: 'Longer', clue: v => `It grew to about ${v} m long.` },
    wingspanM: { type: 'num', label: 'Wingspan', unit: 'm', higherLabel: 'Wider', clue: v => `Its wingspan was about ${v} m.` },
    found: { type: 'cat', label: 'Fossils found in', clue: v => `Its fossils were found in ${v}.` },
  },
  imgPrompt: "Which of these is {lname}?",
  nameImgPrompt: "Which prehistoric animal is this?",
  tfImgPrompt: "This is {lname}.",
  tpl: {"period": {"ask": "In which period did {lname} live?", "askReverse": "Which of these lived in the {value} period?", "stmt": "{lname} lived in the {value} period."}, "mya": {"askHigh": "Which of these lived longest ago?", "askLow": "Which of these lived most recently?", "minRatio": 1.3}, "diet": {"ask": "What did {lname} eat?", "askReverse": "Which of these was {aValue}?", "stmt": "{lname} was {aValue}."}, "dinosaur": {"askBool": "Which of these was a dinosaur?", "stmt": "{lname} was a dinosaur."}, "lengthM": {"askHigh": "Which of these was the longest?", "askLow": "Which of these was the shortest?"}, "wingspanM": {"askHigh": "Which of these had the widest wingspan?"}, "found": {"ask": "Where were fossils of {lname} found?", "askReverse": "Which of these has fossils from {value}?", "stmt": "Fossils of {lname} were found in {value}.", "exclusive": false}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Tyrannosaurus rex', alt: ['T. rex', 'T-rex', 'Tyrannosaurus'], wp: 'Tyrannosaurus', f: f(CR, 67, C, true, 12, 'North America'), d: 1, look: ['Giganotosaurus', 'Allosaurus'],
      b: 'One of the biggest meat-eating dinosaurs ever. It had a huge head, strong jaws and tiny arms.',
      c: ['The most complete skeleton is nicknamed "Sue".', 'Its bite was one of the strongest of any land animal.', 'Its teeth were as big as bananas.', 'It had tiny arms with two fingers.', 'Its name means "tyrant lizard king".'] },
    { n: 'Triceratops', f: f(CR, 67, H, true, 9, 'North America'), d: 1, look: ['Protoceratops'],
      b: 'A big plant-eater with three horns and a bony frill. It lived at the same time as T. rex.',
      c: ['It lived at the same time and place as T. rex.', 'It had a beak like a parrot.', 'It had a huge bony frill.', 'It had two long horns and one short one.', 'Its name means "three-horned face".'] },
    { n: 'Stegosaurus', f: f(JU, 152, H, true, 9, 'North America'), d: 1, look: ['Ankylosaurus'],
      b: 'A plant-eater with big plates along its back and a spiked tail. Its brain was tiny for its size.',
      c: ['Its tail spikes are called a "thagomizer".', 'Its brain was tiny, often compared to a walnut.', 'It lived long before T. rex.', 'It had sharp spikes on its tail.', 'It had big bony plates down its back.'] },
    { n: 'Velociraptor', alt: ['raptor'], f: f(CR, 74, C, true, 2, 'Asia'), d: 1, look: ['Deinonychus'],
      b: 'A turkey-sized feathered hunter from Mongolia. Films made it much bigger than it really was.',
      c: ['One fossil was found locked in a fight with a Protoceratops.', 'It had feathers.', 'It was only about the size of a turkey.', 'It had a big curved claw on each foot.', 'The "Jurassic Park" films made it famous.'] },
    { n: 'Brachiosaurus', f: f(JU, 154, H, true, 22, 'North America'), d: 1, look: ['Diplodocus', 'Brontosaurus'],
      b: 'A giant long-necked plant-eater whose front legs were longer than its back legs, like a giraffe.',
      c: ['Its name means "arm lizard".', 'Its front legs were longer than its back legs.', 'It could reach leaves high in trees.', 'It held its long neck up like a giraffe.', 'It was a huge long-necked sauropod.'] },
    { n: 'Diplodocus', f: f(JU, 152, H, true, 26, 'North America'), d: 1, look: ['Brontosaurus', 'Brachiosaurus'],
      b: 'A very long, slim, long-necked dinosaur with a whip-like tail. A cast called "Dippy" was famous in London.',
      c: ['A cast called "Dippy" stood in London\'s Natural History Museum.', 'Its tail may have cracked like a whip.', 'Its teeth were peg-like, for stripping leaves.', 'It was one of the longest dinosaurs.', 'It had a very long neck and tail.'] },
    { n: 'Brontosaurus', f: f(JU, 153, H, true, 22, 'North America'), d: 1, look: ['Diplodocus', 'Apatosaurus'],
      b: 'A huge long-necked dinosaur. Scientists dropped its name for a century, then brought it back in 2015.',
      c: ['Its name was brought back by scientists in 2015.', 'It was once thought to be the same as Apatosaurus.', 'It had a very thick neck.', 'It was a long-necked sauropod.', 'Its name means "thunder lizard".'] },
    { n: 'Apatosaurus', f: f(JU, 152, H, true, 22, 'North America'), d: 3, look: ['Brontosaurus', 'Diplodocus'],
      b: 'A huge, heavy long-necked dinosaur, a close cousin of Brontosaurus.',
      c: ['Its name means "deceptive lizard".', 'It was named by Othniel Marsh in 1877.', 'Its neck was very thick and strong.', 'It is a close cousin of Brontosaurus.', 'It was a giant long-necked plant-eater.'] },
    { n: 'Spinosaurus', f: f(CR, 97, P, true, 14, 'Africa'), d: 1, look: ['Baryonyx'],
      b: 'A huge meat-eater with a tall sail on its back. It hunted fish in rivers in North Africa.',
      c: ['Its first fossils were destroyed in World War II.', 'It had a long snout like a crocodile.', 'It hunted fish in rivers.', 'It may have been longer than T. rex.', 'It had a big sail on its back.'] },
    { n: 'Allosaurus', f: f(JU, 152, C, true, 9.5, 'North America'), d: 2, look: ['Tyrannosaurus rex'],
      b: 'The top predator of the late Jurassic. It hunted long before T. rex appeared.',
      c: ['It lived about 80 million years before T. rex.', 'It had bony crests above its eyes.', 'It had three-fingered hands with big claws.', 'It may have hunted Stegosaurus.', 'Its name means "different lizard".'] },
    { n: 'Ankylosaurus', f: f(CR, 67, H, true, 7, 'North America'), d: 1, look: ['Stegosaurus', 'Minmi'],
      b: 'A plant-eater covered in bony armour, like a tank, with a big club on its tail.',
      c: ['Even its eyelids had armour.', 'It lived at the same time as T. rex.', 'It was low and wide, like a tank.', 'Its tail ended in a heavy bony club.', 'It was covered in bony armour.'] },
    { n: 'Parasaurolophus', f: f(CR, 75, H, true, 9.5, 'North America'), d: 2, look: ['Iguanodon'],
      b: 'A duck-billed dinosaur with a long, hollow crest on its head that may have been used to make loud calls.',
      c: ['Air could flow through tubes inside its crest.', 'It may have made trumpet-like calls.', 'It had a duck-like bill.', 'It could walk on two or four legs.', 'It had a long, curved tube-shaped crest.'] },
    { n: 'Iguanodon', f: f(CR, 125, H, true, 10, 'Europe'), d: 2, look: ['Parasaurolophus', 'Muttaburrasaurus'],
      b: 'One of the first dinosaurs ever named, in 1825. Its thumbs were big spikes.',
      c: ['It was one of the first dinosaurs to be named.', 'Its thumb spike was first put on its nose by mistake.', 'Many skeletons were found in a Belgian coal mine.', 'It had a spike for a thumb.', 'Its name means "iguana tooth".'] },
    { n: 'Pachycephalosaurus', f: f(CR, 67, H, true, 4.5, 'North America'), d: 2,
      b: 'A dinosaur with a thick, dome-shaped skull up to 25 cm thick. It may have head-butted rivals.',
      c: ['Its skull roof was up to 25 cm thick.', 'Bony knobs ringed its dome.', 'It walked on two legs.', 'It may have head-butted rivals.', 'Its name means "thick-headed lizard".'] },
    { n: 'Archaeopteryx', f: f(JU, 150, C, true, 0.5, 'Europe'), d: 2,
      b: 'A crow-sized feathered dinosaur from Germany. It was found in 1861 and shows that birds came from dinosaurs.',
      c: ['It was found in Germany in 1861, just after Darwin\'s "Origin of Species".', 'It had teeth, claws and a bony tail.', 'It is sometimes called the first bird.', 'It had feathered wings.', 'It was about the size of a crow.'] },
    { n: 'Giganotosaurus', f: f(CR, 98, C, true, 12.5, 'South America'), d: 2, look: ['Tyrannosaurus rex', 'Carnotaurus'],
      b: 'A huge meat-eater from Argentina, as big as or bigger than T. rex.',
      c: ['It was found by an amateur fossil hunter in 1993.', 'It lived millions of years before T. rex.', 'Its skull was about 1.6 m long.', 'It was found in Argentina.', 'Its name means "giant southern lizard".'] },
    { n: 'Carnotaurus', f: f(CR, 71, C, true, 8, 'South America'), d: 2, look: ['Giganotosaurus'],
      b: 'A fast meat-eater from Argentina with two horns above its eyes and even tinier arms than T. rex.',
      c: ['Its skin impressions show rows of bumps.', 'Its arms were even smaller than T. rex\'s.', 'It was found in Argentina.', 'It had two horns above its eyes.', 'Its name means "meat-eating bull".'] },
    { n: 'Dilophosaurus', f: f(JU, 193, C, true, 7, 'North America'), d: 2,
      b: 'An early Jurassic meat-eater with two thin crests on its head. Unlike in films, there is no evidence it spat venom.',
      c: ['There is no evidence it spat venom or had a frill.', 'It lived in what is now Arizona.', 'It was one of the first big meat-eaters.', 'It had two thin crests on its head.', 'Its name means "two-crested lizard".'] },
    { n: 'Compsognathus', f: f(JU, 150, C, true, 1, 'Europe'), d: 2,
      b: 'A tiny meat-eating dinosaur about the size of a chicken. It ate lizards.',
      c: ['A lizard was found inside one\'s stomach.', 'Its fossils come from the same rocks as Archaeopteryx.', 'It was about the size of a chicken.', 'It was one of the smallest dinosaurs known.', 'Its name means "pretty jaw".'] },
    { n: 'Argentinosaurus', f: f(CR, 94, H, true, 35, 'South America'), d: 2, look: ['Brachiosaurus'],
      b: 'One of the biggest land animals ever. It may have weighed as much as 10 elephants or more.',
      c: ['It may have weighed around 70 tonnes.', 'A single backbone is about as tall as a person.', 'It was a titanosaur.', 'It is known from only a few bones.', 'It is named after the country where it was found.'] },
    { n: 'Gallimimus', f: f(CR, 70, O, true, 6, 'Asia'), d: 2,
      b: 'A fast, ostrich-like dinosaur from Mongolia with a toothless beak.',
      c: ['It ran in a flock in "Jurassic Park".', 'It had a toothless beak.', 'It may have run at 50 km/h.', 'It looked like an ostrich.', 'Its name means "chicken mimic".'] },
    { n: 'Oviraptor', f: f(CR, 75, O, true, 1.6, 'Asia'), d: 2,
      b: 'A feathered dinosaur with a parrot-like beak. Its name means "egg thief", but it was really guarding its own eggs.',
      c: ['It was found on a nest it was actually guarding.', 'It had a toothless, parrot-like beak.', 'It was feathered.', 'It lived in Mongolia.', 'Its name means "egg thief".'] },
    { n: 'Therizinosaurus', f: f(CR, 70, H, true, 10, 'Asia'), d: 3,
      b: 'A strange plant-eating dinosaur with giant claws up to a metre long on its hands.',
      c: ['Its claws were first thought to belong to a giant turtle.', 'It was a plant-eater despite its claws.', 'It had a pot belly.', 'Its hand claws were up to a metre long.', 'Its name means "scythe lizard".'] },
    { n: 'Deinonychus', f: f(CR, 112, C, true, 3.4, 'North America'), d: 3, look: ['Velociraptor'],
      b: 'A wolf-sized feathered hunter with a big sickle claw. It helped scientists see that dinosaurs were active and bird-like.',
      c: ['Its discovery helped spark the "dinosaur renaissance".', 'The "Jurassic Park" raptors were based on it.', 'It had a big sickle claw on each foot.', 'It was about the size of a wolf.', 'Its name means "terrible claw".'] },
    { n: 'Maiasaura', f: f(CR, 77, H, true, 9, 'North America'), d: 3,
      b: 'A duck-billed dinosaur found with nests, eggs and babies, showing it cared for its young.',
      c: ['It was the first dinosaur taken into space, as a bone fragment.', 'It nested in huge colonies.', 'It was found with eggs and babies.', 'It was a duck-billed dinosaur.', 'Its name means "good mother lizard".'] },
    { n: 'Protoceratops', f: f(CR, 73, H, true, 1.8, 'Asia'), d: 3, look: ['Triceratops'],
      b: 'A sheep-sized, beaked dinosaur with a frill and no big horns. It may have inspired legends of griffins.',
      c: ['Its fossils may have inspired the griffin legend.', 'One was found locked in a fight with a Velociraptor.', 'It had a frill but no long horns.', 'It was about the size of a sheep.', 'Its name means "first horned face".'] },
    { n: 'Baryonyx', f: f(CR, 125, P, true, 9, 'Europe'), d: 3, look: ['Spinosaurus'],
      b: 'A fish-eating dinosaur with a crocodile-like snout, found in a Surrey clay pit in 1983.',
      c: ['It was found by an amateur fossil hunter in Surrey in 1983.', 'Fish scales were found in its stomach.', 'It had a long, narrow snout like a crocodile.', 'It had a huge thumb claw.', 'Its name means "heavy claw".'] },
    { n: 'Coelophysis', f: f(TR, 210, C, true, 3, 'North America'), d: 3,
      b: 'A small, slim early dinosaur. Hundreds of skeletons were found together at Ghost Ranch in New Mexico.',
      c: ['A skull went to the Mir space station in 1998.', 'Hundreds were found together at Ghost Ranch.', 'It had hollow bones.', 'It was slim and fast.', 'It is the state fossil of New Mexico.'] },
    { n: 'Plateosaurus', f: f(TR, 214, H, true, 8, 'Europe'), d: 3,
      b: 'One of the first big plant-eating dinosaurs, from the late Triassic of Europe.',
      c: ['Over 100 skeletons have been found.', 'Many were trapped in mud in Germany.', 'It was an early relative of the long-necked giants.', 'It walked on two legs.', 'Its name means "flat lizard".'] },
    { n: 'Herrerasaurus', f: f(TR, 230, C, true, 4.5, 'South America'), d: 3,
      b: 'One of the earliest dinosaurs known, from Argentina, about 230 million years ago.',
      c: ['It is named after the farmer who found it.', 'It lived in the Valley of the Moon in Argentina.', 'It was one of the first meat-eating dinosaurs.', 'It walked on two legs.', 'It is one of the oldest dinosaurs known.'] },
    { n: 'Muttaburrasaurus', f: f(CR, 105, H, true, 8, 'Australia'), d: 3, look: ['Iguanodon'],
      b: 'A big plant-eating dinosaur from Queensland with a bump on its snout.',
      c: ['It had a big hollow bump on its snout.', 'It may have eaten tough plants with slicing teeth.', 'It is related to Iguanodon.', 'It was found in Queensland in 1963.', 'It is named after a small Australian town.'] },
    { n: 'Australovenator', f: f(CR, 95, C, true, 6, 'Australia'), d: 3,
      b: 'A fast, light meat-eater from Queensland nicknamed "Banjo".',
      c: ['Its nickname is "Banjo".', 'It is nicknamed after the poet Banjo Paterson.', 'It was found near Winton.', 'It had big hand claws.', 'Its name means "southern hunter".'] },
    { n: 'Leaellynasaura', f: f(CR, 110, H, true, 2, 'Australia'), d: 3,
      b: 'A small plant-eater from Victoria that lived near the South Pole when Australia was further south.',
      c: ['It lived through long polar winters.', 'It had a very long tail.', 'It had big eyes, perhaps for the dark.', 'It was found at Dinosaur Cove in Victoria.', 'It is named after a girl called Leaellyn.'] },
    { n: 'Minmi', wp: 'Minmi (dinosaur)', f: f(CR, 115, H, true, 3, 'Australia'), d: 3, look: ['Ankylosaurus'],
      b: 'A small armoured dinosaur from Queensland. It has one of the shortest dinosaur names.',
      c: ['It has one of the shortest dinosaur names.', 'Its stomach held seeds and fruit.', 'It was an early ankylosaur.', 'It was covered in bony armour.', 'It is named after a creek crossing in Queensland.'] },
    { n: 'Pteranodon', f: f(CR, 86, P, false, null, 'North America', { wingspanM: 6 }), d: 1, look: ['Quetzalcoatlus'],
      b: 'A flying reptile with a long crest and no teeth. It soared over the sea and ate fish. It was not a dinosaur.',
      c: ['Its name means "wing without teeth".', 'It had a long crest on the back of its head.', 'It flew over an inland sea that covered Kansas.', 'It was a pterosaur, not a dinosaur.', 'It was a flying reptile.'] },
    { n: 'Quetzalcoatlus', f: f(CR, 68, C, false, null, 'North America', { wingspanM: 10 }), d: 2, look: ['Pteranodon'],
      b: 'One of the largest flying animals ever, as tall as a giraffe when standing. It hunted on the ground like a stork.',
      c: ['Standing, it was as tall as a giraffe.', 'It probably hunted small animals on foot.', 'It was found in Texas.', 'It was a giant pterosaur.', 'It is named after an Aztec feathered serpent god.'] },
    { n: 'Plesiosaurus', f: f(JU, 190, P, false, 3, 'Europe'), d: 2, look: ['Ichthyosaurus'],
      b: 'A marine reptile with a long neck and four flippers. Mary Anning found the first complete one.',
      c: ['Mary Anning found the first complete skeleton.', 'It swam with four flippers.', 'Some say the Loch Ness Monster looks like it.', 'It had a long neck and a small head.', 'It was a sea reptile, not a dinosaur.'] },
    { n: 'Mosasaurus', f: f(CR, 70, C, false, 15, 'Europe'), d: 1, look: ['Plesiosaurus'],
      b: 'A giant sea reptile related to lizards and snakes. It was a top predator of the late Cretaceous seas.',
      c: ['Its first fossil was found near the Dutch city of Maastricht.', 'It was related to monitor lizards and snakes.', 'It had a second row of teeth on the roof of its mouth.', 'It ate fish, turtles and other sea reptiles.', 'It was a huge sea reptile, not a dinosaur.'] },
    { n: 'Ichthyosaurus', f: f(JU, 190, P, false, 2, 'Europe'), d: 2, look: ['Plesiosaurus'],
      b: 'A dolphin-shaped sea reptile. It gave birth to live young in the sea.',
      c: ['Mary Anning\'s brother found the first skull.', 'It gave birth to live young.', 'It had huge eyes.', 'It looked like a dolphin.', 'Its name means "fish lizard".'] },
    { n: 'Dimetrodon', f: f(PE, 285, C, false, 3.5, 'North America'), d: 2, look: ['Spinosaurus'],
      b: 'A sail-backed animal that lived before the dinosaurs. It was more closely related to mammals than to dinosaurs.',
      c: ['It was more closely related to mammals than to reptiles like lizards.', 'It lived tens of millions of years before the first dinosaurs.', 'Its name means "two measures of teeth".', 'It is often wrongly sold as a toy dinosaur.', 'It had a tall sail on its back.'] },
    { n: 'Megalodon', alt: ['Otodus megalodon'], f: f(NG, 10, C, false, 15, 'Worldwide'), d: 1,
      b: 'The biggest shark that ever lived. Its teeth were as big as a person\'s hand.',
      c: ['It probably ate whales.', 'It is known mainly from its teeth.', 'It died out about 3.6 million years ago.', 'Its teeth could be over 17 cm long.', 'It was a giant prehistoric shark.'] },
    { n: 'Woolly mammoth', ln: 'the woolly mammoth', alt: ['mammoth'], wp: 'Woolly mammoth', f: f(QU, 0.3, H, false, 3.4, 'Worldwide'), d: 1, look: ['Woolly rhinoceros'],
      b: 'A hairy relative of elephants with long curved tusks. It lived in the Ice Age, and the last ones died about 4,000 years ago.',
      c: ['The last ones lived on Wrangel Island about 4,000 years ago.', 'Frozen bodies have been found in Siberian ice.', 'Early humans painted it on cave walls.', 'It had long curved tusks.', 'It was a hairy elephant of the Ice Age.'] },
    { n: 'Smilodon', alt: ['sabre-toothed tiger', 'sabre-toothed cat', 'saber-toothed tiger'], f: f(QU, 0.5, C, false, 1.9, 'the Americas'), d: 1,
      b: 'A big Ice Age cat with huge sabre-shaped teeth. Many were found trapped in the La Brea tar pits.',
      c: ['Thousands were found in the La Brea tar pits.', 'It was not closely related to real tigers.', 'Its fangs were up to about 28 cm long.', 'It lived in the Americas during the Ice Age.', 'It had two huge sabre-like teeth.'] },
    { n: 'Diprotodon', f: f(QU, 0.5, H, false, 3, 'Australia'), d: 2,
      b: 'The biggest marsupial ever, a wombat relative about the size of a hippo. It lived in Australia until about 40,000 years ago.',
      c: ['It was about the size of a hippo.', 'It is related to wombats.', 'Females carried babies in a pouch.', 'It lived in Australia in the Ice Age.', 'It was the largest marsupial ever.'] },
    { n: 'Megatherium', alt: ['giant ground sloth'], f: f(QU, 0.5, H, false, 6, 'South America'), d: 2,
      b: 'A giant ground sloth as big as an elephant. It could stand on its back legs to reach leaves.',
      c: ['Charles Darwin collected its fossils.', 'It could stand on its back legs.', 'It had huge claws.', 'It lived in South America.', 'It was a giant sloth.'] },
    { n: 'Woolly rhinoceros', ln: 'the woolly rhinoceros', alt: ['woolly rhino'], f: f(QU, 0.3, H, false, 3.6, 'Europe and Asia'), d: 2, look: ['Woolly mammoth'],
      b: 'A shaggy Ice Age rhino with a long, flat front horn. Early humans painted it in caves.',
      c: ['It is painted in the Chauvet Cave in France.', 'Its front horn was flat and up to a metre long.', 'Frozen ones have been found in Siberia.', 'It had thick fur.', 'It was a hairy rhino of the Ice Age.'] },
    { n: 'Titanoboa', f: f(PG, 60, C, false, 13, 'South America'), d: 2,
      b: 'The biggest snake ever found, about 13 metres long. It lived in a hot rainforest in Colombia after the dinosaurs died out.',
      c: ['It lived soon after the dinosaurs died out.', 'It was found in a coal mine in Colombia.', 'It may have eaten crocodile relatives.', 'It was about 13 metres long.', 'It was the biggest snake ever.'] },
    { n: 'Dunkleosteus', f: f(DV, 375, C, false, 4, 'North America'), d: 3,
      b: 'A huge armoured fish with bony blades instead of teeth. It lived long before the dinosaurs.',
      c: ['It had sharp bony plates instead of teeth.', 'It could open its mouth extremely fast.', 'Its head was covered in armour.', 'It lived in the Devonian "age of fishes".', 'It was a giant armoured fish.'] },
    { n: 'Meganeura', f: f(CB, 300, C, false, null, 'Europe', { wingspanM: 0.7 }), d: 3,
      b: 'A giant dragonfly-like insect with wings about 70 cm across. It lived long before the dinosaurs.',
      c: ['It was found in a French coal mine.', 'Higher oxygen levels may have let insects grow so big.', 'It hunted other insects.', 'Its wings were about 70 cm across.', 'It was a giant dragonfly relative.'] },
    { n: 'Megalania', alt: ['Varanus priscus'], f: f(QU, 0.5, C, false, 5, 'Australia'), d: 3,
      b: 'A giant monitor lizard that lived in Australia during the Ice Age. It was much bigger than a Komodo dragon.',
      c: ['It may have had a venomous bite.', 'It lived alongside the first Australians.', 'It was much bigger than a Komodo dragon.', 'It lived in Australia.', 'It was a giant prehistoric lizard.'] },
    { n: 'Thylacoleo', alt: ['marsupial lion'], f: f(QU, 0.5, C, false, 1.5, 'Australia'), d: 3,
      b: 'The "marsupial lion" of Ice Age Australia. It had the strongest bite for its size of any known mammal.',
      c: ['It had a huge thumb claw.', 'It had slicing teeth like bolt cutters.', 'It had one of the strongest bites for its size of any mammal.', 'It lived in Australia.', 'It is called the marsupial lion.'] },
  ],
  fakes: ['Glacierosaurus', 'Thunderclawdon', 'Spiketopsaurus', 'Crystallodon', 'Nimbusaurus', 'Hydrocephalix', 'Velocitrex', 'Gigaspinax'],
  questions: [
    { kind: 'mc', prompt: 'Which dinosaur had three horns and a bony frill?', answer: 'Triceratops', wrong: ['Stegosaurus', 'Velociraptor', 'Diplodocus'], explain: 'Its name means "three-horned face".', difficulty: 1 },
    { kind: 'tf', prompt: 'Pterosaurs, like Pteranodon, were dinosaurs.', answer: false, explain: 'Pterosaurs were flying reptiles, close cousins of dinosaurs.', difficulty: 2 },
    { kind: 'tf', prompt: 'Birds are living dinosaurs.', answer: true, explain: 'Birds evolved from small feathered theropod dinosaurs.', difficulty: 2 },
    { kind: 'tf', prompt: 'Stegosaurus and T. rex lived at the same time.', answer: false, explain: 'About 80 million years separate them; T. rex lived closer in time to us.', difficulty: 2 },
    { kind: 'mc', prompt: 'What probably caused the dinosaurs (except birds) to die out 66 million years ago?', answer: 'An asteroid impact', wrong: ['An ice age', 'Humans hunting them', 'A plague'], explain: 'The Chicxulub impact in Mexico caused a global catastrophe.', difficulty: 1 },
    { kind: 'tf', prompt: 'People and non-bird dinosaurs lived at the same time.', answer: false, explain: 'The last non-bird dinosaurs died out about 66 million years before humans appeared.', difficulty: 1 },
    { kind: 'mc', prompt: 'What does the word "dinosaur" mean?', answer: 'Terrible lizard', wrong: ['Giant bird', 'Old monster', 'Thunder beast'], explain: 'Richard Owen coined it in 1842.', difficulty: 2 },
    { kind: 'mc', prompt: 'Who found the first complete Plesiosaurus skeleton on the Dorset coast?', answer: 'Mary Anning', wrong: ['Charles Darwin', 'Richard Owen', 'Marie Curie'], explain: 'She found it at Lyme Regis in 1823.', difficulty: 2 },
    { kind: 'order', prompt: 'Put the periods in order, oldest first.', answer: ['Triassic', 'Jurassic', 'Cretaceous'], orderLabel: 'Oldest to youngest', explain: 'Together they make up the Mesozoic, the age of dinosaurs.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the biggest shark that ever lived?', answer: 'Megalodon', wrong: ['Great white shark', 'Tiger shark', 'Hammerhead shark'], explain: 'Megalodon may have reached about 15 m or more.', difficulty: 1 },
    { kind: 'mc', prompt: 'Where were thousands of Smilodon fossils found?', answer: 'La Brea tar pits', wrong: ['The Sahara Desert', 'Antarctica', 'The Great Barrier Reef'], explain: 'Animals got stuck in natural asphalt in Los Angeles.', difficulty: 3 },
    { kind: 'mc', prompt: 'What are scientists who study fossils called?', answer: 'Palaeontologists', wrong: ['Archaeologists', 'Astronomers', 'Geographers'], explain: 'Archaeologists study human history; palaeontologists study ancient life.', difficulty: 2 },
  ],
};
