import { WD, COMMONS } from './_common.mjs';

const MA = 'Main', SN = 'Snack', DE = 'Dessert', SO = 'Soup', SI = 'Side', BR = 'Breakfast', BA = 'Bread or pastry';
const f = (country, course) => ({ ...(country ? { country } : {}), course });

export default {
  id: 'dishes', title: 'World dishes', theme: 'food', icon: '🍜', kids: true,
  leakExempt: [],
  media: 'wiki', photos: 2, depicts: 0,
  wdCheckLabel: { country: 'P495' },
  factsMeta: {
    country: { type: 'cat', label: 'Comes from', clue: v => `It comes from ${v}.` },
    course: { type: 'cat', label: 'Kind of dish', values: [MA, SN, DE, SO, SI, BR, BA], clue: v => ({ [MA]: 'It is usually a main meal.', [SN]: 'It is usually a snack or street food.', [DE]: 'It is a dessert or sweet treat.', [SO]: 'It is a soup.', [SI]: 'It is usually a side dish or dip.', [BR]: 'It is a breakfast dish.', [BA]: 'It is a kind of bread or pastry.' }[v]) },
  },
  imgPrompt: 'Which of these is {lname}?', nameImgPrompt: 'Which dish is this?', tfImgPrompt: 'This dish is {lname}.',
  tpl: {
    country: { ask: 'Which country does {lname} come from?', askReverse: 'Which of these dishes comes from {value}?', stmt: '{name} comes from {value}.' },
    course: { ask: 'What kind of dish is {lname}?', askReverse: 'Which of these is usually eaten as a {lvalue}?', stmt: '{name} is usually eaten as a {lvalue}.', exclusive: false },
  },
  sources: [WD, COMMONS],
  items: [
    { n: 'Sushi', f: f('Japan', MA), d: 1, look: ['Sashimi'],
      b: 'Vinegared rice with fish, seafood or vegetables, often rolled in seaweed. It began as a way of preserving fish.',
      c: ['It began as a way to preserve fish in fermented rice.', 'Rolls of it are wrapped in nori seaweed.', 'It is often eaten with wasabi and pickled ginger.', 'Its rice is seasoned with vinegar.', 'It is a famous Japanese rice dish, often with raw fish.'] },
    { n: 'Sashimi', f: f('Japan', MA), d: 2, look: ['Sushi'],
      b: 'Thin slices of very fresh raw fish or seafood, served without rice.',
      c: ['It is often served with shredded daikon radish.', 'Unlike sushi, it comes without rice.', 'It is dipped in soy sauce.', 'It is sliced very thinly.', 'It is raw fish from Japan.'] },
    { n: 'Ramen', f: f('Japan', SO), d: 1,
      b: 'Wheat noodles in a rich broth, topped with things like pork, egg and spring onion. It came to Japan from China.',
      c: ['Instant noodles were invented in Japan in 1958.', 'Its broth can be flavoured with soy, miso or pork bones.', 'It is often topped with a soft-boiled egg.', 'It came to Japan from China.', 'It is a Japanese noodle soup.'] },
    { n: 'Tempura', f: f('Japan', MA), d: 2,
      b: 'Seafood and vegetables dipped in a light batter and deep-fried. Portuguese visitors brought the idea to Japan.',
      c: ['Portuguese missionaries introduced the idea.', 'Its batter is made with ice-cold water.', 'Prawns are a classic choice.', 'It is light and crispy.', 'It is a Japanese battered, deep-fried dish.'] },
    { n: 'Pizza', alt: ['pizza Margherita', 'Margherita pizza'], wp: 'Pizza', f: f('Italy', MA), d: 1,
      b: 'A flat bread topped with tomato and cheese and baked in a hot oven. The Margherita is said to be named after an Italian queen.',
      c: ['The Margherita is said to be named after a queen of Italy.', 'Naples is famous for it.', 'It is baked very hot, often in a wood-fired oven.', 'It is topped with tomato and mozzarella.', 'It is round, flat and cut into slices.'] },
    { n: 'Lasagne', alt: ['lasagna'], f: f('Italy', MA), d: 1,
      b: 'Layers of flat pasta sheets with meat sauce, white sauce and cheese, baked in the oven.',
      c: ['Garfield the cat loves it.', 'It is baked in a deep dish.', 'It has a creamy white sauce called béchamel.', 'It is made in layers.', 'It uses flat sheets of pasta.'] },
    { n: 'Risotto', f: f('Italy', MA), d: 2,
      b: 'A creamy northern Italian rice dish, stirred slowly while hot stock is added a little at a time.',
      c: ['Arborio rice is often used.', 'The Milanese version is coloured yellow with saffron.', 'Stock is added a ladle at a time.', 'It is stirred until creamy.', 'It is an Italian rice dish.'] },
    { n: 'Spaghetti carbonara', alt: ['carbonara'], f: f('Italy', MA), d: 2,
      b: 'A Roman pasta dish of spaghetti tossed with egg, hard cheese, cured pork and black pepper.',
      c: ['The traditional version has no cream.', 'It uses guanciale, a cured pork cheek.', 'It comes from Rome.', 'Its sauce is made from egg and cheese.', 'It is a spaghetti dish.'] },
    { n: 'Tiramisu', alt: ['tiramisù'], f: f('Italy', DE), d: 2,
      b: 'An Italian dessert of coffee-soaked biscuits layered with mascarpone cream and dusted with cocoa.',
      c: ['Its name means "pick me up".', 'It uses mascarpone cheese.', 'Its biscuits are dipped in coffee.', 'It is dusted with cocoa powder.', 'It is a layered Italian dessert.'] },
    { n: 'Gelato', f: f('Italy', DE), d: 1,
      b: 'Italian ice cream. It is denser than most ice cream because less air is whipped in.',
      c: ['It is churned more slowly than other ice creams.', 'It has less air than other ice creams.', 'It is served from a flat spade.', 'It is a frozen dessert.', 'It is Italian ice cream.'] },
    { n: 'Paella', f: f('Spain', MA), d: 1,
      b: 'A Spanish rice dish from Valencia, cooked in a wide, flat pan with saffron, meat or seafood.',
      c: ['The crispy rice at the bottom is called socarrat.', 'It is named after the pan it is cooked in.', 'Saffron makes it yellow.', 'It comes from Valencia.', 'It is a Spanish rice dish.'] },
    { n: 'Gazpacho', f: f('Spain', SO), d: 2,
      b: 'A cold soup of blended raw tomatoes, peppers, cucumber, garlic and olive oil, from Andalusia.',
      c: ['It comes from Andalusia.', 'It is blended from raw vegetables.', 'Tomato is its main ingredient.', 'It is eaten on hot days.', 'It is a cold Spanish soup.'] },
    { n: 'Churros', alt: ['churro'], f: f('Spain', SN), d: 1,
      b: 'Ridged sticks of fried dough dusted with sugar, often dipped in thick hot chocolate.',
      c: ['Its dough is piped through a star-shaped nozzle.', 'It is often eaten for breakfast in Spain.', 'It is dipped in thick hot chocolate.', 'It is coated in sugar.', 'It is a long, ridged stick of fried dough.'] },
    { n: 'Croissant', f: f('France', BA), d: 1,
      b: 'A buttery, flaky, crescent-shaped pastry. It grew from the Austrian kipferl.',
      c: ['It developed from an Austrian pastry called the kipferl.', 'Its dough is folded with butter many times.', 'It is a breakfast favourite in France.', 'It is flaky and buttery.', 'Its name means crescent.'] },
    { n: 'Crêpe', alt: ['crepe', 'crêpes'], f: f('France', DE), d: 1,
      b: 'A very thin French pancake, eaten sweet with sugar and lemon or savoury with ham and cheese.',
      c: ['Savoury buckwheat ones are called galettes.', 'Brittany is famous for them.', 'They are cooked on a flat round griddle.', 'They are very thin.', 'It is a thin French pancake.'] },
    { n: 'Ratatouille', f: f('France', MA), d: 2,
      b: 'A Provençal stew of summer vegetables such as aubergine, courgette, peppers and tomato. A Pixar film is named after it.',
      c: ['It comes from Nice in Provence.', 'It includes aubergine and courgette.', 'It is a vegetable stew.', 'A Pixar film about a rat chef shares its name.', 'It is a French vegetable dish.'] },
    { n: 'Bouillabaisse', f: f('France', SO), d: 3,
      b: 'A fish stew from the port of Marseille, flavoured with saffron and served with garlicky rouille.',
      c: ['It is served with a garlic sauce called rouille.', 'It is flavoured with saffron and fennel.', 'Fishermen made it from fish they could not sell.', 'It comes from Marseille.', 'It is a French fish stew.'] },
    { n: 'Macaron', alt: ['French macaron'], f: f('France', DE), d: 2,
      b: 'A small, colourful almond meringue biscuit sandwiched with a creamy filling.',
      c: ['Its shells have frilly "feet".', 'It is made with almond flour.', 'Ladurée in Paris made it famous.', 'It comes in bright colours.', 'It is a small sandwich of two meringue shells.'] },
    { n: 'Fish and chips', f: f('United Kingdom', MA), d: 1,
      b: 'Battered fried fish with thick-cut chips. It has been a British takeaway favourite since the 1860s.',
      c: ['It was not rationed in World War II.', 'Cod and haddock are popular choices.', 'It is often eaten with mushy peas.', 'It is sprinkled with salt and vinegar.', 'It is battered fish with fried potatoes.'] },
    { n: 'Full English breakfast', alt: ['fry-up', 'full breakfast'], f: f('United Kingdom', BR), d: 2,
      b: 'A big cooked breakfast of eggs, bacon, sausages, beans, tomato, mushrooms and toast.',
      c: ['It is served on one big plate.', 'It often comes with a cup of tea.', 'Hotels and cafés serve it in the morning.', 'It often includes black pudding.', 'It includes baked beans.', 'It is often called a fry-up.', 'It has eggs, bacon and sausages.', 'It is a big cooked breakfast from England.'] },
    { n: 'Shepherd\'s pie', alt: ['cottage pie'], f: f('United Kingdom', MA), d: 2,
      b: 'Minced lamb in gravy topped with mashed potato and baked. With beef it is called cottage pie.',
      c: ['Made with beef, it has a different name.', 'It is made with minced lamb.', 'It is topped with mashed potato.', 'It is baked in the oven.', 'It is named after someone who looks after sheep.'] },
    { n: 'Haggis', f: f('United Kingdom', MA), d: 2,
      b: 'Scotland\'s national dish, made from sheep\'s heart, liver and lungs with oats and spices.',
      c: ['It is traditionally cooked in a sheep\'s stomach.', 'It is eaten on Burns Night.', 'Robert Burns wrote a poem to it.', 'It is served with "neeps and tatties".', 'It is the national dish of Scotland.'] },
    { n: 'Bratwurst', f: f('Germany', MA), d: 2,
      b: 'A German sausage, usually pork, grilled or fried and often eaten in a bread roll with mustard.',
      c: ['Nuremberg is famous for small ones.', 'It is often eaten with sauerkraut.', 'It is served in a roll with mustard.', 'It is usually made of pork.', 'It is a German sausage.'] },
    { n: 'Pretzel', alt: ['Brezel'], f: f('Germany', BA), d: 1,
      b: 'A baked bread twisted into a knot and sprinkled with salt. It is dipped in lye before baking to make it brown and shiny.',
      c: ['It is dipped in lye before baking.', 'Its shape may come from arms folded in prayer.', 'It is sold at Oktoberfest.', 'It is sprinkled with coarse salt.', 'It is a bread twisted into a knot.'] },
    { n: 'Black Forest gateau', alt: ['Black Forest cake', 'Schwarzwälder Kirschtorte'], f: f('Germany', DE), d: 2,
      b: 'A chocolate sponge layered with cream and cherries and soaked in cherry brandy.',
      c: ['It is soaked in kirsch, a cherry brandy.', 'It is decorated with chocolate shavings.', 'It has layers of whipped cream.', 'It has cherries inside and on top.', 'It is named after a German forest.'] },
    { n: 'Wiener schnitzel', alt: ['schnitzel'], f: f('Austria', MA), d: 2,
      b: 'A thin slice of veal coated in breadcrumbs and fried. It is Austria\'s national dish.',
      c: ['By law in Austria it must be made of veal.', 'It is served with a lemon wedge.', 'It is pounded thin before frying.', 'It is coated in breadcrumbs.', 'Its name means it comes from Vienna.'] },
    { n: 'Goulash', alt: ['gulyás'], f: f('Hungary', SO), d: 2,
      b: 'A Hungarian stew or soup of beef and vegetables, flavoured with lots of paprika.',
      c: ['It was first made by cattle herders.', 'It is flavoured with paprika.', 'It is a beef stew or soup.', 'It is red-brown in colour.', 'It comes from Hungary.'] },
    { n: 'Pierogi', alt: ['pierogies', 'perogies'], f: f('Poland', MA), d: 2,
      b: 'Polish dumplings filled with potato and cheese, meat, cabbage or fruit, then boiled or fried.',
      c: ['Popular fillings include potato and cheese.', 'They can be sweet or savoury.', 'They are often topped with fried onions.', 'They are half-moon shaped.', 'They are Polish dumplings.'] },
    { n: 'Borscht', alt: ['borshch'], f: f('Ukraine', SO), d: 2,
      b: 'A sour soup coloured deep red by beetroot. UNESCO lists Ukrainian borscht cooking as cultural heritage.',
      c: ['UNESCO listed Ukrainian borscht culture in 2022.', 'It is often served with sour cream.', 'It can be eaten hot or cold.', 'It is deep red.', 'It is a beetroot soup.'] },
    { n: 'Moussaka', f: f('Greece', MA), d: 2,
      b: 'A baked Greek dish of layered aubergine and minced meat topped with creamy white sauce.',
      c: ['Its modern form was shaped by chef Nikolaos Tselementes.', 'It has a thick béchamel topping.', 'It contains minced lamb or beef.', 'It is made with layers of aubergine.', 'It is a baked Greek dish.'] },
    { n: 'Gyros', alt: ['gyro'], f: f('Greece', SN), d: 2, look: ['Doner kebab'],
      b: 'Greek meat cooked on a turning spit, sliced and wrapped in pitta with tomato, onion and tzatziki.',
      c: ['Its name means "turn".', 'It is served with tzatziki.', 'The meat is cooked on a vertical spit.', 'It is wrapped in pitta bread.', 'It is Greek street food.'] },
    { n: 'Doner kebab', alt: ['döner kebab', 'kebab'], f: f('Turkey', SN), d: 1, look: ['Gyros'],
      b: 'Meat roasted on a vertical spit, shaved off and served in bread with salad and sauce. The popular takeaway form took off in Berlin.',
      c: ['Its popular sandwich form took off in Berlin in the 1970s.', 'Its name means "rotating roast".', 'The meat is shaved off a turning spit.', 'It is a late-night takeaway favourite.', 'It comes from Turkey.'] },
    { n: 'Falafel', f: f(null, SN), d: 1,
      b: 'Deep-fried balls of ground chickpeas or fava beans, popular across the Middle East.',
      c: ['Egypt makes it from fava beans.', 'It is often served in pitta with salad.', 'It is often eaten with tahini sauce.', 'It is made from chickpeas.', 'It is a fried ball from the Middle East.'] },
    { n: 'Hummus', alt: ['houmous'], f: f(null, SI), d: 1,
      b: 'A creamy dip of mashed chickpeas, tahini, lemon and garlic, eaten across the Middle East.',
      c: ['Its name is Arabic for chickpea.', 'It contains tahini, a sesame paste.', 'It is often drizzled with olive oil.', 'It is eaten with pitta bread.', 'It is a chickpea dip.'] },
    { n: 'Tagine', alt: ['tajine'], f: f('Morocco', MA), d: 2,
      b: 'A slow-cooked North African stew named after the clay pot with a cone-shaped lid it is cooked in.',
      c: ['It often mixes meat with dried fruit.', 'Its pot has a cone-shaped lid.', 'It is cooked slowly.', 'It is named after its clay pot.', 'It comes from Morocco.'] },
    { n: 'Bobotie', f: f('South Africa', MA), d: 3,
      b: 'A South African dish of spiced minced meat baked with an egg topping, often served with yellow rice.',
      c: ['It is flavoured with curry spices and dried fruit.', 'It has a baked egg topping.', 'It is served with yellow rice.', 'It is made with minced meat.', 'It is a national dish of South Africa.'] },
    { n: 'Injera', f: f('Ethiopia', BA), d: 3,
      b: 'A spongy, sour flatbread made from teff flour. It is used as plate and spoon for stews.',
      c: ['It is made from teff, a tiny grain.', 'It is fermented, giving a sour taste.', 'It is used to scoop up stews.', 'It is spongy and full of holes.', 'It is a flatbread from Ethiopia.'] },
    { n: 'Biryani', alt: ['biriyani'], f: f('India', MA), d: 2,
      b: 'A rich rice dish layered with spiced meat or vegetables, saffron and fried onions.',
      c: ['Hyderabad and Lucknow are famous for it.', 'It is often sealed and cooked slowly.', 'It is flavoured with saffron.', 'It layers rice with spiced meat.', 'It is a South Asian rice dish.'] },
    { n: 'Butter chicken', alt: ['murgh makhani'], f: f('India', MA), d: 1,
      b: 'Chicken in a mild, creamy tomato and butter sauce, created in Delhi in the mid-1900s.',
      c: ['It is often eaten with naan bread.', 'Its sauce is orange.', 'The chicken is marinated in yoghurt and spices.', 'It was created at a Delhi restaurant.', 'The chicken is often cooked in a tandoor first.', 'Its sauce is tomato, butter and cream.', 'It is a mild curry.', 'It is a creamy Indian chicken curry.'] },
    { n: 'Masala dosa', alt: ['dosa'], f: f('India', BR), d: 2,
      b: 'A thin, crispy South Indian pancake of fermented rice and lentil batter, filled with spiced potato.',
      c: ['Its batter is fermented rice and lentils.', 'It is served with sambar and chutney.', 'It is filled with spiced potato.', 'It is very thin and crispy.', 'It comes from South India.'] },
    { n: 'Pad thai', f: f('Thailand', MA), d: 1,
      b: 'Stir-fried rice noodles with egg, tofu or prawns, bean sprouts, peanuts and tamarind. It became popular in the 1930s and 40s.',
      c: ['It may include prawns or tofu.', 'It is served with a wedge of lime.', 'It is often sold at street stalls.', 'The Thai government promoted it in the 1930s and 40s.', 'It is flavoured with tamarind.', 'It is topped with crushed peanuts.', 'It uses flat rice noodles.', 'It is a Thai fried noodle dish.'] },
    { n: 'Tom yum', alt: ['tom yam'], f: f('Thailand', SO), d: 2,
      b: 'A hot and sour Thai soup flavoured with lemongrass, lime leaves, galangal and chilli.',
      c: ['It is flavoured with lemongrass and galangal.', 'Prawns are a classic choice.', 'It is hot and sour.', 'It uses kaffir lime leaves.', 'It is a Thai soup.'] },
    { n: 'Thai green curry', alt: ['green curry'], f: f('Thailand', MA), d: 2,
      b: 'A Thai curry made with green chilli paste and coconut milk.',
      c: ['It may include aubergine and bamboo shoots.', 'Chicken is a popular choice.', 'It can be very spicy.', 'It comes from South-East Asia.', 'It is flavoured with Thai basil.', 'Its paste is made from fresh green chillies.', 'It is made with coconut milk.', 'It is often served with jasmine rice.', 'It is a green Thai curry.'] },
    { n: 'Phở', alt: ['pho'], f: f('Vietnam', SO), d: 1,
      b: 'A Vietnamese noodle soup of rice noodles in fragrant broth with beef or chicken and fresh herbs.',
      c: ['It developed near Hanoi in the early 1900s.', 'Its broth is spiced with star anise.', 'It is topped with fresh herbs and lime.', 'It uses flat rice noodles.', 'It is a Vietnamese noodle soup.'] },
    { n: 'Bánh mì', alt: ['banh mi'], f: f('Vietnam', SN), d: 2,
      b: 'A Vietnamese sandwich in a crispy baguette, filled with meat, pickled vegetables, herbs and chilli.',
      c: ['Its bread comes from French colonial times.', 'It has pickled carrot and radish.', 'It has fresh coriander.', 'It is made with a baguette.', 'It is a Vietnamese sandwich.'] },
    { n: 'Nasi goreng', f: f('Indonesia', MA), d: 2,
      b: 'Indonesian fried rice, sweetened with soy sauce and often topped with a fried egg.',
      c: ['Barack Obama mentioned it in a speech in Jakarta.', 'It uses sweet soy sauce.', 'It is often topped with a fried egg.', 'Its name means "fried rice".', 'It comes from Indonesia.'] },
    { n: 'Satay', alt: ['sate'], f: f('Indonesia', SN), d: 1,
      b: 'Skewers of grilled meat served with a peanut sauce, popular across South-East Asia.',
      c: ['It is often cooked over charcoal.', 'It is popular in Malaysia and Singapore too.', 'It is served with peanut sauce.', 'It is cooked on skewers.', 'It is grilled meat on sticks.'] },
    { n: 'Rendang', f: f('Indonesia', MA), d: 3,
      b: 'Beef slow-cooked in coconut milk and spices until almost dry. It comes from the Minangkabau people of Sumatra.',
      c: ['It comes from the Minangkabau people of Sumatra.', 'It is cooked for hours until almost dry.', 'It uses coconut milk.', 'It is usually made with beef.', 'It is a rich, dry curry.'] },
    { n: 'Peking duck', f: f('China', MA), d: 2,
      b: 'Roast duck with crispy skin from Beijing, served in thin pancakes with spring onion and sauce.',
      c: ['It was a dish of the imperial court.', 'Its skin is famously crispy.', 'It is eaten in thin pancakes with plum or hoisin sauce.', 'It is roast duck.', 'It comes from Beijing.'] },
    { n: 'Jiaozi', alt: ['dumplings', 'Chinese dumplings'], f: f('China', MA), d: 1,
      b: 'Chinese dumplings filled with meat and vegetables. Families make them together for Chinese New Year.',
      c: ['Their name sounds like an old word for changing to a new year.', 'They are often dipped in vinegar and soy sauce.', 'Some families hide a coin inside one.', 'Their dough is folded and pinched shut.', 'They are shaped like old Chinese money.', 'They are eaten at Chinese New Year.', 'They are boiled, steamed or fried.', 'They are filled with meat and vegetables.', 'They are Chinese dumplings.'] },
    { n: 'Kung Pao chicken', alt: ['kung po chicken', 'gong bao chicken'], f: f('China', MA), d: 2,
      b: 'A spicy stir-fry of chicken, peanuts and chillies from Sichuan.',
      c: ['It is named after a Qing dynasty official.', 'It uses Sichuan peppercorns.', 'It contains peanuts.', 'It is spicy.', 'It is a Chinese chicken stir-fry.'] },
    { n: 'Kimchi', f: f('Korea', SI), d: 1,
      b: 'Spicy fermented vegetables, usually napa cabbage with chilli. It is served with almost every Korean meal.',
      c: ['Families make it together in autumn, called kimjang.', 'It is fermented.', 'It is usually made with napa cabbage.', 'It is spicy and red.', 'It is a Korean side dish.'] },
    { n: 'Bibimbap', f: f('Korea', MA), d: 2,
      b: 'A Korean bowl of rice topped with vegetables, meat, egg and chilli paste, mixed together before eating.',
      c: ['It is often served in a hot stone bowl.', 'It is topped with gochujang chilli paste.', 'Its name means "mixed rice".', 'It is topped with a fried egg.', 'It is a Korean rice bowl.'] },
    { n: 'Tacos', alt: ['taco'], f: f('Mexico', SN), d: 1,
      b: 'Folded corn or wheat tortillas filled with meat, beans, salsa and other fillings.',
      c: ['Tacos al pastor use pork cooked on a spit.', 'Traditional tortillas are made from corn.', 'They are topped with salsa.', 'They are folded in half.', 'They are a Mexican street food.'] },
    { n: 'Guacamole', f: f('Mexico', SI), d: 1,
      b: 'A dip of mashed avocado with lime, onion, chilli and coriander. The Aztecs first made it.',
      c: ['The Aztecs first made it.', 'It is often eaten with corn chips.', 'Lime stops it turning brown quickly.', 'It is green.', 'It is mashed avocado.'] },
    { n: 'Hamburger', alt: ['burger', 'cheeseburger'], f: f('United States', MA), d: 1,
      b: 'A minced beef patty in a bun, often with cheese, lettuce, tomato and sauce.',
      c: ['It is named after a city in Germany.', 'It became famous in the USA.', 'It is often eaten with fries.', 'It has a patty of minced beef.', 'It is served in a bun.'] },
    { n: 'Hot dog', alt: ['hotdog'], f: f('United States', SN), d: 1,
      b: 'A cooked sausage in a long bun, often topped with mustard and ketchup.',
      c: ['Coney Island is famous for them.', 'A famous eating contest is held every 4 July.', 'It is topped with mustard and ketchup.', 'It is a sausage in a long bun.', 'Its name sounds like a warm pet.'] },
    { n: 'Poutine', f: f('Canada', SN), d: 2,
      b: 'Chips topped with cheese curds and hot gravy. It comes from Quebec.',
      c: ['Its cheese curds should squeak.', 'It comes from Quebec.', 'It is covered in gravy.', 'It is topped with cheese curds.', 'It is a Canadian dish of chips.'] },
    { n: 'Feijoada', f: f('Brazil', MA), d: 3,
      b: 'A Brazilian stew of black beans with pork and beef, served with rice and orange slices.',
      c: ['It is often served with orange slices.', 'It is often eaten on Saturdays in Brazil.', 'It is served with rice and farofa.', 'It is made with black beans and pork.', 'It is the national dish of Brazil.'] },
    { n: 'Ceviche', alt: ['cebiche'], f: f('Peru', MA), d: 2,
      b: 'Raw fish "cooked" in lime or lemon juice with chilli and onion. It is Peru\'s national dish.',
      c: ['Peru celebrates a national day for it.', 'The fish is "cooked" by acid, not heat.', 'It is marinated in lime juice.', 'It uses raw fish.', 'It is the national dish of Peru.'] },
    { n: 'Asado', f: f('Argentina', MA), d: 3,
      b: 'An Argentine barbecue of beef and other meats slow-cooked over wood or charcoal.',
      c: ['It is usually served with chimichurri sauce.', 'The cook is called the asador.', 'Meat is cooked slowly over embers.', 'It is a big social gathering.', 'It is an Argentine barbecue.'] },
    { n: 'Meat pie', alt: ['Australian meat pie', 'pie'], f: f('Australia', SN), d: 1,
      b: 'A hand-sized pie of minced meat and gravy, an Australian favourite at the footy, often with tomato sauce.',
      c: ['Its pastry case holds a hot filling.', 'It is sold at bakeries and service stations.', 'It is often eaten with your hands.', 'A "pie floater" sits in pea soup.', 'It is eaten at football matches.', 'It is topped with tomato sauce.', 'It is filled with mince and gravy.', 'It is a hand-sized savoury pie.'] },
    { n: 'Lamington', f: f('Australia', DE), d: 1,
      b: 'A square of sponge cake dipped in chocolate and rolled in desiccated coconut. Some have jam in the middle.',
      c: ['It may be named after Lord Lamington, a Queensland governor.', 'Some have a layer of jam or cream.', 'It is rolled in coconut.', 'It is dipped in chocolate icing.', 'It is an Australian sponge cake square.'] },
    { n: 'Pavlova', f: f(null, DE), d: 1,
      b: 'A meringue cake with a crisp shell and soft middle, topped with cream and fruit. Australia and New Zealand both claim it.',
      c: ['It is named after a Russian ballerina.', 'Australia and New Zealand both claim it.', 'It is topped with cream and fruit.', 'It has a crisp shell and soft centre.', 'It is a big meringue dessert.'] },
    { n: 'Fairy bread', f: f('Australia', SN), d: 1,
      b: 'White bread spread with butter and covered in hundreds and thousands. It is a children\'s party classic in Australia.',
      c: ['It is cut into triangles.', 'It is a children\'s party classic.', 'It uses white bread and butter.', 'It is covered in sprinkles called hundreds and thousands.', 'It is named after a magical winged being.'] },
    { n: 'Vegemite', f: f('Australia', SI), d: 1,
      b: 'A dark, salty Australian spread made from leftover brewer\'s yeast, first sold in 1923.',
      c: ['It was first made in Melbourne in 1923.', 'It is made from brewer\'s yeast extract.', 'It is rich in B vitamins.', 'It is spread thinly on toast.', 'It is a dark, salty Australian spread.'] },
  ],
  fakes: ['Glazed moonfish pie (Norway)', 'Sunberry dumplings (Peru)', 'Cloud noodles (Chile)', 'Velvet goat stew (Iceland)'],
  questions: [
    { kind: 'mc', prompt: 'Which country is sushi from?', answer: 'Japan', wrong: ['China', 'Thailand', 'Korea'], explain: 'Sushi grew from a Japanese way of preserving fish.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which country is pizza from?', answer: 'Italy', wrong: ['France', 'Greece', 'United States'], explain: 'Modern pizza comes from Naples.', difficulty: 1 },
    { kind: 'mc', prompt: 'Tacos come from which country?', answer: 'Mexico', wrong: ['Spain', 'Brazil', 'Peru'], explain: 'Tortillas were traditionally made of corn.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the main ingredient of guacamole?', answer: 'Avocado', wrong: ['Peas', 'Cucumber', 'Lime'], explain: 'Lime, onion and chilli are added.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is hummus mainly made from?', answer: 'Chickpeas', wrong: ['Lentils', 'Potatoes', 'Rice'], explain: 'It is blended with tahini, lemon and garlic.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which vegetable makes borscht red?', answer: 'Beetroot', wrong: ['Tomato', 'Red pepper', 'Red cabbage'], explain: 'Borscht is a beetroot soup.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which spice makes paella yellow?', answer: 'Saffron', wrong: ['Turmeric', 'Paprika', 'Cumin'], explain: 'Saffron comes from crocus flowers.', difficulty: 2 },
    { kind: 'mc', prompt: 'Who is the pavlova named after?', answer: 'A Russian ballerina', wrong: ['A French chef', 'An Italian queen', 'A New Zealand prime minister'], explain: 'Anna Pavlova toured Australia and New Zealand in the 1920s.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which city is the hamburger named after?', answer: 'Hamburg', wrong: ['Berlin', 'Frankfurt', 'New York'], explain: 'It is linked to the "Hamburg steak".', difficulty: 2 },
    { kind: 'mc', prompt: 'What does "tiramisu" mean in Italian?', answer: 'Pick me up', wrong: ['Sweet dream', 'Coffee cake', 'Little cloud'], explain: 'It contains coffee and cocoa.', difficulty: 3 },
    { kind: 'mc', prompt: 'What is Vegemite made from?', answer: 'Brewer\'s yeast extract', wrong: ['Black olives', 'Dried seaweed', 'Burnt sugar'], explain: 'It was first made in Melbourne in 1923.', difficulty: 2 },
    { kind: 'mc', prompt: 'What are the sprinkles on fairy bread called in Australia?', answer: 'Hundreds and thousands', wrong: ['Jimmies', 'Glitter drops', 'Rainbow crumbs'], explain: 'Fairy bread is a party classic.', difficulty: 1 },
    { kind: 'tf', prompt: 'Traditional spaghetti carbonara is made with cream.', answer: false, explain: 'The sauce is egg, cheese, cured pork and pepper.', difficulty: 3 },
    { kind: 'mc', prompt: 'Which country is kimchi from?', answer: 'Korea', wrong: ['Japan', 'China', 'Vietnam'], explain: 'It is usually fermented napa cabbage with chilli.', difficulty: 1 },
  ],
};
