import { WD, COMMONS, theC } from './_common.mjs';

const UK = 'United Kingdom', DE = 'Germany', FR = 'France', CN = 'China', JP = 'Japan', AU = 'Australia', US = 'United States', IE = 'Ireland', RU = 'Russia', CH = 'Switzerland', HU = 'Hungary', IT = 'Italy', BE = 'Belgium', CA = 'Canada', MX = 'Mexico', TB = 'Tibet', MT = 'Malta', AF = 'Afghanistan', CU = 'Cuba', ZW = 'Zimbabwe', PT = 'Portugal', HR = 'Croatia', CG = 'Democratic Republic of the Congo';
const sizeOf = kg => (kg < 5 ? 'Toy' : kg < 12 ? 'Small' : kg < 25 ? 'Medium' : kg < 50 ? 'Large' : 'Giant');
const f = (origin, type, massKg) => ({ origin, type, ...(massKg ? { massKg, size: sizeOf(massKg) } : {}) });

export default {
  id: 'dogs', title: 'Dog breeds', theme: 'animals', icon: '🐕', kids: true,
  leakExempt: ['dog', 'dogs', 'breed'],
  media: 'wiki', photos: 3, depicts: 0, lname: 'asis',
  wdCheckLabel: { origin: 'P495' }, wdP31: ['Q39367'],
  ranges: { massKg: [1, 100] },
  factsMeta: {
    origin: { type: 'cat', label: 'Country of origin', clue: v => `The breed comes from ${[].concat(v).map(theC).join(' or ')}.` },
    type: { type: 'cat', label: 'Breed type', values: ['Gundog', 'Herding', 'Hound', 'Terrier', 'Toy', 'Working', 'Companion', 'Spitz'], clue: v => `It is a ${v.toLowerCase()} breed.` },
    massKg: { type: 'num', label: 'Typical adult weight', unit: 'kg', higherLabel: 'Heavier', clue: v => `A typical adult weighs about ${v} kg.` },
    size: { type: 'cat', label: 'Size', values: ['Toy', 'Small', 'Medium', 'Large', 'Giant'], noClue: true },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which dog breed is this?",
  tfImgPrompt: "This dog is {aName}.",
  tpl: {"origin": {"ask": "Which country does the {name} come from?", "askReverse": "Which of these breeds comes from {value}?", "stmt": "The {name} comes from {value}."}, "type": {"ask": "What type of breed is the {name}?", "askReverse": "Which of these is {aValue} breed?", "stmt": "The {name} is {aValue} breed."}, "massKg": {"askHigh": "Which of these breeds is usually the heaviest?", "askLow": "Which of these breeds is usually the lightest?"}, "size": {"ask": "What size is the {name}?", "askReverse": "Which of these breeds is {lvalue}-sized?", "stmt": "The {name} is {aValue}-sized breed."}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Labrador Retriever', alt: ['Labrador', 'Lab'], f: f(UK, 'Gundog', 32), d: 1, look: ['Golden Retriever'],
      b: 'A friendly, clever dog that loves water and food. It is one of the most popular breeds in the world and often works as a guide dog.',
      c: ['Its ancestors came from Newfoundland in Canada.', 'It has a thick "otter" tail.', 'It is one of the most common guide dogs for blind people.', 'It comes in black, yellow and chocolate.', 'It is famous for loving food and swimming.'] },
    { n: 'Golden Retriever', alt: ['Golden'], f: f(UK, 'Gundog', 30), d: 1, look: ['Labrador Retriever', 'Irish Setter'],
      b: 'A gentle, friendly gundog with a feathery golden coat. It was first bred in Scotland in the 1800s.',
      c: ['It was first bred in the Scottish Highlands by Lord Tweedmouth.', 'It carries things gently in its "soft mouth".', 'It is a popular therapy and guide dog.', 'It has a long, feathery coat.', 'Its coat is a warm yellow colour.'] },
    { n: 'German Shepherd', alt: ['Alsatian', 'German Shepherd Dog'], f: f(DE, 'Herding', 34), d: 1, look: ['Belgian Malinois'],
      b: 'A strong, smart working dog often used by police and the army. It was first bred to herd sheep.',
      c: ['It was once called the Alsatian in Britain.', 'Rin Tin Tin, a famous film dog, was one.', 'Police and armies around the world use it.', 'It has upright ears and a black-and-tan coat.', 'It was first bred to herd sheep in central Europe.'] },
    { n: 'French Bulldog', alt: ['Frenchie'], f: f(FR, 'Companion', 11), d: 1, look: ['Bulldog', 'Boston Terrier', 'Pug'],
      b: 'A small, muscly dog with big bat-like ears. It is now one of the most popular breeds in the world.',
      c: ['It descends from toy bulldogs taken from England by lace workers.', 'It cannot swim well because of its heavy front.', 'It has large upright ears like a bat.', 'It snores a lot because of its flat face.', 'Its name says it comes from Paris\'s country.'] },
    { n: 'Bulldog', wp: 'Bulldog', alt: ['British Bulldog', 'English Bulldog'], f: f(UK, 'Companion', 23), d: 1, look: ['French Bulldog'],
      b: 'A stocky, wrinkly dog with a pushed-in face. It is a national symbol of Britain.',
      c: ['It was originally bred for a cruel sport with bulls.', 'It is a mascot of many sports teams.', 'It has a loose, wrinkly face and an underbite.', 'It is linked with Winston Churchill.', 'It is a national symbol of Britain.'] },
    { n: 'Poodle', wp: 'Poodle', alt: ['Standard Poodle'], f: f([FR, DE], 'Companion', 25), d: 1,
      b: 'A clever dog with curly fur that hardly sheds. It comes in standard, miniature and toy sizes.',
      c: ['It was first bred as a water dog in Germany.', 'Its fancy haircut was designed to help it swim.', 'It is one of the most intelligent breeds.', 'It comes in standard, miniature and toy sizes.', 'It has tight, curly fur.'] },
    { n: 'Beagle', f: f(UK, 'Hound', 10), d: 1, look: ['Basset Hound'],
      b: 'A small, merry hound with floppy ears and a great sense of smell. It is used to sniff out food at airports.',
      c: ['Snoopy from "Peanuts" is one.', 'It sniffs bags for food at airports.', 'It was bred to hunt hares in packs.', 'It has floppy ears and a white-tipped tail.', 'It is a small tricolour hound with a great nose.'] },
    { n: 'Rottweiler', alt: ['Rottie'], f: f(DE, 'Working', 45), d: 1, look: ['Dobermann'],
      b: 'A big, powerful black-and-tan dog. Long ago it drove cattle to market and guarded the money.',
      c: ['Butchers once used it to pull carts of meat.', 'It drove cattle to market in a German town.', 'It is used as a police and guard dog.', 'It is black with tan markings on its face and legs.', 'It is a big, strong, muscular dog.'] },
    { n: 'Dachshund', alt: ['sausage dog', 'wiener dog', 'Dackel'], f: f(DE, 'Hound', 10), d: 1, look: ['Basset Hound', 'Corgi'],
      b: 'A long, low dog with short legs. It was bred to dig into badger holes.',
      c: ['Its name means "badger dog" in German.', 'It comes in smooth, wire-haired and long-haired coats.', 'It was bred to chase badgers underground.', 'Its body is very long and its legs are very short.', 'It is nicknamed after a long meat snack.'] },
    { n: 'Yorkshire Terrier', alt: ['Yorkie'], f: f(UK, 'Toy', 3), d: 1, look: ['Silky Terrier', 'Maltese'],
      b: 'A tiny terrier with long, silky steel-blue and tan hair. It was bred to catch rats in mills.',
      c: ['It was bred to catch rats in clothing mills.', 'Its long coat is steel-blue and tan.', 'It is often carried in handbags.', 'It is a tiny, brave terrier.', 'It is named after an English county.'] },
    { n: 'Boxer', wp: 'Boxer (dog)', f: f(DE, 'Working', 30), d: 1, look: ['Bulldog'],
      b: 'A playful, strong dog with a square head. It got its name from the way it stands up and paws with its front legs.',
      c: ['It was among the first breeds used as police dogs in Germany.', 'It stays puppy-like for years.', 'It has a short, square muzzle.', 'It is often fawn or brindle with white.', 'It is said to be named for "punching" with its front paws.'] },
    { n: 'Siberian Husky', alt: ['Husky'], f: f(RU, 'Working', 22), d: 1, look: ['Alaskan Malamute', 'Samoyed'],
      b: 'A tough sled dog from Siberia, often with bright blue eyes. Huskies helped carry medicine to Nome, Alaska, in 1925.',
      c: ['A team carried diphtheria medicine to Nome in 1925.', 'It was bred by the Chukchi people.', 'It howls rather than barks.', 'It often has bright blue eyes.', 'It pulls sleds over snow.'] },
    { n: 'Pembroke Welsh Corgi', alt: ['Corgi'], f: f(UK, 'Herding', 12), d: 1, look: ['Dachshund'],
      b: 'A short-legged herding dog from Wales. Queen Elizabeth II owned more than 30 of them.',
      c: ['It herded cattle by nipping at their heels.', 'Queen Elizabeth II owned more than 30.', 'It has big pointed ears and a fox-like face.', 'It has very short legs and a long body.', 'It comes from Wales.'] },
    { n: 'Great Dane', alt: ['German Mastiff'], f: f(DE, 'Working', 65), d: 1, look: ['English Mastiff', 'Irish Wolfhound'],
      b: 'One of the tallest dog breeds. Scooby-Doo is a cartoon one.',
      c: ['It was bred to hunt wild boar.', 'One named Zeus was the tallest dog ever recorded.', 'It is often called a "gentle giant".', 'Scooby-Doo is one.', 'It is one of the tallest breeds of all.'] },
    { n: 'Chihuahua', wp: 'Chihuahua (dog)', f: f(MX, 'Toy', 2), d: 1, look: ['Papillon', 'Pomeranian'],
      b: 'The smallest dog breed in the world, from Mexico. It has big ears and a big personality.',
      c: ['It may come from the Techichi dogs of ancient Mexico.', 'It has a soft spot on its skull like a baby.', 'It has big ears and big round eyes.', 'It is named after a Mexican state.', 'It is the smallest dog breed in the world.'] },
    { n: 'Pug', f: f(CN, 'Toy', 7), d: 1, look: ['French Bulldog', 'Pekingese'],
      b: 'A small, wrinkly dog with a flat face and curly tail. It was a favourite of Chinese emperors.',
      c: ['It was a favourite of Chinese emperors.', 'Dutch royalty made it popular in Europe.', 'It has a tightly curled tail.', 'Its face is flat and wrinkly.', 'Its name is just three letters.'] },
    { n: 'Shih Tzu', f: f([CN, TB], 'Toy', 6), d: 1, look: ['Lhasa Apso', 'Pekingese'],
      b: 'A small, long-haired lap dog bred for Chinese royalty. Its name means "lion dog".',
      c: ['It was bred for Chinese royalty.', 'It is related to the Lhasa Apso from Tibet.', 'Its hair is often tied up in a topknot.', 'It has a long, flowing coat.', 'Its name means "lion" in Chinese.'] },
    { n: 'Border Collie', alt: ['Collie'], f: f(UK, 'Herding', 17), d: 1, look: ['Australian Shepherd', 'Rough Collie', 'Shetland Sheepdog'],
      b: 'A super-smart, energetic sheepdog. It controls sheep by staring at them with "the eye".',
      c: ['One named Chaser learned the names of over 1,000 toys.', 'It controls sheep with an intense stare.', 'It is often called the cleverest breed.', 'It is usually black and white.', 'It comes from the area where England meets Scotland.'] },
    { n: 'Australian Shepherd', alt: ['Aussie'], f: f(US, 'Herding', 23), d: 2, look: ['Border Collie'],
      b: 'Despite its name, this herding dog was developed in the USA. Many have blue or odd-coloured eyes.',
      c: ['It was developed on ranches in the western USA.', 'Many have one blue eye and one brown eye.', 'It is often blue merle coloured.', 'It was popular in rodeos.', 'Its name suggests a country it does not come from.'] },
    { n: 'Dobermann', wp: 'Dobermann', alt: ['Doberman', 'Doberman Pinscher'], f: f(DE, 'Working', 38), d: 1, look: ['Rottweiler'],
      b: 'A sleek, fast guard dog. It was first bred by a German tax collector to protect him on his rounds.',
      c: ['A tax collector named Louis Dobermann first bred it.', 'It served with US Marines in World War II.', 'It is sleek, fast and alert.', 'It is usually black and rust coloured.', 'It is a famous guard dog.'] },
    { n: 'Cavalier King Charles Spaniel', alt: ['Cavalier'], f: f(UK, 'Toy', 7), d: 2,
      b: 'A gentle little spaniel with long, silky ears. It is named after King Charles II of England.',
      c: ['It is named after a king who loved spaniels.', 'It appears in many old paintings.', 'It comes in four colours, including Blenheim.', 'It has long, feathery ears.', 'It is a small, gentle spaniel.', 'Its silky coat is often chestnut and white.', 'It is one of the most popular lap dogs in Britain.'] },
    { n: 'Miniature Schnauzer', alt: ['Schnauzer'], f: f(DE, 'Terrier', 7), d: 2,
      b: 'A small, bearded German dog with bushy eyebrows. It was bred to catch rats on farms.',
      c: ['Its name means "snout" in German.', 'It was bred as a farm ratter.', 'It has bushy eyebrows.', 'It has a long beard and whiskers.', 'It is the smallest of three sizes of its breed.'] },
    { n: 'Bernese Mountain Dog', alt: ['Berner'], f: f(CH, 'Working', 45), d: 2, look: ['Saint Bernard'],
      b: 'A big, gentle three-coloured farm dog from the Swiss Alps. It pulled carts of milk and cheese.',
      c: ['It pulled carts of milk and cheese.', 'It has a black, white and rust coat.', 'It is gentle and calm.', 'It comes from the Swiss Alps.', 'It is named after a Swiss city and the hills.'] },
    { n: 'Shetland Sheepdog', alt: ['Sheltie'], f: f(UK, 'Herding', 9), d: 2, look: ['Rough Collie', 'Border Collie'],
      b: 'A small herding dog from the Shetland Islands that looks like a mini Lassie.',
      c: ['It was bred to herd small ponies and sheep.', 'It barks a lot.', 'It looks like a small Rough Collie.', 'It has a thick mane-like coat.', 'It comes from islands north of Scotland.'] },
    { n: 'Boston Terrier', f: f(US, 'Companion', 8), d: 2, look: ['French Bulldog'],
      b: 'A small black-and-white dog nicknamed "the American gentleman" because it looks like it is wearing a tuxedo.',
      c: ['It is nicknamed "the American gentleman".', 'It looks like it is wearing a tuxedo.', 'It has a flat face and upright ears.', 'It is the state dog of Massachusetts.', 'It is named after a US city.'] },
    { n: 'Pomeranian', wp: 'Pomeranian dog', alt: ['Pom'], f: f(DE, 'Toy', 2.5), d: 1, look: ['Chihuahua', 'Samoyed'],
      b: 'A tiny, fluffy dog that looks like a little fox. Queen Victoria made it popular.',
      c: ['Its ancestors were big sled dogs.', 'Queen Victoria helped make it small and popular.', 'It has a fluffy coat that stands out.', 'It looks like a little fox or lion.', 'It is named after a region by the Baltic Sea.'] },
    { n: 'Havanese', wp: 'Havanese dog', f: f(CU, 'Toy', 5), d: 3, look: ['Bichon Frise', 'Maltese'],
      b: 'A small, cheerful dog with a long, soft coat. It is the national dog of Cuba.',
      c: ['It is related to the Bichon Frise.', 'It nearly died out after the Cuban revolution.', 'It has a long, silky coat.', 'It is the national dog of Cuba.', 'It is named after Cuba\'s capital city.'] },
    { n: 'English Cocker Spaniel', alt: ['Cocker Spaniel', 'Cocker'], f: f(UK, 'Gundog', 14), d: 1, look: ['English Springer Spaniel', 'Cavalier King Charles Spaniel'],
      b: 'A merry gundog with long, wavy ears. It was bred to flush woodcock for hunters.',
      c: ['It was bred to flush woodcock for hunters.', 'Its tail never seems to stop wagging.', 'It has long, silky ears.', 'Lady in "Lady and the Tramp" is the American kind.', 'It is a spaniel from England.'] },
    { n: 'Maltese', wp: 'Maltese dog', f: f(MT, 'Toy', 3), d: 2, look: ['Bichon Frise', 'Havanese'],
      b: 'A tiny dog with long, silky white hair that reaches the ground. It is one of the oldest toy breeds.',
      c: ['It was kept by ancient Greeks and Romans.', 'It has no undercoat and sheds very little.', 'Its long coat can reach the ground.', 'It is pure white.', 'It is named after a Mediterranean island country.'] },
    { n: 'Bichon Frise', wp: 'Bichon Frisé', alt: ['Bichon'], f: f(FR, 'Toy', 6), d: 2, look: ['Maltese', 'Poodle'],
      b: 'A small, cheerful white dog with a fluffy, powder-puff coat. Its name means "curly lap dog" in French.',
      c: ['Sailors used it as a trading item.', 'Its name means "curly lap dog" in French.', 'It was a favourite of French kings.', 'Its coat is groomed into a round puff.', 'It is small, white and fluffy.'] },
    { n: 'Dalmatian', wp: 'Dalmatian (dog)', f: f(HR, 'Companion', 25), d: 1,
      b: 'A white dog covered in black or liver spots. Puppies are born pure white and grow spots later.',
      c: ['Its puppies are born without spots.', 'It once ran beside horse-drawn fire engines.', 'It is a mascot of firefighters.', 'A Disney film has 101 of them.', 'It is white with black spots.'] },
    { n: 'Jack Russell Terrier', alt: ['Jack Russell'], f: f(UK, 'Terrier', 6), d: 1, look: ['Parson Russell Terrier'],
      b: 'A small, bold, bouncy terrier bred to chase foxes out of their dens.',
      c: ['It is named after a vicar who loved fox hunting.', 'It can jump many times its own height.', 'It is mostly white with tan or black patches.', 'It is full of energy.', 'It is a small, bold terrier named after a man.'] },
    { n: 'Staffordshire Bull Terrier', alt: ['Staffy', 'Staffie'], f: f(UK, 'Terrier', 15), d: 2, look: ['Bull Terrier'],
      b: 'A muscly, friendly terrier with a big grin. It is very popular in the UK and Australia.',
      c: ['It was once nicknamed the "nanny dog".', 'It is very popular in Britain and Australia.', 'It has a broad head and a wide grin.', 'It is short, stocky and muscular.', 'It is named after an English county in the Midlands.'] },
    { n: 'Bull Terrier', f: f(UK, 'Terrier', 27), d: 2, look: ['Staffordshire Bull Terrier'],
      b: 'A muscular terrier with a unique egg-shaped head and small, triangular eyes.',
      c: ['Spuds MacKenzie, a famous beer mascot, was one.', 'Target stores use one as a mascot.', 'It has small, triangular eyes.', 'Its head is shaped like an egg.', 'Its name includes a male cow.'] },
    { n: 'West Highland White Terrier', alt: ['Westie'], f: f(UK, 'Terrier', 8), d: 2, look: ['Scottish Terrier', 'Maltese'],
      b: 'A small, white Scottish terrier with a bright, cheeky face.',
      c: ['It was bred white so hunters would not mistake it for a fox.', 'It appears on Cesar dog food.', 'It has a rough double coat.', 'It comes from Scotland.', 'It is a small, pure white terrier.', 'It was bred to hunt foxes and badgers among rocks.', 'Its face is often trimmed into a round shape.'] },
    { n: 'Scottish Terrier', alt: ['Scottie', 'Aberdeen Terrier'], f: f(UK, 'Terrier', 9), d: 2, look: ['West Highland White Terrier'],
      b: 'A short-legged black terrier with a beard and eyebrows. It is a playing piece in Monopoly.',
      c: ['It is a playing piece in Monopoly.', 'US President Franklin Roosevelt owned one called Fala.', 'It has a beard and bushy eyebrows.', 'It is usually black.', 'It comes from Scotland.'] },
    { n: 'Airedale Terrier', files: ['Airedale Terrier stehend unkupiert.JPG', 'Airedale Terrier 2.jpg', 'Airedale terrier head, Josselin 01.jpg'], alt: ['Airedale'], f: f(UK, 'Terrier', 25), d: 3,
      b: 'The biggest terrier, nicknamed "the king of terriers". It carried messages in World War I.',
      c: ['It carried messages in World War I.', 'It is nicknamed "the king of terriers".', 'It is the largest terrier breed.', 'It has a black saddle and tan legs.', 'It is named after a valley in Yorkshire.', 'Its coat is wiry and dense.', 'It has a long head with a beard.'] },
    { n: 'Whippet', f: f(UK, 'Hound', 13), d: 2, look: ['Greyhound', 'Italian Greyhound'],
      b: 'A slim, fast dog like a small greyhound. It was called "the poor man\'s racehorse".',
      c: ['It was called "the poor man\'s racehorse".', 'It is one of the fastest-accelerating dogs.', 'It loves to curl up on the sofa.', 'It looks like a small greyhound.', 'Its name sounds like a tool for driving horses.'] },
    { n: 'Greyhound', f: f(UK, 'Hound', 30), d: 1, look: ['Whippet', 'Italian Greyhound', 'Saluki'],
      b: 'The fastest dog breed, able to run at about 70 km/h. It is raced on tracks.',
      c: ['It can run at about 70 km/h.', 'Retired racers are often adopted as pets.', 'It has a deep chest and a very thin waist.', 'It is raced on oval tracks chasing a lure.', 'It is the fastest dog breed.'] },
    { n: 'Italian Greyhound', files: ['Italian Greyhound grey.jpg', 'Italian Greyhound (1).jpg'], alt: ['Iggy'], f: f(IT, 'Toy', 4), d: 3, look: ['Whippet', 'Greyhound'],
      b: 'A tiny, slender sighthound that looks like a mini greyhound. It was loved by Renaissance nobles.',
      c: ['It appears in Renaissance paintings.', 'It feels the cold and often wears coats.', 'It is very slim with fine bones.', 'It is a tiny sighthound.', 'It is named after a country shaped like a boot.'] },
    { n: 'Afghan Hound', f: f(AF, 'Hound', 25), d: 2, look: ['Saluki'],
      b: 'A tall, elegant hound with a long, flowing silky coat. It was bred to hunt in the mountains.',
      c: ['Picasso painted one.', 'It was bred to hunt in cold mountains.', 'Its tail curls at the tip like a ring.', 'It has a very long, silky coat.', 'It comes from a country in Central Asia.'] },
    { n: 'Saluki', f: f('Middle East', 'Hound', 22), d: 3, look: ['Afghan Hound', 'Greyhound'],
      b: 'An ancient, graceful sighthound from the Middle East. It was used to hunt gazelles in the desert.',
      c: ['It may be one of the oldest dog breeds.', 'It was used to hunt gazelles.', 'Bedouin people prized it.', 'It has feathery ears and tail.', 'It is a slim desert sighthound.'] },
    { n: 'Basset Hound', alt: ['Basset'], f: f(FR, 'Hound', 27), d: 1, look: ['Beagle', 'Bloodhound', 'Dachshund'],
      b: 'A short-legged hound with long droopy ears and a great nose. It was bred to follow rabbits by scent.',
      c: ['Its name comes from a French word meaning "low".', 'Its long ears sweep scents up to its nose.', 'It has droopy eyes.', 'It has very short legs and very long ears.', 'It is a sad-looking scent hound.'] },
    { n: 'Bloodhound', f: f([BE, FR, UK], 'Hound', 45), d: 1, look: ['Basset Hound'],
      b: 'A big, wrinkly hound with the best sense of smell of any dog. It can follow a trail days old.',
      c: ['Its tracking evidence has been accepted in court.', 'It was bred by monks in Belgium.', 'It can follow a scent trail days old.', 'It has loose, wrinkly skin and long ears.', 'It has the best nose of any dog.'] },
    { n: 'Irish Wolfhound', f: f(IE, 'Hound', 60), d: 2, look: ['Great Dane', 'Scottish Deerhound'],
      b: 'The tallest dog breed. It was bred to hunt wolves in Ireland.',
      c: ['It is the tallest dog breed on average.', 'It nearly died out after the last Irish wolves were killed.', 'It is gentle despite its size.', 'It has a rough, wiry coat.', 'It hunted a wild canine in Ireland.'] },
    { n: 'Saint Bernard', wp: 'St. Bernard (dog)', alt: ['St Bernard', 'St. Bernard'], f: f(CH, 'Working', 75), d: 1, look: ['Bernese Mountain Dog', 'Newfoundland'],
      b: 'A giant rescue dog from the Swiss Alps. Monks used it to find travellers lost in the snow.',
      c: ['One named Barry saved over 40 people.', 'Cartoons show it with a barrel round its neck.', 'Beethoven in the film is one.', 'Monks at a mountain pass bred it.', 'It is a giant Swiss rescue dog.'] },
    { n: 'Newfoundland', wp: 'Newfoundland dog', alt: ['Newfie'], f: f(CA, 'Working', 60), d: 2, look: ['Saint Bernard'],
      b: 'A huge, gentle water dog with webbed feet. It is famous for rescuing people from water.',
      c: ['Nana in "Peter Pan" is one.', 'It has webbed feet.', 'It is famous for water rescues.', 'It has a thick, oily black coat.', 'It is named after a Canadian island.'] },
    { n: 'Alaskan Malamute', alt: ['Malamute'], f: f(US, 'Working', 38), d: 2, look: ['Siberian Husky'],
      b: 'A big, powerful sled dog bred by the Inuit of Alaska to pull heavy loads.',
      c: ['It is named after an Inuit people.', 'It is bigger and stronger than a husky.', 'It was bred for heavy hauling, not speed.', 'It has a plumed tail curled over its back.', 'It comes from a cold US state.'] },
    { n: 'Samoyed', wp: 'Samoyed dog', alt: ['Sammy'], f: f(RU, 'Spitz', 23), d: 2, look: ['Siberian Husky', 'Pomeranian'],
      b: 'A fluffy white sled dog from Siberia. Its upturned mouth looks like a smile.',
      c: ['It is named after the Samoyedic peoples.', 'It went on polar expeditions.', 'Its mouth curls up in a "Sammy smile".', 'It is fluffy and pure white.', 'It comes from Siberia.'] },
    { n: 'Akita', wp: 'Akita (dog)', alt: ['Akita Inu'], f: f(JP, 'Spitz', 40), d: 2, look: ['Shiba Inu'],
      b: 'A big, loyal Japanese dog. The famous Hachikō waited for his dead owner at a station for nearly ten years.',
      c: ['Hachikō waited at Shibuya Station for nearly ten years.', 'Helen Keller brought the first one to the USA.', 'Its tail curls over its back.', 'It is very loyal.', 'It is named after a region of Japan.'] },
    { n: 'Shiba Inu', alt: ['Shiba'], f: f(JP, 'Spitz', 9), d: 1, look: ['Akita'],
      b: 'A small, fox-like Japanese dog. A photo of one became the famous "Doge" meme.',
      c: ['It became the "Doge" internet meme.', 'It makes a loud "Shiba scream".', 'It is Japan\'s smallest native breed.', 'It has a curly tail and pointed ears.', 'It looks like a little red fox.'] },
    { n: 'Chow Chow', alt: ['Chow'], f: f(CN, 'Spitz', 25), d: 2, look: ['Shar Pei'],
      b: 'A fluffy, lion-like dog from China with a blue-black tongue.',
      c: ['It has a blue-black tongue.', 'It walks stiffly on straight back legs.', 'It looks like a lion with its thick mane.', 'It is fluffy and often red.', 'It comes from China and its name repeats.'] },
    { n: 'Shar Pei', wp: 'Shar Pei', alt: ['Chinese Shar-Pei'], f: f(CN, 'Companion', 23), d: 2, look: ['Chow Chow'],
      b: 'A Chinese dog with deep wrinkles and a blue-black tongue. Puppies are even more wrinkly than adults.',
      c: ['It was once one of the rarest dogs in the world.', 'It has a blue-black tongue.', 'Its name means "sand skin".', 'Puppies are even more wrinkly than adults.', 'It is covered in deep wrinkles.'] },
    { n: 'Pekingese', alt: ['Peke'], f: f(CN, 'Toy', 5), d: 2, look: ['Shih Tzu', 'Pug'],
      b: 'A small, long-haired dog once owned only by Chinese emperors. One survived the sinking of the Titanic.',
      c: ['One survived the sinking of the Titanic.', 'Only Chinese royals could own one.', 'It walks with a rolling gait.', 'It has a flat face and long mane.', 'It is named after China\'s capital city.'] },
    { n: 'Lhasa Apso', wp: 'Lhasa Apso', f: f(TB, 'Companion', 6), d: 3, look: ['Shih Tzu'],
      b: 'A small, long-haired dog from Tibet that guarded Buddhist monasteries.',
      c: ['It guarded monasteries indoors.', 'It was often given as a gift by the Dalai Lama.', 'It has a long, heavy coat.', 'It comes from Tibet.', 'It is named after Tibet\'s capital city.'] },
    { n: 'Tibetan Mastiff', f: f(TB, 'Working', 60), d: 3, look: ['English Mastiff'],
      b: 'A huge guardian dog from the Himalayas with a lion-like mane. One sold for a record price in China.',
      c: ['It guarded herds from wolves and snow leopards.', 'One was reportedly sold for millions of dollars in China.', 'It has a thick mane like a lion.', 'It is a huge, fluffy guard dog.', 'It comes from the Himalayas.'] },
    { n: 'English Mastiff', wp: 'English Mastiff', alt: ['Mastiff'], f: f(UK, 'Working', 80), d: 2, look: ['Bullmastiff', 'Great Dane', 'Tibetan Mastiff'],
      b: 'One of the heaviest dog breeds. A mastiff called Zorba was once the heaviest dog ever recorded.',
      c: ['Zorba was once the heaviest dog on record.', 'Romans wrote about British war dogs like it.', 'It has a black mask on its face.', 'It is calm and gentle.', 'It is one of the heaviest breeds.'] },
    { n: 'Bullmastiff', f: f(UK, 'Working', 50), d: 3, look: ['English Mastiff'],
      b: 'A powerful guard dog bred to catch poachers on English estates by pinning them down.',
      c: ['It was nicknamed "the gamekeeper\'s night dog".', 'It pinned poachers without biting.', 'It is a cross of two large breeds.', 'It has a black mask.', 'It is big and muscular.'] },
    { n: 'Weimaraner', alt: ['Weim'], f: f(DE, 'Gundog', 32), d: 2, look: ['Vizsla'],
      b: 'A sleek silver-grey hunting dog nicknamed the "grey ghost". Its puppies have blue eyes.',
      c: ['Photographer William Wegman made it famous.', 'It is nicknamed the "grey ghost".', 'Its eyes are light amber or blue-grey.', 'It has a sleek silver-grey coat.', 'It is named after a German city.'] },
    { n: 'Vizsla', f: f(HU, 'Gundog', 25), d: 3, look: ['Weimaraner', 'Rhodesian Ridgeback'],
      b: 'A sleek, golden-rust hunting dog from Hungary. It likes to stay very close to its owner.',
      c: ['It is nicknamed the "Velcro dog".', 'It has a reddish nose.', 'It has a short golden-rust coat.', 'It comes from Hungary.', 'Its name begins with the letter V.'] },
    { n: 'German Shorthaired Pointer', alt: ['GSP'], f: f(DE, 'Gundog', 27), d: 2,
      b: 'A tireless hunting dog that freezes and points its nose at birds. It is spotted brown and white.',
      c: ['It can hunt on land and in water.', 'It has webbed feet.', 'It freezes and points at hidden birds.', 'It is spotted liver and white.', 'Its coat is short.'] },
    { n: 'English Springer Spaniel', alt: ['Springer Spaniel', 'Springer'], f: f(UK, 'Gundog', 22), d: 2, look: ['English Cocker Spaniel'],
      b: 'A bouncy, eager gundog that flushes birds into the air. It is a favourite sniffer dog.',
      c: ['It is often used as a sniffer dog.', 'It is bigger than the cocker spaniel.', 'It has long, feathery ears.', 'It is usually liver and white.', 'It jumps game birds into the air.'] },
    { n: 'Irish Setter', alt: ['Red Setter'], f: f(IE, 'Gundog', 30), d: 2, look: ['Golden Retriever'],
      b: 'A tall, glossy, mahogany-red gundog with a happy, playful nature.',
      c: ['It was bred to find game birds.', 'It is playful and stays young at heart.', 'It has long, feathery fur on its legs.', 'Its coat is rich mahogany red.', 'It comes from Ireland.'] },
    { n: 'Old English Sheepdog', alt: ['Bobtail'], f: f(UK, 'Herding', 35), d: 2,
      b: 'A big, shaggy grey-and-white dog whose hair often covers its eyes. It was used to drive cattle to market.',
      c: ['It was used to drive cattle to market.', 'It is nicknamed the "bobtail".', 'It has a rolling, bear-like walk.', 'Its shaggy hair often hides its eyes.', 'It is a big grey-and-white herding dog from England.'] },
    { n: 'Rough Collie', alt: ['Lassie dog', 'Collie'], f: f(UK, 'Herding', 25), d: 1, look: ['Shetland Sheepdog', 'Border Collie'],
      b: 'A long-haired Scottish herding dog made famous by the film dog Lassie.',
      c: ['Queen Victoria made it popular.', 'It has a long, narrow face.', 'It has a long, thick mane.', 'It comes from Scotland.', 'Lassie is one.'] },
    { n: 'Australian Cattle Dog', alt: ['Blue Heeler', 'Red Heeler', 'Heeler', 'Queensland Heeler'], f: f(AU, 'Herding', 18), d: 1, look: ['Australian Kelpie'],
      b: 'A tough herding dog from Australia that nips cattle on the heels. Bluey the cartoon dog is one.',
      c: ['It is very energetic and needs lots of exercise.', 'A dog named Bluey lived to 29, the oldest on record.', 'It may have dingo in its ancestry.', 'Puppies are born white and change colour.', 'The cartoon "Bluey" is about one.', 'It nips cows on the heels to move them.', 'It was developed in the 1800s to drive cattle long distances.', 'It is known for its toughness and loyalty.', 'Its coat is speckled blue or red.'] },
    { n: 'Australian Kelpie', alt: ['Kelpie'], f: f(AU, 'Herding', 16), d: 2, look: ['Australian Cattle Dog', 'Border Collie'],
      b: 'A tireless Australian sheepdog that can run across the backs of packed sheep.',
      c: ['Red Dog in the film was one.', 'It can run across the backs of sheep.', 'It can work all day in the heat.', 'It is named after a water spirit from Scottish folklore.', 'It is a sheepdog from Australia.'] },
    { n: 'Australian Terrier', alt: ['Aussie Terrier'], f: f(AU, 'Terrier', 6), d: 3, look: ['Yorkshire Terrier', 'Silky Terrier'],
      b: 'A small, tough terrier and the first Australian breed recognised overseas. It hunted rats and snakes.',
      c: ['It was the first Australian breed shown abroad.', 'It hunted rats and snakes.', 'It has a soft topknot on its head.', 'It is blue and tan or red.', 'It is a small terrier from Australia.', 'It has a rough, shaggy coat.', 'It was bred to work on farms and goldfields.', 'Its ears are small and pricked up.'] },
    { n: 'Silky Terrier', wp: 'Australian Silky Terrier', alt: ['Australian Silky Terrier'], f: f(AU, 'Toy', 4), d: 3, look: ['Yorkshire Terrier', 'Australian Terrier'],
      b: 'A small Australian terrier with a long, fine blue-and-tan coat, bred from Yorkshire and Australian terriers.',
      c: ['It was bred around Sydney.', 'It is a cross of a Yorkshire and an Australian terrier.', 'Its hair is parted down its back.', 'It is blue and tan.', 'Its coat is fine and smooth like a soft fabric.'] },
    { n: 'Papillon', wp: 'Papillon dog', alt: ['Butterfly dog'], f: f(FR, 'Toy', 3), d: 2, look: ['Chihuahua'],
      b: 'A tiny, lively dog with large fringed ears shaped like butterfly wings.',
      c: ['Marie Antoinette is said to have owned one.', 'It is one of the smartest toy breeds.', 'A droop-eared form is called the Phalène.', 'Its ears have long fringes.', 'Its name is French for butterfly.'] },
    { n: 'Basenji', f: f(CG, 'Hound', 10), d: 3,
      b: 'An African hunting dog that does not bark. It yodels instead.',
      c: ['It cleans itself like a cat.', 'Its tail curls tightly.', 'It has a wrinkled forehead.', 'It yodels instead of barking.', 'It is the "barkless dog" of Central Africa.'] },
    { n: 'Rhodesian Ridgeback', alt: ['Ridgeback'], f: f(ZW, 'Hound', 35), d: 2, look: ['Vizsla'],
      b: 'A strong African hound with a stripe of hair growing backwards along its spine. It was used to track lions.',
      c: ['It was nicknamed the "African lion hound".', 'It held lions at bay for hunters.', 'It comes from southern Africa.', 'It is wheaten coloured.', 'A strip of fur on its back grows the wrong way.'] },
    { n: 'Chinese Crested', wp: 'Chinese Crested Dog', alt: ['Chinese Crested Dog'], f: f(CN, 'Toy', 4), d: 2, look: ['Xoloitzcuintle'],
      b: 'A small dog that is mostly hairless, with tufts of hair on its head, feet and tail.',
      c: ['Some are fully furry and called "powderpuffs".', 'It has often won "World\'s Ugliest Dog".', 'It can get sunburn.', 'It has tufts on its head, feet and tail.', 'It is mostly hairless.'] },
    { n: 'Xoloitzcuintle', alt: ['Xolo', 'Mexican Hairless Dog'], f: f(MX, 'Companion'), d: 3, look: ['Chinese Crested'],
      b: 'An ancient hairless dog of Mexico, linked with the Aztec god Xolotl. Dante in Disney\'s "Coco" is one.',
      c: ['The Aztecs linked it with a god of death.', 'It comes in three sizes.', 'Dante in Disney\'s "Coco" is one.', 'It is usually hairless.', 'It is a symbol of Mexico.', 'Its skin feels warm to the touch.', 'Some puppies in a litter are born with fur.', 'Its name is often shortened to four letters.'] },
    { n: 'Puli', wp: 'Puli dog', f: f(HU, 'Herding', 13), d: 2, look: ['Komondor'],
      b: 'A Hungarian sheepdog whose coat grows into long cords, like dreadlocks.',
      c: ['Its cords take years to grow.', 'It is quick and acrobatic.', 'It is usually black.', 'It comes from Hungary.', 'Its coat hangs in long cords like a mop.'] },
    { n: 'Komondor', wp: 'Komondor', f: f(HU, 'Working', 50), d: 3, look: ['Puli'],
      b: 'A huge white Hungarian guard dog covered in long cords of hair. It guarded sheep from wolves.',
      c: ['Its coat can weigh several kilograms.', 'It blends in with the sheep it guards.', 'It guarded flocks from wolves.', 'It is white with long cords like a mop.', 'It comes from Hungary.'] },
    { n: 'Borzoi', alt: ['Russian Wolfhound'], f: f(RU, 'Hound', 35), d: 3, look: ['Afghan Hound', 'Saluki'],
      b: 'A tall, elegant Russian sighthound with a long narrow head. Russian nobles used it to hunt wolves.',
      c: ['Russian nobles hunted wolves with it.', 'Its name means "fast" in Russian.', 'It has a long, narrow head.', 'It has a silky, wavy coat.', 'It is an elegant Russian hound.', 'It hunts by sight rather than smell.', 'It can run very fast over open ground.', 'It was a favourite of the Tsars.'] },
    { n: 'Portuguese Water Dog', alt: ['Portie'], f: f(PT, 'Working', 20), d: 3, look: ['Poodle'],
      b: 'A curly-coated swimming dog that helped fishermen. Barack Obama\'s family had two.',
      c: ['Barack Obama\'s dogs Bo and Sunny were this breed.', 'It herded fish into nets.', 'It has webbed feet.', 'It has a curly or wavy coat.', 'It worked on boats with fishermen.'] },
    { n: 'Leonberger', f: f(DE, 'Working', 55), d: 3, look: ['Saint Bernard', 'Newfoundland'],
      b: 'A giant, gentle German dog with a lion-like mane. It was bred to look like the lion on its town\'s crest.',
      c: ['It was bred to look like a lion on a town crest.', 'It loves water.', 'It has a black mask.', 'It has a thick lion-like mane.', 'It is named after a German town.'] },
    { n: 'Cane Corso', alt: ['Italian Mastiff'], f: f(IT, 'Working', 45), d: 3, look: ['English Mastiff', 'Rottweiler'],
      b: 'A big, muscular Italian guard dog descended from Roman war dogs.',
      c: ['It nearly died out in the 1900s.', 'It descends from Roman war dogs.', 'It is often black or grey.', 'It is a large, muscular guard dog.', 'It comes from Italy.'] },
    { n: 'Belgian Malinois', files: ['BelgianShepherdMalinois.jpg', 'Belgian Malinois 01.jpg'], wp: 'Malinois dog', alt: ['Malinois'], f: f(BE, 'Herding', 27), d: 2, look: ['German Shepherd'],
      b: 'A lean, very energetic herding dog used by police and special forces. One helped in the raid on Osama bin Laden.',
      c: ['A dog named Cairo joined the raid on Osama bin Laden.', 'It is used by special forces.', 'It is lighter than a German Shepherd.', 'It is fawn with a black mask.', 'It comes from Belgium.'] },
    { n: 'Bedlington Terrier', f: f(UK, 'Terrier', 9), d: 3,
      b: 'A terrier that looks like a little lamb, with a curly coat and a pear-shaped head.',
      c: ['It was bred by miners to catch rats.', 'It can run fast like a whippet.', 'It has a pear-shaped head with a topknot.', 'It looks like a little lamb.', 'It is named after a town in Northumberland.'] },
    { n: 'Parson Russell Terrier', f: f(UK, 'Terrier', 7), d: 3, look: ['Jack Russell Terrier'],
      b: 'A longer-legged relative of the Jack Russell, bred to run with fox hounds.',
      c: ['It has longer legs than its close cousin.', 'It was bred to keep up with horses and hounds.', 'It is mostly white.', 'It is named after a vicar.', 'It is a small, bold English terrier.'] },
    { n: 'Scottish Deerhound', alt: ['Deerhound'], f: f(UK, 'Hound', 40), d: 3, look: ['Irish Wolfhound'],
      b: 'A very tall, shaggy grey hound bred to hunt red deer in the Scottish Highlands.',
      c: ['Sir Walter Scott owned one.', 'It looks like a rough-coated greyhound.', 'It has a wiry grey coat.', 'It hunted red deer.', 'It comes from Scotland.'] },
  ],
  fakes: ['Alpine Shadow Hound', 'Brazilian Snow Terrier', 'Danish Cloud Spaniel', 'Golden Moor Collie', 'Norwegian Ridge Retriever', 'Highland Velvet Pointer', 'Persian Water Mastiff', 'Silver Tundra Setter'],
  questions: [
    { kind: 'mc', prompt: 'Which is the smallest dog breed?', answer: 'Chihuahua', wrong: ['Pug', 'Beagle', 'Dachshund'], explain: 'Chihuahuas usually weigh 1.5 to 3 kg.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which breed is the fastest?', answer: 'Greyhound', wrong: ['Bulldog', 'Saint Bernard', 'Pug'], explain: 'Greyhounds can reach about 70 km/h.', difficulty: 1 },
    { kind: 'mc', prompt: 'What breed is Scooby-Doo?', answer: 'Great Dane', wrong: ['Beagle', 'Boxer', 'Labrador Retriever'], explain: 'His creator based him on a Great Dane.', difficulty: 1 },
    { kind: 'mc', prompt: 'What breed is Snoopy from "Peanuts"?', answer: 'Beagle', wrong: ['Dalmatian', 'Poodle', 'Pug'], explain: 'Charles Schulz drew Snoopy as a beagle.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which breed is born pure white and gets its spots later?', answer: 'Dalmatian', wrong: ['Beagle', 'Border Collie', 'Great Dane'], explain: 'Dalmatian spots appear in the first few weeks.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which dog breed does not bark but yodels?', answer: 'Basenji', wrong: ['Siberian Husky', 'Beagle', 'Shiba Inu'], explain: 'Its unusual larynx makes a yodel-like sound.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which two breeds have blue-black tongues?', answer: 'Chow Chow and Shar Pei', wrong: ['Pug and Boxer', 'Akita and Shiba Inu', 'Beagle and Bloodhound'], explain: 'Both come from China.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which country does the Shiba Inu come from?', answer: 'Japan', wrong: ['China', 'Korea', 'Russia'], explain: 'It is Japan\'s smallest native breed.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which famous dog waited at a Tokyo train station for nearly ten years?', answer: 'Hachikō', wrong: ['Laika', 'Lassie', 'Balto'], explain: 'Hachikō, an Akita, waited for his owner at Shibuya Station.', difficulty: 2 },
    { kind: 'tf', prompt: 'The Australian Shepherd was developed in Australia.', answer: false, explain: 'It was developed on ranches in the western USA.', difficulty: 2 },
    { kind: 'mc', prompt: 'What breed is the cartoon dog Bluey?', answer: 'Australian Cattle Dog', wrong: ['Australian Kelpie', 'Border Collie', 'Siberian Husky'], explain: 'Bluey is a Blue Heeler.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which breed was used by monks to rescue travellers in the Alps?', answer: 'Saint Bernard', wrong: ['Newfoundland', 'Bernese Mountain Dog', 'Great Dane'], explain: 'They worked at the Great St Bernard Pass hospice.', difficulty: 1 },
    { kind: 'mc', prompt: 'What does the name Dachshund mean in German?', answer: 'Badger dog', wrong: ['Sausage dog', 'Little legs', 'Long hound'], explain: 'They were bred to hunt badgers.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which breed is a playing piece in Monopoly?', answer: 'Scottish Terrier', wrong: ['Poodle', 'Pug', 'Corgi'], explain: 'The Scottie has been a token since the 1950s.', difficulty: 2 },
  ],
};
