import { INAT, WD } from './_common.mjs';

const EU = 'Europe', AS = 'Asia', AU = 'Australia', AF = 'Africa', NA = 'North America', SA = 'South America', AM = 'the Americas', MED = 'the Mediterranean', ME = 'the Middle East';
const f = (colour, region, emblem) => ({ colour, region, ...(emblem ? { emblem } : {}) });

export default {
  id: 'flowers', title: 'Flowers', theme: 'nature', icon: '🌸', kids: true,
  leakExempt: ['flower', 'flowers'],
  wikiD1: true, wikiAll: true, autoTaxo: ['family', 'genus'],
  factsMeta: {
    colour: { type: 'cat', label: 'Usual colour', clue: v => `It is usually ${v.toLowerCase()}.` },
    region: { type: 'cat', label: 'Native to', clue: v => `It is native to ${v}.` },
    emblem: { type: 'cat', label: 'Floral emblem of', clue: v => `It is the floral emblem of ${v}.` },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which flower is this?",
  tfImgPrompt: "This flower is {aName}.",
  tpl: {"colour": {"ask": "What colour is the {lname} usually?", "stmt": "The {lname} is usually {lvalue}.", "exclusive": false}, "region": {"ask": "Where is the {lname} native to?", "askReverse": "Which of these is native to {value}?", "stmt": "The {lname} is native to {value}.", "exclusive": false}, "emblem": {"ask": "The {lname} is the floral emblem of where?", "askReverse": "Which flower is the floral emblem of {value}?", "stmt": "The {lname} is the floral emblem of {value}."}},
  sources: [INAT, WD],
  items: [
    { n: 'Sunflower', alt: ['common sunflower'], sci: 'Helianthus annuus', g: 'daisy family', f: f('Yellow', NA), d: 1,
      b: 'A tall plant with a huge yellow flower head. Young sunflowers turn to follow the sun.',
      c: ['Its seeds are arranged in spirals.', 'Its seeds are pressed for cooking oil.', 'Young plants turn to follow the sun across the sky.', 'Van Gogh painted it many times.', 'It is a tall plant with a giant yellow flower.'] },
    { n: 'Rose', alt: ['garden rose'], sci: 'Rosa', g: 'rose family', f: f('Red', AS, 'England'), d: 1,
      b: 'A flower with soft, scented petals and thorny stems. Red roses are a symbol of love.',
      c: ['Its fruits are called hips.', 'It is the national flower of England and the USA.', 'Its petals are used to make perfume and rosewater.', 'Its stems have prickles called thorns.', 'Red ones are a symbol of love.'] },
    { n: 'Tulip', sci: 'Tulipa gesneriana', g: 'lily family', f: f('Red', AS), d: 1,
      b: 'A cup-shaped spring flower that grows from a bulb. Tulips are a symbol of the Netherlands.',
      c: ['In the 1630s single bulbs sold for more than a house.', 'It first came from Central Asia and Turkey.', 'It grows from a bulb.', 'Its flowers are cup-shaped.', 'The Netherlands is famous for fields of it.'] },
    { n: 'Common daisy', alt: ['daisy', 'lawn daisy'], sci: 'Bellis perennis', g: 'daisy family', f: f('White', EU), d: 1,
      b: 'A small flower with white petals and a yellow centre that grows in lawns. Children make daisy chains from it.',
      c: ['Its flowers close at night.', 'Its name comes from "day\'s eye".', 'It grows in lawns all over Europe.', 'Children thread them into chains.', 'It has white petals and a yellow centre.'] },
    { n: 'Dandelion', alt: ['common dandelion'], sci: 'Taraxacum officinale', g: 'daisy family', f: f('Yellow', EU), d: 1,
      b: 'A yellow flower that turns into a fluffy "clock" of seeds. Children blow the seeds away.',
      c: ['Its name comes from French for "lion\'s tooth".', 'Its leaves can be eaten in salads.', 'Each seed has its own little parachute.', 'Its seed head is called a clock.', 'It is a yellow lawn weed.'] },
    { n: 'English lavender', alt: ['lavender'], sci: 'Lavandula angustifolia', g: 'mint family', f: f('Purple', MED), d: 1,
      b: 'A purple, sweet-smelling herb. Its flowers are used in soaps, oils and bags to scent drawers.',
      c: ['Provence in France is famous for fields of it.', 'Bees love it.', 'Its oil is used in soap and perfume.', 'It smells sweet and calming.', 'It has spikes of purple flowers.'] },
    { n: 'Moth orchid', alt: ['orchid', 'phalaenopsis'], sci: 'Phalaenopsis', g: 'orchid', f: f('White', AS), d: 1,
      b: 'The most popular house orchid. Its flowers are said to look like moths in flight.',
      c: ['It is a favourite gift plant.', 'It comes from tropical Asia.', 'Its flowers can last for months.', 'In the wild it grows on trees.', 'Its roots grow in the air.', 'It is the most common orchid sold as a houseplant.', 'Its flowers look like moths.'] },
    { n: 'Sacred lotus', alt: ['lotus', 'Indian lotus'], sci: 'Nelumbo nucifera', g: 'lotus', f: f('Pink', AS, 'India'), d: 1, look: ['White water lily'],
      b: 'A pink water flower that rises above the water. It is a holy symbol in Hinduism and Buddhism.',
      c: ['A seed over 1,000 years old has sprouted.', 'Water rolls off its leaves, keeping them clean.', 'Its flowers rise above the water.', 'It is a holy symbol in Hinduism and Buddhism.', 'It is the national flower of India.'] },
    { n: 'White water lily', alt: ['water lily', 'European white waterlily'], sci: 'Nymphaea alba', g: 'water lily', f: f('White', EU), d: 1, look: ['Sacred lotus'],
      b: 'A white flower that floats on ponds among round, flat leaves called lily pads. Monet painted water lilies many times.',
      c: ['Claude Monet painted hundreds of pictures of these plants.', 'Its flowers close at night.', 'Its round leaves are called pads.', 'Its flowers float on ponds.', 'It is a white pond flower.'] },
    { n: 'Common poppy', alt: ['poppy', 'corn poppy', 'red poppy', 'Flanders poppy'], sci: 'Papaver rhoeas', g: 'poppy', f: f('Red', EU), d: 1,
      b: 'A bright red wildflower that grew on the battlefields of World War I. It is worn to remember soldiers who died.',
      c: ['Its seeds can wait in soil for decades.', 'The poem "In Flanders Fields" mentions it.', 'It grew on World War I battlefields.', 'It is worn on Remembrance Day.', 'It is bright red with a black centre.'] },
    { n: 'Wild daffodil', alt: ['daffodil', 'Lent lily'], sci: 'Narcissus pseudonarcissus', g: 'amaryllis family', f: f('Yellow', EU, 'Wales'), d: 1,
      b: 'A yellow spring flower with a trumpet in the middle. It is a symbol of Wales.',
      c: ['William Wordsworth wrote a famous poem about a host of them.', 'Its bulbs are poisonous.', 'It is worn on St David\'s Day.', 'It has a trumpet-shaped centre.', 'It is a yellow spring flower.'] },
    { n: 'Common bluebell', alt: ['bluebell', 'English bluebell'], sci: 'Hyacinthoides non-scripta', g: 'asparagus family', f: f('Blue', EU), d: 1,
      b: 'A woodland flower with drooping blue bells. Half the world\'s bluebells grow in Britain.',
      c: ['About half the world\'s population grows in Britain.', 'It is protected by law in the UK.', 'It carpets woods in spring.', 'Its flowers droop on one side of the stem.', 'It has blue bell-shaped flowers.'] },
    { n: 'Common snowdrop', alt: ['snowdrop'], sci: 'Galanthus nivalis', g: 'amaryllis family', f: f('White', EU), d: 1,
      b: 'A small white flower that droops like a drop of snow. It is one of the first flowers of the year.',
      c: ['A drug for memory loss was made from it.', 'It can push up through snow.', 'It has three outer petals.', 'It flowers in late winter.', 'It is a small, drooping white flower.'] },
    { n: 'Saffron crocus', alt: ['crocus'], sci: 'Crocus sativus', g: 'iris family', f: f('Purple', MED), d: 2,
      b: 'A purple crocus whose red threads are dried to make saffron, the world\'s most expensive spice.',
      c: ['About 150,000 flowers make 1 kg of spice.', 'Its red threads are hand-picked.', 'It flowers in autumn.', 'It is a purple crocus.', 'It gives the world\'s most expensive spice.'] },
    { n: 'Bearded iris', alt: ['iris', 'German iris'], sci: 'Iris germanica', g: 'iris family', f: f('Purple', MED), d: 2,
      b: 'A tall garden flower with three upright and three drooping petals. It inspired the French fleur-de-lis.',
      c: ['It may have inspired the French fleur-de-lis.', 'It is named after a Greek goddess of the rainbow.', 'Its roots are used in perfume.', 'Its drooping petals have a fuzzy "beard".', 'It shares its name with part of the eye.'] },
    { n: 'Chinese hibiscus', alt: ['hibiscus'], sci: 'Hibiscus rosa-sinensis', media: 'wiki', wp: 'Hibiscus rosa-sinensis', inatPhotos: true, g: 'mallow family', f: f('Red', AS, 'Malaysia'), d: 1,
      b: 'A big, trumpet-shaped tropical flower that lasts only a day or so. It is the national flower of Malaysia.',
      c: ['Each flower lasts only about a day.', 'Its petals have been used to shine shoes.', 'It has a long stalk sticking out of the middle.', 'It is the national flower of Malaysia.', 'It is a big red tropical flower.'] },
    { n: 'Mexican marigold', alt: ['marigold', 'African marigold', 'Aztec marigold'], sci: 'Tagetes erecta', g: 'daisy family', f: f('Orange', NA), d: 1,
      b: 'A bright orange flower used to decorate altars and graves for Mexico\'s Day of the Dead.',
      c: ['It is used in garlands in India.', 'Its petals colour chicken feed to make yolks more orange.', 'It is used for Mexico\'s Day of the Dead.', 'It has a strong smell.', 'It is bright orange.'] },
    { n: 'Carnation', sci: 'Dianthus caryophyllus', g: 'pink family', f: f('Pink', MED), d: 1,
      b: 'A frilly-petalled flower often worn in buttonholes. It is a popular flower for Mother\'s Day.',
      c: ['Its scent is a bit like cloves.', 'Its petals have zig-zag edges.', 'It is popular for Mother\'s Day.', 'It is often worn in a buttonhole.', 'It has frilly pink or red petals.'] },
    { n: 'Chrysanthemum', files: ['Chrysanthemum morifolium 08NOV.jpg', 'Chrysanthemum × morifolium Dompierre 1.jpg'], alt: ['mum'], sci: 'Chrysanthemum morifolium', g: 'daisy family', f: f('Yellow', AS, 'Japan'), d: 2,
      b: 'A flower with many layers of petals. It is the symbol of the Japanese emperor.',
      c: ['Japan\'s imperial throne is named after it.', 'In some European countries it is placed on graves.', 'Its name means "gold flower".', 'It flowers in autumn.', 'It has many layers of petals.'] },
    { n: 'Dahlia', sci: 'Dahlia pinnata', g: 'daisy family', f: f('Red', NA), d: 2,
      b: 'A showy garden flower from Mexico that comes in many shapes, from pompoms to spiky "cactus" types.',
      c: ['It is the national flower of Mexico.', 'The Aztecs ate its roots.', 'It is named after a Swedish botanist.', 'It comes in pompom and spiky shapes.', 'Its name starts with "dahl".'] },
    { n: 'Common peony', alt: ['peony'], sci: 'Paeonia officinalis', g: 'peony', f: f('Pink', EU), d: 2,
      b: 'A big, round, frilly flower that blooms in late spring. In China it is called the "king of flowers".',
      c: ['It is called the "king of flowers" in China.', 'Ants are often seen on its buds.', 'One plant can live for 100 years.', 'Its flowers are big and round.', 'It is named after Paeon, a healer in Greek myth.'] },
    { n: 'Bigleaf hydrangea', alt: ['hydrangea', 'hortensia'], sci: 'Hydrangea macrophylla', g: 'hydrangea', f: f('Blue', AS), d: 1,
      b: 'A shrub with big balls of flowers. In acid soil the flowers are blue; in chalky soil they are pink.',
      c: ['Its flowers change colour with the soil.', 'Acid soil turns its flowers blue.', 'It comes from Japan.', 'Its flowers grow in big round balls.', 'Its name begins with "hydra".'] },
    { n: 'Lily of the valley', sci: 'Convallaria majalis', g: 'asparagus family', f: f('White', EU), d: 2,
      b: 'A woodland plant with tiny white bell-shaped flowers and a sweet scent. All parts are poisonous.',
      c: ['In France it is given as a gift on 1 May.', 'All parts of it are poisonous.', 'Its scent is used in perfume.', 'It has tiny white bells.', 'Its name includes a lowland between hills.'] },
    { n: 'Foxglove', alt: ['common foxglove'], sci: 'Digitalis purpurea', g: 'plantain family', f: f('Purple', EU), d: 1,
      b: 'A tall spike of purple, bell-shaped flowers. It is very poisonous, but it gave us an important heart medicine.',
      c: ['A heart drug, digoxin, comes from it.', 'Its genus name means "finger".', 'Its flowers have spots inside.', 'Bees climb inside its tube-shaped flowers.', 'It is named after a wild animal\'s glove.'] },
    { n: 'Water forget-me-not', alt: ['forget-me-not'], sci: 'Myosotis scorpioides', g: 'borage family', f: f('Blue', EU), d: 2,
      b: 'A tiny sky-blue flower with a yellow centre. It is a symbol of remembrance.',
      c: ['Its genus name means "mouse ear".', 'It is the state flower of Alaska.', 'It grows near water.', 'It is tiny, blue and yellow-centred.', 'Its name is a plea to remember.'] },
    { n: 'Garden pansy', alt: ['pansy'], sci: 'Viola × wittrockiana', inat: 'Viola × wittrockiana', g: 'violet family', f: f('Purple', EU), d: 1, look: ['Sweet violet'],
      b: 'A cheerful garden flower with a "face" in the middle. Its name comes from the French word for "thought".',
      c: ['Its name comes from the French "pensée", meaning thought.', 'It was bred from wild violets.', 'It can flower in winter.', 'Its petals seem to show a face.', 'It is a bright garden flower.'] },
    { n: 'Sweet violet', alt: ['violet'], sci: 'Viola odorata', g: 'violet family', f: f('Purple', EU), d: 2, look: ['Garden pansy'],
      b: 'A small, sweet-smelling purple flower. Its scent seems to vanish after a sniff or two.',
      c: ['Its scent seems to disappear after a few sniffs.', 'Its flowers are candied to decorate cakes.', 'It has heart-shaped leaves.', 'A colour is named after it.', 'It is a small, scented purple flower.'] },
    { n: 'Meadow buttercup', alt: ['buttercup'], sci: 'Ranunculus acris', g: 'buttercup family', f: f('Yellow', EU), d: 1,
      b: 'A shiny yellow meadow flower. Children hold it under a chin to see if it glows yellow.',
      c: ['Its sap can irritate skin.', 'Cows avoid eating it.', 'Children hold it under chins to see if they glow.', 'Its petals are glossy.', 'Its name includes a dairy spread.'] },
    { n: 'Bird of paradise', noAutoImg: true, files: ['Ave del Paraíso (Strelitzia reginae), Jardín Botánico de Múnich, Alemania, 2013-05-04, DD 01.jpg', 'Strelitzia April 2015-1.jpg'], alt: ['crane flower', 'strelitzia'], sci: 'Strelitzia reginae', g: 'strelitzia', f: f('Orange', AF), d: 1,
      b: 'A South African flower that looks like a colourful bird\'s head. Sunbirds pollinate it.',
      c: ['It is named after Queen Charlotte.', 'Sunbirds stand on it to drink nectar.', 'It is the official flower of Los Angeles.', 'It comes from South Africa.', 'It looks like the head of a bird.'] },
    { n: 'King protea', alt: ['protea'], sci: 'Protea cynaroides', g: 'protea', f: f('Pink', AF, 'South Africa'), d: 2, look: ['Waratah'],
      b: 'A huge, bowl-shaped flower from South Africa. Its national cricket team is named after it.',
      c: ['South Africa\'s cricket team is named after its family.', 'Its flower head can be 30 cm across.', 'It sprouts again after fires.', 'It comes from the Cape.', 'It is the national flower of South Africa.'] },
    { n: 'Waratah', alt: ['New South Wales waratah'], sci: 'Telopea speciosissima', g: 'protea', f: f('Red', AU, 'New South Wales'), d: 2, look: ['King protea'],
      b: 'A big, bright red Australian flower. It is the floral emblem of New South Wales.',
      c: ['Its name comes from the Eora people of Sydney.', 'It is related to proteas and banksias.', 'Birds drink its nectar.', 'Its flower head is big and bright red.', 'It is the emblem of New South Wales.'] },
    { n: 'Kangaroo paw', noAutoImg: true, files: ['Anigozanthos manglesii gnangarra-1008.jpg', 'Anigozanthos manglesii, Eaton.JPG'], alt: ['red and green kangaroo paw'], sci: 'Anigozanthos manglesii', g: 'kangaroo paw', f: f('Red and green', AU, 'Western Australia'), d: 1,
      b: 'A furry Australian flower shaped like an animal\'s paw. It is the floral emblem of Western Australia.',
      c: ['Birds pollinate it while perching on its stem.', 'Its flowers are covered in velvety hairs.', 'It is red and green.', 'It is the emblem of Western Australia.', 'It is named after a hopping animal\'s foot.'] },
    { n: 'Sturt\'s desert pea', sci: 'Swainsona formosa', g: 'pea family', f: f('Red', AU, 'South Australia'), d: 2,
      b: 'A desert flower with bright red petals and a shiny black "eye". It is the floral emblem of South Australia.',
      c: ['It is named after explorer Charles Sturt.', 'It creeps along the ground.', 'It grows in arid inland Australia.', 'It is the emblem of South Australia.', 'It is red with a glossy black centre.'] },
    { n: 'Old man banksia', ln: 'old man banksia', alt: ['banksia', 'saw banksia'], sci: 'Banksia serrata', g: 'protea', f: f('Yellow', AU), d: 2,
      b: 'A gnarled Australian tree with bottlebrush-like flower spikes. Its old cones inspired May Gibbs\'s "big bad Banksia men".',
      c: ['Its spent flowers turn into hard, knobbly cones.', 'It grows on the east coast of Australia.', 'Its old cones became the villains in May Gibbs\'s stories.', 'It is named after the botanist Joseph Banks.', 'Fire helps open its seed cones.', 'Its leaves have saw-toothed edges.', 'Its flowers grow in big cylindrical spikes.'] },
    { n: 'Flannel flower', sci: 'Actinotus helianthi', g: 'carrot family', f: f('White', AU), d: 3,
      b: 'A soft, white, daisy-like flower of the Sydney region that feels like flannel cloth.',
      c: ['It feels soft like cloth.', 'It flowers heavily after bushfires.', 'It is related to carrots.', 'It grows around Sydney.', 'It is white and fuzzy.'] },
    { n: 'Edelweiss', sci: 'Leontopodium nivale', g: 'daisy family', f: f('White', EU), d: 2,
      b: 'A white, woolly star-shaped flower of the high Alps. A famous song from "The Sound of Music" is named after it.',
      c: ['Its genus name means "lion\'s paw".', 'Its woolly hairs protect it from cold and sun.', 'It grows high in the Alps.', 'A song in "The Sound of Music" is about it.', 'It is a white, star-shaped mountain flower.'] },
    { n: 'Corpse flower', alt: ['rafflesia', 'stinking corpse lily'], sci: 'Rafflesia arnoldii', g: 'rafflesia', f: f('Red', AS), d: 2, look: ['Titan arum'],
      b: 'The biggest single flower in the world, up to a metre across. It smells like rotting meat to attract flies.',
      c: ['It has no leaves, stems or roots of its own.', 'It lives as a parasite on vines.', 'It is named after Sir Stamford Raffles.', 'It smells of rotting meat.', 'It is the biggest single flower in the world.'] },
    { n: 'Titan arum', sci: 'Amorphophallus titanum', g: 'arum family', f: f('Purple', AS), d: 2, look: ['Corpse flower'],
      b: 'A giant plant from Sumatra with the biggest unbranched flower spike in the world. It smells of rotting meat when it blooms.',
      c: ['It may bloom only once every several years.', 'Its spike can be 3 metres tall.', 'It heats up to spread its smell.', 'It comes from Sumatra.', 'It smells of rotting meat.'] },
    { n: 'Venus flytrap', sci: 'Dionaea muscipula', g: 'carnivorous', f: f('White', NA), d: 1,
      b: 'A meat-eating plant whose leaves snap shut on insects. It is found wild only in the Carolinas, USA.',
      c: ['Its traps count: two touches set them off.', 'It grows wild only in North and South Carolina.', 'Its traps have tooth-like bristles.', 'It digests insects.', 'Its leaves snap shut like a mouth.'] },
    { n: 'Gerbera', alt: ['gerbera daisy', 'Barberton daisy'], sci: 'Gerbera jamesonii', g: 'daisy family', f: f('Orange', AF), d: 2,
      b: 'A bright, daisy-like flower from South Africa. It is one of the most popular cut flowers in the world.',
      c: ['It is a member of the daisy family.', 'Florists sell it in bright colours.', 'It comes from near Barberton in South Africa.', 'It is one of the top five cut flowers.', 'It comes in many bright colours.', 'It looks like a big daisy.', 'Its name begins with "gerb".'] },
    { n: 'Common jasmine', alt: ['jasmine'], sci: 'Jasminum officinale', g: 'olive family', f: f('White', AS), d: 2,
      b: 'A climbing plant with small white star-shaped flowers and a strong sweet scent, used in tea and perfume.',
      c: ['Jasmine flowers are used to scent green tea.', 'Its scent is strongest at night.', 'It is used in perfumes.', 'It climbs walls and fences.', 'It has small, white, sweet-smelling flowers.'] },
    { n: 'Frangipani', alt: ['plumeria'], sci: 'Plumeria rubra', g: 'dogbane family', f: f('White', AM, 'Laos'), d: 2,
      b: 'A tropical tree with waxy, scented flowers used in Hawaiian leis. It is the national flower of Laos.',
      c: ['It is the national flower of Laos.', 'It is used to make Hawaiian leis.', 'Its flowers have five waxy petals.', 'It has no nectar but smells sweet.', 'It is a scented tropical flower.'] },
    { n: 'Bougainvillea', sci: 'Bougainvillea glabra', g: 'four o\'clock family', f: f('Pink', SA), d: 2,
      b: 'A thorny climbing plant covered in bright papery "petals" that are really leaves called bracts.',
      c: ['Its bright "petals" are really leaves.', 'Its real flowers are tiny and white.', 'It is named after a French explorer.', 'It has thorns.', 'It is a bright pink climber.'] },
    { n: 'Japanese camellia', alt: ['camellia'], sci: 'Camellia japonica', g: 'tea family', f: f('Pink', AS), d: 2,
      b: 'A shrub with glossy leaves and rose-like flowers that bloom in winter. The tea plant is a close relative.',
      c: ['Coco Chanel used it as her symbol.', 'Tea comes from a close relative.', 'It flowers in winter.', 'Its leaves are glossy and dark.', 'Its flowers look a bit like roses.'] },
    { n: 'Common hyacinth', alt: ['hyacinth'], sci: 'Hyacinthus orientalis', g: 'asparagus family', f: f('Blue', ME), d: 2,
      b: 'A spring bulb with a dense spike of very sweet-smelling flowers, often grown indoors in winter.',
      c: ['It is named after a youth in Greek myth.', 'It can be grown in water in a glass.', 'Its scent is very strong.', 'Its flowers form a dense spike.', 'It grows from a bulb in spring.'] },
    { n: 'Blue passionflower', alt: ['passionflower', 'passion flower'], sci: 'Passiflora caerulea', g: 'passionflower', f: f('Blue', SA), d: 2,
      b: 'An amazing-looking climbing flower with a ring of thread-like filaments. Its relatives produce passion fruit.',
      c: ['Its fruit is orange when ripe.', 'It is often grown over fences.', 'Missionaries linked its parts to the story of the crucifixion.', 'A relative grows passion fruit.', 'It climbs using curly tendrils.', 'It has a ring of thin filaments.', 'It comes from South America.'] },
    { n: 'Spear thistle', alt: ['thistle'], sci: 'Cirsium vulgare', g: 'daisy family', f: f('Purple', EU), d: 2,
      b: 'A spiky plant with purple flower heads. The thistle is the national emblem of Scotland.',
      c: ['Goldfinches eat its seeds.', 'Its seeds float on fluffy parachutes.', 'A legend says it saved Scotland from invaders.', 'It is covered in sharp prickles.', 'It is Scotland\'s national emblem.'] },
    { n: 'Common heather', alt: ['heather', 'ling'], sci: 'Calluna vulgaris', g: 'heath family', f: f('Purple', EU), d: 2,
      b: 'A low, tough shrub that turns moors purple in late summer. White heather is said to be lucky.',
      c: ['White ones are said to bring luck.', 'Bees make a dark honey from it.', 'It was used to make brooms.', 'It covers Scottish moors.', 'It turns hills purple in late summer.'] },
    { n: 'Cornflower', alt: ['bachelor\'s button'], sci: 'Centaurea cyanus', g: 'daisy family', f: f('Blue', EU), d: 2,
      b: 'A bright blue wildflower that once grew in cornfields. A wreath of them was found in Tutankhamun\'s tomb.',
      c: ['Garlands of it were found in Tutankhamun\'s tomb.', 'It is a national symbol of Estonia.', 'It once grew as a weed among crops.', 'A shade of blue is named after it.', 'It is named after a cereal field.'] },
    { n: 'Common morning glory', alt: ['morning glory'], sci: 'Ipomoea purpurea', g: 'bindweed family', f: f('Purple', AM), d: 3,
      b: 'A climbing vine with trumpet-shaped flowers that open in the morning and fade by afternoon.',
      c: ['It is related to the sweet potato.', 'It twines up fences and poles.', 'Its flowers are trumpet-shaped.', 'Each flower lasts only one day.', 'Its flowers open early in the day.'] },
  ],
  fakes: ['Crimson starbell', 'Moonlight tulipwort', 'Golden ghost orchid lily', 'Silver-cup poppy', 'Blue lantern daisy', 'Northern velvet rose'],
  questions: [
    { kind: 'mc', prompt: 'What do bees collect from flowers to make honey?', answer: 'Nectar', wrong: ['Pollen', 'Petals', 'Seeds'], explain: 'Bees also collect pollen, but honey is made from nectar.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which flower is worn to remember soldiers who died in war?', answer: 'Poppy', wrong: ['Rose', 'Daisy', 'Tulip'], explain: 'Poppies grew on World War I battlefields.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which country is famous for its tulip fields?', answer: 'The Netherlands', wrong: ['Italy', 'Brazil', 'Egypt'], explain: 'Tulips first came from Central Asia and Turkey.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which flower is the national flower of India?', answer: 'Lotus', wrong: ['Rose', 'Sunflower', 'Tulip'], explain: 'The sacred lotus is a symbol in Hinduism and Buddhism.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the biggest single flower in the world?', answer: 'Rafflesia', wrong: ['Sunflower', 'Titan arum', 'Water lily'], explain: 'Rafflesia arnoldii can be about 1 m across.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which flower is a symbol of Wales?', answer: 'Daffodil', wrong: ['Thistle', 'Rose', 'Shamrock'], explain: 'Daffodils and leeks are both Welsh symbols.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which spice comes from the threads of a crocus flower?', answer: 'Saffron', wrong: ['Cinnamon', 'Pepper', 'Nutmeg'], explain: 'It takes about 150,000 flowers to make a kilogram.', difficulty: 2 },
    { kind: 'tf', prompt: 'The Venus flytrap eats insects.', answer: true, explain: 'It digests insects to get nutrients missing from boggy soil.', difficulty: 1 },
    { kind: 'mc', prompt: 'What does a hydrangea grown in acid soil look like?', answer: 'Blue', wrong: ['Pink', 'White', 'Black'], explain: 'Aluminium taken up from acid soil turns the flowers blue.', difficulty: 3 },
    { kind: 'mc', prompt: 'Which flower turns into a fluffy "clock" of seeds?', answer: 'Dandelion', wrong: ['Daisy', 'Buttercup', 'Rose'], explain: 'Each seed floats away on a little parachute.', difficulty: 1 },
  ],
};
