import { WD, COMMONS } from './_common.mjs';

const G = 'Gemstone', M = 'Mineral', O = 'Organic', R = 'Rock', ME = 'Metal';
const f = (kind, colour, mohs, birthstone) => ({ kind, colour, ...(mohs != null ? { mohs } : {}), ...(birthstone ? { birthstone } : {}) });

export default {
  id: 'gems', title: 'Gemstones & minerals', theme: 'nature', icon: '💎', kids: true,
  leakExempt: ['stone', 'gem', 'gemstone'],
  media: 'wiki', photos: 2, depicts: 1,
  wdCheckNum: { mohs: 'P1088' }, wdCheckTol: { mohs: 0.75 },
  ranges: { mohs: [1, 10] },
  factsMeta: {
    kind: { type: 'cat', label: 'Kind', values: [G, M, O, R, ME], noClue: true },
    colour: { type: 'cat', label: 'Best-known colour', clue: v => `It is best known in ${v.toLowerCase()}.` },
    mohs: { type: 'num', label: 'Mohs hardness', unit: '', higherLabel: 'Harder', clue: v => `Its Mohs hardness is about ${v}.` },
    birthstone: { type: 'cat', label: 'Birthstone for', values: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'], clue: v => `It is a birthstone for ${v}.` },
  },
  imgPrompt: "Which of these is {lname}?",
  nameImgPrompt: "Which gem or mineral is this?",
  tfImgPrompt: "This is {lname}.",
  tpl: {"kind": {"ask": "What kind of thing is {lname}?", "askReverse": "Which of these is a {lvalue}?", "stmt": "{name} is a {lvalue}."}, "colour": {"ask": "What colour is {lname} best known for?", "stmt": "{name} is best known in {lvalue}.", "exclusive": false}, "mohs": {"askHigh": "Which of these is the hardest?", "askLow": "Which of these is the softest?", "minRatio": 1.3}, "birthstone": {"ask": "{name} is a birthstone for which month?", "askReverse": "Which of these is a birthstone for {value}?", "stmt": "{name} is a birthstone for {value}."}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Diamond', f: f(G, 'Colourless', 10, 'April'), d: 1, look: ['Quartz'],
      b: 'The hardest natural material. It is pure carbon, squeezed deep underground over billions of years.',
      c: ['Its Mohs hardness is the top of the scale.', 'The Cullinan, found in 1905, is the largest gem-quality one ever found.', 'It is made of pure carbon, like pencil lead.', 'It is the hardest natural material.', 'It is the stone in most engagement rings.'] },
    { n: 'Ruby', f: f(G, 'Red', 9, 'July'), d: 1, look: ['Garnet', 'Sapphire'],
      b: 'A red gemstone made of the mineral corundum. Its red colour comes from a trace of chromium.',
      c: ['It is the same mineral as sapphire.', 'Its colour comes from chromium.', 'The first laser in 1960 used a crystal of it.', 'Dorothy\'s slippers in the "Wizard of Oz" film are named after it.', 'It is a red gemstone.'] },
    { n: 'Sapphire', f: f(G, 'Blue', 9, 'September'), d: 1, look: ['Ruby', 'Tanzanite'],
      b: 'A gemstone made of corundum. It is most famous in blue, but it comes in almost every colour except red.',
      c: ['Red forms of the same mineral are called something else.', 'Princess Diana\'s engagement ring has a big one.', 'It is used in tough watch glass.', 'Queensland and Sri Lanka are famous sources.', 'It is a famous blue gemstone.'] },
    { n: 'Emerald', f: f(G, 'Green', 8, 'May'), d: 1, look: ['Peridot', 'Jade'],
      b: 'A deep green gemstone, a kind of the mineral beryl. Colombia produces the finest.',
      c: ['It is a kind of beryl.', 'Most have tiny flaws called "jardin", meaning garden.', 'Colombia is famous for the best ones.', 'Cleopatra loved it.', 'It is a deep green gemstone.'] },
    { n: 'Amethyst', f: f(G, 'Purple', 7, 'February'), d: 1, look: ['Quartz', 'Tanzanite'],
      b: 'A purple kind of quartz. The ancient Greeks believed it stopped you getting drunk.',
      c: ['Its name means "not drunk" in ancient Greek.', 'Heating it can turn it yellow.', 'Big geodes lined with it come from Brazil and Uruguay.', 'It is a kind of quartz.', 'It is a purple gemstone.'] },
    { n: 'Topaz', f: f(G, 'Blue', 8, 'November'), d: 2,
      b: 'A hard gemstone that comes in many colours. Most blue topaz has been treated to make it blue.',
      c: ['It is used as the number 8 on the Mohs scale.', 'Most blue ones are treated with heat and radiation.', 'Imperial ones are golden-orange.', 'It is a birthstone for November.', 'Its name has five letters and starts with T.'] },
    { n: 'Opal', f: f(G, 'Multicoloured', 6, 'October'), d: 1,
      b: 'A gemstone that flashes rainbow colours. Australia produces almost all the world\'s precious opal.',
      c: ['It contains water.', 'Coober Pedy residents live underground to mine it.', 'Its flashes of colour are called "play of colour".', 'Australia mines almost all of the world\'s supply.', 'It flashes all the colours of the rainbow.'] },
    { n: 'Pearl', f: f(O, 'White', 3, 'June'), d: 1,
      b: 'A shiny gem made inside the shell of an oyster or mussel. It is the only gem made by a living animal.',
      c: ['Most sold today are farmed.', 'It dissolves in vinegar.', 'Layers of nacre build it up.', 'It forms inside an oyster.', 'It is a shiny white gem from the sea.'] },
    { n: 'Jade', alt: ['jadeite', 'nephrite'], f: f(G, 'Green', 6.5), d: 1, look: ['Emerald', 'Malachite'],
      b: 'A tough green stone treasured in China for thousands of years. The name covers two different minerals.',
      c: ['Its name covers two different minerals.', 'It is extremely tough and hard to break.', 'Ancient Chinese emperors were buried in suits of it.', 'Māori carve it into pendants called pounamu.', 'It is a green stone prized in China.'] },
    { n: 'Turquoise', f: f(G, 'Blue', 5.5, 'December'), d: 1, look: ['Lapis lazuli'],
      b: 'A sky-blue to green stone prized for thousands of years in Persia, Egypt and the American Southwest.',
      c: ['Tutankhamun\'s mask is inlaid with it.', 'It contains copper.', 'It is prized in Native American jewellery.', 'A colour is named after it.', 'It is a sky-blue stone.'] },
    { n: 'Garnet', f: f(G, 'Red', 7, 'January'), d: 2, look: ['Ruby'],
      b: 'A deep red gemstone. Its crystals often grow as twelve-sided balls.',
      c: ['Its crystals are often twelve-sided.', 'It is used to make sandpaper.', 'Its name comes from the Latin for pomegranate.', 'It is a birthstone for January.', 'It is a deep red gemstone.'] },
    { n: 'Aquamarine', f: f(G, 'Blue', 7.5, 'March'), d: 2, look: ['Topaz', 'Sapphire'],
      b: 'A pale sea-blue kind of beryl, the same mineral as emerald.',
      c: ['It is the same mineral as emerald.', 'Sailors carried it for luck at sea.', 'Its crystals can be huge.', 'It is a birthstone for March.', 'Its name means "sea water".'] },
    { n: 'Peridot', f: f(G, 'Green', 6.5, 'August'), d: 2, look: ['Emerald'],
      b: 'A lime-green gem of the mineral olivine. Some has been found in meteorites.',
      c: ['It has been found in meteorites.', 'It forms deep in the Earth\'s mantle.', 'Hawaii has green beaches made of it.', 'It is a kind of olivine.', 'It is lime green.'] },
    { n: 'Citrine', f: f(G, 'Yellow', 7, 'November'), d: 2, look: ['Topaz', 'Amethyst'],
      b: 'A yellow kind of quartz. Much of it is really amethyst that has been heated.',
      c: ['Much of it is heated amethyst.', 'It is a kind of quartz.', 'It is a birthstone for November.', 'It is yellow to orange.', 'Its name comes from the same word as citrus.'] },
    { n: 'Lapis lazuli', alt: ['lapis'], f: f(R, 'Blue', 5.5), d: 2, look: ['Turquoise'],
      b: 'A deep blue rock with golden flecks of pyrite. It was ground up to make the paint ultramarine.',
      c: ['It was ground to make ultramarine paint.', 'It has golden flecks of pyrite.', 'It was mined in Afghanistan for 6,000 years.', 'Tutankhamun\'s mask contains it.', 'It is a deep blue rock.'] },
    { n: 'Moonstone', f: f(G, 'White', 6, 'June'), d: 2,
      b: 'A milky gemstone with a soft blue glow that seems to float inside it.',
      c: ['It is a kind of feldspar.', 'Its glow is called adularescence.', 'It is a birthstone for June.', 'It has a soft, floating blue glow.', 'It is named after something in the night sky.'] },
    { n: 'Tanzanite', f: f(G, 'Violet-blue', 6.5, 'December'), d: 2, look: ['Sapphire', 'Amethyst'],
      b: 'A violet-blue gem found in only one place on Earth, near Mount Kilimanjaro in Tanzania.',
      c: ['It was discovered in 1967.', 'Tiffany & Co. named it.', 'It looks different colours from different angles.', 'It is found only near Mount Kilimanjaro.', 'It is named after an African country.'] },
    { n: 'Tiger\'s eye', ln: 'tiger\'s eye', f: f(G, 'Golden brown', 7), d: 2,
      b: 'A golden-brown stone with silky bands that seem to shift and shine as it moves.',
      c: ['Its shine is called chatoyancy.', 'It is a kind of quartz.', 'Much of it comes from South Africa.', 'Its bands shine as it moves.', 'It is named after the eye of a big cat.'] },
    { n: 'Malachite', f: f(M, 'Green', 3.75), d: 2, look: ['Jade', 'Turquoise'],
      b: 'A green copper mineral with swirling bands. It was once ground to make green paint.',
      c: ['It was ground into green paint and eye make-up.', 'It is a copper mineral.', 'A room in the Winter Palace is covered in it.', 'It has swirling light and dark bands.', 'It is bright green.'] },
    { n: 'Obsidian', f: f(R, 'Black', 5.5), d: 2,
      b: 'A shiny black volcanic glass formed when lava cools very fast. Its edges can be sharper than steel.',
      c: ['Its edges can be sharper than steel scalpels.', 'The Aztecs used it for blades.', 'It forms when lava cools very fast.', 'It is a natural glass.', 'It is shiny and black.'] },
    { n: 'Quartz', alt: ['rock crystal', 'clear quartz'], f: f(M, 'Colourless', 7), d: 1, look: ['Diamond', 'Amethyst'],
      b: 'One of the most common minerals on Earth. Tiny quartz crystals keep time in watches.',
      c: ['It is number 7 on the Mohs scale.', 'Sand is mostly made of it.', 'Tiny crystals of it keep time in watches.', 'Its crystals have six sides.', 'Amethyst and citrine are kinds of it.'] },
    { n: 'Rose quartz', f: f(M, 'Pink', 7), d: 2, look: ['Quartz', 'Amethyst'],
      b: 'A pale pink kind of quartz, often polished into beads and carvings.',
      c: ['It rarely forms clear crystals.', 'It is often carved into beads.', 'Its colour can fade in strong sunlight.', 'It is a kind of quartz.', 'It is pale pink.'] },
    { n: 'Amber', f: f(O, 'Orange', 2.25), d: 1,
      b: 'Fossilised tree resin, often millions of years old. Some amber has insects trapped inside.',
      c: ['Rubbing it makes static electricity; "electric" comes from its Greek name.', 'It floats in salty water.', 'It is fossilised tree resin.', 'Insects can be trapped inside it.', 'It is golden orange.'] },
    { n: 'Pyrite', alt: ['fool\'s gold', 'iron pyrite'], f: f(M, 'Gold', 6.25), d: 1, look: ['Gold'],
      b: 'A shiny gold-coloured mineral that fooled miners into thinking they had found gold.',
      c: ['It is made of iron and sulphur.', 'It can make sparks when struck.', 'It often forms perfect cubes.', 'Miners mistook it for gold.', 'It is called "fool\'s gold".'] },
    { n: 'Gold', alt: ['native gold'], f: f(ME, 'Gold', 2.75), d: 1, look: ['Pyrite'],
      b: 'A soft, shiny yellow metal that never rusts. One gram can be beaten into a sheet about a square metre in size.',
      c: ['Its chemical symbol is Au.', 'One gram can be hammered into a sheet about a square metre.', 'The biggest nugget, the "Welcome Stranger", was found in Victoria.', 'It never rusts or tarnishes.', 'Olympic winners get a medal of it.'] },
    { n: 'Hematite', alt: ['haematite'], f: f(M, 'Silver-grey', 5.75), d: 3,
      b: 'The main ore of iron. It looks metallic grey but leaves a red-brown streak and makes red ochre.',
      c: ['Its name comes from the Greek for blood.', 'It leaves a red-brown streak.', 'It has been found on Mars.', 'It is the main ore of iron.', 'It looks shiny and metallic grey.'] },
    { n: 'Fluorite', f: f(M, 'Purple', 4), d: 3,
      b: 'A colourful mineral that often glows under ultraviolet light. The word "fluorescent" comes from it.',
      c: ['It is number 4 on the Mohs scale.', 'It is used to make steel.', 'The word fluorescent comes from its name.', 'It often forms cubes.', 'It glows under ultraviolet light.'] },
    { n: 'Calcite', f: f(M, 'White', 3), d: 3,
      b: 'A common mineral that makes up limestone, marble and chalk. A clear crystal of it makes you see double.',
      c: ['It is number 3 on the Mohs scale.', 'A clear piece makes things behind it look double.', 'It fizzes in weak acid.', 'Limestone, chalk and marble are made of it.', 'It is calcium carbonate.'] },
    { n: 'Gypsum', alt: ['selenite', 'desert rose'], f: f(M, 'White', 2), d: 3,
      b: 'A soft mineral used to make plaster and plasterboard. A Mexican cave holds gypsum crystals 11 metres long.',
      c: ['It is number 2 on the Mohs scale.', 'You can scratch it with a fingernail.', 'It is used to make plaster of Paris.', 'Giant crystals of it grow in a Mexican cave.', 'It is a soft white mineral.'] },
    { n: 'Talc', f: f(M, 'White', 1), d: 2,
      b: 'The softest mineral, at the bottom of the Mohs scale. It feels soapy and is ground into talcum powder.',
      c: ['Soapstone is mostly made of it.', 'It feels soapy or greasy.', 'It is ground into baby powder.', 'It is number 1 on the Mohs scale.', 'It is the softest mineral.'] },
    { n: 'Halite', alt: ['rock salt'], f: f(M, 'Colourless', 2.5), d: 2,
      b: 'The mineral form of table salt. Its crystals form perfect cubes.',
      c: ['It forms cubes.', 'It dissolves in water.', 'Salt mines in Poland have chapels carved from it.', 'It is spread on icy roads.', 'It is rock salt.'] },
  ],
  fakes: ['Lunarite', 'Celestine opalite', 'Bluefire garnet', 'Draconite', 'Kryptonite', 'Starmoon beryl', 'Royal azurine'],
  questions: [
    { kind: 'mc', prompt: 'What is the hardest natural material?', answer: 'Diamond', wrong: ['Quartz', 'Gold', 'Ruby'], explain: 'Diamond is 10 on the Mohs scale.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which mineral is the softest, at number 1 on the Mohs scale?', answer: 'Talc', wrong: ['Gypsum', 'Gold', 'Calcite'], explain: 'Talc can be scratched with a fingernail.', difficulty: 2 },
    { kind: 'mc', prompt: 'Ruby and sapphire are both kinds of which mineral?', answer: 'Corundum', wrong: ['Quartz', 'Beryl', 'Feldspar'], explain: 'Red corundum is ruby; other colours are sapphire.', difficulty: 2 },
    { kind: 'mc', prompt: 'Diamonds are made of which element?', answer: 'Carbon', wrong: ['Silicon', 'Iron', 'Oxygen'], explain: 'Graphite in pencils is carbon too.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which country produces almost all of the world\'s precious opal?', answer: 'Australia', wrong: ['Brazil', 'South Africa', 'Canada'], explain: 'Coober Pedy and Lightning Ridge are famous opal towns.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is "fool\'s gold"?', answer: 'Pyrite', wrong: ['Copper', 'Amber', 'Quartz'], explain: 'It is iron sulphide.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which gem forms inside an oyster?', answer: 'Pearl', wrong: ['Opal', 'Amber', 'Jade'], explain: 'The oyster coats an irritant with layers of nacre.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is amber?', answer: 'Fossilised tree resin', wrong: ['Volcanic glass', 'Coloured quartz', 'Dried honey'], explain: 'Some amber has insects trapped inside.', difficulty: 1 },
    { kind: 'mc', prompt: 'What colour is an emerald?', answer: 'Green', wrong: ['Red', 'Blue', 'Purple'], explain: 'Emerald is green beryl.', difficulty: 1 },
    { kind: 'mc', prompt: 'What colour is a ruby?', answer: 'Red', wrong: ['Green', 'Blue', 'Yellow'], explain: 'Chromium makes ruby red.', difficulty: 1 },
    { kind: 'mc', prompt: 'What colour is an amethyst?', answer: 'Purple', wrong: ['Red', 'Green', 'Yellow'], explain: 'It is purple quartz.', difficulty: 1 },
    { kind: 'order', prompt: 'Put these in order from softest to hardest.', answer: ['Talc', 'Calcite', 'Quartz', 'Diamond'], orderLabel: 'Softest to hardest', explain: 'Mohs hardness 1, 3, 7 and 10.', difficulty: 2 },
  ],
};
