import { INAT, WD } from './_common.mjs';

const BE = 'Beetles', LE = 'Butterflies & moths', FL = 'Flies', HY = 'Ants, bees & wasps', OR = 'Grasshoppers & crickets', MA = 'Mantises',
  OD = 'Dragonflies & damselflies', HE = 'True bugs', PH = 'Stick & leaf insects', BL = 'Cockroaches & termites', DE = 'Earwigs', NE = 'Lacewings & antlions', ZY = 'Silverfish';
const FULL = new Set([BE, LE, FL, HY, NE]);
const f = order => ({ order, complete: FULL.has(order) });

export default {
  id: 'insects', title: 'Insects', theme: 'animals', icon: '🐞', kids: true,
  leakExempt: ['insect', 'insects'],
  autoTaxo: ['family', 'genus'],
  factsMeta: {
    order: { type: 'cat', label: 'Insect group', noClue: true },
    complete: { type: 'bool', label: 'Has a pupa stage', yes: 'Egg, larva, pupa, adult', no: 'Egg, nymph, adult', clue: v => (v ? 'It goes through a pupa stage as it grows.' : 'Its young look like small adults; there is no pupa stage.') },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which insect is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"order": {"ask": "Which insect group does the {lname} belong to?", "askReverse": "Which of these belongs to the group \"{value}\"?", "stmt": "The {lname} belongs to the group \"{value}\"."}, "complete": {"askBool": "Which of these insects goes through a pupa stage?", "stmt": "The {lname} goes through a pupa stage as it grows."}},
  sources: [INAT, WD],
  items: [
    { n: 'Seven-spot ladybird', alt: ['ladybird', 'ladybug', 'seven-spotted lady beetle'], sci: 'Coccinella septempunctata', g: 'beetle', f: f(BE), d: 1,
      b: 'A red beetle with seven black spots. Gardeners love it because it eats aphids.',
      c: ['It can eat thousands of aphids in its life.', 'It oozes smelly yellow liquid from its legs when scared.', 'Its larvae look like tiny grey alligators.', 'It is a small, round, red beetle.', 'It has seven black spots.'] },
    { n: 'Monarch butterfly', alt: ['monarch'], sci: 'Danaus plexippus', g: 'butterfly', f: f(LE), d: 1, look: ['Painted lady'],
      b: 'An orange-and-black butterfly famous for flying thousands of kilometres from North America to Mexico for winter.',
      c: ['Its caterpillars eat only milkweed.', 'Birds avoid it because it tastes bad.', 'Millions spend the winter in forests in Mexico.', 'It flies thousands of kilometres each year.', 'It is orange with black veins and shares its name with a king or queen.'] },
    { n: 'Painted lady', sci: 'Vanessa cardui', g: 'butterfly', f: f(LE), d: 2, look: ['Monarch butterfly', 'Red admiral'],
      b: 'One of the most widespread butterflies on Earth. Some fly from Africa to Europe and back again each year.',
      c: ['Some fly from Africa to Europe across the Sahara.', 'It is found on every continent except Antarctica and South America.', 'Its caterpillars often eat thistles.', 'It is orange with black and white spots.', 'Its name sounds like a woman covered in paint.'] },
    { n: 'Peacock butterfly', sci: 'Aglais io', g: 'butterfly', f: f(LE), d: 1,
      b: 'A red butterfly with big eye-spots on its wings. It flashes them to scare off birds.',
      c: ['It spends winter asleep in sheds and hollow trees.', 'It hisses by rubbing its wings together.', 'Its caterpillars eat stinging nettles.', 'It has four big eye-spots on its wings.', 'It is named after a showy bird.'] },
    { n: 'Red admiral', sci: 'Vanessa atalanta', g: 'butterfly', f: f(LE), d: 2, look: ['Painted lady'],
      b: 'A black butterfly with bright red bands and white spots. It is common in gardens in late summer.',
      c: ['Its caterpillars eat nettles.', 'It likes feeding on rotting fruit.', 'Many fly north to Britain each spring.', 'It is black with a red band and white spots.', 'It shares its name with a navy officer.'] },
    { n: 'Small white', alt: ['cabbage white', 'cabbage butterfly'], sci: 'Pieris rapae', g: 'butterfly', f: f(LE), d: 1,
      b: 'A common white butterfly whose green caterpillars munch cabbages. It has spread around the world.',
      c: ['It has spread to North America, Australia and New Zealand.', 'Its green caterpillars are garden pests.', 'It has one or two black spots on each front wing.', 'It loves cabbages and other brassicas.', 'Its wings are white.'] },
    { n: 'Blue morpho', sci: 'Morpho menelaus', g: 'butterfly', f: f(LE), d: 1,
      b: 'A big butterfly from South American rainforests with shining blue wings. The blue comes from tiny scales that reflect light, not from colour.',
      c: ['Its colour comes from the structure of its scales, not pigment.', 'The undersides of its wings are brown with eye-spots.', 'It drinks juice from rotting fruit.', 'It lives in Central and South American rainforests.', 'Its wings are a shining sky colour.'] },
    { n: 'Old World swallowtail', alt: ['swallowtail', 'common yellow swallowtail'], sci: 'Papilio machaon', g: 'butterfly', f: f(LE), d: 2, look: ['Ulysses butterfly'],
      b: 'A big yellow-and-black butterfly with tails on its back wings. In Britain it lives only in the Norfolk Broads.',
      c: ['Its caterpillar pushes out orange "horns" that smell when scared.', 'In Britain it is found only in the Norfolk Broads.', 'Its caterpillars eat milk-parsley and fennel.', 'Its back wings have long tails.', 'It is named after a bird with a forked tail.'] },
    { n: 'Ulysses butterfly', alt: ['blue emperor'], sci: 'Papilio ulysses', g: 'butterfly', f: f(LE), d: 3, look: ['Blue morpho', 'Old World swallowtail'],
      b: 'A large electric-blue swallowtail of north Queensland and New Guinea. It is a tourism symbol of Queensland.',
      c: ['It is a symbol of tourism in Queensland.', 'Males are attracted to anything bright blue.', 'Its back wings have tails.', 'It lives in north Queensland rainforest.', 'It is named after a Greek hero.'] },
    { n: 'Atlas moth', sci: 'Attacus atlas', g: 'moth', f: f(LE), d: 2,
      b: 'One of the biggest moths in the world, from Asian forests. The tips of its wings look like snake heads.',
      c: ['Adults have no working mouth and live only about a week.', 'Its wingtips look like snake heads.', 'Its cocoons have been used as purses in Taiwan.', 'It is one of the largest moths in the world.', 'It is named after a giant who held up the sky.'] },
    { n: 'Luna moth', sci: 'Actias luna', g: 'moth', f: f(LE), d: 2,
      b: 'A pale green North American moth with long trailing tails on its back wings. Adults live only about a week.',
      c: ['Its long tails confuse bats\' echolocation.', 'Adults cannot eat.', 'It lives in North American forests.', 'It is pale lime green.', 'Its name means moon.'] },
    { n: 'Death\'s-head hawkmoth', ln: 'death\'s-head hawkmoth', sci: 'Acherontia atropos', g: 'moth', f: f(LE), d: 2,
      b: 'A big moth with a skull-like pattern on its back. It squeaks loudly and raids beehives for honey.',
      c: ['It appears on the poster for "The Silence of the Lambs".', 'It sneaks into beehives to steal honey.', 'It squeaks when handled.', 'It is one of the largest moths in Europe.', 'It has a skull-like pattern on its back.'] },
    { n: 'Hummingbird hawk-moth', sci: 'Macroglossum stellatarum', g: 'moth', f: f(LE), d: 2,
      b: 'A day-flying moth that hovers in front of flowers and sips nectar with a long tongue, just like a tiny bird.',
      c: ['It flies by day, unlike most moths.', 'Its wings beat so fast they hum.', 'It uncurls a long tongue to drink nectar.', 'It hovers in front of flowers.', 'It looks like a tiny bird from the Americas.'] },
    { n: 'Bogong moth', sci: 'Agrotis infusa', g: 'moth', f: f(LE), d: 3,
      b: 'A brown Australian moth that flies to cool mountain caves for summer. Aboriginal people feasted on them there.',
      c: ['It can navigate using the stars.', 'Millions shelter in alpine caves in summer.', 'Aboriginal people roasted them as food.', 'Swarms have invaded Parliament House in Canberra.', 'It is a brown moth from south-eastern Australia.'] },
    { n: 'Domestic silk moth', alt: ['silkworm'], sci: 'Bombyx mori', g: 'moth', f: f(LE), d: 2,
      b: 'A moth bred by people for 5,000 years. Its caterpillar spins a cocoon of the thread we use to make silk.',
      c: ['It no longer exists in the wild.', 'Adults cannot fly.', 'Its caterpillars eat mulberry leaves.', 'It was first farmed in China.', 'Its cocoon is unwound to make a smooth shiny cloth.'] },
    { n: 'Stag beetle', alt: ['European stag beetle'], sci: 'Lucanus cervus', g: 'beetle', f: f(BE), d: 1,
      b: 'A big beetle whose males have huge jaws like antlers. They use them to wrestle other males.',
      c: ['Its larvae live in rotting wood for up to six years.', 'Adults live only a few weeks.', 'Males wrestle with their giant jaws.', 'It is the biggest beetle in Britain.', 'The male\'s jaws look like a deer\'s antlers.'] },
    { n: 'Hercules beetle', sci: 'Dynastes hercules', g: 'beetle', f: f(BE), d: 1, look: ['Stag beetle'],
      b: 'One of the longest beetles in the world, from Central and South American rainforests. Males have a huge horn.',
      c: ['Males can be about 17 cm long including the horn.', 'It can change colour from olive to black with humidity.', 'Males use their horns to flip rivals.', 'It is a kind of rhinoceros beetle.', 'It is named after a strong Greek hero.'] },
    { n: 'Goliath beetle', sci: 'Goliathus goliatus', g: 'beetle', f: f(BE), d: 2,
      b: 'One of the heaviest insects in the world, from African rainforests. Its larvae can weigh up to 100 grams.',
      c: ['Its larvae can weigh about 100 grams.', 'It lives in African rainforests.', 'It has bold black and white markings.', 'It is one of the heaviest insects.', 'It is named after a giant from the Bible.'] },
    { n: 'Sacred scarab', alt: ['dung beetle', 'scarab beetle'], sci: 'Scarabaeus sacer', g: 'beetle', f: f(BE), d: 2,
      b: 'A dung beetle that rolls balls of dung. Ancient Egyptians linked it with the sun god.',
      c: ['Ancient Egyptians saw it as a symbol of the rising sun.', 'Some of its relatives steer using the Milky Way.', 'It lays its eggs inside a ball of droppings.', 'It rolls a ball much bigger than itself.', 'It eats animal poo.'] },
    { n: 'Common eastern firefly', alt: ['firefly', 'lightning bug'], sci: 'Photinus pyralis', g: 'beetle', f: f(BE), d: 1,
      b: 'A beetle whose tail glows in the dark. Males flash their lights to talk to females on summer nights.',
      c: ['It is really a beetle, not a fly.', 'Its light makes almost no heat.', 'Males flash a J-shaped pattern while flying.', 'It flashes on summer nights.', 'Its tail glows in the dark.'] },
    { n: 'Christmas beetle', sci: 'Anoplognathus', g: 'beetle', f: f(BE), d: 2,
      b: 'Shiny golden-brown beetles that swarm around Australian gum trees in early summer.',
      c: ['They eat eucalyptus leaves.', 'Their larvae are lawn grubs.', 'They buzz around lights on summer nights.', 'They are shiny gold or brown.', 'They appear in Australia around the end of December.'] },
    { n: 'Bombardier beetle', sci: 'Brachinus', g: 'beetle', f: f(BE), d: 2,
      b: 'A beetle that sprays a boiling-hot chemical spray from its tail with a popping sound.',
      c: ['Its spray reaches about 100 °C.', 'Two chemicals mix inside it and explode.', 'It can aim its spray in many directions.', 'It makes a popping sound.', 'It is named after a soldier who fires big guns.'] },
    { n: 'Colorado potato beetle', sci: 'Leptinotarsa decemlineata', g: 'beetle', f: f(BE), d: 3,
      b: 'A striped beetle that is a serious pest of potato crops. It has resisted many insecticides.',
      c: ['It has 10 black stripes.', 'It has become resistant to many insecticides.', 'It spread from America to Europe.', 'It strips the leaves off spud plants.', 'It is named after an American state and a vegetable.'] },
    { n: 'Acorn weevil', sci: 'Curculio glandium', g: 'beetle', f: f(BE), d: 3,
      b: 'A small beetle with an extremely long snout. It drills into acorns to lay its eggs.',
      c: ['Its snout can be as long as its body.', 'It drills holes in nuts to lay eggs.', 'Its larvae eat their way out of the nut.', 'It is a kind of weevil.', 'It lays eggs in the nuts of oak trees.'] },
    { n: 'European mantis', alt: ['praying mantis', 'mantis'], sci: 'Mantis religiosa', g: 'mantis', f: f(MA), d: 1, look: ['Orchid mantis'],
      b: 'A green insect that holds its spiky front legs as if praying. It catches other insects in a flash.',
      c: ['It can turn its head to look over its shoulder.', 'Females sometimes eat males.', 'It ambushes insects with lightning-fast front legs.', 'Its front legs fold up like a pocket knife.', 'It is a long green insect.'] },
    { n: 'Orchid mantis', sci: 'Hymenopus coronatus', g: 'mantis', f: f(MA), d: 2, look: ['European mantis'],
      b: 'A pink-and-white mantis from South-East Asia that looks like a flower. Insects that come to visit get eaten.',
      c: ['Insects mistake it for a flower.', 'Its legs look like petals.', 'It lives in South-East Asian rainforests.', 'It is pink and white.', 'It looks like a famous flower.'] },
    { n: 'Spiny leaf insect', alt: ['giant prickly stick insect', 'Macleay\'s spectre'], sci: 'Extatosoma tiaratum', g: 'stick insect', f: f(PH), d: 2, look: ['Leaf insect'],
      b: 'A big spiky Australian stick insect that curls its tail like a scorpion. Ants carry its eggs into their nests.',
      c: ['Ants carry its eggs into their nests.', 'It curls its tail like a scorpion.', 'It is a popular pet in Australia.', 'It is covered in spikes.', 'It is a kind of stick insect.'] },
    { n: 'Leaf insect', alt: ['walking leaf'], sci: 'Phyllium', g: 'stick insect', f: f(PH), d: 2, look: ['Spiny leaf insect'],
      b: 'An insect so flat and green it looks exactly like a leaf, even with fake veins and bite marks.',
      c: ['Some even have brown edges as if they are dying.', 'It sways gently as if blown by the wind.', 'It lives in South-East Asia.', 'It is flat and green.', 'It looks just like part of a plant.'] },
    { n: 'Emperor dragonfly', alt: ['dragonfly'], sci: 'Anax imperator', g: 'dragonfly', f: f(OD), d: 1, look: ['Banded demoiselle'],
      b: 'A big blue-and-green dragonfly that patrols ponds. It catches other insects in mid-air.',
      c: ['Its young live underwater for a year or more.', 'It eats its prey while flying.', 'It is one of the largest dragonflies in Europe.', 'Males have a bright blue body.', 'It is named after a ruler of an empire.'] },
    { n: 'Banded demoiselle', alt: ['damselfly'], sci: 'Calopteryx splendens', g: 'damselfly', f: f(OD), d: 2, look: ['Emperor dragonfly'],
      b: 'A damselfly with a shining blue-green body. Males have a dark band on each wing and flutter like butterflies.',
      c: ['It folds its wings along its body at rest.', 'It flutters like a butterfly.', 'It lives along slow rivers.', 'Males have a dark patch across each wing.', 'Its name means young lady.'] },
    { n: 'Desert locust', alt: ['locust'], sci: 'Schistocerca gregaria', g: 'grasshopper', f: f(OR), d: 2,
      b: 'A grasshopper that can form enormous swarms. A swarm can eat as much food in a day as millions of people.',
      c: ['Crowding changes its colour and behaviour.', 'Swarms can contain billions of insects.', 'It is one of the plagues in the Bible story of Exodus.', 'Swarms destroy crops in Africa and Asia.', 'It is a swarming grasshopper.'] },
    { n: 'House cricket', alt: ['cricket'], sci: 'Acheta domesticus', g: 'cricket', f: f(OR), d: 2,
      b: 'A cricket that chirps by rubbing its wings. It is farmed as food for pets and people.',
      c: ['Its ears are on its front legs.', 'It is farmed as food for reptiles.', 'Males chirp by rubbing their wings together.', 'It has very long antennae.', 'It shares its name with a bat-and-ball game.'] },
    { n: 'Green grocer cicada', alt: ['cicada', 'greengrocer'], sci: 'Cyclochila australasiae', g: 'cicada', f: f(HE), d: 1,
      b: 'A big green Australian cicada. Males sing so loudly in summer they are among the loudest insects in the world.',
      c: ['Its young live underground for years.', 'Children collect the empty skins from tree trunks.', 'It is one of the loudest insects in the world.', 'It sings on hot summer days in Australia.', 'It is green, like a fresh vegetable seller\'s name.'] },
    { n: 'Periodical cicada', sci: 'Magicicada septendecim', g: 'cicada', f: f(HE), d: 3, look: ['Green grocer cicada'],
      b: 'A red-eyed cicada of the eastern USA that lives underground for 17 years, then comes out in billions all at once.',
      c: ['Its species name means seventeen.', 'Billions emerge in the same year.', 'It has bright red eyes.', 'It lives underground for 17 years.', 'It appears only once every many years.'] },
    { n: 'Bullet ant', sci: 'Paraponera clavata', g: 'ant', f: f(HY), d: 2,
      b: 'A large rainforest ant with the most painful sting of any insect, said to feel like being shot.',
      c: ['The Sateré-Mawé people use it in a coming-of-age ritual.', 'The pain from its sting can last a whole day.', 'It lives in Central and South American rainforests.', 'It tops the Schmidt sting pain index.', 'Its sting is said to feel like being shot.'] },
    { n: 'Leafcutter ant', sci: 'Atta cephalotes', g: 'ant', f: f(HY), d: 1,
      b: 'Ants that carry pieces of leaf back to their nest. They do not eat the leaves but use them to farm a fungus.',
      c: ['They grow a fungus garden for food.', 'A nest can hold millions of ants.', 'They carry loads far heavier than themselves.', 'Lines of them march through the rainforest.', 'They cut pieces out of leaves.'] },
    { n: 'Green tree ant', alt: ['weaver ant', 'green ant'], sci: 'Oecophylla smaragdina', g: 'ant', f: f(HY), d: 2,
      b: 'A tropical ant that sews leaves together into nests using silk from its larvae. Its green rear end tastes of lime.',
      c: ['Its rear end tastes like lime.', 'Workers hold larvae that squeeze out silk.', 'They build nests by sewing leaves together.', 'It lives in trees in northern Australia and Asia.', 'Its bottom is green.'] },
    { n: 'Red imported fire ant', alt: ['fire ant'], sci: 'Solenopsis invicta', g: 'ant', f: f(HY), d: 2,
      b: 'A South American ant with a burning sting. It has invaded the USA, Australia and Asia.',
      c: ['Colonies form floating rafts in floods.', 'Its species name means unbeaten.', 'It has invaded Brisbane and the southern USA.', 'Its sting leaves white pimples.', 'Its sting burns like a flame.'] },
    { n: 'American cockroach', alt: ['cockroach'], sci: 'Periplaneta americana', g: 'cockroach', f: f(BL), d: 1,
      b: 'A big reddish-brown cockroach that lives in drains and buildings around the world. It can run very fast.',
      c: ['It can live for a week without its head.', 'It can run about 50 body lengths a second.', 'It lives in sewers and warm buildings.', 'It is a large reddish-brown kitchen pest.', 'Despite its name, it probably came from Africa.'] },
    { n: 'Magnetic termite', alt: ['termite'], sci: 'Amitermes meridionalis', g: 'termite', f: f(BL), d: 3,
      b: 'A termite of northern Australia that builds tall, flat mounds lined up north to south, which keeps them from overheating.',
      c: ['Its mounds are thin and wedge-shaped.', 'You can see its mounds in Litchfield National Park.', 'Its mounds line up north to south.', 'It eats grass.', 'Its mounds act like a compass.'] },
    { n: 'Housefly', alt: ['house fly', 'fly'], sci: 'Musca domestica', g: 'fly', f: f(FL), d: 1,
      b: 'The common fly found in homes all over the world. It tastes with its feet and spits on food before eating it.',
      c: ['It tastes food with its feet.', 'It spits on food to soften it.', 'Its eyes are made of thousands of lenses.', 'It buzzes around kitchens.', 'It is the commonest fly in homes.'] },
    { n: 'Yellow fever mosquito', alt: ['mosquito'], sci: 'Aedes aegypti', g: 'fly', f: f(FL), d: 1,
      b: 'A small black-and-white striped mosquito that spreads dengue, Zika and yellow fever. Only females bite.',
      c: ['It spreads dengue and Zika viruses.', 'Its eggs can survive dry for months.', 'Only the females drink blood.', 'Its legs have white bands.', 'Its bite leaves an itchy bump.'] },
    { n: 'Common earwig', alt: ['earwig'], sci: 'Forficula auricularia', g: 'earwig', f: f(DE), d: 1,
      b: 'A brown insect with pincers on its tail. Despite the myth, it does not crawl into people\'s ears.',
      c: ['Mothers guard and clean their eggs.', 'It can fly but rarely does.', 'Males have curved pincers.', 'An old myth says it crawls into ears.', 'It has pincers on its tail end.'] },
    { n: 'Giant wētā', alt: ['weta', 'giant weta'], sci: 'Deinacrida', g: 'cricket', f: f(OR), d: 3,
      b: 'Huge flightless crickets from New Zealand. Some are among the heaviest insects in the world.',
      c: ['One was recorded weighing 71 grams.', 'They cannot fly.', 'Many survive only on predator-free islands.', 'They live in New Zealand.', 'Their Māori name is four letters long.'] },
    { n: 'Common pond skater', alt: ['water strider', 'pond skater'], sci: 'Gerris lacustris', g: 'bug', f: f(HE), d: 2,
      b: 'A long-legged bug that skates across the surface of ponds without sinking, using surface tension.',
      c: ['It feels ripples to find insects that fall in.', 'Water-repellent hairs keep it afloat.', 'It uses surface tension.', 'It has long thin legs.', 'It glides across ponds.'] },
    { n: 'Green shield bug', alt: ['stink bug', 'shield bug'], sci: 'Palomena prasina', g: 'bug', f: f(HE), d: 2,
      b: 'A bright green bug shaped like a shield. It gives off a bad smell when it is disturbed.',
      c: ['It turns bronze in autumn.', 'It sucks juices from plants.', 'It gives off a bad smell when scared.', 'It is bright green.', 'It is shaped like a knight\'s shield.'] },
    { n: 'Pea aphid', alt: ['aphid', 'greenfly'], sci: 'Acyrthosiphon pisum', g: 'bug', f: f(HE), d: 2,
      b: 'A tiny green bug that sucks sap from plants. Females can give birth without mating.',
      c: ['Ants "farm" it for its sugary honeydew.', 'Females can give birth to live young without males.', 'Ladybirds eat them by the hundreds.', 'It sucks sap from plants.', 'It is a tiny sap-sucking pest of beans and clover.'] },
    { n: 'Silverfish', sci: 'Lepisma saccharinum', g: 'silverfish', f: f(ZY), d: 2,
      b: 'A wingless, silvery insect that wriggles like a fish. It eats starch in paper, glue and food.',
      c: ['It can live for years.', 'It eats paper, glue and book bindings.', 'It has no wings.', 'It wriggles like a fish when it runs.', 'It is covered in shiny grey scales.'] },
    { n: 'Antlion', sci: 'Myrmeleontidae', g: 'lacewing', f: f(NE), d: 3,
      b: 'Its larva digs a cone-shaped pit in sand and waits at the bottom for ants to fall in. Adults look like damselflies.',
      c: ['Its larva is also called a doodlebug.', 'Adults look like damselflies.', 'Its larva flicks sand at prey trying to climb out.', 'Its larva digs a pit trap in sand.', 'It is named after an insect and a big cat.'] },
    { n: 'Green lacewing', alt: ['lacewing'], sci: 'Chrysoperla carnea', g: 'lacewing', f: f(NE), d: 2,
      b: 'A delicate green insect with see-through, net-veined wings. Its larvae eat lots of aphids.',
      c: ['It lays each egg on top of a thin stalk.', 'Its larvae are called aphid lions.', 'It has golden eyes.', 'Its wings are clear with a net of veins.', 'It is a pale green insect.'] },
  ],
  fakes: ['Crimson glass beetle', 'Northern thunder moth', 'Silver-winged stick mantis', 'Golden ribbon dragonfly beetle', 'Velvet comb cricket', 'Spotted lantern weevil-fly'],
  questions: [
    { kind: 'number', prompt: 'How many legs does an insect have?', answer: 6, unit: 'legs', tolerance: 0, explain: 'All adult insects have six legs.', difficulty: 1 },
    { kind: 'number', prompt: 'How many main body parts does an insect have?', answer: 3, unit: 'parts', tolerance: 0, explain: 'Head, thorax and abdomen.', difficulty: 2 },
    { kind: 'mc', prompt: 'What does a caterpillar turn into?', answer: 'A butterfly or moth', wrong: ['A beetle', 'A spider', 'A dragonfly'], explain: 'Caterpillars are the larvae of butterflies and moths.', difficulty: 1 },
    { kind: 'order', prompt: 'Put a butterfly\'s life cycle in order.', answer: ['Egg', 'Caterpillar', 'Chrysalis', 'Butterfly'], orderLabel: 'First to last', explain: 'The chrysalis is the pupa stage.', difficulty: 1 },
    { kind: 'tf', prompt: 'A spider is an insect.', answer: false, explain: 'Spiders have eight legs and are arachnids.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which of these is NOT an insect?', answer: 'Spider', wrong: ['Ant', 'Beetle', 'Butterfly'], explain: 'Spiders are arachnids with eight legs.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do fireflies use their glowing lights for?', answer: 'Signalling to find a mate', wrong: ['Keeping warm', 'Seeing in the dark', 'Scaring bats'], explain: 'Each species has its own flash pattern.', difficulty: 2 },
    { kind: 'tf', prompt: 'A firefly is a kind of fly.', answer: false, explain: 'Fireflies are beetles.', difficulty: 2 },
    { kind: 'tf', prompt: 'A ladybird is a kind of beetle.', answer: true, explain: 'Ladybirds belong to the beetle family Coccinellidae.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which insect group has the most known species?', answer: 'Beetles', wrong: ['Butterflies and moths', 'Flies', 'Ants, bees and wasps'], explain: 'About 400,000 beetle species have been described.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which insect has the most painful sting, according to the Schmidt pain index?', answer: 'Bullet ant', wrong: ['Honey bee', 'Fire ant', 'Common wasp'], explain: 'Its sting is said to feel like being shot.', difficulty: 2 },
    { kind: 'mc', prompt: 'What do leafcutter ants do with the leaves they collect?', answer: 'Grow fungus on them for food', wrong: ['Eat them straight away', 'Build roofs with them', 'Feed them to aphids'], explain: 'The ants eat the fungus, not the leaves.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which butterfly migrates from Canada and the USA to Mexico each winter?', answer: 'Monarch butterfly', wrong: ['Blue morpho', 'Small white', 'Peacock butterfly'], explain: 'Millions gather in fir forests in central Mexico.', difficulty: 2 },
    { kind: 'mc', prompt: 'Where are a cricket\'s ears?', answer: 'On its front legs', wrong: ['On its head', 'On its wings', 'It has no ears'], explain: 'Crickets hear through eardrums just below the knees of their front legs.', difficulty: 3 },
    { kind: 'mc', prompt: 'Only which mosquitoes bite to drink blood?', answer: 'Females', wrong: ['Males', 'Babies', 'Both males and females equally'], explain: 'Females need the protein in blood to make eggs.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is a dragonfly\'s young called?', answer: 'A nymph', wrong: ['A caterpillar', 'A tadpole', 'A grub'], explain: 'Dragonfly nymphs live underwater and hunt other small animals.', difficulty: 3 },
    { kind: 'tf', prompt: 'Insects have their skeleton on the outside of their bodies.', answer: true, explain: 'It is called an exoskeleton.', difficulty: 2 },
    { kind: 'mc', prompt: 'How long do periodical cicadas of the eastern USA live underground, at most?', answer: '17 years', wrong: ['1 year', '5 years', '50 years'], explain: 'Some broods emerge every 13 years, others every 17.', difficulty: 3 },
  ],
};
