import { WD, COMMONS } from './_common.mjs';

const UK = 'United Kingdom', US = 'United States', FR = 'France', DE = 'Germany', IT = 'Italy', NL = 'Netherlands', AU = 'Australia', SE = 'Sweden', CH = 'Switzerland', CN = 'China', HU = 'Hungary', DK = 'Denmark', JP = 'Japan';
const f = (year, inventor, country) => ({ year, inventor, country });

export default {
  id: 'inventions', title: 'Inventions', theme: 'science', icon: '💡', kids: true,
  leakExempt: [],
  media: 'wiki', photos: 1, depicts: 0, lnamePrefix: 'the ',
  ranges: { year: [100, 2010] },
  factsMeta: {
    year: { type: 'year', label: 'Year', higherLabel: 'Later', clue: v => `It dates from ${v}.` },
    inventor: { type: 'text', label: 'Inventor', clue: v => `It is credited to ${v}.` },
    country: { type: 'cat', label: 'Country', clue: v => `It was invented in ${v}.` },
  },
  imgPrompt: "Which of these is {lname}?",
  nameImgPrompt: "Which invention is this?",
  tfImgPrompt: "This is {lname}.",
  tpl: {"year": {"askHigh": "Which of these is the newest invention?", "askLow": "Which of these is the oldest invention?", "minRatio": 1.01}, "inventor": {"ask": "Who is credited with {lname}?", "askReverse": "Which invention is credited to {value}?", "stmt": "The {lname} is credited to {value}."}, "country": {"ask": "Where was {lname} invented?", "askReverse": "Which of these was invented in {value}?", "stmt": "The {lname} was invented in {value}."}},
  sources: [WD, COMMONS],
  items: [
    { n: 'Paper', ln: 'paper', f: f(105, 'Cai Lun', CN), d: 1,
      b: 'Paper made from plant fibres was improved and recorded by Cai Lun, a Chinese court official, around 105 AD.',
      c: ['Its maker was a court official of the Han dynasty.', 'Early versions used tree bark, hemp and old fishing nets.', 'The idea reached Europe over a thousand years later.', 'Books and newspapers are printed on it.', 'You write on it with a pen.'] },
    { n: 'Printing press', alt: ['movable-type printing press'], f: f(1440, 'Johannes Gutenberg', DE), d: 1,
      b: 'Johannes Gutenberg\'s press with movable metal type made books much cheaper and spread ideas across Europe.',
      c: ['Its most famous early product was a Bible.', 'It used movable metal letters.', 'It was developed in Mainz.', 'It made books cheap and common.', 'It prints pages of text.'] },
    { n: 'Telescope', f: f(1608, 'Hans Lipperhey', NL), d: 1,
      b: 'The first known telescope patent was filed by the Dutch spectacle-maker Hans Lipperhey in 1608. Galileo soon used one to study the sky.',
      c: ['A Dutch spectacle-maker applied for the first patent.', 'Galileo used one to find moons around Jupiter.', 'Isaac Newton built a version using a mirror.', 'Hubble is a famous space version.', 'It makes faraway things look closer.'] },
    { n: 'Barometer', f: f(1643, 'Evangelista Torricelli', IT), d: 3,
      b: 'Evangelista Torricelli made the first mercury barometer in 1643. It measures air pressure and helps forecast weather.',
      c: ['Its inventor was a student of Galileo.', 'Early ones used a tube of mercury.', 'Falling readings can mean a storm is coming.', 'It measures air pressure.', 'It helps forecast the weather.'] },
    { n: 'Pendulum clock', f: f(1656, 'Christiaan Huygens', NL), d: 3,
      b: 'Christiaan Huygens built the first pendulum clock in 1656. It was far more accurate than any clock before.',
      c: ['Galileo had studied how its key part swings.', 'It made clocks accurate to within a minute a day.', 'Grandfather clocks use one.', 'It ticks as a weight swings back and forth.', 'It keeps time with a swinging weight.'] },
    { n: 'Mercury thermometer', f: f(1714, 'Daniel Gabriel Fahrenheit', NL), d: 3,
      b: 'Daniel Fahrenheit made the first mercury thermometer in 1714 and later created a temperature scale.',
      c: ['Its inventor also created a temperature scale used in the USA.', 'It uses a liquid metal in a thin glass tube.', 'Doctors once used it to take temperatures.', 'It has been replaced by digital versions.', 'It measures temperature.'] },
    { n: 'Lightning rod', alt: ['lightning conductor'], f: f(1752, 'Benjamin Franklin', US), d: 2,
      b: 'Benjamin Franklin invented the lightning rod around 1752 to protect buildings from lightning strikes.',
      c: ['Its inventor is famous for a kite experiment.', 'Its inventor is on the US $100 note.', 'It is a metal rod on top of a building.', 'It carries electricity safely into the ground.', 'It protects buildings during storms.'] },
    { n: 'Watt steam engine', ln: 'the Watt steam engine', alt: ['steam engine'], f: f(1769, 'James Watt', UK), d: 2,
      b: 'James Watt\'s 1769 improvement to the steam engine made it far more efficient and powered the Industrial Revolution.',
      c: ['Its inventor added a separate condenser.', 'A unit of power is named after its inventor.', 'It powered factories and mills.', 'It drove the Industrial Revolution.', 'It runs on boiling water.'] },
    { n: 'Hot air balloon', f: f(1783, 'Montgolfier brothers', FR), d: 1,
      b: 'The Montgolfier brothers flew the first hot air balloon with people aboard in Paris in 1783.',
      c: ['Its first passengers were a sheep, a duck and a rooster.', 'Its inventors were brothers who made paper.', 'The first human flight was over Paris.', 'It rises because hot air is lighter than cool air.', 'It carries people in a basket.'] },
    { n: 'Smallpox vaccine', ln: 'the smallpox vaccine', alt: ['vaccine', 'vaccination'], f: f(1796, 'Edward Jenner', UK), d: 2,
      b: 'In 1796 Edward Jenner showed that cowpox could protect people from smallpox. It was the world\'s first vaccine.',
      c: ['It was first tested on a boy named James Phipps.', 'It used material from cowpox blisters.', 'Its name comes from the Latin for cow.', 'It led to smallpox being wiped out in 1980.', 'It was the first vaccine.'] },
    { n: 'Electric battery', alt: ['battery', 'voltaic pile'], f: f(1800, 'Alessandro Volta', IT), d: 1,
      b: 'Alessandro Volta stacked metal discs and salty cardboard to make the first battery in 1800.',
      c: ['The first one was a pile of zinc and copper discs.', 'A unit of electricity is named after its inventor.', 'It stores chemical energy.', 'Phones and torches use it.', 'It gives power to things with no plug.'] },
    { n: 'Steam locomotive', f: f(1804, 'Richard Trevithick', UK), d: 2,
      b: 'Richard Trevithick built the first working steam locomotive in Wales in 1804.',
      c: ['Its first run was at an ironworks in Wales.', 'George Stephenson\'s "Rocket" made it famous.', 'It burns coal to make steam.', 'It pulls trains.', 'It puffs smoke as it chugs along rails.'] },
    { n: 'Stethoscope', f: f(1816, 'René Laennec', FR), d: 2,
      b: 'René Laennec invented the stethoscope in 1816, starting with a rolled-up tube of paper.',
      c: ['The first one was a rolled-up tube of paper.', 'Its inventor was a French doctor.', 'It lets you hear the lungs and heart.', 'Doctors wear it around their neck.', 'Doctors listen to your heartbeat with it.'] },
    { n: 'Draisine', ln: 'the draisine', alt: ['running machine', 'dandy horse'], f: f(1817, 'Karl Drais', DE), d: 3,
      b: 'Karl Drais\'s 1817 "running machine" had two wheels but no pedals. It was the ancestor of the bicycle.',
      c: ['Riders pushed it along with their feet.', 'It had no pedals.', 'It was invented in Mannheim.', 'It was also called a dandy horse.', 'It was the ancestor of the bicycle.'] },
    { n: 'Daguerreotype', ln: 'the daguerreotype', f: f(1839, 'Louis Daguerre', FR), d: 3,
      b: 'The daguerreotype, announced in 1839, was the first popular form of photography.',
      c: ['Its pictures were on silver-coated copper plates.', 'Sitters had to stay still for a long time.', 'It was announced to the world in 1839.', 'It was an early kind of photograph.', 'It is named after its French inventor.'] },
    { n: 'Safety pin', f: f(1849, 'Walter Hunt', US), d: 2,
      b: 'Walter Hunt invented the safety pin in 1849 by twisting a piece of wire, then sold the rights for $400.',
      c: ['Its inventor sold the rights for $400.', 'It was made from a single twisted wire.', 'It has a clasp that covers the point.', 'It holds nappies and clothes together.', 'It is a pin that will not stab you.'] },
    { n: 'Elevator safety brake', alt: ['safety elevator', 'safety lift'], f: f(1852, 'Elisha Otis', US), d: 3,
      b: 'Elisha Otis invented a safety brake that stops a lift from falling if the cable breaks. It made skyscrapers possible.',
      c: ['Its inventor showed it off by cutting the rope while standing on the platform.', 'A big lift company still has its inventor\'s name.', 'It made skyscrapers practical.', 'It stops a lift falling if the cable snaps.', 'It keeps lifts safe.'] },
    { n: 'Dynamite', ln: 'dynamite', f: f(1867, 'Alfred Nobel', SE), d: 2,
      b: 'Alfred Nobel invented dynamite in 1867. He later used his fortune to create the Nobel Prizes.',
      c: ['Its inventor\'s brother died in an explosion.', 'It made nitroglycerine safer to handle.', 'Its inventor\'s fortune funds famous prizes.', 'It is used in mining and demolition.', 'It is an explosive in sticks.'] },
    { n: 'Typewriter', alt: ['QWERTY typewriter'], f: f(1868, 'Christopher Latham Sholes', US), d: 2,
      b: 'Christopher Latham Sholes patented the first practical typewriter in 1868. Its QWERTY layout is still used today.',
      c: ['It gave us the QWERTY layout.', 'Mark Twain was an early user.', 'Its keys hit an inked ribbon.', 'It makes a clacking sound.', 'It types letters onto paper.'] },
    { n: 'Telephone', f: f(1876, 'Alexander Graham Bell', US), d: 1,
      b: 'Alexander Graham Bell patented the telephone in 1876. His first call was to his assistant, Mr Watson.',
      c: ['Its first words were "Mr Watson, come here".', 'Its inventor was born in Scotland.', 'Its patent was granted in 1876.', 'It sends voices along wires.', 'You make calls on it.'] },
    { n: 'Phonograph', f: f(1877, 'Thomas Edison', US), d: 2,
      b: 'Thomas Edison invented the phonograph in 1877, the first machine that could record and play back sound.',
      c: ['The first words it recorded were "Mary had a little lamb".', 'It recorded on tinfoil wrapped round a cylinder.', 'Its inventor is called the "Wizard of Menlo Park".', 'It led to the record player.', 'It records and plays back sound.'] },
    { n: 'Incandescent light bulb', alt: ['light bulb', 'lightbulb'], f: f(1879, 'Thomas Edison', US), d: 1,
      b: 'In 1879 Thomas Edison made a long-lasting light bulb with a carbon filament. Joseph Swan made a similar bulb in England.',
      c: ['Joseph Swan made one in England at the same time.', 'Its early filament was carbonised bamboo or thread.', 'It wastes most of its energy as heat.', 'Cartoons show one above a head for a bright idea.', 'It lights up a room.'] },
    { n: 'Benz Patent-Motorwagen', ln: 'the Benz Patent-Motorwagen', alt: ['motor car', 'car', 'automobile'], f: f(1885, 'Karl Benz', DE), d: 2,
      b: 'Karl Benz built the first true petrol-powered car in 1885. His wife Bertha took it on the first long road trip.',
      c: ['It had three wheels.', 'Bertha Benz drove it 106 km to show it worked.', 'It was patented in 1886.', 'It had a petrol engine.', 'It is called the first car.'] },
    { n: 'Electric drill', f: f(1889, 'Arthur James Arnot', AU), d: 3,
      b: 'Australian electrical engineer Arthur James Arnot patented the electric drill in Melbourne in 1889.',
      c: ['It was first designed to drill rock and coal.', 'Its inventor worked in Melbourne.', 'Its patent was granted in 1889.', 'It spins a bit to make holes.', 'It is a power tool for making holes.'] },
    { n: 'Diesel engine', f: f(1893, 'Rudolf Diesel', DE), d: 2,
      b: 'Rudolf Diesel developed an engine in the 1890s that ignites fuel by squeezing air until it is hot.',
      c: ['It has no spark plugs.', 'It squeezes air until it is hot enough to ignite fuel.', 'Its inventor vanished from a ship in 1913.', 'Trucks and ships use it.', 'It is named after its German inventor.'] },
    { n: 'Cinématographe', ln: 'the Cinématographe', alt: ['cinematograph', 'cinema'], f: f(1895, 'Lumière brothers', FR), d: 3,
      b: 'The Lumière brothers\' camera and projector showed the first public films to a paying audience in Paris in 1895.',
      c: ['An early film showed a train arriving at a station.', 'It was camera, printer and projector in one.', 'Its first paid show was in Paris in 1895.', 'It was made by two French brothers.', 'It showed moving pictures.'] },
    { n: 'Radio', ln: 'radio', alt: ['wireless telegraphy'], f: f(1895, 'Guglielmo Marconi', IT), d: 1,
      b: 'Guglielmo Marconi sent radio signals in 1895 and across the Atlantic in 1901.',
      c: ['Its inventor shared the 1909 Nobel Prize in Physics.', 'It sent a signal across the Atlantic in 1901.', 'It uses invisible waves.', 'You can listen to music and news on it.', 'It plays sound from far away without wires.'] },
    { n: 'Air conditioning', ln: 'air conditioning', f: f(1902, 'Willis Carrier', US), d: 2,
      b: 'Willis Carrier invented modern air conditioning in 1902 to control humidity at a printing plant.',
      c: ['It was first built for a printing company.', 'Its first job was to control humidity.', 'It made hot cities more liveable.', 'It cools rooms.', 'It blows cold air on hot days.'] },
    { n: 'Airplane', alt: ['aeroplane', 'Wright Flyer', 'plane'], f: f(1903, 'Wright brothers', US), d: 1,
      b: 'The Wright brothers made the first powered, controlled aeroplane flight at Kitty Hawk in 1903.',
      c: ['The first flight lasted 12 seconds.', 'Its inventors ran a bicycle shop.', 'The first flight was at Kitty Hawk, North Carolina.', 'Orville and Wilbur made it.', 'It flies people through the sky.'] },
    { n: 'Zipper', alt: ['zip', 'zip fastener'], f: f(1913, 'Gideon Sundback', US), d: 1,
      b: 'Gideon Sundback, a Swedish-born engineer in the USA, designed the modern zip in 1913.',
      c: ['Its inventor was born in Sweden.', 'It was first called the "hookless fastener".', 'It is used on jeans and jackets.', 'Its teeth lock together.', 'You pull it up and down to close a jacket.'] },
    { n: 'Crossword', ln: 'the crossword', alt: ['crossword puzzle'], f: f(1913, 'Arthur Wynne', US), d: 2,
      b: 'Arthur Wynne published the first crossword puzzle in a New York newspaper in 1913.',
      c: ['Its first version was diamond-shaped.', 'Its inventor was born in Liverpool.', 'It first appeared in the New York World.', 'Newspapers print one every day.', 'It is a word puzzle with clues across and down.'] },
    { n: 'Television', ln: 'television', alt: ['TV'], f: f(1926, 'John Logie Baird', UK), d: 1,
      b: 'John Logie Baird gave the first public demonstration of television in London in 1926.',
      c: ['Its first public demonstration was in a London attic room.', 'Its inventor was Scottish.', 'Early versions used a spinning disc.', 'You watch shows on it.', 'It is often called the telly.'] },
    { n: 'Jet engine', f: f(1930, 'Frank Whittle', UK), d: 2,
      b: 'Frank Whittle patented the jet engine in 1930. Hans von Ohain in Germany built one separately.',
      c: ['A German engineer, Hans von Ohain, developed one separately.', 'Its inventor was an RAF officer.', 'It was patented in 1930.', 'It sucks in air and blasts it out the back.', 'It powers big passenger planes.'] },
    { n: 'Nylon', ln: 'nylon', f: f(1935, 'Wallace Carothers', US), d: 2,
      b: 'Wallace Carothers made nylon at DuPont in 1935. It was first used for toothbrush bristles and stockings.',
      c: ['It was first used in toothbrush bristles.', 'Stockings made of it caused shopping riots.', 'It was made at the DuPont company.', 'It is a strong plastic fibre.', 'Its name has five letters.'] },
    { n: 'Ballpoint pen', alt: ['biro'], f: f(1938, 'László Bíró', HU), d: 1,
      b: 'Hungarian journalist László Bíró patented the ballpoint pen in 1938. In many countries it is still called a biro.',
      c: ['Its inventor was a Hungarian journalist.', 'It was inspired by quick-drying newspaper ink.', 'A tiny rolling ball spreads the ink.', 'In Britain it is often called by its inventor\'s name.', 'You write with it.'] },
    { n: 'Helicopter', alt: ['Sikorsky VS-300'], f: f(1939, 'Igor Sikorsky', US), d: 1,
      b: 'Igor Sikorsky flew the first practical single-rotor helicopter, the VS-300, in 1939.',
      c: ['Leonardo da Vinci drew an "aerial screw" like it.', 'Its inventor was born in Kyiv.', 'It has a small rotor on its tail.', 'It can hover and fly backwards.', 'It flies with spinning blades on top.'] },
    { n: 'Microwave oven', alt: ['microwave'], f: f(1945, 'Percy Spencer', US), d: 1,
      b: 'Percy Spencer noticed a chocolate bar melting in his pocket near radar equipment in 1945 and invented the microwave oven.',
      c: ['A melting chocolate bar inspired it.', 'Its inventor worked on radar.', 'The first ones were taller than a person.', 'It heats food in minutes.', 'It reheats leftovers with invisible waves.'] },
    { n: 'Hills Hoist', ln: 'the Hills Hoist', alt: ['rotary clothesline'], f: f(1945, 'Lance Hill', AU), d: 2,
      b: 'Lance Hill of Adelaide started making his winding rotary clothesline in 1945. It became an Australian backyard icon.',
      c: ['It appeared in the Sydney 2000 Olympics opening ceremony.', 'You wind it up and down with a handle.', 'It was made in Adelaide.', 'It is an Australian backyard icon.', 'It is a spinning clothesline.'] },
    { n: 'Transistor', f: f(1947, 'Bardeen, Brattain and Shockley', US), d: 3,
      b: 'The transistor was invented at Bell Labs in 1947. Billions now fit on a single computer chip.',
      c: ['It was invented at Bell Labs.', 'Its three inventors won the 1956 Nobel Prize.', 'It replaced bulky vacuum tubes.', 'Billions fit on one chip.', 'It switches and boosts electric signals.'] },
    { n: 'Velcro', ln: 'Velcro', alt: ['hook-and-loop fastener'], f: f(1955, 'George de Mestral', CH), d: 1,
      b: 'Swiss engineer George de Mestral invented Velcro after looking at burrs stuck to his dog\'s fur.',
      c: ['Burrs stuck to a dog\'s fur inspired it.', 'Its name joins French words for velvet and hook.', 'Astronauts use it to stop things floating away.', 'One side has hooks and the other loops.', 'It rips apart with a tearing sound.'] },
    { n: 'Flight recorder', alt: ['black box'], f: f(1958, 'David Warren', AU), d: 2,
      b: 'Australian scientist David Warren built the first flight data and voice recorder in 1958. It helps explain plane crashes.',
      c: ['Its Australian inventor\'s father died in a plane crash.', 'It is painted bright orange.', 'It records cockpit voices and flight data.', 'Investigators search for it after a crash.', 'It is nicknamed the "black box".'] },
    { n: 'Lego brick', ln: 'the Lego brick', alt: ['Lego'], f: f(1958, 'Godtfred Kirk Christiansen', DK), d: 1,
      b: 'The modern Lego brick, with tubes inside for a firm grip, was patented in Denmark in 1958.',
      c: ['Its name comes from Danish words meaning "play well".', 'The modern brick was patented in 1958.', 'Bricks from 1958 still fit bricks made today.', 'It is a plastic building toy.', 'It hurts to step on one.'] },
    { n: 'Three-point seat belt', alt: ['seat belt', 'seatbelt'], f: f(1959, 'Nils Bohlin', SE), d: 2,
      b: 'Nils Bohlin designed the three-point seat belt for Volvo in 1959. Volvo let other carmakers use it for free.',
      c: ['Volvo let other car makers use it free.', 'It is thought to have saved over a million lives.', 'It crosses the lap and the chest.', 'It is the law to wear one.', 'You buckle it in a car.'] },
    { n: 'Laser', f: f(1960, 'Theodore Maiman', US), d: 2,
      b: 'Theodore Maiman built the first working laser in 1960 using a ruby crystal.',
      c: ['The first one used a ruby crystal.', 'Its name is short for "light amplification by stimulated emission of radiation".', 'It reads barcodes at checkouts.', 'It makes a very narrow beam.', 'It is a beam of focused light.'] },
    { n: 'Kevlar', ln: 'Kevlar', f: f(1965, 'Stephanie Kwolek', US), d: 3,
      b: 'Chemist Stephanie Kwolek invented Kevlar in 1965. It is five times stronger than steel for its weight.',
      c: ['It is five times stronger than steel by weight.', 'It was invented by a woman chemist at DuPont.', 'It is used in racing tyres.', 'It is used in bulletproof vests.', 'Its name starts with a K.'] },
    { n: 'Mobile phone', alt: ['cell phone', 'cellphone'], f: f(1973, 'Martin Cooper', US), d: 1,
      b: 'Martin Cooper of Motorola made the first handheld mobile phone call in New York in 1973.',
      c: ['Its first call was made to a rival company.', 'The first one weighed about 1 kg.', 'The first call was made in New York in 1973.', 'It was made by Motorola.', 'You carry it in your pocket.'] },
    { n: 'Rubik\'s Cube', ln: 'the Rubik\'s Cube', alt: ['Rubiks cube', 'magic cube'], f: f(1974, 'Ernő Rubik', HU), d: 1,
      b: 'Hungarian professor Ernő Rubik invented his famous puzzle cube in 1974.',
      c: ['It has over 43 quintillion possible positions.', 'Its inventor was a Hungarian architecture professor.', 'Speed solvers finish it in a few seconds.', 'Each face has nine coloured squares.', 'It is a twisting puzzle cube.'] },
    { n: 'Cochlear implant', alt: ['bionic ear'], f: f(1978, 'Graeme Clark', AU), d: 3,
      b: 'Australian surgeon Graeme Clark implanted his multi-channel "bionic ear" in 1978. It helps deaf people hear.',
      c: ['Its inventor\'s father was deaf.', 'It was first implanted in Melbourne in 1978.', 'It sends electrical signals to the hearing nerve.', 'It is called the bionic ear.', 'It helps deaf people hear.'] },
    { n: 'Post-it note', ln: 'the Post-it note', alt: ['sticky note', 'Post-it'], f: f(1980, 'Spencer Silver and Art Fry', US), d: 1,
      b: 'Post-it notes went on sale in 1980. They use a weak glue that 3M scientist Spencer Silver made by accident.',
      c: ['Its glue was a failed attempt at a strong adhesive.', 'Art Fry wanted bookmarks that would not fall out of his hymn book.', 'The classic colour is canary yellow.', 'It was made by 3M.', 'It is a small sticky note.'] },
    { n: 'Polymer banknote', alt: ['plastic banknote'], f: f(1988, 'Reserve Bank of Australia and CSIRO', AU), d: 3,
      b: 'Australia issued the world\'s first polymer banknote in 1988. It lasts longer and is hard to fake.',
      c: ['Its first design celebrated a bicentenary.', 'It was developed with CSIRO.', 'It has a clear window that is hard to forge.', 'It survives a trip through the washing machine.', 'It is money made of plastic.'] },
    { n: 'World Wide Web', ln: 'the World Wide Web', alt: ['the web', 'WWW'], f: f(1989, 'Tim Berners-Lee', CH), d: 1,
      b: 'Tim Berners-Lee invented the World Wide Web at CERN in Switzerland in 1989.',
      c: ['Its inventor was knighted in 2004.', 'It was invented at CERN.', 'Its pages are linked by hyperlinks.', 'Its addresses often start with "www".', 'You browse it on the internet.'] },
    { n: 'iPhone', ln: 'the iPhone', f: f(2007, 'Apple', US), d: 1,
      b: 'Apple\'s iPhone, launched by Steve Jobs in 2007, made touchscreen smartphones mainstream.',
      c: ['Steve Jobs called it three devices in one.', 'It launched in 2007.', 'It brought the App Store a year later.', 'It has a touchscreen.', 'It is a smartphone made by Apple.'] },
  ],
  fakes: ['Steam-powered umbrella (1822)', 'Electric spoon (1911)', 'Pneumatic hat (1874)', 'Clockwork toothbrush (1797)'],
  questions: [
    { kind: 'mc', prompt: 'Who is credited with inventing the telephone in 1876?', answer: 'Alexander Graham Bell', wrong: ['Thomas Edison', 'Guglielmo Marconi', 'Nikola Tesla'], explain: 'Bell\'s patent was granted in March 1876.', difficulty: 1 },
    { kind: 'mc', prompt: 'Who made the first powered aeroplane flight in 1903?', answer: 'The Wright brothers', wrong: ['The Montgolfier brothers', 'The Lumière brothers', 'Charles Lindbergh'], explain: 'Orville flew 12 seconds at Kitty Hawk.', difficulty: 1 },
    { kind: 'mc', prompt: 'Who invented the World Wide Web?', answer: 'Tim Berners-Lee', wrong: ['Bill Gates', 'Steve Jobs', 'Alan Turing'], explain: 'He proposed it at CERN in 1989.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which inventor\'s fortune created the Nobel Prizes?', answer: 'Alfred Nobel', wrong: ['Thomas Edison', 'James Watt', 'Karl Benz'], explain: 'He invented dynamite.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which Australian invention records data to help investigate plane crashes?', answer: 'The black box flight recorder', wrong: ['The jet engine', 'Radar', 'The seat belt'], explain: 'David Warren built the first in 1958.', difficulty: 2 },
    { kind: 'mc', prompt: 'What inspired the invention of Velcro?', answer: 'Burrs stuck to a dog\'s fur', wrong: ['A bird\'s feather', 'A spider\'s web', 'Gecko feet'], explain: 'George de Mestral studied the burrs under a microscope.', difficulty: 2 },
    { kind: 'mc', prompt: 'What melted in Percy Spencer\'s pocket and led to the microwave oven?', answer: 'A chocolate bar', wrong: ['An ice cube', 'A candle', 'A crayon'], explain: 'He was working near a radar magnetron.', difficulty: 2 },
    { kind: 'order', prompt: 'Put these inventions in order, oldest first.', answer: ['Printing press', 'Telephone', 'Television', 'World Wide Web'], orderLabel: 'Oldest first', explain: 'About 1440, 1876, 1926 and 1989.', difficulty: 2 },
    { kind: 'order', prompt: 'Put these inventions in order, oldest first.', answer: ['Paper', 'Telescope', 'Light bulb', 'Mobile phone'], orderLabel: 'Oldest first', explain: 'About 105, 1608, 1879 and 1973.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which unit of power is named after the inventor of an improved steam engine?', answer: 'Watt', wrong: ['Volt', 'Joule', 'Newton'], explain: 'James Watt improved the steam engine in 1769.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which inventor is famous for flying a kite in a thunderstorm?', answer: 'Benjamin Franklin', wrong: ['Thomas Edison', 'Isaac Newton', 'Galileo Galilei'], explain: 'He went on to invent the lightning rod.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which country did the Lego brick come from?', answer: 'Denmark', wrong: ['Sweden', 'Germany', 'Japan'], explain: 'Lego comes from the Danish "leg godt", meaning play well.', difficulty: 1 },
    { kind: 'mc', prompt: 'Who invented the ballpoint pen in 1938?', answer: 'László Bíró', wrong: ['Thomas Edison', 'Ernő Rubik', 'Karl Benz'], explain: 'Many people still call a ballpoint a biro.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which country issued the world\'s first plastic (polymer) banknote?', answer: 'Australia', wrong: ['Canada', 'United Kingdom', 'Japan'], explain: 'A commemorative $10 note was issued in 1988.', difficulty: 2 },
  ],
};
