import { NOT_ID, INAT, WD } from './_common.mjs';

const H = 'Harmless', M = 'Mild sting', P = 'Painful sting', X = 'Potentially deadly';
const f = (danger, kind) => ({ danger, kind });

export default {
  id: 'jellyfish', title: 'Jellyfish & stingers', theme: 'animals', icon: '🪼', kids: true,
  noun: 'sea stinger', fakePrompt: 'Which of these sea stingers is made up?',
  notice: NOT_ID + ' If stung, get first aid and follow local advice.',
  leakExempt: ['jellyfish', 'jelly'],
  wikiD1: true, autoTaxo: ['class', 'family'],
  factsMeta: {
    danger: { type: 'cat', label: 'Sting', values: [H, M, P, X], clue: v => ({ [H]: 'It is harmless to people.', [M]: 'Its sting is mild.', [P]: 'Its sting is very painful.', [X]: 'Its venom can kill a person.' }[v]) },
    kind: { type: 'cat', label: 'Kind of animal', clue: v => `It is a kind of ${v.toLowerCase()}.`, noClue: true },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "What is this sea creature?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"danger": {"ask": "How bad is a sting from the {lname}?", "askReverse": "Which of these has a sting rated \"{lvalue}\"?", "stmt": "The {lname}'s sting is rated \"{lvalue}\"."}, "kind": {"ask": "What kind of animal is the {lname}?", "askReverse": "Which of these is {aValue}?", "stmt": "The {lname} is a kind of {lvalue}."}},
  sources: [INAT, WD],
  items: [
    { n: 'Box jellyfish', alt: ['sea wasp', 'Australian box jellyfish'], sci: 'Chironex fleckeri', g: 'box jellyfish', f: f(X, 'Box jellyfish'), d: 1, look: ['Moon jellyfish', 'Irukandji jellyfish'],
      b: 'A see-through jellyfish of northern Australia with a cube-shaped bell. Its sting is one of the most deadly in the world.',
      c: ['It has 24 eyes, some with lenses.', 'Vinegar is poured on its stings to stop more stinging cells firing.', 'It can have up to 60 tentacles up to 3 metres long.', 'It is a big danger on northern Australian beaches in summer.', 'Its bell is shaped like a cube.'] },
    { n: 'Irukandji jellyfish', alt: ['Irukandji'], sci: 'Carukia barnesi', g: 'box jellyfish', f: f(X, 'Box jellyfish'), d: 2, look: ['Box jellyfish'],
      b: 'A tiny box jellyfish, about the size of a fingernail. Its sting can cause terrible pain, sweating and a dangerous rise in blood pressure.',
      c: ['Its species name honours Jack Barnes, who let it sting him to prove it was the cause.', 'Its bell is only about 1 cm across.', 'Its sting causes a syndrome of back pain, vomiting and sweating.', 'It is named after an Aboriginal people from near Cairns.', 'It is a tiny but very dangerous jellyfish.'] },
    { n: 'Portuguese man o\' war', alt: ['man o\' war', 'Portuguese man-of-war'], sci: 'Physalia physalis', g: 'siphonophore', f: f(P, 'Siphonophore'), d: 1, look: ['Bluebottle', 'By-the-wind sailor'],
      b: 'It looks like a jellyfish, but it is really a floating colony of many tiny animals working together. Its long blue tentacles sting.',
      c: ['It is a colony of many small animals, not one animal.', 'Its tentacles can be over 10 metres long.', 'It floats on a gas-filled sail.', 'It is named after an old sailing warship.', 'It comes from a country next to Spain.'] },
    { n: 'Bluebottle', alt: ['Pacific man o\' war'], sci: 'Physalia utriculus', g: 'siphonophore', f: f(P, 'Siphonophore'), d: 1, look: ['Portuguese man o\' war', 'Blue button'],
      b: 'A small blue floating stinger that washes up on Australian beaches in thousands after onshore winds.',
      c: ['Its float acts as a sail.', 'It usually has one main long fishing tentacle.', 'Hot water helps ease its sting.', 'Thousands wash up on Australian beaches after north-east winds.', 'It is named after a blue glass container.'] },
    { n: 'Moon jellyfish', alt: ['moon jelly', 'common jellyfish'], sci: 'Aurelia aurita', g: 'true jellyfish', f: f(M, 'True jellyfish'), d: 1, look: ['Box jellyfish'],
      b: 'A common see-through jellyfish with four pale rings in its bell. Its sting is too weak for most people to feel.',
      c: ['It is often kept in aquariums.', 'It catches plankton on sticky mucus.', 'It has four horseshoe-shaped rings in its bell.', 'It is clear and saucer-shaped.', 'It is named after something in the night sky.'] },
    { n: 'Lion\'s mane jellyfish', ln: 'lion\'s mane jellyfish', alt: ['lion\'s mane'], sci: 'Cyanea capillata', g: 'true jellyfish', f: f(P, 'True jellyfish'), d: 2,
      b: 'The largest known jellyfish. Its mass of hundreds of tentacles can trail for many metres.',
      c: ['One washed up in 1870 had tentacles about 37 metres long.', 'It lives in cold northern seas.', 'It has hundreds of thin tentacles.', 'It is the largest known jellyfish.', 'Its tentacles look like the hairy neck of a big cat.'] },
    { n: 'Compass jellyfish', sci: 'Chrysaora hysoscella', g: 'true jellyfish', f: f(P, 'True jellyfish'), d: 2,
      b: 'A European jellyfish with brown V-shaped markings that look like the points of a compass.',
      c: ['It starts life as a male and later becomes female.', 'It is common around Britain in summer.', 'It has 24 tentacles.', 'Its bell has 16 brown V-shaped marks.', 'It is named after a tool for finding north.'] },
    { n: 'Barrel jellyfish', alt: ['dustbin-lid jellyfish'], sci: 'Rhizostoma pulmo', g: 'true jellyfish', f: f(M, 'True jellyfish'), d: 2,
      b: 'A huge, heavy European jellyfish with frilly arms instead of long tentacles. It can be as big as a person.',
      c: ['A diver filmed one as big as a person off Cornwall in 2019.', 'It has frilly arms instead of long tentacles.', 'Its bell has a purple rim.', 'Its sting is weak.', 'It is named after a wooden container for wine.'] },
    { n: 'Upside-down jellyfish', sci: 'Cassiopea', g: 'true jellyfish', f: f(M, 'True jellyfish'), d: 2,
      b: 'A jellyfish that lies on the sea floor with its arms pointing up, so algae living in it get sunlight.',
      c: ['Algae living inside it make food from sunlight.', 'It releases stinging mucus into the water.', 'It lives in shallow lagoons and mangroves.', 'It lies on the sea floor.', 'It rests the wrong way up.'] },
    { n: 'Immortal jellyfish', files: ['Turritopsis dohrnii (cropped).jpg', 'Turritopsis dohrnii.jpg'], sci: 'Turritopsis dohrnii', g: 'hydrozoan', f: f(H, 'Hydrozoan'), d: 2,
      b: 'A tiny jellyfish that can turn back into its baby form when stressed or old, again and again.',
      c: ['It is only about 4.5 mm across.', 'Its stomach shows bright red through its body.', 'It can turn back into a polyp.', 'It can restart its life cycle.', 'It is said it may never die of old age.'] },
    { n: 'Fried egg jellyfish', alt: ['Mediterranean jellyfish'], sci: 'Cotylorhiza tuberculata', g: 'true jellyfish', f: f(H, 'True jellyfish'), d: 2,
      b: 'A Mediterranean jellyfish with a raised yellow-orange dome in the middle of its pale bell.',
      c: ['It lives in the Mediterranean.', 'Small fish often shelter under it.', 'Its sting is too weak to hurt people.', 'It has a yellow dome in the middle.', 'It looks like a breakfast food.'] },
    { n: 'Mauve stinger', sci: 'Pelagia noctiluca', g: 'true jellyfish', f: f(P, 'True jellyfish'), d: 3,
      b: 'A pinkish-purple jellyfish that glows at night. Huge swarms close beaches in the Mediterranean.',
      c: ['Its scientific name means "night light".', 'It glows when disturbed.', 'Swarms of it close Mediterranean beaches.', 'Its whole body is covered in stinging warts.', 'It is a pinkish-purple colour.'] },
    { n: 'Pacific sea nettle', alt: ['sea nettle'], sci: 'Chrysaora fuscescens', g: 'true jellyfish', f: f(P, 'True jellyfish'), d: 2,
      b: 'A golden-brown jellyfish with long maroon arms, common off the west coast of North America and in big aquariums.',
      c: ['It is a favourite in big public aquariums.', 'It lives off California and Oregon.', 'It has long, frilly maroon arms.', 'Its bell is golden-brown.', 'It is named after a stinging plant.'] },
    { n: 'Blue blubber jellyfish', alt: ['blue blubber'], sci: 'Catostylus mosaicus', g: 'true jellyfish', f: f(M, 'True jellyfish'), d: 2,
      b: 'A round, rubbery jellyfish of eastern Australia that can be blue, brown or white. Its sting is mild.',
      c: ['It has no long tentacles, only eight frilly arms.', 'It lives in estuaries of eastern Australia.', 'It can be blue, brown or cream.', 'Its sting is mild.', 'Its name sounds like whale fat.'] },
    { n: 'By-the-wind sailor', alt: ['velella'], sci: 'Velella velella', g: 'hydrozoan', f: f(H, 'Hydrozoan'), d: 3, look: ['Portuguese man o\' war', 'Blue button'],
      b: 'A small blue floating animal with a stiff sail on top. Millions sometimes wash up on beaches at once.',
      c: ['Some sail to the left of the wind and some to the right.', 'It is a floating colony of tiny animals.', 'Millions can wash up on one beach.', 'It is bright blue with a clear stiff sail.', 'It is pushed around by moving air.'] },
    { n: 'Blue button', sci: 'Porpita porpita', g: 'hydrozoan', f: f(M, 'Hydrozoan'), d: 3, look: ['By-the-wind sailor', 'Bluebottle'],
      b: 'A small, round, floating animal with a golden disc and blue tentacles. It is not a true jellyfish.',
      c: ['It is a colony of tiny animals.', 'It floats at the sea surface.', 'Its centre is a golden-brown disc.', 'It has a ring of blue tentacles.', 'It is round and small, like a fastener on a shirt.'] },
    { n: 'Crystal jelly', sci: 'Aequorea victoria', g: 'hydrozoan', f: f(H, 'Hydrozoan'), d: 3,
      b: 'A clear jellyfish of the North American Pacific coast. A glowing protein found in it won a Nobel Prize and changed biology.',
      c: ['A protein from it won the 2008 Nobel Prize in Chemistry.', 'Its green fluorescent protein is used to make cells glow in labs.', 'It glows green around its edge.', 'It lives off the west coast of North America.', 'It is almost totally see-through, like glass.'] },
    { n: 'Golden jellyfish', sci: 'Mastigias papua', g: 'true jellyfish', f: f(H, 'True jellyfish'), d: 3,
      b: 'Millions of these jellyfish live in Jellyfish Lake in Palau, following the sun across the lake each day.',
      c: ['Millions live in a marine lake in Palau.', 'They swim across the lake each day following the sun.', 'Algae inside them make food from sunlight.', 'Tourists snorkel among them.', 'They are a yellow colour.'] },
    { n: 'Cannonball jellyfish', sci: 'Stomolophus meleagris', g: 'true jellyfish', f: f(M, 'True jellyfish'), d: 3,
      b: 'A firm, round jellyfish common off the south-eastern USA. It is caught and dried for food in Asia.',
      c: ['It is exported to Asia as food.', 'It has no long tentacles.', 'Its bell is round and hard.', 'It is common off Georgia and Florida.', 'It is named after an old iron ball fired from guns.'] },
    { n: 'Stonefish', alt: ['reef stonefish'], sci: 'Synanceia verrucosa', g: 'fish', f: f(X, 'Fish'), d: 1, look: ['Lionfish'],
      b: 'The most venomous fish in the world. It looks just like a lumpy rock, and its spines sting people who step on it.',
      c: ['It has 13 venomous spines on its back.', 'It can survive out of water for hours.', 'People are stung when they step on it.', 'It is the most venomous fish in the world.', 'It looks just like a rock.'] },
    { n: 'Red lionfish', alt: ['lionfish'], sci: 'Pterois volitans', g: 'fish', f: f(P, 'Fish'), d: 1, look: ['Stonefish'],
      b: 'A striped fish with long venomous spines. It has invaded the Caribbean, where it eats many native fish.',
      c: ['It is invading the Caribbean and Atlantic.', 'It comes from the Indian and Pacific Oceans.', 'Its fins spread out like feathers.', 'It is striped red and white.', 'It is named after a big cat with a mane.'] },
    { n: 'Blue-ringed octopus', sci: 'Hapalochlaena lunulata', g: 'mollusc', f: f(X, 'Octopus'), d: 1, look: ['Cone snail'],
      b: 'A tiny octopus that flashes bright blue rings when alarmed. Its bite contains a venom with no antidote.',
      c: ['Its venom is the same toxin found in pufferfish.', 'There is no antivenom for its bite.', 'It is only about the size of a golf ball.', 'It lives in rock pools in Australia and Asia.', 'It flashes bright blue rings when alarmed.'] },
    { n: 'Geography cone', alt: ['cone snail'], sci: 'Conus geographus', g: 'mollusc', f: f(X, 'Sea snail'), d: 2, look: ['Blue-ringed octopus'],
      b: 'A sea snail with a beautiful patterned shell that fires a venomous harpoon. It has killed people.',
      c: ['It has been nicknamed the "cigarette snail".', 'It fires a harpoon-like tooth.', 'Cone snail venoms have inspired new painkillers.', 'Collectors are stung picking up its shell.', 'It is named after the study of maps.'] },
    { n: 'Crown-of-thorns starfish', sci: 'Acanthaster planci', g: 'echinoderm', f: f(P, 'Starfish'), d: 2,
      b: 'A big starfish covered in venomous spines. Outbreaks of it eat large areas of coral on the Great Barrier Reef.',
      c: ['It can have up to 21 arms.', 'It eats coral by pushing its stomach out over it.', 'Outbreaks damage the Great Barrier Reef.', 'It is covered in sharp venomous spines.', 'It is named after something worn by Jesus at the crucifixion.'] },
    { n: 'Fire coral', sci: 'Millepora', g: 'hydrozoan', f: f(P, 'Hydrozoan'), d: 2,
      b: 'It looks like coral, but it is related to jellyfish. Touching it gives a burning sting.',
      c: ['It is related to jellyfish, not true corals.', 'Its surface is covered in tiny pores.', 'It is yellow-brown with white tips.', 'Divers get stung when they brush against it.', 'Its sting feels like a burn.'] },
    { n: 'Bluespotted ribbontail ray', sci: 'Taeniura lymma', g: 'ray', f: f(P, 'Fish'), d: 2,
      b: 'A small, colourful stingray of Indo-Pacific reefs with bright blue spots and venomous tail spines.',
      c: ['It has one or two venomous spines on its tail.', 'It lives on Indo-Pacific coral reefs.', 'It is a kind of stingray.', 'Its body is covered in bright blue spots.', 'Its tail has blue stripes on the sides.'] },
    { n: 'Warty comb jelly', alt: ['sea walnut'], sci: 'Mnemiopsis leidyi', g: 'comb jelly', f: f(H, 'Comb jelly'), d: 3, look: ['Moon jellyfish'],
      b: 'A see-through comb jelly with rows of shimmering hairs. It is not a jellyfish and cannot sting.',
      c: ['It invaded the Black Sea in the 1980s.', 'It has no stinging cells.', 'Rows of tiny hairs flash rainbow colours as it swims.', 'It is not a true jellyfish.', 'It is also called the sea walnut.'] },
  ],
  fakes: ['Glass crown jellyfish', 'Spotted thunder jelly', 'Northern ribbon stinger', 'Golden man o\' war', 'Silver box jelly', 'Coral lantern stinger'],
  questions: [
    { kind: 'tf', prompt: 'Jellyfish have no brain.', answer: true, explain: 'They have a simple net of nerves instead of a brain.', difficulty: 1 },
    { kind: 'tf', prompt: 'A jellyfish is a fish.', answer: false, explain: 'Jellyfish are cnidarians, related to corals and sea anemones.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which Australian jellyfish has a cube-shaped bell and a deadly sting?', answer: 'Box jellyfish', wrong: ['Moon jellyfish', 'Blue blubber jellyfish', 'Lion\'s mane jellyfish'], explain: 'Chironex fleckeri is among the most venomous animals known.', difficulty: 1 },
    { kind: 'mc', prompt: 'Lifeguards in northern Australia pour what on box jellyfish stings?', answer: 'Vinegar', wrong: ['Fresh water', 'Milk', 'Lemonade'], explain: 'Vinegar stops unfired stinging cells from firing. Always follow local first-aid advice.', difficulty: 2 },
    { kind: 'tf', prompt: 'The Portuguese man o\' war is a single animal.', answer: false, explain: 'It is a colony of specialised zooids working together.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the most venomous fish in the world?', answer: 'Stonefish', wrong: ['Lionfish', 'Great white shark', 'Piranha'], explain: 'Its back spines inject venom when stepped on.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which jellyfish can turn back into its young form?', answer: 'Immortal jellyfish', wrong: ['Moon jellyfish', 'Box jellyfish', 'Barrel jellyfish'], explain: 'Turritopsis dohrnii can revert from medusa to polyp.', difficulty: 2 },
    { kind: 'mc', prompt: 'What does a blue-ringed octopus do when it is alarmed?', answer: 'Flashes bright blue rings', wrong: ['Squirts red ink', 'Puffs up like a ball', 'Changes into a starfish shape'], explain: 'The rings warn predators of its deadly venom.', difficulty: 1 },
    { kind: 'mc', prompt: 'What kind of animal is a jellyfish most closely related to?', answer: 'Coral', wrong: ['Squid', 'Fish', 'Crab'], explain: 'Jellyfish, corals and sea anemones are all cnidarians with stinging cells.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which famous glowing protein came from a jellyfish and won a Nobel Prize?', answer: 'Green fluorescent protein', wrong: ['Insulin', 'Penicillin', 'Haemoglobin'], explain: 'GFP from the crystal jelly earned the 2008 Nobel Prize in Chemistry.', difficulty: 3 },
    { kind: 'tf', prompt: 'Jellyfish are mostly made of water.', answer: true, explain: 'They are about 95% water.', difficulty: 1 },
    { kind: 'mc', prompt: 'What should you do if you find a jellyfish on the beach?', answer: 'Leave it alone', wrong: ['Pick it up', 'Poke it with your foot', 'Take it home'], explain: 'Even washed-up jellyfish can still sting.', difficulty: 1 },
    { kind: 'tf', prompt: 'Some jellyfish can glow in the dark.', answer: true, explain: 'Many jellyfish make their own light.', difficulty: 1 },
    { kind: 'mc', prompt: 'What part of a jellyfish stings?', answer: 'Its tentacles', wrong: ['Its teeth', 'Its fins', 'Its shell'], explain: 'Tentacles are covered in tiny stinging cells.', difficulty: 1 },
  ],
};
