import { INAT, WD, COMMONS, STATUS_META, mass } from './_common.mjs';

const AF = 'Africa', AS = 'Asia', AU = 'Australia', EU = 'Europe', NA = 'North America', SA = 'South America', AM = 'the Americas', AR = 'the Arctic', EA = 'Europe and Asia', WW = 'many parts of the world';
const C = 'Carnivore', H = 'Herbivore', O = 'Omnivore', I = 'Insectivore';
const f = (massKg, region, diet) => ({ massKg, region, diet });

export default {
  id: 'mammals', title: 'Mammals', theme: 'animals', icon: '🦁', kids: true,
  leakExempt: [],
  autoTaxo: ['family', 'genus'], status: true, audio: true, wdCheck: { massKg: 'P2067' },
  ranges: { massKg: [0.005, 7000] },
  factsMeta: {
    massKg: mass(),
    region: { type: 'cat', label: 'Found in', clue: v => `It lives in ${v}.` },
    diet: { type: 'cat', label: 'Diet', values: [C, H, O, I], clue: v => ({ [C]: 'It eats meat.', [H]: 'It eats plants.', [O]: 'It eats both plants and animals.', [I]: 'It eats mostly insects.' }[v]) },
    status: STATUS_META,
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which animal is this?",
  tfImgPrompt: "This animal is {aName}.",
  tpl: {"massKg": {"askHigh": "Which of these animals is the heaviest?", "askLow": "Which of these animals is the lightest?", "minRatio": 2}, "region": {"ask": "Where does the {lname} live?", "askReverse": "Which of these animals lives in {value}?", "stmt": "The {lname} lives in {value}.", "exclusive": false}, "diet": {"ask": "What does the {lname} eat?", "askReverse": "Which of these animals is a {lvalue}?", "stmt": "The {lname} is a {lvalue}."}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD, COMMONS],
  items: [
    // ---- big cats ----
    { n: 'Lion', sci: 'Panthera leo', g: 'cat', f: f(190, AF, C), d: 1, look: ['Tiger', 'Cougar'],
      b: 'The only cat that lives in groups, called prides. Males have a big mane.',
      c: ['A small group lives in the Gir Forest in India.', 'Its roar can be heard 8 km away.', 'The females do most of the hunting.', 'It lives in groups called prides.', 'The male has a big shaggy mane.'] },
    { n: 'Tiger', sci: 'Panthera tigris', g: 'cat', f: f(200, AS, C), d: 1, look: ['Lion', 'Jaguar'],
      b: 'The biggest cat in the world. Its orange coat has black stripes, and no two tigers have the same stripes.',
      c: ['Unlike most cats, it likes to swim.', 'Its skin is striped as well as its fur.', 'The Siberian kind is the largest.', 'It is the largest cat in the world.', 'It is orange with black stripes.'] },
    { n: 'Leopard', sci: 'Panthera pardus', g: 'cat', f: f(55, AF, C), d: 1, look: ['Jaguar', 'Cheetah', 'Snow leopard'],
      b: 'A strong spotted cat that drags its prey up into trees to keep it safe from lions and hyenas.',
      c: ['Some are all black and are called black panthers.', 'It lives in Africa and Asia.', 'It drags its prey up into trees.', 'Its spots are rosettes, like flowers.', 'It is a spotted big cat that climbs trees.'] },
    { n: 'Jaguar', sci: 'Panthera onca', g: 'cat', f: f(80, SA, C), d: 1, look: ['Leopard', 'Cheetah'],
      b: 'The biggest cat in the Americas. It has the strongest bite of any big cat and kills by biting through skulls.',
      c: ['Its rosettes have spots inside them.', 'It can bite through turtle shells.', 'It loves water and catches caimans.', 'It is the biggest cat in the Americas.', 'A British car company is named after it.'] },
    { n: 'Cheetah', sci: 'Acinonyx jubatus', g: 'cat', f: f(50, AF, C), d: 1, look: ['Leopard', 'Jaguar'],
      b: 'The fastest land animal, reaching about 100 km/h in short bursts. It has black "tear lines" on its face.',
      c: ['It cannot roar, but it chirps and purrs.', 'Its claws do not fully pull in.', 'It has black "tear marks" down its face.', 'It has solid black spots.', 'It is the fastest land animal.'] },
    { n: 'Snow leopard', sci: 'Panthera uncia', g: 'cat', f: f(45, AS, C), d: 1, look: ['Leopard'],
      b: 'A pale, spotted big cat of the high mountains of Central Asia. It wraps its long, thick tail around itself for warmth.',
      c: ['It cannot roar.', 'It wraps its thick tail around itself like a scarf.', 'Its big furry paws work like snowshoes.', 'It lives in the Himalayas.', 'It is a pale grey spotted cat of the mountains.'] },
    { n: 'Cougar', alt: ['puma', 'mountain lion', 'panther'], sci: 'Puma concolor', g: 'cat', f: f(60, AM, C), d: 2, look: ['Lion'],
      b: 'A big, plain tawny cat found from Canada to the tip of South America. It has more names than almost any other animal.',
      c: ['It has more common names than almost any other mammal.', 'It is found from Canada to Patagonia.', 'It purrs instead of roaring.', 'It is tawny brown with no spots.', 'It is also called a mountain lion.'] },
    { n: 'Eurasian lynx', alt: ['lynx'], sci: 'Lynx lynx', g: 'cat', f: f(20, EA, C), d: 2,
      b: 'A wild cat with black ear tufts, a short tail and big furry paws. It hunts deer in northern forests.',
      c: ['It is the third-largest predator in Europe.', 'It hunts roe deer.', 'Its big furry paws help it walk on snow.', 'It has a short tail with a black tip.', 'It has long black tufts on its ears.'] },
    // ---- Africa ----
    { n: 'African bush elephant', alt: ['African elephant', 'elephant'], sci: 'Loxodonta africana', g: 'elephant', f: f(6000, AF, H), d: 1, look: ['Asian elephant'],
      b: 'The biggest land animal on Earth. Its huge ears help it keep cool.',
      c: ['It can recognise the voices of family members.', 'Its pregnancy lasts about 22 months.', 'Its ears are shaped a bit like Africa.', 'It uses its trunk to drink and smell.', 'It is the biggest land animal.'] },
    { n: 'Asian elephant', sci: 'Elephas maximus', g: 'elephant', f: f(4000, AS, H), d: 1, look: ['African bush elephant'],
      b: 'A smaller elephant than the African kind, with smaller ears. Many females have no tusks.',
      c: ['Many females have no tusks.', 'It has one "finger" on its trunk tip, not two.', 'It has been used to carry heavy loads for centuries.', 'Its ears are smaller and rounder than its African cousin\'s.', 'It is an elephant from India and South-East Asia.'] },
    { n: 'Giraffe', sci: 'Giraffa camelopardalis', g: 'giraffe', f: f(1000, AF, H), d: 1, look: ['Okapi'],
      b: 'The tallest animal in the world. Its long neck has only seven bones, the same as ours.',
      c: ['Its tongue is dark blue-black and about 50 cm long.', 'Its neck has seven bones, just like a human\'s.', 'It sleeps for only a short time each day.', 'It eats leaves from acacia trees.', 'It is the tallest animal in the world.'] },
    { n: 'Plains zebra', alt: ['zebra'], sci: 'Equus quagga', g: 'horse', f: f(300, AF, H), d: 1,
      b: 'A wild horse of Africa with black-and-white stripes. Every zebra\'s stripes are different.',
      c: ['Its stripes may help keep biting flies away.', 'No two have exactly the same pattern.', 'It migrates with wildebeest.', 'It is related to horses.', 'It has black and white stripes.'] },
    { n: 'Hippopotamus', alt: ['hippo'], sci: 'Hippopotamus amphibius', g: 'hippo', f: f(1500, AF, H), d: 1,
      b: 'A huge animal that spends its days in rivers. It is one of the most dangerous animals in Africa.',
      c: ['Its closest living relatives are whales.', 'Its skin makes a red oily liquid that works like sunscreen.', 'It cannot really swim; it walks on the river bed.', 'It is one of Africa\'s most dangerous animals.', 'Its name means "river horse".'] },
    { n: 'White rhinoceros', alt: ['white rhino', 'square-lipped rhinoceros'], sci: 'Ceratotherium simum', g: 'rhino', f: f(2300, AF, H), d: 1, look: ['Black rhinoceros'],
      b: 'The biggest rhino, with a wide, square mouth for grazing grass. It is not actually white.',
      c: ['The northern kind has only two females left.', 'Its horn is made of keratin, like fingernails.', 'It has a wide, square lip for eating grass.', 'It is grey, despite its name.', 'It is the largest rhino.'] },
    { n: 'Black rhinoceros', alt: ['black rhino'], sci: 'Diceros bicornis', g: 'rhino', f: f(1100, AF, H), d: 2, look: ['White rhinoceros'],
      b: 'A smaller rhino with a hooked lip for grabbing leaves from bushes. It is critically endangered.',
      c: ['It is critically endangered.', 'It has a pointed, hooked upper lip.', 'It browses on bushes rather than grass.', 'It has two horns.', 'It is grey, despite its name.'] },
    { n: 'Western gorilla', alt: ['gorilla'], sci: 'Gorilla gorilla', g: 'ape', f: f(140, AF, H), d: 1, look: ['Chimpanzee', 'Bornean orangutan'],
      b: 'The biggest ape. Gorillas live in family groups led by a big male called a silverback.',
      c: ['A gorilla called Koko learned many signs.', 'It builds a new nest to sleep in each night.', 'It walks on its knuckles.', 'Old males have silver hair on their backs.', 'It is the largest ape.'] },
    { n: 'Chimpanzee', alt: ['chimp'], sci: 'Pan troglodytes', g: 'ape', f: f(50, AF, O), d: 1, look: ['Bonobo', 'Western gorilla'],
      b: 'Our closest living relative, along with the bonobo. Chimps use sticks as tools to fish for termites.',
      c: ['Jane Goodall studied them at Gombe in Tanzania.', 'It uses sticks to fish termites out of mounds.', 'It shares about 98% of its DNA with us.', 'It lives in groups in African forests.', 'It is an ape and one of our closest relatives.'] },
    { n: 'Bonobo', sci: 'Pan paniscus', g: 'ape', f: f(40, AF, O), d: 3, look: ['Chimpanzee'],
      b: 'A peaceful ape that lives only south of the Congo River. Bonobo groups are led by females.',
      c: ['Its groups are led by females.', 'It lives only south of the Congo River.', 'It is more peaceful than its close cousin.', 'It is one of our two closest living relatives.', 'It looks like a slim chimpanzee.'] },
    { n: 'Bornean orangutan', alt: ['orangutan'], sci: 'Pongo pygmaeus', g: 'ape', f: f(60, AS, O), d: 1, look: ['Western gorilla'],
      b: 'A shaggy red-orange ape of Borneo that spends most of its life in trees. Its name means "person of the forest".',
      c: ['Adult males can have big cheek pads.', 'It makes a new tree nest every night.', 'Its arms are much longer than its legs.', 'Its name means "person of the forest" in Malay.', 'It is a red-orange ape.'] },
    { n: 'Ring-tailed lemur', alt: ['lemur'], sci: 'Lemur catta', g: 'primate', f: f(2.2, AF, O), d: 1,
      b: 'A primate from Madagascar with a long black-and-white striped tail. Groups sunbathe together in the morning.',
      c: ['Groups sit and sunbathe each morning.', 'Males have "stink fights" with their tails.', 'King Julien in "Madagascar" is one.', 'It lives only on Madagascar.', 'Its tail has black and white rings.'] },
    { n: 'Mandrill', sci: 'Mandrillus sphinx', g: 'primate', f: f(25, AF, O), d: 2,
      b: 'The largest monkey, with a bright red-and-blue face. Rafiki in "The Lion King" is partly based on one.',
      c: ['It is the largest monkey in the world.', 'It lives in rainforests of central Africa.', 'Rafiki in "The Lion King" is partly based on it.', 'It has a colourful bottom.', 'Males have a red nose and blue cheeks.'] },
    { n: 'Meerkat', sci: 'Suricata suricatta', g: 'mongoose', f: f(0.7, AF, I), d: 1,
      b: 'A small mongoose of southern Africa. Meerkats take turns standing on their back legs to watch for danger.',
      c: ['It is a kind of mongoose.', 'It is immune to some scorpion venom.', 'Timon in "The Lion King" is one.', 'It lives in big family groups in burrows.', 'It stands up on its back legs to keep watch.'] },
    { n: 'Spotted hyena', alt: ['hyena'], sci: 'Crocuta crocuta', g: 'hyena', f: f(60, AF, C), d: 1,
      b: 'A powerful hunter of the African savanna, famous for its "laughing" calls. Females lead the group.',
      c: ['Females are bigger than males and lead the clan.', 'It can crunch and digest bones.', 'It hunts more than it scavenges.', 'Its call sounds like laughing.', 'It is a spotted dog-like animal of Africa.'] },
    { n: 'African wild dog', alt: ['painted dog'], sci: 'Lycaon pictus', g: 'dog', f: f(25, AF, C), d: 2,
      b: 'A patchy-coated African dog that hunts in packs. Its hunts succeed more often than a lion\'s.',
      c: ['It has only four toes on each foot.', 'Pack members "vote" to start a hunt by sneezing.', 'Its hunts are very successful.', 'Each one has a unique patchy coat.', 'It is also called the painted wolf.'] },
    { n: 'Honey badger', alt: ['ratel'], sci: 'Mellivora capensis', g: 'weasel', f: f(10, AF, O), d: 2,
      b: 'A small, fearless animal with thick, loose skin. It raids bee nests and fights snakes.',
      c: ['Its loose skin lets it twist round to bite attackers.', 'It eats venomous snakes.', 'It is famous for being fearless.', 'It is black with a grey-white back.', 'It raids bees\' nests for a sweet food.'] },
    { n: 'Aardvark', sci: 'Orycteropus afer', g: 'aardvark', f: f(60, AF, I), d: 2,
      b: 'A burrowing African animal with a pig-like snout, long ears and a sticky tongue for eating ants and termites.',
      c: ['It comes first in most English dictionaries.', 'Its name means "earth pig" in Afrikaans.', 'It can dig very fast.', 'It eats ants and termites.', 'It has a long snout and rabbit-like ears.'] },
    { n: 'Okapi', sci: 'Okapia johnstoni', g: 'giraffe', f: f(250, AF, H), d: 2, look: ['Giraffe', 'Plains zebra'],
      b: 'A shy forest animal with zebra-striped legs. It is the giraffe\'s only living relative.',
      c: ['Its tongue is long enough to clean its ears.', 'Europeans did not know it until 1901.', 'It lives in rainforests of the Congo.', 'Its back legs have zebra-like stripes.', 'It is the giraffe\'s closest relative.'] },
    { n: 'Warthog', alt: ['common warthog'], sci: 'Phacochoerus africanus', g: 'pig', f: f(80, AF, O), d: 1,
      b: 'A wild African pig with tusks and lumpy "warts" on its face. It kneels to eat grass.',
      c: ['It runs with its tail straight up.', 'It kneels on its front legs to eat.', 'It backs into burrows so its tusks face out.', 'Pumbaa in "The Lion King" is one.', 'It is a wild pig with tusks.'] },
    // ---- Asia ----
    { n: 'Giant panda', alt: ['panda'], sci: 'Ailuropoda melanoleuca', g: 'bear', f: f(100, AS, H), d: 1, look: ['Red panda'],
      b: 'A black-and-white bear from the mountains of China. It eats bamboo for up to 14 hours a day.',
      c: ['It has a "thumb" made from a wrist bone.', 'It eats bamboo for up to 14 hours a day.', 'Its cubs are born tiny and pink.', 'It lives in the mountains of China.', 'It is a black-and-white bear.'] },
    { n: 'Red panda', sci: 'Ailurus fulgens', g: 'red panda', f: f(5, AS, H), d: 1, look: ['Giant panda'],
      b: 'A small, red-furred tree animal of the Himalayas with a ringed tail. It was called a panda before the giant panda.',
      c: ['It was named "panda" before the black-and-white bear.', 'It is not a bear or a raccoon.', 'It wraps its bushy tail around itself.', 'It lives in Himalayan forests.', 'It has red fur and a ringed tail.'] },
    { n: 'Proboscis monkey', sci: 'Nasalis larvatus', g: 'primate', f: f(15, AS, H), d: 2,
      b: 'A monkey of Borneo whose males have huge, droopy noses. It is a great swimmer.',
      c: ['It has webbed feet.', 'It lives in mangroves on Borneo.', 'It is a strong swimmer.', 'It has a pot belly.', 'Males have a huge, droopy nose.'] },
    { n: 'Japanese macaque', alt: ['snow monkey'], sci: 'Macaca fuscata', g: 'primate', f: f(10, AS, O), d: 2,
      b: 'The monkey that lives further north than any other. Some bathe in hot springs in winter.',
      c: ['Some wash sweet potatoes in the sea.', 'It lives further north than any other monkey.', 'Some bathe in hot springs in winter.', 'It has a bright red face.', 'It is often called the snow monkey.'] },
    { n: 'Malayan tapir', sci: 'Tapirus indicus', g: 'tapir', f: f(300, AS, H), d: 2,
      b: 'A black-and-white tapir of South-East Asia with a short trunk. Its colours break up its outline in the moonlit forest.',
      c: ['Its babies are brown with stripes and spots.', 'It is related to horses and rhinos.', 'It has a short, bendy trunk.', 'It is the largest tapir.', 'Its body is black with a white middle.'] },
    { n: 'Yak', sci: 'Bos mutus', inat: 'Bos grunniens', g: 'cattle', f: f(500, AS, H), d: 2,
      b: 'A shaggy wild ox of the Tibetan Plateau. Tame yaks carry loads and give milk in the Himalayas.',
      c: ['It grunts rather than moos.', 'It lives higher than almost any other large mammal.', 'Its milk is made into butter for tea.', 'It has long shaggy hair.', 'It is a wild ox of Tibet.'] },
    { n: 'Bactrian camel', sci: 'Camelus bactrianus', g: 'camel', f: f(500, AS, H), d: 2, look: ['Dromedary'],
      b: 'A two-humped camel of the cold deserts of Central Asia. Its humps store fat, not water.',
      c: ['It copes with winters of -40 °C and hot summers.', 'It lives in the Gobi Desert.', 'Its humps store fat, not water.', 'Its shaggy coat falls out in summer.', 'It has two humps.'] },
    // ---- Europe & northern lands ----
    { n: 'Grey wolf', alt: ['wolf', 'gray wolf'], sci: 'Canis lupus', g: 'dog', f: f(40, WW, C), d: 1, look: ['Dingo', 'Red fox'],
      b: 'The wild ancestor of the pet dog. Wolves live and hunt in family packs.',
      c: ['Pet dogs are descended from it.', 'Its reintroduction changed Yellowstone National Park.', 'It lives in family packs.', 'It howls to talk to its pack.', 'It is a wild dog of northern lands.'] },
    { n: 'Red fox', alt: ['fox'], sci: 'Vulpes vulpes', g: 'dog', f: f(6, WW, O), d: 1, look: ['Fennec fox', 'Grey wolf'],
      b: 'The most widespread wild carnivore on Earth. It lives in forests, farms and even big cities.',
      c: ['It was taken to Australia for hunting.', 'It pounces on mice under the snow.', 'It is common in cities like London.', 'It has a bushy, white-tipped tail.', 'It has orange-red fur.'] },
    { n: 'Fennec fox', alt: ['fennec'], sci: 'Vulpes zerda', g: 'dog', f: f(1.2, AF, O), d: 1, look: ['Red fox'],
      b: 'The smallest fox in the world, from the Sahara. Its enormous ears help it lose heat and hear prey underground.',
      c: ['It is the national animal of Algeria.', 'Its furry feet protect it from hot sand.', 'It can go a long time without drinking.', 'It is the smallest fox.', 'It has enormous ears.'] },
    { n: 'Polar bear', sci: 'Ursus maritimus', g: 'bear', f: f(450, AR, C), d: 1, look: ['Brown bear'],
      b: 'The biggest land carnivore. It lives on Arctic sea ice and hunts seals.',
      c: ['Its skin is black under its fur.', 'Its fur hairs are actually clear, not white.', 'It can swim for days.', 'It hunts seals on the sea ice.', 'It is a big white bear of the Arctic.'] },
    { n: 'Brown bear', alt: ['grizzly bear', 'grizzly'], sci: 'Ursus arctos', g: 'bear', f: f(300, WW, O), d: 1, look: ['Polar bear', 'American black bear'],
      b: 'A big bear of northern forests and mountains. It catches salmon in rivers and sleeps through the winter.',
      c: ['Kodiak ones are among the largest bears.', 'It has a hump of muscle on its shoulders.', 'It catches salmon jumping up waterfalls.', 'In North America it is called the grizzly.', 'It is a big brown bear.'] },
    { n: 'American black bear', alt: ['black bear'], sci: 'Ursus americanus', g: 'bear', f: f(120, NA, O), d: 2, look: ['Brown bear'],
      b: 'The most common bear in North America. Despite its name, it can be brown, cinnamon or even white.',
      c: ['Some on the Canadian coast are white.', 'It is an excellent tree climber.', 'It raids bins in towns.', 'It is the most common bear in North America.', 'It is often black.'] },
    { n: 'Moose', alt: ['elk'], sci: 'Alces alces', g: 'deer', f: f(450, WW, H), d: 1, look: ['Reindeer', 'Red deer'],
      b: 'The biggest deer in the world. Males have huge flat antlers. In Europe it is called an elk.',
      c: ['In Britain and Europe it is called an elk.', 'It can dive underwater to eat plants.', 'It has a flap of skin under its chin called a bell.', 'Males grow huge, flat antlers.', 'It is the biggest deer in the world.'] },
    { n: 'Reindeer', alt: ['caribou'], sci: 'Rangifer tarandus', g: 'deer', f: f(120, AR, H), d: 1, look: ['Moose'],
      b: 'A deer of the Arctic where both males and females grow antlers. In North America it is called a caribou.',
      c: ['Its knees make a clicking sound as it walks.', 'Its eyes change colour from gold to blue in winter.', 'Both males and females grow antlers.', 'In North America it is called a caribou.', 'Legend says it pulls Santa\'s sleigh.'] },
    { n: 'Red deer', alt: ['stag'], sci: 'Cervus elaphus', g: 'deer', f: f(150, EA, H), d: 2, look: ['Moose'],
      b: 'A big deer of Europe and Asia. In autumn, stags roar and fight with their antlers.',
      c: ['Stags roar in the autumn rut.', 'It is the largest wild land mammal in Britain.', 'It sheds its antlers every year.', 'A male is called a stag.', 'Its coat is reddish-brown.'] },
    { n: 'European hedgehog', alt: ['hedgehog'], sci: 'Erinaceus europaeus', g: 'hedgehog', f: f(0.9, EU, I), d: 1,
      b: 'A small, spiny animal that rolls into a ball when scared. It hibernates through winter.',
      c: ['It has about 5,000 to 7,000 spines.', 'It hibernates in winter.', 'It eats beetles, worms and slugs.', 'It rolls into a spiky ball when scared.', 'It is covered in spines.'] },
    { n: 'Red squirrel', alt: ['squirrel'], sci: 'Sciurus vulgaris', g: 'rodent', f: f(0.3, EA, H), d: 1,
      b: 'A red squirrel with tufted ears. In Britain it has been pushed out of most areas by the grey squirrel.',
      c: ['In Britain it survives mostly in Scotland and on islands.', 'It has ear tufts in winter.', 'It buries nuts and forgets some, planting trees.', 'It has a big bushy tail.', 'Its fur is reddish.'] },
    { n: 'European badger', alt: ['badger'], sci: 'Meles meles', g: 'weasel', f: f(12, EA, O), d: 2,
      b: 'A stocky night-time animal with a black-and-white striped face. It lives in big burrows called setts.',
      c: ['Its burrow is called a sett.', 'It eats lots of earthworms.', 'Its setts can be used for centuries.', 'It comes out at night.', 'Its face has black and white stripes.'] },
    { n: 'Eurasian otter', alt: ['otter'], sci: 'Lutra lutra', g: 'weasel', f: f(8, EA, C), d: 2,
      b: 'A playful river otter of Europe and Asia. It swims with its webbed feet and catches fish.',
      c: ['Its droppings are called spraints.', 'It has returned to every county in England.', 'It has webbed feet.', 'It lives along rivers and catches fish.', 'It is a sleek, playful swimmer.'] },
    { n: 'Wolverine', sci: 'Gulo gulo', g: 'weasel', f: f(13, AR, C), d: 2,
      b: 'The largest land member of the weasel family. It is tough enough to chase wolves off a kill.',
      c: ['It can chase wolves off their kill.', 'Its scientific name means "glutton".', 'It is the largest land weasel.', 'It lives in cold northern forests.', 'A Marvel superhero shares its name.'] },
    { n: 'European rabbit', alt: ['rabbit', 'bunny'], sci: 'Oryctolagus cuniculus', g: 'rabbit', f: f(1.8, WW, H), d: 1, look: ['European hare'],
      b: 'The rabbit that all pet rabbits come from. Rabbits live in burrows called warrens.',
      c: ['It eats some of its own droppings.', 'Its introduction to Australia caused a plague.', 'It lives in burrows called warrens.', 'It thumps its back feet as a warning.', 'All pet bunnies come from it.'] },
    { n: 'European hare', alt: ['brown hare', 'hare'], sci: 'Lepus europaeus', g: 'rabbit', f: f(4, EU, H), d: 2, look: ['European rabbit'],
      b: 'A long-eared, long-legged animal like a big rabbit. In spring, hares "box" in fields.',
      c: ['Its babies are born with fur and open eyes.', 'It does not dig burrows.', 'It can run at about 70 km/h.', 'In spring it "boxes" in fields.', 'It looks like a big rabbit with long ears.'] },
    // ---- the Americas ----
    { n: 'American bison', alt: ['bison', 'buffalo'], sci: 'Bison bison', g: 'cattle', f: f(700, NA, H), d: 1,
      b: 'The biggest land animal in North America. Tens of millions once roamed the plains before hunters nearly wiped them out.',
      c: ['Only a few hundred were left by about 1890.', 'It can run at about 55 km/h.', 'Tens of millions once roamed the Great Plains.', 'It has a big shoulder hump.', 'It is often called a buffalo.'] },
    { n: 'Llama', sci: 'Lama glama', g: 'camel', f: f(150, SA, H), d: 1, look: ['Alpaca'],
      b: 'A tall South American camel relative used to carry loads in the Andes. It spits when annoyed.',
      c: ['It is related to camels.', 'It was used by the Inca to carry goods.', 'It spits when annoyed.', 'It is bigger than an alpaca.', 'It lives in the Andes.'] },
    { n: 'Alpaca', sci: 'Lama pacos', g: 'camel', f: f(60, SA, H), d: 1, look: ['Llama'],
      b: 'A fluffy South American animal kept for its soft wool. It is smaller than a llama.',
      c: ['It hums to communicate.', 'It was bred from the wild vicuña.', 'Its wool is very soft and warm.', 'It is smaller than a llama.', 'It is fluffy and lives in the Andes.'] },
    { n: 'Capybara', sci: 'Hydrochoerus hydrochaeris', g: 'rodent', f: f(50, SA, H), d: 1,
      b: 'The biggest rodent in the world. It is so calm that other animals sit on it.',
      c: ['Birds and monkeys often sit on it.', 'It has partly webbed feet.', 'It lives near rivers in South America.', 'It is very calm and friendly.', 'It is the biggest rodent in the world.'] },
    { n: 'Giant anteater', alt: ['anteater'], sci: 'Myrmecophaga tridactyla', g: 'anteater', f: f(35, SA, I), d: 1,
      b: 'A big South American animal with a long snout and a sticky tongue up to 60 cm long. It eats thousands of ants a day.',
      c: ['It has no teeth.', 'It can flick its tongue about 150 times a minute.', 'It walks on its knuckles to protect its claws.', 'Its tongue can be 60 cm long.', 'It eats thousands of ants and termites a day.'] },
    { n: 'Brown-throated sloth', alt: ['three-toed sloth', 'sloth'], sci: 'Bradypus variegatus', g: 'sloth', f: f(4, SA, H), d: 1,
      b: 'The world\'s slowest mammal. It hangs upside down in trees and climbs down only about once a week to go to the toilet.',
      c: ['Green algae grow in its fur.', 'It comes down from its tree about once a week to poo.', 'It can turn its head almost all the way round.', 'It hangs upside down.', 'It is the slowest mammal.'] },
    { n: 'Nine-banded armadillo', alt: ['armadillo'], sci: 'Dasypus novemcinctus', g: 'armadillo', f: f(5, AM, I), d: 1,
      b: 'An animal covered in bony armour. It nearly always gives birth to four identical babies.',
      c: ['It usually gives birth to identical quadruplets.', 'It can hold its breath for six minutes.', 'It jumps straight up when startled.', 'It is covered in bony armour.', 'Its name means "little armoured one" in Spanish.'] },
    { n: 'North American beaver', alt: ['beaver'], sci: 'Castor canadensis', g: 'rodent', f: f(20, NA, H), d: 1,
      b: 'A big rodent that builds dams across streams with sticks and mud. Its orange teeth never stop growing.',
      c: ['Its front teeth are orange because of iron.', 'It is the national animal of Canada.', 'It slaps its flat tail on water as a warning.', 'It builds dams and lodges.', 'It chews down trees with its teeth.'] },
    { n: 'Common raccoon', alt: ['raccoon', 'racoon'], sci: 'Procyon lotor', g: 'raccoon', f: f(7, NA, O), d: 1, look: ['Red panda'],
      b: 'A clever animal with a black "mask" and a ringed tail. It often raids rubbish bins at night.',
      c: ['Its front paws are very sensitive.', 'It sometimes dunks food in water before eating.', 'It raids rubbish bins.', 'It has a ringed tail.', 'It has a black mask across its eyes.'] },
    { n: 'Striped skunk', alt: ['skunk'], sci: 'Mephitis mephitis', g: 'skunk', f: f(3, NA, O), d: 1,
      b: 'A black-and-white animal that sprays a horrible-smelling liquid at attackers.',
      c: ['Its spray can be smelled over a kilometre away.', 'It stamps its feet as a warning.', 'Great horned owls hunt it.', 'It has a white stripe down its back.', 'It sprays a terrible smell.'] },
    { n: 'Virginia opossum', alt: ['opossum', 'possum'], sci: 'Didelphis virginiana', g: 'marsupial', f: f(3, NA, O), d: 2,
      b: 'North America\'s only marsupial. It "plays dead" when in danger.',
      c: ['It has 50 teeth.', 'It is the only marsupial in the USA and Canada.', 'It carries its babies in a pouch and on its back.', 'Its long tail is almost hairless.', 'It "plays dead" when scared.'] },
    // ---- Australia ----
    { n: 'Red kangaroo', alt: ['kangaroo'], sci: 'Osphranter rufus', g: 'marsupial', f: f(55, AU, H), d: 1, look: ['Eastern grey kangaroo'],
      b: 'The biggest marsupial in the world. It hops on its big back legs and carries its baby, a joey, in a pouch.',
      c: ['It can jump about 8 metres in one bound.', 'Its baby is called a joey.', 'It uses its strong tail like a fifth leg.', 'It appears on Australia\'s coat of arms.', 'It is the biggest marsupial.'] },
    { n: 'Eastern grey kangaroo', sci: 'Macropus giganteus', g: 'marsupial', f: f(40, AU, H), d: 2, look: ['Red kangaroo'],
      b: 'A big grey kangaroo common in the grasslands and woodlands of eastern Australia.',
      c: ['It is common on golf courses in eastern Australia.', 'Its species name means "gigantic".', 'It lives in groups called mobs.', 'It is the second-largest marsupial.', 'It has soft grey fur.'] },
    { n: 'Koala', alt: ['koala bear'], sci: 'Phascolarctos cinereus', g: 'marsupial', f: f(9, AU, H), d: 1, look: ['Common wombat'],
      b: 'A tree-living marsupial from Australia that eats gum leaves. It sleeps for up to 20 hours a day.',
      c: ['Its fingerprints are almost like a human\'s.', 'It sleeps up to 20 hours a day.', 'It eats almost only eucalyptus leaves.', 'It is not a bear, but a marsupial.', 'It is a furry grey tree-dweller from Australia.'] },
    { n: 'Common wombat', alt: ['wombat'], sci: 'Vombatus ursinus', g: 'marsupial', f: f(30, AU, H), d: 1, look: ['Koala'],
      b: 'A stocky burrowing marsupial from Australia. Famously, it does cube-shaped poo.',
      c: ['Its pouch faces backwards so dirt does not get in.', 'Its bottom is hard, like a shield.', 'It digs long burrows.', 'It is a stocky Australian marsupial.', 'It does cube-shaped poo.'] },
    { n: 'Tasmanian devil', sci: 'Sarcophilus harrisii', g: 'marsupial', f: f(8, AU, C), d: 1,
      b: 'The biggest meat-eating marsupial alive. It screeches loudly and has a very strong bite.',
      c: ['A contagious face cancer has hit its numbers.', 'It eats bones and fur too.', 'It screeches when it feeds.', 'It is black with a white chest band.', 'It lives only on an island state of Australia.'] },
    { n: 'Platypus', alt: ['duck-billed platypus'], sci: 'Ornithorhynchus anatinus', g: 'monotreme', f: f(1.5, AU, C), d: 1, look: ['Short-beaked echidna'],
      b: 'An Australian mammal that lays eggs, has a duck-like bill and webbed feet. Males have venomous spurs.',
      c: ['Its fur glows under ultraviolet light.', 'Males have venomous spurs on their back legs.', 'It finds prey using electric signals.', 'It is a mammal that lays eggs.', 'It has a duck-like bill.'] },
    { n: 'Short-beaked echidna', alt: ['echidna', 'spiny anteater'], sci: 'Tachyglossus aculeatus', g: 'monotreme', f: f(4, AU, I), d: 1, look: ['Platypus', 'European hedgehog'],
      b: 'A spiny Australian mammal that lays eggs. Its baby, called a puggle, hatches in its pouch.',
      c: ['Its baby is called a puggle.', 'It is on the Australian five-cent coin.', 'It eats ants with a long sticky tongue.', 'It lays eggs.', 'It is covered in spines.'] },
    { n: 'Quokka', sci: 'Setonix brachyurus', g: 'marsupial', f: f(3, AU, H), d: 1,
      b: 'A small wallaby that looks like it is smiling. It is famous for selfies on Rottnest Island.',
      c: ['Dutch explorers thought it was a giant rat.', 'Rottnest Island means "rat\'s nest island".', 'It is famous for selfies.', 'It lives on Rottnest Island.', 'It looks as if it is smiling.'] },
    { n: 'Sugar glider', sci: 'Petaurus breviceps', g: 'marsupial', f: f(0.12, AU, O), d: 2,
      b: 'A tiny marsupial that glides between trees on flaps of skin. It loves sweet sap and nectar.',
      c: ['It can glide about 50 metres.', 'It lives in family groups in tree hollows.', 'It is active at night.', 'It has a flap of skin like a cape between its legs.', 'It loves sweet food and glides.'] },
    { n: 'Numbat', alt: ['banded anteater'], sci: 'Myrmecobius fasciatus', g: 'marsupial', f: f(0.6, AU, I), d: 2,
      b: 'A striped marsupial from Western Australia that eats up to 20,000 termites a day.',
      c: ['It is Western Australia\'s animal emblem.', 'It eats up to 20,000 termites a day.', 'It is active during the day.', 'It has white stripes across its back.', 'Its name starts with a word for having no feeling.'] },
    { n: 'Greater bilby', alt: ['bilby'], sci: 'Macrotis lagotis', g: 'marsupial', f: f(1.5, AU, O), d: 2,
      b: 'A desert marsupial with long rabbit-like ears. Australians buy chocolate bilbies at Easter instead of bunnies.',
      c: ['It never needs to drink water.', 'Its pouch faces backwards.', 'It digs spiral burrows.', 'Chocolate ones are sold at Easter in Australia.', 'It has long ears like a rabbit.'] },
    { n: 'Dingo', sci: 'Canis familiaris dingo', inat: 'Canis familiaris dingo', g: 'dog', f: f(15, AU, C), d: 1, look: ['Grey wolf'],
      b: 'Australia\'s wild dog. Dingoes arrived in Australia thousands of years ago.',
      c: ['A 5,600 km fence keeps it out of south-eastern farmland.', 'It howls but rarely barks.', 'It arrived in Australia thousands of years ago.', 'It is usually sandy-ginger.', 'It is Australia\'s wild dog.'] },
    { n: 'Grey-headed flying fox', alt: ['flying fox', 'fruit bat'], sci: 'Pteropus poliocephalus', g: 'bat', f: f(0.7, AU, H), d: 2,
      b: 'A big fruit bat of eastern Australia. Huge colonies roost in city parks, and they spread seeds and pollen at night.',
      c: ['It spreads pollen and seeds over long distances.', 'Colonies roost in city parks.', 'It has a ginger collar.', 'It eats fruit and nectar.', 'It is a big bat with a fox-like face.'] },
    // ---- worldwide oddities ----
    { n: 'Chinese pangolin', alt: ['pangolin'], sci: 'Manis pentadactyla', g: 'pangolin', f: f(4, AS, I), d: 2,
      b: 'A scaly anteater that rolls into an armoured ball. Pangolins are among the most trafficked mammals.',
      c: ['It is one of the most trafficked mammals.', 'It has no teeth.', 'Its scales are made of keratin, like hair.', 'It rolls into a ball when scared.', 'It is the only mammal covered in scales.'] },
    { n: 'Naked mole-rat', sci: 'Heterocephalus glaber', g: 'rodent', f: f(0.035, AF, H), d: 2,
      b: 'A wrinkly, almost hairless rodent that lives underground in colonies with a queen, like bees.',
      c: ['It can live for over 30 years.', 'It hardly ever gets cancer.', 'Its colony has a queen, like bees.', 'It lives underground in East Africa.', 'It is wrinkly and nearly hairless.'] },
    { n: 'Crested porcupine', alt: ['porcupine'], sci: 'Hystrix cristata', g: 'rodent', f: f(15, AF, H), d: 2,
      b: 'A big rodent covered in long sharp quills. It rattles its quills and charges backwards at attackers.',
      c: ['It rattles hollow quills on its tail.', 'It charges backwards at attackers.', 'It cannot shoot its quills.', 'It is a large rodent.', 'It is covered in long sharp spines.'] },
    { n: 'Dromedary', alt: ['camel', 'Arabian camel'], sci: 'Camelus dromedarius', g: 'camel', f: f(500, 'Africa and the Middle East', H), d: 1, look: ['Bactrian camel'],
      b: 'A one-humped camel of hot deserts. It can drink over 100 litres of water in a few minutes.',
      c: ['It can drink over 100 litres in about 10 minutes.', 'Australia has the largest wild herd.', 'It can close its nostrils against sand.', 'Its hump stores fat.', 'It has one hump.'] },
  ],
  fakes: ['Golden-maned tapir', 'Pygmy snow wombat', 'Striped forest yak', 'Northern glass otter', 'Spotted marsh panda', 'Desert thunder lemur', 'Crested tundra koala'],
  questions: [
    { kind: 'mc', prompt: 'Which is the biggest land animal?', answer: 'African bush elephant', wrong: ['Giraffe', 'Hippopotamus', 'White rhinoceros'], explain: 'Bulls can weigh over 6 tonnes.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the tallest animal?', answer: 'Giraffe', wrong: ['African bush elephant', 'Ostrich', 'Moose'], explain: 'Males can be about 5.5 m tall.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the fastest land animal?', answer: 'Cheetah', wrong: ['Lion', 'Horse', 'Greyhound'], explain: 'It can reach about 100 km/h in short sprints.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which mammals lay eggs?', answer: 'Platypus and echidna', wrong: ['Koala and wombat', 'Bat and mole', 'Kangaroo and wallaby'], explain: 'They are monotremes, found only in Australia and New Guinea.', difficulty: 2 },
    { kind: 'tf', prompt: 'A koala is a kind of bear.', answer: false, explain: 'Koalas are marsupials that carry their babies in a pouch.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is a baby kangaroo called?', answer: 'A joey', wrong: ['A cub', 'A kit', 'A calf'], explain: 'Joeys grow up in their mother\'s pouch.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which animal is famous for cube-shaped poo?', answer: 'Common wombat', wrong: ['Koala', 'Rabbit', 'Kangaroo'], explain: 'Its intestines shape the droppings into cubes.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the biggest rodent in the world?', answer: 'Capybara', wrong: ['Beaver', 'Porcupine', 'Rat'], explain: 'Capybaras can weigh over 60 kg.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the only bear that eats mostly bamboo?', answer: 'Giant panda', wrong: ['Polar bear', 'Brown bear', 'Red panda'], explain: 'Bamboo makes up about 99% of its diet. Red pandas are not bears.', difficulty: 1 },
    { kind: 'tf', prompt: 'A bat is a mammal.', answer: true, explain: 'Bats are the only mammals that can truly fly.', difficulty: 1 },
    { kind: 'mc', prompt: 'What colour is a polar bear\'s skin?', answer: 'Black', wrong: ['White', 'Pink', 'Grey'], explain: 'Black skin soaks up heat; its fur hairs are clear.', difficulty: 2 },
    { kind: 'mc', prompt: 'How many bones are in a giraffe\'s neck?', answer: '7', wrong: ['2', '20', '50'], explain: 'Almost all mammals, including us, have seven neck bones.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is a group of lions called?', answer: 'A pride', wrong: ['A pack', 'A herd', 'A flock'], explain: 'Lions are the only truly social cats.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which animal is the closest living relative of the giraffe?', answer: 'Okapi', wrong: ['Zebra', 'Camel', 'Antelope'], explain: 'Okapis are giraffids that live in Congo rainforest.', difficulty: 2 },
    { kind: 'mc', prompt: 'What do you call an animal that eats only plants?', answer: 'Herbivore', wrong: ['Carnivore', 'Omnivore', 'Insectivore'], explain: 'Herbivores eat plants; carnivores eat meat; omnivores eat both.', difficulty: 1 },
  ],
};
