import { INAT, WD } from './_common.mjs';

const E = 'Edible', I = 'Inedible', P = 'Poisonous', X = 'Deadly';
const EU = 'Europe', AS = 'Asia', AU = 'Australia', NA = 'North America', WW = 'many parts of the world', NH = 'the northern hemisphere';
const f = (edibility, region, extra = {}) => ({ ...(edibility ? { edibility } : {}), region, ...extra });

export default {
  id: 'mushrooms', title: 'Mushrooms & fungi', theme: 'nature', icon: '🍄', kids: false, kidsSafe: false,
  noun: 'mushroom or fungus', fakePrompt: 'Which of these mushrooms and fungi is made up?',
  notice: 'Never use this to forage. Many deadly mushrooms look like edible ones. Not for real-world identification.',
  leakExempt: ['mushroom', 'mushrooms', 'fungus', 'fungi'],
  wikiD1: true, autoTaxo: ['family', 'genus'],
  factsMeta: {
    edibility: { type: 'cat', label: 'Edibility', values: [E, I, P, X], clue: v => ({ [E]: 'It is eaten as food, but only when expertly identified.', [I]: 'It is not good to eat.', [P]: 'It is poisonous.', [X]: 'It can kill people who eat it.' }[v]) },
    region: { type: 'cat', label: 'Found in', clue: v => `It grows in ${v}.` },
    glows: { type: 'bool', label: 'Glows in the dark', yes: 'Glows in the dark', no: 'Does not glow', clue: v => (v ? 'It glows in the dark.' : null) },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which fungus is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"edibility": {"ask": "Which word best describes the {lname}?", "askReverse": "Which of these is classed as \"{lvalue}\"?", "stmt": "The {lname} is classed as \"{lvalue}\"."}, "region": {"ask": "Where does the {lname} grow?", "stmt": "The {lname} grows in {value}.", "exclusive": false}, "glows": {"askBool": "Which of these glows in the dark?", "stmt": "The {lname} glows in the dark."}},
  sources: [INAT, WD],
  items: [
    { n: 'Death cap', sci: 'Amanita phalloides', g: 'amanita', f: f(X, WW), d: 1, look: ['Field mushroom', 'Destroying angel', 'Paddy straw mushroom'],
      b: 'The deadliest mushroom in the world. It causes most mushroom poisoning deaths, and cooking does not make it safe.',
      c: ['It has spread to Australia and North America on the roots of imported trees.', 'Symptoms can seem to get better before the liver fails.', 'Half a cap can kill an adult.', 'It has a ring on its stem and a cup-like sac at its base.', 'It causes most deaths from mushroom poisoning.'] },
    { n: 'Destroying angel', sci: 'Amanita virosa', g: 'amanita', f: f(X, EU), d: 2, look: ['Death cap', 'Field mushroom'],
      b: 'A pure white, deadly mushroom closely related to the death cap. It is easily mistaken for edible white mushrooms.',
      c: ['It contains the same toxins as the death cap.', 'Its gills stay white, unlike a field mushroom\'s.', 'It has a sac-like cup at its base.', 'It is pure white.', 'Its name sounds heavenly but deadly.'] },
    { n: 'Fly agaric', alt: ['fly amanita'], sci: 'Amanita muscaria', g: 'amanita', f: f(P, NH), d: 1, look: ['Panther cap'],
      b: 'The classic red toadstool with white spots, seen in fairy tales and video games. It is poisonous.',
      c: ['It was once broken into milk to kill flies.', 'It grows with birch and pine trees.', 'Its white spots can wash off in rain.', 'It appears in "Super Mario" games.', 'It is red with white spots.'] },
    { n: 'Panther cap', sci: 'Amanita pantherina', g: 'amanita', f: f(P, NH), d: 3, look: ['Fly agaric'],
      b: 'A brown-capped Amanita with white warts. It is poisonous.',
      c: ['It is a close relative of the fly agaric.', 'It has a ring on its stem.', 'Its base has a rim like a collar.', 'Its brown cap has white warts.', 'It is named after a spotted big cat.'] },
    { n: 'Field mushroom', alt: ['meadow mushroom'], sci: 'Agaricus campestris', g: 'agaricus', f: f(E, WW), d: 2, look: ['Death cap', 'Yellow stainer', 'Destroying angel'],
      b: 'A white mushroom of grassy fields, related to the button mushroom. Deadly white Amanitas can look similar.',
      c: ['Deadly white Amanitas can look very similar.', 'Its gills turn from pink to chocolate brown.', 'It grows in grassy pastures.', 'It is a close relative of the supermarket mushroom.', 'It grows in meadows.'] },
    { n: 'Button mushroom', alt: ['white mushroom', 'portobello', 'chestnut mushroom', 'champignon'], sci: 'Agaricus bisporus', g: 'agaricus', f: f(E, WW), d: 1, look: ['Field mushroom'],
      b: 'The common supermarket mushroom. White button, chestnut and portobello mushrooms are all the same species.',
      c: ['Portobello mushrooms are just grown-up ones.', 'It is grown in the dark on compost.', 'It is the most farmed mushroom in the world.', 'It is sold in every supermarket.', 'Its small white form looks like a shirt fastener.'] },
    { n: 'Yellow stainer', sci: 'Agaricus xanthodermus', g: 'agaricus', f: f(P, WW), d: 3, look: ['Field mushroom'],
      b: 'A poisonous mushroom that looks like a field mushroom but turns bright yellow when scratched and smells of ink.',
      c: ['It causes many poisonings in Australia.', 'It smells of ink or disinfectant.', 'It looks like an edible field mushroom.', 'Its base turns bright yellow when scratched.', 'It stains yellow.'] },
    { n: 'Golden chanterelle', alt: ['chanterelle', 'girolle'], sci: 'Cantharellus cibarius', g: 'chanterelle', f: f(E, EU), d: 2, look: ['Jack-o\'-lantern mushroom'],
      b: 'A golden, funnel-shaped mushroom with a fruity smell. It has ridges instead of true gills.',
      c: ['It smells faintly of apricots.', 'It has ridges instead of real gills.', 'It is prized by chefs.', 'It is shaped like a funnel or trumpet.', 'It is golden-yellow.'] },
    { n: 'Jack-o\'-lantern mushroom', alt: ['jack-o-lantern'], sci: 'Omphalotus olearius', g: 'omphalotus', f: f(P, EU, { glows: true }), d: 2, look: ['Golden chanterelle', 'Ghost fungus'],
      b: 'A bright orange, poisonous mushroom that grows in clusters on wood. Its gills glow faintly green in the dark.',
      c: ['Its gills glow faintly green.', 'It is often mistaken for chanterelles.', 'It grows in clusters on olive and oak wood.', 'It is bright orange.', 'It is named after a carved Halloween pumpkin.'] },
    { n: 'Ghost fungus', sci: 'Omphalotus nidiformis', g: 'omphalotus', f: f(P, AU, { glows: true }), d: 2, look: ['Jack-o\'-lantern mushroom'],
      b: 'An Australian mushroom that glows green in the dark. It is poisonous.',
      c: ['It is related to the jack-o\'-lantern mushroom.', 'It grows on dead wood in Australian forests.', 'It is shaped like a fan.', 'It glows green at night.', 'It is named after a spooky spirit.'] },
    { n: 'Penny bun', alt: ['porcini', 'cep', 'king bolete'], sci: 'Boletus edulis', g: 'bolete', f: f(E, NH), d: 2,
      b: 'A chunky mushroom with a brown cap and sponge-like pores instead of gills. Italians call it porcini.',
      c: ['Its name in Italian means "piglets".', 'It is sold dried for risotto.', 'It has pores like a sponge, not gills.', 'Its cap is brown like a bread roll.', 'Its name includes a small coin.'] },
    { n: 'Shaggy ink cap', alt: ['lawyer\'s wig', 'shaggy mane'], sci: 'Coprinus comatus', g: 'ink cap', f: f(E, WW), d: 2,
      b: 'A tall, white, shaggy mushroom that melts into black ink as it ages. The ink was once used for writing.',
      c: ['It is nicknamed the "lawyer\'s wig".', 'Its gills melt into a black liquid.', 'The liquid was once used as ink.', 'It is tall, white and shaggy.', 'It grows on lawns and roadsides.'] },
    { n: 'Giant puffball', alt: ['puffball'], sci: 'Calvatia gigantea', g: 'puffball', f: f(E, NH), d: 1,
      b: 'A huge white ball of a mushroom that can grow as big as a football. Old ones release trillions of spores.',
      c: ['One can release trillions of spores.', 'It has no cap, gills or stem.', 'It can grow as big as a football.', 'It is a big white ball.', 'Old ones send out smoky clouds when squeezed.'] },
    { n: 'Common morel', alt: ['morel', 'yellow morel'], sci: 'Morchella esculenta', g: 'morel', f: f(E, NH), d: 2, look: ['False morel'],
      b: 'A prized mushroom with a honeycomb-patterned cap. It is hollow inside, unlike the poisonous false morel.',
      c: ['It often appears after forest fires.', 'It must always be cooked.', 'Its cap is hollow inside.', 'Its cap looks like a honeycomb.', 'It is a prized spring mushroom.'] },
    { n: 'False morel', alt: ['brain mushroom'], sci: 'Gyromitra esculenta', g: 'morel', f: f(X, NH), d: 3, look: ['Common morel'],
      b: 'A poisonous lookalike of the morel with a wrinkled, brain-like cap. It contains a toxin related to rocket fuel.',
      c: ['Its toxin turns into a chemical used in rocket fuel.', 'It has been eaten in Finland after special treatment, which is still risky.', 'Its cap is not hollow.', 'Its cap looks like a brain.', 'It is a dangerous lookalike of the morel.'] },
    { n: 'Oyster mushroom', sci: 'Pleurotus ostreatus', g: 'oyster', f: f(E, WW), d: 1,
      b: 'A fan-shaped mushroom that grows in layers on dead trees. It even catches and eats tiny worms.',
      c: ['It traps and digests tiny worms called nematodes.', 'It can be grown on coffee grounds.', 'It grows in overlapping shelves on wood.', 'It is a popular farmed mushroom.', 'It is shaped like a shellfish.'] },
    { n: 'Shiitake', sci: 'Lentinula edodes', g: 'shiitake', f: f(E, AS), d: 1,
      b: 'A brown East Asian mushroom grown on logs. It has a rich, savoury taste.',
      c: ['It has been farmed in China for about 1,000 years.', 'It is grown on oak logs.', 'Its name comes from Japanese for a tree it grows on.', 'It is used in miso soup and stir-fries.', 'It is a brown Japanese mushroom.'] },
    { n: 'Enoki', alt: ['enokitake', 'velvet shank'], sci: 'Flammulina velutipes', g: 'enoki', f: f(E, AS), d: 2,
      b: 'Farmed enoki are long, thin and white, grown in the dark. Wild ones look very different, with orange caps.',
      c: ['Wild ones have orange caps and velvety stems.', 'It grows even in winter.', 'Farmed ones are grown in the dark in bottles.', 'It is used in hot pot and soup.', 'Farmed ones are long, thin and white.'] },
    { n: 'Chicken of the woods', alt: ['sulphur shelf'], sci: 'Laetiporus sulphureus', g: 'bracket', f: f(E, NH), d: 2,
      b: 'A bright orange-yellow bracket fungus that grows in shelves on trees. It is said to taste like chicken.',
      c: ['It can cause stomach upsets in some people.', 'It grows in overlapping shelves.', 'It is bright orange and sulphur-yellow.', 'It grows on oak and other trees.', 'It is said to taste like a farm bird.'] },
    { n: 'Turkey tail', sci: 'Trametes versicolor', g: 'bracket', f: f(I, WW), d: 1,
      b: 'A thin bracket fungus with bands of colour, like a fanned-out turkey\'s tail.',
      c: ['Its species name means "of several colours".', 'It is one of the most common fungi on dead wood.', 'It is too tough to eat.', 'It has bands of brown, grey and cream.', 'It looks like the fanned tail of a big bird.'] },
    { n: 'Lion\'s mane', ln: 'lion\'s mane', alt: ['bearded tooth fungus', 'pom pom mushroom'], sci: 'Hericium erinaceus', g: 'tooth fungus', f: f(E, NH), d: 2,
      b: 'A white fungus made of long, dangling spines, like a shaggy mane or a frozen waterfall.',
      c: ['It is rare and protected in Britain.', 'It tastes a bit like crab or lobster.', 'It grows on old beech and oak trees.', 'It is made of long white dangling spines.', 'It looks like the mane of a big cat.'] },
    { n: 'Common stinkhorn', alt: ['stinkhorn'], sci: 'Phallus impudicus', g: 'stinkhorn', f: f(null, EU), d: 2, look: ['Veiled lady'],
      b: 'A smelly fungus that hatches from an "egg". Its slimy tip smells of rotting meat to attract flies, which spread its spores.',
      c: ['It grows out of a jelly-filled "egg".', 'Flies spread its spores.', 'You often smell it before you see it.', 'Its tip is covered in dark green slime.', 'It smells awful.'] },
    { n: 'Collared earthstar', alt: ['earthstar'], sci: 'Geastrum triplex', g: 'earthstar', f: f(I, WW), d: 2,
      b: 'A fungus whose outer skin splits into a star shape around a round spore sac.',
      c: ['Raindrops puff its spores out.', 'It grows in leaf litter.', 'It has a round spore sac in the middle.', 'It is related to puffballs.', 'Its outer layer splits into a star.'] },
    { n: 'Deadly webcap', sci: 'Cortinarius rubellus', g: 'webcap', f: f(X, EU), d: 3,
      b: 'A rusty-orange mushroom whose poison destroys the kidneys. Symptoms can take up to three weeks to appear.',
      c: ['Symptoms can take two to three weeks to appear.', 'Its poison attacks the kidneys.', 'Young ones have a cobweb-like veil.', 'It grows in pine forests.', 'It is rusty orange and very poisonous.'] },
    { n: 'Funeral bell', sci: 'Galerina marginata', g: 'galerina', f: f(X, WW), d: 3,
      b: 'A small brown mushroom on rotting wood that contains the same deadly toxins as the death cap.',
      c: ['It contains the same toxins as the death cap.', 'It grows on rotting wood.', 'It is a small brown mushroom.', 'It has a ring on its stem.', 'Its name is linked to a burial.'] },
    { n: 'Honey fungus', sci: 'Armillaria mellea', g: 'armillaria', f: f(E, NH), d: 2,
      b: 'A clump-forming fungus that attacks trees. A related species in Oregon is one of the largest living things on Earth.',
      c: ['A relative in Oregon covers nearly 10 square kilometres.', 'Its black root-like strands are called bootlaces.', 'It kills trees and shrubs in gardens.', 'It grows in big clumps.', 'Its cap is the colour of a sweet bee product.'] },
    { n: 'Sulphur tuft', sci: 'Hypholoma fasciculare', g: 'hypholoma', f: f(P, NH), d: 3,
      b: 'A bitter, poisonous mushroom that grows in big yellow clumps on dead wood.',
      c: ['It tastes very bitter.', 'Its gills turn from yellow to greenish to dark.', 'It grows in big clumps on stumps.', 'It is very common.', 'It is bright sulphur yellow.'] },
    { n: 'Amethyst deceiver', sci: 'Laccaria amethystina', g: 'laccaria', f: f(E, NH), d: 2,
      b: 'A small, bright purple mushroom that fades as it dries out, making it hard to recognise.',
      c: ['It can soak up arsenic from soil.', 'Its colour fades as it dries.', 'It grows in woodland leaf litter.', 'It is bright violet.', 'It is named after a purple gemstone.'] },
    { n: 'Scarlet elf cup', sci: 'Sarcoscypha austriaca', g: 'cup fungus', f: f(null, NH), d: 2,
      b: 'A bright red, cup-shaped fungus that grows on mossy fallen twigs in winter and early spring.',
      c: ['It grows on mossy twigs.', 'It appears in winter and early spring.', 'It can puff out clouds of spores.', 'It is shaped like a cup.', 'It is bright scarlet red.'] },
    { n: 'Parasol mushroom', alt: ['parasol'], sci: 'Macrolepiota procera', g: 'parasol', f: f(E, NH), d: 2,
      b: 'A tall mushroom with a wide, scaly cap like an umbrella. Its stem has a snakeskin pattern.',
      c: ['Its ring can slide up and down the stem.', 'Its stem has a snakeskin pattern.', 'Its cap can be 30 cm across.', 'It is very tall.', 'Its cap opens like an umbrella.'] },
    { n: 'Veiled lady', alt: ['bamboo fungus', 'long net stinkhorn'], sci: 'Phallus indusiatus', g: 'stinkhorn', f: f(E, AS), d: 3, look: ['Common stinkhorn'],
      b: 'A tropical stinkhorn with a lacy white "skirt" hanging from its cap. It is eaten in Chinese cooking.',
      c: ['It is eaten in Chinese cooking.', 'Its cap is covered in smelly slime.', 'It grows in tropical forests.', 'It has a lacy net hanging down.', 'It looks like it is wearing a white veil.'] },
    { n: 'Bleeding tooth fungus', sci: 'Hydnellum peckii', g: 'tooth fungus', f: f(I, NH), d: 3,
      b: 'A white fungus that oozes drops of bright red liquid, like strawberry jam or blood.',
      c: ['It is nicknamed "strawberries and cream".', 'It has spines instead of gills.', 'It is too bitter to eat.', 'It oozes red drops.', 'It looks as if it is bleeding.'] },
    { n: 'Indigo milk cap', sci: 'Lactarius indigo', g: 'milk cap', f: f(E, NA), d: 3,
      b: 'A rare bright blue mushroom that oozes blue "milk" when cut. It is sold in markets in Mexico.',
      c: ['It is sold in Mexican markets.', 'It oozes blue liquid when cut.', 'It turns green where bruised.', 'It is one of very few blue mushrooms.', 'It is a deep blue colour.'] },
    { n: 'Paddy straw mushroom', alt: ['straw mushroom'], sci: 'Volvariella volvacea', g: 'volvariella', f: f(E, AS), d: 3, look: ['Death cap'],
      b: 'A mushroom grown on rice straw in Asia. Young ones look dangerously like death caps.',
      c: ['Immigrants have been poisoned mistaking death caps for it.', 'It is grown on rice straw.', 'Young ones are egg-shaped.', 'It is used in Asian cooking.', 'It is grown in rice fields.'] },
  ],
  fakes: ['Silver bell cap', 'Crimson moon puffball', 'Golden widow\'s veil', 'Northern glass morel', 'Spotted thunder bolete', 'Velvet ghost chanterelle'],
  questions: [
    { kind: 'tf', prompt: 'A mushroom is a kind of plant.', answer: false, explain: 'Fungi are a separate kingdom; they cannot make food from sunlight.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which mushroom causes the most deaths from mushroom poisoning?', answer: 'Death cap', wrong: ['Fly agaric', 'Button mushroom', 'Giant puffball'], explain: 'Its toxins destroy the liver, and cooking does not remove them.', difficulty: 1 },
    { kind: 'tf', prompt: 'Cooking a death cap makes it safe to eat.', answer: false, explain: 'Its amatoxins are not destroyed by heat.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which red mushroom with white spots appears in fairy tales and "Super Mario"?', answer: 'Fly agaric', wrong: ['Death cap', 'Chanterelle', 'Shiitake'], explain: 'It is poisonous despite its friendly look.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do mushrooms release to make new fungi?', answer: 'Spores', wrong: ['Seeds', 'Eggs', 'Pollen'], explain: 'Spores are tiny and spread by wind, water and animals.', difficulty: 1 },
    { kind: 'mc', prompt: 'Portobello, chestnut and white button mushrooms are all…', answer: 'The same species', wrong: ['Different poisonous species', 'Kinds of truffle', 'Grown on trees'], explain: 'They are ages and strains of Agaricus bisporus.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which antibiotic was first discovered in a mould, a kind of fungus?', answer: 'Penicillin', wrong: ['Aspirin', 'Insulin', 'Paracetamol'], explain: 'Alexander Fleming noticed it in 1928.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which fungus helps bread dough rise?', answer: 'Yeast', wrong: ['Mould', 'Mushroom spores', 'Lichen'], explain: 'Yeast gives off carbon dioxide bubbles.', difficulty: 1 },
    { kind: 'mc', prompt: 'One of the largest living things on Earth is a honey fungus in which US state?', answer: 'Oregon', wrong: ['Texas', 'Florida', 'Alaska'], explain: 'It spreads underground across nearly 10 square kilometres.', difficulty: 3 },
    { kind: 'tf', prompt: 'Some mushrooms glow in the dark.', answer: true, explain: 'Ghost fungus and jack-o\'-lantern mushrooms are bioluminescent.', difficulty: 1 },
    { kind: 'tf', prompt: 'You should never eat a wild mushroom unless an expert says it is safe.', answer: true, explain: 'Deadly mushrooms can look like edible ones.', difficulty: 1 },
    { kind: 'mc', prompt: 'Where do mushrooms often grow?', answer: 'On damp ground and rotting wood', wrong: ['On hot sand', 'In the sea', 'On clouds'], explain: 'Most fungi like damp, shady places.', difficulty: 1 },
    { kind: 'tf', prompt: 'Mushrooms need sunlight to make their food.', answer: false, explain: 'Unlike plants, fungi feed on dead or living material.', difficulty: 1 },
  ],
};
