import { INAT, WD, COMMONS, STATUS_META, len } from './_common.mjs';

const AU = 'Australia', AF = 'Africa', AS = 'Asia', EU = 'Europe', NA = 'North America', SA = 'South America', AM = 'the Americas', NZ = 'New Zealand', GA = 'the Galápagos Islands';
const RE = 'Reptile', AMP = 'Amphibian';
// venomous: null = left out (venom glands or skin toxins too weak or disputed to call either way)
const f = (cls, region, lengthM, venomous = false) => ({ cls, region, lengthM, ...(venomous == null ? {} : { venomous }) });

export default {
  id: 'reptiles', title: 'Frogs & reptiles', theme: 'animals', icon: '🐸', kids: true,
  noun: 'frog or reptile', fakePrompt: 'Which of these frogs and reptiles is made up?',
  leakExempt: [],
  wikiD1: true, autoTaxo: ['family', 'genus'], status: true, audio: true, wdCheck: { lengthM: 'P2043' },
  ranges: { lengthM: [0.01, 7] },
  factsMeta: {
    cls: { type: 'cat', label: 'Group', values: [RE, AMP], clue: v => `It is an ${v === AMP ? 'amphibian' : 'reptile'}.`.replace('an reptile', 'a reptile') },
    region: { type: 'cat', label: 'Found in', clue: v => `It lives in ${v}.` },
    lengthM: len('Typical adult length'),
    venomous: { type: 'bool', label: 'Venomous or poisonous', yes: 'Venomous or poisonous', no: 'Harmless', clue: v => (v ? 'It is poisonous or venomous.' : null) },
    status: STATUS_META,
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which animal is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"cls": {"ask": "Is the {lname} a reptile or an amphibian?", "askReverse": "Which of these is an {lvalue}?", "stmt": "The {lname} is an {lvalue}."}, "region": {"ask": "Where does the {lname} live?", "askReverse": "Which of these lives in {value}?", "stmt": "The {lname} lives in {value}.", "exclusive": false}, "lengthM": {"askHigh": "Which of these grows the longest?", "askLow": "Which of these is the smallest?", "minRatio": 2}, "venomous": {"askBool": "Which of these is venomous or poisonous?", "stmt": "The {lname} is venomous or poisonous."}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD, COMMONS],
  items: [
    { n: 'Saltwater crocodile', alt: ['saltie', 'estuarine crocodile'], sci: 'Crocodylus porosus', g: 'crocodilian', f: f(RE, AU, 5), d: 1, look: ['Nile crocodile', 'American alligator', 'Gharial'],
      b: 'The biggest living reptile. It lives in rivers and coasts from India to northern Australia, and it can swim far out to sea.',
      c: ['It can swim hundreds of kilometres across the open sea.', 'Its bite is one of the strongest ever measured.', 'Large males can be over 6 metres long.', 'It is common in northern Australian rivers.', 'It is the biggest living reptile.'] },
    { n: 'Nile crocodile', sci: 'Crocodylus niloticus', g: 'crocodilian', f: f(RE, AF, 4.5), d: 2, look: ['Saltwater crocodile'],
      b: 'Africa\'s biggest crocodile. It ambushes zebras and wildebeest as they cross rivers.',
      c: ['Ancient Egyptians worshipped a crocodile god called Sobek.', 'Mothers carry their babies in their mouths.', 'It ambushes wildebeest crossing rivers.', 'It is the largest crocodile in Africa.', 'It is named after the world\'s longest river.'] },
    { n: 'American alligator', alt: ['alligator', 'gator'], sci: 'Alligator mississippiensis', g: 'crocodilian', f: f(RE, NA, 3.5), d: 1, look: ['Saltwater crocodile'],
      b: 'A big reptile of the swamps of the south-eastern USA. It has a wide, rounded snout, unlike a crocodile\'s pointed one.',
      c: ['The temperature of the nest decides if babies are male or female.', 'It can live in freshwater swamps.', 'It is common in Florida and Louisiana.', 'Its snout is wide and U-shaped.', 'It is found in the swamps of the USA.'] },
    { n: 'Gharial', alt: ['gavial'], sci: 'Gavialis gangeticus', g: 'crocodilian', f: f(RE, AS, 4.5), d: 2, look: ['Saltwater crocodile'],
      b: 'A crocodilian of Indian rivers with a very long, thin snout for catching fish.',
      c: ['Males have a pot-shaped lump on the snout tip.', 'It eats mostly fish.', 'It is critically endangered.', 'It lives in rivers of India and Nepal.', 'Its snout is very long and thin.'] },
    { n: 'Komodo dragon', sci: 'Varanus komodoensis', g: 'monitor', f: f(RE, AS, 2.6, true), d: 1, look: ['Lace monitor', 'Perentie'],
      b: 'The biggest lizard in the world, from a few Indonesian islands. It has a venomous bite.',
      c: ['Females can lay eggs without a male.', 'It can eat 80% of its body weight in one meal.', 'Its bite contains venom.', 'It lives on a few Indonesian islands.', 'It is the biggest lizard in the world.'] },
    { n: 'Lace monitor', alt: ['goanna', 'tree goanna'], sci: 'Varanus varius', g: 'monitor', f: f(RE, AU, 1.7, true), d: 2, look: ['Perentie', 'Komodo dragon'],
      b: 'A big goanna of eastern Australia that climbs trees and raids picnic grounds and bird nests.',
      c: ['It lays its eggs inside termite mounds.', 'It raids picnic grounds for food.', 'It climbs trees easily.', 'It is the second-largest lizard in Australia.', 'It is a kind of goanna.'] },
    { n: 'Perentie', sci: 'Varanus giganteus', g: 'monitor', f: f(RE, AU, 2, null), d: 2, look: ['Lace monitor', 'Komodo dragon'],
      b: 'Australia\'s biggest lizard, a goanna of the desert. It stands up on its back legs to look around.',
      c: ['Its species name means "gigantic".', 'It stands on its back legs to look around.', 'It lives in the red centre of Australia.', 'It is the largest lizard in Australia.', 'It is a desert goanna.'] },
    { n: 'Green iguana', alt: ['iguana'], sci: 'Iguana iguana', g: 'iguana', f: f(RE, AM, 1.5), d: 1, look: ['Marine iguana'],
      b: 'A big green lizard of Central and South American forests. It eats leaves and can drop from trees into water.',
      c: ['It has a "third eye" on top of its head that senses light.', 'It can drop its tail to escape.', 'It is invasive in Florida.', 'It has spines down its back.', 'It is a big green lizard.'] },
    { n: 'Marine iguana', sci: 'Amblyrhynchus cristatus', g: 'iguana', f: f(RE, GA, 1), d: 2, look: ['Green iguana'],
      b: 'The only lizard that feeds in the sea. It dives for seaweed off the Galápagos Islands and sneezes out salt.',
      c: ['Darwin called it an "imp of darkness".', 'It can shrink its body when food is short.', 'It sneezes out salt.', 'It dives for seaweed.', 'It is the only lizard that feeds in the sea.'] },
    { n: 'Frill-necked lizard', alt: ['frilled lizard', 'frilled dragon'], sci: 'Chlamydosaurus kingii', g: 'dragon', f: f(RE, AU, 0.85), d: 1,
      b: 'An Australian lizard that opens a huge frill around its neck to scare enemies, then runs away on its back legs.',
      c: ['It was on the Australian two-cent coin.', 'It runs away on its back legs.', 'It hisses with its mouth wide open.', 'It lives in northern Australia.', 'It opens a big frill around its neck.'] },
    { n: 'Thorny devil', alt: ['thorny dragon', 'moloch'], sci: 'Moloch horridus', g: 'dragon', f: f(RE, AU, 0.2), d: 1,
      b: 'A spiky desert lizard of Australia. It drinks by soaking up water through grooves in its skin.',
      c: ['It drinks through grooves in its skin.', 'It eats thousands of ants a day.', 'It has a false head on its neck.', 'It lives in Australian deserts.', 'It is covered in sharp spikes.'] },
    { n: 'Eastern blue-tongued lizard', alt: ['blue-tongued skink', 'bluey', 'blue-tongue'], sci: 'Tiliqua scincoides', g: 'skink', f: f(RE, AU, 0.5), d: 1,
      b: 'A big, slow Australian skink that sticks out its bright blue tongue to scare enemies. It eats snails in gardens.',
      c: ['It gives birth to live young.', 'It eats snails in gardens.', 'It has short legs and a fat tail.', 'It is a common garden lizard in Australia.', 'It sticks out a bright blue tongue.'] },
    { n: 'Central bearded dragon', alt: ['bearded dragon', 'beardie'], sci: 'Pogona vitticeps', g: 'dragon', f: f(RE, AU, 0.5), d: 1,
      b: 'A spiky Australian lizard that puffs out a dark "beard" when scared. It is a very popular pet.',
      c: ['It waves its arm to show it is not a threat.', 'It turns its throat black when stressed.', 'It is one of the most popular pet lizards.', 'It lives in inland Australia.', 'It has a spiky beard under its chin.'] },
    { n: 'Gila monster', sci: 'Heloderma suspectum', g: 'beaded lizard', f: f(RE, NA, 0.5, true), d: 2,
      b: 'A venomous lizard of the south-western USA and Mexico with beaded pink-and-black skin. Its venom led to a diabetes drug.',
      c: ['A diabetes and weight-loss drug came from its saliva.', 'It stores fat in its tail.', 'It is one of very few venomous lizards.', 'Its skin is beaded black and pink.', 'It is named after a river in Arizona.'] },
    { n: 'Panther chameleon', alt: ['chameleon'], sci: 'Furcifer pardalis', g: 'chameleon', f: f(RE, AF, 0.4), d: 1, look: ['Veiled chameleon'],
      b: 'A colourful chameleon from Madagascar. It changes colour and catches insects with a super-fast tongue.',
      c: ['Its tongue can be longer than its body.', 'Its eyes move separately.', 'It lives on Madagascar.', 'It grips branches with its tail.', 'It changes colour.'] },
    { n: 'Veiled chameleon', sci: 'Chamaeleo calyptratus', g: 'chameleon', f: f(RE, AS, 0.45), d: 3, look: ['Panther chameleon'],
      b: 'A chameleon from Yemen and Saudi Arabia with a tall casque on its head that helps it collect water.',
      c: ['It comes from Yemen and Saudi Arabia.', 'Its tall casque funnels water to its mouth.', 'Its eyes swivel separately.', 'It has a tall helmet on its head.', 'It is a kind of chameleon.'] },
    { n: 'Leopard gecko', sci: 'Eublepharis macularius', g: 'gecko', f: f(RE, AS, 0.2), d: 2, look: ['Tokay gecko'],
      b: 'A spotted, gentle gecko from deserts of Pakistan and India. Unlike most geckos, it has eyelids and cannot climb glass.',
      c: ['It has eyelids, unlike most geckos.', 'It cannot climb glass.', 'It stores fat in its thick tail.', 'It is a popular pet.', 'It has spots like a big cat.'] },
    { n: 'Tokay gecko', sci: 'Gekko gecko', g: 'gecko', f: f(RE, AS, 0.3), d: 2, look: ['Leopard gecko'],
      b: 'A big, blue-grey gecko with orange spots. Its loud "to-kay" call gives it its name.',
      c: ['It licks its eyes clean.', 'Its toe pads stick to walls with tiny hairs.', 'It bites hard.', 'It is blue-grey with orange spots.', 'Its name comes from its loud call.'] },
    { n: 'Galápagos tortoise', alt: ['giant tortoise', 'Galapagos giant tortoise'], sci: 'Chelonoidis niger', g: 'tortoise', f: f(RE, GA, 1.5), d: 1, look: ['Alligator snapping turtle'],
      b: 'A giant tortoise from the Galápagos Islands. It can live for over 100 years.',
      c: ['Lonesome George was the last of his kind.', 'Its shell shape differs from island to island.', 'It can live for over 100 years.', 'It can go a year without food or water.', 'It is a huge tortoise from islands off Ecuador.'] },
    { n: 'Alligator snapping turtle', sci: 'Macrochelys temminckii', g: 'turtle', f: f(RE, NA, 0.7), d: 2,
      b: 'A huge freshwater turtle of the USA. It lures fish with a worm-like pink tongue.',
      c: ['Its tongue has a pink worm-shaped lure.', 'It sits still with its mouth open.', 'It is one of the heaviest freshwater turtles.', 'It has a spiky shell and a hooked beak.', 'It has a powerful snapping bite.'] },
    { n: 'Tuatara', sci: 'Sphenodon punctatus', g: 'tuatara', f: f(RE, NZ, 0.6), d: 2,
      b: 'A lizard-like reptile from New Zealand. It is the last survivor of a group that lived with the dinosaurs.',
      c: ['It has a "third eye" on top of its head.', 'It can live for over 100 years.', 'It is the last of an ancient group.', 'It looks like a lizard but is not one.', 'It lives only in New Zealand.'] },
    { n: 'Axolotl', sci: 'Ambystoma mexicanum', g: 'salamander', f: f(AMP, NA, 0.25), d: 1,
      b: 'A Mexican salamander that keeps its feathery gills and stays in the water all its life. It can regrow lost legs.',
      c: ['It can regrow legs, tail and even parts of its heart.', 'It is almost extinct in the wild.', 'It lives only in lakes near Mexico City.', 'It has feathery gills on its head.', 'It seems to smile.'] },
    { n: 'Golden poison frog', alt: ['poison dart frog', 'golden poison dart frog'], sci: 'Phyllobates terribilis', g: 'frog', f: f(AMP, SA, 0.05, true), d: 1, look: ['Strawberry poison frog'],
      b: 'A tiny bright yellow frog from Colombia. It is one of the most poisonous animals on Earth.',
      c: ['Hunters rubbed blow darts on its skin.', 'One frog has enough poison to kill several people.', 'Pet ones are not poisonous because of their diet.', 'It lives in the rainforests of Colombia.', 'It is bright yellow and very poisonous.'] },
    { n: 'Strawberry poison frog', alt: ['strawberry poison-dart frog'], sci: 'Oophaga pumilio', g: 'frog', f: f(AMP, AM, 0.02, true), d: 2, look: ['Golden poison frog'],
      b: 'A tiny red frog with blue legs from Central America. Mothers carry their tadpoles up trees and feed them eggs.',
      c: ['Mothers feed their tadpoles unfertilised eggs.', 'It carries tadpoles up into trees.', 'Its bright colour warns that it is poisonous.', 'It is red with blue legs.', 'It is named after a red fruit.'] },
    { n: 'Red-eyed tree frog', sci: 'Agalychnis callidryas', g: 'frog', f: f(AMP, AM, 0.06), d: 1,
      b: 'A bright green tree frog with huge red eyes. It flashes its eyes to startle predators.',
      c: ['Its eggs can hatch early if a snake attacks them.', 'It flashes its eyes to startle predators.', 'It has orange feet and blue sides.', 'It lives in Central American rainforests.', 'It has huge red eyes.'] },
    { n: 'Cane toad', alt: ['giant toad'], sci: 'Rhinella marina', g: 'toad', f: f(AMP, SA, 0.15, true), d: 1, look: ['Common toad'],
      b: 'A big, poisonous toad from the Americas. It was brought to Australia in 1935 to eat beetles and became a pest.',
      c: ['It was released in Queensland in 1935.', 'It did not even eat the cane beetles it was meant to.', 'Glands behind its eyes ooze poison.', 'It is a major pest in Australia.', 'It is named after a sugar crop.'] },
    { n: 'Australian green tree frog', alt: ['green tree frog', 'White\'s tree frog', 'dumpy tree frog'], sci: 'Ranoidea caerulea', inat: 'Litoria caerulea', g: 'frog', f: f(AMP, AU, 0.1), d: 1, look: ['Red-eyed tree frog'],
      b: 'A plump, friendly green frog of Australia that often lives in bathrooms, water tanks and drainpipes.',
      c: ['Its skin makes a substance studied for medicine.', 'It often lives in toilets and drainpipes.', 'It has big sticky toe pads.', 'It is plump and smiles.', 'It is a green frog that climbs.'] },
    { n: 'Southern corroboree frog', files: ['Southern Corroboree frog.jpg', 'CorroboreeFrog.jpg'], alt: ['corroboree frog'], sci: 'Pseudophryne corroboree', g: 'frog', f: f(AMP, AU, 0.03, true), d: 3,
      b: 'A tiny, critically endangered frog of the Snowy Mountains with bright yellow and black stripes.',
      c: ['It makes its own poison, unlike poison dart frogs.', 'It lives in alpine bogs.', 'It is critically endangered.', 'It lives in the Snowy Mountains.', 'It is striped yellow and black.'] },
    { n: 'American bullfrog', alt: ['bullfrog'], sci: 'Lithobates catesbeianus', g: 'frog', f: f(AMP, NA, 0.15), d: 2, look: ['Common frog'],
      b: 'A huge North American frog with a deep call like a cow mooing. It eats almost anything it can swallow.',
      c: ['It eats snakes, birds and other frogs.', 'Its tadpoles can take two years to change.', 'It is invasive in many countries.', 'Its call sounds like a cow mooing.', 'It is the largest frog in North America.'] },
    { n: 'Common frog', alt: ['European common frog', 'grass frog', 'frog'], sci: 'Rana temporaria', g: 'frog', f: f(AMP, EU, 0.08), d: 1, look: ['Common toad', 'American bullfrog'],
      b: 'The common frog of European ponds. It lays big clumps of frogspawn in early spring.',
      c: ['It can breathe through its skin while it rests in pond mud in winter.', 'It lays clumps of spawn in early spring.', 'It has a dark patch behind each eye.', 'It hops with long back legs.', 'It is the frog of European garden ponds.'] },
    { n: 'Common toad', alt: ['European toad', 'toad'], sci: 'Bufo bufo', g: 'toad', f: f(AMP, EU, 0.1, true), d: 1, look: ['Common frog', 'Cane toad'],
      b: 'A warty brown toad of Europe. Every spring, toads migrate back to the ponds where they hatched.',
      c: ['Volunteers help them cross roads in spring.', 'It lays its eggs in long strings.', 'It walks more than it hops.', 'Its skin is dry and warty.', 'It is the common toad of Europe.'] },
    { n: 'Glass frog', alt: ['reticulated glass frog'], sci: 'Hyalinobatrachium valerioi', g: 'frog', f: f(AMP, AM, 0.025), d: 2,
      b: 'A tiny frog with see-through skin on its belly. You can see its heart beating.',
      c: ['Fathers guard the eggs on leaves.', 'It lives in Central American rainforests.', 'Its eggs are laid over streams.', 'You can see its heart beating.', 'Its belly skin is see-through.'] },
    { n: 'Goliath frog', wikiFirst: true, sci: 'Conraua goliath', g: 'frog', f: f(AMP, AF, 0.3), d: 2,
      b: 'The biggest frog in the world, from West Africa. It can weigh over 3 kg.',
      c: ['It moves heavy rocks to build ponds for its eggs.', 'It has no vocal sac, so it does not croak.', 'It lives in Cameroon.', 'It can weigh over 3 kg.', 'It is the biggest frog in the world.'] },
    { n: 'Fire salamander', sci: 'Salamandra salamandra', g: 'salamander', f: f(AMP, EU, 0.2, true), d: 2, look: ['Great crested newt'],
      b: 'A black-and-yellow salamander of European forests. Its skin oozes poison.',
      c: ['People once thought it could walk through fire.', 'It gives birth to larvae in streams.', 'Its skin oozes toxins.', 'It lives in damp European forests.', 'It is black with yellow spots.'] },
    { n: 'Great crested newt', wikiFirst: true, sci: 'Triturus cristatus', g: 'newt', f: f(AMP, EU, 0.15, null), d: 3, look: ['Fire salamander'],
      b: 'A big dark newt of Europe. In spring, males grow a jagged crest along their backs.',
      c: ['It is protected by law in Britain.', 'Its belly is orange with black spots.', 'Females fold each egg into a leaf.', 'It has warty dark skin.', 'Males grow a jagged crest in spring.'] },
    { n: 'Pacman frog', alt: ['Argentine horned frog', 'horned frog'], sci: 'Ceratophrys ornata', g: 'frog', f: f(AMP, SA, 0.12), d: 2,
      b: 'A round frog with a huge mouth from South America. It will try to eat almost anything that moves past it.',
      c: ['It has small horn-like points above its eyes.', 'It buries itself and ambushes prey.', 'It comes from Argentina.', 'Its mouth is almost as wide as its body.', 'It is named after a video game character.'] },
  ],
  fakes: ['Crimson-backed water dragon toad', 'Golden marsh tuatara', 'Northern glass gecko-frog', 'Spotted thunder iguana', 'Blue-horned river skink', 'Desert velvet crocodile'],
  questions: [
    { kind: 'mc', prompt: 'What does a tadpole grow into?', answer: 'A frog', wrong: ['A fish', 'A lizard', 'A snake'], explain: 'Tadpoles are baby frogs and toads that live in water.', difficulty: 1 },
    { kind: 'order', prompt: 'Put a frog\'s life cycle in order.', answer: ['Frogspawn', 'Tadpole', 'Froglet', 'Frog'], orderLabel: 'First to last', explain: 'Tadpoles grow legs and absorb their tails.', difficulty: 1 },
    { kind: 'mc', prompt: 'How can you tell an alligator from a crocodile?', answer: 'An alligator has a wide, U-shaped snout', wrong: ['An alligator has wings', 'An alligator has no teeth', 'An alligator is always smaller'], explain: 'Crocodiles have narrower, V-shaped snouts and show more teeth.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is the biggest living reptile?', answer: 'Saltwater crocodile', wrong: ['Komodo dragon', 'Galápagos tortoise', 'Green anaconda'], explain: 'Big males can exceed 6 m and 1,000 kg.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the biggest lizard?', answer: 'Komodo dragon', wrong: ['Green iguana', 'Perentie', 'Gila monster'], explain: 'Komodo dragons can be about 3 m long.', difficulty: 1 },
    { kind: 'tf', prompt: 'A frog is a reptile.', answer: false, explain: 'Frogs are amphibians; they start life in water.', difficulty: 1 },
    { kind: 'tf', prompt: 'Chameleons can move each eye on its own.', answer: true, explain: 'They can look in two directions at once.', difficulty: 1 },
    { kind: 'mc', prompt: 'Why were cane toads brought to Australia in 1935?', answer: 'To eat beetles on sugar cane', wrong: ['As pets', 'For food', 'To eat mosquitoes'], explain: 'It failed, and the toads spread across northern Australia.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which animal can regrow its legs, tail and even parts of its heart?', answer: 'Axolotl', wrong: ['Tuatara', 'Cane toad', 'Gharial'], explain: 'Axolotls are famous for regeneration.', difficulty: 2 },
    { kind: 'mc', prompt: 'What decides whether baby alligators are male or female?', answer: 'The temperature of the nest', wrong: ['The size of the egg', 'The month they hatch', 'The colour of the mother'], explain: 'Warmer and cooler nests produce different sexes.', difficulty: 3 },
    { kind: 'mc', prompt: 'Which famous tortoise was the last of his kind on Pinta Island?', answer: 'Lonesome George', wrong: ['Harriet', 'Jonathan', 'Speedy'], explain: 'He died in 2012.', difficulty: 3 },
  ],
};
