import { INAT, WD, COMMONS, STATUS_META, len } from './_common.mjs';

const MA = 'Mammal', FI = 'Fish', RE = 'Reptile', MO = 'Mollusc', CR = 'Crustacean', EC = 'Echinoderm', CN = 'Cnidarian', AR = 'Chelicerate';
const f = (kind, lengthM) => ({ kind, breathesAir: kind === MA || kind === RE, ...(lengthM != null ? { lengthM } : {}) });

export default {
  id: 'sea', title: 'Sea creatures', theme: 'animals', icon: '🐋', kids: true,
  leakExempt: [],
  wikiD1: true, autoTaxo: ['family', 'genus'], status: true, audio: true, wdCheck: { lengthM: 'P2043' },
  ranges: { lengthM: [0.02, 35] },
  factsMeta: {
    kind: { type: 'cat', label: 'Kind of animal', values: [MA, FI, RE, MO, CR, EC, CN, AR], clue: v => `It is a ${v.toLowerCase()}.` },
    breathesAir: { type: 'bool', label: 'Breathes air', yes: 'Breathes air', no: 'Breathes underwater', clue: v => (v ? 'It must come to the surface to breathe air.' : null) },
    lengthM: len(),
    status: STATUS_META,
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which sea creature is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"kind": {"ask": "What kind of animal is the {lname}?", "askReverse": "Which of these is {aValue}?", "stmt": "The {lname} is {aValue}."}, "breathesAir": {"askBool": "Which of these sea creatures breathes air?", "stmt": "The {lname} has to come to the surface to breathe air."}, "lengthM": {"askHigh": "Which of these grows the longest?", "askLow": "Which of these is the smallest?", "minRatio": 2}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD, COMMONS],
  items: [
    { n: 'Blue whale', sci: 'Balaenoptera musculus', g: 'whale', f: f(MA, 25), d: 1, look: ['Humpback whale', 'Sperm whale'],
      b: 'The biggest animal that has ever lived. It eats tiny shrimp-like krill, up to several tonnes a day.',
      c: ['Its heart is about the size of a small car.', 'It can eat about 4 tonnes of krill a day.', 'Its calls are among the loudest of any animal.', 'It filters food through plates called baleen.', 'It is the biggest animal ever.'] },
    { n: 'Humpback whale', sci: 'Megaptera novaeangliae', g: 'whale', f: f(MA, 14), d: 1, look: ['Blue whale'],
      b: 'A big whale famous for its songs and for leaping out of the water. It has very long flippers.',
      c: ['Its flippers can be a third of its body length.', 'Males sing long, complex songs.', 'Groups trap fish in nets of bubbles.', 'It often leaps right out of the water.', 'Its name describes the shape of its back when it dives.'] },
    { n: 'Orca', alt: ['killer whale'], sci: 'Orcinus orca', g: 'dolphin', f: f(MA, 7), d: 1, look: ['Bottlenose dolphin'],
      b: 'The biggest member of the dolphin family. Orcas live in family pods and hunt seals, fish and even whales.',
      c: ['Some families hunt by making waves to wash seals off ice.', 'Pods have their own "dialects" of calls.', 'Males have a very tall dorsal fin.', 'It is black and white.', 'It is also called the killer whale.'] },
    { n: 'Sperm whale', sci: 'Physeter macrocephalus', g: 'whale', f: f(MA, 16), d: 1, look: ['Blue whale'],
      b: 'The biggest toothed animal, with a huge square head. It dives deeper than a kilometre to hunt giant squid.',
      c: ['It has the largest brain of any animal.', 'Moby-Dick is a white one.', 'It dives over a kilometre deep.', 'It hunts giant squid.', 'It has a huge, square head.'] },
    { n: 'Common bottlenose dolphin', alt: ['bottlenose dolphin', 'dolphin'], sci: 'Tursiops truncatus', g: 'dolphin', f: f(MA, 3), d: 1, look: ['Orca'],
      b: 'A clever, playful dolphin found in warm seas around the world. Each dolphin has its own signature whistle, like a name.',
      c: ['Each one has a signature whistle, like a name.', 'Some use sponges to protect their noses while hunting.', 'It sleeps with half its brain at a time.', 'It finds food using echolocation.', 'It is a grey, smiling-looking sea mammal.'] },
    { n: 'Beluga', alt: ['beluga whale', 'white whale'], sci: 'Delphinapterus leucas', g: 'whale', f: f(MA, 4.5), d: 1, look: ['Narwhal'],
      b: 'A white Arctic whale nicknamed the "sea canary" because of its chirps and whistles.',
      c: ['It can turn its head, unlike most whales.', 'Its forehead bulge is called a melon.', 'It is nicknamed the "sea canary".', 'It lives in Arctic seas.', 'It is all white.'] },
    { n: 'Narwhal', sci: 'Monodon monoceros', g: 'whale', f: f(MA, 4.5), d: 1, look: ['Beluga'],
      b: 'An Arctic whale whose males have a long spiral tusk. Its tusk is really a tooth.',
      c: ['Its tusks were once sold as unicorn horns.', 'The tusk is a tooth that can grow 3 metres long.', 'It is a close relative of the beluga.', 'It lives in Arctic waters.', 'It has a long spiral tusk.'] },
    { n: 'Dugong', alt: ['sea cow'], sci: 'Dugong dugon', g: 'sea cow', f: f(MA, 3), d: 2, look: ['West Indian manatee'],
      b: 'A gentle sea mammal that grazes on seagrass. Australia has the world\'s biggest population.',
      c: ['Sailors may have mistaken it for mermaids.', 'Australia has most of the world\'s population.', 'Its closest relatives on land are elephants.', 'Its tail is shaped like a dolphin\'s.', 'It grazes on seagrass.'] },
    { n: 'West Indian manatee', alt: ['manatee', 'sea cow'], sci: 'Trichechus manatus', g: 'sea cow', f: f(MA, 3.2), d: 1, look: ['Dugong'],
      b: 'A big, slow sea mammal that eats water plants. It has a round, paddle-shaped tail.',
      c: ['It is related to elephants.', 'Boat propellers are a big danger to it.', 'It gathers at warm springs in Florida in winter.', 'Its tail is shaped like a paddle.', 'It is a gentle, slow "sea cow".'] },
    { n: 'Walrus', sci: 'Odobenus rosmarus', g: 'seal', f: f(MA, 3), d: 1,
      b: 'A huge Arctic sea mammal with long tusks and whiskers. It uses its tusks to haul itself onto ice.',
      c: ['Its scientific name means "tooth-walking".', 'It finds clams with its sensitive whiskers.', 'It uses its tusks to pull itself onto ice.', 'Both males and females have tusks.', 'It has long tusks and lives in the Arctic.'] },
    { n: 'Harbour seal', alt: ['common seal', 'harbor seal', 'seal'], sci: 'Phoca vitulina', g: 'seal', f: f(MA, 1.6), d: 1, look: ['California sea lion'],
      b: 'A spotted seal of northern coasts that rests on sandbanks and rocks. It wriggles on its belly on land.',
      c: ['It has no ear flaps, only small holes.', 'It moves on land by wriggling on its belly.', 'It often rests in a "banana" pose.', 'It lives on northern coasts.', 'It is a spotted grey seal.'] },
    { n: 'Leopard seal', sci: 'Hydrurga leptonyx', g: 'seal', f: f(MA, 3), d: 2,
      b: 'A big spotted Antarctic seal and a fierce hunter of penguins.',
      c: ['It has a huge mouth with sharp teeth.', 'It lives around Antarctica.', 'It hunts penguins and other seals.', 'Its throat is covered in dark spots.', 'It is named after a spotted big cat.'] },
    { n: 'California sea lion', alt: ['sea lion'], sci: 'Zalophus californianus', g: 'seal', f: f(MA, 2), d: 1, look: ['Harbour seal'],
      b: 'A noisy, playful sea lion that barks loudly. Unlike seals, sea lions can walk on their flippers.',
      c: ['The US Navy trains them to find objects.', 'It barks loudly.', 'It has small ear flaps.', 'It can walk on all four flippers.', 'It is named after a US state and a big cat.'] },
    { n: 'Sea otter', sci: 'Enhydra lutris', g: 'weasel', f: f(MA, 1.3), d: 1,
      b: 'An otter that floats on its back and cracks shellfish with a rock. It has the thickest fur of any animal.',
      c: ['It has the thickest fur of any animal.', 'It holds hands with others while sleeping so it does not drift.', 'It keeps a favourite rock in a skin pouch.', 'It cracks shells on its chest.', 'It floats on its back in the sea.'] },
    { n: 'Green sea turtle', alt: ['green turtle'], sci: 'Chelonia mydas', g: 'turtle', f: f(RE, 1.1), d: 1, look: ['Loggerhead sea turtle', 'Hawksbill sea turtle'],
      b: 'A big sea turtle that eats seagrass and algae. It is named after the green colour of its fat.',
      c: ['Raine Island on the Great Barrier Reef is a huge nesting site.', 'Females return to the beach where they hatched.', 'Adults eat seagrass and algae.', 'Its name comes from the colour of its fat.', 'It is a big sea turtle.'] },
    { n: 'Leatherback sea turtle', alt: ['leatherback'], sci: 'Dermochelys coriacea', g: 'turtle', f: f(RE, 2), d: 2,
      b: 'The biggest turtle in the world. It has a leathery shell instead of a hard one and eats jellyfish.',
      c: ['It can dive over 1,000 metres deep.', 'It eats mainly jellyfish.', 'It can keep warm in cold water.', 'Its shell is leathery, not hard.', 'It is the largest turtle.'] },
    { n: 'Loggerhead sea turtle', alt: ['loggerhead'], sci: 'Caretta caretta', g: 'turtle', f: f(RE, 0.9), d: 2, look: ['Green sea turtle'],
      b: 'A sea turtle with a big head and strong jaws for crushing shellfish. Many nest in Florida and Queensland.',
      c: ['Many nest at Mon Repos in Queensland.', 'Hatchlings use the Earth\'s magnetic field to navigate.', 'It crushes crabs and clams.', 'Its shell is reddish-brown.', 'It has a very big head.'] },
    { n: 'Hawksbill sea turtle', alt: ['hawksbill'], sci: 'Eretmochelys imbricata', g: 'turtle', f: f(RE, 0.8), d: 2, look: ['Green sea turtle'],
      b: 'A coral-reef turtle with a sharp, bird-like beak. It eats sponges. Its shell was once used to make "tortoiseshell".',
      c: ['It eats sponges, some of them toxic.', 'Its shell was used for "tortoiseshell" combs.', 'It is critically endangered.', 'It lives on coral reefs.', 'Its beak is pointed like a bird of prey\'s.'] },
    { n: 'Giant Pacific octopus', sci: 'Enteroctopus dofleini', g: 'octopus', f: f(MO, 4), d: 2, look: ['Common octopus'],
      b: 'The biggest octopus in the world, with arms spanning several metres. It is very clever and can escape from tanks.',
      c: ['It has three hearts and blue blood.', 'It has escaped from aquarium tanks.', 'Its arms can span several metres.', 'It lives in the North Pacific.', 'It is the largest octopus.'] },
    { n: 'Common octopus', alt: ['octopus'], sci: 'Octopus vulgaris', g: 'octopus', f: f(MO, 1), d: 1, look: ['Giant Pacific octopus', 'Common cuttlefish'],
      b: 'A clever sea animal with eight arms, three hearts and blue blood. It can change colour in a flash.',
      c: ['It can taste with its suckers.', 'It squirts ink to escape.', 'It has three hearts and blue blood.', 'It can change colour and texture in a flash.', 'It has eight arms.'] },
    { n: 'Common cuttlefish', alt: ['cuttlefish'], sci: 'Sepia officinalis', g: 'cuttlefish', f: f(MO, 0.45), d: 2, look: ['Common octopus'],
      b: 'A relative of the octopus with eight arms, two tentacles and W-shaped pupils. It changes colour to talk and hide.',
      c: ['Its pupils are W-shaped.', 'Its internal shell is given to pet birds.', 'It flashes rippling colours.', 'Its ink was used to make sepia paint.', 'It is a squid-like animal with a frill of fin.'] },
    { n: 'Chambered nautilus', alt: ['nautilus'], sci: 'Nautilus pompilius', g: 'nautilus', f: f(MO, 0.2), d: 2,
      b: 'A shelled relative of the octopus that has barely changed in millions of years. It floats by adjusting gas in its shell.',
      c: ['It has about 90 tentacles with no suckers.', 'It controls gas in its shell chambers to float.', 'It is called a "living fossil".', 'Its shell is coiled and striped.', 'Jules Verne named a submarine after it.'] },
    { n: 'Ocellaris clownfish', alt: ['clownfish', 'anemonefish', 'Nemo'], sci: 'Amphiprion ocellaris', g: 'reef fish', f: f(FI, 0.1), d: 1,
      b: 'A small orange fish with white stripes that lives safely among the stinging tentacles of a sea anemone.',
      c: ['All are born male; the biggest becomes female.', 'A slimy coat stops anemones stinging it.', 'It lives in sea anemones.', 'It is orange with white stripes.', 'Nemo is one.'] },
    { n: 'Blue tang', alt: ['regal tang', 'palette surgeonfish', 'Dory'], sci: 'Paracanthurus hepatus', g: 'reef fish', f: f(FI, 0.25), d: 1,
      b: 'A bright blue reef fish with a yellow tail. It has sharp spines near its tail. Dory in "Finding Nemo" is one.',
      c: ['It has a sharp spine like a scalpel near its tail.', 'It hides in coral when scared.', 'It has a yellow tail.', 'Dory in "Finding Nemo" is one.', 'It is bright blue.'] },
    { n: 'Moorish idol', sci: 'Zanclus cornutus', g: 'reef fish', f: f(FI, 0.2), d: 2,
      b: 'A striking black, white and yellow reef fish with a long trailing fin. Gill in "Finding Nemo" is one.',
      c: ['It is the only member of its family.', 'It has a long snout.', 'A long white fin trails from its back.', 'It is banded black, white and yellow.', 'Gill in "Finding Nemo" is one.'] },
    { n: 'Reef manta ray', alt: ['manta ray', 'manta'], sci: 'Mobula alfredi', g: 'ray', f: f(FI, 3.5), d: 1,
      b: 'A huge, gentle ray that glides through the sea eating plankton. It has the biggest brain of any fish.',
      c: ['It has one of the biggest brains of any fish.', 'Divers swim with it at Lady Elliot Island.', 'It visits "cleaning stations" on reefs.', 'Its fins spread like wings.', 'It is a huge, gentle ray.'] },
    { n: 'Southern stingray', alt: ['stingray'], sci: 'Hypanus americanus', g: 'ray', f: f(FI, 1.5), d: 2,
      b: 'A flat, diamond-shaped ray of the western Atlantic that buries itself in sand. Its tail has a venomous spine.',
      c: ['Tourists feed them at Stingray City in the Cayman Islands.', 'It buries itself in sand.', 'Its mouth is on its underside.', 'Its tail has a venomous spine.', 'It is flat and diamond-shaped.'] },
    { n: 'Big-belly seahorse', alt: ['seahorse', 'pot-bellied seahorse'], sci: 'Hippocampus abdominalis', g: 'seahorse', f: f(FI, 0.3), d: 1, look: ['Leafy seadragon', 'Weedy seadragon'],
      b: 'One of the biggest seahorses, from Australia and New Zealand. As with all seahorses, the male gets pregnant.',
      c: ['The male carries the eggs in a pouch.', 'It grips seaweed with its curly tail.', 'It swims upright.', 'It is a kind of fish.', 'Its head looks like a horse\'s.'] },
    { n: 'Leafy seadragon', sci: 'Phycodurus eques', g: 'seahorse', f: f(FI, 0.3), d: 2, look: ['Weedy seadragon', 'Big-belly seahorse'],
      b: 'A relative of the seahorse from southern Australia, covered in leaf-like flaps that make it look like seaweed.',
      c: ['It is South Australia\'s marine emblem.', 'The male carries the eggs.', 'It drifts like floating seaweed.', 'It is covered in leaf-like flaps.', 'It is a seahorse relative named after a mythical beast.'] },
    { n: 'Weedy seadragon', alt: ['common seadragon'], sci: 'Phyllopteryx taeniolatus', g: 'seahorse', f: f(FI, 0.45), d: 3, look: ['Leafy seadragon'],
      b: 'A colourful seahorse relative of southern Australia with small leafy flaps. It is Victoria\'s marine emblem.',
      c: ['It is Victoria\'s marine emblem.', 'It has red, yellow and purple colours.', 'Males carry eggs on their tails.', 'It has fewer, smaller flaps than its leafy cousin.', 'It is a seahorse relative from southern Australia.'] },
    { n: 'Guineafowl puffer', wikiFirst: true, alt: ['pufferfish', 'puffer fish', 'blowfish'], sci: 'Arothron meleagris', g: 'pufferfish', f: f(FI, 0.4), d: 1,
      b: 'A spotted pufferfish of coral reefs. Like other puffers, it swallows water to blow up like a ball, and it is poisonous to eat.',
      c: ['Its flesh contains a deadly poison.', 'It can be black with white spots or bright yellow.', 'It eats coral tips with its beak-like teeth.', 'It is covered in white spots.', 'It blows itself up like a balloon.'] },
    { n: 'Ocean sunfish', alt: ['mola', 'sunfish'], sci: 'Mola mola', g: 'sunfish', f: f(FI, 1.8), d: 2,
      b: 'The heaviest bony fish in the world. It looks like a giant swimming head and lies flat at the surface to warm up.',
      c: ['It can lay 300 million eggs.', 'It has no proper tail.', 'It lies on its side at the surface to warm up.', 'It is the heaviest bony fish.', 'It looks like a huge swimming head.'] },
    { n: 'Swordfish', sci: 'Xiphias gladius', g: 'billfish', f: f(FI, 3), d: 1,
      b: 'A big, fast fish with a long, flat bill like a sword. It slashes at fish with its bill.',
      c: ['It has a special organ that warms its eyes and brain.', 'Its scientific name includes the word for a Roman sword.', 'Adults have no scales or teeth.', 'It slashes prey with its bill.', 'Its long, flat bill looks like a blade.'] },
    { n: 'Atlantic bluefin tuna', wikiFirst: true, alt: ['bluefin tuna', 'tuna'], sci: 'Thunnus thynnus', g: 'tuna', f: f(FI, 2.5), d: 2,
      b: 'A huge, fast, warm-bodied fish that crosses the Atlantic. One fish can sell for a fortune at Tokyo fish auctions.',
      c: ['One sold for over US$3 million at a Tokyo auction.', 'It can keep its body warmer than the water.', 'It crosses the Atlantic Ocean.', 'It is used for sushi.', 'It is a large, fast tuna.'] },
    { n: 'Great barracuda', alt: ['barracuda'], sci: 'Sphyraena barracuda', g: 'fish', f: f(FI, 1.5), d: 2,
      b: 'A long, silvery hunter with fang-like teeth. It is attracted to shiny things.',
      c: ['It is attracted to shiny objects.', 'It can burst to about 40 km/h.', 'It has a jutting lower jaw full of fangs.', 'It is long and silvery.', 'Its name starts with "barra".'] },
    { n: 'Green moray', alt: ['moray eel', 'moray'], sci: 'Gymnothorax funebris', g: 'eel', f: f(FI, 1.8), d: 2,
      b: 'A big eel that hides in reef crevices. Its skin is brown, but yellow slime makes it look green.',
      c: ['Its skin is brown; yellow mucus makes it look green.', 'It has a second set of jaws in its throat.', 'It opens and closes its mouth to breathe.', 'It hides in rock and coral holes.', 'It is a large reef eel.'] },
    { n: 'Bumphead parrotfish', alt: ['parrotfish'], sci: 'Bolbometopon muricatum', g: 'reef fish', f: f(FI, 1.3), d: 2,
      b: 'The biggest parrotfish, with a bump on its head. It crunches coral and poos out sand.',
      c: ['It rams coral with its head.', 'It turns coral into fine sand.', 'Schools sleep together on reefs.', 'It has a big bump on its forehead.', 'Its beak-like teeth look like a colourful bird\'s.'] },
    { n: 'Giant clam', sci: 'Tridacna gigas', g: 'clam', f: f(MO, 1.2), d: 2,
      b: 'The biggest shellfish in the world, weighing over 200 kg. Algae living in its colourful lips make food from sunlight.',
      c: ['Algae in its body make food from sunlight.', 'It cannot snap shut on divers, despite old stories.', 'It can live for over 100 years.', 'Its lips are bright blue or purple.', 'It is the biggest clam in the world.'] },
    { n: 'Ochre sea star', alt: ['starfish', 'sea star'], sci: 'Pisaster ochraceus', g: 'starfish', f: f(EC, 0.25), d: 1,
      b: 'A purple or orange starfish of the Pacific coast of North America. It eats mussels by pushing its stomach into their shells.',
      c: ['It pushes its stomach out to eat mussels.', 'It can regrow lost arms.', 'It has no brain and no blood.', 'It can be purple or orange.', 'It has five arms.'] },
    { n: 'Purple sea urchin', alt: ['sea urchin'], sci: 'Strongylocentrotus purpuratus', g: 'sea urchin', f: f(EC, 0.1), d: 2,
      b: 'A spiny purple ball that grazes on kelp. Without sea otters to eat them, urchins can destroy kelp forests.',
      c: ['Sea otters eat it.', 'Too many can wipe out kelp forests.', 'Its mouth is on its underside.', 'It is covered in spines.', 'It is purple and spiny.'] },
    { n: 'Magnificent sea anemone', alt: ['sea anemone'], sci: 'Heteractis magnifica', g: 'anemone', f: f(CN, 0.5), d: 2,
      b: 'A big sea anemone that clownfish live in. Its tentacles sting other fish.',
      c: ['It is related to jellyfish and coral.', 'It can slowly walk on its base.', 'Its tentacles sting small fish.', 'Clownfish live among its tentacles.', 'It looks like a flower but is an animal.'] },
    { n: 'Atlantic horseshoe crab', alt: ['horseshoe crab'], sci: 'Limulus polyphemus', g: 'horseshoe crab', f: f(AR, 0.6), d: 2,
      b: 'Not a true crab but a relative of spiders. Its blue blood is used to test medicines for germs.',
      c: ['It is more closely related to spiders than to crabs.', 'Its blue blood is used to test vaccines.', 'It has ten eyes.', 'It has existed for hundreds of millions of years.', 'Its shell is shaped like a lucky charm for a horse.'] },
    { n: 'American lobster', alt: ['lobster'], sci: 'Homarus americanus', g: 'lobster', f: f(CR, 0.5), d: 1,
      b: 'A big crustacean with two huge claws, one for crushing and one for cutting. It turns red only when cooked.',
      c: ['One claw crushes and the other cuts.', 'Very rarely, one is born bright blue.', 'It can live for over 100 years.', 'It is dark green-brown until cooked.', 'It turns red when cooked.'] },
    { n: 'Common hermit crab', alt: ['hermit crab'], sci: 'Pagurus bernhardus', g: 'crab', f: f(CR, 0.1), d: 1,
      b: 'A crab with a soft body that lives inside an empty snail shell. It moves to a bigger shell as it grows.',
      c: ['Sea anemones sometimes ride on its shell.', 'It queues to swap shells with others.', 'Its soft body curls into a spiral.', 'It moves to a bigger shell as it grows.', 'It lives inside an empty snail shell.'] },
    { n: 'Peacock mantis shrimp', alt: ['mantis shrimp'], sci: 'Odontodactylus scyllarus', g: 'mantis shrimp', f: f(CR, 0.15), d: 2,
      b: 'A colourful reef crustacean with one of the fastest punches in nature. Its club can crack aquarium glass.',
      c: ['Its eyes have up to 16 kinds of colour sensors.', 'Its punch can crack aquarium glass.', 'Its punch speeds up as fast as a bullet fired from a gun.', 'It is brightly coloured like a peacock.', 'It is a crustacean, not a mantis.'] },
    { n: 'Red king crab', alt: ['king crab'], sci: 'Paralithodes camtschaticus', g: 'crab', f: f(CR) /* 1.8 m is its leg span, not a length */, d: 2,
      b: 'A huge crab of cold northern seas, with legs spanning up to 1.8 metres. It is caught for food in the Bering Sea.',
      c: ['It was introduced to the Barents Sea by Soviet scientists.', 'Its legs can span 1.8 metres.', 'The TV show "Deadliest Catch" features its fishery.', 'It lives in cold northern seas.', 'It is a big red crab with a royal name.'] },
    { n: 'Spanish dancer', sci: 'Hexabranchus sanguineus', g: 'sea slug', f: f(MO, 0.4), d: 3,
      b: 'A big red sea slug that swims by flapping its body like a flamenco dancer\'s skirt.',
      c: ['It is a kind of nudibranch.', 'Its eggs form a pink rose-like ribbon.', 'It is one of the largest sea slugs.', 'It is bright red.', 'It swims like a twirling flamenco performer.'] },
    { n: 'Eastern blue groper', alt: ['blue groper'], sci: 'Achoerodus viridis', g: 'reef fish', f: f(FI, 1), d: 3,
      b: 'A big, friendly blue fish of the New South Wales coast. Females can change into males.',
      c: ['It is the state fish of New South Wales.', 'It starts life female and can become male.', 'Divers find it friendly and curious.', 'Males are bright blue.', 'It is a kind of wrasse.'] },
    { n: 'Flying fish', wikiFirst: true, alt: ['tropical two-wing flyingfish'], sci: 'Exocoetus volitans', g: 'fish', f: f(FI, 0.25), d: 2,
      b: 'A fish that leaps out of the sea and glides on wing-like fins to escape predators.',
      c: ['It can glide about 50 metres.', 'It beats its tail on the water to take off again.', 'It has huge, wing-like fins.', 'It escapes predators by leaving the water.', 'It glides through the air.'] },
    { n: 'Atlantic cod', alt: ['cod'], sci: 'Gadus morhua', g: 'fish', f: f(FI, 1), d: 2,
      b: 'A big fish of the North Atlantic that was fished so heavily that Canada closed its cod fishery in 1992.',
      c: ['Canada closed its Grand Banks fishery in 1992.', 'It has a whisker on its chin.', 'Its liver oil is a health supplement.', 'It is used for fish and chips.', 'It is a big fish of the North Atlantic.'] },
  ],
  fakes: ['Spotted glass whale', 'Crimson sea mole', 'Northern velvet dolphin', 'Golden ribbon turtle', 'Silver-finned sea badger', 'Striped coral otter'],
  questions: [
    { kind: 'mc', prompt: 'What is the biggest animal that has ever lived?', answer: 'Blue whale', wrong: ['Whale shark', 'Megalodon', 'Argentinosaurus'], explain: 'Blue whales can be about 30 m long and 150 tonnes or more.', difficulty: 1 },
    { kind: 'tf', prompt: 'A whale is a fish.', answer: false, explain: 'Whales are mammals that breathe air and feed their young milk.', difficulty: 1 },
    { kind: 'tf', prompt: 'A dolphin breathes air.', answer: true, explain: 'Dolphins breathe through a blowhole on top of their heads.', difficulty: 1 },
    { kind: 'number', prompt: 'How many hearts does an octopus have?', answer: 3, unit: 'hearts', tolerance: 0, explain: 'Two pump blood through the gills and one round the body.', difficulty: 2 },
    { kind: 'number', prompt: 'How many arms does an octopus have?', answer: 8, unit: 'arms', tolerance: 0, explain: '"Octo" means eight.', difficulty: 1 },
    { kind: 'mc', prompt: 'In seahorses, which parent gives birth?', answer: 'The father', wrong: ['The mother', 'Both parents', 'Neither; eggs hatch in seaweed'], explain: 'The female puts eggs into the male\'s pouch.', difficulty: 1 },
    { kind: 'mc', prompt: 'What kind of fish is Nemo?', answer: 'Clownfish', wrong: ['Blue tang', 'Pufferfish', 'Goldfish'], explain: 'Ocellaris clownfish live in sea anemones.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is a narwhal\'s tusk?', answer: 'A long tooth', wrong: ['A horn', 'A nose', 'A fin'], explain: 'It is a spiral canine tooth, usually on males.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which animal has the thickest fur of any animal?', answer: 'Sea otter', wrong: ['Polar bear', 'Walrus', 'Harbour seal'], explain: 'It has up to about a million hairs per square inch.', difficulty: 2 },
    { kind: 'mc', prompt: 'What colour is a lobster before it is cooked?', answer: 'Dark greenish-brown', wrong: ['Bright red', 'White', 'Yellow'], explain: 'Cooking breaks down a protein, revealing a red pigment.', difficulty: 2 },
    { kind: 'mc', prompt: 'What do blue whales mainly eat?', answer: 'Krill', wrong: ['Sharks', 'Seals', 'Seaweed'], explain: 'They filter tonnes of the small crustaceans each day.', difficulty: 1 },
    { kind: 'tf', prompt: 'A starfish is a fish.', answer: false, explain: 'Starfish, or sea stars, are echinoderms related to sea urchins.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which animal lives inside an empty snail shell?', answer: 'Hermit crab', wrong: ['Lobster', 'Seahorse', 'Octopus'], explain: 'It moves to bigger shells as it grows.', difficulty: 1 },
  ],
};
