import { INAT, WD, STATUS_META, len } from './_common.mjs';

const H = 'Harmless', B = 'Bites if provoked', D = 'Dangerous', X = 'Potentially deadly';
const OO = 'Open ocean', CO = 'Coasts', RF = 'Coral reefs', DS = 'Deep sea';
const f = (lengthM, danger, habitat) => ({ lengthM, danger, habitat });

export default {
  id: 'sharks', title: 'Sharks', theme: 'animals', icon: '🦈', kids: true,
  leakExempt: ['shark', 'sharks'],
  wikiD1: true, autoTaxo: ['family', 'genus'], status: true, wdCheck: { lengthM: 'P2043' },
  ranges: { lengthM: [0.15, 13] },
  factsMeta: {
    lengthM: len(),
    danger: { type: 'cat', label: 'Danger to people', values: [H, B, D, X], clue: v => ({ [H]: 'It is harmless to people.', [B]: 'It only bites people if provoked.', [D]: 'It has bitten people unprovoked.', [X]: 'It has killed people.' }[v]) },
    habitat: { type: 'cat', label: 'Lives in', clue: v => ({ [OO]: 'It lives in the open ocean.', [CO]: 'It lives in coastal waters.', [RF]: 'It lives around coral reefs.', [DS]: 'It lives in the deep sea.' }[v]) },
    status: STATUS_META,
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which shark is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"lengthM": {"askHigh": "Which of these sharks grows the longest?", "askLow": "Which of these sharks is the smallest?"}, "danger": {"ask": "How dangerous is the {lname} to people?", "askReverse": "Which of these sharks is rated \"{lvalue}\"?", "stmt": "The {lname} is rated \"{lvalue}\" to people."}, "habitat": {"ask": "Where does the {lname} mainly live?", "askReverse": "Which of these sharks mainly lives in {lvalue}?", "stmt": "The {lname} mainly lives in {lvalue}."}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD],
  items: [
    { n: 'Great white shark', alt: ['great white', 'white pointer', 'white shark'], sci: 'Carcharodon carcharias', g: 'mackerel shark', f: f(4.5, X, CO), d: 1, look: ['Shortfin mako', 'Sand tiger shark'],
      b: 'The biggest predatory fish in the sea. It hunts seals and sometimes leaps right out of the water.',
      c: ['It can sense the tiny electric fields of hidden animals.', 'Off South Africa it leaps clear of the water to catch seals.', 'It was the star of the film "Jaws".', 'It is responsible for more unprovoked bites on people than any other shark.', 'It is grey on top with a pale belly.'] },
    { n: 'Tiger shark', sci: 'Galeocerdo cuvier', g: 'requiem shark', f: f(4, X, CO), d: 1, look: ['Bull shark'],
      b: 'A big shark that eats almost anything, from turtles to tyres. Young ones have dark stripes.',
      c: ['Number plates and tyres have been found in their stomachs.', 'It eats sea turtles, cracking their shells.', 'It is second only to the great white for bites on people.', 'Its stripes fade as it grows older.', 'It is named after a striped big cat.'] },
    { n: 'Bull shark', sci: 'Carcharhinus leucas', g: 'requiem shark', f: f(2.4, X, CO), d: 1, look: ['Tiger shark'],
      b: 'A stocky shark that can live in fresh water as well as the sea. It swims far up rivers like the Amazon and Mississippi.',
      c: ['It has been found thousands of kilometres up the Amazon.', 'It lives in a lake in Nicaragua.', 'It can live in both salt water and fresh water.', 'It is stocky with a short, blunt snout.', 'It is named after a male cow.'] },
    { n: 'Oceanic whitetip shark', sci: 'Carcharhinus longimanus', g: 'requiem shark', f: f(3, X, OO), d: 2,
      b: 'A bold shark of the open ocean with long, rounded, white-tipped fins. It is now critically endangered.',
      c: ['It was blamed for many deaths after ships sank in World War II.', 'Its fins are hugely valued for shark-fin soup.', 'Its pectoral fins are long and rounded.', 'It lives far out in the open ocean.', 'Its fins have pale tips.'] },
    { n: 'Whale shark', sci: 'Rhincodon typus', g: 'carpet shark', f: f(10, H, OO), d: 1, look: ['Basking shark'],
      b: 'The biggest fish in the world. It is gentle and eats tiny plankton.',
      c: ['Divers swim with it at Ningaloo Reef.', 'Each one has a unique pattern of spots.', 'It filters plankton from the water.', 'It is the largest fish on Earth.', 'It is named after the largest kind of sea mammal.'] },
    { n: 'Basking shark', sci: 'Cetorhinus maximus', g: 'mackerel shark', f: f(8, H, CO), d: 2, look: ['Whale shark', 'Megamouth shark'],
      b: 'The second-largest fish in the world. It swims slowly with its huge mouth wide open to filter plankton.',
      c: ['It is common off the coasts of Cornwall and Scotland in summer.', 'Its gill slits almost circle its head.', 'It swims with its huge mouth wide open.', 'It is the second-largest fish in the world.', 'It is named after lying in the sun.'] },
    { n: 'Megamouth shark', sci: 'Megachasma pelagios', g: 'mackerel shark', f: f(5, H, DS), d: 3, look: ['Basking shark'],
      b: 'A rare filter-feeding shark first found in 1976, when one got tangled in a ship\'s anchor off Hawaii.',
      c: ['It was unknown to science until 1976.', 'Only a few hundred have ever been seen.', 'It rises at night to feed on shrimp-like krill.', 'Its head is large and rounded.', 'Its name means big mouth.'] },
    { n: 'Great hammerhead', alt: ['great hammerhead shark'], sci: 'Sphyrna mokarran', g: 'hammerhead', f: f(4, D, CO), d: 1, look: ['Scalloped hammerhead', 'Bonnethead'],
      b: 'The biggest hammerhead. Its wide, flat head helps it find stingrays hiding in the sand.',
      c: ['It eats stingrays and is not bothered by their stings.', 'Its tall dorsal fin is shaped like a sickle.', 'Its wide head spreads out its senses like a metal detector.', 'It is the largest of its kind.', 'Its head is shaped like a tool for hitting nails.'] },
    { n: 'Scalloped hammerhead', sci: 'Sphyrna lewini', g: 'hammerhead', f: f(3, B, CO), d: 2, look: ['Great hammerhead'],
      b: 'A hammerhead that gathers in huge schools around underwater mountains, such as near the Galápagos.',
      c: ['Hundreds gather near the Galápagos and Cocos Island.', 'It is critically endangered.', 'The front edge of its head has a wavy outline.', 'It forms big schools by day.', 'Its head is shaped like a T-shaped tool.'] },
    { n: 'Bonnethead', alt: ['bonnethead shark'], sci: 'Sphyrna tiburo', g: 'hammerhead', f: f(0.9, H, CO), d: 3, look: ['Great hammerhead'],
      b: 'A small hammerhead with a rounded, shovel-shaped head. It is the only shark known to eat a lot of seagrass.',
      c: ['It can digest seagrass.', 'Females can reproduce without males.', 'It is one of the smallest hammerheads.', 'Its head is rounded like a shovel.', 'It is named after an old-fashioned hat.'] },
    { n: 'Shortfin mako', alt: ['mako shark', 'mako'], sci: 'Isurus oxyrinchus', g: 'mackerel shark', f: f(3.2, D, OO), d: 2, look: ['Great white shark'],
      b: 'The fastest shark in the sea, with bursts of over 50 km/h. It can leap high out of the water.',
      c: ['It is a close relative of the great white.', 'It can leap several metres out of the water.', 'It is prized by sport fishers.', 'It has a bright metallic blue back.', 'It is the fastest shark.'] },
    { n: 'Blue shark', sci: 'Prionace glauca', g: 'requiem shark', f: f(3, D, OO), d: 2,
      b: 'A slim, long-finned shark of the open ocean that crosses whole oceans. Millions are caught each year.',
      c: ['It migrates right across the Atlantic.', 'Millions are caught each year for fins and meat.', 'It has very long pectoral fins.', 'It is slim with big eyes.', 'Its back is a deep indigo colour.'] },
    { n: 'Thresher shark', alt: ['common thresher'], sci: 'Alopias vulpinus', g: 'mackerel shark', f: f(5, H, OO), d: 2,
      b: 'A shark whose tail can be as long as its body. It whips its tail to stun fish.',
      c: ['Its scientific name means "fox".', 'Its upper tail fin can be as long as its body.', 'It stuns fish by slapping them with its tail.', 'It has been seen leaping clear of the water.', 'It is named after beating grain to separate it.'] },
    { n: 'Greenland shark', sci: 'Somniosus microcephalus', g: 'sleeper shark', f: f(5, H, DS), d: 2,
      b: 'A slow shark of icy Arctic waters that may live for 250 to 500 years, longer than any other animal with a backbone.',
      c: ['It may live for more than 250 years.', 'It swims at under 3 km/h.', 'Its flesh is poisonous unless it is dried for months.', 'A tiny animal often hangs from its eyes.', 'It lives in the icy North Atlantic and Arctic.'] },
    { n: 'Goblin shark', sci: 'Mitsukurina owstoni', g: 'mackerel shark', f: f(3.5, H, DS), d: 2,
      b: 'A strange pink deep-sea shark with a long flat snout. Its jaws shoot forward to catch prey.',
      c: ['It is called a "living fossil".', 'Its jaws shoot forward like a catapult.', 'Its skin is pinkish.', 'It has a long, flat, blade-like snout.', 'It is named after a creature from folk tales.'] },
    { n: 'Frilled shark', sci: 'Chlamydoselachus anguineus', g: 'frilled shark', f: f(1.5, H, DS), d: 2,
      b: 'An eel-like deep-sea shark with frilly gills and 300 needle-like teeth. It has changed little in millions of years.',
      c: ['Its pregnancy may last over three years.', 'It has about 300 three-pointed teeth.', 'It is long and thin like an eel.', 'It lives deep in the ocean.', 'Its gills have ruffled edges.'] },
    { n: 'Port Jackson shark', sci: 'Heterodontus portusjacksoni', g: 'bullhead shark', f: f(1.3, H, CO), d: 2,
      b: 'A blunt-headed shark of southern Australia that crunches sea urchins with flat teeth. Its eggs are spiral-shaped.',
      c: ['Its egg cases are screw-shaped.', 'It crushes sea urchins with flat back teeth.', 'It has a dark harness-shaped pattern.', 'It lives in southern Australia.', 'It is named after Sydney Harbour.'] },
    { n: 'Spotted wobbegong', alt: ['wobbegong'], sci: 'Orectolobus maculatus', g: 'carpet shark', f: f(1.7, B, CO), d: 2,
      b: 'A flat, patterned shark that lies on the sea floor in Australia. Weedy flaps around its mouth help it hide.',
      c: ['Its name is thought to mean "shaggy beard".', 'It has weed-like flaps around its mouth.', 'It lies still on the sea floor waiting for fish.', 'It bites people who step on it.', 'It is covered in pale spots and rings.'] },
    { n: 'Lemon shark', sci: 'Negaprion brevirostris', g: 'requiem shark', f: f(2.6, B, CO), d: 2,
      b: 'A shark of shallow mangrove coasts. Young ones grow up in mangrove nurseries such as Bimini in the Bahamas.',
      c: ['It is one of the best-studied sharks.', 'Its pups grow up in mangroves at Bimini.', 'It has two dorsal fins of almost the same size.', 'It lives in shallow water.', 'It is named for its yellowish colour, like a citrus fruit.'] },
    { n: 'Nurse shark', sci: 'Ginglymostoma cirratum', g: 'carpet shark', f: f(2.5, B, CO), d: 1,
      b: 'A slow shark that rests on the sea floor by day and sucks prey out of holes. Divers often see it sleeping in piles.',
      c: ['It sucks prey out of holes like a vacuum cleaner.', 'It can pump water over its gills while resting.', 'It has two whiskers under its snout.', 'It rests on the sea floor in groups.', 'It shares its name with someone who works in a hospital.'] },
    { n: 'Blacktip reef shark', sci: 'Carcharhinus melanopterus', g: 'requiem shark', f: f(1.4, B, RF), d: 1, look: ['Whitetip reef shark', 'Grey reef shark'],
      b: 'A small reef shark often seen in very shallow water, with its black-tipped fin above the surface.',
      c: ['It often swims in water only knee-deep.', 'Its dorsal fin often sticks out of the water.', 'It lives around Indian and Pacific Ocean reefs.', 'It is common on coral reefs.', 'Its fins have dark tips.'] },
    { n: 'Whitetip reef shark', sci: 'Triaenodon obesus', g: 'requiem shark', f: f(1.6, H, RF), d: 2, look: ['Blacktip reef shark', 'Oceanic whitetip shark'],
      b: 'A slender reef shark that rests in caves by day and hunts in reef crevices at night.',
      c: ['It can rest still on the bottom, unlike many sharks.', 'It hunts in groups at night.', 'It squeezes into crevices after fish.', 'It lives on coral reefs.', 'Its fins have pale tips.'] },
    { n: 'Grey reef shark', sci: 'Carcharhinus amblyrhynchos', g: 'requiem shark', f: f(1.8, B, RF), d: 2, look: ['Blacktip reef shark'],
      b: 'A common shark of Indo-Pacific coral reefs. When threatened, it hunches its back and swims in a stiff, jerky way.',
      c: ['Its threat display is a hunched, jerky swim.', 'Its tail has a black rear edge.', 'It patrols reef edges in groups.', 'It lives on Indo-Pacific coral reefs.', 'Its colour is between black and white.'] },
    { n: 'Zebra shark', sci: 'Stegostoma tigrinum', g: 'carpet shark', f: f(2.2, H, RF), d: 2,
      b: 'A gentle reef shark with ridges along its body. Young ones are striped, but adults are spotted.',
      c: ['Females have reproduced without males in aquariums.', 'It has ridges running along its body.', 'Its tail is about half its length.', 'Adults are spotted, but babies are striped.', 'It is named after a striped African animal.'] },
    { n: 'Epaulette shark', sci: 'Hemiscyllium ocellatum', g: 'carpet shark', f: f(0.8, H, RF), d: 2,
      b: 'A small reef shark that can "walk" on its fins across rock pools and survive for hours with little oxygen.',
      c: ['It can survive hours with very little oxygen.', 'It lives on the Great Barrier Reef.', 'It walks on its fins across rock pools.', 'It has a big black spot behind each front fin.', 'It is named after a shoulder decoration on uniforms.'] },
    { n: 'Cookiecutter shark', sci: 'Isistius brasiliensis', g: 'dogfish shark', f: f(0.45, H, DS), d: 2,
      b: 'A small shark that bites round plugs of flesh out of whales, big fish and even submarines.',
      c: ['It has bitten submarines\' rubber parts.', 'Its belly glows in the dark.', 'It bites round chunks out of whales and dolphins.', 'It is only about half a metre long.', 'It is named after a baking tool.'] },
    { n: 'Spiny dogfish', sci: 'Squalus acanthias', g: 'dogfish shark', f: f(1, H, CO), d: 3,
      b: 'A small shark with a sharp spine in front of each dorsal fin. Its pregnancy lasts nearly two years.',
      c: ['Its pregnancy lasts about two years.', 'It may live for over 50 years.', 'It was widely sold as fish and chips.', 'It has a sharp spine at the front of each back fin.', 'Its name is partly a pet animal.'] },
    { n: 'Sand tiger shark', alt: ['grey nurse shark', 'ragged-tooth shark'], sci: 'Carcharias taurus', g: 'mackerel shark', f: f(2.5, B, CO), d: 2, look: ['Great white shark'],
      b: 'A fierce-looking but calm shark with ragged teeth. In Australia it is called the grey nurse shark.',
      c: ['The biggest unborn pup eats its brothers and sisters in the womb.', 'It gulps air to float without moving.', 'Its crooked teeth stick out of its mouth.', 'It is called the grey nurse shark in Australia.', 'Its name has a sandy beach and a big cat.'] },
    { n: 'Angelshark', alt: ['angel shark'], sci: 'Squatina squatina', g: 'angel shark', f: f(1.5, B, CO), d: 2,
      b: 'A flat shark that buries itself in sand and ambushes fish. It is critically endangered in Europe.',
      c: ['The Canary Islands are one of its last strongholds.', 'It is critically endangered.', 'It buries itself in sand to ambush fish.', 'It is flat like a ray.', 'Its fins spread out like wings.'] },
    { n: 'Silky shark', sci: 'Carcharhinus falciformis', g: 'requiem shark', f: f(2.5, D, OO), d: 3,
      b: 'A slender ocean shark with smooth, satiny skin. It often gathers around floating objects at sea.',
      c: ['It often follows schools of tuna.', 'It gathers under floating logs and buoys.', 'It is one of the most common ocean sharks.', 'It is slim with a rounded snout.', 'Its skin feels smooth, like a soft fabric.'] },
    { n: 'Leopard shark', sci: 'Triakis semifasciata', g: 'houndshark', f: f(1.5, H, CO), d: 2,
      b: 'A spotted shark of the Pacific coast of North America. Schools gather in warm, shallow bays.',
      c: ['Pregnant females gather in warm shallow water at La Jolla.', 'It lives off California.', 'It eats clams, crabs and worms.', 'It has dark saddle-shaped spots.', 'It is named after a spotted big cat.'] },
    { n: 'Small-spotted catshark', alt: ['lesser spotted dogfish'], sci: 'Scyliorhinus canicula', g: 'catshark', f: f(0.6, H, CO), d: 3,
      b: 'A small, spotty shark common around Britain. Its egg cases wash up on beaches as "mermaid\'s purses".',
      c: ['Its empty egg cases are called mermaid\'s purses.', 'It is common around the British Isles.', 'It has rough skin like sandpaper.', 'It is covered in small dark spots.', 'It is named after a pet that purrs.'] },
    { n: 'Bluntnose sixgill shark', alt: ['sixgill shark'], sci: 'Hexanchus griseus', g: 'cow shark', f: f(4.5, H, DS), d: 3,
      b: 'A large, primitive deep-sea shark with six gill slits instead of five.',
      c: ['Most sharks have one gill slit fewer than it does.', 'It rises to shallower water at night.', 'It has bright green eyes.', 'It lives in deep water.', 'Its snout is rounded, not pointed.'] },
    { n: 'Dwarf lanternshark', sci: 'Etmopterus perryi', g: 'dogfish shark', f: f(0.2, H, DS), d: 3,
      b: 'One of the smallest sharks in the world, about as long as a pencil. Its belly glows in the dark.',
      c: ['It lives off Colombia and Venezuela.', 'It could fit in your hand.', 'Its belly glows to hide its shadow.', 'It is one of the smallest sharks in the world.', 'It is named after a small glowing light.'] },
  ],
  fakes: ['Velvet reef shark', 'Pacific glass shark', 'Northern ghost hammerhead', 'Crimson-finned mako', 'Spotted ribbon shark', 'Golden lantern hammerhead', 'Arctic sword shark'],
  questions: [
    { kind: 'mc', prompt: 'What is the biggest fish in the world?', answer: 'Whale shark', wrong: ['Great white shark', 'Basking shark', 'Blue whale'], explain: 'Whale sharks can be over 12 m long. Blue whales are mammals, not fish.', difficulty: 1 },
    { kind: 'tf', prompt: 'A shark is a fish.', answer: true, explain: 'Sharks are fish with skeletons made of cartilage.', difficulty: 1 },
    { kind: 'mc', prompt: 'Shark skeletons are made of what?', answer: 'Cartilage', wrong: ['Bone', 'Shell', 'Wood-like fibre'], explain: 'Cartilage is the bendy material in your nose and ears.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which shark can live in rivers and lakes as well as the sea?', answer: 'Bull shark', wrong: ['Great white shark', 'Whale shark', 'Thresher shark'], explain: 'Bull sharks have been found far up the Amazon and Mississippi.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which shark may live longer than any other animal with a backbone?', answer: 'Greenland shark', wrong: ['Whale shark', 'Great white shark', 'Nurse shark'], explain: 'Studies of eye lenses suggest they may live 250 to 500 years.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the fastest shark?', answer: 'Shortfin mako', wrong: ['Great white shark', 'Blue shark', 'Tiger shark'], explain: 'Makos can burst to over 50 km/h.', difficulty: 2 },
    { kind: 'tf', prompt: 'Sharks lose and replace their teeth throughout their lives.', answer: true, explain: 'New rows of teeth keep moving forward to replace lost ones.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which shark was the star of the 1975 film "Jaws"?', answer: 'Great white shark', wrong: ['Tiger shark', 'Bull shark', 'Hammerhead'], explain: 'The film was based on Peter Benchley\'s novel.', difficulty: 1 },
    { kind: 'mc', prompt: 'What are "mermaid\'s purses" found on beaches?', answer: 'Shark and ray egg cases', wrong: ['Seaweed pods', 'Jellyfish', 'Crab shells'], explain: 'Catsharks, skates and some others lay eggs in leathery cases.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which shark uses its very long tail to stun fish?', answer: 'Thresher shark', wrong: ['Whale shark', 'Nurse shark', 'Goblin shark'], explain: 'Its upper tail fin can be as long as the rest of its body.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which shark has a head shaped like a hammer?', answer: 'Hammerhead shark', wrong: ['Whale shark', 'Tiger shark', 'Nurse shark'], explain: 'Its wide head helps it find food hidden in the sand.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do sharks use to breathe underwater?', answer: 'Gills', wrong: ['Lungs', 'A blowhole', 'Their fins'], explain: 'Water flows over their gills, which take in oxygen.', difficulty: 1 },
    { kind: 'tf', prompt: 'All sharks are dangerous to people.', answer: false, explain: 'Most sharks are harmless; whale sharks eat only tiny plankton.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is bigger?', answer: 'Whale shark', wrong: ['Great white shark', 'Nurse shark', 'Hammerhead shark'], explain: 'The whale shark is the biggest fish of all.', difficulty: 1 },
  ],
};
