import { NOT_ID, INAT, WD, STATUS_META, VENOM_META, DANGER_META, REGION_META, len } from './_common.mjs';

const AU = 'Australia', AS = 'Asia', AF = 'Africa', AM = 'the Americas', EU = 'Europe', SEA = 'Oceans';
const H = 'Harmless', M = 'Mildly venomous', D = 'Dangerous', X = 'Potentially deadly';
const f = (venomous, lengthM, region, danger) => ({ venomous, lengthM, region, danger });

export default {
  id: 'snakes', title: 'Snakes', theme: 'animals', icon: '🐍', kids: true, notice: NOT_ID,
  leakExempt: ['snake', 'snakes'],
  autoTaxo: ['family', 'genus'], status: true, wdCheck: { lengthM: 'P2043' },
  ranges: { lengthM: [0.2, 9] },
  factsMeta: { venomous: VENOM_META, danger: DANGER_META, lengthM: len(), region: REGION_META, status: STATUS_META },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which snake is this?",
  tfImgPrompt: "This snake is {aName}.",
  tpl: {"venomous": {"askBool": "Which of these snakes is venomous?", "stmt": "The {lname} is venomous."}, "danger": {"ask": "How dangerous is the {lname} to people?", "askReverse": "Which of these snakes is rated \"{lvalue}\" to people?", "stmt": "The {lname} is rated \"{lvalue}\" to people."}, "lengthM": {"askHigh": "Which of these snakes is usually the longest?", "askLow": "Which of these snakes is usually the shortest?"}, "region": {"ask": "Where does the {lname} live?", "askReverse": "Which of these snakes lives in {value}?", "stmt": "The {lname} lives in {value}.", "exclusive": false}, "status": {"ask": "What is the IUCN conservation status of the {lname}?", "askReverse": "Which of these is listed as \"{value}\" by the IUCN?", "stmt": "The {lname} is listed as \"{value}\" by the IUCN."}},
  sources: [INAT, WD],
  items: [
    // ---- Australia ----
    { n: 'Inland taipan', alt: ['fierce snake', 'western taipan'], sci: 'Oxyuranus microlepidotus', g: 'elapid', f: f(true, 1.8, AU, X), d: 2, look: ['Coastal taipan', 'Eastern brown snake'],
      b: 'Its venom is the most toxic of any land snake tested, yet it is shy and lives in remote semi-desert, so bites are very rare.',
      c: ['It lives in the cracking clay floodplains of the Channel Country.', 'Its main prey is the long-haired rat.', 'Its skin darkens in winter and lightens in summer.', 'One bite holds enough venom to kill many adult humans.', 'It is said to have the most toxic venom of any land snake.'] },
    { n: 'Coastal taipan', sci: 'Oxyuranus scutellatus', g: 'elapid', f: f(true, 2.0, AU, X), d: 2, look: ['Inland taipan', 'Eastern brown snake'],
      b: 'A long, fast elapid of northern and eastern Australia and New Guinea. Before antivenom arrived in 1955, a bite was almost always fatal.',
      c: ['Its antivenom was first produced in 1955.', 'It has a pale, almost coffin-shaped head.', 'It hunts rats in sugar-cane fields.', 'It is the longest venomous snake in Australia.', 'Its inland cousin has the most toxic venom of any land snake.'] },
    { n: 'Eastern brown snake', sci: 'Pseudonaja textilis', g: 'elapid', f: f(true, 1.5, AU, X), d: 1, look: ['Inland taipan', 'Coastal taipan', 'Mulga snake'],
      b: 'Responsible for more snakebite deaths in Australia than any other snake. It is common around farms and outer suburbs on the east coast.',
      c: ['Young ones are often banded and have a dark head patch.', 'It raises its neck in a tall S-shape when threatened.', 'It thrives where mice gather around farm sheds.', 'Its venom has the second most toxic rating of any land snake.', 'It causes the most snakebite deaths in Australia.'] },
    { n: 'Dugite', sci: 'Pseudonaja affinis', g: 'elapid', f: f(true, 1.5, AU, X), d: 3, look: ['Eastern brown snake'],
      b: 'A brown snake of south-western Australia, often met in Perth suburbs. Its venom is highly toxic.',
      c: ['Its name comes from a Noongar word.', 'It is often speckled with black scales.', 'It lives around Perth and on Rottnest Island.', 'It belongs to the brown snake group.', 'It is a highly venomous snake of Western Australia.'] },
    { n: 'Tiger snake', alt: ['mainland tiger snake'], sci: 'Notechis scutatus', g: 'elapid', f: f(true, 1.2, AU, X), d: 1,
      b: 'A stocky, often banded elapid of southern Australia and Tasmania. Island populations range from giants to jet-black dwarfs.',
      c: ['Populations on Chappell Island feed on mutton-bird chicks.', 'Some island forms are completely black.', 'It flattens its neck like a cobra when threatened.', 'It likes swamps and wetlands of southern Australia.', 'Many are banded yellow and dark, like a big cat.'] },
    { n: 'Red-bellied black snake', sci: 'Pseudechis porphyriacus', g: 'elapid', f: f(true, 1.5, AU, D), d: 2, look: ['Mulga snake'],
      b: 'A glossy black snake with a red or pink belly, common near water on the east coast of Australia. Its bite is painful but rarely serious.',
      c: ['It gives birth to live young rather than laying eggs.', 'It is often seen near creeks, dams and swamps.', 'It eats lots of frogs.', 'Cane toads have caused declines in some populations.', 'Its back is glossy black and its belly is red.'] },
    { n: 'Mulga snake', alt: ['king brown snake'], sci: 'Pseudechis australis', g: 'elapid', f: f(true, 2.0, AU, X), d: 2, look: ['Eastern brown snake', 'Red-bellied black snake'],
      b: 'One of the heaviest venomous snakes in Australia, found across most of the mainland. It delivers a very large amount of venom.',
      c: ['Despite its common nickname it is really a black snake.', 'It is named after a kind of acacia shrubland.', 'It can produce more venom per bite than almost any other snake.', 'It eats other snakes, even venomous ones.', 'It is widely called the king brown.'] },
    { n: 'Common death adder', sci: 'Acanthophis antarcticus', g: 'elapid', f: f(true, 0.7, AU, X), d: 2,
      b: 'A short, thick Australian elapid that looks like a viper. It lies hidden in leaf litter and wiggles its tail tip to lure prey.',
      c: ['It is an elapid, not a true viper, despite its name.', 'It can strike faster than almost any other snake.', 'It wiggles a grub-like tail tip to lure lizards and birds.', 'It lies buried in leaf litter waiting for prey.', 'Its name sounds like it should be a viper.'] },
    { n: 'Lowlands copperhead', sci: 'Austrelaps superbus', g: 'elapid', f: f(true, 1.2, AU, D), d: 3, look: ['Copperhead'],
      b: 'A cold-tolerant elapid of south-eastern Australia and Tasmania. It is active even on cool days.',
      c: ['It is active at lower temperatures than most Australian snakes.', 'It lives in Tasmania and around Bass Strait islands.', 'It hunts frogs in swamps and grassland.', 'It shares a name with an unrelated North American pit viper.', 'Its head is often coppery brown.'] },
    { n: 'Rough-scaled snake', sci: 'Tropidechis carinatus', g: 'elapid', f: f(true, 0.75, AU, D), d: 3, look: ['Keelback'],
      b: 'A rainforest elapid of eastern Australia whose keeled scales make it look like the harmless keelback.',
      c: ['It is the only member of its genus.', 'It lives in rainforest and wet forest of eastern Australia.', 'It is easily confused with the harmless keelback.', 'Each scale has a raised ridge down the middle.', 'Its common name describes its bumpy skin.'] },
    { n: 'Bandy-bandy', sci: 'Vermicella annulata', g: 'elapid', f: f(true, 0.5, AU, M), d: 2, look: ['Banded krait'],
      b: 'A small burrowing elapid ringed in bold black and white. It eats almost nothing but blind snakes.',
      c: ['It feeds mainly on blind snakes.', 'When disturbed it throws its body into stiff hoops.', 'It is rarely seen except after rain at night.', 'Its body is ringed in black and white bands.', 'Its name repeats a word, joined by a hyphen.'] },
    { n: 'Carpet python', sci: 'Morelia spilota', g: 'python', f: f(false, 2.5, AU, H), d: 1, look: ['Diamond python'],
      b: 'Australia\'s most widespread python, often found in roofs and sheds where it eats rats and possums.',
      c: ['Many subspecies exist, including the jungle and coastal forms.', 'Heat pits along its lips sense warm-blooded prey.', 'It often lives in roof spaces and eats rats.', 'Its blotched pattern looks like a woven rug.', 'It is a common non-venomous constrictor in Australia.'] },
    { n: 'Diamond python', sci: 'Morelia spilota spilota', inat: 'Morelia spilota spilota', g: 'python', f: f(false, 2.0, AU, H), d: 2, look: ['Carpet python'],
      b: 'A dark subspecies of the carpet python with clusters of cream spots, found in coastal New South Wales and Victoria.',
      c: ['It is a subspecies of a more widespread python.', 'It lives further south than any other python in the world.', 'It is found around Sydney.', 'Its black scales carry cream spots in rosette-like clusters.', 'It is named after a shape found on playing cards.'] },
    { n: 'Scrub python', alt: ['amethystine python'], sci: 'Simalia kinghorni', g: 'python', f: f(false, 4.0, AU, H), d: 3,
      b: 'Australia\'s longest snake, living in the rainforests of north Queensland. Large ones can eat wallabies.',
      c: ['It is the longest snake in Australia.', 'Big ones can swallow small wallabies.', 'Its scales have an iridescent purple sheen.', 'It lives in rainforest in far north Queensland.', 'It is a slender, very long python.'] },
    { n: 'Olive python', sci: 'Liasis olivaceus', g: 'python', f: f(false, 3.5, AU, H), d: 3,
      b: 'A large plain-coloured python of northern Australia that often lives near rocky waterholes.',
      c: ['The Pilbara subspecies is listed as threatened.', 'It ambushes animals coming to drink at waterholes.', 'It is one of the largest snakes in Australia.', 'It has no bold pattern at all.', 'It is named after the colour of a fruit used for oil.'] },
    { n: 'Black-headed python', sci: 'Aspidites melanocephalus', g: 'python', f: f(false, 1.5, AU, H), d: 2, look: ['Woma'],
      b: 'A banded python of northern Australia whose glossy black head helps it warm up quickly in the sun.',
      c: ['It lacks the heat pits found in most pythons.', 'It eats other snakes, including venomous ones.', 'It can warm its whole body by sunning just its head.', 'Its body is banded in cream and brown.', 'Its head and neck are jet black.'] },
    { n: 'Woma', alt: ['woma python'], sci: 'Aspidites ramsayi', g: 'python', f: f(false, 1.5, AU, H), d: 3, look: ['Black-headed python'],
      b: 'A banded desert python of central and western Australia. It hunts reptiles in burrows by squeezing them against the walls.',
      c: ['It has no heat-sensing pits on its lips.', 'It pins prey against the walls of burrows.', 'It is endangered in parts of its range.', 'It is the pale desert cousin of the black-headed python.', 'Its name is four letters, from an Aboriginal language.'] },
    { n: 'Children\'s python', sci: 'Antaresia childreni', g: 'python', f: f(false, 1.0, AU, H), d: 3, look: ['Spotted python'],
      b: 'A small python of northern Australia, popular as a pet. It is named after the zoologist John George Children, not young people.',
      c: ['It was named after a British zoologist at the British Museum.', 'It often shelters in caves and hunts bats.', 'It is one of the smallest pythons in the world.', 'It is a popular beginner\'s pet in Australia.', 'Its name sounds as if it is meant for kids.'] },
    { n: 'Spotted python', sci: 'Antaresia maculosa', g: 'python', f: f(false, 1.0, AU, H), d: 3, look: ['Children\'s python'],
      b: 'A small, blotchy python of eastern Queensland that often hangs in cave entrances to catch bats.',
      c: ['It belongs to the same small-python genus as the children\'s python.', 'It catches bats at cave mouths.', 'It lives in eastern Queensland.', 'It is one of Australia\'s smallest pythons.', 'Its pale body is covered in dark blotches.'] },
    { n: 'Green tree python', sci: 'Morelia viridis', g: 'python', f: f(false, 1.5, AU, H), d: 1, look: ['Emerald tree boa'],
      b: 'A bright green python of New Guinea and Cape York. Babies are yellow or red and turn green as they grow.',
      c: ['Its young are yellow or red before turning green.', 'It lives in New Guinea and on Cape York Peninsula.', 'It rests looped over a branch in a tidy saddle shape.', 'It looks almost identical to a South American boa.', 'It is bright green and lives in trees.'] },
    { n: 'Common tree snake', alt: ['green tree snake'], sci: 'Dendrelaphis punctulatus', g: 'colubrid', f: f(false, 1.2, AU, H), d: 2,
      b: 'A slender, fast, harmless snake of northern and eastern Australia, often seen in gardens.',
      c: ['It inflates its neck to show blue skin between the scales when threatened.', 'It gives off a strong smell when handled.', 'It is very slender with big eyes.', 'It is often green, olive or even blue-black.', 'It is a harmless climber common in Queensland gardens.'] },
    { n: 'Brown tree snake', sci: 'Boiga irregularis', g: 'colubrid', f: f(true, 1.5, AU, M), d: 2,
      b: 'A rear-fanged night hunter of northern Australia and New Guinea. Accidentally brought to Guam, it wiped out most of the island\'s native forest birds.',
      c: ['It caused power cuts on Guam by climbing power lines.', 'It reached Guam in cargo after World War II.', 'It is rear-fanged and mildly venomous.', 'It wiped out most of Guam\'s forest birds.', 'It is a brown snake that lives in trees.'] },
    { n: 'Keelback', alt: ['freshwater snake'], sci: 'Tropidonophis mairii', g: 'colubrid', f: f(false, 0.75, AU, H), d: 3, look: ['Rough-scaled snake'],
      b: 'A harmless water snake of northern and eastern Australia. It can eat small cane toads without dying.',
      c: ['It is related to the grass snakes of Europe.', 'It can survive eating young cane toads.', 'Its tail breaks off easily if grabbed.', 'It is often confused with the venomous rough-scaled snake.', 'Its scales have ridges, a little like the bottom of a boat.'] },
    { n: 'Beaked sea snake', sci: 'Hydrophis schistosus', g: 'sea snake', f: f(true, 1.1, SEA, X), d: 3, look: ['Yellow-bellied sea snake'],
      b: 'A sea snake of tropical coasts from the Persian Gulf to Australia. It causes most sea snake bite deaths, often among fishers.',
      c: ['It is often caught in fishing nets in Asia.', 'It causes the majority of fatal sea snake bites.', 'Its snout has a hooked point.', 'It has a paddle-shaped tail.', 'It lives in shallow tropical coastal waters.'] },
    { n: 'Yellow-bellied sea snake', sci: 'Hydrophis platurus', g: 'sea snake', f: f(true, 0.8, SEA, D), d: 2, look: ['Beaked sea snake'],
      b: 'The most widespread snake on Earth, drifting in the open Pacific and Indian Oceans. It gathers in slicks of floating debris to ambush fish.',
      c: ['It drinks fresh rainwater that floats on the sea surface.', 'It is the only snake that spends its whole life in the open ocean.', 'It drifts in lines of floating debris to ambush fish.', 'It has a black back and a bright belly.', 'Its belly is yellow.'] },
    { n: 'Olive sea snake', sci: 'Aipysurus laevis', g: 'sea snake', f: f(true, 1.5, SEA, D), d: 3,
      b: 'A large, curious sea snake of coral reefs in northern Australia, the Coral Sea and New Guinea.',
      c: ['It has light-sensitive cells in its tail.', 'It is often seen by divers on the Great Barrier Reef.', 'It hunts fish in reef crevices.', 'It is one of the largest reef sea snakes.', 'Its body is a dull greenish-brown, like an olive.'] },
    // ---- Asia ----
    { n: 'King cobra', alt: ['hamadryad'], sci: 'Ophiophagus hannah', g: 'elapid', f: f(true, 3.5, AS, X), d: 1, look: ['Indian cobra'],
      b: 'The world\'s longest venomous snake, found in forests of India and South-East Asia. It mostly eats other snakes.',
      c: ['Its genus name means "snake eater".', 'It is the only snake that builds a nest for its eggs.', 'It can lift a third of its body off the ground.', 'It eats mostly other snakes.', 'It is the longest venomous snake in the world.'] },
    { n: 'Indian cobra', alt: ['spectacled cobra'], sci: 'Naja naja', g: 'elapid', f: f(true, 1.5, AS, X), d: 1, look: ['King cobra', 'Monocled cobra'],
      b: 'The cobra of snake charmers, with a spectacle-shaped mark on the back of its hood. It is one of India\'s "Big Four" deadly snakes.',
      c: ['It is one of the "Big Four" responsible for most snakebite deaths in South Asia.', 'Snake charmers traditionally use it.', 'It is linked with the Hindu god Shiva.', 'The back of its hood has a mark like a pair of glasses.', 'It is a hooded snake from South Asia.'] },
    { n: 'Monocled cobra', sci: 'Naja kaouthia', g: 'elapid', f: f(true, 1.5, AS, X), d: 3, look: ['Indian cobra'],
      b: 'A cobra of eastern India and South-East Asia with a single ring-shaped mark on the back of its hood.',
      c: ['It is common around rice paddies in Thailand.', 'Some populations can spit venom.', 'It is found from eastern India to Vietnam.', 'The mark on its hood is a single ring.', 'Its name refers to a one-lens eyeglass.'] },
    { n: 'Common krait', sci: 'Bungarus caeruleus', g: 'elapid', f: f(true, 1.0, AS, X), d: 2, look: ['Banded krait'],
      b: 'A night-active snake of South Asia whose nearly painless bite often strikes people sleeping on the floor.',
      c: ['It is one of India\'s "Big Four" medically important snakes.', 'Its bite is often painless, so victims may not wake.', 'It is active at night and enters homes.', 'It is glossy black with thin white crossbands.', 'Its name is a short word starting with K.'] },
    { n: 'Banded krait', sci: 'Bungarus fasciatus', g: 'elapid', f: f(true, 1.5, AS, X), d: 2, look: ['Common krait', 'Bandy-bandy'],
      b: 'A boldly banded snake of South-East Asia. It is shy and slow by day, and rarely bites unless handled.',
      c: ['Its tail ends bluntly rather than in a fine point.', 'Its back has a raised ridge, giving it a triangular cross-section.', 'It is sluggish by day and active at night.', 'It eats other snakes.', 'It has broad yellow and black bands.'] },
    { n: 'Russell\'s viper', sci: 'Daboia russelii', g: 'viper', f: f(true, 1.2, AS, X), d: 2, look: ['Saw-scaled viper'],
      b: 'A chain-patterned viper of South Asia and one of the deadliest snakes in the world by number of deaths.',
      c: ['It is named after the Scottish herpetologist Patrick Russell.', 'It hisses louder than almost any other snake.', 'It causes many thousands of deaths in South Asia each year.', 'Its back has three rows of dark spots like chain links.', 'It is a viper named after a person.'] },
    { n: 'Saw-scaled viper', alt: ['carpet viper'], sci: 'Echis carinatus', g: 'viper', f: f(true, 0.5, AS, X), d: 2, look: ['Russell\'s viper'],
      b: 'A small, quick-tempered viper of dry regions from the Middle East to India. Its group may cause more deaths than any other snakes.',
      c: ['It is one of India\'s "Big Four" deadly snakes.', 'It warns by rubbing its body coils together.', 'The warning noise sounds like water on a hot plate.', 'Its scales have serrated keels.', 'Its name describes a toothed cutting tool.'] },
    { n: 'Malayan pit viper', sci: 'Calloselasma rhodostoma', g: 'viper', f: f(true, 0.8, AS, X), d: 3,
      b: 'A ground-dwelling pit viper of South-East Asia, a major cause of snakebite on plantations.',
      c: ['It is the only species in its genus.', 'It often bites rubber-plantation workers.', 'It has smooth scales, unusual for a pit viper.', 'Its back has dark triangles along each side.', 'It is named after a South-East Asian peninsula.'] },
    { n: 'Wagler\'s pit viper', alt: ['temple viper'], sci: 'Tropidolaemus wagleri', g: 'viper', f: f(true, 0.8, AS, D), d: 3,
      b: 'A tree-dwelling pit viper of South-East Asia. Many live at the Temple of the Azure Cloud in Penang.',
      c: ['Males are small and green while females are big, black and yellow.', 'It can sit still in one tree for days.', 'Dozens live in a temple in Penang, Malaysia.', 'It is sometimes called the temple viper.', 'It is named after a German naturalist.'] },
    { n: 'Reticulated python', sci: 'Malayopython reticulatus', g: 'python', f: f(false, 5.0, AS, D), d: 1, look: ['Burmese python', 'Green anaconda'],
      b: 'The world\'s longest snake, found in South-East Asia. Very large ones have killed and eaten people.',
      c: ['Its genus name honours its home region.', 'It is a strong swimmer and has colonised many islands.', 'Very large ones have eaten adult humans.', 'Its pattern is a complex net-like mesh.', 'It is the longest snake in the world.'] },
    { n: 'Burmese python', sci: 'Python bivittatus', g: 'python', f: f(false, 4.0, AS, D), d: 1, look: ['Reticulated python', 'African rock python'],
      b: 'One of the largest snakes on Earth, native to South-East Asia. Released pets now form a large invasive population in Florida\'s Everglades.',
      c: ['It is native to South-East Asia.', 'It is a big problem as an invasive species in Florida.', 'It has wiped out many mammals in the Everglades.', 'It is one of the five largest snakes in the world.', 'It is named after a country now called Myanmar.'] },
    { n: 'Paradise tree snake', alt: ['paradise flying snake'], sci: 'Chrysopelea paradisi', g: 'colubrid', f: f(true, 1.0, AS, M), d: 3,
      b: 'A South-East Asian snake that can glide from tree to tree by flattening its body and undulating through the air.',
      c: ['It can travel up to about 100 metres in one glide.', 'It flattens its ribs to make its body into a wing.', 'It wriggles through the air as it travels between trees.', 'It is often called a flying snake.', 'Its name refers to heaven.'] },
    { n: 'Mangrove snake', alt: ['gold-ringed cat snake'], sci: 'Boiga dendrophila', g: 'colubrid', f: f(true, 2.0, AS, M), d: 3,
      b: 'A glossy black and yellow rear-fanged snake of South-East Asian forests and swamps.',
      c: ['Its pupils are vertical like a cat\'s.', 'It is rear-fanged and mildly venomous.', 'It hunts birds, lizards and frogs at night.', 'It is black with narrow yellow rings.', 'It is named after coastal swamp forests.'] },
    // ---- Africa ----
    { n: 'Black mamba', sci: 'Dendroaspis polylepis', g: 'elapid', f: f(true, 2.5, AF, X), d: 1, look: ['Eastern green mamba'],
      b: 'A long, fast African elapid named for the inky black inside of its mouth. Untreated bites are almost always fatal.',
      c: ['It is the longest venomous snake in Africa.', 'It can move at around 15 km/h, among the fastest snakes.', 'Untreated bites are nearly always fatal.', 'Its body is actually grey or olive-brown.', 'The inside of its mouth is inky black.'] },
    { n: 'Eastern green mamba', sci: 'Dendroaspis angusticeps', g: 'elapid', f: f(true, 1.8, AF, X), d: 2, look: ['Black mamba', 'Boomslang'],
      b: 'A shy, bright green tree snake of East and southern Africa. It is less aggressive than its black cousin.',
      c: ['It lives in coastal forests of East Africa.', 'It is shy and spends most of its life in trees.', 'It is often confused with the harmless bush snakes.', 'It is a close relative of the black mamba.', 'It is bright green.'] },
    { n: 'Puff adder', sci: 'Bitis arietans', g: 'viper', f: f(true, 1.0, AF, X), d: 2, look: ['Gaboon viper'],
      b: 'A stout, sluggish viper common across Africa. It causes more serious bites in Africa than any other snake because it sits still when approached.',
      c: ['It relies on camouflage and sits still instead of fleeing.', 'It causes more bites in Africa than any other snake.', 'It has chevron markings along its back.', 'It inflates its body and hisses loudly when threatened.', 'Its name describes blowing up with air.'] },
    { n: 'Gaboon viper', sci: 'Bitis gabonica', g: 'viper', f: f(true, 1.3, AF, X), d: 2, look: ['Puff adder', 'Rhinoceros viper'],
      b: 'A huge, beautifully patterned viper of African rainforest floors. It has the longest fangs of any snake.',
      c: ['It is the heaviest viper in Africa.', 'Its pattern makes it vanish among fallen leaves.', 'Its fangs can be 5 cm long.', 'It has the longest fangs of any snake.', 'It is named after a country on Africa\'s west coast.'] },
    { n: 'Rhinoceros viper', sci: 'Bitis nasicornis', g: 'viper', f: f(true, 0.9, AF, D), d: 3, look: ['Gaboon viper'],
      b: 'A gaudy blue, green and red viper of central African rainforests with horn-like scales on its snout.',
      c: ['It lives in West and Central African rainforests.', 'Its pattern mixes blue, green, red and black.', 'It is a close relative of the Gaboon viper.', 'It has two or three pairs of horn-like scales on its nose.', 'It is named after a horned African mammal.'] },
    { n: 'Boomslang', sci: 'Dispholidus typus', g: 'colubrid', f: f(true, 1.4, AF, X), d: 2, look: ['Eastern green mamba'],
      b: 'A rear-fanged African tree snake with huge eyes. Its slow-acting venom killed the herpetologist Karl Schmidt in 1957.',
      c: ['Karl Schmidt kept notes on his symptoms until he died from its bite.', 'Its venom stops blood from clotting.', 'It has unusually large eyes.', 'It is one of the few dangerous rear-fanged snakes.', 'Its name is Afrikaans for "tree snake".'] },
    { n: 'Cape cobra', sci: 'Naja nivea', g: 'elapid', f: f(true, 1.3, AF, X), d: 2,
      b: 'A cobra of dry parts of southern Africa that comes in yellow, brown and speckled forms.',
      c: ['It often raids sociable weaver nests for eggs and chicks.', 'It lives in the Karoo and Kalahari.', 'Some are butter-yellow, others brown or speckled.', 'It is one of Africa\'s most dangerous cobras.', 'It is named after a cape at the tip of Africa.'] },
    { n: 'Egyptian cobra', sci: 'Naja haje', g: 'elapid', f: f(true, 1.5, AF, X), d: 2,
      b: 'A large cobra of northern Africa. The "asp" of ancient Egypt and the rearing snake on the pharaohs\' crowns.',
      c: ['It is often said to be the asp linked with Cleopatra\'s death.', 'The uraeus on pharaohs\' crowns shows it rearing up.', 'It lives across North and West Africa.', 'It spreads a broad hood when threatened.', 'It is named after a country on the Nile.'] },
    { n: 'Mozambique spitting cobra', sci: 'Naja mossambica', g: 'elapid', f: f(true, 1.1, AF, D), d: 3,
      b: 'A spitting cobra of south-eastern Africa that can aim venom at the eyes from over two metres away.',
      c: ['It usually rears up before spraying venom.', 'Its venom causes tissue damage around a bite.', 'It aims at the eyes of a threat.', 'It is a hooded snake of south-eastern Africa.', 'It is named after an African country on the Indian Ocean.'] },
    { n: 'Horned viper', alt: ['desert horned viper', 'Saharan horned viper'], sci: 'Cerastes cerastes', g: 'viper', f: f(true, 0.6, AF, D), d: 2, look: ['Sidewinder'],
      b: 'A small sand-coloured viper of the Sahara and Arabia that often has a spike-like scale above each eye.',
      c: ['It moves across loose sand by sidewinding.', 'It buries itself in sand with only its eyes showing.', 'It lives in the Sahara and Arabian deserts.', 'It is sand-coloured.', 'It has a spike-like scale above each eye.'] },
    { n: 'African rock python', sci: 'Python sebae', g: 'python', f: f(false, 4.0, AF, D), d: 2, look: ['Burmese python'],
      b: 'Africa\'s largest snake. It can swallow antelopes and is known to have killed people.',
      c: ['It is the largest snake in Africa.', 'It can swallow small antelopes and crocodiles.', 'It lives in savanna and forest south of the Sahara.', 'It has an arrow-shaped mark on top of its head.', 'Its name includes a word for stone.'] },
    { n: 'Ball python', alt: ['royal python'], sci: 'Python regius', g: 'python', f: f(false, 1.2, AF, H), d: 2,
      b: 'A small, gentle West African python and one of the world\'s most popular pet snakes.',
      c: ['Breeders have produced thousands of colour forms called morphs.', 'In some West African cultures it is sacred.', 'It is one of the most popular pet snakes.', 'Its scientific name means "royal".', 'When scared it curls into a tight sphere.'] },
    // ---- Americas ----
    { n: 'Western diamondback rattlesnake', sci: 'Crotalus atrox', g: 'viper', f: f(true, 1.2, AM, X), d: 1, look: ['Eastern diamondback rattlesnake'],
      b: 'A big, bold rattlesnake of the south-western USA and Mexico, and one of the most dangerous snakes in North America.',
      c: ['Its tail is ringed black and white, like a raccoon\'s.', 'It is a leading cause of snakebite in the south-western USA.', 'It adds a new segment to its tail each time it sheds.', 'It has diamond-shaped markings along its back.', 'It shakes a buzzing tail as a warning.'] },
    { n: 'Eastern diamondback rattlesnake', sci: 'Crotalus adamanteus', g: 'viper', f: f(true, 1.5, AM, X), d: 2, look: ['Western diamondback rattlesnake'],
      b: 'The heaviest venomous snake in the Americas, found in pine woods of the south-eastern USA.',
      c: ['It often shelters in gopher tortoise burrows.', 'It lives in longleaf pine forests of the south-east USA.', 'It is the heaviest venomous snake in the Americas.', 'Its back has bold diamonds edged in cream.', 'It warns with a buzzing tail.'] },
    { n: 'Timber rattlesnake', sci: 'Crotalus horridus', g: 'viper', f: f(true, 1.1, AM, X), d: 2,
      b: 'A rattlesnake of forests in the eastern USA. It appeared on the "Don\'t tread on me" Gadsden flag.',
      c: ['It appears on the "Don\'t tread on me" flag.', 'It shelters in rocky dens over winter, often in groups.', 'Its scientific name means "dreadful".', 'It has dark zig-zag crossbands.', 'It lives in eastern US woodlands and shakes its tail.'] },
    { n: 'Sidewinder', alt: ['horned rattlesnake'], sci: 'Crotalus cerastes', g: 'viper', f: f(true, 0.6, AM, D), d: 2, look: ['Horned viper'],
      b: 'A small desert rattlesnake of the south-western USA and Mexico that moves across sand in sideways loops.',
      c: ['It has horn-like scales over its eyes.', 'It lives in the Mojave and Sonoran deserts.', 'It leaves J-shaped tracks in the sand.', 'It is a small rattlesnake.', 'It moves across sand by throwing its body sideways.'] },
    { n: 'Copperhead', sci: 'Agkistrodon contortrix', g: 'viper', f: f(true, 0.75, AM, D), d: 2, look: ['Cottonmouth', 'Lowlands copperhead'],
      b: 'A pit viper of the eastern USA with hourglass-shaped bands. It bites more people in the US than any other snake, but deaths are very rare.',
      c: ['Its young have bright yellow tail tips to lure frogs.', 'Its bands look like hourglasses from the side.', 'It bites more Americans than any other venomous snake.', 'Its bites are very rarely fatal.', 'Its head is the colour of a reddish metal.'] },
    { n: 'Cottonmouth', alt: ['water moccasin'], sci: 'Agkistrodon piscivorus', g: 'viper', f: f(true, 0.9, AM, D), d: 2, look: ['Copperhead'],
      b: 'A semi-aquatic pit viper of the south-eastern USA. It gapes to show the white lining of its mouth when threatened.',
      c: ['It is the only venomous water snake in North America.', 'Its scientific name means "fish eater".', 'It swims with its whole body floating high on the water.', 'It is also called the water moccasin.', 'When threatened it opens its mouth to show the white inside.'] },
    { n: 'Eastern coral snake', sci: 'Micrurus fulvius', g: 'elapid', f: f(true, 0.75, AM, X), d: 1, look: ['Milk snake', 'Scarlet kingsnake'],
      b: 'A brightly ringed elapid of the south-eastern USA. Its red bands touch yellow ones, unlike its harmless lookalikes.',
      c: ['Its bite can take hours before symptoms show.', 'It is related to cobras, not to rattlesnakes.', 'Its red bands touch yellow bands.', 'The rhyme "red touches yellow" helps tell it from mimics in the USA.', 'It is ringed in red, yellow and black and shares its name with a reef animal.'] },
    { n: 'Milk snake', sci: 'Lampropeltis triangulum', g: 'colubrid', f: f(false, 0.9, AM, H), d: 2, look: ['Eastern coral snake', 'Scarlet kingsnake'],
      b: 'A harmless North American snake whose red, black and yellow bands mimic the deadly coral snakes.',
      c: ['Some forms copy the colours of a deadly snake.', 'In it, red bands touch black bands.', 'It eats rodents and other snakes.', 'A legend said it drank milk from cows.', 'Its name is a dairy drink.'] },
    { n: 'Scarlet kingsnake', sci: 'Lampropeltis elapsoides', g: 'colubrid', f: f(false, 0.5, AM, H), d: 3, look: ['Eastern coral snake', 'Milk snake'],
      b: 'A small, harmless snake of the south-eastern USA whose red, black and yellow rings mimic the coral snake.',
      c: ['It often hides under the bark of dead pine trees.', 'Its red bands are bordered by black.', 'It mimics the eastern coral snake.', 'It is one of the smallest kingsnakes.', 'It is named after a bright shade of red.'] },
    { n: 'California kingsnake', sci: 'Lampropeltis californiae', g: 'colubrid', f: f(false, 1.0, AM, H), d: 2,
      b: 'A banded or striped kingsnake of the western USA and Mexico. It is immune to rattlesnake venom and eats rattlesnakes.',
      c: ['It is resistant to rattlesnake venom.', 'It kills and eats rattlesnakes.', 'It is usually banded black and white.', 'It is a popular pet.', 'It is named after a US state.'] },
    { n: 'Corn snake', alt: ['red rat snake'], sci: 'Pantherophis guttatus', g: 'colubrid', f: f(false, 1.2, AM, H), d: 1,
      b: 'A gentle, orange-red rat snake of the south-eastern USA and one of the most popular pet snakes.',
      c: ['Its belly has a checkerboard pattern.', 'It was often found around grain stores, where it hunted mice.', 'It is one of the most popular pet snakes.', 'It is orange with red blotches.', 'Its name is a cereal crop.'] },
    { n: 'Common garter snake', sci: 'Thamnophis sirtalis', g: 'colubrid', f: f(false, 0.7, AM, H), d: 1,
      b: 'North America\'s most widespread snake. In Manitoba, tens of thousands emerge together from winter dens.',
      c: ['Some populations can eat poisonous newts.', 'Tens of thousands mass at dens in Manitoba each spring.', 'It is found further north than any other North American reptile.', 'It usually has three pale stripes along its body.', 'Its name sounds like a gardener\'s snake.'] },
    { n: 'Gopher snake', alt: ['bullsnake'], sci: 'Pituophis catenifer', g: 'colubrid', f: f(false, 1.4, AM, H), d: 3, look: ['Western diamondback rattlesnake'],
      b: 'A large, harmless snake of western North America that bluffs by hissing and shaking its tail like a rattlesnake.',
      c: ['It hisses loudly through a flap in its windpipe.', 'It vibrates its tail in dry leaves to mimic a rattle.', 'It is often killed by mistake as a rattlesnake.', 'It hunts rodents in their burrows.', 'It is named after a burrowing rodent.'] },
    { n: 'Fer-de-lance', alt: ['terciopelo', 'common lancehead'], sci: 'Bothrops asper', g: 'viper', f: f(true, 1.5, AM, X), d: 2,
      b: 'A large, irritable pit viper of Central and northern South America. It causes more serious bites there than any other snake.',
      c: ['In Costa Rica it is called the terciopelo, meaning velvet.', 'Females give birth to dozens of live young.', 'It causes most snakebites in Central America.', 'It is often found near streams and farms.', 'Its French name means "iron of the spear".'] },
    { n: 'Bushmaster', sci: 'Lachesis muta', g: 'viper', f: f(true, 2.5, AM, X), d: 2,
      b: 'The longest viper in the Americas, living on the floor of Amazon rainforest.',
      c: ['Its genus is named after one of the three Fates.', 'Unlike most American vipers, it lays eggs.', 'Its tail ends in a spiny tip but no rattle.', 'It lives in the Amazon rainforest.', 'It is the longest viper in the Americas.'] },
    { n: 'Eyelash viper', sci: 'Bothriechis schlegelii', g: 'viper', f: f(true, 0.6, AM, D), d: 2,
      b: 'A small tree viper of Central and South America that comes in yellow, green and pink forms.',
      c: ['One colour form is bright golden yellow.', 'It ambushes hummingbirds at flowers.', 'It lives in trees in Central American rainforest.', 'It is a small pit viper.', 'It has spiky scales above its eyes.'] },
    { n: 'South American rattlesnake', alt: ['cascabel'], sci: 'Crotalus durissus', g: 'viper', f: f(true, 1.2, AM, X), d: 3,
      b: 'The rattlesnake of South America, whose venom attacks the nervous system more than most rattlesnakes\'.',
      c: ['Its venom can cause blindness and paralysis.', 'It lives in dry savanna, not rainforest.', 'It has two dark stripes down its neck.', 'It is the only rattlesnake across most of its continent.', 'It has a rattle and lives south of Panama.'] },
    { n: 'Green anaconda', sci: 'Eunectes murinus', g: 'boa', f: f(false, 5.0, AM, D), d: 1, look: ['Reticulated python'],
      b: 'The heaviest snake in the world, living in the swamps and rivers of tropical South America.',
      c: ['Its scientific name means "of mice", though it eats caimans.', 'Its eyes and nostrils sit on top of its head.', 'It spends most of its time in water.', 'It is the heaviest snake in the world.', 'It is an olive-coloured giant of the Amazon.'] },
    { n: 'Boa constrictor', alt: ['red-tailed boa', 'boa'], sci: 'Boa constrictor', g: 'boa', f: f(false, 2.5, AM, H), d: 1,
      b: 'A large constrictor of Central and South America and one of the few animals whose scientific name is also its common name.',
      c: ['Its scientific name is the same as its common name.', 'It gives birth to live young.', 'Its tail is often reddish.', 'It kills prey by squeezing.', 'It is a large South American snake that shares its name with a feather scarf.'] },
    { n: 'Emerald tree boa', sci: 'Corallus caninus', g: 'boa', f: f(false, 1.8, AM, H), d: 2, look: ['Green tree python'],
      b: 'A bright green boa of Amazon rainforest that coils over branches, looking almost identical to the green tree python.',
      c: ['Its long front teeth help it grip birds.', 'It is green with white zig-zag marks along its back.', 'It lives in the Amazon canopy.', 'It looks almost exactly like a python from New Guinea.', 'It is named after a green gemstone.'] },
    // ---- Europe ----
    { n: 'Common European adder', alt: ['adder', 'common viper'], sci: 'Vipera berus', g: 'viper', f: f(true, 0.6, EU, D), d: 1, look: ['Smooth snake', 'Grass snake'],
      b: 'Britain\'s only venomous snake, with a zig-zag stripe down its back. It lives further north than any other snake, even beyond the Arctic Circle.',
      c: ['It is found north of the Arctic Circle in Scandinavia.', 'Males gather for "adder dances" in spring.', 'It is the only venomous snake in Britain.', 'It has a dark zig-zag stripe down its back.', 'Its name begins with the word for "ordinary".'] },
    { n: 'Nose-horned viper', alt: ['long-nosed viper'], sci: 'Vipera ammodytes', g: 'viper', f: f(true, 0.7, EU, D), d: 2,
      b: 'A viper of the Balkans and Italy often called Europe\'s most dangerous snake. It has a soft horn on its snout.',
      c: ['It lives in rocky hills of the Balkans.', 'Its scientific name means "sand digger".', 'It is often called the most dangerous snake in Europe.', 'It has a zig-zag stripe down its back.', 'It has a soft horn on the tip of its snout.'] },
    { n: 'Asp viper', alt: ['aspic viper'], sci: 'Vipera aspis', g: 'viper', f: f(true, 0.65, EU, D), d: 3,
      b: 'A viper of south-western Europe, found in France, Italy, Spain and Switzerland.',
      c: ['It lives in France, Italy and Switzerland.', 'Its snout is slightly upturned.', 'It gives birth to live young.', 'It is a European viper.', 'Its name shares a word with the snake linked to Cleopatra.'] },
    { n: 'Grass snake', sci: 'Natrix natrix', g: 'colubrid', f: f(false, 1.0, EU, H), d: 1, look: ['Common European adder'],
      b: 'Europe\'s common harmless water snake, with a yellow collar behind its head. When cornered it often plays dead.',
      c: ['It lays its eggs in compost heaps for warmth.', 'It plays dead and gives off a foul smell when grabbed.', 'It swims well and hunts frogs and fish.', 'It has a yellow or cream collar behind its head.', 'Its name is a lawn plant.'] },
    { n: 'Smooth snake', sci: 'Coronella austriaca', g: 'colubrid', f: f(false, 0.6, EU, H), d: 3, look: ['Common European adder'],
      b: 'A small, rare, harmless snake of European heathland. It constricts lizards and other small reptiles.',
      c: ['In Britain it lives only on a few southern heaths.', 'It constricts lizards and slow-worms.', 'It is often mistaken for an adder.', 'It is one of only three native snakes in Britain.', 'Its scales have no ridges, so it feels sleek.'] },
    { n: 'Aesculapian snake', sci: 'Zamenis longissimus', g: 'colubrid', f: f(false, 1.5, EU, H), d: 3,
      b: 'A long, harmless climbing snake of Europe, linked with the Greek god of medicine.',
      c: ['Its species name means "longest".', 'It is a good climber, often seen in trees.', 'It is one of the longest snakes in Europe.', 'It is linked with the rod of the Greek god of medicine.', 'It is named after a god of healing.'] },
    { n: 'Banded sea krait', alt: ['yellow-lipped sea krait'], sci: 'Laticauda colubrina', g: 'sea snake', f: f(true, 1.0, SEA, D), d: 3, look: ['Banded krait'],
      b: 'A blue-and-black banded sea snake of the western Pacific that hunts eels on reefs but comes ashore to rest and lay eggs.',
      c: ['It comes ashore to digest food and lay eggs.', 'It hunts eels in coral reef crevices.', 'Its upper lip is yellow.', 'It is banded blue-grey and black.', 'It is a banded snake that lives in the sea.'] },
  ],
  fakes: ['Glass-eyed adder', 'Crimson taipan', 'Silver mamba', 'Velvet-tailed cobra', 'Moonlight krait', 'Ironbark viper', 'Thunder python', 'Sapphire-bellied boa', 'Desert ghost mamba', 'Spotted tiger cobra'],
  questions: [
    { kind: 'mc', prompt: 'Which snake has the most toxic venom of any land snake tested?', answer: 'Inland taipan', wrong: ['King cobra', 'Black mamba', 'Western diamondback rattlesnake'], explain: 'The inland taipan of central Australia tops standard venom-toxicity tests on mice.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the longest snake species in the world?', answer: 'Reticulated python', wrong: ['Green anaconda', 'King cobra', 'Burmese python'], explain: 'The reticulated python is the longest; the green anaconda is the heaviest.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the heaviest snake in the world?', answer: 'Green anaconda', wrong: ['Reticulated python', 'Boa constrictor', 'King cobra'], explain: 'Green anacondas are bulkier than reticulated pythons, even though they are shorter.', difficulty: 2 },
    { kind: 'tf', prompt: 'The king cobra is the only snake that builds a nest for its eggs.', answer: true, explain: 'Females pile leaves into a mound nest and guard it.', difficulty: 2 },
    { kind: 'tf', prompt: 'Britain has three native venomous snakes.', answer: false, explain: 'The adder is Britain\'s only venomous snake; the grass snake and smooth snake are harmless.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which island lost most of its forest birds to the introduced brown tree snake?', answer: 'Guam', wrong: ['Hawaii', 'Tasmania', 'Madagascar'], explain: 'The snake arrived on Guam in cargo after World War II.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which snake causes the most snakebite deaths in Australia?', answer: 'Eastern brown snake', wrong: ['Inland taipan', 'Tiger snake', 'Common death adder'], explain: 'Brown snakes live close to people on farms and city edges.', difficulty: 2 },
    { kind: 'tf', prompt: 'The death adder is a true viper.', answer: false, explain: 'Death adders are elapids, related to cobras, that evolved a viper-like body.', difficulty: 3 },
    { kind: 'mc', prompt: 'Which snake has the longest fangs?', answer: 'Gaboon viper', wrong: ['King cobra', 'Black mamba', 'Inland taipan'], explain: 'Gaboon viper fangs can reach about 5 cm.', difficulty: 2 },
    { kind: 'mc', prompt: 'In the USA, the rhyme "red touches yellow" helps tell which snake from its harmless mimics?', answer: 'Coral snake', wrong: ['Copperhead', 'Cottonmouth', 'Garter snake'], explain: 'In US coral snakes red bands touch yellow; in milk snakes and scarlet kingsnakes red touches black. It does not hold everywhere.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which invasive snake has become a serious problem in Florida\'s Everglades?', answer: 'Burmese python', wrong: ['King cobra', 'Green anaconda', 'Black mamba'], explain: 'Released and escaped pets founded a breeding population.', difficulty: 1 },
    { kind: 'mc', prompt: 'Snake charmers in India traditionally use which snake?', answer: 'Indian cobra', wrong: ['Russell\'s viper', 'Common krait', 'Reticulated python'], explain: 'The spectacled Indian cobra rears and spreads its hood.', difficulty: 1 },
    { kind: 'tf', prompt: 'The black mamba is named after the colour of its scales.', answer: false, explain: 'It is usually grey or olive; the name comes from the inky black inside of its mouth.', difficulty: 2 },
  ],
};
