import { WD, COMMONS, NASA } from './_common.mjs';

const PL = 'Planet', DP = 'Dwarf planet', MO = 'Moon', ST = 'Star', CO = 'Constellation', GA = 'Galaxy', NE = 'Nebula', MI = 'Mission or spacecraft', CM = 'Comet', BH = 'Black hole';
const body = (kind, diameterKm, extra = {}) => ({ kind, ...(diameterKm ? { diameterKm } : {}), ...extra });
const mission = (year, extra = {}) => ({ kind: MI, year, ...extra });

export default {
  id: 'space', title: 'Space', theme: 'science', icon: '🪐', kids: true,
  noun: 'space object', fakePrompt: 'Which of these space names is made up?',
  leakExempt: [],
  media: 'wiki', photos: 2, depicts: 0, lname: 'asis',
  ranges: { diameterKm: [1, 1.4e6], year: [1950, 2026] },
  factsMeta: {
    kind: { type: 'cat', label: 'Kind', values: [PL, DP, MO, ST, CO, GA, NE, MI, CM, BH], clue: v => `It is ${/^[AEIOU]/.test(v) ? 'an' : 'a'} ${v.toLowerCase()}.` },
    diameterKm: { type: 'num', label: 'Diameter', unit: 'km', higherLabel: 'Bigger', clue: v => `It is about ${v.toLocaleString('en-GB')} km across.` },
    fromSun: { type: 'num', label: 'Order from the Sun', unit: '', askNumber: 'Counting out from the Sun, which planet number is {name}?', matchPrompt: 'Match each planet to its place from the Sun', clue: v => `It is planet number ${v} from the Sun.` },
    year: { type: 'year', label: 'Launched', clue: v => `It launched in ${v}.` },
    planetType: { type: 'cat', label: 'Planet type', values: ['Rocky', 'Gas giant', 'Ice giant'], clue: v => `It is ${v === 'Rocky' ? 'a rocky planet' : 'an ' + v.toLowerCase()}.`.replace('an gas', 'a gas') },
    orbits: { type: 'cat', label: 'Orbits', clue: v => `It orbits ${v}.` },
  },
  imgPrompt: "Which of these is {lname}?",
  nameImgPrompt: "What is this?",
  tfImgPrompt: "This is {lname}.",
  tpl: {"kind": {"ask": "What is {lname}?", "askReverse": "Which of these is {aValue}?", "stmt": "{lname} is {aValue}."}, "diameterKm": {"askHigh": "Which of these is the biggest?", "askLow": "Which of these is the smallest?"}, "fromSun": {"askHigh": "Which of these planets is farthest from the Sun?", "askLow": "Which of these planets is closest to the Sun?", "minRatio": 1.1}, "year": {"askHigh": "Which of these launched most recently?", "askLow": "Which of these launched first?", "minRatio": 1.002}, "planetType": {"ask": "What type of planet is {lname}?", "askReverse": "Which of these is {aValue} planet?", "stmt": "{lname} is {aValue} planet."}, "orbits": {"ask": "What does {lname} orbit?", "askReverse": "Which of these orbits {value}?", "stmt": "{lname} orbits {value}."}},
  sources: [NASA, WD, COMMONS],
  items: [
    // ---- the Sun and planets ----
    { n: 'Sun', ln: 'the Sun', alt: ['the Sun', 'Sol'], f: body(ST, 1392700), d: 1,
      b: 'The star at the centre of our solar system. Its light takes about 8 minutes to reach Earth.',
      c: ['It holds about 99.8% of the mass of the solar system.', 'It is about 4.6 billion years old.', 'Its light takes about 8 minutes to reach us.', 'It is a yellow dwarf star.', 'It is the star at the centre of our solar system.'] },
    { n: 'Mercury', wp: 'Mercury (planet)', f: body(PL, 4879, { fromSun: 1, planetType: 'Rocky' }), d: 1, look: ['Moon'],
      b: 'The smallest planet and the closest to the Sun. A year there is just 88 Earth days.',
      c: ['A day there lasts longer than its year.', 'It has almost no atmosphere, so nights fall to about −180 °C.', 'Its year is just 88 Earth days.', 'It is the smallest planet.', 'It is the closest planet to the Sun.'] },
    { n: 'Venus', f: body(PL, 12104, { fromSun: 2, planetType: 'Rocky' }), d: 1,
      b: 'The hottest planet, wrapped in thick clouds of acid. It spins backwards compared with most planets.',
      c: ['It spins in the opposite direction to most planets.', 'Its clouds contain sulphuric acid.', 'It is the hottest planet, even though Mercury is closer to the Sun.', 'It is the brightest planet in our sky.', 'It is named after the Roman goddess of love.'] },
    { n: 'Earth', ln: 'Earth', alt: ['the Earth'], f: body(PL, 12742, { fromSun: 3, planetType: 'Rocky' }), d: 1,
      b: 'Our home and the only place known to have life. About 71% of its surface is covered in water.',
      c: ['It is the densest planet in the solar system.', 'About 71% of its surface is water.', 'It has one natural satellite.', 'It is the only planet known to have life.', 'It is the planet we live on.'] },
    { n: 'Mars', f: body(PL, 6779, { fromSun: 4, planetType: 'Rocky' }), d: 1,
      b: 'The red planet, coloured by rusty dust. It has the tallest volcano in the solar system, Olympus Mons.',
      c: ['Its moons are Phobos and Deimos.', 'Olympus Mons, the tallest volcano in the solar system, is here.', 'Rovers like Curiosity and Perseverance explore it.', 'It is named after the Roman god of war.', 'It is called the red planet.'] },
    { n: 'Jupiter', f: body(PL, 139820, { fromSun: 5, planetType: 'Gas giant' }), d: 1,
      b: 'The biggest planet, a gas giant with a giant storm called the Great Red Spot.',
      c: ['Galileo discovered its four biggest moons in 1610.', 'It has the shortest day of any planet, about 10 hours.', 'Its Great Red Spot is a storm bigger than Earth.', 'It is named after the king of the Roman gods.', 'It is the biggest planet.'] },
    { n: 'Saturn', f: body(PL, 116460, { fromSun: 6, planetType: 'Gas giant' }), d: 1,
      b: 'A gas giant famous for its bright rings of ice and rock. It is so light it would float in a big enough bath.',
      c: ['It is less dense than water.', 'Its biggest moon, Titan, has a thick atmosphere.', 'The Cassini probe studied it for 13 years.', 'It is the sixth planet from the Sun.', 'It has the most famous rings.'] },
    { n: 'Uranus', f: body(PL, 50724, { fromSun: 7, planetType: 'Ice giant' }), d: 1,
      b: 'An ice giant that spins on its side. It was the first planet found with a telescope.',
      c: ['William Herschel discovered it in 1781.', 'It was the first planet found with a telescope.', 'Most of its moons are named after Shakespeare characters.', 'It spins on its side.', 'It is the seventh planet from the Sun.'] },
    { n: 'Neptune', f: body(PL, 49244, { fromSun: 8, planetType: 'Ice giant' }), d: 1,
      b: 'The farthest planet from the Sun, a deep blue ice giant with the fastest winds in the solar system.',
      c: ['It was found by maths before it was seen, in 1846.', 'Only Voyager 2 has visited it.', 'It has the fastest winds in the solar system.', 'It is named after the Roman god of the sea.', 'It is the farthest planet from the Sun.'] },
    { n: 'Pluto', f: body(DP, 2377, { orbits: 'the Sun' }), d: 1,
      b: 'A dwarf planet in the Kuiper Belt. It was called the ninth planet until 2006.',
      c: ['It has a heart-shaped plain of nitrogen ice.', 'New Horizons flew past it in 2015.', 'It was discovered by Clyde Tombaugh in 1930.', 'It was reclassified as a dwarf planet in 2006.', 'It used to be called the ninth planet.'] },
    { n: 'Ceres', wp: 'Ceres (dwarf planet)', f: body(DP, 940, { orbits: 'the Sun' }), d: 2,
      b: 'The largest object in the asteroid belt and the only dwarf planet in the inner solar system.',
      c: ['It was discovered in 1801.', 'The Dawn spacecraft orbited it.', 'It has bright salty spots in a crater.', 'It is the largest object in the asteroid belt.', 'It is named after the Roman goddess of farming.'] },
    { n: 'Eris', wp: 'Eris (dwarf planet)', f: body(DP, 2326, { orbits: 'the Sun' }), d: 3,
      b: 'A distant dwarf planet almost as big as Pluto. Its discovery led to Pluto being reclassified.',
      c: ['It was discovered in 2005.', 'It is more massive than Pluto.', 'Its discovery led to the definition of a planet.', 'It is named after the Greek goddess of strife.', 'It is a distant dwarf planet.'] },
    // ---- moons ----
    { n: 'Moon', ln: 'the Moon', alt: ['the Moon', 'Luna'], f: body(MO, 3474, { orbits: 'Earth' }), d: 1, look: ['Mercury'],
      b: 'Earth\'s natural satellite. Twelve astronauts walked on it between 1969 and 1972.',
      c: ['It is slowly moving away from Earth by about 4 cm a year.', 'The same side always faces Earth.', 'Twelve people have walked on it.', 'Its pull causes the tides.', 'It lights up the night sky.'] },
    { n: 'Io', wp: 'Io (moon)', f: body(MO, 3643, { orbits: 'Jupiter' }), d: 2, look: ['Europa'],
      b: 'A moon of Jupiter and the most volcanic place in the solar system.',
      c: ['Its volcanoes shoot plumes hundreds of kilometres high.', 'Its yellow colour comes from sulphur.', 'Galileo discovered it in 1610.', 'It is the most volcanic body in the solar system.', 'It has only two letters in its name.'] },
    { n: 'Europa', wp: 'Europa (moon)', f: body(MO, 3122, { orbits: 'Jupiter' }), d: 2, look: ['Io', 'Enceladus'],
      b: 'An icy moon of Jupiter with a salty ocean under its shell. It is one of the best places to look for life.',
      c: ['NASA\'s Europa Clipper is on its way there.', 'Its ice is criss-crossed with cracks.', 'A salty ocean lies under its ice.', 'It is one of Jupiter\'s four big moons.', 'It shares its name with a continent.'] },
    { n: 'Ganymede', nasa: 'Ganymede Juno', f: body(MO, 5268, { orbits: 'Jupiter' }), d: 2, look: ['Titan'],
      b: 'The biggest moon in the solar system, bigger than the planet Mercury. It has its own magnetic field.',
      c: ['It is the only moon with its own magnetic field.', 'It is bigger than the planet Mercury.', 'It orbits Jupiter.', 'It is the largest moon in the solar system.', 'It is named after a cup-bearer of the Greek gods.'] },
    { n: 'Callisto', nasa: 'Callisto Galileo', f: body(MO, 4821, { orbits: 'Jupiter' }), d: 3,
      b: 'A dark, heavily cratered moon of Jupiter. Its surface is one of the oldest in the solar system.',
      c: ['It is the most heavily cratered body in the solar system.', 'Its surface is about 4 billion years old.', 'It is the second-largest moon of Jupiter.', 'Galileo discovered it in 1610.', 'It is named after a nymph in Greek myth.'] },
    { n: 'Titan', wp: 'Titan (moon)', f: body(MO, 5150, { orbits: 'Saturn' }), d: 2, look: ['Ganymede'],
      b: 'Saturn\'s largest moon, with a thick orange haze and lakes of liquid methane.',
      c: ['The Huygens probe landed there in 2005.', 'It has lakes and rain of liquid methane.', 'It has a thicker atmosphere than Earth.', 'It is the largest moon of Saturn.', 'Its name means a giant from Greek myth.'] },
    { n: 'Enceladus', f: body(MO, 504, { orbits: 'Saturn' }), d: 3, look: ['Europa'],
      b: 'A small, icy moon of Saturn that shoots jets of water from cracks near its south pole.',
      c: ['Its jets feed one of Saturn\'s rings.', 'It reflects almost all the sunlight that hits it.', 'Cassini flew through its plumes.', 'It sprays water jets from its south pole.', 'It is a small icy moon of Saturn.'] },
    { n: 'Triton', wp: 'Triton (moon)', f: body(MO, 2707, { orbits: 'Neptune' }), d: 3,
      b: 'Neptune\'s biggest moon. It orbits backwards and has geysers of nitrogen.',
      c: ['It orbits in the opposite direction to Neptune\'s spin.', 'It may be a captured Kuiper Belt object.', 'Voyager 2 saw its nitrogen geysers.', 'It is Neptune\'s largest moon.', 'It is named after a merman god.'] },
    { n: 'Phobos', wp: 'Phobos (moon)', f: body(MO, 22, { orbits: 'Mars' }), d: 3,
      b: 'The larger of Mars\'s two tiny moons. It is slowly spiralling inwards and will break apart one day.',
      c: ['It orbits Mars three times a day.', 'It is slowly spiralling towards Mars.', 'It is shaped like a potato.', 'Its name means "fear" in Greek.', 'It is the bigger of Mars\'s two moons.'] },
    { n: 'Charon', wp: 'Charon (moon)', f: body(MO, 1212, { orbits: 'Pluto' }), d: 3,
      b: 'Pluto\'s largest moon, about half Pluto\'s size. The two are locked face to face.',
      c: ['It and Pluto always show each other the same face.', 'It has a reddish polar cap.', 'It was discovered in 1978.', 'It is about half the size of Pluto.', 'It is named after the ferryman of the dead.'] },
    // ---- stars, galaxies and more ----
    { n: 'Sirius', alt: ['Dog Star'], f: body(ST, null), d: 2,
      b: 'The brightest star in the night sky. It is about 8.6 light years away.',
      c: ['It is in the southern half of the sky.', 'It is a white star, twice as massive as the Sun.', 'Ancient Egyptians linked its rising to the Nile flood.', 'It is in the dog constellation.', 'It is the brightest point of light at night after the planets.', 'It has a tiny white dwarf companion.', 'It is about 8.6 light years away.', 'It is in the constellation Canis Major.', 'It is called the Dog Star.', 'It is the brightest star in the night sky.'] },
    { n: 'Betelgeuse', f: body(ST, null), d: 2,
      b: 'A huge red supergiant star in Orion. It will explode as a supernova one day.',
      c: ['It is hundreds of times wider than the Sun.', 'It looks orange-red.', 'It dimmed strangely in 2019 and 2020.', 'It will one day explode as a supernova.', 'It is a red supergiant.', 'It marks a shoulder of Orion.', 'Its name sounds like a famous ghost film.'] },
    { n: 'Polaris', alt: ['North Star', 'Pole Star'], f: body(ST, null), d: 2,
      b: 'The North Star. It sits almost directly above the North Pole, so it barely moves in the sky.',
      c: ['Its height above the horizon tells you your latitude.', 'It is in Ursa Minor.', 'It sits almost directly above the North Pole.', 'It cannot be seen from Australia.', 'Northern sailors steered by it.', 'It is really a system of several stars.', 'Sailors used it to find their latitude.', 'It is at the end of the Little Dipper\'s handle.', 'It barely moves in the night sky.', 'It is called the North Star.'] },
    { n: 'Proxima Centauri', f: body(ST, null), d: 2, look: ['Alpha Centauri'],
      b: 'The closest star to the Sun, about 4.2 light years away. It has at least one planet.',
      c: ['It sometimes gives off big flares.', 'It is part of a three-star system.', 'It has a planet in its habitable zone.', 'It is a small red dwarf.', 'It is too dim to see without a telescope.', 'It is about 4.2 light years away.', 'It is the closest star to the Sun.'] },
    { n: 'Alpha Centauri', alt: ['Rigil Kentaurus'], f: body(ST, null), d: 3, look: ['Proxima Centauri'],
      b: 'The closest star system to us. Its two bright stars look like one point of light to the naked eye.',
      c: ['It is in the southern sky.', 'It cannot be seen from most of Europe.', 'It is a triple star system.', 'It points the way to the Southern Cross.', 'Two of its stars look like one to the naked eye.', 'It is the third-brightest star in the night sky.', 'It is about 4.4 light years away.', 'It is the brightest star in Centaurus.'] },
    { n: 'Orion', wp: 'Orion (constellation)', files: ['Orion Head to Toe.jpg'] /* unlabelled: the usual charts print the name */, f: body(CO, null), d: 1, allowSvg: true,
      b: 'A bright constellation shaped like a hunter, with three stars in a row for his belt.',
      c: ['It can be seen from both hemispheres.', 'It is best seen in December and January evenings.', 'Its brightest stars are Rigel and Betelgeuse.', 'A famous nebula forms its sword.', 'Three stars in a row form its belt.', 'Australians see it upside down as "the Saucepan".', 'It is named after a hunter from Greek myth.'] },
    { n: 'Ursa Major', alt: ['Great Bear', 'Big Dipper', 'the Plough'], f: body(CO, null), d: 2, allowSvg: true,
      b: 'A big northern constellation, the Great Bear. Seven of its stars form the Big Dipper, or Plough.',
      c: ['It circles the North Star.', 'It is the third-largest constellation.', 'Two of its stars point to Polaris.', 'Seven of its brightest stars form a saucepan or wagon shape.', 'Its name is Latin for a large wild animal.', 'It is a big constellation of the northern sky.', 'Its seven famous stars are sometimes called a farm tool.'] },
    { n: 'Crux', alt: ['Southern Cross'], files: ['The Crux from Southeastern Queensland.jpg'], f: body(CO, null), d: 1, allowSvg: true,
      b: 'The smallest constellation, a cross of stars in the southern sky. It is on the flags of Australia and New Zealand.',
      c: ['It is in the Milky Way.', 'It is best seen from the southern hemisphere.', 'Its brightest star is Acrux.', 'It has four bright stars and one fainter one.', 'It is the smallest of the 88 constellations.', 'Two pointer stars lead to it.', 'It helps find south.', 'It appears on the flags of Australia and New Zealand.', 'It is called the Southern Cross.'] },
    { n: 'Cassiopeia', wp: 'Cassiopeia (constellation)', f: body(CO, null), d: 2, allowSvg: true,
      b: 'A northern constellation shaped like a W, named after a vain queen in Greek myth.',
      c: ['It is a northern constellation.', 'It sits in the Milky Way.', 'It never sets in much of the northern hemisphere.', 'It is named after a vain queen.', 'Her daughter Andromeda is nearby.', 'It is opposite the Big Dipper around the North Star.', 'Its stars form a W shape.'] },
    { n: 'Scorpius', alt: ['Scorpio'], f: body(CO, null), d: 2, allowSvg: true,
      b: 'A constellation shaped like a scorpion, with the bright red star Antares at its heart.',
      c: ['It is best seen in winter evenings in Australia.', 'It lies near the centre of the Milky Way.', 'Its brightest star is Antares, a red supergiant.', 'In myth it killed Orion.', 'It is a sign of the zodiac.', 'Its stars curl like a tail with a sting.', 'It is shaped like a scorpion.'] },
    { n: 'Milky Way', ln: 'the Milky Way', alt: ['the Milky Way'], f: body(GA, null), d: 1, look: ['Andromeda Galaxy'],
      b: 'Our home galaxy, a spiral of hundreds of billions of stars. On dark nights it looks like a glowing band across the sky.',
      c: ['It is about 100,000 light years across.', 'The Sun takes about 230 million years to go round it.', 'A supermassive black hole sits at its centre.', 'It is a barred spiral galaxy.', 'It contains hundreds of billions of stars.', 'It looks like a glowing band across dark skies.', 'It is our home galaxy.'] },
    { n: 'Andromeda Galaxy', ln: 'the Andromeda Galaxy', alt: ['Andromeda', 'M31'], f: body(GA, null), d: 2, look: ['Milky Way'],
      b: 'The nearest big galaxy to the Milky Way, about 2.5 million light years away. The two will merge in billions of years.',
      c: ['It has two small companions called M32 and M110.', 'It is bigger than the Milky Way.', 'Charles Messier listed it as number 31.', 'It is in the northern sky.', 'It is heading towards the Milky Way.', 'It is about 2.5 million light years away.', 'It is the most distant thing most people can see without a telescope.', 'It is a huge spiral of about a trillion stars.', 'It is named after a princess in Greek myth.'] },
    { n: 'Orion Nebula', ln: 'the Orion Nebula', alt: ['M42'], f: body(NE, null), d: 3,
      b: 'A glowing cloud of gas where new stars are being born. It forms the "sword" of Orion.',
      c: ['It is about 24 light years across.', 'It glows pink and red in photos.', 'It is about 1,300 light years away.', 'It is a stellar nursery.', 'It can be seen without a telescope.', 'It forms the sword of a hunter constellation.', 'It is named after a hunter.'] },
    { n: 'Pillars of Creation', ln: 'the Pillars of Creation', f: body(NE, null), d: 2,
      b: 'Towering columns of gas and dust in the Eagle Nebula, made famous by a Hubble photo in 1995.',
      c: ['They are about 6,500 light years away.', 'Their tallest column is about 4 light years long.', 'They are in the Eagle Nebula.', 'Hubble photographed them in 1995.', 'The James Webb telescope photographed them in 2022.', 'New stars are forming inside them.', 'They look like tall columns of gas and dust.'] },
    { n: 'Halley\'s Comet', alt: ['Halley\'s comet', 'Comet Halley'], f: body(CM, null), d: 1,
      b: 'The most famous comet, seen from Earth about every 76 years. It will next return in 2061.',
      c: ['Edmond Halley predicted its return.', 'It was seen by a spacecraft fleet in 1986.', 'It appears on the Bayeux Tapestry.', 'It last came near Earth in 1986.', 'It returns about every 76 years.', 'It will next be visible in 2061.', 'It is named after an English astronomer.'] },
    { n: 'Sagittarius A*', alt: ['Sagittarius A star', 'Sgr A*'], f: body(BH, null), d: 3,
      b: 'The supermassive black hole at the centre of our galaxy. It is about four million times the mass of the Sun.',
      c: ['It lies about 26,000 light years away.', 'It is in the direction of Sagittarius.', 'Radio telescopes study it.', 'Its first image was released in 2022.', 'It is about four million times the mass of the Sun.', 'Stars whizz around it in tight orbits.', 'It sits at the centre of the Milky Way.', 'It is a supermassive black hole.'] },
    // ---- missions ----
    { n: 'Sputnik 1', alt: ['Sputnik'], f: mission(1957), d: 2,
      b: 'The first artificial satellite, launched by the Soviet Union in 1957. It beeped radio signals as it orbited.',
      c: ['It was a metal ball with four long antennas.', 'Its beeps could be heard by radio amateurs.', 'It started the Space Race.', 'The Soviet Union launched it in 1957.', 'It was the first artificial satellite.'] },
    { n: 'Vostok 1', f: mission(1961), d: 3,
      b: 'The spacecraft that carried Yuri Gagarin, the first person in space, around the Earth in 1961.',
      c: ['Its flight lasted 108 minutes.', 'Its pilot ejected and landed by parachute.', 'It launched on 12 April 1961.', 'It carried Yuri Gagarin.', 'It took the first human into space.'] },
    { n: 'Apollo 11', f: mission(1969), d: 1,
      b: 'The mission that first landed people on the Moon, in July 1969. Neil Armstrong and Buzz Aldrin walked on the surface.',
      c: ['Michael Collins stayed in orbit in the command module.', 'Its lunar module was called Eagle.', 'It landed in the Sea of Tranquility.', 'Neil Armstrong said "one small step for man".', 'It was the first mission to land people on the Moon.'] },
    { n: 'Apollo 13', f: mission(1970), d: 2,
      b: 'A Moon mission that went wrong when an oxygen tank exploded. The crew got home safely using the lunar module as a lifeboat.',
      c: ['An oxygen tank exploded on the way to the Moon.', 'The crew used the lunar module as a lifeboat.', 'Its crew said "Houston, we\'ve had a problem."', 'A 1995 film with Tom Hanks tells its story.', 'It never landed on the Moon.'] },
    { n: 'Voyager 1', f: mission(1977), d: 2, look: ['New Horizons'],
      b: 'A space probe launched in 1977. It is the farthest human-made object from Earth, now in interstellar space.',
      c: ['It carries a golden record of sounds from Earth.', 'It took the "Pale Blue Dot" photo of Earth.', 'It flew past Jupiter and Saturn.', 'It entered interstellar space in 2012.', 'It is the farthest human-made object.'] },
    { n: 'Hubble Space Telescope', ln: 'the Hubble Space Telescope', alt: ['Hubble'], f: mission(1990), d: 1, look: ['James Webb Space Telescope'],
      b: 'A space telescope launched in 1990. It has taken some of the most famous pictures of the universe.',
      c: ['It launched in 1990.', 'Astronauts visited it five times to repair it.', 'It sees mainly visible and ultraviolet light.', 'Its mirror was faulty at first and fixed by astronauts.', 'It was carried into space by the Space Shuttle.', 'It helped measure the age of the universe.', 'It orbits the Earth.', 'It is named after the astronomer Edwin Hubble.'] },
    { n: 'James Webb Space Telescope', ln: 'the James Webb Space Telescope', alt: ['JWST', 'Webb'], f: mission(2021), d: 2, look: ['Hubble Space Telescope'],
      b: 'The biggest space telescope ever launched, in 2021. It sees in infrared light and has a gold-coated mirror.',
      c: ['Its sunshield is the size of a tennis court.', 'It orbits about 1.5 million km from Earth.', 'It sees in infrared light.', 'Its mirror is coated in gold.', 'It launched on Christmas Day 2021.'] },
    { n: 'International Space Station', ln: 'the International Space Station', alt: ['ISS', 'space station'], f: mission(1998), d: 1,
      b: 'A space station that has had people living on it since 2000. It circles Earth about every 90 minutes.',
      c: ['It has been lived on non-stop since 2000.', 'It travels at about 28,000 km/h.', 'It circles Earth about 16 times a day.', 'You can see it from the ground as a moving bright dot.', 'Astronauts from many countries live on it.'] },
    { n: 'Space Shuttle', ln: 'the Space Shuttle', f: mission(1981), d: 1,
      b: 'A reusable spaceplane flown by NASA from 1981 to 2011. Five shuttles flew in space.',
      c: ['Its big orange fuel tank was thrown away each flight.', 'It was launched by NASA.', 'Two were lost, Challenger and Columbia.', 'Its last flight was in 2011.', 'It landed like a glider.', 'It launched Hubble into orbit.', 'It was NASA\'s reusable spaceplane.'] },
    { n: 'Curiosity', wp: 'Curiosity (rover)', alt: ['Curiosity rover'], f: mission(2011), d: 2, look: ['Perseverance'],
      b: 'A car-sized NASA rover that landed in Gale Crater on Mars in 2012 using a rocket-powered "sky crane".',
      c: ['It has a laser to zap rocks.', 'It is nuclear powered.', 'It landed using a rocket-powered sky crane.', 'It is powered by plutonium.', 'It landed in Gale Crater in 2012.', 'It is about the size of a car.', 'It is a NASA rover on Mars.'] },
    { n: 'Perseverance', nasa: 'Perseverance rover selfie', wp: 'Perseverance (rover)', alt: ['Perseverance rover', 'Percy'], f: mission(2020), d: 2, look: ['Curiosity'],
      b: 'A NASA Mars rover that landed in 2021. It carried a small helicopter called Ingenuity.',
      c: ['It has microphones that recorded sounds on Mars.', 'It is nuclear powered.', 'It collects rock samples to bring back to Earth one day.', 'It landed in Jezero Crater.', 'It carried a helicopter called Ingenuity.', 'It landed on Mars in 2021.', 'It is a NASA Mars rover.'] },
    { n: 'Cassini–Huygens', alt: ['Cassini', 'Cassini-Huygens'], f: mission(1997), d: 3,
      b: 'A mission that orbited Saturn for 13 years. It dropped the Huygens probe onto Titan.',
      c: ['It ended by diving into Saturn in 2017.', 'Its probe landed on Titan.', 'It found water jets on Enceladus.', 'It orbited Saturn for 13 years.', 'It is named after two astronomers.'] },
    { n: 'New Horizons', f: mission(2006), d: 3, look: ['Voyager 1'],
      b: 'A NASA probe that flew past Pluto in 2015, giving us the first close-up pictures of it.',
      c: ['It is a NASA spacecraft.', 'It was the fastest spacecraft at launch.', 'It took nine years to reach its main target.', 'It carries some of Clyde Tombaugh\'s ashes.', 'It later flew past Arrokoth in the Kuiper Belt.', 'It launched in 2006.', 'It flew past Pluto in 2015.', 'Its name means new edges of the sky.'] },
    { n: 'Parker Solar Probe', ln: 'the Parker Solar Probe', f: mission(2018), d: 3,
      b: 'A NASA probe that flies closer to the Sun than any spacecraft before. It is the fastest human-made object.',
      c: ['It is named after Eugene Parker.', 'It was the first NASA spacecraft named after a living person.', 'It is the fastest human-made object.', 'It is protected by a heat shield.', 'It has "touched" the Sun\'s outer atmosphere.', 'It launched in 2018.', 'It studies the Sun up close.'] },
  ],
  fakes: ['Planet Nibiru', 'Vulcanis', 'Kepler\'s Moon of Ganthor', 'The Orion Spiral Galaxy', 'Apollo 21', 'Comet Brightwater'],
  questions: [
    { kind: 'order', prompt: 'Put these planets in order from the Sun.', answer: ['Mercury', 'Venus', 'Earth', 'Mars'], orderLabel: 'Closest first', explain: 'These are the four rocky planets.', difficulty: 1 },
    { kind: 'order', prompt: 'Put these planets in order from the Sun.', answer: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], orderLabel: 'Closest first', explain: 'These are the four giant planets.', difficulty: 2 },
    { kind: 'number', prompt: 'How many planets are in our solar system?', answer: 8, unit: 'planets', tolerance: 0, explain: 'Pluto was reclassified as a dwarf planet in 2006.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the biggest planet?', answer: 'Jupiter', wrong: ['Saturn', 'Neptune', 'Earth'], explain: 'Over 1,300 Earths could fit inside it.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the hottest planet?', answer: 'Venus', wrong: ['Mercury', 'Mars', 'Jupiter'], explain: 'Its thick carbon dioxide atmosphere traps heat, so it beats Mercury.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which planet is called the red planet?', answer: 'Mars', wrong: ['Venus', 'Jupiter', 'Mercury'], explain: 'Iron oxide dust makes it look red.', difficulty: 1 },
    { kind: 'mc', prompt: 'Who was the first person to walk on the Moon?', answer: 'Neil Armstrong', wrong: ['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], explain: 'He stepped onto the Moon on 20 July 1969 (21 July UTC).', difficulty: 1 },
    { kind: 'mc', prompt: 'Who was the first person in space?', answer: 'Yuri Gagarin', wrong: ['Neil Armstrong', 'Alan Shepard', 'Valentina Tereshkova'], explain: 'He orbited Earth in Vostok 1 on 12 April 1961.', difficulty: 1 },
    { kind: 'mc', prompt: 'Who was the first woman in space?', answer: 'Valentina Tereshkova', wrong: ['Sally Ride', 'Mae Jemison', 'Eileen Collins'], explain: 'She flew Vostok 6 in 1963.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which planet has the most famous rings?', answer: 'Saturn', wrong: ['Jupiter', 'Mars', 'Venus'], explain: 'All four giant planets have rings, but Saturn\'s are the brightest.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the name of our galaxy?', answer: 'The Milky Way', wrong: ['Andromeda', 'The Whirlpool', 'Orion'], explain: 'It is a barred spiral galaxy.', difficulty: 1 },
    { kind: 'mc', prompt: 'About how long does sunlight take to reach Earth?', answer: '8 minutes', wrong: ['8 seconds', '8 hours', '8 days'], explain: 'Light travels about 150 million km from the Sun.', difficulty: 2 },
    { kind: 'tf', prompt: 'Pluto is still called a planet by astronomers.', answer: false, explain: 'The IAU classed it as a dwarf planet in 2006.', difficulty: 1 },
    { kind: 'mc', prompt: 'What causes the tides on Earth?', answer: 'Mainly the Moon\'s gravity', wrong: ['The wind', 'Earthquakes', 'The Earth\'s magnetic field'], explain: 'The Sun adds a smaller pull too.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the closest star to the Sun?', answer: 'Proxima Centauri', wrong: ['Sirius', 'Polaris', 'Betelgeuse'], explain: 'It is about 4.2 light years away.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which is the brightest star in the night sky?', answer: 'Sirius', wrong: ['Polaris', 'Betelgeuse', 'Vega'], explain: 'Polaris is not especially bright; it is famous for staying still.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is a light year?', answer: 'The distance light travels in a year', wrong: ['The time it takes to get to the Moon', 'A year on a planet with no night', 'The weight of a star'], explain: 'It is about 9.5 trillion km.', difficulty: 2 },
    { kind: 'mc', prompt: 'What is at the centre of our solar system?', answer: 'The Sun', wrong: ['The Earth', 'The Moon', 'Jupiter'], explain: 'All the planets orbit the Sun.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which planet is the closest to the Sun?', answer: 'Mercury', wrong: ['Venus', 'Earth', 'Mars'], explain: 'Mercury orbits in just 88 days.', difficulty: 1 },
    { kind: 'tf', prompt: 'The Sun is a star.', answer: true, explain: 'It is a fairly ordinary yellow dwarf star.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is the name of the very large volcano on Mars?', answer: 'Olympus Mons', wrong: ['Mount Everest', 'Mauna Kea', 'Vesuvius'], explain: 'It is about 22 km high.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which spacecraft is the farthest human-made object from Earth?', answer: 'Voyager 1', wrong: ['Hubble Space Telescope', 'New Horizons', 'Apollo 11'], explain: 'It has been travelling since 1977.', difficulty: 2 },
    { kind: 'mc', prompt: 'How many people have walked on the Moon?', answer: '12', wrong: ['2', '6', '24'], explain: 'Six Apollo missions landed between 1969 and 1972.', difficulty: 2 },
  ],
};
