import { NOT_ID, INAT, WD, DANGER_META, REGION_META } from './_common.mjs';

const AU = 'Australia', AS = 'Asia', AF = 'Africa', AM = 'the Americas', EU = 'Europe', WW = 'many parts of the world';
const H = 'Harmless', M = 'Mildly venomous', D = 'Dangerous', X = 'Potentially deadly';
const f = (danger, region, web) => ({ danger, region, ...(web == null ? {} : { web }) });

export default {
  id: 'spiders', title: 'Spiders', theme: 'animals', icon: '🕷️', kids: true, notice: NOT_ID,
  leakExempt: ['spider', 'spiders'],
  wikiD1: true, autoTaxo: ['family', 'genus'],
  factsMeta: {
    danger: { ...DANGER_META, clue: v => ({ Harmless: 'Its bite is harmless to people.', 'Mildly venomous': 'Its bite can hurt but is rarely serious.', Dangerous: 'Its bite can make a person very ill.', 'Potentially deadly': 'Its bite can kill a person without treatment.' }[v]) },
    region: REGION_META,
    web: { type: 'bool', label: 'Catches prey in a web', yes: 'Web builder', no: 'Hunts without a web', clue: v => (v ? 'It catches prey in a web.' : 'It hunts without a catching web.') },
    legSpanCm: { type: 'num', label: 'Leg span', unit: 'cm', higherLabel: 'Bigger', clue: v => `Its leg span can reach about ${v} cm.` },
  },
  ranges: { legSpanCm: [0.3, 32] },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which spider is this?",
  tfImgPrompt: "This spider is {aName}.",
  tpl: {"danger": {"ask": "How dangerous is a bite from the {lname}?", "askReverse": "Which of these spiders is rated \"{lvalue}\" to people?", "stmt": "A bite from the {lname} is rated \"{lvalue}\"."}, "region": {"ask": "Where does the {lname} live?", "askReverse": "Which of these spiders lives in {value}?", "stmt": "The {lname} lives in {value}.", "exclusive": false}, "web": {"askBool": "Which of these spiders catches its prey in a web?", "stmt": "The {lname} catches its prey in a web."}, "legSpanCm": {"askHigh": "Which of these spiders has the biggest leg span?", "askLow": "Which of these spiders has the smallest leg span?"}},
  sources: [INAT, WD],
  items: [
    { n: 'Sydney funnel-web spider', alt: ['funnel-web', 'Sydney funnel-web'], sci: 'Atrax robustus', g: 'funnel-web', f: f(X, AU, false), d: 1, look: ['Trapdoor spider', 'Mouse spider'],
      b: 'A glossy black spider from around Sydney. Its venom can kill a person. Since antivenom arrived in 1981, no one has died from its bite.',
      c: ['The males wander in summer looking for mates.', 'Male venom is far more dangerous than female venom.', 'An antivenom was made in 1981 using venom milked at a reptile park.', 'It lives in silk-lined burrows around Australia\'s biggest city.', 'It is said to be the deadliest spider in the world.'] },
    { n: 'Redback spider', alt: ['redback'], sci: 'Latrodectus hasselti', g: 'widow', f: f(D, AU, true), d: 1, look: ['Black widow', 'False widow spider'],
      b: 'A small black Australian spider with a red stripe on its back. It likes sheds, letterboxes and outdoor toilets.',
      c: ['It is a close relative of the black widow.', 'Males often get eaten by the female during mating.', 'It builds messy, tangled webs in dry, sheltered spots.', 'A pub song is about one hiding under a toilet seat.', 'The female is shiny black with a red stripe.'] },
    { n: 'White-tailed spider', sci: 'Lampona cylindrata', g: 'hunter', f: f(M, AU, false), d: 2,
      b: 'A slim, dark Australian spider that hunts other spiders at night. Its bite is painful but it does not cause flesh to rot.',
      c: ['It hunts other spiders, especially black house spiders.', 'It often hides in clothes and towels.', 'It was wrongly blamed for causing skin ulcers.', 'It has a cigar-shaped grey body.', 'Its tail end has a pale tip.'] },
    { n: 'Huntsman spider', alt: ['huntsman'], sci: 'Sparassidae', g: 'huntsman', f: f(H, WW, false), d: 1, look: ['Wolf spider'],
      b: 'Big, flat, fast spiders that often turn up on walls and in cars in Australia. They look scary but are harmless.',
      c: ['Its legs spread out sideways, like a crab.', 'It can squeeze under doors and behind pictures.', 'It sometimes hides behind a car\'s sun visor.', 'The giant species from Laos has a leg span of about 30 cm.', 'It is a large, hairy, flat spider common in Australian homes.'] },
    { n: 'Australian golden orb-weaver', alt: ['golden orb-weaver', 'golden orb weaver'], sci: 'Trichonephila edulis', g: 'orb-weaver', f: f(H, AU, true), d: 1, look: ['European garden spider'],
      b: 'A large spider with long banded legs that spins a huge web of golden silk. The female is many times bigger than the male.',
      c: ['Tiny males live on the edge of the female\'s web.', 'Its webs can be over a metre across.', 'Its huge webs often stay up for months.', 'The female has long legs with tufts at the joints.', 'Its silk shines like a precious yellow metal.'] },
    { n: 'Eastern mouse spider', alt: ['mouse spider'], sci: 'Missulena bradleyi', g: 'mygalomorph', f: f(D, AU, false), d: 3, look: ['Sydney funnel-web spider'],
      b: 'A stocky burrowing spider of eastern Australia with big, bulging jaws. Males wander by day looking for mates.',
      c: ['Funnel-web antivenom works against its bite.', 'Its jaws are large and bulging.', 'It lives in a deep burrow in the ground.', 'Males often roam in daylight after rain.', 'It is named after a small rodent.'] },
    { n: 'Trapdoor spider', sci: 'Idiopidae', g: 'mygalomorph', f: f(H, WW, false), d: 2, look: ['Sydney funnel-web spider'],
      b: 'Burrowing spiders that close their burrows with a hinged lid of soil and silk. They wait under the lid and grab passing insects.',
      c: ['Some live for over 40 years.', 'Silk trip-lines around the burrow warn it of prey.', 'It lives in a burrow in the ground.', 'It is often confused with the funnel-web.', 'Its burrow has a hinged lid.'] },
    { n: 'Wolf spider', sci: 'Lycosidae', g: 'wolf', f: f(H, WW, false), d: 1, look: ['Huntsman spider'],
      b: 'Hairy ground spiders that chase down prey instead of using webs. Mothers carry their babies on their backs.',
      c: ['Their eyes shine green in torchlight.', 'Mothers drag their egg sac attached to their spinnerets.', 'Babies ride on their mother\'s back.', 'They hunt on the ground at night.', 'They are named after a wild dog that hunts in packs.'] },
    { n: 'Peacock spider', sci: 'Maratus volans', g: 'jumping', f: f(H, AU, false), d: 1,
      b: 'A tiny Australian jumping spider. The male raises a brightly coloured flap and dances to win a mate.',
      c: ['It is only about 5 millimetres long.', 'It belongs to the jumping spider family.', 'The male waves his third pair of legs in the air.', 'The male shows off a bright fan on his back.', 'It is named after a showy bird.'] },
    { n: 'St Andrew\'s cross spider', sci: 'Argiope keyserlingi', g: 'orb-weaver', f: f(H, AU, true), d: 2, look: ['Wasp spider'],
      b: 'An Australian orb-weaver that adds bright zig-zag bands to its web in the shape of a cross.',
      c: ['It sits with its legs held in pairs.', 'It adds zig-zag silk bands to the web.', 'The bands may reflect ultraviolet light.', 'The bands form an X shape.', 'It is named after the cross of Scotland\'s patron saint.'] },
    { n: 'Black house spider', sci: 'Badumna insignis', g: 'hunter', f: f(M, AU, true), d: 2, look: ['Redback spider'],
      b: 'A dark, shy spider that builds messy, funnel-shaped webs in window frames and walls in Australia.',
      c: ['White-tailed spiders hunt it.', 'Its lacy webs have a funnel retreat.', 'It is often found in window frames.', 'Its bite is painful but not dangerous.', 'It is a dark spider that lives on buildings.'] },
    { n: 'Daddy long-legs spider', alt: ['cellar spider', 'daddy longlegs'], sci: 'Pholcus phalangioides', g: 'cellar', f: f(H, WW, true), d: 1,
      b: 'A spider with a tiny body and very long, thin legs. It lives in quiet corners of houses all over the world.',
      c: ['A myth says it has the strongest venom but fangs too small to bite.', 'When disturbed it shakes its web very fast.', 'It hunts other spiders, even redbacks.', 'It lives in house corners and ceilings.', 'Its legs are very long and thin.'] },
    { n: 'Christmas spider', alt: ['jewel spider'], sci: 'Austracantha minax', g: 'orb-weaver', f: f(H, AU, true), d: 2,
      b: 'A small spiny orb-weaver that appears in Australian gardens in early summer, often in big groups.',
      c: ['Its body has six spines.', 'Many often build webs together in a group.', 'It is black with white or yellow spots.', 'It is common in Australian gardens in December.', 'It is named after a holiday.'] },
    { n: 'Bird-dropping spider', sci: 'Celaenia excavata', g: 'orb-weaver', f: f(H, AU, false), d: 3,
      b: 'An Australian spider that looks like a bird dropping by day. At night it gives off a smell like a female moth to lure males.',
      c: ['It catches male moths without a web.', 'It copies the scent of female moths.', 'It sits still on leaves all day.', 'Predators ignore it because of how it looks.', 'It looks like something a bird left behind.'] },
    { n: 'Black widow', alt: ['southern black widow'], sci: 'Latrodectus mactans', g: 'widow', f: f(D, AM, true), d: 1, look: ['Redback spider', 'Brown widow', 'False widow spider'],
      b: 'A glossy black American spider with a red hourglass under its belly. The female sometimes eats the male.',
      c: ['Its venom attacks the nerves.', 'The female sometimes eats the male after mating.', 'It builds a messy tangle web near the ground.', 'Its belly has a red hourglass mark.', 'Its name means a woman whose husband has died.'] },
    { n: 'Brown widow', sci: 'Latrodectus geometricus', g: 'widow', f: f(M, WW, true), d: 3, look: ['Black widow'],
      b: 'A widow spider that has spread around the warm parts of the world. Its egg sacs are covered in spiky bumps.',
      c: ['Its egg sacs look like spiky balls.', 'It has an orange hourglass on its belly.', 'It has spread across the warm parts of the world.', 'Its venom is strong but it injects very little.', 'It is a paler cousin of the black widow.'] },
    { n: 'Brown recluse', alt: ['violin spider', 'fiddleback'], sci: 'Loxosceles reclusa', g: 'recluse', f: f(D, AM, false), d: 2,
      b: 'A shy brown spider of the central USA with a violin-shaped mark. Rarely, its bite causes a slow-healing wound.',
      c: ['It has six eyes instead of eight.', 'It hides in boxes, shoes and closets.', 'Its bite can rarely cause a slow-healing wound.', 'It has a violin-shaped mark on its back.', 'Its name means it likes to be alone.'] },
    { n: 'Brazilian wandering spider', alt: ['banana spider', 'armed spider'], sci: 'Phoneutria nigriventer', g: 'wandering', f: f(X, AM, false), d: 2,
      b: 'A large, fast South American spider that hunts on the forest floor at night. It sometimes hides in bunches of bananas.',
      c: ['Its genus name means "murderess" in Greek.', 'It raises its front legs in a threat pose.', 'It roams the forest floor at night.', 'It has been found hiding in banana shipments.', 'It comes from the largest country in South America.'] },
    { n: 'Six-eyed sand spider', sci: 'Hexophthalma hahni', g: 'recluse', f: f(D, AF, false), d: 3,
      b: 'A flat spider of southern African deserts that buries itself in sand to ambush prey. It can live a year without food.',
      c: ['It is related to the recluse spiders.', 'It can survive for a year without eating.', 'It lives in the deserts of southern Africa.', 'It flicks sand over itself to hide.', 'It has fewer eyes than most spiders.'] },
    { n: 'Goliath birdeater', sci: 'Theraphosa blondi', g: 'tarantula', f: { danger: M, region: AM, web: false, legSpanCm: 28 }, d: 1, look: ['Mexican red-knee tarantula'],
      b: 'The heaviest spider in the world, from South American rainforests. Despite its name, it rarely eats birds.',
      c: ['It can weigh as much as 175 grams.', 'It flicks itchy hairs off its belly to defend itself.', 'It can make a hissing sound by rubbing its legs.', 'It is the heaviest spider in the world.', 'It is named after a biblical giant.'] },
    { n: 'Mexican red-knee tarantula', sci: 'Brachypelma hamorii', g: 'tarantula', f: { danger: H, region: AM, web: false, legSpanCm: 15 }, d: 2, look: ['Goliath birdeater', 'Chilean rose tarantula'],
      b: 'A calm, colourful tarantula from Mexico and a favourite pet. Females can live for over 25 years.',
      c: ['Females can live for more than 25 years.', 'It flicks itchy hairs when threatened.', 'It is a popular pet tarantula.', 'Its legs have orange bands at the joints.', 'It comes from the country just south of the USA.'] },
    { n: 'Chilean rose tarantula', sci: 'Grammostola rosea', g: 'tarantula', f: { danger: H, region: AM, web: false, legSpanCm: 13 }, d: 3, look: ['Mexican red-knee tarantula'],
      b: 'A gentle tarantula from South America and one of the most common pet spiders.',
      c: ['It can go without food for months.', 'It is one of the most common pet tarantulas.', 'Its hairs have a pinkish shine.', 'It comes from a long, thin country in South America.', 'It is named after a flower.'] },
    { n: 'Gooty sapphire tarantula', alt: ['peacock tarantula'], sci: 'Poecilotheria metallica', g: 'tarantula', f: { danger: D, region: AS, web: false, legSpanCm: 20 }, d: 3,
      b: 'A bright blue tree-dwelling tarantula from a small patch of forest in India. It is critically endangered.',
      c: ['It was rediscovered in 2001 after more than 100 years.', 'It lives in trees in southern India.', 'It is critically endangered in the wild.', 'Its legs are a bright metallic blue.', 'It is named after a blue gemstone.'] },
    { n: 'European garden spider', alt: ['cross spider'], sci: 'Araneus diadematus', g: 'orb-weaver', f: f(H, EU, true), d: 1, look: ['Australian golden orb-weaver'],
      b: 'The common orb-weaver of European gardens in autumn. It has a white cross of spots on its back.',
      c: ['It eats its old web each day and spins a new one.', 'It is most noticed in autumn.', 'It spins a round, wheel-shaped web.', 'It has a cross of white spots on its back.', 'It is often found in back yards in Europe.'] },
    { n: 'Wasp spider', sci: 'Argiope bruennichi', g: 'orb-weaver', f: f(H, EU, true), d: 1, look: ['Yellow garden spider', 'St Andrew\'s cross spider'],
      b: 'A striking orb-weaver with yellow and black stripes. It has spread north through Europe as the climate has warmed.',
      c: ['It adds a zig-zag band of silk to its web.', 'It has spread into southern Britain.', 'It builds its web low in long grass.', 'It is striped yellow and black.', 'It is named after a stinging insect it looks like.'] },
    { n: 'Yellow garden spider', alt: ['writing spider'], sci: 'Argiope aurantia', g: 'orb-weaver', f: f(H, AM, true), d: 2, look: ['Wasp spider'],
      b: 'A large black-and-yellow orb-weaver of North American gardens. The thick zig-zag in its web inspired the nickname "writing spider".',
      c: ['It often eats its web at night and spins a new one.', 'It is sometimes called the writing spider.', 'Its web has a thick zig-zag down the middle.', 'It is common in North American gardens.', 'It is black and yellow.'] },
    { n: 'Zebra jumping spider', sci: 'Salticus scenicus', g: 'jumping', f: f(H, WW, false), d: 1, look: ['Bold jumping spider'],
      b: 'A small black-and-white jumping spider often seen hunting on sunny walls in Europe and North America.',
      c: ['It has two huge front eyes.', 'It stalks flies on sunny walls.', 'It can leap many times its own length.', 'It is black with white stripes.', 'It is named after a striped African animal.'] },
    { n: 'Bold jumping spider', sci: 'Phidippus audax', g: 'jumping', f: f(H, AM, false), d: 3, look: ['Zebra jumping spider', 'Regal jumping spider'],
      b: 'A fuzzy black jumping spider of North America with shiny green-blue jaws.',
      c: ['Its jaws are shiny metallic green or blue.', 'It has big front eyes and sharp vision.', 'It is black with white spots.', 'It is common in North America.', 'Its name means daring.'] },
    { n: 'Regal jumping spider', sci: 'Phidippus regius', g: 'jumping', f: f(H, AM, false), d: 3, look: ['Bold jumping spider'],
      b: 'The largest jumping spider in eastern North America. Females are often orange or grey.',
      c: ['Females can be bright orange.', 'It is the largest jumping spider in eastern North America.', 'It is often kept as a pet.', 'It lives in Florida and the Caribbean.', 'Its name means royal.'] },
    { n: 'Diving bell spider', alt: ['water spider'], sci: 'Argyroneta aquatica', g: 'water', f: f(H, EU, false), d: 2,
      b: 'The only spider that lives almost its whole life underwater. It breathes from a silk bubble of air it fills itself.',
      c: ['Its genus name means "silver net".', 'It carries air down on its hairy body.', 'It builds a silk bell full of air.', 'It lives in ponds in Europe and Asia.', 'It is the only spider that lives underwater.'] },
    { n: 'Raft spider', sci: 'Dolomedes fimbriatus', g: 'fishing', f: f(H, EU, false), d: 3,
      b: 'A large European spider that sits at the edge of ponds and runs across the water to catch insects and tiny fish.',
      c: ['It can catch small fish and tadpoles.', 'It senses ripples with its front legs.', 'It has a pale stripe down each side.', 'It walks on the surface of ponds.', 'It is named after a floating platform.'] },
    { n: 'Darwin\'s bark spider', sci: 'Caerostris darwini', g: 'orb-weaver', f: f(H, AF, true), d: 3,
      b: 'A spider from Madagascar that spins the biggest webs known, right across rivers. Its silk is the toughest known.',
      c: ['It was described in 2010.', 'Its silk is tougher than Kevlar.', 'Its webs can stretch right across rivers.', 'It lives in Madagascar.', 'It is named after a famous naturalist.'] },
    { n: 'Net-casting spider', alt: ['ogre-faced spider'], sci: 'Deinopis', g: 'net-caster', f: f(H, WW, false), d: 3,
      b: 'A stick-thin spider that holds a small stretchy net in its front legs and throws it over passing insects.',
      c: ['It has two enormous eyes for seeing at night.', 'Its face looks a bit like a monster\'s.', 'It hangs upside down and waits.', 'It holds a stretchy web between its front legs.', 'It throws its web over prey.'] },
    { n: 'Goldenrod crab spider', sci: 'Misumena vatia', g: 'crab', f: f(H, WW, false), d: 2,
      b: 'A crab spider that waits on flowers to grab bees and butterflies. It can slowly change between white and yellow.',
      c: ['It can change colour between white and yellow.', 'It ambushes bees on flowers.', 'Its front legs are long and held open.', 'It walks sideways like a crab.', 'It is named after a yellow flower.'] },
    { n: 'Spiny orb-weaver', alt: ['spiny-backed orb-weaver'], sci: 'Gasteracantha cancriformis', g: 'orb-weaver', f: f(H, AM, true), d: 2,
      b: 'A small orb-weaver with a hard, colourful shell and six spikes. It is common in warm parts of the Americas.',
      c: ['Its body is shaped a bit like a crab.', 'Its shell can be white, yellow or red with black spots.', 'It has six red spikes.', 'It builds round webs in gardens.', 'Its back is covered in spikes.'] },
    { n: 'False widow spider', alt: ['noble false widow'], sci: 'Steatoda nobilis', g: 'widow', f: f(M, EU, true), d: 2, look: ['Black widow', 'Redback spider'],
      b: 'A spider from the Canary Islands that has spread across Britain and Europe. Its bite hurts but is rarely serious.',
      c: ['It probably came from the Canary Islands.', 'It is now common in British homes.', 'It has a cream pattern like a skull on its back.', 'It looks a bit like a widow spider.', 'It is the most venomous spider in Britain.'] },
    { n: 'Giant house spider', sci: 'Eratigena atrica', g: 'funnel-weaver', f: f(H, EU, true), d: 2, look: ['Hobo spider'],
      b: 'A big, fast, long-legged spider that appears in European homes in autumn. It is one of the fastest spiders.',
      c: ['Males go looking for females in autumn.', 'It builds sheet webs with a funnel in a corner.', 'It is one of the fastest-running spiders.', 'It is often found in baths.', 'It is a large spider found indoors.'] },
    { n: 'Hobo spider', sci: 'Eratigena agrestis', g: 'funnel-weaver', f: f(H, EU, true), d: 3, look: ['Giant house spider'],
      b: 'A brown funnel-weaver from Europe that spread to the north-western USA. It was wrongly blamed for nasty bites.',
      c: ['It was wrongly blamed for skin wounds in the USA.', 'It reached the north-western USA in the 1930s.', 'It builds funnel webs near the ground.', 'It is brown with a herringbone pattern.', 'Its name is a word for a wandering worker.'] },
    { n: 'Woodlouse spider', sci: 'Dysdera crocata', g: 'hunter', f: f(H, WW, false), d: 3,
      b: 'A reddish spider with huge jaws that hunts woodlice, which most other spiders avoid.',
      c: ['Its jaws are huge for its size.', 'It hides under stones and logs by day.', 'Its legs and head are reddish.', 'Its body is pale and shiny.', 'It eats small grey crustaceans that roll into balls.'] },
    { n: 'Indian ornamental tarantula', sci: 'Poecilotheria regalis', g: 'tarantula', f: { danger: D, region: AS, web: false, legSpanCm: 18 }, d: 3, look: ['Gooty sapphire tarantula'],
      b: 'A fast, tree-dwelling tarantula from India with bold grey, black and yellow patterns.',
      c: ['Its bite can cause strong cramps.', 'It lives in holes in trees.', 'Underneath, its front legs are bright yellow.', 'It comes from southern India.', 'Its name means decorative.'] },
    { n: 'Jumping spider', sci: 'Salticidae', g: 'jumping', f: f(H, WW, false), d: 1, look: ['Zebra jumping spider', 'Peacock spider'],
      b: 'Small spiders with big front eyes that stalk and pounce on insects. They have some of the best eyesight of any small animal.',
      c: ['They are the largest family of spiders, with over 6,000 kinds.', 'They tie a silk safety line before each leap.', 'They have excellent eyesight.', 'Two of their eyes are huge and face forward.', 'They leap onto their prey.'] },
    { n: 'Tarantula', sci: 'Theraphosidae', g: 'tarantula', f: f(H, WW, false), d: 1, look: ['Goliath birdeater', 'Mexican red-knee tarantula'],
      b: 'Big, hairy spiders found in warm places around the world. Many are kept as pets and live for many years.',
      c: ['Some flick itchy hairs at attackers.', 'Females of some kinds live for over 20 years.', 'They moult their whole skin as they grow.', 'Many are kept as pets.', 'They are very big and hairy.'] },
    { n: 'Money spider', sci: 'Linyphiidae', g: 'sheet-weaver', f: f(H, WW, true), d: 1,
      b: 'Tiny spiders that are said to bring good luck if one lands on you. Babies float through the air on threads of silk.',
      c: ['They are often only 2 or 3 millimetres long.', 'They spin flat sheet webs in grass.', 'Young ones fly long distances on silk threads.', 'On misty autumn mornings their webs cover fields.', 'Folklore says one landing on you brings riches.'] },
  ],
  fakes: ['Crimson funnel-web', 'Glass-backed widow', 'Silver huntsman tarantula', 'Desert lantern spider', 'Velvet trapdoor weaver', 'Thunder orb-weaver', 'Blue-fanged recluse', 'Shadow wolf tarantula'],
  questions: [
    { kind: 'number', prompt: 'How many legs does a spider have?', answer: 8, unit: 'legs', tolerance: 0, explain: 'All spiders have eight legs; insects have six.', difficulty: 1 },
    { kind: 'tf', prompt: 'Spiders are insects.', answer: false, explain: 'Spiders are arachnids: eight legs and two body parts.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which is the heaviest spider in the world?', answer: 'Goliath birdeater', wrong: ['Huntsman spider', 'Sydney funnel-web spider', 'Mexican red-knee tarantula'], explain: 'Goliath birdeaters can weigh about 175 g.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which Australian spider\'s male venom is far more dangerous than the female\'s?', answer: 'Sydney funnel-web spider', wrong: ['Redback spider', 'Huntsman spider', 'White-tailed spider'], explain: 'A toxin found mainly in males is deadly to primates.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which spider lives almost its whole life underwater in a bubble of air?', answer: 'Diving bell spider', wrong: ['Raft spider', 'Wolf spider', 'Huntsman spider'], explain: 'It builds a silk "bell" and fills it with air.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which mark is found under the belly of a female black widow?', answer: 'A red hourglass', wrong: ['A white cross', 'A blue spot', 'A yellow stripe'], explain: 'The red hourglass is the classic widow marking.', difficulty: 1 },
    { kind: 'tf', prompt: 'All spiders spin webs to catch their food.', answer: false, explain: 'Many, like jumping, wolf and huntsman spiders, hunt without a web.', difficulty: 1 },
    { kind: 'mc', prompt: 'How many eyes do most spiders have?', answer: '8', wrong: ['2', '4', '12'], explain: 'Most have eight eyes; recluse spiders have six.', difficulty: 2 },
    { kind: 'tf', prompt: 'Wolf spider mothers carry their babies on their backs.', answer: true, explain: 'The spiderlings ride on her back for days.', difficulty: 2 },
    { kind: 'mc', prompt: 'Spiders belong to which group of animals?', answer: 'Arachnids', wrong: ['Insects', 'Crustaceans', 'Reptiles'], explain: 'Arachnids include spiders, scorpions, ticks and mites.', difficulty: 2 },
  ],
};
