import { INAT, WD } from './_common.mjs';

const EU = 'Europe', NA = 'North America', AS = 'Asia', AU = 'Australia', AF = 'Africa', SA = 'South America', NZ = 'New Zealand', MED = 'the Mediterranean', TR = 'the tropics', ME = 'the Middle East';
const f = (region, evergreen, conifer, heightM) => ({ region, evergreen, conifer, ...(heightM ? { heightM } : {}) });

export default {
  id: 'trees', title: 'Trees', theme: 'nature', icon: '🌳', kids: true,
  leakExempt: ['tree', 'trees'],
  wikiD1: true, wikiAll: true, autoTaxo: ['family', 'genus'],
  ranges: { heightM: [3, 120] },
  factsMeta: {
    region: { type: 'cat', label: 'Native to', clue: v => `It is native to ${v}.` },
    evergreen: { type: 'bool', label: 'Evergreen', yes: 'Evergreen', no: 'Loses its leaves', clue: v => (v ? 'It keeps its leaves all year.' : 'It loses its leaves each year.') },
    conifer: { type: 'bool', label: 'Conifer', yes: 'Conifer', no: 'Not a conifer', clue: v => (v ? 'It is a conifer.' : null) },
    heightM: { type: 'num', label: 'Typical mature height', unit: 'm', higherLabel: 'Taller', clue: v => `It typically grows to about ${v} m tall.` },
  },
  imgPrompt: "Which of these is {aName}?",
  nameImgPrompt: "Which tree is this?",
  tfImgPrompt: "This is {aName}.",
  tpl: {"region": {"ask": "Where is the {lname} native to?", "askReverse": "Which of these trees is native to {value}?", "stmt": "The {lname} is native to {value}.", "exclusive": false}, "evergreen": {"askBool": "Which of these trees keeps its leaves all year?", "stmt": "The {lname} keeps its leaves all year."}, "conifer": {"askBool": "Which of these trees is a conifer?", "stmt": "The {lname} is a conifer."}, "heightM": {"askHigh": "Which of these trees grows the tallest?", "askLow": "Which of these trees is the smallest?"}},
  sources: [INAT, WD],
  items: [
    { n: 'English oak', alt: ['oak', 'pedunculate oak', 'common oak'], sci: 'Quercus robur', g: 'broadleaf', f: f(EU, false, false, 30), d: 1, look: ['Cork oak'],
      b: 'A big, long-lived tree that grows acorns. One oak can be home to hundreds of kinds of insects.',
      c: ['It can support over 2,000 other species.', 'Some living ones are over 1,000 years old.', 'Its leaves have rounded lobes.', 'It was used to build wooden warships.', 'Its nuts are called acorns.'] },
    { n: 'Silver birch', alt: ['birch'], sci: 'Betula pendula', g: 'broadleaf', f: f(EU, false, false, 25), d: 1,
      b: 'A slender tree with white, papery bark and drooping twigs. It is one of the first trees to grow on bare land.',
      c: ['It is a pioneer tree that colonises cleared land.', 'Its sap can be tapped and drunk in spring.', 'Its twigs droop at the tips.', 'Its leaves are small and triangular.', 'Its bark is white and papery.'] },
    { n: 'European beech', alt: ['beech', 'common beech'], sci: 'Fagus sylvatica', g: 'broadleaf', f: f(EU, false, false, 35), d: 2,
      b: 'A tall tree with smooth grey bark. Its dense leaves make beech woods dark and shady.',
      c: ['Young trees often keep dead leaves through winter.', 'Its nuts are called mast.', 'Its bark is smooth and grey.', 'It is often grown as a hedge.', 'Its name begins like a sandy seaside.'] },
    { n: 'Horse chestnut', alt: ['conker tree'], sci: 'Aesculus hippocastanum', g: 'broadleaf', f: f(EU, false, false, 30), d: 1,
      b: 'A big tree with leaves like an open hand and spiky cases holding shiny brown seeds called conkers.',
      c: ['It comes from the Balkans.', 'Its flowers stand up like candles in spring.', 'Its leaves have five to seven leaflets like fingers.', 'Children play a game with its seeds on strings.', 'Its shiny brown seeds are called conkers.'] },
    { n: 'Sugar maple', alt: ['maple'], sci: 'Acer saccharum', g: 'broadleaf', f: f(NA, false, false, 30), d: 1, look: ['Japanese maple'],
      b: 'A North American tree whose sap is boiled down to make maple syrup. Its leaves turn brilliant colours in autumn.',
      c: ['It takes about 40 litres of sap to make 1 litre of syrup.', 'Its leaves turn orange and red in autumn.', 'Its seeds spin like helicopters.', 'Its leaf is on the flag of Canada.', 'Its sap makes a sweet syrup for pancakes.'] },
    { n: 'Japanese maple', sci: 'Acer palmatum', g: 'broadleaf', f: f(AS, false, false, 8), d: 2, look: ['Sugar maple'],
      b: 'A small, graceful tree with finely cut leaves that turn fiery red in autumn. It is popular in gardens.',
      c: ['Thousands of garden varieties exist.', 'Its leaves look like little hands.', 'It is often used for bonsai.', 'Its leaves turn bright red in autumn.', 'It comes from Japan, Korea and China.'] },
    { n: 'Weeping willow', alt: ['willow'], sci: 'Salix babylonica', g: 'broadleaf', f: f(AS, false, false, 15), d: 1,
      b: 'A tree with long, drooping branches that often grows by rivers and lakes.',
      c: ['Willow bark gave us the idea for aspirin.', 'It comes from northern China.', 'It grows well near water.', 'Its long branches hang down to the ground.', 'Its name sounds sad, as if it is crying.'] },
    { n: 'Scots pine', sci: 'Pinus sylvestris', g: 'conifer', f: f(EU, true, true, 30), d: 2, look: ['Norway spruce'],
      b: 'A pine with orange-red bark near the top and blue-green needles in pairs. It is often called Scotland\'s national tree.',
      c: ['Its upper bark is orange-red.', 'Its needles grow in pairs.', 'It is the only native timber pine of Britain.', 'It is often called Scotland\'s national tree.', 'It is a pine with a Scottish name.'] },
    { n: 'Norway spruce', alt: ['Christmas tree', 'spruce'], sci: 'Picea abies', g: 'conifer', f: f(EU, true, true, 40), d: 1, look: ['Scots pine'],
      b: 'A tall, cone-shaped conifer. It is the traditional Christmas tree in Europe.',
      c: ['Norway gives one to London every year for Trafalgar Square.', 'Its wood is used to make violins.', 'Its cones hang downwards.', 'It is shaped like a cone.', 'It is a traditional Christmas tree.'] },
    { n: 'Coast redwood', alt: ['redwood', 'California redwood'], sci: 'Sequoia sempervirens', g: 'conifer', f: f(NA, true, true, 90), d: 1, look: ['Giant sequoia'],
      b: 'The tallest tree in the world. The tallest one, named Hyperion, is over 115 metres tall.',
      c: ['The tallest known one is called Hyperion.', 'It gets water from fog.', 'Its thick bark resists fire.', 'It grows on the coast of California.', 'It is the tallest tree in the world.'] },
    { n: 'Giant sequoia', alt: ['giant redwood', 'Wellingtonia'], sci: 'Sequoiadendron giganteum', g: 'conifer', f: f(NA, true, true, 80), d: 2, look: ['Coast redwood'],
      b: 'The biggest tree in the world by volume. The largest, General Sherman, is over 2,000 years old.',
      c: ['The heat of fires helps its cones release seeds.', 'The biggest one is called General Sherman.', 'It can live for over 3,000 years.', 'It grows in California\'s Sierra Nevada.', 'It is the biggest tree in the world by volume.'] },
    { n: 'Douglas fir', sci: 'Pseudotsuga menziesii', g: 'conifer', f: f(NA, true, true, 70), d: 2,
      b: 'A huge conifer of western North America and a very important timber tree. Its cones have three-pointed bracts.',
      c: ['It is named after the Scottish botanist David Douglas.', 'Its cones have three-pointed "mouse tails" sticking out.', 'It is a popular Christmas tree in the USA.', 'It is one of the world\'s most important timber trees.', 'It is not a true fir.'] },
    { n: 'Monkey puzzle tree', alt: ['monkey puzzle', 'Chilean pine'], sci: 'Araucaria araucana', g: 'conifer', f: f(SA, true, true, 30), d: 2,
      b: 'A strange conifer from Chile covered in sharp, scale-like leaves. It is said that even a monkey would find it puzzling to climb.',
      c: ['It is the national tree of Chile.', 'Its seeds were a staple food of the Mapuche people.', 'Its leaves are hard, sharp triangles.', 'It is a "living fossil" from dinosaur times.', 'Its name suggests an animal would find it hard to climb.'] },
    { n: 'Ginkgo', alt: ['maidenhair tree', 'gingko'], sci: 'Ginkgo biloba', g: 'ancient', f: f(AS, false, false, 25), d: 2,
      b: 'A "living fossil" tree with fan-shaped leaves. Six survived the Hiroshima atomic bomb.',
      c: ['Some survived the Hiroshima atomic bomb.', 'Its seeds smell like rotten butter.', 'It has no close living relatives.', 'Its leaves turn golden yellow in autumn.', 'Its leaves are shaped like fans.'] },
    { n: 'African baobab', alt: ['baobab'], sci: 'Adansonia digitata', g: 'broadleaf', f: f(AF, false, false, 20), d: 1, look: ['Boab'],
      b: 'A huge, thick-trunked African tree that stores water in its trunk. It is called the "upside-down tree".',
      c: ['Its fruit is called monkey bread.', 'Some are thought to be over 2,000 years old.', 'Its trunk stores water.', 'It is called the "upside-down tree".', 'Its trunk is very fat and its branches look like roots.'] },
    { n: 'Boab', alt: ['Australian baobab'], sci: 'Adansonia gregorii', g: 'broadleaf', f: f(AU, false, false, 12), d: 2, look: ['African baobab'],
      b: 'Australia\'s only baobab, found in the Kimberley. One hollow boab was used as a prison.',
      c: ['A hollow one near Derby is called the "Prison Tree".', 'It loses its leaves in the dry season.', 'It grows in the Kimberley region.', 'Its trunk is bottle-shaped.', 'It is the Australian cousin of the African baobab.'] },
    { n: 'Mountain ash', wp: 'Eucalyptus regnans', alt: ['swamp gum', 'Victorian ash'], sci: 'Eucalyptus regnans', g: 'eucalypt', f: f(AU, true, false, 85), d: 2,
      b: 'The tallest flowering plant in the world, a giant eucalypt of Victoria and Tasmania.',
      c: ['The tallest known one, Centurion, is about 100 m tall.', 'It is killed by fire but its seeds sprout afterwards.', 'It grows in Victoria and Tasmania.', 'It is the tallest flowering plant.', 'It is a giant gum tree.'] },
    { n: 'River red gum', alt: ['red gum'], sci: 'Eucalyptus camaldulensis', g: 'eucalypt', f: f(AU, true, false, 30), d: 2,
      b: 'A big, spreading gum tree that grows along rivers across Australia. It can drop heavy branches without warning.',
      c: ['It is the most widespread eucalypt in Australia.', 'It can drop big branches without warning.', 'Hollows in it are homes for birds and possums.', 'It grows along inland rivers like the Murray.', 'Its wood is red.'] },
    { n: 'Tasmanian blue gum', alt: ['blue gum', 'eucalyptus'], sci: 'Eucalyptus globulus', g: 'eucalypt', f: f(AU, true, false, 45), d: 1,
      b: 'A fast-growing eucalypt with blue-grey young leaves. Its oil is used in cough sweets and inhalers.',
      c: ['It is planted for timber and paper around the world.', 'Its young leaves are round and blue-grey.', 'Its oil is used in cough medicines.', 'It is the floral emblem of Tasmania.', 'Koalas eat leaves from trees like it.'] },
    { n: 'Snow gum', sci: 'Eucalyptus pauciflora', g: 'eucalypt', f: f(AU, true, false, 10), d: 3,
      b: 'A twisted, colourful gum tree that grows high in the Australian Alps, where it survives snow and freezing winds.',
      c: ['Its bark is streaked with red, green and cream.', 'It grows higher up mountains than any other eucalypt.', 'It often has twisted, crooked trunks.', 'It grows in the Snowy Mountains.', 'Its name includes winter weather.'] },
    { n: 'Moreton Bay fig', sci: 'Ficus macrophylla', g: 'fig', f: f(AU, true, false, 40), d: 2, look: ['Banyan'],
      b: 'A huge fig tree of eastern Australia with buttress roots. It often starts life growing on another tree.',
      c: ['It often starts as a seed in another tree\'s branches.', 'A tiny wasp pollinates it.', 'It has huge buttress roots.', 'It is planted in parks across Australia.', 'It is named after a bay near Brisbane.'] },
    { n: 'Wollemi pine', sci: 'Wollemia nobilis', g: 'conifer', f: f(AU, true, true, 35), d: 2,
      b: 'A "dinosaur tree" known only from fossils until 1994, when a few were found in a hidden gorge near Sydney.',
      c: ['Firefighters saved the wild trees during the 2019 bushfires.', 'Its location is kept secret.', 'It was found in 1994 by a bushwalker.', 'Fewer than 100 grow in the wild.', 'It is called the "dinosaur tree".'] },
    { n: 'Jacaranda', sci: 'Jacaranda mimosifolia', g: 'broadleaf', f: f(SA, false, false, 15), d: 1,
      b: 'A tree covered in purple-blue flowers in late spring. In Australia, students say it blooms at exam time.',
      c: ['Grafton in New South Wales holds a festival for it.', 'It comes from South America.', 'Students joke that it blooms at exam time.', 'Its fallen flowers make purple carpets.', 'It is covered in purple flowers.'] },
    { n: 'Coconut palm', noAutoImg: true, files: ['Koh Mak (island), Thailand, Palm tree on the beach.jpg', 'Koh Samui Lipa Noi2.jpg'], alt: ['coconut tree'], sci: 'Cocos nucifera', g: 'palm', f: f(TR, true, false, 25), d: 1, look: ['Date palm'],
      b: 'A tall tropical palm that grows coconuts. Coconuts can float across oceans to new beaches.',
      c: ['Its seeds can float across oceans.', 'Every part of it can be used by people.', 'It grows on tropical beaches.', 'Its fruit holds sweet water.', 'Its fruit is a big hairy nut.'] },
    { n: 'Date palm', sci: 'Phoenix dactylifera', g: 'palm', f: f(ME, true, false, 20), d: 2, look: ['Coconut palm'],
      b: 'A desert palm that has been grown for its sweet fruit for thousands of years.',
      c: ['A seed 2,000 years old was grown into a tree.', 'It has been farmed for about 7,000 years.', 'It grows in desert oases.', 'Its sweet fruit grows in big bunches.', 'Its fruit shares a name with a day on the calendar.'] },
    { n: 'Banyan', alt: ['banyan tree'], sci: 'Ficus benghalensis', g: 'fig', f: f(AS, true, false, 25), d: 2, look: ['Moreton Bay fig'],
      b: 'A fig tree that drops roots from its branches, which become new trunks. One banyan can cover a whole field.',
      c: ['One in India covers about 1.9 hectares.', 'It is the national tree of India.', 'Its hanging roots become new trunks.', 'It spreads out like a forest from one tree.', 'It is a kind of fig.'] },
    { n: 'Olive tree', noAutoImg: true, files: ['Olea europaea Preveli 01.JPG', 'Olea europaea, Murviel-lès-Béziers.jpg'], alt: ['olive'], sci: 'Olea europaea', g: 'broadleaf', f: f(MED, true, false, 10), d: 1,
      b: 'A twisted, silvery-leaved tree of the Mediterranean. Its fruit is pressed to make oil.',
      c: ['Some are thought to be over 2,000 years old.', 'Its branch is a symbol of peace.', 'Its leaves are silvery underneath.', 'Its fruit is pressed for oil.', 'It grows around the Mediterranean.'] },
    { n: 'Japanese cherry', alt: ['cherry blossom', 'sakura'], sci: 'Prunus serrulata', g: 'broadleaf', f: f(AS, false, false, 10), d: 1,
      b: 'A tree famous for clouds of pink and white blossom in spring. In Japan, people hold picnics under it.',
      c: ['Washington DC holds a festival for trees gifted by Japan.', 'Its flowers last only about a week.', 'Japanese picnics under it are called hanami.', 'It is a symbol of spring in Japan.', 'It is covered in pink blossom.'] },
    { n: 'Apple tree', alt: ['apple'], sci: 'Malus domestica', g: 'broadleaf', f: f(AS, false, false, 6), d: 1,
      b: 'A fruit tree first grown in Central Asia. There are thousands of kinds of apple.',
      c: ['Its wild ancestor comes from Kazakhstan.', 'There are over 7,000 varieties.', 'A falling fruit is said to have inspired Isaac Newton.', 'Its blossom is pink and white.', 'It grows a crunchy red or green fruit.'] },
    { n: 'Golden wattle', alt: ['wattle'], sci: 'Acacia pycnantha', g: 'wattle', f: f(AU, true, false, 6), d: 1,
      b: 'A small tree covered in fluffy golden flowers. It is Australia\'s national flower.',
      c: ['Australia celebrates it on 1 September.', 'Its leaves are really flattened stems.', 'It is a kind of acacia.', 'It is Australia\'s floral emblem.', 'It is covered in fluffy golden flowers.'] },
    { n: 'Norfolk Island pine', sci: 'Araucaria heterophylla', g: 'conifer', f: f(AU, true, true, 50), d: 2, look: ['Monkey puzzle tree'],
      b: 'A tall, symmetrical conifer from Norfolk Island that lines many beaches in Australia.',
      c: ['Captain Cook hoped to use it for ship masts.', 'It leans towards the equator.', 'Its branches grow in neat tiers.', 'It lines many Australian beaches.', 'It comes from a small Pacific island.'] },
    { n: 'Kauri', alt: ['New Zealand kauri'], sci: 'Agathis australis', g: 'conifer', f: f(NZ, true, true, 40), d: 3,
      b: 'A giant New Zealand conifer. The biggest, Tāne Mahuta, is thought to be well over 1,000 years old.',
      c: ['Its gum was dug up and sold for varnish.', 'The biggest is called Tāne Mahuta, "lord of the forest".', 'It is threatened by kauri dieback disease.', 'Its trunk has no branches until high up.', 'It is a giant tree of New Zealand.'] },
    { n: 'Rowan', alt: ['mountain ash', 'European rowan'], sci: 'Sorbus aucuparia', g: 'broadleaf', f: f(EU, false, false, 12), d: 2,
      b: 'A small tree with clusters of bright red berries in autumn. Folklore says it protects against witches.',
      c: ['Folklore says it protects against witches.', 'Birds love its berries.', 'It grows high up on mountains.', 'Its leaves are feather-like.', 'It has bunches of bright red berries.'] },
    { n: 'English yew', alt: ['yew', 'common yew'], sci: 'Taxus baccata', g: 'conifer', f: f(EU, true, true, 15), d: 2,
      b: 'A dark, long-lived evergreen often found in churchyards. Almost every part of it is poisonous.',
      c: ['Its wood was used for longbows.', 'A cancer drug was made from yews.', 'Almost every part is poisonous.', 'It is often found in churchyards.', 'Some are thought to be thousands of years old.'] },
    { n: 'Holly', alt: ['English holly'], sci: 'Ilex aquifolium', g: 'broadleaf', f: f(EU, true, false, 10), d: 1,
      b: 'An evergreen with shiny, spiky leaves and red berries. It is used as a Christmas decoration.',
      c: ['Only female trees have berries.', 'Its berries are poisonous to people.', 'Higher leaves are often less spiky.', 'It is a Christmas decoration.', 'It has spiky leaves and red berries.'] },
    { n: 'London plane', alt: ['plane tree'], sci: 'Platanus × hispanica', inat: 'Platanus × hispanica', g: 'broadleaf', f: f(EU, false, false, 30), d: 3,
      b: 'A tough city tree with patchy, flaking bark. It lines the streets of London and many other cities.',
      c: ['It is a hybrid of two other trees.', 'Its seeds hang like little spiky balls.', 'Its bark flakes off in patches.', 'It copes well with city pollution.', 'It lines the streets of the UK capital.'] },
    { n: 'Cedar of Lebanon', alt: ['Lebanon cedar'], sci: 'Cedrus libani', g: 'conifer', f: f(ME, true, true, 35), d: 2,
      b: 'A majestic conifer with flat, spreading layers of branches. It appears on the flag of Lebanon.',
      c: ['Its wood was used in ancient temples.', 'Its branches grow in flat layers.', 'It is mentioned in the Bible.', 'Its cones sit upright like barrels.', 'It appears on the flag of a Middle Eastern country.'] },
    { n: 'Great Basin bristlecone pine', alt: ['bristlecone pine'], sci: 'Pinus longaeva', g: 'conifer', f: f(NA, true, true, 10), d: 3,
      b: 'A twisted pine of the American West. One called Methuselah is over 4,800 years old.',
      c: ['One called Methuselah is over 4,800 years old.', 'It grows high in the mountains of Nevada and California.', 'Its needles can last 40 years.', 'Its trunk is twisted and weathered.', 'It is one of the oldest living things on Earth.'] },
    { n: 'Dragon\'s blood tree', ln: 'dragon\'s blood tree', alt: ['Socotra dragon tree'], sci: 'Dracaena cinnabari', g: 'broadleaf', f: f(ME, true, false, 10), d: 3,
      b: 'An umbrella-shaped tree from the island of Socotra. Its red resin was used as dye and medicine.',
      c: ['It grows only on the island of Socotra.', 'Its red resin was used as medicine and dye.', 'Its crown is shaped like an upturned umbrella.', 'It is named after a mythical beast\'s red resin.', 'Its sap is red, like blood.'] },
    { n: 'Joshua tree', sci: 'Yucca brevifolia', g: 'yucca', f: f(NA, true, false, 10), d: 2,
      b: 'A spiky desert tree of the Mojave Desert. Mormon settlers named it after Joshua from the Bible.',
      c: ['A rock band named an album after it.', 'A small moth pollinates it.', 'It grows only in the Mojave Desert.', 'It is a kind of yucca.', 'It is named after a figure from the Bible.'] },
    { n: 'Cork oak', sci: 'Quercus suber', g: 'broadleaf', f: f(MED, true, false, 20), d: 2, look: ['English oak'],
      b: 'An evergreen oak whose thick bark is peeled off every nine years or so to make wine corks.',
      c: ['Portugal produces about half the world\'s supply of its product.', 'Its bark is stripped every nine years or so.', 'Stripping the bark does not kill it.', 'It is an evergreen oak.', 'Its bark is used to seal wine bottles.'] },
    { n: 'Southern magnolia', alt: ['magnolia'], sci: 'Magnolia grandiflora', g: 'broadleaf', f: f(NA, true, false, 25), d: 2,
      b: 'An evergreen tree of the south-eastern USA with huge, scented white flowers and glossy leaves.',
      c: ['Magnolias appeared before bees existed and are pollinated by beetles.', 'It is the state flower of Mississippi.', 'Its leaves are glossy and leathery.', 'Its white flowers are huge and scented.', 'Its name begins with "magno".'] },
    { n: 'Rubber tree', alt: ['Pará rubber tree'], sci: 'Hevea brasiliensis', g: 'broadleaf', f: f(SA, true, false, 30), d: 2,
      b: 'A tree from the Amazon whose milky sap, called latex, is made into natural rubber.',
      c: ['Seeds were smuggled from Brazil to Asia in 1876.', 'Most natural rubber now comes from South-East Asia.', 'Its milky sap is called latex.', 'Workers cut its bark to collect sap.', 'Its sap makes tyres and balloons.'] },
  ],
  fakes: ['Silver thorn cedar', 'Crimson bark redwood', 'Golden fan pine', 'Northern glass birch', 'Spotted ghost oak', 'Velvet-leaf mountain gum'],
  questions: [
    { kind: 'mc', prompt: 'What is the tallest kind of tree in the world?', answer: 'Coast redwood', wrong: ['Giant sequoia', 'Mountain ash', 'Douglas fir'], explain: 'The tallest known, Hyperion, is over 115 m.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which tree\'s leaf is on the flag of Canada?', answer: 'Maple', wrong: ['Oak', 'Birch', 'Pine'], explain: 'The red maple leaf became the flag in 1965.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which tree grows acorns?', answer: 'Oak', wrong: ['Pine', 'Willow', 'Palm'], explain: 'Acorns are oak nuts.', difficulty: 1 },
    { kind: 'mc', prompt: 'What do you call a tree that keeps its leaves all year?', answer: 'Evergreen', wrong: ['Deciduous', 'Conifer', 'Perennial'], explain: 'Deciduous trees drop their leaves each year.', difficulty: 1 },
    { kind: 'mc', prompt: 'What gas do trees take in to make food?', answer: 'Carbon dioxide', wrong: ['Oxygen', 'Helium', 'Nitrogen'], explain: 'Photosynthesis uses carbon dioxide, water and sunlight, and releases oxygen.', difficulty: 1 },
    { kind: 'mc', prompt: 'You can tell a tree\'s age by counting what?', answer: 'Its growth rings', wrong: ['Its leaves', 'Its branches', 'Its roots'], explain: 'Most trees add one ring of wood a year.', difficulty: 1 },
    { kind: 'mc', prompt: 'Which tree, known only from fossils, was found alive near Sydney in 1994?', answer: 'Wollemi pine', wrong: ['Monkey puzzle tree', 'Ginkgo', 'Kauri'], explain: 'Fewer than 100 grow in the wild, in a secret gorge.', difficulty: 2 },
    { kind: 'mc', prompt: 'Which tree\'s bark is used to make wine corks?', answer: 'Cork oak', wrong: ['Birch', 'Yew', 'Plane'], explain: 'It can be stripped every nine years or so without killing the tree.', difficulty: 2 },
    { kind: 'tf', prompt: 'Maple syrup is made from tree sap.', answer: true, explain: 'Sap from sugar maples is boiled down.', difficulty: 1 },
    { kind: 'mc', prompt: 'What is Australia\'s national floral emblem?', answer: 'Golden wattle', wrong: ['Waratah', 'Jacaranda', 'Eucalyptus'], explain: 'It was proclaimed in 1988; Wattle Day is 1 September.', difficulty: 2 },
  ],
};
