// Merge the per-stage manifests into game/assets/atlas.json — the single file the game reads.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WORK = path.join(ROOT, 'work');
const OUT = path.join(ROOT, '..', 'game', 'assets');

const read = f => fs.existsSync(path.join(WORK, f)) ? JSON.parse(fs.readFileSync(path.join(WORK, f))) : null;
const bg = read('bg_manifest.json') || {};
const props = read('props_manifest.json') || { props: null, debris: null, materials: {} };
const terr = read('terrain_manifest.json') || { terrain: null, kinds: {}, decals: [] };

const atlases = {};
const addAtlas = (name, a) => {
  if (!a) return;
  atlases[name] = { image: a.image, w: a.w, h: a.h, frames: a.frames };
};
addAtlas('props', props.props);
addAtlas('debris', props.debris);
addAtlas('terrain', terr.terrain);

const backgrounds = {};
for (const [loc, rec] of Object.entries(bg)) {
  backgrounds[loc] = {
    bands: rec.bands.map(b => ({
      id: b.id, image: b.image, w: b.w, h: b.h,
      layer: { sky: 'SKY', far: 'BG_FAR', mid: 'BG_MID', near: 'BG_NEAR', fg: 'FG_OCCLUDE' }[b.id.split('_').pop()],
      tile: true, parallax: b.parallax,
      worldW: b.worldW, worldH: b.worldH, anchorY: b.anchorY,
    })),
  };
}

const manifest = {
  version: 1,
  note: 'Generated by art/tools/build_*.js. Do not hand-edit; edit the builders and re-run.',
  atlases,
  backgrounds,
  materials: props.materials || {},
  composites: props.composites || {},
  terrain: terr.kinds || {},
  decals: terr.decals || [],
  // id -> [id, id_v1, ...]: interchangeable readings of the same element, all lit to the
  // same key. Scatter code MUST pick from these rather than stamping one frame repeatedly.
  variants: props.variants || {},
};

fs.writeFileSync(path.join(OUT, 'atlas.json'), JSON.stringify(manifest, null, 1));

let total = 0;
const walk = d => {
  for (const f of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, f.name);
    if (f.isDirectory()) walk(p); else total += fs.statSync(p).size;
  }
};
walk(OUT);
console.log(`atlas.json written — ${Object.keys(atlases).length} atlases, ` +
            `${Object.keys(backgrounds).length} locations, ${Object.keys(manifest.materials).length} destructibles`);
console.log(`TOTAL SHIPPED PAYLOAD: ${(total / 1048576).toFixed(2)} MB`);
