#!/usr/bin/env node
/**
 * Builds js/data/music.js from assets/audio/music/tracks.json + whatever mp3s actually exist.
 *
 * The music agent writes tracks.json (metadata it knows: name, context, intensity, bpm, key).
 * This walks the real files, drops any entry whose file is missing, measures each one, and
 * emits the manifest the game and the settings screen read. Regenerate after every music batch.
 *
 *   node tools/build_music_manifest.mjs [--check]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'assets/audio/music');
const META = join(DIR, 'tracks.json');
const OUT = join(ROOT, 'js/data/music.js');
const check = process.argv.includes('--check');

const CONTEXTS = ['title', 'battle', 'boss', 'hangar', 'sting_win', 'sting_lose'];

const meta = existsSync(META) ? JSON.parse(readFileSync(META, 'utf8')) : {};
const files = existsSync(DIR)
  ? readdirSync(DIR).filter((f) => f.endsWith('.mp3') && !f.startsWith('probe_')).sort()
  : [];

const dur = (f) => {
  try {
    return Math.round(Number(execFileSync('ffprobe',
      ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f], { encoding: 'utf8' }).trim()));
  } catch { return 0; }
};
const loud = (f) => {
  try {
    const o = execFileSync('ffmpeg', ['-i', f, '-af', 'volumedetect', '-f', 'null', '-'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return Number((o.match(/mean_volume:\s*(-?[\d.]+)/) || [])[1] ?? 0);
  } catch (e) {
    const m = String(e.stderr || '').match(/mean_volume:\s*(-?[\d.]+)/);
    return m ? Number(m[1]) : 0;
  }
};

const rows = [];
const problems = [];
for (const f of files) {
  const id = f.replace(/\.mp3$/, '');
  const path = join(DIR, f);
  const m = meta[id] || {};
  const seconds = dur(path);
  const mean = loud(path);
  const kb = Math.round(statSync(path).size / 1024);

  // A silent or truncated download looks perfectly fine in a directory listing. Catch it here.
  if (seconds < 4) problems.push(`${id}: only ${seconds}s — truncated?`);
  if (mean < -60) problems.push(`${id}: mean volume ${mean} dB — silent?`);
  const ctx = m.context || guessContext(id);
  if (!CONTEXTS.includes(ctx)) problems.push(`${id}: unknown context ${JSON.stringify(ctx)}`);

  rows.push({
    id, file: f, name: m.name || prettify(id), context: ctx,
    intensity: m.intensity || (/heavy/.test(id) ? 'heavy' : 'march'),
    acts: m.acts || [], bpm: m.bpm || 0, key: m.key || '', pairId: m.pairId || '',
    seconds, kb,
  });
}

function guessContext(id) {
  if (/^title/.test(id)) return 'title';
  if (/^boss/.test(id)) return 'boss';
  if (/hangar|radio|brief/.test(id)) return 'hangar';
  if (/victory|win/.test(id)) return 'sting_win';
  if (/defeat|lose|lost/.test(id)) return 'sting_lose';
  return 'battle';
}
function prettify(id) {
  return id.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

const byCtx = {};
for (const r of rows) (byCtx[r.context] ||= []).push(r.id);
for (const c of ['title', 'battle', 'hangar']) {
  if (!byCtx[c]?.length) problems.push(`no track for context "${c}" — the game will be silent there`);
}

const src = `// GENERATED by tools/build_music_manifest.mjs — do not hand-edit; rerun after adding music.
// Every track the game can play. The settings screen lists these so a player can switch off any
// track they dislike; \`pickTrack\` skips disabled ids and degrades rather than going silent.

export const MUSIC = ${JSON.stringify(rows, null, 2)};

export const MUSIC_BY_ID = Object.fromEntries(MUSIC.map((t) => [t.id, t]));

/**
 * Choose a track. \`disabled\` is the player's set of switched-off ids from settings.
 * Falls back through context -> battle -> anything, so one enabled track is enough to keep
 * the game scored. Returns null only when the player has switched everything off, which is
 * a legitimate way to ask for silence.
 */
export function pickTrack({ context = 'battle', act = 1, intensity = '', disabled = {}, rng = Math.random } = {}) {
  const live = MUSIC.filter((t) => !disabled[t.id]);
  const fits = (t) => !t.acts.length || t.acts.includes(act);
  const tiers = [
    live.filter((t) => t.context === context && fits(t) && (!intensity || t.intensity === intensity)),
    live.filter((t) => t.context === context && fits(t)),
    live.filter((t) => t.context === context),
    live.filter((t) => t.context === 'battle'),
    live,
  ];
  for (const tier of tiers) if (tier.length) return tier[Math.floor(rng() * tier.length) % tier.length];
  return null;
}

/** The other half of a march/heavy pair, for the live intensity crossfade. */
export function pairedTrack(id, intensity, disabled = {}) {
  const t = MUSIC_BY_ID[id];
  if (!t || !t.pairId) return null;
  return MUSIC.find((o) => o.pairId === t.pairId && o.intensity === intensity && !disabled[o.id]) || null;
}
`;

if (check) {
  console.log(`${rows.length} track(s):`);
  for (const c of CONTEXTS) if (byCtx[c]) console.log(`  ${c.padEnd(10)} ${byCtx[c].join(', ')}`);
  if (problems.length) { console.log('\nPROBLEMS:'); for (const p of problems) console.log('  ' + p); process.exit(1); }
  console.log('\nmanifest OK');
} else {
  writeFileSync(OUT, src);
  console.log(`wrote js/data/music.js — ${rows.length} track(s), ${rows.reduce((s, r) => s + r.kb, 0)} KB total`);
  for (const p of problems) console.log('  WARN ' + p);
}
