// Every voiced line (key → who/text). Source of truth for barks + media's VO generation. Mirrors docs/LEVELS.md §6.
// `_nn` keys are name-free alternates used when the player renames a character.
export const LINES = {
  j_intro_1: { who: 'jon', text: "Ahh. A quiet evening, a perfect steak, and absolutely no interruptions." },
  g_intro_1: { who: 'garfield', text: "Interruptions are my specialty." },
  j_intro_2: { who: 'jon', text: "GARFIELD!" },
  j_intro_2_nn: { who: 'jon', text: "HEY! MY STEAK!" },
  j_open_bowl_1: { who: 'jon', text: "Here you go, buddy! Crunchy cat biscuits, your favourite!" },
  j_open_bowl_2: { who: 'jon', text: "Dinner is served! One bowl of healthy, nutritious biscuits!" },
  j_open_bowl_3: { who: 'jon', text: "Biscuits for you, and something special for me!" },
  j_open_steak: { who: 'jon', text: "And for me: steak, peas and mashed potatoes!" },
  j_open_lasagna: { who: 'jon', text: "And for me: a big slice of lasagna, fresh from the pan!" },
  j_open_meatloaf: { who: 'jon', text: "And for me: meatloaf. Plain, simple, honest meatloaf." },
  g_open_spit_1: { who: 'garfield', text: "Blech. Crunchy disappointment." },
  g_open_spit_2: { who: 'garfield', text: "These taste like a cardboard box had a sad day." },
  g_open_spit_3: { who: 'garfield', text: "Healthy. Ugh. My least favourite flavour." },
  g_open_spit_4: { who: 'garfield', text: "Nope. My tongue has filed a complaint." },
  g_open_plan_steak: { who: 'garfield', text: "Steak, peas and mash. Well, the steak and mash, anyway." },
  g_open_plan_lasagna: { who: 'garfield', text: "Lasagna. My true love. My destiny." },
  g_open_plan_meatloaf: { who: 'garfield', text: "Meatloaf. Not fancy. Still mine." },
  j_l10_1: { who: 'jon', text: "You won't let me eat my food; I won't let you eat my food. Fine, I just won't eat." },
  j_l10_2: { who: 'jon', text: "There. Safe and sound. Nobody's eating tonight." },
  g_l10_1: { who: 'garfield', text: "Nobody? Challenge accepted." },
  j_l10_sulk_1: { who: 'jon', text: "I'm fine. Totally fine. Not hungry at all." },
  j_l10_sulk_2: { who: 'jon', text: "My tummy is rumbling. I'm ignoring it." },
  j_l10_sulk_3: { who: 'jon', text: "This is a very nice chair. I love sitting here. Not eating." },
  j_catch_1: { who: 'jon', text: "Gotcha!" },
  j_catch_2: { who: 'jon', text: "Bad kitty!" },
  j_catch_3: { who: 'jon', text: "Not my dinner, mister!" },
  j_catch_4: { who: 'jon', text: "Back to your biscuits!" },
  j_catch_5: { who: 'jon', text: "Newspaper of justice!" },
  g_caught_1: { who: 'garfield', text: "Ow. My dignity." },
  g_caught_2: { who: 'garfield', text: "Worth it." },
  g_caught_3: { who: 'garfield', text: "I'm flat. Still hungry, though." },
  g_caught_4: { who: 'garfield', text: "I'll allow it. This time." },
  g_caught_5: { who: 'garfield', text: "That was the sports section. Rude." },
  j_leg_1: { who: 'jon', text: "Ow ow ow! My leg!" },
  j_leg_2: { who: 'jon', text: "Yeowch! That was my good leg!" },
  j_leg_3: { who: 'jon', text: "Hop… hop… OUCH!" },
  j_face_1: { who: 'jon', text: "Aah! My face!" },
  j_face_2: { who: 'jon', text: "Not the face! Anything but the face!" },
  j_face_3: { who: 'jon', text: "I can't see! …Okay, I can see." },
  j_paper_1: { who: 'jon', text: "Newspaper time!" },
  j_paper_2: { who: 'jon', text: "Special delivery!" },
  j_paper_3: { who: 'jon', text: "Incoming!" },
  j_paper_fetch_1: { who: 'jon', text: "Now where did my paper go…" },
  j_paper_fetch_2: { who: 'jon', text: "I hadn't even read the comics yet." },
  j_butt_1: { who: 'jon', text: "Yow! My behind!" },
  j_butt_2: { who: 'jon', text: "Hey! That's private property!" },
  j_butt_3: { who: 'jon', text: "Not the pants! These are my good pants!" },
  j_chase_1: { who: 'jon', text: "Come back here!" },
  j_chase_2: { who: 'jon', text: "You can't outrun me! …Can you?" },
  j_chase_3: { who: 'jon', text: "Slow down, you fuzzball!" },
  j_chase_4: { who: 'jon', text: "I just want to talk! With a newspaper!" },
  j_chase_5: { who: 'jon', text: "Garfield, stop!" },
  j_chase_6: { who: 'jon', text: "I'm faster than I look! …Wheeze." },
  j_glare_1: { who: 'jon', text: "Get down from there!" },
  j_glare_2: { who: 'jon', text: "I can wait. …I can't wait." },
  j_glare_3: { who: 'jon', text: "No fair! I can't jump that high!" },
  j_giveup_1: { who: 'jon', text: "Fine. Stay up there." },
  j_giveup_2: { who: 'jon', text: "I'll get you next time." },
  j_giveup_3: { who: 'jon', text: "I'm too tired for this." },
  j_giveup_4: { who: 'jon', text: "Phew. Cardio." },
  j_offtable_1: { who: 'jon', text: "Garfield! Off the table!" },
  j_offtable_2: { who: 'jon', text: "Paws off my plate!" },
  j_offtable_3: { who: 'jon', text: "Shoo! This is people food!" },
  j_back_1: { who: 'jon', text: "Now, where was I? Oh right. Dinner." },
  j_back_2: { who: 'jon', text: "Peace and quiet at last." },
  j_lost_1: { who: 'jon', text: "My dinner! Again!" },
  j_lost_2: { who: 'jon', text: "Why does this always happen to me?" },
  j_lost_3: { who: 'jon', text: "I guess it's cereal for dinner. Again." },
  j_huh_1: { who: 'jon', text: "Hmm?" },
  j_huh_2: { who: 'jon', text: "What was that noise?" },
  j_huh_3: { who: 'jon', text: "Hello? Who's there?" },
  j_eat_1: { who: 'jon', text: "Mmm, delicious." },
  j_eat_2: { who: 'jon', text: "Best. Dinner. Ever." },
  j_eat_3: { who: 'jon', text: "Nom nom nom." },
  j_eat_4: { who: 'jon', text: "Now THIS is living." },
  j_eat_5: { who: 'jon', text: "I should cook this more often." },
  j_eat_6: { who: 'jon', text: "Don't even think about it, buddy." },
  j_wander_1: { who: 'jon', text: "La la la, dinner time soon!" },
  j_wander_2: { who: 'jon', text: "Where did I put my glasses? …Oh, they're on my face." },
  j_wander_3: { who: 'jon', text: "Should I vacuum? …Nah." },
  j_wander_4: { who: 'jon', text: "What a lovely evening." },
  j_wander_5: { who: 'jon', text: "Note to self: hide the lasagna better." },
  j_wander_6: { who: 'jon', text: "I wonder if the TV has anything good on." },
  j_wander_7: { who: 'jon', text: "Who left cat hair on the sofa? …Oh. Right." },
  j_dinner_time: { who: 'jon', text: "Dinner time! Finally!" },
  j_chair_crack: { who: 'jon', text: "Huh? What's that crunchy noise?" },
  j_chair_fall: { who: 'jon', text: "Whoa-whoa-WHOA!" },
  j_chair_floor: { who: 'jon', text: "Ow. Hello, floor." },
  j_vase_hear: { who: 'jon', text: "What was THAT?!" },
  j_vase_see: { who: 'jon', text: "My good vase! In a million pieces!" },
  j_vase_sweep: { who: 'jon', text: "Where did I put that broom…" },
  j_vase_spare: { who: 'jon', text: "Good thing I keep a spare vase." },
  j_vase_see2: { who: 'jon', text: "Not my OTHER good vase!" },
  j_vase_spare2: { who: 'jon', text: "Second spare vase. I buy them in bulk." },
  j_curtain_hear: { who: 'jon', text: "Is something ripping?" },
  j_curtain_see: { who: 'jon', text: "My CURTAINS! They were on sale!" },
  j_curtain_fix: { who: 'jon', text: "Maybe if I hold this bit up… nope." },
  j_pan_gone: { who: 'jon', text: "Wait… where's my pan?" },
  j_fling_1: { who: 'jon', text: "HEY! My dinner!" },
  j_fling_2: { who: 'jon', text: "Five-second rule! Five-second rule!" },
  j_fling_save: { who: 'jon', text: "Saved it! Ha!" },
  j_cold_1: { who: 'jon', text: "Brrr! Why is it suddenly freezing?!" },
  j_cold_2: { who: 'jon', text: "Who opened the window?" },
  j_cold_3: { who: 'jon', text: "Much better. Brrr." },
  j_shoo: { who: 'jon', text: "Shoo, off the sill!" },
  j_bed_hear: { who: 'jon', text: "What's going on up there?" },
  j_bed_see: { who: 'jon', text: "My BED! My comfy, cosy bed!" },
  j_trapped_1: { who: 'jon', text: "Hey! The door's stuck!" },
  j_trapped_2: { who: 'jon', text: "Garfield, open this door!" },
  j_trapped_3: { who: 'jon', text: "Hello? Anybody? …Anybody with thumbs?" },
  j_letout: { who: 'jon', text: "Out you go, mister." },
  j_bump_1: { who: 'jon', text: "Earthquake?!" },
  j_bump_2: { who: 'jon', text: "Did the table just… hop?" },
  j_bump_3: { who: 'jon', text: "I'm sure it's nothing." },
  j_stunned: { who: 'jon', text: "Wobble… wobble… is the room spinning?" },
  j_slip: { who: 'jon', text: "Whoa—whoa—WHOAAA!" },
  j_faceplant: { who: 'jon', text: "Mmmph." },
  j_fridge_hey: { who: 'jon', text: "Hey! I can SEE you!" },
  g_idle_01: { who: 'garfield', text: "I'm not lazy. I'm in energy-saving mode." },
  g_idle_02: { who: 'garfield', text: "If I sit still long enough, maybe dinner comes to me." },
  g_idle_03: { who: 'garfield', text: "Is it nap time? It feels like nap time." },
  g_idle_04: { who: 'garfield', text: "I could do something. Or… not." },
  g_idle_05: { who: 'garfield', text: "My tummy is talking. It says 'more'." },
  g_idle_06: { who: 'garfield', text: "I need a snack, to give me strength to find a snack." },
  g_idle_07: { who: 'garfield', text: "A diet is just a sad word for 'less food'." },
  g_idle_08: { who: 'garfield', text: "Exercise? I thought you said extra pies." },
  g_idle_09: { who: 'garfield', text: "I'll get up in five minutes. Or fifty." },
  g_idle_10: { who: 'garfield', text: "Time is just the gap between meals." },
  g_idle_11: { who: 'garfield', text: "I'm not fat. I'm fluffy with ambition." },
  g_idle_12: { who: 'garfield', text: "This floor is comfy. I live here now." },
  g_idle_13: { who: 'garfield', text: "Somebody should do something. Not me, though." },
  g_idle_14: { who: 'garfield', text: "Waiting is hungry work." },
  g_idle_15: { who: 'garfield', text: "Yawn. Being this adorable is exhausting." },
  g_idle_16: { who: 'garfield', text: "Jon's dinner won't eat itself. That's my job." },
  g_idle_17: { who: 'garfield', text: "A cat's gotta do what a cat's gotta eat." },
  g_idle_18: { who: 'garfield', text: "Hello? Food? Where are you hiding?" },
  g_idle_19: { who: 'garfield', text: "I could chase my tail. But then I'd have to catch it." },
  g_idle_20: { who: 'garfield', text: "Cat biscuits. The saddest two words." },
  g_idle_21: { who: 'garfield', text: "Is it Monday? It feels like a Monday." },
  g_idle_22: { who: 'garfield', text: "Hmm. Thinking about lasagna. As usual." },
  g_near_steak: { who: 'garfield', text: "Steak? Don't mind if I do." },
  g_near_lasagna: { who: 'garfield', text: "Lasagna. Hello, gorgeous." },
  g_near_meatloaf: { who: 'garfield', text: "Meatloaf. Plain. Boring. MINE." },
  g_near_1: { who: 'garfield', text: "So close I can taste it. Because I'm about to." },
  g_near_2: { who: 'garfield', text: "Come to papa." },
  g_guarded_1: { who: 'garfield', text: "He's watching. I need a distraction." },
  g_guarded_2: { who: 'garfield', text: "Not while he's looking. Too risky." },
  g_guarded_3: { who: 'garfield', text: "First, a little chaos. Then dinner." },
  g_jumpfail_1: { who: 'garfield', text: "Gravity. My oldest enemy." },
  g_jumpfail_2: { who: 'garfield', text: "That was a warm-up." },
  g_jumpfail_3: { who: 'garfield', text: "I meant to do that." },
  g_jumpfail_4: { who: 'garfield', text: "Too much cat, not enough jump." },
  g_scratch_hit_1: { who: 'garfield', text: "Sorry. Not sorry." },
  g_scratch_hit_2: { who: 'garfield', text: "Claws: one. Jon: zero." },
  g_scratch_hit_3: { who: 'garfield', text: "That's for the cat biscuits." },
  g_scratch_hit_4: { who: 'garfield', text: "Oops. My paw slipped. On purpose." },
  g_scratch_miss_1: { who: 'garfield', text: "Swing and a miss." },
  g_scratch_miss_2: { who: 'garfield', text: "Just stretching." },
  g_scratch_miss_3: { who: 'garfield', text: "Practising. Obviously." },
  g_chased_1: { who: 'garfield', text: "Run away! Slowly!" },
  g_chased_2: { who: 'garfield', text: "Cats don't run. We relocate. Quickly." },
  g_chased_3: { who: 'garfield', text: "I regret nothing! Except the running." },
  g_chased_4: { who: 'garfield', text: "He'll never catch me. Probably." },
  g_chased_5: { who: 'garfield', text: "Legs! Do your thing!" },
  g_chased_6: { who: 'garfield', text: "Up high! Jon can't jump!" },
  // D27: the one and only chase thought (three takes of the same line)
  g_runnap_1: { who: 'garfield', text: "Run Now, Nap Later." },
  g_runnap_2: { who: 'garfield', text: "Run Now, Nap Later." },
  g_runnap_3: { who: 'garfield', text: "Run Now, Nap Later." },
  g_escape_1: { who: 'garfield', text: "Ha. Jons can't jump." },
  g_escape_2: { who: 'garfield', text: "Up here, I'm untouchable." },
  g_escape_3: { who: 'garfield', text: "Enjoy the view, Jon." },
  g_gaveup_1: { who: 'garfield', text: "And the cat wins again." },
  g_gaveup_2: { who: 'garfield', text: "Too easy." },
  g_gaveup_3: { who: 'garfield', text: "Better luck next time, pal." },
  g_paper_hit_1: { who: 'garfield', text: "Ow. Read all about it." },
  g_paper_hit_2: { who: 'garfield', text: "That was a strongly worded newspaper." },
  g_paper_hit_3: { who: 'garfield', text: "Hit by the comics section. Ironic." },
  g_paper_dodge_1: { who: 'garfield', text: "Missed me!" },
  g_paper_dodge_2: { who: 'garfield', text: "Too slow, paperboy." },
  g_win_1: { who: 'garfield', text: "Mmm. Worth every second." },
  g_win_2: { who: 'garfield', text: "Delicious. Are there seconds?" },
  g_win_3: { who: 'garfield', text: "Victory tastes like gravy." },
  g_win_4: { who: 'garfield', text: "Belly: fuller. Life: better." },
  g_win_5: { who: 'garfield', text: "Burp. Pardon me." },
  g_win_6: { who: 'garfield', text: "Now THAT is what I call a heist." },
  g_tut_1: { who: 'garfield', text: "Okay. Sneaking lesson. It's like napping, but with walking." },
  g_tut_2: { who: 'garfield', text: "Jon's wandering around. Let's practise on him." },
  g_tut_3: { who: 'garfield', text: "He's sitting down to eat. Showtime." },
  g_l02_frontleg: { who: 'garfield', text: "Wrong leg. The back ones hold up the Jon." },
  g_l05_miss: { who: 'garfield', text: "Too early. Or too late. Timing is hard." },
  g_l09_early: { who: 'garfield', text: "Not loose enough yet. More belly power needed." },
  g_l05_grab: { who: 'garfield', text: "Me Tarzan. You lasagna." },
  j_chase_5_nn: { who: 'jon', text: "Kitty, stop!" },
  j_offtable_1_nn: { who: 'jon', text: "Hey! Off the table!" },
  j_trapped_2_nn: { who: 'jon', text: "Kitty, open this door!" },
  l01_hint_1: { who: 'garfield', text: "Jon's face is up high. I need to be up high too." },
  l01_hint_2: { who: 'garfield', text: "If I jump on the table next to him, I can reach his face." },
  l01_hint_3: { who: 'garfield', text: "Table. Scratch face. Eat. Simple." },
  l02_hint_1: { who: 'garfield', text: "That chair looks wobbly…" },
  l02_hint_2: { who: 'garfield', text: "If a back leg of Jon's chair broke… timber!" },
  l02_hint_3: { who: 'garfield', text: "Scratch the BACK leg of Jon's chair." },
  l03_hint_1: { who: 'garfield', text: "That vase on the windowsill looks… breakable." },
  l03_hint_2: { who: 'garfield', text: "Jump on the windowsill and give that vase a little nudge." },
  l03_hint_3: { who: 'garfield', text: "Scratch the vase off the sill, then run for the food while Jon looks." },
  l04_hint_1: { who: 'garfield', text: "Those curtains look very scratchable." },
  l04_hint_2: { who: 'garfield', text: "If I really shred those curtains, Jon will have to come and look." },
  l04_hint_3: { who: 'garfield', text: "Scratch the curtains a few times. Then eat while he's busy." },
  l05_hint_1: { who: 'garfield', text: "The fridge top looks like a good view. How do I get up there?" },
  l05_hint_2: { who: 'garfield', text: "Chair, counter, bread bin, fridge. Step by step." },
  l05_hint_3: { who: 'garfield', text: "Grab the vine on the fridge, swing over the table and press Space over the pan!" },
  l06_hint_1: { who: 'garfield', text: "He's guarding that plate like a dragon." },
  l06_hint_2: { who: 'garfield', text: "What if the food… fell off the table?" },
  l06_hint_3: { who: 'garfield', text: "Jump on the table and scratch the plate! Then eat it off the floor." },
  l07_hint_1: { who: 'garfield', text: "It's a bit stuffy in here. Some fresh air would be nice." },
  l07_hint_2: { who: 'garfield', text: "If I open that window, Jon will have to close it." },
  l07_hint_3: { who: 'garfield', text: "Jump on the windowsill, press Space to open the window, then go eat." },
  l08_hint_1: { who: 'garfield', text: "Jon loves his bed. Almost as much as I love his dinner." },
  l08_hint_2: { who: 'garfield', text: "If I scratch up his bed, he'll come running upstairs…" },
  l08_hint_3: { who: 'garfield', text: "Shred the bed, wait for Jon to go in, then close the door on him!" },
  l09_hint_1: { who: 'garfield', text: "This table is wobbly. And I am… substantial." },
  l09_hint_2: { who: 'garfield', text: "If I jump under the table enough, things will start shaking." },
  l09_hint_3: { who: 'garfield', text: "Bump the table 3 times from below, then walk under Jon's chair!" },
  l10_hint_1: { who: 'garfield', text: "That vase is back. Jon never learns." },
  l10_hint_2: { who: 'garfield', text: "If Jon's busy by the broken vase… a little scratch might trip him up." },
  l10_hint_3: { who: 'garfield', text: "Knock the vase off, scratch Jon next to the pieces, then raid the fridge!" },
  g_l09_ready: { who: 'garfield', text: "Table: loosened. Now for the chair." },

  // ======================= WAVE 3 (docs/LEVELS2.md) =======================
  // who: 'lyman' (l_), 'odie' (o_: dog noises only — text is the subtitle, `sfx` the sound), 'delivery' (d_).
  // ---- Chapter One Free Play ----
  fp1_j_sit_1: { who: 'jon', text: "Just going to sit here. Not eating. Totally relaxed." },
  fp1_j_sit_2: { who: 'jon', text: "A nice quiet sit at the table. No food. Nothing to steal. Ha!" },
  fp1_j_sit_3: { who: 'jon', text: "I'll just read the paper. The comics first, obviously." },
  fp1_j_sit_4: { who: 'jon', text: "Is it weird to sit at the table without dinner? It feels weird." },
  fp1_j_wander_1: { who: 'jon', text: "Day off! What should I do? …Wander. I'll wander." },
  fp1_j_wander_2: { who: 'jon', text: "I should alphabetise my socks today." },
  fp1_j_wander_3: { who: 'jon', text: "Hmm, the house seems suspiciously calm." },
  fp1_j_wander_4: { who: 'jon', text: "I wonder what the cat's up to. Probably nothing. Probably." },
  fp1_j_recover_1: { who: 'jon', text: "Ugh… what happened? Did I miss anything?" },
  fp1_j_recover_2: { who: 'jon', text: "I'm okay! I'm okay. Mostly okay." },
  fp1_j_recover_3: { who: 'jon', text: "Note to self: stop falling over." },
  fp1_j_free_1: { who: 'jon', text: "Freedom! Sweet, sweet hallway!" },
  fp1_j_free_2: { who: 'jon', text: "Finally! I wiggled the handle the right way!" },
  fp1_j_refill: { who: 'jon', text: "Good thing I made extra." },
  fp1_j_fall_vine: { who: 'jon', text: "A flying cat?! WHOA-OA-OA!" },
  fp1_g_vine_1: { who: 'garfield', text: "Death from above. Well. Scratches from above." },
  fp1_g_vine_2: { who: 'garfield', text: "Incoming fuzzball!" },
  fp1_g_start_1: { who: 'garfield', text: "No rules. No plan. Just chaos. My favourite." },
  fp1_g_start_2: { who: 'garfield', text: "Free play. Free food. Free time to annoy Jon." },
  fp1_g_fridge_1: { who: 'garfield', text: "Empty. Who keeps an empty fridge? Jon, that's who." },
  fp1_g_fridge_2: { who: 'garfield', text: "Just checking. You never know." },
  fp1_g_fridge_3: { who: 'garfield', text: "Cold air. Zero lasagna. Disappointing." },
  fp1_g_door_1: { who: 'garfield', text: "Doors: the one thing I'm good at besides eating." },
  fp1_g_eat_1: { who: 'garfield', text: "Unguarded food is just food asking to be eaten." },
  fp_g_idle_1: { who: 'garfield', text: "What shall I wreck next? So many choices." },
  fp_g_idle_2: { who: 'garfield', text: "Pick a trick, any trick." },
  fp_g_idle_3: { who: 'garfield', text: "I'm on holiday. From good behaviour." },
  fp_g_idle_4: { who: 'garfield', text: "Chaos doesn't make itself. Well, it does. But I help." },

  // ---- Chapter Two story (verbatim lines marked in LEVELS2.md) ----
  c2_j_story_1: { who: 'jon', text: "My cat may be a naughty rascal, but I will always love him, as he is still an amazing cat. I just can't help but think a dog might have been better..." },
  g_c2_story_bored: { who: 'garfield', text: "A dog. Hilarious. Wake me when it's lunch." },
  c2_j_story_lyman: { who: 'jon', text: "Lyman!" },
  c2_l_story_jon: { who: 'lyman', text: "Jon." },
  c2_l_story_jon_nn: { who: 'lyman', text: "Hey, pal." },
  c2_l_story_cold: { who: 'lyman', text: "I'm cold. I'm hungry. I'm weak. Take me in!" },
  c2_j_story_home: { who: 'jon', text: "Sure, Lyman. You know my home is your home." },
  c2_g_story_sandbox: { who: 'garfield', text: "And my sandbox is off limits." },
  c2_j_story_suitcase: { who: 'jon', text: "Is that all you have, the one suitcase?" },
  c2_l_story_hereboy: { who: 'lyman', text: "Not exactly. HERE BOY!" },
  c2_g_story_lawsey: { who: 'garfield', text: "Oh, Lawsey, Lawsey, Lawsey." },
  c2_l_story_odie: { who: 'lyman', text: "This is Odie." },
  c2_g_story_tweedledee: { who: 'garfield', text: "Ten billion dogs in this world, and I get Tweedledee the wonder dummy." },

  // ---- Chapter Two shared ----
  c2_j_naughty: { who: 'jon', text: "Naughty Garfield!" },
  c2_j_naughty_nn: { who: 'jon', text: "Naughty kitty!" },
  c2_l_naughty: { who: 'lyman', text: "Naughty Garfield!" },
  c2_l_naughty_nn: { who: 'lyman', text: "Naughty kitty!" },
  c2_j_offtable: { who: 'jon', text: "Paws off! That's two dinners you're not having!" },
  c2_l_offtable: { who: 'lyman', text: "Off the table, furball! Guests eat first!" },
  c2_j_l2_telly: { who: 'jon', text: "Back to the telly." },
  c2_l_telly_1: { who: 'lyman', text: "Ooh, the good bit's on. Sit down, Jon!" },
  c2_l_telly_2: { who: 'lyman', text: "Pass the remote. And the snacks. And the cushion." },

  // ---- C2 L1 ----
  c2_g_l1_hungry: { who: 'garfield', text: "I'm extra, extra hungry today. Even biscuits look good." },
  c2_l_l1_bowl: { who: 'lyman', text: "Dinner, Odie! Plain dog biscuits, your favourite!" },
  c2_j_l1_steak: { who: 'jon', text: "Steak for two! Dig in, Lyman." },
  c2_l_l1_steak: { who: 'lyman', text: "Don't mind if I do. And if I do again." },
  c2_g_l1_biscuits: { who: 'garfield', text: "Crunchy. Bland. Gone." },
  c2_j_l1_ew: { who: 'jon', text: "Ew!" },
  c2_l_l1_ew: { who: 'lyman', text: "Ew!" },
  c2_j_l1_nomore: { who: 'jon', text: "Cat feet in my peas. I don't want it anymore." },
  c2_l_l1_nomore: { who: 'lyman', text: "I've lost my appetite. And I never lose my appetite." },
  c2_g_l1_plate: { who: 'garfield', text: "One down. One to go. Then dessert: dog food." },
  c2_g_l1_dogfood: { who: 'garfield', text: "Dog food. Don't tell anyone." },
  c2_g_l1_first: { who: 'garfield', text: "Biscuits first. A cat needs fuel to cause trouble." },
  c2_l01_hint_1: { who: 'garfield', text: "My bowl first. A cat needs fuel to cause trouble." },
  c2_l01_hint_2: { who: 'garfield', text: "If I step in their dinners, they won't want them." },
  c2_l01_hint_3: { who: 'garfield', text: "Biscuits, table, both plates, scratch the dog, eat his food." },

  // ---- C2 L2 ----
  c2_g_l2_intro: { who: 'garfield', text: "I think I'll put this dog's lights out." },
  c2_g_l2_vase_miss: { who: 'garfield', text: "Missed. Need a dog under it." },
  c2_g_l2_biscuits: { who: 'garfield', text: "Here, doggy doggy." },
  c2_g_l2_win: { who: 'garfield', text: "Lights out, dog. Enjoy the snack." },
  c2_g_l2_shut: { who: 'garfield', text: "He's not in yet. Patience. Ugh, patience." },
  c2_l02_hint_1: { who: 'garfield', text: "That dog's on the edge of the table. Literally." },
  c2_l02_hint_2: { who: 'garfield', text: "Vase plus dog, from the windowsill." },
  c2_l02_hint_3: { who: 'garfield', text: "Open the cupboard under the stairs, scratch the biscuit box, shut him in." },

  // ---- C2 L3 ----
  c2_g_l3_intro: { who: 'garfield', text: "Next time, I bite." },
  c2_j_l3_soup: { who: 'jon', text: "Mmm, chicken soup. Good for the soul. And the sniffles." },
  c2_j_l3_splash: { who: 'jon', text: "AAH! Hot soup! Hot soup!" },
  c2_j_l3_dab: { who: 'jon', text: "I smell like a chicken. A soggy chicken." },
  c2_l_l3_disco: { who: 'lyman', text: "Make way! Lyman's got his dancing pants on!" },
  c2_l_l3_dance: { who: 'lyman', text: "Look at these moves! Disco never died, Jon!" },
  c2_g_l3_suit: { who: 'garfield', text: "A white suit. On a man who lives with a cat. Bold." },
  c2_l_l3_furry: { who: 'lyman', text: "My SUIT! I look like a yeti in a disco!" },
  c2_l03_hint_1: { who: 'garfield', text: "Jon's soup looks splashable." },
  c2_l03_hint_2: { who: 'garfield', text: "Lyman's dressed in white. And I'm made of orange." },
  c2_l03_hint_3: { who: 'garfield', text: "Rub against Lyman's legs till his suit's covered in fur." },

  // ---- C2 L4 ----
  c2_j_l4_diet: { who: 'jon', text: "Diet time." },
  c2_g_l4_cranky: { who: 'garfield', text: "Diet. The ugliest four-letter word. I need to take it out on someone." },
  c2_j_l4_work: { who: 'jon', text: "Off to work! Be good, you two!" },
  c2_g_l4_drat: { who: 'garfield', text: "Drat. He usually lands in the neighbour's lawn. This diet has got me weak." },
  c2_g_l4_higher: { who: 'garfield', text: "Maybe if I scratch him from higher he will go higher." },
  c2_g_l4_shut: { who: 'garfield', text: "Window's shut. Even I know that." },
  c2_g_l4_win: { who: 'garfield', text: "And stay out. Or come back. Whatever. Bye." },
  c2_l04_hint_1: { who: 'garfield', text: "That window is a perfect dog-shaped exit." },
  c2_l04_hint_2: { who: 'garfield', text: "Open the window first. Then aim the dog." },
  c2_l04_hint_3: { who: 'garfield', text: "Scratch Odie from the table so he flies higher." },

  // ---- C2 L5 ----
  d_l5_sign: { who: 'delivery', text: "Delivery for Arbuckle! Sign here." },
  d_l5_bye2: { who: 'delivery', text: "Enjoy the telly! Have a lovely evening." },   // D28: never "mind the cat"
  c2_j_l5_tv: { who: 'jon', text: "Oh, goodie, the new TV!" },
  c2_j_l5_swap: { who: 'jon', text: "Out with the old, in with the… identical. Perfect!" },
  c2_g_l5_intro: { who: 'garfield', text: "A new TV and an old one. And a dog. I sense an opportunity." },
  c2_g_l5_hole: { who: 'garfield', text: "A mouse hole. Mice love cheese. Humans hate mice." },
  c2_g_l5_cheese: { who: 'garfield', text: "Cheese. For the mice. Mostly." },
  c2_g_l5_place: { who: 'garfield', text: "Come and get it, little guys." },
  c2_j_l5_mice: { who: 'jon', text: "MICE! Lyman, get the broom!" },
  c2_l_l5_mice: { who: 'lyman', text: "I don't do mice! …Fine, I do mice!" },
  c2_j_l5_chase: { who: 'jon', text: "Hold still, you little — missed!" },
  c2_l_l5_chase: { who: 'lyman', text: "It went up my trouser leg! IT WENT UP MY TROUSER LEG!" },
  c2_g_l5_eyes: { who: 'garfield', text: "Too many eyes. I need a distraction." },
  c2_g_l5_win: { who: 'garfield', text: "TV dinner." },
  c2_l05_hint_1: { who: 'garfield', text: "Mice. I need mice. Where do mice live?" },
  c2_l05_hint_2: { who: 'garfield', text: "Cheese from the fridge, then leave it lying about." },
  c2_l05_hint_3: { who: 'garfield', text: "Grip the carpet behind the new TV and PULL." },

  // ---- C2 L6 ----
  c2_g_l6_intro: { who: 'garfield', text: "Well, aren't I bored today." },
  c2_g_l6_found: { who: 'garfield', text: "Ooh. Contraband." },
  c2_g_l6_far: { who: 'garfield', text: "Out of range. Get closer." },
  c2_j_l6_coffee: { who: 'jon', text: "HOT COFFEE! Lyman!" },
  c2_l_l6_brawl: { who: 'lyman', text: "Your cat started it!" },
  c2_j_l6_brawl: { who: 'jon', text: "My cat is UPSTAIRS!" },
  c2_g_l6_win: { who: 'garfield', text: "Much better." },
  c2_l06_hint_1: { who: 'garfield', text: "Jon keeps all sorts of junk in his bedroom drawers." },
  c2_l06_hint_2: { who: 'garfield', text: "Scratch the drawer in Jon's room open." },
  c2_l06_hint_3: { who: 'garfield', text: "Take the launcher downstairs and fire it at Odie." },

  // ---- C2 L7 + arena ----
  c2_g_l7_intro: { who: 'garfield', text: "You. Me. The bedroom. Now." },
  c2_g_l7_win: { who: 'garfield', text: "Champion. Obviously." },
  c2_g_l7_lose: { who: 'garfield', text: "I let him win. For his self-esteem." },
  ar_g_hit_1: { who: 'garfield', text: "Point to the cat!" },
  ar_g_hit_2: { who: 'garfield', text: "Swipe!" },
  ar_g_hit_3: { who: 'garfield', text: "Too easy." },
  ar_g_hit_4: { who: 'garfield', text: "Float like a butterfly, scratch like a cat." },
  ar_g_hurt_1: { who: 'garfield', text: "Oof. Slobbery." },
  ar_g_hurt_2: { who: 'garfield', text: "Lucky shot, dog." },
  ar_g_hurt_3: { who: 'garfield', text: "I'm fine. I meant to fall over." },
  ar_g_lead_1: { who: 'garfield', text: "Winning. Naturally." },
  ar_g_lead_2: { who: 'garfield', text: "Is that all you've got, dog?" },
  ar_g_behind_1: { who: 'garfield', text: "Okay, I'm awake now." },
  ar_g_behind_2: { who: 'garfield', text: "Time to stop going easy on him." },
  ar_g_start: { who: 'garfield', text: "Let's dance, dog." },
  ar_g_win: { who: 'garfield', text: "Undefeated. Mostly." },
  ar_g_lose: { who: 'garfield', text: "Rematch. Now. After a nap." },

  // ---- C2 L8 ----
  c2_g_l8_intro: { who: 'garfield', text: "Oh goody, its shedding week. Time for some fun." },
  c2_g_l8_shed_1: { who: 'garfield', text: "A little gift. From me. Made of me." },
  c2_g_l8_shed_2: { who: 'garfield', text: "Orange is the new everything." },
  c2_g_l8_shed_3: { who: 'garfield', text: "That's a nice sofa. Was." },
  c2_j_l8_hair_1: { who: 'jon', text: "Who shed on the sofa? …Oh. Right." },
  c2_j_l8_hair_2: { who: 'jon', text: "My bed is ORANGE now. Wonderful." },
  c2_j_l8_hair_3: { who: 'jon', text: "I'm going to need a bigger lint roller." },
  c2_j_l8_bald: { who: 'jon', text: "It was bound to happen, Garfield." },
  c2_j_l8_bald_nn: { who: 'jon', text: "It was bound to happen, buddy." },
  c2_g_l8_bald: { who: 'garfield', text: "I feel… breezy." },
  c2_l08_hint_1: { who: 'garfield', text: "Shedding week. Jon's bed first." },
  c2_l08_hint_2: { who: 'garfield', text: "Next: the sofa. Then the armchair." },
  c2_l08_hint_3: { who: 'garfield', text: "Save the table for last. It's the big finish." },

  // ---- C2 L9 ----
  c2_g_l9_intro: { who: 'garfield', text: "Boy, am I in a bad mood." },
  c2_j_l9_morning: { who: 'jon', text: "Goooood moooorrrning Garfield!" },
  c2_j_l9_morning_nn: { who: 'jon', text: "Goooood moooorrrning kitty!" },
  c2_j_l9_ow: { who: 'jon', text: "OW! Right in the nose!" },
  c2_j_l9_nasty: { who: 'jon', text: "Garfield's sure been in a nasty mood lately." },
  c2_j_l9_nasty_nn: { who: 'jon', text: "The cat's sure been in a nasty mood lately." },
  c2_l_l9_treat: { who: 'lyman', text: "We'll see about that. Do you know how to treat a mad cat?" },
  c2_j_l9_respect: { who: 'jon', text: "With great, great respect." },
  c2_j_l9_love: { who: 'jon', text: "WE LOVE YOU GARFIELD!" },
  c2_j_l9_love_nn: { who: 'jon', text: "WE LOVE YOU, KITTY!" },
  c2_l_l9_love: { who: 'lyman', text: "WE LOVE YOU GARFIELD!" },
  c2_l_l9_love_nn: { who: 'lyman', text: "WE LOVE YOU, KITTY!" },
  c2_g_l9_loved: { who: 'garfield', text: "Okay. Bad mood cancelled. For now." },
  c2_g_l9_glare: { who: 'garfield', text: "Behold. The glare." },
  c2_l09_hint_1: { who: 'garfield', text: "Sit on the table and wait for someone to annoy me." },
  c2_l09_hint_2: { who: 'garfield', text: "Poke him. Right in the face." },
  c2_l09_hint_3: { who: 'garfield', text: "Hold Interact and give them the full glare." },

  // ---- C2 L10 ----
  c2_g_l10_socks: { who: 'garfield', text: "Socks. Warm, smelly, wonderful." },
  c2_g_l10_idea: { who: 'garfield', text: "I have an idea. A beautiful, terrible idea." },
  c2_g_l10_sock_1: { who: 'garfield', text: "Ears: fashionable." },
  c2_g_l10_sock_2: { who: 'garfield', text: "Tail: cosy." },
  c2_g_l10_sock_3: { who: 'garfield', text: "Mouth: finally, some peace and quiet." },
  c2_j_l10_socks: { who: 'jon', text: "Garfield!" },
  c2_j_l10_socks_nn: { who: 'jon', text: "Hey! Kitty!" },
  c2_g_l10_whistle: { who: 'garfield', text: "Hmm, a whistle." },
  c2_g_l10_broken: { who: 'garfield', text: "Must be broken." },
  c2_g_l10_end: { who: 'garfield', text: "…Huh." },
  c2_l10_hint_1: { who: 'garfield', text: "Jon's sock drawer. A cat's paradise." },
  c2_l10_hint_2: { who: 'garfield', text: "Socks… on the dog. Obviously." },
  c2_l10_hint_3: { who: 'garfield', text: "There's a whistle on Jon's floor. Blow it as hard as you can." },

  // ---- Garfield barks about Odie / Lyman (Ch2 + free play 2) ----
  g_c2_odie_1: { who: 'garfield', text: "The dog is breathing on me. Again." },
  g_c2_odie_2: { who: 'garfield', text: "His tongue has its own postcode." },
  g_c2_odie_3: { who: 'garfield', text: "Somewhere, a brain cell is lonely. It's his." },
  g_c2_odie_4: { who: 'garfield', text: "Panting is not a personality, Odie." },
  g_c2_odie_5: { who: 'garfield', text: "Why is he wet? Why is he always wet?" },
  g_c2_odie_6: { who: 'garfield', text: "If dogs are man's best friend, I'm man's best boss." },
  g_c2_odie_7: { who: 'garfield', text: "He chased his tail for an hour. The tail won." },
  g_c2_odie_8: { who: 'garfield', text: "Hello, drool. Goodbye, dignity." },
  g_c2_odie_scratch_1: { who: 'garfield', text: "Not yet, dog. I have plans for you." },
  g_c2_odie_scratch_2: { who: 'garfield', text: "Just a warm-up scratch." },
  g_c2_odie_scratch_3: { who: 'garfield', text: "Run along. And come back so I can do it again." },
  g_c2_lyman_1: { who: 'garfield', text: "Lyman. The guest who never leaves." },
  g_c2_lyman_2: { who: 'garfield', text: "He eats more than me. I didn't think that was possible." },
  g_c2_lyman_3: { who: 'garfield', text: "That moustache is hiding crumbs. My crumbs." },
  g_c2_lyman_4: { who: 'garfield', text: "Two humans. Twice the snacks. Twice the chasing." },
  g_c2_idle_1: { who: 'garfield', text: "A dog in my house. What's next, a goldfish with opinions?" },
  g_c2_idle_2: { who: 'garfield', text: "Peace and quiet. Remember those? I miss those." },
  g_c2_idle_3: { who: 'garfield', text: "Somebody should get rid of the dog. Somebody orange." },
  g_c2_idle_4: { who: 'garfield', text: "I'm not jealous of the dog. I'm superior to the dog. Different thing." },
  g_c2_chased_1: { who: 'garfield', text: "Two of them! That's not fair! …Running anyway!" },
  g_c2_chased_2: { who: 'garfield', text: "Double trouble. Double legs. Go go go!" },
  fp2_g_start_1: { who: 'garfield', text: "A house full of targets. Where do I start?" },
  fp2_g_start_2: { who: 'garfield', text: "Free play, round two. The dog doesn't stand a chance." },
  fp2_g_bald: { who: 'garfield', text: "Still breezy." },
  fp2_g_back: { who: 'garfield', text: "He's back. Of course he's back. They always come back." },

  // ---- Lyman reactions / barks (mirror Jon's families) ----
  l_leg_1: { who: 'lyman', text: "OW! My dancing leg!" },
  l_leg_2: { who: 'lyman', text: "Yowza! That cat's got knives for toes!" },
  l_leg_3: { who: 'lyman', text: "Hop… hop… I've been wounded, Jon!" },
  l_face_1: { who: 'lyman', text: "Not the moustache! Anything but the moustache!" },
  l_face_2: { who: 'lyman', text: "My beautiful face!" },
  l_face_3: { who: 'lyman', text: "I can't see! Is my moustache okay?" },
  l_butt_1: { who: 'lyman', text: "YEOW! My sitting-down part!" },
  l_butt_2: { who: 'lyman', text: "Hey! These are my good trousers! My only trousers!" },
  l_paper_1: { who: 'lyman', text: "Have a newspaper, furball!" },
  l_paper_2: { who: 'lyman', text: "Catch! Read all about it!" },
  l_paper_fetch_1: { who: 'lyman', text: "Where'd it go? I wasn't finished with the crossword." },
  l_chase_1: { who: 'lyman', text: "Come here, you orange menace!" },
  l_chase_2: { who: 'lyman', text: "I'm right behind you! …Slightly to the left!" },
  l_chase_3: { who: 'lyman', text: "Jon! Cut him off at the sofa!" },
  l_chase_4: { who: 'lyman', text: "I haven't run this much since the buffet closed!" },
  l_glare_1: { who: 'lyman', text: "Come down from there this instant!" },
  l_glare_2: { who: 'lyman', text: "I'd climb up there, but I just ate." },
  l_giveup_1: { who: 'lyman', text: "Fine! I needed a sit-down anyway." },
  l_giveup_2: { who: 'lyman', text: "You win this round, cat." },
  l_giveup_3: { who: 'lyman', text: "Phew. Snack break." },
  l_catch_1: { who: 'lyman', text: "Got you, you rascal!" },
  l_catch_2: { who: 'lyman', text: "The long arm of Lyman!" },
  l_catch_3: { who: 'lyman', text: "Gotcha! Jon, I got him! Jon? Are you watching?" },
  l_back_1: { who: 'lyman', text: "Right. Where was I? Oh yes: relaxing." },
  l_huh_1: { who: 'lyman', text: "Eh? What was that?" },
  l_huh_2: { who: 'lyman', text: "Jon, did you hear something?" },
  l_eat_1: { who: 'lyman', text: "Mmm! Jon, you've outdone yourself." },
  l_eat_2: { who: 'lyman', text: "Is there seconds? There's always seconds, right?" },
  l_eat_3: { who: 'lyman', text: "Delicious. Free food always tastes better." },
  l_idle_1: { who: 'lyman', text: "Jon, old pal, is there any more of that cake?" },
  l_idle_2: { who: 'lyman', text: "I'll only stay a week. Or a month. Or forever." },
  l_idle_3: { who: 'lyman', text: "Odie, sit! …Odie? Odie, that's a lamp." },
  l_idle_4: { who: 'lyman', text: "This sofa fits me perfectly. It's like it was made for me." },
  l_idle_5: { who: 'lyman', text: "Who drank all the milk? …Oh. Me." },
  l_idle_6: { who: 'lyman', text: "Ah, the dramatic life of a house guest." },
  l_idle_7: { who: 'lyman', text: "Odie! Good boy! …Mostly good boy." },
  l_idle_8: { who: 'lyman', text: "Jon, your cat is giving me a funny look." },

  // ---- Jon Ch2 idles ----
  c2_j_idle_1: { who: 'jon', text: "Two pets and a houseguest. My life is so full!" },
  c2_j_idle_2: { who: 'jon', text: "Lyman, have you seen my socks? All of them?" },
  c2_j_idle_3: { who: 'jon', text: "Odie, please stop licking the TV." },
  c2_j_idle_4: { who: 'jon', text: "I think the cat and the dog are really bonding." },
  c2_j_idle_5: { who: 'jon', text: "Lyman, it's been three days. Are you staying? …Great!" },
  c2_j_idle_6: { who: 'jon', text: "Who put a sock on the lampshade?" },
  c2_j_watch_1: { who: 'jon', text: "Ooh, a documentary about cheese!" },
  c2_j_watch_2: { who: 'jon', text: "This show's great. I have no idea what's happening." },

  // ---- Odie (dog noises only) ----
  o_yip_1: { who: 'odie', text: "Yip!", sfx: 'yip' },
  o_yip_2: { who: 'odie', text: "Yip yip!", sfx: 'yip' },
  o_yip_3: { who: 'odie', text: "Yipe!", sfx: 'yip' },
  o_yip_long: { who: 'odie', text: "Yiiiiiiiip!", sfx: 'yip' },
  o_bark_1: { who: 'odie', text: "Woof!", sfx: 'bark' },
  o_bark_2: { who: 'odie', text: "Arf! Arf!", sfx: 'bark' },
  o_bark_happy: { who: 'odie', text: "Arf arf arf!", sfx: 'yap' },
  o_pant: { who: 'odie', text: "Hah-hah-hah-hah…", sfx: 'pant' },
  o_whine: { who: 'odie', text: "Hnnnn…", sfx: 'whine' },
  o_whimper: { who: 'odie', text: "Hmm-mm-mm…", sfx: 'whimper' },
  o_whine_muffled: { who: 'odie', text: "Mmf! Mmf!", sfx: 'whine' },
  o_growl_play: { who: 'odie', text: "Grrr-arf!", sfx: 'bark' },
  o_shake_off: { who: 'odie', text: "Brrrrrr!", sfx: 'pant' },
  o_sniff: { who: 'odie', text: "Sniff sniff.", sfx: 'sniff' },

  // ---- Chapter Two Free Play (helper 'fp2', merged from freeplay2.js FP2_LINES) ----
  fp2_g_idle_1: { who: 'garfield', text: "Jon, Lyman, a dog and me. One of us is the brains. Guess who." },
  fp2_g_idle_2: { who: 'garfield', text: "The house is quiet. That's my cue." },
  fp2_g_idle_3: { who: 'garfield', text: "Every day is free play if you're a cat." },
  fp2_g_idle_4: { who: 'garfield', text: "I could nap. Or I could cause chaos. Why not both?" },
  fp2_g_idle_5: { who: 'garfield', text: "So many targets. So little nap time." },
  fp2_g_odie_table_1: { who: 'garfield', text: "The dog's on the table again. Gravity, do your thing." },
  fp2_g_odie_table_2: { who: 'garfield', text: "Somebody's about to learn about edges." },
  fp2_g_odie_fly_1: { who: 'garfield', text: "Bon voyage, dog breath." },
  fp2_g_odie_fly_2: { who: 'garfield', text: "Fly, Odie, fly! Preferably far." },
  fp2_g_odie_splat_1: { who: 'garfield', text: "Wall: one. Dog: nil." },
  fp2_g_odie_splat_2: { who: 'garfield', text: "Close. Next time, open window AND good aim." },
  fp2_g_vase_odie_1: { who: 'garfield', text: "Bullseye. Sorry, vase." },
  fp2_g_vase_odie_2: { who: 'garfield', text: "Special delivery: one vase, express." },
  fp2_g_vase_miss_1: { who: 'garfield', text: "Missed. That vase died for nothing." },
  fp2_g_cupboard_1: { who: 'garfield', text: "Dinner's in the cupboard, dog. So are you." },
  fp2_g_cupboard_out_1: { who: 'garfield', text: "He's out. Nobody tell him how doors work." },
  fp2_g_whistle_again_1: { who: 'garfield', text: "Still broken. I'll keep testing it. For science." },
  fp2_g_whistle_again_2: { who: 'garfield', text: "Not a peep. Rubbish whistle." },
  fp2_g_socks_1: { who: 'garfield', text: "Odie in socks. My finest work." },
  fp2_g_launcher_1: { who: 'garfield', text: "Spit-ball launcher. Loaded and dangerous." },
  fp2_g_launcher_2: { who: 'garfield', text: "One straw. Infinite possibilities." },
  fp2_g_brawl_1: { who: 'garfield', text: "I didn't do anything. I'm just a cat." },
  fp2_g_brawl_2: { who: 'garfield', text: "Two grown men and a dog. Best show on telly." },
  fp2_g_mice_1: { who: 'garfield', text: "Mice party. Humans dancing. Everything's going to plan." },
  fp2_g_mice_2: { who: 'garfield', text: "I'd catch them, but I'm on a break. Forever." },
  fp2_g_delivery_1: { who: 'garfield', text: "A parcel! Is it lasagna? It's never lasagna." },
  fp2_g_carpet_1: { who: 'garfield', text: "TV dinner, round two." },
  fp2_g_carpet_miss_1: { who: 'garfield', text: "No dog under it. Still satisfying." },
  fp2_g_shed_1: { who: 'garfield', text: "Shedding week again. Bless." },
  fp2_g_shed_2: { who: 'garfield', text: "A little orange makes everything better." },
  fp2_g_shed_3: { who: 'garfield', text: "Fur here. Fur there. Fur everywhere." },
  fp2_g_bald_back_1: { who: 'garfield', text: "Fur's back. Order restored. Handsome restored." },
  fp2_g_trap_1: { who: 'garfield', text: "Enjoy your room. I'll hold the door. Closed." },
  fp2_g_trap_2: { who: 'garfield', text: "Peace and quiet. Finally." },
  fp2_g_disco_1: { who: 'garfield', text: "The white suit's back. My fur sees an opportunity." },
  fp2_g_disco_end_1: { who: 'garfield', text: "Disco's dead. I killed it. With fur." },
  fp2_g_warp_1: { who: 'garfield', text: "The table's weak. Not me. The table." },
  fp2_g_cancel_1: { who: 'garfield', text: "Two things were about to happen. Then neither did. Typical." },
  fp2_g_cancel_2: { who: 'garfield', text: "Something was going to happen. It changed its mind." },
  fp2_g_eat_1: { who: 'garfield', text: "Unguarded dinner. My favourite kind." },
  fp2_g_eat_2: { who: 'garfield', text: "Ew for them. Yum for me." },
  fp2_g_soup_1: { who: 'garfield', text: "Soup. The drink you eat. I approve." },
  fp2_g_bowl_1: { who: 'garfield', text: "Biscuits. The salad of cat food." },
  fp2_g_guard_1: { who: 'garfield', text: "The dog's guarding it. With his face." },
  fp2_g_window_1: { who: 'garfield', text: "Fresh air. For the dog. On his way out." },
  fp2_g_morning_1: { who: 'garfield', text: "Bad mood. Big table. Let's see who dares." },
  fp2_g_hug_1: { who: 'garfield', text: "Fine. I'm loved. Don't make it weird." },
  fp2_g_nohug_1: { who: 'garfield', text: "Respect. That's all I ask. And lasagna." },
  fp2_j_wander_1: { who: 'jon', text: "Lyman, did you eat my sandwich? …Lyman?" },
  fp2_j_wander_2: { who: 'jon', text: "What a lovely day to stay in with my pets!" },
  fp2_j_wander_3: { who: 'jon', text: "Odie, that's not a chew toy, that's my slipper." },
  fp2_j_room_1: { who: 'jon', text: "Now where did I put my good socks?" },
  fp2_j_room_2: { who: 'jon', text: "Who's been rolling in my sock drawer?" },
  fp2_j_free_1: { who: 'jon', text: "Freedom! Who keeps shutting doors?!" },
  fp2_j_coffee_1: { who: 'jon', text: "Ahh. Coffee. The only thing in this house that doesn't shed." },
  fp2_j_coffee_2: { who: 'jon', text: "A quiet cup of coffee. Any second now. Quiet. Any second." },
  fp2_j_delivery_1: { who: 'jon', text: "The doorbell! Coming!" },
  fp2_j_dinner_1: { who: 'jon', text: "Dinner time! Two plates, zero cats." },
  fp2_j_soup_1: { who: 'jon', text: "Chicken soup for one. Lovely." },
  fp2_j_makeup_1: { who: 'jon', text: "Sorry, Lyman. Hug it out?" },
  fp2_j_odie_1: { who: 'jon', text: "Odie! Are you okay, boy?" },
  fp2_j_window_1: { who: 'jon', text: "Who opened the window? Brrr!" },
  fp2_j_mice_end_1: { who: 'jon', text: "I think they're gone. I'm never buying cheese again." },
  fp2_j_shed_1: { who: 'jon', text: "Is it shedding week AGAIN?!" },
  fp2_j_tv_1: { who: 'jon', text: "Telly time! Lyman, budge up." },
  fp2_l_wander_1: { who: 'lyman', text: "Jon, your fridge is my fridge, right? Right." },
  fp2_l_wander_2: { who: 'lyman', text: "A man needs his afternoon snack. And his morning snack." },
  fp2_l_room_1: { who: 'lyman', text: "Just a little nap. A twelve-hour little nap." },
  fp2_l_free_1: { who: 'lyman', text: "I'm out! I'm cold, I'm hungry, I'm weak… but I'm out!" },
  fp2_l_trapped_1: { who: 'lyman', text: "Jon! The door's stuck! I'm wasting away in here!" },
  fp2_l_trapped_2: { who: 'lyman', text: "Let me out! I can hear snacks!" },
  fp2_l_coffee_1: { who: 'lyman', text: "Coffee and telly. Living the dream." },
  fp2_l_disco_1: { who: 'lyman', text: "Time to boogie! Make way for Lyman!" },
  fp2_l_disco_end_1: { who: 'lyman', text: "My suit! Covered in cat! I'm going to change." },
  fp2_l_disco_done_1: { who: 'lyman', text: "Right. Back to normal Lyman. Dull, dull Lyman." },
  fp2_l_makeup_1: { who: 'lyman', text: "No hard feelings, Jon. Your cat started it." },
  fp2_l_odie_1: { who: 'lyman', text: "Odie! Who did this to you? …I bet it was the cat." },
  fp2_l_odie_back_1: { who: 'lyman', text: "Odie! You came back! Good boy!" },
  fp2_l_dinner_1: { who: 'lyman', text: "Steak? Again? Jon, you spoil me." },
};
