// Every voiced line (key → who/text). Source of truth for barks + media's VO generation. Mirrors docs/LEVELS.md §6.
// `_nn` keys are name-free alternates used when the player renames a character.
export const LINES = {
  j_intro_1: { who: 'jon', text: "Ahh. A quiet evening, a perfect steak, and absolutely no interruptions." },
  g_intro_1: { who: 'garfield', text: "Interruptions are my specialty." },
  j_intro_2: { who: 'jon', text: "GARFIELD!" },
  j_intro_2_nn: { who: 'jon', text: "HEY! MY STEAK!" },
  j_open_bowl_1: { who: 'jon', text: "Here you go, buddy! Crunchy cat biscuits, your favourite!" },
  j_open_bowl_2: { who: 'jon', text: "Dinner is served! One bowl of healthy, nutritious biscuits!" },
  j_open_bowl_3: { who: 'jon', text: "Biscuits for you, and something special for me!" },
  j_open_steak: { who: 'jon', text: "And for me: steak, peas and mashed potatoes!" },
  j_open_lasagna: { who: 'jon', text: "And for me: a big slice of lasagna, fresh from the pan!" },
  j_open_meatloaf: { who: 'jon', text: "And for me: meatloaf. Plain, simple, honest meatloaf." },
  g_open_spit_1: { who: 'garfield', text: "Blech. Crunchy disappointment." },
  g_open_spit_2: { who: 'garfield', text: "These taste like a cardboard box had a sad day." },
  g_open_spit_3: { who: 'garfield', text: "Healthy. Ugh. My least favourite flavour." },
  g_open_spit_4: { who: 'garfield', text: "Nope. My tongue has filed a complaint." },
  g_open_plan_steak: { who: 'garfield', text: "Steak, peas and mash. Well, the steak and mash, anyway." },
  g_open_plan_lasagna: { who: 'garfield', text: "Lasagna. My true love. My destiny." },
  g_open_plan_meatloaf: { who: 'garfield', text: "Meatloaf. Not fancy. Still mine." },
  j_l10_1: { who: 'jon', text: "You won't let me eat my food; I won't let you eat my food. Fine, I just won't eat." },
  j_l10_2: { who: 'jon', text: "There. Safe and sound. Nobody's eating tonight." },
  g_l10_1: { who: 'garfield', text: "Nobody? Challenge accepted." },
  j_l10_sulk_1: { who: 'jon', text: "I'm fine. Totally fine. Not hungry at all." },
  j_l10_sulk_2: { who: 'jon', text: "My tummy is rumbling. I'm ignoring it." },
  j_l10_sulk_3: { who: 'jon', text: "This is a very nice chair. I love sitting here. Not eating." },
  j_catch_1: { who: 'jon', text: "Gotcha!" },
  j_catch_2: { who: 'jon', text: "Bad kitty!" },
  j_catch_3: { who: 'jon', text: "Not my dinner, mister!" },
  j_catch_4: { who: 'jon', text: "Back to your biscuits!" },
  j_catch_5: { who: 'jon', text: "Newspaper of justice!" },
  g_caught_1: { who: 'garfield', text: "Ow. My dignity." },
  g_caught_2: { who: 'garfield', text: "Worth it." },
  g_caught_3: { who: 'garfield', text: "I'm flat. Still hungry, though." },
  g_caught_4: { who: 'garfield', text: "I'll allow it. This time." },
  g_caught_5: { who: 'garfield', text: "That was the sports section. Rude." },
  j_leg_1: { who: 'jon', text: "Ow ow ow! My leg!" },
  j_leg_2: { who: 'jon', text: "Yeowch! That was my good leg!" },
  j_leg_3: { who: 'jon', text: "Hop… hop… OUCH!" },
  j_face_1: { who: 'jon', text: "Aah! My face!" },
  j_face_2: { who: 'jon', text: "Not the face! Anything but the face!" },
  j_face_3: { who: 'jon', text: "I can't see! …Okay, I can see." },
  j_paper_1: { who: 'jon', text: "Newspaper time!" },
  j_paper_2: { who: 'jon', text: "Special delivery!" },
  j_paper_3: { who: 'jon', text: "Incoming!" },
  j_paper_fetch_1: { who: 'jon', text: "Now where did my paper go…" },
  j_paper_fetch_2: { who: 'jon', text: "I hadn't even read the comics yet." },
  j_butt_1: { who: 'jon', text: "Yow! My behind!" },
  j_butt_2: { who: 'jon', text: "Hey! That's private property!" },
  j_butt_3: { who: 'jon', text: "Not the pants! These are my good pants!" },
  j_chase_1: { who: 'jon', text: "Come back here!" },
  j_chase_2: { who: 'jon', text: "You can't outrun me! …Can you?" },
  j_chase_3: { who: 'jon', text: "Slow down, you fuzzball!" },
  j_chase_4: { who: 'jon', text: "I just want to talk! With a newspaper!" },
  j_chase_5: { who: 'jon', text: "Garfield, stop!" },
  j_chase_6: { who: 'jon', text: "I'm faster than I look! …Wheeze." },
  j_glare_1: { who: 'jon', text: "Get down from there!" },
  j_glare_2: { who: 'jon', text: "I can wait. …I can't wait." },
  j_glare_3: { who: 'jon', text: "No fair! I can't jump that high!" },
  j_giveup_1: { who: 'jon', text: "Fine. Stay up there." },
  j_giveup_2: { who: 'jon', text: "I'll get you next time." },
  j_giveup_3: { who: 'jon', text: "I'm too tired for this." },
  j_giveup_4: { who: 'jon', text: "Phew. Cardio." },
  j_offtable_1: { who: 'jon', text: "Garfield! Off the table!" },
  j_offtable_2: { who: 'jon', text: "Paws off my plate!" },
  j_offtable_3: { who: 'jon', text: "Shoo! This is people food!" },
  j_back_1: { who: 'jon', text: "Now, where was I? Oh right. Dinner." },
  j_back_2: { who: 'jon', text: "Peace and quiet at last." },
  j_lost_1: { who: 'jon', text: "My dinner! Again!" },
  j_lost_2: { who: 'jon', text: "Why does this always happen to me?" },
  j_lost_3: { who: 'jon', text: "I guess it's cereal for dinner. Again." },
  j_huh_1: { who: 'jon', text: "Hmm?" },
  j_huh_2: { who: 'jon', text: "What was that noise?" },
  j_huh_3: { who: 'jon', text: "Hello? Who's there?" },
  j_eat_1: { who: 'jon', text: "Mmm, delicious." },
  j_eat_2: { who: 'jon', text: "Best. Dinner. Ever." },
  j_eat_3: { who: 'jon', text: "Nom nom nom." },
  j_eat_4: { who: 'jon', text: "Now THIS is living." },
  j_eat_5: { who: 'jon', text: "I should cook this more often." },
  j_eat_6: { who: 'jon', text: "Don't even think about it, buddy." },
  j_wander_1: { who: 'jon', text: "La la la, dinner time soon!" },
  j_wander_2: { who: 'jon', text: "Where did I put my glasses? …Oh, they're on my face." },
  j_wander_3: { who: 'jon', text: "Should I vacuum? …Nah." },
  j_wander_4: { who: 'jon', text: "What a lovely evening." },
  j_wander_5: { who: 'jon', text: "Note to self: hide the lasagna better." },
  j_wander_6: { who: 'jon', text: "I wonder if the TV has anything good on." },
  j_wander_7: { who: 'jon', text: "Who left cat hair on the sofa? …Oh. Right." },
  j_dinner_time: { who: 'jon', text: "Dinner time! Finally!" },
  j_chair_crack: { who: 'jon', text: "Huh? What's that crunchy noise?" },
  j_chair_fall: { who: 'jon', text: "Whoa-whoa-WHOA!" },
  j_chair_floor: { who: 'jon', text: "Ow. Hello, floor." },
  j_vase_hear: { who: 'jon', text: "What was THAT?!" },
  j_vase_see: { who: 'jon', text: "My good vase! In a million pieces!" },
  j_vase_sweep: { who: 'jon', text: "Where did I put that broom…" },
  j_vase_spare: { who: 'jon', text: "Good thing I keep a spare vase." },
  j_vase_see2: { who: 'jon', text: "Not my OTHER good vase!" },
  j_vase_spare2: { who: 'jon', text: "Second spare vase. I buy them in bulk." },
  j_curtain_hear: { who: 'jon', text: "Is something ripping?" },
  j_curtain_see: { who: 'jon', text: "My CURTAINS! They were on sale!" },
  j_curtain_fix: { who: 'jon', text: "Maybe if I hold this bit up… nope." },
  j_pan_gone: { who: 'jon', text: "Wait… where's my pan?" },
  j_fling_1: { who: 'jon', text: "HEY! My dinner!" },
  j_fling_2: { who: 'jon', text: "Five-second rule! Five-second rule!" },
  j_fling_save: { who: 'jon', text: "Saved it! Ha!" },
  j_cold_1: { who: 'jon', text: "Brrr! Why is it suddenly freezing?!" },
  j_cold_2: { who: 'jon', text: "Who opened the window?" },
  j_cold_3: { who: 'jon', text: "Much better. Brrr." },
  j_shoo: { who: 'jon', text: "Shoo, off the sill!" },
  j_bed_hear: { who: 'jon', text: "What's going on up there?" },
  j_bed_see: { who: 'jon', text: "My BED! My comfy, cosy bed!" },
  j_trapped_1: { who: 'jon', text: "Hey! The door's stuck!" },
  j_trapped_2: { who: 'jon', text: "Garfield, open this door!" },
  j_trapped_3: { who: 'jon', text: "Hello? Anybody? …Anybody with thumbs?" },
  j_letout: { who: 'jon', text: "Out you go, mister." },
  j_bump_1: { who: 'jon', text: "Earthquake?!" },
  j_bump_2: { who: 'jon', text: "Did the table just… hop?" },
  j_bump_3: { who: 'jon', text: "I'm sure it's nothing." },
  j_stunned: { who: 'jon', text: "Wobble… wobble… is the room spinning?" },
  j_slip: { who: 'jon', text: "Whoa—whoa—WHOAAA!" },
  j_faceplant: { who: 'jon', text: "Mmmph." },
  j_fridge_hey: { who: 'jon', text: "Hey! I can SEE you!" },
  g_idle_01: { who: 'garfield', text: "I'm not lazy. I'm in energy-saving mode." },
  g_idle_02: { who: 'garfield', text: "If I sit still long enough, maybe dinner comes to me." },
  g_idle_03: { who: 'garfield', text: "Is it nap time? It feels like nap time." },
  g_idle_04: { who: 'garfield', text: "I could do something. Or… not." },
  g_idle_05: { who: 'garfield', text: "My tummy is talking. It says 'more'." },
  g_idle_06: { who: 'garfield', text: "I need a snack, to give me strength to find a snack." },
  g_idle_07: { who: 'garfield', text: "A diet is just a sad word for 'less food'." },
  g_idle_08: { who: 'garfield', text: "Exercise? I thought you said extra pies." },
  g_idle_09: { who: 'garfield', text: "I'll get up in five minutes. Or fifty." },
  g_idle_10: { who: 'garfield', text: "Time is just the gap between meals." },
  g_idle_11: { who: 'garfield', text: "I'm not fat. I'm fluffy with ambition." },
  g_idle_12: { who: 'garfield', text: "This floor is comfy. I live here now." },
  g_idle_13: { who: 'garfield', text: "Somebody should do something. Not me, though." },
  g_idle_14: { who: 'garfield', text: "Waiting is hungry work." },
  g_idle_15: { who: 'garfield', text: "Yawn. Being this adorable is exhausting." },
  g_idle_16: { who: 'garfield', text: "Jon's dinner won't eat itself. That's my job." },
  g_idle_17: { who: 'garfield', text: "A cat's gotta do what a cat's gotta eat." },
  g_idle_18: { who: 'garfield', text: "Hello? Food? Where are you hiding?" },
  g_idle_19: { who: 'garfield', text: "I could chase my tail. But then I'd have to catch it." },
  g_idle_20: { who: 'garfield', text: "Cat biscuits. The saddest two words." },
  g_idle_21: { who: 'garfield', text: "Is it Monday? It feels like a Monday." },
  g_idle_22: { who: 'garfield', text: "Hmm. Thinking about lasagna. As usual." },
  g_near_steak: { who: 'garfield', text: "Steak? Don't mind if I do." },
  g_near_lasagna: { who: 'garfield', text: "Lasagna. Hello, gorgeous." },
  g_near_meatloaf: { who: 'garfield', text: "Meatloaf. Plain. Boring. MINE." },
  g_near_1: { who: 'garfield', text: "So close I can taste it. Because I'm about to." },
  g_near_2: { who: 'garfield', text: "Come to papa." },
  g_guarded_1: { who: 'garfield', text: "He's watching. I need a distraction." },
  g_guarded_2: { who: 'garfield', text: "Not while he's looking. Too risky." },
  g_guarded_3: { who: 'garfield', text: "First, a little chaos. Then dinner." },
  g_jumpfail_1: { who: 'garfield', text: "Gravity. My oldest enemy." },
  g_jumpfail_2: { who: 'garfield', text: "That was a warm-up." },
  g_jumpfail_3: { who: 'garfield', text: "I meant to do that." },
  g_jumpfail_4: { who: 'garfield', text: "Too much cat, not enough jump." },
  g_scratch_hit_1: { who: 'garfield', text: "Sorry. Not sorry." },
  g_scratch_hit_2: { who: 'garfield', text: "Claws: one. Jon: zero." },
  g_scratch_hit_3: { who: 'garfield', text: "That's for the cat biscuits." },
  g_scratch_hit_4: { who: 'garfield', text: "Oops. My paw slipped. On purpose." },
  g_scratch_miss_1: { who: 'garfield', text: "Swing and a miss." },
  g_scratch_miss_2: { who: 'garfield', text: "Just stretching." },
  g_scratch_miss_3: { who: 'garfield', text: "Practising. Obviously." },
  g_chased_1: { who: 'garfield', text: "Run away! Slowly!" },
  g_chased_2: { who: 'garfield', text: "Cats don't run. We relocate. Quickly." },
  g_chased_3: { who: 'garfield', text: "I regret nothing! Except the running." },
  g_chased_4: { who: 'garfield', text: "He'll never catch me. Probably." },
  g_chased_5: { who: 'garfield', text: "Legs! Do your thing!" },
  g_chased_6: { who: 'garfield', text: "Up high! Jon can't jump!" },
  g_escape_1: { who: 'garfield', text: "Ha. Jons can't jump." },
  g_escape_2: { who: 'garfield', text: "Up here, I'm untouchable." },
  g_escape_3: { who: 'garfield', text: "Enjoy the view, Jon." },
  g_gaveup_1: { who: 'garfield', text: "And the cat wins again." },
  g_gaveup_2: { who: 'garfield', text: "Too easy." },
  g_gaveup_3: { who: 'garfield', text: "Better luck next time, pal." },
  g_paper_hit_1: { who: 'garfield', text: "Ow. Read all about it." },
  g_paper_hit_2: { who: 'garfield', text: "That was a strongly worded newspaper." },
  g_paper_hit_3: { who: 'garfield', text: "Hit by the comics section. Ironic." },
  g_paper_dodge_1: { who: 'garfield', text: "Missed me!" },
  g_paper_dodge_2: { who: 'garfield', text: "Too slow, paperboy." },
  g_win_1: { who: 'garfield', text: "Mmm. Worth every second." },
  g_win_2: { who: 'garfield', text: "Delicious. Are there seconds?" },
  g_win_3: { who: 'garfield', text: "Victory tastes like gravy." },
  g_win_4: { who: 'garfield', text: "Belly: fuller. Life: better." },
  g_win_5: { who: 'garfield', text: "Burp. Pardon me." },
  g_win_6: { who: 'garfield', text: "Now THAT is what I call a heist." },
  g_tut_1: { who: 'garfield', text: "Okay. Sneaking lesson. It's like napping, but with walking." },
  g_tut_2: { who: 'garfield', text: "Jon's wandering around. Let's practise on him." },
  g_tut_3: { who: 'garfield', text: "He's sitting down to eat. Showtime." },
  g_l02_frontleg: { who: 'garfield', text: "Wrong leg. The back ones hold up the Jon." },
  g_l05_miss: { who: 'garfield', text: "Too early. Or too late. Timing is hard." },
  g_l09_early: { who: 'garfield', text: "Not loose enough yet. More belly power needed." },
  g_l05_grab: { who: 'garfield', text: "Me Tarzan. You lasagna." },
  j_chase_5_nn: { who: 'jon', text: "Kitty, stop!" },
  j_offtable_1_nn: { who: 'jon', text: "Hey! Off the table!" },
  j_trapped_2_nn: { who: 'jon', text: "Kitty, open this door!" },
  l01_hint_1: { who: 'garfield', text: "Jon's face is up high. I need to be up high too." },
  l01_hint_2: { who: 'garfield', text: "If I jump on the table next to him, I can reach his face." },
  l01_hint_3: { who: 'garfield', text: "Table. Scratch face. Eat. Simple." },
  l02_hint_1: { who: 'garfield', text: "That chair looks wobbly…" },
  l02_hint_2: { who: 'garfield', text: "If a back leg of Jon's chair broke… timber!" },
  l02_hint_3: { who: 'garfield', text: "Scratch the BACK leg of Jon's chair." },
  l03_hint_1: { who: 'garfield', text: "That vase on the windowsill looks… breakable." },
  l03_hint_2: { who: 'garfield', text: "Jump on the windowsill and give that vase a little nudge." },
  l03_hint_3: { who: 'garfield', text: "Scratch the vase off the sill, then run for the food while Jon looks." },
  l04_hint_1: { who: 'garfield', text: "Those curtains look very scratchable." },
  l04_hint_2: { who: 'garfield', text: "If I really shred those curtains, Jon will have to come and look." },
  l04_hint_3: { who: 'garfield', text: "Scratch the curtains a few times. Then eat while he's busy." },
  l05_hint_1: { who: 'garfield', text: "The fridge top looks like a good view. How do I get up there?" },
  l05_hint_2: { who: 'garfield', text: "Chair, counter, bread bin, fridge. Step by step." },
  l05_hint_3: { who: 'garfield', text: "Grab the vine on the fridge, swing over the table and press Space over the pan!" },
  l06_hint_1: { who: 'garfield', text: "He's guarding that plate like a dragon." },
  l06_hint_2: { who: 'garfield', text: "What if the food… fell off the table?" },
  l06_hint_3: { who: 'garfield', text: "Jump on the table and scratch the plate! Then eat it off the floor." },
  l07_hint_1: { who: 'garfield', text: "It's a bit stuffy in here. Some fresh air would be nice." },
  l07_hint_2: { who: 'garfield', text: "If I open that window, Jon will have to close it." },
  l07_hint_3: { who: 'garfield', text: "Jump on the windowsill, press Space to open the window, then go eat." },
  l08_hint_1: { who: 'garfield', text: "Jon loves his bed. Almost as much as I love his dinner." },
  l08_hint_2: { who: 'garfield', text: "If I scratch up his bed, he'll come running upstairs…" },
  l08_hint_3: { who: 'garfield', text: "Shred the bed, wait for Jon to go in, then close the door on him!" },
  l09_hint_1: { who: 'garfield', text: "This table is wobbly. And I am… substantial." },
  l09_hint_2: { who: 'garfield', text: "If I jump under the table enough, things will start shaking." },
  l09_hint_3: { who: 'garfield', text: "Bump the table 3 times from below, then walk under Jon's chair!" },
  l10_hint_1: { who: 'garfield', text: "That vase is back. Jon never learns." },
  l10_hint_2: { who: 'garfield', text: "If Jon's busy by the broken vase… a little scratch might trip him up." },
  l10_hint_3: { who: 'garfield', text: "Knock the vase off, scratch Jon next to the pieces, then raid the fridge!" },
  g_l09_ready: { who: 'garfield', text: "Table: loosened. Now for the chair." },
};
