import * as T from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {createWorld,ground as terrainGround,inside,makeEnemy} from './world.js';
import {createLab,createMainland} from './regions.js';
import {fresh,validate,level,threshold,SKILLS,ready,forge,eat,addXP,repair,cleanName} from './state.mjs';
import {icon,skillIcons} from './icons.js';
const $=id=>document.getElementById(id), SAVE='emberwake-v1';
const ground=(x,z)=>state.region==='lab'?0:state.region==='island'&&x>6.6&&x<9.4&&z>20.8&&z<28.9?Math.max(.99,terrainGround(x,z)):terrainGround(x,z);
let state=fresh(), saved=null;try{saved=validate(JSON.parse(localStorage.getItem(SAVE)))}catch{}
const stories=await fetch('story.json').then(r=>{if(!r.ok)throw Error('Story could not load');return r.json()});
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('fatal').hidden=false;throw e}
renderer.info.autoReset=false;renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const worlds={lab:createLab()};let world=worlds.lab,{scene,player}=world;
const camera=new T.OrthographicCamera(-18,18,12,-12,.1,220);let zoom=24,angle=.62;const focus=new T.Vector3(0,0,8);
const composer=new EffectComposer(renderer);const renderPass=new RenderPass(scene,camera);composer.addPass(renderPass);const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.24,.5,1.05);composer.addPass(bloom);composer.addPass(new OutputPass());let quality='high';
function resize(){renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;camera.top=zoom/2;camera.bottom=-zoom/2;camera.left=-zoom*aspect/2;camera.right=zoom*aspect/2;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize);
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),-.6),keys=new Set();let destination=null,path=[],selected=null,moving=false,started=false,clock=0,last=performance.now(),attackCD=0,dodgeCD=0,dodgeTime=0,actionCD=0,uiTimer=0,saveTimer=0,toastUntil=0,selectedSkill=0,narration=null,storyAfter=null,currentStory=null,steps=0;const effects=[],floaters=[],enemies=[];let soundCtx=null;
const stageTitles=['A stranger on the shore','From the shore','Fire & copper','The language of steel','A memory of fire','Shadows in the garden','The last watch','Carry the light','Keeper of the first flame'];
const stageTexts=['Find Edda beside the keeper’s cottage.','Gather two driftwood and two copper ore. Click a resource to collect it.','Take your materials to the old forge.','Equip sword [1] and dagger [2]. Land three hits with each on the effigy, then visit the rune well.','Equip ember magic [3]. Cast three bolts at the training effigy.','Defeat the three drowned shades in the northern garden.','Defeat the Hollow Warden at the lighthouse. Dodge the red circle before it fills.','Place the recovered embers in the dark beacon.','The crossing is open. Enter the beacon to travel to Lantern Reach.'];
const weaponNames=['COPPER LONGSWORD','COPPER DAGGER','EMBER BOLT'];
function toast(text){$('toast').textContent=text;toastUntil=clock+3.6}
function save(){if(!started)return;state.x=player.position.x;state.z=player.position.z;try{localStorage.setItem(SAVE,JSON.stringify(state));$('saveStatus').textContent='Progress saved on this device.'}catch{$('saveStatus').textContent='Device storage is unavailable; progress lasts for this session.'}}
function tone(freq=440,duration=.12,type='sine',volume=.04){if(state.muted)return;try{soundCtx ||=new (window.AudioContext||window.webkitAudioContext)();if(soundCtx.state==='suspended')soundCtx.resume();let o=soundCtx.createOscillator(),g=soundCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,soundCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,soundCtx.currentTime+duration);g.gain.setValueAtTime(volume,soundCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,soundCtx.currentTime+duration);o.connect(g).connect(soundCtx.destination);o.start();o.stop(soundCtx.currentTime+duration)}catch{}}
function voiceInfo(line){const selected=line?.voice==='player';return {name:selected?(state.gender==='female'?'BELLA':'ECHO'):'LEWIS',file:line.id+(selected?'-'+state.gender:'')};}
function playVoice(){narration?.pause();if(state.muted||!currentStory){$('voiceStatus').textContent='NARRATION MUTED';return;}const v=voiceInfo(currentStory);narration=new Audio(`audio/${v.file}.mp3`);narration.volume=.9;$('voiceStatus').textContent=v.name+' · NARRATING';narration.onended=()=>{$('voiceStatus').textContent=v.name+' · KOKORO'};narration.onerror=()=>{$('voiceStatus').textContent='Audio unavailable · text is complete'};narration.play().catch(()=>{$('voiceStatus').textContent='Tap replay to hear '+v.name});}
function story(id){currentStory=stories.find(s=>s.id===id);if(!currentStory)return;state.pendingStory=id;$('dialogueKicker').textContent=currentStory.voice==='player'?state.name+' · YOUR THOUGHTS':currentStory.speaker;$('dialogueTitle').textContent=currentStory.title;$('dialogueText').textContent=currentStory.text;$('continue').textContent=currentStory.button;$('dialogue').hidden=false;keys.clear();destination=null;path=[];selected=null;playVoice();$('continue').focus();save();}
$('continue').onclick=()=>{const id=currentStory?.id;narration?.pause();$('dialogue').hidden=true;currentStory=null;state.pendingStory=null;
 const next={lab_test:'lab_return',lab_return:'lab_attack',lab_hidden:'lab_escape',keeper:'creator',ledger:'ledger_thought',neri_truth:'signal',signal:'chapter_end'};
 if(id==='lab_return'){state.labStep=1;world.alert=true;document.body.classList.add('labAlert');tone(48,1.2,'sawtooth',.15);burst(new T.Vector3(9,2,6),'#ffc88b',65);}
 if(id==='ending'){enterRegion('mainland',0,24);if(state.mainStage===0)story('main_arrival');}
 else if(next[id])story(next[id]);
 save();renderUI();};$('replayVoice').onclick=playVoice;
function makeLabels(){for(const l of labels)l.el.remove();labels.length=0;for(const o of world.objects.filter(o=>o.name&&(!['wood','ore'].includes(o.kind)||o.id.endsWith('1')))){const el=document.createElement('div');el.className='worldlabel';$('labels').append(el);labels.push({o,el});}}
function enterRegion(region,x,z){
 for(const e of enemies)scene.remove(e.mesh,e.warning);enemies.length=0;
 for(const e of effects){scene.remove(e.m);if(e.m.geometry!==particleGeo)e.m.geometry.dispose();e.m.material.dispose();}effects.length=0;
 for(const f of floaters)f.el.remove();floaters.length=0;
 state.region=region;world=worlds[region] ||= region==='island'?createWorld(renderer):createMainland();scene=world.scene;player=world.player;renderPass.scene=scene;
 const valid=region==='lab'?Math.abs(x)<11&&Math.abs(z)<10:region==='mainland'?Math.abs(x)<25&&Math.abs(z)<36:inside(x,z);
 player.position.set(valid?x:0,0,valid?z:region==='lab'?7:18);player.position.y=ground(player.position.x,player.position.z);player.userData.appearance(state.gender,region==='lab');focus.copy(player.position);zoom=region==='lab'?19:24;resize();keys.clear();destination=null;path=[];selected=null;attackCD=actionCD=dodgeTime=dodgeCD=0;
 document.body.classList.toggle('lab',region==='lab');document.body.classList.toggle('labAlert',region==='lab'&&state.labStep>0);world.alert=state.labStep>0;if(world.portraitLight)world.portraitLight.visible=false;if(region==='lab')world.objects.filter(o=>o.kind==='vale'||o.kind==='sato').forEach(o=>o.group.visible=true);world.beaconLight.visible=world.beam.visible=state.beacon;makeLabels();spawnEnemies();equip(state.weapon);syncRegion();
}
function syncRegion(){if(state.region==='mainland'){world.relayLights.forEach((m,i)=>m.visible=state.relays.includes('relay'+(i+1)));const n=world.objects.find(o=>o.id==='neri');if(state.mainStage>=4){n.x=11;n.z=2;n.y=ground(n.x,n.z);}else{n.x=12;n.z=-8;n.y=ground(n.x,n.z);}world.neri.position.set(n.x,n.y,n.z);}player.userData.hand.visible=state.region!=='lab'&&state.weapon!==2;}
function gain(skill,amount){const up=addXP(state,skill,amount);floatText(`+${amount} ${skill} XP`,player.position,'#f3dda1',true);if(up){toast(`${skill} advanced to level ${level(state.xp[skill])}`);burst(player.position,'#f7d185',22);tone(660,.6)}}
function advance(stage,id){state.stage=stage;renderUI();save();if(id)story(id)}
function equip(n){if(n===2&&!state.magic){toast('Attune your ember at the rune well first.');return}state.weapon=n;let d=player.userData;d.blade.scale.y=n===1?.5:1;d.tip.position.y=n===1?.75:1.23;d.hand.visible=n!==2;if(state.region==='lab')d.hand.visible=false;renderUI();save();tone(n===2?700:260,.08)}
function spawnEnemies(){for(const e of enemies){scene.remove(e.mesh,e.warning)}enemies.length=0;for(const[i,x,z]of(state.region==='lab'?[]:state.region==='mainland'?[[10,9,-8],[11,15,-10],[12,0,-24]]:[[0,-8,-10],[1,2,-12],[2,9,-10],[3,0,-21]])){let boss=i===3||i===12;if(state.region==='mainland'?state.mainKills.includes(i):boss?state.bossDead:state.kills.includes(i))continue;const mesh=makeEnemy(boss);mesh.position.set(x,ground(x,z),z);scene.add(mesh);const warning=new T.Mesh(new T.RingGeometry(.04,1,48),new T.MeshBasicMaterial({color:'#f27159',transparent:true,opacity:.33,side:T.DoubleSide,depthWrite:false}));warning.rotation.x=-Math.PI/2;warning.visible=false;scene.add(warning);enemies.push({id:i,name:state.region==='mainland'?(boss?'Observatory Custodian':'Lost sentinel'):(boss?'Hollow Warden':'Drowned shade'),kind:'enemy',x,z,homeX:x,homeZ:z,hp:boss?230:65,max:boss?230:65,boss,mesh,warning,wind:0,cooldown:1,alive:true,attackX:0,attackZ:0,phase:0})}}
function init(resume=false){narration?.pause();state=resume&&saved?structuredClone(saved):fresh();if(!resume){state.name=cleanName($('heroName').value);state.gender=document.querySelector('[name=gender]:checked').value;state.x=0;state.z=7;}started=true;document.body.classList.remove('intro','creation');$('welcome').hidden=$('creation').hidden=$('dialogue').hidden=true;$('sound').checked=!state.muted;$('belt').dataset.size=state.belt;$('skills').dataset.size=state.skills;enterRegion(state.region,state.x,state.z);renderUI();if(state.pendingStory)story(state.pendingStory);else if(!resume)story('lab_intro');else toast(`Welcome back, ${state.name}.`);save();}
function creation(){narration?.pause();started=false;document.body.classList.add('intro','creation');$('welcome').hidden=true;$('creation').hidden=false;state.region='lab';world=worlds.lab;scene=world.scene;player=world.player;renderPass.scene=scene;world.alert=false;world.portraitLight.visible=true;world.objects.filter(o=>o.kind==='vale'||o.kind==='sato').forEach(o=>o.group.visible=false);player.position.set(0,0,4);previewCharacter();}
function previewCharacter(){const gender=document.querySelector('[name=gender]:checked').value;player.userData.appearance(gender,true);player.userData.hand.visible=false;player.rotation.y=.4;$('previewName').textContent=cleanName($('heroName').value);}
$('characterForm').onsubmit=e=>{e.preventDefault();init(false);};document.querySelectorAll('[name=gender]').forEach(el=>el.onchange=()=>{narration?.pause();previewCharacter();});$('heroName').oninput=previewCharacter;
$('previewVoice').onclick=()=>{narration?.pause();const gender=document.querySelector('[name=gender]:checked').value;narration=new Audio('audio/arrival-'+gender+'.mp3');narration.play().catch(()=>{});};
$('creationBack').onclick=()=>{narration?.pause();world.portraitLight.visible=false;world.objects.filter(o=>o.kind==='vale'||o.kind==='sato').forEach(o=>o.group.visible=true);$('creation').hidden=true;$('welcome').hidden=false;document.body.classList.remove('creation');zoom=24;resize();};
 document.body.classList.add('intro');player.position.set(0,0,4);player.userData.appearance('male',true);player.userData.hand.visible=false;$('resume').hidden=!saved;$('start').onclick=()=>{if(saved&&$('start').dataset.confirm!=='yes'){$('start').dataset.confirm='yes';$('start').textContent='Replace your saved journey? Click again to create.';return;}creation();};$('resume').onclick=()=>init(true);if(saved){$('resume').className='primary';$('start').className='quiet';$('start').textContent='Start a new journey…';$('start').before($('resume'));}
function resource(o){if(actionCD>0)return;actionCD=.65;if(o.kind==='wood'){state.bag.wood++;gain('Woodcutting',30);toast('Driftwood gathered · +1 wood');tone(180,.12,'triangle')}else{state.bag.ore++;gain('Mining',35);toast('Copper chipped free · +1 ore');tone(800,.12,'triangle')}burst(new T.Vector3(o.x,o.y+.5,o.z),o.kind==='wood'?'#c5ad79':'#d5a06e',10);if(state.region==='island'&&state.stage===1&&ready(state))advance(2,'forge');save();renderUI()}
function interact(o){if(!o)return;if(regionalInteract(o)){save();renderUI();return;}if(o.kind==='enemy'||o.kind==='dummy'){attack(o);return}if(actionCD>0)return;
 if(o.kind==='edda'){if(state.stage===0)advance(1,'keeper');else if(state.stage===8)story('edda_repeat');else{toast(stageTexts[state.stage]);state.hp=100;state.mana=100;burst(player.position,'#b8e8ba',12)}}
 else if(o.kind==='wood'||o.kind==='ore')resource(o);
 else if(o.kind==='forge'){if(forge(state)){toast('Smithing advanced to level 2 · +120 XP');floatText('+120 Smithing XP',player.position,'#f3dda1',true);advance(3,'training');tone(500,.3,'triangle');burst(player.position,'#ffd98d',20)}else toast(state.crafted?'Your copper blades are already forged.':'The forge needs 2 driftwood and 2 copper ore.')}
 else if(o.kind==='well'){if(state.stage===3&&ready(state)){state.magic=true;state.mana=100;state.weapon=2;advance(4,'well');equip(2)}else{state.mana=100;toast(state.magic?'Focus restored.':'Practise three sword hits and three dagger hits first.');burst(player.position,'#82f7db',14)}}
 else if(o.kind==='fish'){actionCD=1.4;state.bag.raw++;gain('Fishing',40);toast('Caught a silverfin. Cook it at the keeper’s fire.');tone(600,.2);burst(new T.Vector3(o.x,0,o.z),'#b1f9e6',12)}
 else if(o.kind==='fire'){state.hp=100;if(state.bag.raw){let n=state.bag.raw;state.bag.fish+=n;state.bag.raw=0;toast(`Cooked ${n} silverfin · vitality restored`)}else toast('Rested by the fire · vitality restored');tone(300,.3)}
 else if(o.kind==='beacon'){if(state.stage===7){state.beacon=true;state.bag.embers=0;world.beaconLight.visible=world.beam.visible=true;advance(8,'ending');burst(new T.Vector3(0,ground(0,-27)+4,-27),'#ffe89d',70);tone(880,1)}else if(state.beacon)story('ending');else toast('The Hollow Warden still holds the crossing.')}save();renderUI();}
function attack(o){if(attackCD>0||!o)return;if(o.kind==='enemy'&&!activeEnemy(o)){toast(state.region==='mainland'?'Follow Mara’s mission before entering this fight.':o.boss?'Finish the garden before facing the Warden.':'Complete your training at the refuge first.');selected=null;return}if(o.kind==='dummy'&&!state.crafted){toast('Forge your copper blades before training.');selected=null;return}
 let n=state.weapon;if(n===2&&state.mana<13){toast('Gathering focus…');attackCD=.5;return}const range=n===2?9:2.1;if(Math.hypot(player.position.x-o.x,player.position.z-o.z)>range)return;player.rotation.y=Math.atan2(o.x-player.position.x,o.z-player.position.z);attackCD=[.68,.34,.8][n];player.userData.swing=.25;if(n===2){state.mana-=13;bolt(player.position,new T.Vector3(o.x,ground(o.x,o.z)+1.1,o.z));tone(680,.25,'sine')}else{slash(n);tone(n===1?420:210,.1,'triangle',.045)}
 const dmg=[18,10,25][n]+level(state.xp[n===2?'Magic':'Melee'])*2+(state.reinforced?4:0);
 if(o.kind==='dummy'){state.training[n]++;gain(n===2?'Magic':'Melee',n===1?9:15);floatText(String(dmg),new T.Vector3(o.x,o.y+1.8,o.z),n===2?'#9bfff0':'#f7e1b4');burst(new T.Vector3(o.x,o.y+1.2,o.z),n===2?'#83ffde':'#ead2a0',6);if(state.stage===3&&ready(state)){toast('Both blades mastered. Visit the rune well.');selected=null}if(state.stage===4&&ready(state)){advance(5,'shadows');selected=null}}
 else{damageEnemy(o,dmg);if(n===0)for(const e of enemies)if(e!==o&&activeEnemy(e)&&Math.hypot(e.x-o.x,e.z-o.z)<2.5)damageEnemy(e,Math.round(dmg*.6))}renderUI();}
function activeEnemy(e){return e.alive&&(state.region==='mainland'?state.mainStage>=(e.boss?4:3):state.region==='island'&&state.stage>=(e.boss?6:5))}
function damageEnemy(e,dmg){e.hp-=dmg;burst(e.mesh.position.clone().add(new T.Vector3(0,1.2,0)),state.weapon===2?'#8dfbe3':'#e4c79c',8);floatText(String(dmg),e.mesh.position.clone().add(new T.Vector3(0,2.2,0)),state.weapon===2?'#a1fff1':'#fff0c7');gain(state.weapon===2?'Magic':'Melee',6);if(e.hp<=0){e.alive=false;e.mesh.visible=e.warning.visible=false;state.bag.embers++;gain(state.weapon===2?'Magic':'Melee',e.boss?140:45);if(state.region==='mainland'){state.mainKills.push(e.id);toast(e.boss?'The ledger is within reach.':'Sentinel released.');}else if(e.boss){state.bossDead=true;advance(7,'beacon')}else{state.kills.push(e.id);toast('Drowned shade released · +1 ember');if(state.stage===5&&state.kills.length===3)advance(6,'warden')}selected=null;destination=null;path=[];save()}}
function hurt(dmg){if(dodgeTime>0)return;state.hp=Math.max(0,state.hp-dmg);floatText(`−${dmg}`,player.position.clone().add(new T.Vector3(0,2,0)),'#ff9b83');tone(85,.2,'sawtooth',.025);if(state.hp<=0){state.hp=100;state.mana=100;player.position.set(state.region==='mainland'?4:-3,ground(state.region==='mainland'?4:-3,15),15);destination=null;path=[];selected=null;for(const e of enemies)if(e.alive){e.x=e.homeX;e.z=e.homeZ;e.hp=e.max;e.wind=0;e.warning.visible=false;e.mesh.position.set(e.x,ground(e.x,e.z),e.z)}toast('You recover at the hearth. Your progress is safe.');save()}renderUI()}
let dodgeDir=new T.Vector3();function dodge(){if(dodgeCD>0||paused())return;dodgeCD=1.5;dodgeTime=.32;dodgeDir.set(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y));tone(180,.14);destination=null;path=[];selected=null}
function consume(){if(eat(state)){toast('A warm meal · +45 vitality');tone(540,.2);burst(player.position,'#cce5a4',14);save();renderUI()}else toast(state.bag.fish?'You are already at full vitality.':'Catch a silverfin and cook it at the fire.')}
// Small ground grid with diagonal corner checks; routing avoids the cottage and tree trunks.
function walkable(x,z){return (state.region==='lab'?Math.abs(x)<11.7&&Math.abs(z)<10.5:state.region==='mainland'?Math.abs(x)<25.5&&Math.abs(z)<36.5:inside(x,z))&&!world.colliders.some(c=>Math.hypot(x-c.x,z-c.z)<c.r+.28)}
function route(x,z){const bx=state.region==='mainland'?25:state.region==='lab'?11:20,bz=state.region==='mainland'?36:state.region==='lab'?10:29;x=Math.max(-bx,Math.min(bx,x));z=Math.max(-bz,Math.min(bz,z));if(!walkable(x,z))return [];let sx=Math.round(player.position.x),sz=Math.round(player.position.z),tx=Math.round(x),tz=Math.round(z);const key=(x,z)=>x+','+z,open=[{x:sx,z:sz,g:0,f:0}],known=new Map(),closed=new Set();let end=null;known.set(key(sx,sz),open[0]);for(let n=0;open.length&&n<2500;n++){open.sort((a,b)=>a.f-b.f);let cur=open.shift(),k=key(cur.x,cur.z);if(closed.has(k))continue;closed.add(k);if(Math.hypot(cur.x-tx,cur.z-tz)<=1){end=cur;break}for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){if(!dx&&!dz)continue;let nx=cur.x+dx,nz=cur.z+dz,nk=key(nx,nz);if(closed.has(nk)||!walkable(nx,nz)||(dx&&dz&&(!walkable(cur.x+dx,cur.z)||!walkable(cur.x,cur.z+dz))))continue;let g=cur.g+Math.hypot(dx,dz),old=known.get(nk);if(!old||g<old.g){let next={x:nx,z:nz,g,f:g+Math.hypot(tx-nx,tz-nz),prev:cur};known.set(nk,next);open.push(next)}}}if(!end)return [];let out=[{x,z}];while(end.prev){out.unshift({x:end.x,z:end.z});end=end.prev}return out}
function go(x,z,o=null){selected=o;const range=o?(o.kind==='enemy'||o.kind==='dummy'?state.weapon===2?8:1.65:1.6):0;if(o){let dx=player.position.x-x,dz=player.position.z-z,d=Math.hypot(dx,dz)||1;if(d<=range+.25){destination=null;path=[];interact(o);return}x+=dx/d*range;z+=dz/d*range}path=route(x,z);if(!path.length&&o){let best=null;for(let i=0;i<16;i++){const a=i*Math.PI/8,xx=o.x+Math.cos(a)*range,zz=o.z+Math.sin(a)*range,p=route(xx,zz);if(p.length&&(!best||p.length<best.path.length))best={x:xx,z:zz,path:p};}if(best){x=best.x;z=best.z;path=best.path;}}destination=path.length?{x,z}:null;if(!destination){if(!o)toast('That shore is too steep to cross.');return}world.marker.position.set(x,ground(x,z)+.09,z);world.marker.visible=true;}
function move(dx,dz){let x=player.position.x,z=player.position.z;if(walkable(x+dx,z+dz)){player.position.x+=dx;player.position.z+=dz}else if(walkable(x+dx,z))player.position.x+=dx;else if(walkable(x,z+dz))player.position.z+=dz;player.position.y=ground(player.position.x,player.position.z)}
function nearest(){let list=[...world.objects,...enemies.filter(activeEnemy)];return list.filter(o=>o.kind!=='beacon'||state.stage>=7).sort((a,b)=>Math.hypot(a.x-player.position.x,a.z-player.position.z)-Math.hypot(b.x-player.position.x,b.z-player.position.z))[0]}
function useNearest(){if(paused())return;const o=nearest();if(o&&Math.hypot(o.x-player.position.x,o.z-player.position.z)<5)go(o.x,o.z,o);else toast('Move closer to a person, resource or enemy.')}
function paused(){return !started||!$('dialogue').hidden||$('settings').open||$('journal').open||document.hidden}
let drag=null;$('world').addEventListener('pointerdown',e=>{if(paused())return;drag={x:e.clientX,y:e.clientY,button:e.button};$('world').setPointerCapture(e.pointerId)});$('world').addEventListener('pointermove',e=>{if(drag&&drag.button===2){angle-=(e.clientX-drag.x)*.007;drag.x=e.clientX}});$('world').addEventListener('contextmenu',e=>e.preventDefault());$('world').addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(paused()||d.button!==0||Math.hypot(e.clientX-d.x,e.clientY-d.y)>12)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);let picks=[];for(const o of [...world.objects,...enemies.filter(e=>e.alive)]){const pos=new T.Vector3(o.x,ground(o.x,o.z)+(o.boss?1.7:.85),o.z);let hit=new T.Vector3();if(ray.ray.intersectSphere(new T.Sphere(pos,o.kind==='beacon'?1.7:o.kind==='fish'?1.2:.95),hit))picks.push({o,d:ray.ray.origin.distanceTo(hit)})}if(picks.length){picks.sort((a,b)=>a.d-b.d);const o=picks[0].o;go(o.x,o.z,o)}else{const hit=new T.Vector3();if(ray.ray.intersectPlane(plane,hit))go(hit.x,hit.z)}});
$('world').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(15,Math.min(40,zoom+e.deltaY*.016));resize()},{passive:false});
addEventListener('keydown',e=>{if(e.code==='Escape'&&!$('dialogue').hidden){$('continue').click();return}if(paused())return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code.startsWith('Digit')&&Number(e.key)<=3&&Number(e.key)>=1)equip(Number(e.key)-1);if(e.code==='KeyE')useNearest();if(e.code==='Space')dodge();if(e.code==='KeyR')consume();if(e.code==='KeyJ')openJournal();if(e.code==='KeyB')toggle('belt');if(e.code==='KeyK')toggle('skills')});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();drag=null;save()});document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden){narration?.pause();save()}});
function toggle(panel){state[panel]=(state[panel]+1)%3;if(innerWidth<=600&&state[panel]===2){const other=panel==='belt'?'skills':'belt';state[other]=0;$(other).dataset.size=0;}$(panel).dataset.size=state[panel];renderUI();save()}
$('beltToggle').onclick=()=>toggle('belt');$('skillsToggle').onclick=()=>toggle('skills');$('interact').onclick=useNearest;$('dodge').onclick=dodge;$('settingsBtn').onclick=()=>{keys.clear();narration?.pause();$('settings').showModal()};$('sound').onchange=()=>{state.muted=!$('sound').checked;if(state.muted)narration?.pause();save()};$('opacity').oninput=()=>document.documentElement.style.setProperty('--panel',$('opacity').value/100);$('quality').onchange=()=>{quality=$('quality').value;renderer.shadowMap.enabled=quality==='high';renderer.setPixelRatio(quality==='high'?Math.min(devicePixelRatio,1.6):1);resize()};$('restart').onclick=()=>{if($('restart').dataset.confirm==='yes'){$('settings').close();$('restart').dataset.confirm='';$('restart').textContent='Start a new journey…';saved=structuredClone(state);creation()}else{$('restart').dataset.confirm='yes';$('restart').textContent='Replace this journey? Click again to confirm'}};
function objective(){if(state.region!=='island')return regionalObjective();if(state.stage===0)return world.objects.find(o=>o.id==='edda');if(state.stage===1)return world.objects.find(o=>o.id===(state.bag.wood<2?'wood1':'ore1'));if(state.stage===2)return world.objects.find(o=>o.id==='forge');if(state.stage===3)return world.objects.find(o=>o.id===(ready(state)?'well':'dummy'));if(state.stage===4)return world.objects.find(o=>o.id==='dummy');if(state.stage===5||state.stage===6)return enemies.find(e=>activeEnemy(e)&&e.boss===(state.stage===6));return world.objects.find(o=>o.id==='beacon')}
$('track').onclick=()=>{if(paused())return;const o=objective();if(o){go(o.x,o.z,o);toast(`On the way to ${o.name}`)}};
const markupCache=new Map();function put(id,html){if(markupCache.get(id)!==html){$(id).innerHTML=html;markupCache.set(id,html)}}
function renderUI(){const l=SKILLS.reduce((a,k)=>a+level(state.xp[k]),0);$('totalLevel').textContent=l;$('heroLevel').textContent=Math.max(level(state.xp.Melee),level(state.xp.Magic));$('hpText').textContent=`${Math.ceil(state.hp)} / 100`;$('manaText').textContent=`${Math.floor(state.mana)} / 100`;$('hpBar').style.width=state.hp+'%';$('manaBar').style.width=state.mana+'%';$('questTitle').textContent=stageTitles[state.stage];$('questText').textContent=stageTexts[state.stage];$('chapter').textContent=`${String(Math.min(8,state.stage+1)).padStart(2,'0')} / 08`;$('questProgress').textContent=state.stage===1?`Wood ${Math.min(2,state.bag.wood)} / 2 · Copper ${Math.min(2,state.bag.ore)} / 2`:state.stage===3?`Sword ${Math.min(3,state.training[0])} / 3 · Dagger ${Math.min(3,state.training[1])} / 3`:state.stage===4?`Ember bolts ${Math.min(3,state.training[2])} / 3`:state.stage===5?`Shades released ${state.kills.length} / 3`:state.stage===8?'CROSSING OPEN · Travel to Lantern Reach':'';
 renderQuest();$('characterKit').textContent=state.name+' · '+(state.region==='lab'?'Lab coat · Aster device':(state.reinforced?'Reinforced blades · ':'')+'Traveller’s cloak · Aster device');$('weaponName').textContent=state.crafted?weaponNames[state.weapon]:'WEATHERED SWORD';$('beltToggle').innerHTML=`BELT <span class="sizeLabel">${['Ⅰ','Ⅱ','Ⅲ'][state.belt]} / Ⅲ ⤢</span>`;$('skillsToggle').querySelector('.sizeLabel').textContent=`${['Ⅰ','Ⅱ','Ⅲ'][state.skills]} / Ⅲ ⤢`;
 put('actions',['sword','dagger','magic','fish','dodge','bag'].map((name,i)=>`<button class="action ${state.weapon===i?'active':''}" data-action="${i}" title="${['Equip sword (1)','Equip dagger (2)','Equip ember magic (3)','Eat cooked silverfin (R)','Dodge (Space)','Expand tool belt (B)'][i]}" aria-label="${['Equip sword','Equip dagger','Equip magic','Eat silverfin','Dodge','Expand tool belt'][i]}" ${i===2&&!state.magic?'disabled':''}><span class="key">${['1','2','3','R','␣','B'][i]}</span>${icon(name)}${i===3?`<small>${state.bag.fish}</small>`:''}${i===2&&!state.magic?'<small>◇</small>':''}</button>`).join(''));$('actions').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(paused())return;let n=+b.dataset.action;if(n<3)equip(n);else if(n===3)consume();else if(n===4)dodge();else toggle('belt')});
 put('inventory',[['log','wood','Driftwood'],['ore','ore','Copper ore'],['fish','raw','Raw silverfin'],['fish','fish','Cooked silverfin'],['ember','embers','Recovered embers'],['magic',null,'Aster device']].map(([ic,k,name])=>`<div class="item" title="${name}">${icon(ic)}<small>${k?state.bag[k]:'◆'}</small></div>`).join(''));$('weaponDetail').textContent=['Longsword · 0.68s swing · sweeps nearby foes','Dagger · 0.34s strike · stay close and move','Ember bolt · 9m range · 13 focus · regenerates over time'][state.weapon];
 put('skillGrid',SKILLS.map((s,i)=>{let l=level(state.xp[s]),pct=(state.xp[s]-threshold(l))/(threshold(l+1)-threshold(l))*100;return`<button class="skill ${i===selectedSkill?'active':''}" data-skill="${i}" aria-label="${s} level ${l}, show experience">${icon(skillIcons[i])}<span class="skillname">${s}</span><b>${l}</b><i class="xpLine" style="width:${pct}%"></i></button>`}).join(''));$('skillGrid').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedSkill=+b.dataset.skill;state.skills=2;$('skills').dataset.size=2;if(innerWidth<=600){state.belt=0;$('belt').dataset.size=0;}renderUI();save()});let skill=SKILLS[selectedSkill],xp=state.xp[skill],lv=level(xp),next=threshold(lv+1),prev=threshold(lv);$('skillDetail').innerHTML=`<h3>${skill} <span>· ${lv}</span></h3><div>${xp.toLocaleString()} total experience</div><div class="xpTrack"><i style="width:${(xp-prev)/(next-prev)*100}%"></i></div><div>${next-xp} XP to level ${lv+1}</div><small>${['Train with steel and defeat foes.','Cast ember bolts to strengthen your magic.','Gather driftwood along the shore.','Chip copper from the eastern outcrops.','Catch silverfin from the old jetty.','Forge your copper equipment.'][selectedSkill]}</small>`;
}
// Transient visual effects use shared small geometries; disposed on expiration.
const particleGeo=new T.IcosahedronGeometry(.055,0);
function burst(pos,color,count){for(let i=0;i<count;i++){let m=new T.Mesh(particleGeo,new T.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos);scene.add(m);effects.push({m,life:.5+Math.random()*.5,max:1,vel:new T.Vector3((Math.random()-.5)*3,Math.random()*3+.5,(Math.random()-.5)*3),type:'particle'})}}
function slash(n){const m=new T.Mesh(new T.TorusGeometry(n===1?.85:1.3,.035,3,24,Math.PI*1.2),new T.MeshBasicMaterial({color:'#ffe1a0',transparent:true,opacity:.85}));m.rotation.x=Math.PI/2;m.rotation.z=-player.rotation.y-1;m.position.copy(player.position);m.position.y+=1;scene.add(m);effects.push({m,life:.18,max:.18,type:'slash'})}
function bolt(from,to){const m=new T.Mesh(new T.SphereGeometry(.16,8,6),new T.MeshBasicMaterial({color:'#91ffe5'}));m.position.copy(from).y+=1.2;scene.add(m);effects.push({m,life:.3,max:.3,type:'bolt',start:m.position.clone(),end:to.clone()});const light=new T.PointLight('#78f9db',6,4);m.add(light)}
function floatText(text,pos,color='#ffe4a7',small=false){if(floaters.length>25)return;const el=document.createElement('div');el.className='float';el.textContent=text;el.style.color=color;if(small)el.style.font='10px Manrope, sans-serif';$('floats').append(el);floaters.push({el,pos:pos.clone(),life:1.2,small})}
const labels=[];
function project(pos){const p=pos.clone().project(camera);return{x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight,z:p.z}}
function updateLabels(){const obj=objective();const beacon=world.objects.find(o=>o.id==='beacon');if(beacon)beacon.name=state.beacon?'Crossing · Lantern Reach':'The dark beacon';for(const{o,el}of labels){let d=Math.hypot(player.position.x-o.x,player.position.z-o.z);el.hidden=!started||d>16||!$('dialogue').hidden;const p=project(new T.Vector3(o.x,o.y+(o.kind==='beacon'?6:o.kind==='edda'?2.5:2.0),o.z));el.style.left=p.x+'px';el.style.top=p.y+'px';el.innerHTML=`${obj===o?'<span>◆</span>':''}${o.name}`;}for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];const p=project(f.pos.clone().add(new T.Vector3(0,(1.2-f.life)*1.2+(f.small?2.4:0),0)));f.el.style.left=p.x+'px';f.el.style.top=p.y+'px';f.el.style.opacity=Math.min(1,f.life*2);if(f.life<=0){f.el.remove();floaters.splice(i,1)}}}
function tickEnemies(dt){for(const e of enemies){e.mesh.visible=e.alive&&(state.region==='mainland'||state.stage>=5||e.boss);if(!activeEnemy(e))continue;e.cooldown-=dt;const d=Math.hypot(e.x-player.position.x,e.z-player.position.z);if(e.wind>0){e.wind-=dt;const size=e.boss?3.6:1.9;e.warning.scale.setScalar(size*(1-e.wind/(e.boss?1.15:.85)));e.warning.material.opacity=.25+(1-e.wind/(e.boss?1.15:.85))*.35;if(e.wind<=0){e.warning.visible=false;burst(new T.Vector3(e.attackX,ground(e.attackX,e.attackZ)+.1,e.attackZ),'#e58d6f',e.boss?30:12);if(Math.hypot(player.position.x-e.attackX,player.position.z-e.attackZ)<size)hurt(e.boss?32:14);e.cooldown=e.boss?1.65:1.4}}else if(d<(e.boss?3.3:1.7)&&e.cooldown<=0){e.wind=e.boss?1.15:.85;e.attackX=e.x;e.attackZ=e.z;e.warning.position.set(e.x,ground(e.x,e.z)+.12,e.z);e.warning.visible=true;e.warning.scale.setScalar(.1);tone(110,.3,'sine',.018)}else if(d<(e.boss?13:9)&&d>(e.boss?2.7:1.4)){const speed=e.boss?(e.hp<e.max*.5?2.5:1.65):1.8;let dx=(player.position.x-e.x)/d*dt*speed,dz=(player.position.z-e.z)/d*dt*speed;if(walkable(e.x+dx,e.z+dz)){e.x+=dx;e.z+=dz}}e.mesh.position.set(e.x,ground(e.x,e.z)+Math.sin(clock*3+e.id)*.04,e.z);e.mesh.rotation.y=Math.atan2(player.position.x-e.x,player.position.z-e.z);if(e.boss&&e.hp<e.max*.5&&!e.phase){e.phase=1;toast(e.name+' quickens. Watch the circle.');burst(e.mesh.position,'#8de2ce',25)}}}
function tick(dt){renderer.info.reset();clock+=dt;world.update(clock);if(!paused()){attackCD=Math.max(0,attackCD-dt);actionCD=Math.max(0,actionCD-dt);dodgeCD=Math.max(0,dodgeCD-dt);state.mana=Math.min(100,state.mana+dt*7);moving=false;
 if(dodgeTime>0){dodgeTime=Math.max(0,dodgeTime-dt);move(dodgeDir.x*dt*14,dodgeDir.z*dt*14);moving=true}else{let mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),mz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(mx||mz){destination=null;path=[];selected=null;const d=Math.hypot(mx,mz),dx=(mx*Math.cos(angle)+mz*Math.sin(angle))/d,dz=(-mx*Math.sin(angle)+mz*Math.cos(angle))/d;move(dx*dt*4.5,dz*dt*4.5);player.rotation.y=Math.atan2(dx,dz);moving=true}else if(path.length){const p=path[0],dx=p.x-player.position.x,dz=p.z-player.position.z,d=Math.hypot(dx,dz);if(d<.18)path.shift();else{const speed=Math.min(d,dt*4.3);move(dx/d*speed,dz/d*speed);player.rotation.y=Math.atan2(dx,dz);moving=true}if(!path.length)destination=null}}
 if(selected&&!dodgeTime){if(selected.kind==='enemy'&&!selected.alive)selected=null;else{let range=selected.kind==='dummy'||selected.kind==='enemy'?(state.weapon===2?9:2.15):2.15,dist=Math.hypot(player.position.x-selected.x,player.position.z-selected.z);if(dist<=range){destination=null;path=[];interact(selected);if(selected&&!['enemy','dummy'].includes(selected.kind))selected=null}else if(!destination&&selected.kind==='enemy')go(selected.x,selected.z,selected)}}
 tickEnemies(dt);saveTimer+=dt;if(saveTimer>4){saveTimer=0;save()}uiTimer+=dt;if(uiTimer>.25){uiTimer=0;renderUI();const o=nearest(),near=o&&Math.hypot(o.x-player.position.x,o.z-player.position.z)<5;$('interact').textContent=near?`E · ${o.kind==='enemy'?'Attack':o.kind==='dummy'?'Train':o.kind==='edda'?'Talk to Edda':o.name}`:'E · Interact';$('dodge').style.opacity=dodgeCD>0?.45:1;$('place').textContent=state.region==='lab'?'Aster research · Test chamber':state.region==='mainland'?(player.position.z<-18?'The old observatory':player.position.z<0?'The archive road':'Lantern Reach'):player.position.z<-17?'The last watch':player.position.z<-5?'Drowned garden':player.position.x>9?'Copperstrand':'Keeper’s refuge'}
 }else moving=false;
 steps+=dt*(moving?10:2);player.userData.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(steps+i*Math.PI)*.65:0);player.userData.body.position.y=moving?Math.abs(Math.sin(steps))*.06:Math.sin(clock*2)*.015;if(player.userData.swing>0){player.userData.swing-=dt;player.userData.hand.rotation.x=-Math.sin(player.userData.swing/.25*Math.PI)*1.8}else player.userData.hand.rotation.x=0;
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.type==='particle'){e.m.position.addScaledVector(e.vel,dt);e.vel.y-=dt*5;e.m.material.opacity=Math.max(0,e.life)}if(e.type==='slash')e.m.material.opacity=Math.max(0,e.life/e.max);if(e.type==='bolt')e.m.position.lerpVectors(e.start,e.end,Math.min(1,1-e.life/e.max));if(e.life<=0){scene.remove(e.m);if(e.m.geometry!==particleGeo)e.m.geometry.dispose();e.m.material.dispose();effects.splice(i,1)}}for(const f of floaters)f.life-=dt;
 const creating=!$('creation').hidden;const desired=started?player.position:new T.Vector3(0,0,1);if(creating){const previewZoom=innerWidth<=600?8:6;if(zoom!==previewZoom){zoom=previewZoom;resize();}focus.copy(player.position).add(new T.Vector3(innerWidth<=600?0:1.2,innerWidth<=600?-1.3:.7,0));} if(!creating)focus.lerp(desired,1-Math.exp(-dt*4));camera.position.set(focus.x+Math.sin(angle)*30,focus.y+(creating?12:29),focus.z+Math.cos(angle)*30);camera.lookAt(focus.x,focus.y,focus.z);camera.updateMatrixWorld();world.marker.visible=!!destination;world.marker.rotation.z=clock;world.marker.scale.setScalar(1+Math.sin(clock*5)*.1);if(clock>toastUntil)$('toast').textContent='';const target=selected?.kind==='enemy'?selected:null;$('target').hidden=!target;if(target){$('targetName').textContent=target.name;$('targetHp').style.width=Math.max(0,target.hp/target.max*100)+'%'}updateLabels();if(quality==='high')composer.render();else renderer.render(scene,camera);}
let frames=0;function frame(now){requestAnimationFrame(frame);let dt=Math.min(.05,(now-last)/1000);last=now;try{tick(dt);frames++}catch(e){console.error(e);$('fatal').hidden=false;throw e}}requestAnimationFrame(frame);
window.emberwake={get state(){return state},get world(){return world},camera,enemies,go,interact,equip,attack,dodge,save,get metrics(){return{frames,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,position:player.position.toArray(),effects:effects.length}},project,objective};

const labTitles=['Your first day','A breach in the lab','One way out'];
const labTexts=['Meet Dr Vale beside the test platform. Click to walk, or use WASD.','Take cover behind the storage cabinets. Keep the device out of sight.','Use the device beside the cabinets to escape the intruders.'];
const mainlandTitles=['A town beyond the lesson','A light for the living','The town can breathe','The missing archivist','An impossible entry','A name from home','The second anchor'];
const mainlandTexts=['Speak to Mara at the ward station in town.','Repair all three ward lamps. Each needs 1 wood and 1 copper. Supplies are west of town.','Return to Mara for your reward and news of the archive.','Defeat the two sentinels on the archive road, then speak to Neri.','Defeat the Observatory Custodian and recover the ledger behind it.','Show the ledger to Neri, now safely back at the town archive.','The return channel is blocked. Review your journal, explore, or revisit Edda. The northern road is sealed for now.'];
function findObject(id){return world.objects.find(o=>o.id===id);}
function regionalObjective(){if(state.region==='lab')return findObject(['vale','hide','device'][Math.min(2,state.labStep)]);
 switch(state.mainStage){case 0:case 2:return findObject('mara');case 1:return findObject(state.bag.wood<1?'wood1':state.bag.ore<1?'ore1':['relay1','relay2','relay3'].find(id=>!state.relays.includes(id)));case 3:return enemies.find(e=>!e.boss&&e.alive)||findObject('neri');case 4:return enemies.find(e=>e.boss&&e.alive)||findObject('ledger');case 5:return findObject('neri');default:return findObject('road');}}
function mainAdvance(n,id){state.mainStage=n;syncRegion();save();renderUI();if(id)story(id);}
function regionalInteract(o){
 if(state.region==='lab'){
  if(o.kind==='vale'){if(state.labStep===0)story('lab_test');else toast('Vale is holding the intruders back. Find cover.');}
  else if(o.kind==='sato')toast('Dr Sato checks the return timer: sixty-one seconds.');
  else if(o.kind==='hide'){if(state.labStep===1){state.labStep=2;story('lab_hidden');}else toast(state.labStep===0?'Meet Dr Vale at the test platform.':'Use the device while you are hidden.');}
  else if(o.kind==='device'){if(state.labStep===2){state.labStep=3;enterRegion('island',0,18);story('arrival');tone(740,.9);burst(player.position,'#9dffe3',50);}else toast('Meet Dr Vale first.');}
  return true;
 }
 if(state.region!=='mainland')return false;
 if(o.kind==='mara'){
  state.hp=100;state.mana=100;
  if(state.mainStage===0)mainAdvance(1,'mara');
  else if(state.mainStage===2){state.reinforced=true;state.bag.fish+=3;gain('Smithing',90);mainAdvance(3,'wards_done');toast('Reinforced blades · +4 damage · +3 cooked silverfin');}
  else if(state.mainStage===1)toast('Each ward lamp needs one wood and one copper.');
  else story('mara_repeat');return true;
 }
 if(o.kind==='relay'){
  if(state.relays.includes(o.id))toast('This ward is already holding.');
  else if(repair(state,o.id)){syncRegion();floatText('+65 Smithing XP',player.position,'#f3dda1',true);burst(new T.Vector3(o.x,o.y+2.5,o.z),'#a0ffe0',28);tone(700,.6);toast('Ward restored · '+state.relays.length+' / 3');if(state.relays.length===3)mainAdvance(2);}
  else toast(state.mainStage===0?'Speak to Mara before working on the wards.':'You need 1 wood and 1 copper for this ward.');return true;
 }
 if(o.kind==='neri'){
  if(state.mainStage===3){if([10,11].every(id=>state.mainKills.includes(id))){gain('Magic',80);mainAdvance(4,'neri_rescue');}else toast('Defeat both sentinels before helping Neri.');}
  else if(state.mainStage===5){state.clues.push('second_anchor');gain('Magic',150);state.bag.fish+=2;mainAdvance(6,'neri_truth');}
  else if(state.mainStage===6)story('neri_repeat');else toast(state.mainStage<3?'Speak with Mara at the ward station.':'The observatory ledger is north along the old road.');return true;
 }
 if(o.kind==='ledger'){
  if(state.mainStage===4&&state.mainKills.includes(12)){state.ledger=true;state.clues.push('aster_record');mainAdvance(5,'ledger');}
  else toast(state.ledger?'The ledger is recorded in your journal.':state.mainStage<4?'Help Neri on the archive road first.':'The Custodian still guards this ledger.');return true;
 }
 if(o.kind==='return'){enterRegion('island',0,-24);toast('The first shore. The beacon will take you back.');return true;}
 if(o.kind==='road'){toast('The northern road is sealed. This chapter ends here; your discoveries are saved.');return true;}
 return false;
}
function renderQuest(){
 const region=state.region;$('regionName').textContent=region==='lab'?'ASTER RESEARCH':region==='mainland'?'THE MAINLAND':'THE SUNDOWN ISLES';
 $('quest').querySelector('.eyebrow>span').textContent=region==='lab'?'◆ PROLOGUE':region==='mainland'?'◆ LANTERN REACH':'◆ THE FIRST SHORE';
 if(region==='lab'){$('questTitle').textContent=labTitles[Math.min(2,state.labStep)];$('questText').textContent=labTexts[Math.min(2,state.labStep)];$('chapter').textContent=String(Math.min(3,state.labStep+1)).padStart(2,'0')+' / 03';$('questProgress').textContent='NEW LAB ASSISTANT · '+state.name;}
 if(region==='mainland'){$('questTitle').textContent=mainlandTitles[state.mainStage];$('questText').textContent=mainlandTexts[state.mainStage];$('chapter').textContent=state.mainStage===6?'COMPLETE':(state.mainStage<3?'01':state.mainStage===3?'02':'03')+' / 03';$('questProgress').textContent=state.mainStage===1?`Wards ${state.relays.length} / 3 · Wood ${state.bag.wood} · Copper ${state.bag.ore}`:state.mainStage===3?`Sentinels ${state.mainKills.filter(id=>id!==12).length} / 2`:state.mainStage===6?'CHAPTER COMPLETE · Three mainland missions':'';}
}
function openJournal(){keys.clear();narration?.pause();$('journalTitle').textContent=state.name+'’s field notes';
 const notes=[['Aster Lab',state.labStep>=3?'An attack forced me through the device. Vale tested it for ten seconds, then one minute. The intruders called it a key.':'My first day as a lab assistant. Dr Vale has just returned from the second test.'],['The first shore',state.stage>0?'Edda calls the maker of this place “the Creator,” as though everyone knows who that is. She expected travellers.':'The device appears to reach another dimension. That is still only the lab’s working theory.']];
 if(state.beacon)notes.push(['The crossing','The island beacon opens a passage to Lantern Reach. It works in both directions.']);
 if(state.mainStage>0)notes.push(['01 · A light for the living',state.mainStage>=3?'Complete. Three wards restored. Mara reinforced my blades (+4 damage) and gave me three meals.':`Repair the town’s three ward lamps (${state.relays.length}/3). Each consumes one wood and one copper. Then report to Mara.`]);
 if(state.mainStage>=3)notes.push(['02 · The missing archivist',state.mainStage>=4?'Complete. Neri is safe. The sentinels demanded a traveller’s key; someone changed their orders.':'Two sentinels have Neri trapped on the archive road. Defeat them, then speak to her.']);
 if(state.mainStage>=4)notes.push(['03 · An impossible entry',state.mainStage>=6?'Complete. The ledger records ASTER LAB / RETURN TEST / 00:61. It calls the Creator “Founder.” The return channel is suspended.':'Recover the ledger from the Observatory Custodian and show it to Neri.']);
 if(state.mainStage>=6)notes.push(['Questions still open','Vale’s voice came through the stone: the return setting is watched. Find the second anchor. Who built this world? Why does its old ledger know our lab? Who attacked, and where did they take Vale?'],['Beyond this chapter','Neri is researching the broken coordinates. The northern road is sealed for now. You can gather, fish, cook, train on the island, and travel freely between both shores.']);
 $('journalContent').replaceChildren();for(const [title,text] of notes){const h=document.createElement('h3'),p=document.createElement('p');h.textContent=title;p.textContent=text;$('journalContent').append(h,p);}$('journal').showModal();
}
$('journalBtn').onclick=openJournal;
