// Generated by gen_monsters.py — every monster clip that has ever been
// rendered, plus which one the game plays. Edit through the debug panel
// (Monsters tab) rather than by hand.
window.MonsterVariants = {
  "clips": {
    "attack:alien": {
      "selected": "videos/monster_attack_alien_v2.mp4",
      "variants": [
        {
          "bytes": 242112,
          "created": "2026-05-15 02:08:00",
          "file": "monster_attack_alien.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 23.4,
          "src": "videos/monster_attack_alien.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 449632,
          "created": "2026-08-11 07:53:53",
          "durationSecs": 205.5,
          "file": "monster_attack_alien_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a sleek black-grey alien infiltrator with reflective eyes and a narrow insectile silhouette is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 54.7,
          "src": "videos/monster_attack_alien_v2.mp4",
          "start": "images/monster_attack_alien_start.jpg"
        }
      ]
    },
    "attack:frost": {
      "selected": "videos/monster_attack_frost_v3.mp4",
      "variants": [
        {
          "bytes": 238474,
          "created": "2026-05-18 05:47:31",
          "file": "monster_attack_frost.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 29.7,
          "src": "videos/monster_attack_frost.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 411760,
          "created": "2026-08-11 08:45:51",
          "durationSecs": 219.5,
          "file": "monster_attack_frost_v2.mp4",
          "flags": [
            "runaway"
          ],
          "n": 2,
          "note": "",
          "prompt": "a translucent frost-covered figure forming from rolling cryogenic vapor and ice crystals is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 30,
          "src": "videos/monster_attack_frost_v2.mp4",
          "start": "images/monster_attack_frost_start.jpg"
        },
        {
          "bytes": 379498,
          "created": "2026-08-11 09:46:45",
          "durationSecs": 229.8,
          "file": "monster_attack_frost_v3.mp4",
          "flags": [],
          "n": 3,
          "note": "",
          "prompt": "a translucent frost-covered figure forming from rolling cryogenic vapor and ice crystals is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_frost_v3.mp4",
          "start": "images/monster_attack_frost_start.jpg"
        }
      ]
    },
    "attack:gene": {
      "selected": "videos/monster_attack_gene_v2.mp4",
      "variants": [
        {
          "bytes": 296156,
          "created": "2026-05-15 02:04:42",
          "file": "monster_attack_gene.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 32.4,
          "src": "videos/monster_attack_gene.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 355282,
          "created": "2026-08-11 07:46:57",
          "durationSecs": 215.1,
          "file": "monster_attack_gene_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall bio-engineered humanoid hunter with pale synthetic armor plates and long predatory limbs is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 32.9,
          "src": "videos/monster_attack_gene_v2.mp4",
          "start": "images/monster_attack_gene_start.jpg"
        }
      ]
    },
    "attack:machine": {
      "selected": "videos/monster_attack_machine_v2.mp4",
      "variants": [
        {
          "bytes": 325786,
          "created": "2026-06-11 18:17:37",
          "file": "monster_attack_machine.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 41.0,
          "src": "videos/monster_attack_machine.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 287914,
          "created": "2026-08-11 08:08:40",
          "durationSecs": 220.7,
          "file": "monster_attack_machine_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "an autonomous maintenance rig with jointed repair arms, sensor lenses, and sparking tool claws is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_machine_v2.mp4",
          "start": "images/monster_attack_machine_start.jpg"
        }
      ]
    },
    "attack:mimic": {
      "selected": "videos/monster_attack_mimic_v2.mp4",
      "variants": [
        {
          "bytes": 398157,
          "created": "2026-07-13 22:57:32",
          "file": "monster_attack_mimic.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 32.3,
          "src": "videos/monster_attack_mimic.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 445415,
          "created": "2026-08-11 08:30:58",
          "durationSecs": 219.1,
          "file": "monster_attack_mimic_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a false rescue worker in a clean emergency suit with a visor-glare face and unnaturally smooth posture is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_mimic_v2.mp4",
          "start": "images/monster_attack_mimic_start.jpg"
        }
      ]
    },
    "attack:mirror": {
      "selected": "videos/monster_attack_mirror_v2.mp4",
      "variants": [
        {
          "bytes": 415224,
          "created": "2026-05-18 05:54:32",
          "file": "monster_attack_mirror.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 38.4,
          "src": "videos/monster_attack_mirror.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 382650,
          "created": "2026-08-11 09:00:52",
          "durationSecs": 229.5,
          "file": "monster_attack_mirror_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a duplicate astronaut with a reflective visor and mismatched body language, copying the viewer badly is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_mirror_v2.mp4",
          "start": "images/monster_attack_mirror_start.jpg"
        }
      ]
    },
    "attack:parasite": {
      "selected": "videos/monster_attack_parasite_v5.mp4",
      "variants": [
        {
          "bytes": 267165,
          "created": "2026-05-16 18:57:20",
          "file": "monster_attack_parasite.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 32.8,
          "src": "videos/monster_attack_parasite.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 300701,
          "created": "2026-08-11 08:15:51",
          "durationSecs": 212.8,
          "file": "monster_attack_parasite_v2.mp4",
          "flags": [
            "murky"
          ],
          "n": 2,
          "note": "",
          "prompt": "black root-like alien vines spreading across the floor and walls like a living cable mass is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": -2.7,
          "src": "videos/monster_attack_parasite_v2.mp4",
          "start": "images/monster_attack_parasite_start.jpg"
        },
        {
          "bytes": 586691,
          "created": "2026-08-11 09:31:49",
          "durationSecs": 221.2,
          "file": "monster_attack_parasite_v3.mp4",
          "flags": [
            "murky"
          ],
          "n": 3,
          "note": "",
          "prompt": "black root-like alien vines spreading across the floor and walls like a living cable mass is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": -8.9,
          "src": "videos/monster_attack_parasite_v3.mp4",
          "start": "images/monster_attack_parasite_start.jpg"
        },
        {
          "bytes": 527318,
          "created": "2026-08-11 11:41:43",
          "durationSecs": 224.5,
          "file": "monster_attack_parasite_v4.mp4",
          "flags": [],
          "n": 4,
          "note": "",
          "prompt": "black root-like alien vines spreading across the floor and walls like a living cable mass is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 59.7,
          "src": "videos/monster_attack_parasite_v4.mp4",
          "start": "images/monster_attack_parasite_start.jpg"
        },
        {
          "bytes": 558599,
          "created": "2026-08-11 11:54:07",
          "durationSecs": 184.7,
          "file": "monster_attack_parasite_v5.mp4",
          "flags": [],
          "n": 5,
          "note": "",
          "prompt": "black root-like alien vines spreading across the floor and walls like a living cable mass is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 61.0,
          "src": "videos/monster_attack_parasite_v5.mp4",
          "start": "images/monster_attack_parasite_start.jpg"
        }
      ]
    },
    "attack:radiant": {
      "selected": "videos/monster_attack_radiant_v2.mp4",
      "variants": [
        {
          "bytes": 167227,
          "created": "2026-06-11 21:33:25",
          "file": "monster_attack_radiant.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 38.9,
          "src": "videos/monster_attack_radiant.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 176275,
          "created": "2026-08-11 08:53:21",
          "durationSecs": 215.9,
          "file": "monster_attack_radiant_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a glowing radiation silhouette in a damaged hazard suit, edges flaring with hot white light is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 60,
          "src": "videos/monster_attack_radiant_v2.mp4",
          "start": "images/monster_attack_radiant_start.jpg"
        }
      ]
    },
    "attack:shadow": {
      "selected": "videos/monster_attack_shadow_v4.mp4",
      "variants": [
        {
          "bytes": 283303,
          "created": "2026-05-16 19:01:08",
          "file": "monster_attack_shadow.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 29.1,
          "src": "videos/monster_attack_shadow.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 330323,
          "created": "2026-08-11 08:23:22",
          "durationSecs": 229.7,
          "file": "monster_attack_shadow_v2.mp4",
          "flags": [
            "murky"
          ],
          "n": 2,
          "note": "",
          "prompt": "an empty pressure suit walking by itself, helmet dark, limbs hanging slightly wrong is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": -9.6,
          "src": "videos/monster_attack_shadow_v2.mp4",
          "start": "images/monster_attack_shadow_start.jpg"
        },
        {
          "bytes": 387180,
          "created": "2026-08-11 09:39:20",
          "durationSecs": 225.6,
          "file": "monster_attack_shadow_v3.mp4",
          "flags": [
            "murky"
          ],
          "n": 3,
          "note": "",
          "prompt": "an empty pressure suit walking by itself, helmet dark, limbs hanging slightly wrong is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": -9.9,
          "src": "videos/monster_attack_shadow_v3.mp4",
          "start": "images/monster_attack_shadow_start.jpg"
        },
        {
          "bytes": 491600,
          "created": "2026-08-11 11:45:38",
          "durationSecs": 233.0,
          "file": "monster_attack_shadow_v4.mp4",
          "flags": [],
          "n": 4,
          "note": "",
          "prompt": "an empty pressure suit walking by itself, helmet dark, limbs hanging slightly wrong is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it fills the whole frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, hard corridor light keeps the creature clearly lit and readable the whole time, the creature does not change shape, the shot never goes black, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_shadow_v4.mp4",
          "start": "images/monster_attack_shadow_start.jpg"
        }
      ]
    },
    "attack:siren": {
      "selected": "videos/monster_attack_siren_v2.mp4",
      "variants": [
        {
          "bytes": 502361,
          "created": "2026-06-11 18:06:47",
          "file": "monster_attack_siren.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 36.6,
          "src": "videos/monster_attack_siren.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 437853,
          "created": "2026-08-11 09:08:33",
          "durationSecs": 229.6,
          "file": "monster_attack_siren_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a humanoid emergency alarm host with flashing red beacon lights embedded in its suit and shoulders is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 45.6,
          "src": "videos/monster_attack_siren_v2.mp4",
          "start": "images/monster_attack_siren_start.jpg"
        }
      ]
    },
    "attack:spore": {
      "selected": "videos/monster_attack_spore_v2.mp4",
      "variants": [
        {
          "bytes": 330749,
          "created": "2026-06-11 18:14:00",
          "file": "monster_attack_spore.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 42.6,
          "src": "videos/monster_attack_spore.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 430935,
          "created": "2026-08-11 09:23:50",
          "durationSecs": 219.7,
          "file": "monster_attack_spore_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a breathing spore mass of pale fungal bulbs and drifting dust motes gathering into a hunched shape is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 52.2,
          "src": "videos/monster_attack_spore_v2.mp4",
          "start": "images/monster_attack_spore_start.jpg"
        }
      ]
    },
    "attack:swarm": {
      "selected": "videos/monster_attack_swarm_v2.mp4",
      "variants": [
        {
          "bytes": 346055,
          "created": "2026-06-11 21:30:56",
          "file": "monster_attack_swarm.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 39.0,
          "src": "videos/monster_attack_swarm.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 648829,
          "created": "2026-08-11 08:38:30",
          "durationSecs": 223.1,
          "file": "monster_attack_swarm_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a dense grey nanite cloud forming a rough human outline above the hallway floor is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 45.8,
          "src": "videos/monster_attack_swarm_v2.mp4",
          "start": "images/monster_attack_swarm_start.jpg"
        }
      ]
    },
    "attack:warden": {
      "selected": "videos/monster_attack_warden_v2.mp4",
      "variants": [
        {
          "bytes": 287232,
          "created": "2026-06-11 18:10:24",
          "file": "monster_attack_warden.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 35.3,
          "src": "videos/monster_attack_warden.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 276839,
          "created": "2026-08-11 09:16:24",
          "durationSecs": 224.2,
          "file": "monster_attack_warden_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a bulky containment security android with lockdown plating, clamp arms, and a cold visor slit is already filling the frame at the lens, it surges the last half-step into the camera, its mass swelling until it blacks out the frame, ending pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 57.7,
          "src": "videos/monster_attack_warden_v2.mp4",
          "start": "images/monster_attack_warden_start.jpg"
        }
      ]
    },
    "attack:zombie": {
      "selected": "videos/monster_attack_zombie_v2.mp4",
      "variants": [
        {
          "bytes": 383583,
          "created": "2026-05-15 02:11:42",
          "file": "monster_attack_zombie.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 37.5,
          "src": "videos/monster_attack_zombie.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 577603,
          "created": "2026-08-11 08:01:14",
          "durationSecs": 216.0,
          "file": "monster_attack_zombie_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a reanimated crew member in a torn space uniform, helmet cracked, movements stiff and unnatural is already filling the frame at the lens, it surges the last half-step into the camera, head snapping forward, mouth opening wider, ending on the face pressed against the lens, violent fast jump scare impact, camera shakes hard, the creature does not change shape, no other people, no blood, no gore",
          "score": 70,
          "src": "videos/monster_attack_zombie_v2.mp4",
          "start": "images/monster_attack_zombie_start.jpg"
        }
      ]
    },
    "release:alien": {
      "selected": "videos/monster_release_alien_v2.mp4",
      "variants": [
        {
          "bytes": 179559,
          "created": "2026-05-15 01:58:48",
          "file": "monster_release_alien.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 18.2,
          "src": "videos/monster_release_alien.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 325200,
          "created": "2026-08-11 07:50:23",
          "durationSecs": 201.2,
          "file": "monster_release_alien_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a sleek black-grey alien infiltrator with reflective eyes and a narrow insectile silhouette is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 38.8,
          "src": "videos/monster_release_alien_v2.mp4",
          "start": "images/monster_release_alien_start.jpg"
        }
      ]
    },
    "release:frost": {
      "selected": "videos/monster_release_frost_v2.mp4",
      "variants": [
        {
          "bytes": 304656,
          "created": "2026-05-18 05:19:58",
          "file": "monster_release_frost.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 30.0,
          "src": "videos/monster_release_frost.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 323459,
          "created": "2026-08-11 08:42:10",
          "durationSecs": 219.0,
          "file": "monster_release_frost_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a translucent frost-covered figure forming from rolling cryogenic vapor and ice crystals is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 33.0,
          "src": "videos/monster_release_frost_v2.mp4",
          "start": "images/monster_release_frost_start.jpg"
        }
      ]
    },
    "release:gene": {
      "selected": "videos/monster_release_gene_v2.mp4",
      "variants": [
        {
          "bytes": 241793,
          "created": "2026-05-15 01:56:29",
          "file": "monster_release_gene.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 27.6,
          "src": "videos/monster_release_gene.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 315201,
          "created": "2026-08-11 07:43:22",
          "durationSecs": 209.1,
          "file": "monster_release_gene_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a tall bio-engineered humanoid hunter with pale synthetic armor plates and long predatory limbs is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 32.2,
          "src": "videos/monster_release_gene_v2.mp4",
          "start": "images/monster_release_gene_start.jpg"
        }
      ]
    },
    "release:machine": {
      "selected": "videos/monster_release_machine_v2.mp4",
      "variants": [
        {
          "bytes": 305041,
          "created": "2026-05-16 18:41:55",
          "file": "monster_release_machine.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 35.0,
          "src": "videos/monster_release_machine.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 271630,
          "created": "2026-08-11 08:04:55",
          "durationSecs": 218.8,
          "file": "monster_release_machine_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "an autonomous maintenance rig with jointed repair arms, sensor lenses, and sparking tool claws is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 28.6,
          "src": "videos/monster_release_machine_v2.mp4",
          "start": "images/monster_release_machine_start.jpg"
        }
      ]
    },
    "release:mimic": {
      "selected": "videos/monster_release_mimic_v2.mp4",
      "variants": [
        {
          "bytes": 344279,
          "created": "2026-07-13 22:57:32",
          "file": "monster_release_mimic.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 31.6,
          "src": "videos/monster_release_mimic.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 249310,
          "created": "2026-08-11 08:27:17",
          "durationSecs": 234.2,
          "file": "monster_release_mimic_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a false rescue worker in a clean emergency suit with a visor-glare face and unnaturally smooth posture is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 24.4,
          "src": "videos/monster_release_mimic_v2.mp4",
          "start": "images/monster_release_mimic_start.jpg"
        }
      ]
    },
    "release:mirror": {
      "selected": "videos/monster_release_mirror_v2.mp4",
      "variants": [
        {
          "bytes": 349504,
          "created": "2026-05-18 05:26:47",
          "file": "monster_release_mirror.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 31.2,
          "src": "videos/monster_release_mirror.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 319891,
          "created": "2026-08-11 08:57:02",
          "durationSecs": 220.3,
          "file": "monster_release_mirror_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a duplicate astronaut with a reflective visor and mismatched body language, copying the viewer badly is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 31.3,
          "src": "videos/monster_release_mirror_v2.mp4",
          "start": "images/monster_release_mirror_start.jpg"
        }
      ]
    },
    "release:parasite": {
      "selected": "videos/monster_release_parasite_v2.mp4",
      "variants": [
        {
          "bytes": 303235,
          "created": "2026-07-13 22:57:32",
          "file": "monster_release_parasite.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 24.3,
          "src": "videos/monster_release_parasite.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 256383,
          "created": "2026-08-11 08:12:16",
          "durationSecs": 211.7,
          "file": "monster_release_parasite_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "black root-like alien vines spreading across the floor and walls like a living cable mass is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 28.6,
          "src": "videos/monster_release_parasite_v2.mp4",
          "start": "images/monster_release_parasite_start.jpg"
        }
      ]
    },
    "release:radiant": {
      "selected": "videos/monster_release_radiant_v2.mp4",
      "variants": [
        {
          "bytes": 369190,
          "created": "2026-06-11 17:44:52",
          "file": "monster_release_radiant.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 59.3,
          "src": "videos/monster_release_radiant.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 385213,
          "created": "2026-08-11 08:49:41",
          "durationSecs": 225.8,
          "file": "monster_release_radiant_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a glowing radiation silhouette in a damaged hazard suit, edges flaring with hot white light is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 42.4,
          "src": "videos/monster_release_radiant_v2.mp4",
          "start": "images/monster_release_radiant_start.jpg"
        }
      ]
    },
    "release:shadow": {
      "selected": "videos/monster_release_shadow_v2.mp4",
      "variants": [
        {
          "bytes": 279172,
          "created": "2026-05-16 18:49:49",
          "file": "monster_release_shadow.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 29.3,
          "src": "videos/monster_release_shadow.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 245209,
          "created": "2026-08-11 08:19:31",
          "durationSecs": 217.6,
          "file": "monster_release_shadow_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "an empty pressure suit walking by itself, helmet dark, limbs hanging slightly wrong is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 29.1,
          "src": "videos/monster_release_shadow_v2.mp4",
          "start": "images/monster_release_shadow_start.jpg"
        }
      ]
    },
    "release:siren": {
      "selected": "videos/monster_release_siren_v2.mp4",
      "variants": [
        {
          "bytes": 340775,
          "created": "2026-06-11 17:48:33",
          "file": "monster_release_siren.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 34.4,
          "src": "videos/monster_release_siren.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 274165,
          "created": "2026-08-11 09:04:43",
          "durationSecs": 226.8,
          "file": "monster_release_siren_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a humanoid emergency alarm host with flashing red beacon lights embedded in its suit and shoulders is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 29.8,
          "src": "videos/monster_release_siren_v2.mp4",
          "start": "images/monster_release_siren_start.jpg"
        }
      ]
    },
    "release:spore": {
      "selected": "videos/monster_release_spore_v2.mp4",
      "variants": [
        {
          "bytes": 300897,
          "created": "2026-06-11 17:55:50",
          "file": "monster_release_spore.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 31.2,
          "src": "videos/monster_release_spore.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 305921,
          "created": "2026-08-11 09:20:10",
          "durationSecs": 223.5,
          "file": "monster_release_spore_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a breathing spore mass of pale fungal bulbs and drifting dust motes gathering into a hunched shape is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 29.6,
          "src": "videos/monster_release_spore_v2.mp4",
          "start": "images/monster_release_spore_start.jpg"
        }
      ]
    },
    "release:swarm": {
      "selected": "videos/monster_release_swarm_v2.mp4",
      "variants": [
        {
          "bytes": 260016,
          "created": "2026-06-11 17:41:07",
          "file": "monster_release_swarm.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 35.0,
          "src": "videos/monster_release_swarm.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 195080,
          "created": "2026-08-11 08:34:43",
          "durationSecs": 223.8,
          "file": "monster_release_swarm_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a dense grey nanite cloud forming a rough human outline above the hallway floor is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 24.0,
          "src": "videos/monster_release_swarm_v2.mp4",
          "start": "images/monster_release_swarm_start.jpg"
        }
      ]
    },
    "release:warden": {
      "selected": "videos/monster_release_warden_v2.mp4",
      "variants": [
        {
          "bytes": 296730,
          "created": "2026-06-11 17:52:05",
          "file": "monster_release_warden.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 23.5,
          "src": "videos/monster_release_warden.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 390831,
          "created": "2026-08-11 09:12:39",
          "durationSecs": 245.2,
          "file": "monster_release_warden_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a bulky containment security android with lockdown plating, clamp arms, and a cold visor slit is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, its whole mass turning to face the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 31.9,
          "src": "videos/monster_release_warden_v2.mp4",
          "start": "images/monster_release_warden_start.jpg"
        }
      ]
    },
    "release:zombie": {
      "selected": "videos/monster_release_zombie_v2.mp4",
      "variants": [
        {
          "bytes": 258353,
          "created": "2026-05-15 02:01:30",
          "file": "monster_release_zombie.mp4",
          "flags": [],
          "n": 1,
          "note": "original",
          "prompt": "",
          "score": 27.5,
          "src": "videos/monster_release_zombie.mp4",
          "start": "images/hallway.jpg"
        },
        {
          "bytes": 376625,
          "created": "2026-08-11 07:57:34",
          "durationSecs": 217.9,
          "file": "monster_release_zombie_v2.mp4",
          "flags": [],
          "n": 2,
          "note": "",
          "prompt": "a reanimated crew member in a torn space uniform, helmet cracked, movements stiff and unnatural is already standing at the far end of the corridor, it takes two slow deliberate steps toward the camera and stops, head turning to fix on the lens, the corridor lights flicker once, slow oppressive dread, camera holds still, the creature does not change shape, no other people, no gore",
          "score": 33.2,
          "src": "videos/monster_release_zombie_v2.mp4",
          "start": "images/monster_release_zombie_start.jpg"
        }
      ]
    }
  },
  "game": "awake",
  "generated": "2026-08-11 11:54:07",
  "monsters": [
    {
      "attackRef": "ref/monster_gene_attack.jpg",
      "id": "gene",
      "name": "genetically created monster",
      "ref": "ref/monster_gene.jpg"
    },
    {
      "attackRef": "ref/monster_alien_attack.jpg",
      "id": "alien",
      "name": "alien infiltrator",
      "ref": "ref/monster_alien.jpg"
    },
    {
      "attackRef": "ref/monster_zombie_attack.jpg",
      "id": "zombie",
      "name": "reanimated crew",
      "ref": "ref/monster_zombie.jpg"
    },
    {
      "attackRef": "ref/monster_machine_attack.jpg",
      "id": "machine",
      "name": "maintenance intelligence",
      "ref": "ref/monster_machine.jpg"
    },
    {
      "attackRef": "ref/monster_parasite_attack.jpg",
      "id": "parasite",
      "name": "black root parasite",
      "ref": "ref/monster_parasite.jpg"
    },
    {
      "attackRef": "ref/monster_shadow_attack.jpg",
      "id": "shadow",
      "name": "pressure-suit shadow",
      "ref": "ref/monster_shadow.jpg"
    },
    {
      "attackRef": "ref/monster_mimic_attack.jpg",
      "id": "mimic",
      "name": "voice mimic",
      "ref": "ref/monster_mimic.jpg"
    },
    {
      "attackRef": "ref/monster_swarm_attack.jpg",
      "id": "swarm",
      "name": "nanite swarm",
      "ref": "ref/monster_swarm.jpg"
    },
    {
      "attackRef": "ref/monster_frost_attack.jpg",
      "id": "frost",
      "name": "cryogenic wraith",
      "ref": "ref/monster_frost.jpg"
    },
    {
      "attackRef": "ref/monster_radiant_attack.jpg",
      "id": "radiant",
      "name": "radiation revenant",
      "ref": "ref/monster_radiant.jpg"
    },
    {
      "attackRef": "ref/monster_mirror_attack.jpg",
      "id": "mirror",
      "name": "mirror duplicate",
      "ref": "ref/monster_mirror.jpg"
    },
    {
      "attackRef": "ref/monster_siren_attack.jpg",
      "id": "siren",
      "name": "emergency siren host",
      "ref": "ref/monster_siren.jpg"
    },
    {
      "attackRef": "ref/monster_warden_attack.jpg",
      "id": "warden",
      "name": "containment warden",
      "ref": "ref/monster_warden.jpg"
    },
    {
      "attackRef": "ref/monster_spore_attack.jpg",
      "id": "spore",
      "name": "breathing spore mass",
      "ref": "ref/monster_spore.jpg"
    }
  ],
  "zoom": {
    "videos/monster_attack_alien_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_frost_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_frost_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_gene_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_machine_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_mimic_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_mirror_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_parasite_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_parasite_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_parasite_v4.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_parasite_v5.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_radiant_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_shadow_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_shadow_v3.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_shadow_v4.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_siren_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_spore_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_swarm_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_warden_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    },
    "videos/monster_attack_zombie_v2.mp4": {
      "enabled": true,
      "fade": 0.4,
      "lead": 1.0,
      "scale": 2.6,
      "x": 0.5,
      "y": 0.4
    }
  }
};
