import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {fresh,threshold} from '../state.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const url=process.env.EMBERWAKE_URL||'http://127.0.0.1:8888/gms/3d/emberwake/';
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
async function visit(id){await page.evaluate(id=>{const o=emberwake.world.objects.find(o=>o.id===id);emberwake.go(o.x,o.z,o);},id);}
async function station(id){await visit(id);await page.waitForFunction(()=>document.querySelector('#workshop').open,null,{timeout:20000});}
try{
 const s=fresh();Object.assign(s,{region:'island',labStep:3,stage:3,crafted:true,x:-3,z:15,muted:true,coins:1000});s.bag.raw=6;s.bag.ore=s.bag.wood=30;s.xp.Cooking=threshold(5)-35;s.xp.Smithing=threshold(5)-55;
 await page.goto(url);await page.waitForFunction(()=>window.emberwake?.metrics.frames>5);await page.evaluate(s=>localStorage.setItem('emberwake-v1',JSON.stringify(s)),s);await page.reload();await page.tap('#resume');
 await station('fire');await page.selectOption('#craftQuantity','5');await page.screenshot({path:'/private/tmp/emberwake-kitchen-mobile.png'});await page.tap('[data-recipe=meal]');await page.waitForFunction(()=>emberwake.state.bag.raw===5);await page.waitForTimeout(2700);assert.equal(await page.evaluate(()=>emberwake.state.bag.raw),5);assert.equal(await page.evaluate(()=>emberwake.activity.remaining),4);checks.push('manual Cooking consumes one fish per action; queued batch waits');
 await page.tap('#masteryBtn');const cdp=await page.context().newCDPSession(page);const b=await page.locator('#stoke').boundingBox();let held=false;
 for(let i=0;i<350;i++){const c=await page.evaluate(()=>({status:emberwake.challenge.status,heat:emberwake.challenge.heat}));if(c.status!=='playing')break;const next=held?c.heat<.65:c.heat<.50;if(next!==held){await cdp.send('Input.dispatchTouchEvent',next?{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]}:{type:'touchEnd',touchPoints:[]});held=next;}await page.waitForTimeout(70);}if(held)await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert.equal(await page.evaluate(()=>emberwake.state.mastery.Cooking),1);await page.screenshot({path:'/private/tmp/emberwake-cooking-mastery.png'});await page.tap('#closeMastery');await page.waitForFunction(()=>emberwake.activity.remaining===0,null,{timeout:18000});assert.equal(await page.evaluate(()=>emberwake.state.bag.raw),1);assert.equal(await page.evaluate(()=>emberwake.state.bag.fish),8);await page.waitForTimeout(2500);assert.equal(await page.evaluate(()=>emberwake.state.bag.raw),1);checks.push('touch heat-control victory unlocks automatic batches; exact batch limit is respected');
 await page.evaluate(()=>emberwake.state.hp=1);await page.tap('[data-action="3"]');assert.equal(await page.evaluate(()=>emberwake.state.hp),49);checks.push('Cooking mastery improves meals already in the bag');
 await station('forge');assert(await page.locator('[data-recipe=temper]').isDisabled());await page.selectOption('#craftQuantity','5');await page.tap('[data-recipe=ingot]');await page.waitForFunction(()=>emberwake.state.bag.ingot===1);await page.waitForTimeout(3500);assert.equal(await page.evaluate(()=>emberwake.state.bag.ingot),1);await page.tap('#masteryBtn');
 for(let i=0;i<6;i++){await page.waitForFunction(()=>emberwake.challenge.cooldown===0&&Math.abs(emberwake.challenge.cursor-(emberwake.challenge.hits%2?.3:.7))<.04);await page.keyboard.press('Space');}
 assert.equal(await page.evaluate(()=>emberwake.state.mastery.Smithing),1);await page.screenshot({path:'/private/tmp/emberwake-smithing-mastery.png'});await page.tap('#closeMastery');await page.waitForFunction(()=>emberwake.activity.remaining===0,null,{timeout:18000});assert.equal(await page.evaluate(()=>emberwake.state.bag.ingot),5);checks.push('anvil timing victory unlocks repeatable automatic smelting');
 await page.tap('#workRecipes');await page.tap('[data-recipe=temper]');await page.waitForFunction(()=>emberwake.state.bladeTier===1);assert.equal(await page.evaluate(()=>emberwake.state.bag.ingot),3);await page.tap('#beltToggle');await page.tap('#beltToggle');assert.match(await page.locator('#weaponDetail').textContent(),/Temper \+2 damage/);await page.tap('#beltToggle');checks.push('tempering spends ingots and exposes a permanent melee damage bonus');
 await visit('shop');await page.waitForFunction(()=>document.querySelector('#shop').open);await page.tap('[data-tool=Fishing]');assert.equal(await page.evaluate(()=>emberwake.state.tools.Fishing),1);assert.equal(await page.evaluate(()=>emberwake.state.coins),940);await page.tap('#closeShop');await visit('fish');await page.waitForFunction(()=>emberwake.world.player.userData.workSignature==='fish:1',null,{timeout:20000});assert(await page.evaluate(()=>emberwake.world.player.userData.workTool.children.length>1));await page.tap('#stopWork');checks.push('shop tool purchase equips visible tiered tools while gathering');
 await page.reload();await page.tap('#resume');assert.equal(await page.evaluate(()=>emberwake.state.bladeTier),1);assert.equal(await page.evaluate(()=>emberwake.state.mastery.Cooking),1);assert.equal(await page.evaluate(()=>emberwake.state.tools.Fishing),1);checks.push('artisan mastery, tempering and tool purchases survive reload');
 for(const size of [{width:320,height:568},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(300);await page.getByRole('button',{name:/Cooking level/}).tap();const b=await page.locator('#skills').boundingBox();assert(b.x>=0&&b.y>=0&&b.x+b.width<=size.width+1&&b.y+b.height<=size.height+1);assert(await page.locator('#skillDetail').isVisible());await page.tap('#skillsToggle');}checks.push('seven-skill layout and Cooking details fit small phones');
 await page.setViewportSize({width:390,height:844});await station('fire');await page.screenshot({path:'/private/tmp/emberwake-artisan-recipes.png'});await page.tap('#closeWorkshop');const metrics=await page.evaluate(()=>emberwake.metrics);assert(metrics.drawCalls>10&&metrics.triangles>1000);assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks,metrics,errors},null,2));
}catch(e){console.error(await page.evaluate(()=>({state:emberwake?.state,activity:emberwake?.activity&&{kind:emberwake.activity.object.kind,remaining:emberwake.activity.remaining,waiting:emberwake.activity.waiting},challenge:emberwake?.challenge,metrics:emberwake?.metrics})));await page.screenshot({path:'/private/tmp/emberwake-artisan-failure.png'});throw e;}finally{await browser.close();}
