import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {fresh} from '../state.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const errors=[];const url=process.env.EMBERWAKE_URL||'http://127.0.0.1:8891/gms/3d/emberwake/';
async function load(page,s){await page.goto(url);await page.waitForFunction(()=>window.emberwake?.metrics.frames>5);await page.evaluate(s=>localStorage.setItem('emberwake-v1',JSON.stringify(s)),s);await page.reload();await page.click('#resume')}
let page;try{
 page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await load(page,fresh());const target=await page.evaluate(()=>emberwake.project(emberwake.world.player.position.clone().set(4,.6,18)));await page.touchscreen.tap(target.x,target.y);await page.waitForFunction(()=>Math.abs(emberwake.world.player.position.x-4)<.5);
 await page.tap('#beltToggle');assert.equal(await page.locator('#belt').getAttribute('data-size'),'1');await page.tap('#beltToggle');assert.equal(await page.locator('#belt').getAttribute('data-size'),'2');await page.getByRole('button',{name:/Mining level/}).tap();assert.equal(await page.locator('#belt').getAttribute('data-size'),'0');assert.equal(await page.locator('#skills').getAttribute('data-size'),'2');await page.tap('#skillsToggle');
 for(const width of[320,390]){await page.setViewportSize({width,height:844});const bounds=await page.locator('.skill').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&e.scrollWidth<=e.clientWidth+1}));assert(bounds.every(Boolean),JSON.stringify(bounds));}
 await page.tap('#settingsBtn');await page.selectOption('#quality','low');await page.getByRole('button',{name:'Return to the island',exact:true}).tap();await page.waitForTimeout(300);await page.screenshot({path:'/private/tmp/emberwake-touch.png'});
 // Place a completed-training save into the real boss encounter to verify dodge and recovery.
 const s=fresh();Object.assign(s,{stage:6,crafted:true,magic:true,x:0,z:-19,weapon:0,kills:[0,1,2],training:[3,3,3]});await load(page,s);await page.waitForFunction(()=>emberwake.enemies.find(e=>e.boss).wind>0);await page.tap('#dodge');await page.waitForTimeout(1300);assert.equal(await page.evaluate(()=>emberwake.state.hp),100);assert(await page.evaluate(()=>emberwake.world.player.position.z>-17));
 // Stay inside a telegraphed attack at one vitality: death must preserve quest progress.
 await page.evaluate(()=>{const p=emberwake.world.player,e=emberwake.enemies.find(e=>e.boss);p.position.set(e.x,e.mesh.position.y,e.z+.5);emberwake.state.hp=1});await page.waitForFunction(()=>emberwake.world.player.position.z>10,null,{timeout:12000});assert.equal(await page.evaluate(()=>emberwake.state.hp),100);assert.deepEqual(await page.evaluate(()=>emberwake.state.kills),[0,1,2]);assert.equal(await page.evaluate(()=>emberwake.state.stage),6);
 // Fishing, cooking and food consumption use the live interactions.
 await page.evaluate(()=>{const g=emberwake,o=g.world.objects.find(o=>o.id==='fish');g.go(o.x,o.z,o)});await page.waitForFunction(()=>emberwake.state.bag.raw>0,null,{timeout:15000});await page.evaluate(()=>{const g=emberwake,o=g.world.objects.find(o=>o.id==='fire');g.go(o.x,o.z,o)});await page.waitForFunction(()=>emberwake.state.bag.raw===0,null,{timeout:15000});assert.equal(await page.evaluate(()=>emberwake.state.bag.fish),4);await page.evaluate(()=>emberwake.state.hp=30);await page.getByRole('button',{name:'Eat silverfin',exact:true}).tap();assert.equal(await page.evaluate(()=>emberwake.state.hp),75);assert.equal(await page.evaluate(()=>emberwake.state.bag.fish),3);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks:['real touch ground movement','touch belt states','mobile full panels do not stack','320px skill contents fit','low quality rendering','dodge evades boss strike','death returns to fire without progress loss','fishing','cooking','food heals 45'],errors},null,2));
}catch(e){console.error(await page.evaluate(()=>({state:emberwake.state,metrics:emberwake.metrics})));await page.screenshot({path:'/private/tmp/emberwake-interaction-failure.png'});throw e}finally{await browser.close()}
