import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {fresh,threshold} from '../state.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const url=process.env.EMBERWAKE_URL||'http://127.0.0.1:8888/gms/3d/emberwake/';
const errors=[],checks=[];let page;
async function load(s){await page.goto(url);await page.waitForFunction(()=>window.emberwake?.metrics.frames>5);await page.evaluate(s=>localStorage.setItem('emberwake-v1',JSON.stringify(s)),s);await page.reload();await page.click('#resume');}
async function visit(id){await page.evaluate(id=>{const g=emberwake,o=g.world.objects.find(o=>o.id===id);g.go(o.x,o.z,o);},id);}
async function work(kind){await visit(kind==='wood'?'wood1':kind==='ore'?'ore1':'fish');await page.waitForFunction(kind=>emberwake.activity?.object.kind===kind,kind,{timeout:20000});}
const fixture=()=>({...fresh(),region:'island',labStep:3,muted:true,stage:1,x:8,z:24});
try{
 page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 let s=fixture();s.xp.Fishing=threshold(5)-40;await load(s);await work('fish');await page.waitForFunction(()=>emberwake.state.bag.raw===1);await page.waitForTimeout(3500);assert.equal(await page.evaluate(()=>emberwake.state.bag.raw),1);assert(await page.locator('#gatherAgain').isVisible());assert(await page.locator('#masteryBtn').isVisible());checks.push('one manual catch reaches level 5; no automatic second catch');
 await page.click('#masteryBtn');let reel=await page.locator('#reel').boundingBox();await page.mouse.move(reel.x+reel.width/2,reel.y+reel.height/2);let held=false;
 for(let i=0;i<350;i++){const c=await page.evaluate(()=>({status:emberwake.challenge.status,tension:emberwake.challenge.tension}));if(c.status!=='playing')break;const shouldHold=held?c.tension<.75:c.tension<.3;if(shouldHold!==held){if(shouldHold)await page.mouse.down();else await page.mouse.up();held=shouldHold;}await page.waitForTimeout(80);}await page.mouse.up();
 assert.equal(await page.evaluate(()=>emberwake.state.mastery.Fishing),1);await page.screenshot({path:'/private/tmp/emberwake-mastery-desktop.png'});await page.click('#closeMastery');await page.waitForFunction(()=>emberwake.state.bag.raw>=3);checks.push('real hold/release fishing victory unlocks automatic repeat');
 await page.click('#settingsBtn');const count=await page.evaluate(()=>emberwake.state.bag.raw);await page.waitForTimeout(3500);assert.equal(await page.evaluate(()=>emberwake.state.bag.raw),count);await page.getByRole('button',{name:'Return to the journey',exact:true}).click();await page.waitForFunction(n=>emberwake.state.bag.raw>n,count);await page.keyboard.press('w');await page.waitForFunction(()=>!emberwake.activity);checks.push('menus pause; closing resumes; keyboard movement cancels');
 await page.reload();await page.click('#resume');assert.equal(await page.evaluate(()=>emberwake.state.mastery.Fishing),1);assert.equal(await page.evaluate(()=>emberwake.activity),null);checks.push('mastery persists; activity does not resume after reload');
 await visit('shop');await page.waitForFunction(()=>document.querySelector('#shop').open);const coins=await page.evaluate(()=>emberwake.state.coins);await page.click('[data-item="raw"][data-side="sell"][data-quantity="1"]');assert.equal(await page.evaluate(()=>emberwake.state.coins),coins+5);await page.click('[data-item="wood"][data-side="buy"]');assert.equal(await page.evaluate(()=>emberwake.state.bag.wood),1);await page.screenshot({path:'/private/tmp/emberwake-shop-desktop.png'});await page.click('#closeShop');checks.push('island stall buys and sells at mastery prices');
 await work('fish');await page.click('#stopWork');assert.equal(await page.evaluate(()=>emberwake.activity),null);checks.push('Stop cancels automatic work');
 // Mobile touch input uses Chrome touch events, including a held finger on the reel.
 await page.close();page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 s=fixture();s.xp.Fishing=threshold(10);s.mastery.Fishing=1;s.xp.Woodcutting=s.xp.Mining=threshold(5);await load(s);await work('fish');await page.tap('#masteryBtn');
 const cdp=await page.context().newCDPSession(page);reel=await page.locator('#reel').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:reel.x+reel.width/2,y:reel.y+reel.height/2}]});await page.waitForTimeout(700);assert(await page.evaluate(()=>emberwake.challenge.progress>.02));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});let tension=await page.evaluate(()=>emberwake.challenge.tension);await page.waitForTimeout(500);assert(await page.evaluate(t=>emberwake.challenge.tension<t,tension));
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:reel.x+reel.width/2,y:reel.y+reel.height/2}]});await page.waitForFunction(()=>emberwake.challenge.status==='snapped');await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>emberwake.state.mastery.Fishing),1);await page.tap('#retryMastery');assert.equal(await page.evaluate(()=>emberwake.challenge.status),'playing');await page.tap('#closeMastery');checks.push('real touch hold reels, release eases, snapping is safe, retry resets');
 await work('wood');await page.tap('#masteryBtn');for(let i=0;i<6;i++){await page.waitForFunction(()=>emberwake.challenge.cooldown===0&&Math.abs(emberwake.challenge.cursor-.5)<.06);await page.keyboard.press('Space');}assert.equal(await page.evaluate(()=>emberwake.state.mastery.Woodcutting),1);await page.tap('#closeMastery');checks.push('woodcutting timing challenge with keyboard access');
 await work('ore');await page.tap('#masteryBtn');for(let i=0;i<6;i++){await page.waitForFunction(()=>emberwake.challenge.cooldown===0);await page.tap('#miningChallenge .weak');}assert.equal(await page.evaluate(()=>emberwake.state.mastery.Mining),1);await page.tap('#closeMastery');checks.push('mining touch targets unlock automatic mining');
 const bounds=[];for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.waitForTimeout(150);bounds.push(await page.locator('#work').evaluate(el=>{const r=el.getBoundingClientRect();return {width:innerWidth,inside:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,overflow:document.documentElement.scrollWidth>innerWidth};}));}assert(bounds.every(b=>b.inside&&!b.overflow),JSON.stringify(bounds));await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.screenshot({path:'/private/tmp/emberwake-work-mobile.png'});
 await page.tap('#stopWork');s={...fixture(),region:'mainland',x:7,z:12};await load(s);await visit('shop');await page.waitForFunction(()=>document.querySelector('#shop').open);assert.equal(await page.locator('#shopTitle').textContent(),'Lantern market');await page.tap('[data-item="wood"][data-side="buy"]');assert.equal(await page.evaluate(()=>emberwake.state.bag.wood),1);await page.screenshot({path:'/private/tmp/emberwake-shop-mobile.png'});await page.tap('#closeShop');checks.push('mobile activity fits 320/390/768px; mainland market works');
 const metrics=await page.evaluate(()=>emberwake.metrics);assert(metrics.drawCalls>10&&metrics.triangles>1000,JSON.stringify(metrics));assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks,bounds,metrics,errors},null,2));
}catch(e){if(page&&!page.isClosed()){console.error(await page.evaluate(()=>({state:emberwake?.state,activity:emberwake?.activity?.object.id,challenge:emberwake?.challenge,metrics:emberwake?.metrics})));await page.screenshot({path:'/private/tmp/emberwake-professions-failure.png'});}throw e;}finally{await browser.close();}
