import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {fresh} from '../state.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)errors.push(r.url())});
const url=process.env.EMBERWAKE_URL||'http://127.0.0.1:8891/gms/3d/emberwake/';
async function load(s){await p.goto(url);await p.waitForFunction(()=>window.emberwake?.metrics.frames>4);await p.evaluate(s=>localStorage.setItem('emberwake-v1',JSON.stringify(s)),s);await p.reload();await p.click('#resume');}
try{
 await load({...fresh(),x:0,z:7,pendingStory:'lab_intro',muted:true});assert(await p.locator('#dialogue').isHidden());assert(await p.locator('#speechText').isVisible());
 const before=await p.evaluate(()=>emberwake.metrics.position);await p.keyboard.down('KeyD');await p.waitForTimeout(650);await p.keyboard.up('KeyD');const after=await p.evaluate(()=>emberwake.metrics.position);assert(Math.hypot(after[0]-before[0],after[2]-before[2])>1);
 await p.tap('#speechOpen');assert(await p.locator('#dialogue').isVisible());const elapsed=await p.evaluate(()=>emberwake.speech.elapsed),position=await p.evaluate(()=>emberwake.metrics.position);await p.keyboard.down('KeyD');await p.waitForTimeout(700);await p.keyboard.up('KeyD');assert.deepEqual(await p.evaluate(()=>emberwake.metrics.position),position);assert.equal(await p.evaluate(()=>emberwake.speech.elapsed),elapsed);await p.tap('#continue');assert.equal(await p.evaluate(()=>emberwake.speech.id),'lab_intro');assert(await p.locator('#dialogue').isHidden());
 // Text-only play advances automatically and retains the last full transcript.
 await p.waitForFunction(()=>!emberwake.speech.id,null,{timeout:25000});await p.tap('#speechOpen');assert.match(await p.locator('#dialogueText').textContent(),/first shift/);await p.tap('#continue');
 // The spoken lab chain advances without a modal or a Continue click.
 await load({...fresh(),x:0,z:2,pendingStory:'lab_return',muted:true});await p.waitForFunction(()=>emberwake.state.labStep===1,null,{timeout:25000});assert.equal(await p.evaluate(()=>emberwake.speech.id),'lab_attack');assert(await p.locator('#dialogue').isHidden());await p.evaluate(()=>{const g=emberwake;g.interact(g.world.objects.find(o=>o.id==='device'));});assert.equal(await p.evaluate(()=>emberwake.travelling),false);
 // The rift is the visible, clickable destination, away from the old box marker.
 await load({...fresh(),labStep:2,x:3,z:7,gender:'female',pendingStory:'lab_escape'});await p.waitForTimeout(400);assert(await p.evaluate(()=>emberwake.world.escapeRift.visible));assert.deepEqual(await p.evaluate(()=>{const o=emberwake.objective();return[o.id,o.x,o.z]}),['device',6,5]);
 await p.screenshot({path:'/private/tmp/emberwake-rift-mobile.png'});
 const point=await p.evaluate(()=>{const o=emberwake.objective();return emberwake.project(emberwake.world.player.position.clone().set(o.x,1.6,o.z))});await p.touchscreen.tap(point.x,point.y);await p.waitForFunction(()=>emberwake.travelling,null,{timeout:12000});assert(await p.locator('#dialogue').isHidden());assert(await p.locator('#speech').isHidden());await p.screenshot({path:'/private/tmp/emberwake-rift-departure.png'});
 await p.waitForFunction(()=>emberwake.state.region==='island');assert(await p.evaluate(()=>emberwake.travelling));assert(await p.locator('#dialogue').isHidden());await p.screenshot({path:'/private/tmp/emberwake-rift-arrival.png'});await p.waitForFunction(()=>!emberwake.travelling);assert.equal(await p.evaluate(()=>emberwake.speech.id),'arrival');assert.match(await p.locator('#voiceStatus').textContent(),/BELLA/);
 // A new quest line queues behind ongoing speech instead of losing it or interrupting movement.
 await p.evaluate(()=>emberwake.interact(emberwake.world.objects.find(o=>o.id==='edda')));assert.deepEqual(await p.evaluate(()=>emberwake.speech.queued),['keeper']);await p.reload();await p.click('#resume');assert.equal(await p.evaluate(()=>emberwake.speech.id),'arrival');assert.deepEqual(await p.evaluate(()=>emberwake.speech.queued),['keeper']);await p.tap('#speechNext');assert.equal(await p.evaluate(()=>emberwake.speech.id),'keeper');await p.tap('#speechNext');assert.equal(await p.evaluate(()=>emberwake.speech.id),'creator');
 for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await p.setViewportSize(size);await p.waitForTimeout(100);const bounds=await p.locator('#speech').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=size.width+1&&bounds.y>=0&&bounds.y+bounds.height<=size.height);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks:['speech allows movement','message icon pauses movement and subtitle timer','closing transcript resumes same speech','muted automatic progression','last message remains readable','automatic lab boom and speech chain','rift gated until hiding','touch picks actual rift','unobstructed departure and arrival','queued speech survives reload','four subtitle layouts'],errors},null,2));
}catch(e){console.log(await p.evaluate(()=>({state:emberwake.state,speech:emberwake.speech,metrics:emberwake.metrics})));await p.screenshot({path:'/private/tmp/emberwake-speech-failure.png'});throw e;}finally{await browser.close();}
