"""Build audio/manifest.json from script.json, music.json and the files on disk. Paths are relative to the game root."""
import json, os, subprocess
H = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(H, '../..'))
S = json.load(open(os.path.join(H, 'script.json')))
M = json.load(open(os.path.join(H, 'music.json')))


def dur(rel):
    p = os.path.join(ROOT, rel)
    if not os.path.exists(p): return None
    o = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', p], capture_output=True, text=True).stdout
    return round(float(o), 2)


vo = {}
for k, c in S['chars'].items():
    lines, wl = [], []
    for l in c['lines']:
        f = f'audio/vo/{k}/{l["id"]}.mp3'; d = dur(f)
        if d is None: continue
        lines.append(dict(id=l['id'], text=l['text'], file=f, dur=d, trig=l['trig'], once=bool(l.get('once')), rude=bool(l.get('rude'))))
    for w in c['wordless']:
        f = f'audio/vo/{k}/{w["id"]}.mp3'; d = dur(f)
        if d is None: continue
        wl.append(dict(id=w['id'], text=w['text'], kind=w['kind'], file=f, dur=d))
    if lines or wl:
        vo[k] = dict(name=c['name'], lines=lines, wordless=wl)

music = {}
for k, c in M.items():
    f = f'audio/music/{k}.mp3'; d = dur(f)
    if d is None: continue
    music[k] = dict(file=f, loop=c['loop'], dur=d, title=c['title'], stinger=k.startswith('st_') or k == 'duel')

piano = {'riffs': [], 'samples': [], 'phrases': None}
pj = os.path.join(ROOT, 'audio/piano/phrases.json')
kinds = {}
if os.path.exists(pj):
    P = json.load(open(pj))
    piano['samples'] = P['samples']; piano['phrases'] = 'audio/piano/phrases.json'
    kinds = {p['id']: (p['kind'], p['title']) for p in P['phrases']}
ace_meta = {}
am = os.path.join(H, 'piano_log.json')
if os.path.exists(am): ace_meta = json.load(open(am)).get('riffs', {})
rd = os.path.join(ROOT, 'audio/piano/riffs')
for f in sorted(os.listdir(rd)) if os.path.isdir(rd) else []:
    if not f.endswith('.mp3'): continue
    rid = f[:-4]
    if rid.startswith('syn_'):
        kind, title = kinds.get(rid[4:], ('vamp', rid))
        src = 'synth'
    else:
        kind, title, src = ace_meta.get(rid, {}).get('kind', 'vamp'), rid, 'ace'
    piano['riffs'].append(dict(id=rid, file=f'audio/piano/riffs/{f}', dur=dur(f'audio/piano/riffs/{f}'), kind=kind, src=src, title=title))


def size(d):
    t = 0
    for a, _, fs in os.walk(os.path.join(ROOT, d)):
        t += sum(os.path.getsize(os.path.join(a, f)) for f in fs if f.endswith('.mp3') or f.endswith('.json'))
    return t

budget = {d: size(f'audio/{d}') for d in ('vo', 'music', 'piano')}
budget['total'] = sum(budget.values())
man = dict(version=1, note='Generated by tools/audio/manifest.py. Paths relative to the game root. See docs/AUDIO.md for playback rules.',
           vo=vo, music=music, piano=piano, bytes=budget)
json.dump(man, open(os.path.join(ROOT, 'audio/manifest.json'), 'w'), indent=1, ensure_ascii=False)
print({k: f'{v / 1e6:.2f} MB' for k, v in budget.items()}, 'lines', sum(len(v['lines']) for v in vo.values()),
      'wordless', sum(len(v['wordless']) for v in vo.values()), 'cues', len(music), 'riffs', len(piano['riffs']))
