// node js/actors/human_head_bake.mjs <lyman|delivery>  → rewrites <name>_head_data.js (pre-meshed SDF head per quality)
// (Jon's head: jon_head_bake.mjs.) Run after editing the head's SDF primitives.
import { writeFileSync } from 'fs';
import { makeHead } from './human_head.js';
const name = process.argv[2];
const mod = await import(`./${name}_head.js`);
const h = makeHead(mod.BASE, { data: null });
const b64 = (ta) => Buffer.from(ta.buffer, ta.byteOffset, ta.byteLength).toString('base64');
const out = {};
for (const q of ['high', 'medium', 'low']) {
  const m = h.meshHead(q);
  out[q] = { pos: b64(new Float32Array(m.pos)), idx: b64(new Uint16Array(m.idx)) };
  console.log(name, q, m.idx.length / 3, 'tris');
}
writeFileSync(new URL(`./${name}_head_data.js`, import.meta.url), `// generated by human_head_bake.mjs ${name} — do not edit\nexport const HEAD_DATA = ` + JSON.stringify(out) + ';\n');
