// node js/actors/jon_head_bake.mjs  → rewrites jon_head_data.js (pre-meshed SDF head per quality)
import { writeFileSync } from 'fs';
import { meshHead } from './jon_head.js';
const b64 = (ta) => Buffer.from(ta.buffer, ta.byteOffset, ta.byteLength).toString('base64');
const out = {};
for (const q of ['high', 'medium', 'low']) {
  const m = meshHead(q);
  out[q] = { pos: b64(new Float32Array(m.pos)), idx: b64(new Uint16Array(m.idx)) };
  console.log(q, m.idx.length / 3, 'tris');
}
writeFileSync(new URL('./jon_head_data.js', import.meta.url), '// generated by jon_head_bake.mjs — do not edit\nexport const HEAD_DATA = ' + JSON.stringify(out) + ';\n');
