import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const { chromium }=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'/private/tmp/tanking-tools/node_modules/playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const errors=[],checks=[];
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1,acceptDownloads:true});
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,600))});
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
const check=(name,value)=>{assert.ok(value,name);checks.push(name)};
const run=fn=>page.evaluate(fn);
try {
  await page.goto(process.env.TANKING_URL||'http://127.0.0.1:8888/gms/3d/tanking/');
  await page.waitForFunction(()=>window.tanking?.metrics.frames>30);
  check('attract screen starts without asset requests',!await page.locator('#boot').isVisible());
  await page.screenshot({path:'/private/tmp/tanking-final-landing.png'});
  await page.locator('#begin').click();await page.locator('[data-speed="0"]').click();
  check('career starts in 20 gallons with an incomplete tetra school',await run(()=>tanking.state.tanks[0].gallons===20&&tanking.state.tanks[0].fish.filter(f=>f.id==='neon').length===4));
  await page.locator('[data-panel="stock"]').click();await page.locator('[data-species="neon"]').click();
  check('live compatibility recommends two companions',await page.locator('#buyCount').inputValue()==='2'&&(await page.locator('#compatibility').textContent()).includes('promising'));
  await page.locator('#purchase').click();await run(()=>tanking.step(1));
  check('gentle tutorial resolves and grants funds',await run(()=>tanking.state.stage===1&&tanking.known.includes('school')));
  check('wrong water is red',await run(()=>tanking.compatibility('clown',tanking.state.tanks[0]).level==='red'));
  await page.locator('#panelClose').click();await page.locator('[data-panel="habitat"]').click();
  await page.locator('[data-decor="plants"]').click();await page.locator('[data-decor="plants"]').click();await page.locator('[data-upgrade="filter"]').click();await run(()=>tanking.step(1));
  check('habitat and filter advance career',await run(()=>tanking.state.stage===2));
  check('overfeeding creates waste; water exchange reduces toxins',await run(()=>{let t=tanking.state.tanks[0];tanking.feed();tanking.feed();tanking.feed();tanking.step(12);let before=t.ammonia+t.nitrite+t.waste; t.money=1000;tanking.waterChange();return before>0&&t.ammonia+t.nitrite+t.waste<before}));
  await page.locator('#panelClose').click();await page.locator('#sound').click();
  check('ambient audio toggles',await page.locator('#sound').getAttribute('aria-label')==='Mute ambient audio');
  await page.locator('[data-speed="1"]').click();let time=await run(()=>tanking.state.time);await page.waitForTimeout(600);check('1x advances time',await run(()=>tanking.state.time)>time);
  await page.locator('[data-speed="0"]').click();time=await run(()=>tanking.state.time);await page.waitForTimeout(300);check('pause freezes simulation',await run(()=>tanking.state.time)===time);
  await page.locator('[data-speed="3"]').click();await page.waitForTimeout(500);check('3x advances faster',await run(()=>tanking.state.time)>time+1);
  await page.locator('[data-speed="0"]').click();
  const simResults=await run(()=>{
    let results={};
    tanking.start('puzzle','rescue','rescue-test');let t=tanking.state.tanks[0];let initial=t.health;tanking.waterChange();tanking.buyUpgrade('filter');for(let i=0;i<3;i++){tanking.step(6);tanking.waterChange()}tanking.step(160);results.rescue={won:tanking.state.won,health:t.health,initial,losses:tanking.state.losses};
    tanking.start('career',null,'cycle-test');t=tanking.state.tanks[0];t.ammonia=2;t.nitrite=0;t.nitrate=0;t.plants=0;t.oxygen=8;t.up.filter=1;tanking.step(30);results.cycle={ammonia:t.ammonia,nitrite:t.nitrite,nitrate:t.nitrate};
    tanking.start('career',null,'predator-test');t=tanking.state.tanks[0];tanking.state.money=9999;tanking.buyFish('angel',1);let angel=t.fish.find(f=>f.id==='angel');angel.age=1;tanking.step(110);results.angel={discovered:tanking.known.includes('angel'),losses:tanking.state.losses,warning:tanking.state.notifications.some(n=>n.text.includes('eyeing'))};
    tanking.start('zen',null,'puffer-test');t=tanking.state.tanks[0];tanking.buyFish('snail',1);tanking.buyFish('puffer',1);tanking.state.mode='survival';tanking.state.eventAt=1000;tanking.step(150);results.puffer={discovered:tanking.known.includes('puffer'),snails:t.fish.filter(f=>f.id==='snail').length};
    tanking.start('career',null,'fin-test');t=tanking.state.tanks[0];tanking.state.money=9999;tanking.buyFish('angel',1);tanking.buyFish('betta',1);tanking.state.mode='career';tanking.step(90);results.betta={discovered:tanking.known.includes('betta'),fin:t.fish.find(f=>f.id==='angel')?.fin};
    tanking.start('conservation',null,'breed-test');t=tanking.state.tanks[0];tanking.state.money=9999;for(let i=0;i<6;i++){tanking.feed();tanking.step(88);tanking.releaseYoung();}results.breed={releases:tanking.state.releases,won:tanking.state.won,health:t.health};
    tanking.start('zen',null,'zen-test');t=tanking.state.tanks[0];let count=t.fish.length;t.ammonia=20;t.nitrite=20;t.oxygen=.1;t.fish.forEach(f=>{f.health=.01;f.hunger=100});tanking.step(2);results.zen=t.fish.length===count&&t.fish.every(f=>f.health===100);
    tanking.start('puzzle','peace','peace-test');results.peace=!tanking.buyFish('betta',1)&&tanking.state.tanks[0].fish.every(f=>f.id!=='betta');
    tanking.start('draft',null,'draft-test');let picks=[...tanking.state.draftChoices];tanking.pickDraft(picks[0]);tanking.step(90.1);results.draft=tanking.state.round===2&&tanking.state.draftChoices.length===3;
    function daily(){tanking.start('daily',null,'2026-09-12');tanking.step(80);return JSON.stringify({rng:tanking.state.rng,fish:tanking.state.tanks[0].fish,score:tanking.scoreBreakdown(),water:tanking.state.tanks[0].ammonia})}let a=daily(),b=daily();results.daily=a===b;
    tanking.start('daily',null,'daily-finish');tanking.step(301);results.dailyFinish=tanking.state.ended&&tanking.state.score.total>=0;
    tanking.start('showtime',null,'festival-test');tanking.step(361);results.festival=tanking.state.ended&&!!tanking.state.score;
    tanking.start('survival',null,'event-test');t=tanking.state.tanks[0];tanking.triggerEvent('power');let noBackup=t.oxygen;tanking.step(20);let lost=noBackup-t.oxygen;t.up.backup=1;tanking.triggerEvent('power');let start=t.oxygen;tanking.step(20);results.backup=lost>0&&t.oxygen>start;
    tanking.start('puzzle','diversity','diversity-test');for(let[id,n]of [['neon',6],['rasbora',6],['danio',6],['cory',3],['snail',1],['betta',1]])tanking.buyFish(id,n);tanking.selectTank(1);for(let[id,n]of [['clown',2],['chromis',5],['cardinal',2],['shrimp',1]])tanking.buyFish(id,n);tanking.step(92);results.diversity=tanking.state.won&&tanking.state.losses===0;
    tanking.start('zen',null,'horse-test');t=tanking.state.tanks[0];tanking.state.mode='survival';tanking.state.eventAt=1000;let horse=t.fish.find(f=>f.id==='seahorse');horse.hunger=70;tanking.feed();let ordinary=horse.hunger;tanking.feed(true);results.horse=ordinary>50&&horse.hunger<10;
    t.disease=30;tanking.step(10);results.cleaner=t.disease<30&&tanking.known.includes('shrimp');
    tanking.start('zen',null,'multi-test');tanking.state.money=9999;return results;
  });
  console.log('simulation',JSON.stringify(simResults));
  check('toxic rescue can be completed with no losses',simResults.rescue.won&&simResults.rescue.losses===0);
  check('ammonia becomes nitrite and nitrate',simResults.cycle.ammonia<2&&simResults.cycle.nitrite>0&&simResults.cycle.nitrate>0);
  check('grown angelfish discover and hunt tetras',simResults.angel.discovered&&simResults.angel.losses>0&&simResults.angel.warning);
  check('puffers eat snails',simResults.puffer.discovered&&simResults.puffer.snails===0);
  check('bettas damage long fins',simResults.betta.discovered&&simResults.betta.fin<100);
  check('conservation can breed and release ten young',simResults.breed.won&&simResults.breed.releases>=10);
  check('Zen prevents losses',simResults.zen);
  check('peaceful scenario excludes hostile purchases',simResults.peace);
  check('draft advances to another three-card choice',simResults.draft);
  check('Daily Reef deterministic under identical input',simResults.daily);
  check('Daily Reef and Showtime finish with score reports',simResults.dailyFinish&&simResults.festival);
  check('backup power protects oxygen during outages',simResults.backup);
  check('ten species can share two tanks with no losses',simResults.diversity);
  check('target feeding reaches outcompeted seahorses',simResults.horse);
  check('cleaner shrimp lower disease',simResults.cleaner);
  await page.locator('[data-panel="manage"]').click();await page.locator('[data-newtank="fresh"]').click();
  check('multi-tank management creates and selects a tank',await run(()=>tanking.state.tanks.length===2&&tanking.active===1));
  await run(()=>{tanking.buyFish('neon',6);tanking.selectTank(0);let f=tanking.state.tanks[1].fish[0],x=f.x;tanking.step(4);window.inactiveMoved=f.x!==x});
  check('unattended tanks keep simulating their fish',await run(()=>window.inactiveMoved));
  await page.locator('#panelClose').click();await page.locator('[data-speed="0"]').click();
  const point=await run(()=>tanking.projectFish().find(f=>f.x>350&&f.x<1100&&f.y>160&&f.y<700));
  assert.ok(point);await page.mouse.click(point.x,point.y);await page.waitForTimeout(300);
  check('clicking a fish starts cinematic following',await run(()=>tanking.follow!==null));
  await page.locator('#followClose').click();
  await page.locator('[data-panel="manage"]').click();await page.locator('#photoMode').click();
  check('photo mode hides HUD and exposes depth controls',await run(()=>tanking.photo)&&!await page.locator('#hud').isVisible());
  await page.locator('#photoFilter').selectOption('2');const downloadPromise=page.waitForEvent('download');await page.locator('#capture').click();let download=await downloadPromise;check('photo exports a PNG',download.suggestedFilename().endsWith('.png'));await page.locator('#exitPhoto').click();
  await run(()=>tanking.save());const saved=await run(()=>({mode:tanking.state.mode,fish:tanking.state.tanks.map(t=>t.fish.length),active:tanking.active}));
  await page.reload();await page.waitForFunction(()=>tanking.metrics.frames>10);await page.locator('#resume').click();
  check('local save restores tanks and selection',JSON.stringify(await run(()=>({mode:tanking.state.mode,fish:tanking.state.tanks.map(t=>t.fish.length),active:tanking.active})))===JSON.stringify(saved));
  const bounds=[];
  for(const size of [{width:320,height:568},{width:390,height:844},{width:844,height:390},{width:768,height:1024},{width:1440,height:960}]){
    await page.setViewportSize(size);await page.waitForTimeout(150);bounds.push(await run(()=>({width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,clipped:['dock','timeControl','meters'].filter(id=>{let r=document.getElementById(id).getBoundingClientRect();return r.left<0||r.right>innerWidth+1||r.top<0||r.bottom>innerHeight+1})})));
  }
  check('five responsive layouts keep primary controls in bounds',bounds.every(b=>!b.overflow&&!b.clipped.length));
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(process.env.TANKING_URL||'http://127.0.0.1:8888/gms/3d/tanking/');await mobile.waitForFunction(()=>tanking.metrics.frames>8);await mobile.locator('#begin').tap();await mobile.locator('[data-panel="stock"]').tap();await mobile.locator('[data-species="neon"]').tap();await mobile.locator('#purchase').tap();
  check('touch purchasing completes a school on a phone viewport',await mobile.evaluate(()=>tanking.state.tanks[0].fish.filter(f=>f.id==='neon').length===6));await mobile.close();
  await run(()=>tanking.start('zen',null,'visual-final'));await page.waitForTimeout(2000);await page.screenshot({path:'/private/tmp/tanking-final-zen.png'});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await page.screenshot({path:'/private/tmp/tanking-final-mobile.png'});
  check('no JavaScript, shader, or HTTP errors',errors.length===0);
  console.log(JSON.stringify({result:'PASS',checks,bounds,metrics:await run(()=>tanking.metrics)},null,2));
} catch(e){console.error('ERRORS',errors);await page.screenshot({path:'/private/tmp/tanking-failure.png'});throw e}finally{await browser.close()}
