/* levels-ext.js - Levels 51-100: the "Nightmare" expansion.
   Introduces MOVING obstacles: an obstacle may carry moveX / moveY
   (oscillation amplitude in play-area fractions), period (seconds) and
   phase (radians). game.js animates x/y = base + sin(t)*amplitude. */
'use strict';

(function () {
    // Compact obstacle builders (all coords are play-area fractions)
    const V = (x, y, h, extra) => Object.assign({ x, y, w: 0.04, h }, extra || {});
    const H = (x, y, w, extra) => Object.assign({ x, y, w, h: 0.04 }, extra || {});
    const B = (x, y, s, extra) => Object.assign({ x, y, w: s, h: s }, extra || {});

    const EXT_LEVELS = [
        // === 51-60: Moving parts ===
        {
            name: 'Sliding Door',
            description: 'The wall itself is on the move!',
            timeLimit: 50,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [{ x: 0.9, y: 0.5, type: 'food' }],
            obstacles: [
                V(0.48, 0.0, 0.45, { moveY: 0.12, period: 3.5 }),
                V(0.48, 0.55, 0.45, { moveY: 0.12, period: 3.5, phase: Math.PI }),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'Pendulum',
            description: 'Time your run past the swinging bar.',
            timeLimit: 55,
            ants: [{ x: 0.5, y: 0.9, angle: -Math.PI / 2 }],
            goals: [
                { x: 0.2, y: 0.12, type: 'food', order: 1 },
                { x: 0.8, y: 0.12, type: 'sugar', order: 2 },
            ],
            obstacles: [
                H(0.25, 0.45, 0.5, { moveX: 0.2, period: 3 }),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'The Crusher',
            description: 'The gap opens and closes. Be brave.',
            timeLimit: 55,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [{ x: 0.9, y: 0.5, type: 'nest' }],
            obstacles: [
                V(0.48, 0.0, 0.4, { moveY: 0.1, period: 2.8 }),
                V(0.48, 0.6, 0.4, { moveY: -0.1, period: 2.8 }),
            ],
            antSpeed: 2.1,
        },
        {
            name: 'Traffic',
            description: 'Three lanes of sliding walls.',
            timeLimit: 60,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [{ x: 0.92, y: 0.5, type: 'leaf' }],
            obstacles: [
                V(0.28, 0.1, 0.5, { moveY: 0.15, period: 4 }),
                V(0.5, 0.4, 0.5, { moveY: 0.15, period: 4, phase: Math.PI }),
                V(0.72, 0.1, 0.5, { moveY: 0.15, period: 4, phase: Math.PI / 2 }),
            ],
            antSpeed: 2.1,
        },
        {
            name: 'Escort Duty',
            description: 'Two ants through the drifting block.',
            timeLimit: 65,
            ants: [
                { x: 0.1, y: 0.3, angle: 0 },
                { x: 0.1, y: 0.7, angle: 0 },
            ],
            goals: [
                { x: 0.9, y: 0.3, type: 'food', order: 1 },
                { x: 0.9, y: 0.7, type: 'nest', order: 2 },
            ],
            obstacles: [
                B(0.42, 0.38, 0.16, { moveY: 0.22, period: 5 }),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'Revolving Gate',
            description: 'The treasure is behind rotating guards.',
            timeLimit: 65,
            ants: [{ x: 0.1, y: 0.1, angle: Math.PI / 4 }],
            goals: [{ x: 0.5, y: 0.5, type: 'sugar' }],
            obstacles: [
                H(0.32, 0.3, 0.36, { moveX: 0.1, period: 3.2 }),
                H(0.32, 0.66, 0.36, { moveX: -0.1, period: 3.2 }),
                V(0.28, 0.32, 0.36, { moveY: 0.1, period: 3.2, phase: Math.PI / 2 }),
                V(0.68, 0.32, 0.36, { moveY: -0.1, period: 3.2, phase: Math.PI / 2 }),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'Conveyor Chaos',
            description: 'Blocks drift across every path.',
            timeLimit: 70,
            ants: [{ x: 0.1, y: 0.9, angle: -Math.PI / 4 }],
            goals: [
                { x: 0.9, y: 0.15, type: 'food' },
                { x: 0.5, y: 0.1, type: 'leaf' },
            ],
            obstacles: [
                B(0.2, 0.3, 0.1, { moveX: 0.15, period: 4 }),
                B(0.6, 0.45, 0.1, { moveX: -0.15, period: 4 }),
                B(0.35, 0.6, 0.1, { moveX: 0.18, period: 5 }),
                B(0.55, 0.25, 0.1, { moveX: -0.12, period: 3.5 }),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'Tight Squeeze',
            description: 'A guard patrols the only gap.',
            timeLimit: 55,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [{ x: 0.9, y: 0.5, type: 'food' }],
            obstacles: [
                V(0.48, 0.0, 0.42, null),
                V(0.48, 0.58, 0.42, null),
                B(0.44, 0.44, 0.12, { moveY: 0.3, period: 3 }),
            ],
            antSpeed: 2.6,
        },
        {
            name: 'Double Doors',
            description: 'Two doors, never open together.',
            timeLimit: 65,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [{ x: 0.92, y: 0.5, type: 'nest' }],
            obstacles: [
                V(0.33, 0.0, 0.55, { moveY: 0.25, period: 4 }),
                V(0.33, 0.75, 0.25, null),
                V(0.63, 0.45, 0.55, { moveY: -0.25, period: 4 }),
                V(0.63, 0.0, 0.25, null),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'Night Shift',
            description: 'Four workers, moving pillars.',
            timeLimit: 80,
            ants: [
                { x: 0.1, y: 0.15, angle: 0 },
                { x: 0.1, y: 0.4, angle: 0 },
                { x: 0.1, y: 0.6, angle: 0 },
                { x: 0.1, y: 0.85, angle: 0 },
            ],
            goals: [
                { x: 0.9, y: 0.2, type: 'food' },
                { x: 0.9, y: 0.5, type: 'sugar' },
                { x: 0.9, y: 0.8, type: 'leaf' },
            ],
            obstacles: [
                B(0.35, 0.2, 0.08, { moveY: 0.15, period: 3.5 }),
                B(0.55, 0.5, 0.08, { moveY: 0.18, period: 4.2, phase: Math.PI }),
                B(0.35, 0.7, 0.08, { moveY: 0.15, period: 3.8, phase: Math.PI / 2 }),
                B(0.7, 0.35, 0.08, { moveX: 0.12, period: 4 }),
            ],
            antSpeed: 2.1,
        },

        // === 61-70: Mazes in motion ===
        {
            name: 'Spiral Down',
            description: 'Wind your way to the centre.',
            timeLimit: 75,
            ants: [{ x: 0.08, y: 0.08, angle: 0 }],
            goals: [
                { x: 0.5, y: 0.55, type: 'sugar', order: 1 },
                { x: 0.9, y: 0.9, type: 'nest', order: 2 },
            ],
            obstacles: [
                H(0.15, 0.2, 0.7, null),
                V(0.81, 0.2, 0.55, null),
                H(0.3, 0.75, 0.55, null),
                V(0.3, 0.35, 0.4, null),
                H(0.3, 0.35, 0.35, null),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'Switchback',
            description: 'A fast ant in a dense zigzag.',
            timeLimit: 60,
            ants: [{ x: 0.08, y: 0.08, angle: Math.PI / 4 }],
            goals: [{ x: 0.92, y: 0.92, type: 'food' }],
            obstacles: [
                H(0.0, 0.22, 0.8, null),
                H(0.2, 0.42, 0.8, null),
                H(0.0, 0.62, 0.8, null),
                H(0.2, 0.82, 0.8, null),
            ],
            antSpeed: 2.8,
        },
        {
            name: 'The Sweeper',
            description: 'A wall patrols the whole page.',
            timeLimit: 60,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.9, y: 0.2, type: 'food' },
                { x: 0.9, y: 0.8, type: 'leaf' },
            ],
            obstacles: [
                V(0.45, 0.15, 0.7, { moveX: 0.3, period: 6 }),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'Ant Jam',
            description: 'Six ants push through the pillars.',
            timeLimit: 85,
            ants: [
                { x: 0.1, y: 0.15, angle: 0 },
                { x: 0.1, y: 0.35, angle: 0 },
                { x: 0.1, y: 0.55, angle: 0 },
                { x: 0.1, y: 0.75, angle: 0 },
                { x: 0.25, y: 0.9, angle: -Math.PI / 4 },
                { x: 0.4, y: 0.1, angle: Math.PI / 4 },
            ],
            goals: [
                { x: 0.88, y: 0.15, type: 'food' },
                { x: 0.88, y: 0.4, type: 'sugar' },
                { x: 0.88, y: 0.65, type: 'leaf' },
                { x: 0.88, y: 0.9, type: 'friend' },
            ],
            obstacles: [
                B(0.35, 0.25, 0.07, null),
                B(0.55, 0.25, 0.07, null),
                B(0.45, 0.45, 0.07, null),
                B(0.35, 0.65, 0.07, null),
                B(0.55, 0.65, 0.07, null),
                B(0.65, 0.45, 0.07, null),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'Corridor Rush',
            description: 'The gauntlet grew moving guards.',
            timeLimit: 70,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [{ x: 0.92, y: 0.5, type: 'food' }],
            obstacles: [
                V(0.25, 0.0, 0.38, null),
                V(0.25, 0.62, 0.38, null),
                B(0.21, 0.42, 0.11, { moveY: 0.12, period: 2.8 }),
                V(0.55, 0.0, 0.38, null),
                V(0.55, 0.62, 0.38, null),
                B(0.51, 0.42, 0.11, { moveY: 0.12, period: 2.8, phase: Math.PI }),
                V(0.8, 0.3, 0.4, { moveY: 0.15, period: 4 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Four Rooms',
            description: 'Visit every room, in order.',
            timeLimit: 90,
            ants: [{ x: 0.5, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.15, y: 0.15, type: 'food', order: 1 },
                { x: 0.85, y: 0.15, type: 'sugar', order: 2 },
                { x: 0.85, y: 0.85, type: 'leaf', order: 3 },
                { x: 0.15, y: 0.85, type: 'nest', order: 4 },
            ],
            obstacles: [
                V(0.48, 0.0, 0.32, null),
                V(0.48, 0.68, 0.32, null),
                H(0.0, 0.48, 0.32, null),
                H(0.68, 0.48, 0.32, null),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Metronome',
            description: 'Tick... tock... dash!',
            timeLimit: 65,
            ants: [{ x: 0.5, y: 0.9, angle: -Math.PI / 2 }],
            goals: [
                { x: 0.15, y: 0.12, type: 'sugar' },
                { x: 0.85, y: 0.12, type: 'food' },
            ],
            obstacles: [
                V(0.48, 0.05, 0.45, { moveX: 0.25, period: 3 }),
                H(0.2, 0.6, 0.24, null),
                H(0.56, 0.6, 0.24, null),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Swarm',
            description: 'Eight ants. Stay calm.',
            timeLimit: 90,
            ants: [
                { x: 0.1, y: 0.1, angle: Math.PI / 4 },
                { x: 0.1, y: 0.35, angle: 0 },
                { x: 0.1, y: 0.65, angle: 0 },
                { x: 0.1, y: 0.9, angle: -Math.PI / 4 },
                { x: 0.3, y: 0.1, angle: Math.PI / 3 },
                { x: 0.3, y: 0.9, angle: -Math.PI / 3 },
                { x: 0.5, y: 0.1, angle: Math.PI / 2 },
                { x: 0.5, y: 0.9, angle: -Math.PI / 2 },
            ],
            goals: [
                { x: 0.85, y: 0.2, type: 'food' },
                { x: 0.85, y: 0.5, type: 'sugar' },
                { x: 0.85, y: 0.8, type: 'leaf' },
            ],
            obstacles: [
                V(0.6, 0.3, 0.4, { moveY: 0.15, period: 4.5 }),
            ],
            antSpeed: 2.0,
        },
        {
            name: 'Thread the Sweep',
            description: 'Falling through moving floors.',
            timeLimit: 70,
            ants: [{ x: 0.5, y: 0.08, angle: Math.PI / 2 }],
            goals: [{ x: 0.5, y: 0.92, type: 'nest' }],
            obstacles: [
                H(0.0, 0.28, 0.44, { moveX: 0.1, period: 3.6 }),
                H(0.56, 0.28, 0.44, { moveX: -0.1, period: 3.6 }),
                H(0.0, 0.52, 0.44, { moveX: -0.12, period: 4.2 }),
                H(0.56, 0.52, 0.44, { moveX: 0.12, period: 4.2 }),
                H(0.0, 0.76, 0.44, { moveX: 0.1, period: 3.2 }),
                H(0.56, 0.76, 0.44, { moveX: -0.1, period: 3.2 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Gatekeeper',
            description: 'One gate circles the prize.',
            timeLimit: 75,
            ants: [{ x: 0.1, y: 0.9, angle: -Math.PI / 4 }],
            goals: [
                { x: 0.5, y: 0.5, type: 'sugar', order: 1 },
                { x: 0.9, y: 0.1, type: 'nest', order: 2 },
            ],
            obstacles: [
                H(0.3, 0.28, 0.4, { moveX: 0.15, period: 4 }),
                H(0.3, 0.68, 0.4, { moveX: -0.15, period: 4 }),
                V(0.26, 0.32, 0.36, null),
                V(0.7, 0.32, 0.36, { moveY: 0.1, period: 3 }),
            ],
            antSpeed: 2.2,
        },

        // === 71-80: Speed and precision ===
        {
            name: 'Hyper Ant',
            description: 'It. Will. Not. Slow. Down.',
            timeLimit: 40,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.9, y: 0.2, type: 'sugar' },
                { x: 0.9, y: 0.8, type: 'food' },
            ],
            obstacles: [
                B(0.45, 0.42, 0.16, null),
            ],
            antSpeed: 3.4,
        },
        {
            name: 'Twin Sweepers',
            description: 'Two walls sweep in opposite beats.',
            timeLimit: 70,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.9, y: 0.15, type: 'food', order: 1 },
                { x: 0.9, y: 0.85, type: 'nest', order: 2 },
            ],
            obstacles: [
                V(0.35, 0.1, 0.8, { moveX: 0.12, period: 5 }),
                V(0.65, 0.1, 0.8, { moveX: -0.12, period: 5 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Grid Lock',
            description: 'Sixteen pillars, two ordered stops.',
            timeLimit: 80,
            ants: [{ x: 0.08, y: 0.92, angle: -Math.PI / 4 }],
            goals: [
                { x: 0.92, y: 0.08, type: 'food', order: 1 },
                { x: 0.08, y: 0.08, type: 'nest', order: 2 },
            ],
            obstacles: [
                B(0.18, 0.18, 0.06, null), B(0.38, 0.18, 0.06, null), B(0.58, 0.18, 0.06, null), B(0.78, 0.18, 0.06, null),
                B(0.18, 0.38, 0.06, null), B(0.38, 0.38, 0.06, null), B(0.58, 0.38, 0.06, null), B(0.78, 0.38, 0.06, null),
                B(0.18, 0.58, 0.06, null), B(0.38, 0.58, 0.06, null), B(0.58, 0.58, 0.06, null), B(0.78, 0.58, 0.06, null),
                B(0.18, 0.78, 0.06, null), B(0.38, 0.78, 0.06, null), B(0.58, 0.78, 0.06, null), B(0.78, 0.78, 0.06, null),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Relay Race',
            description: 'Three runners, five checkpoints.',
            timeLimit: 100,
            ants: [
                { x: 0.1, y: 0.2, angle: 0 },
                { x: 0.1, y: 0.5, angle: 0 },
                { x: 0.1, y: 0.8, angle: 0 },
            ],
            goals: [
                { x: 0.3, y: 0.15, type: 'food', order: 1 },
                { x: 0.55, y: 0.85, type: 'sugar', order: 2 },
                { x: 0.75, y: 0.15, type: 'leaf', order: 3 },
                { x: 0.9, y: 0.5, type: 'friend', order: 4 },
                { x: 0.54, y: 0.5, type: 'nest', order: 5 },
            ],
            obstacles: [
                V(0.42, 0.3, 0.4, { moveY: 0.12, period: 4 }),
                V(0.66, 0.3, 0.4, { moveY: -0.12, period: 4 }),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'The Blender',
            description: 'Four blocks churn the middle.',
            timeLimit: 65,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [{ x: 0.9, y: 0.5, type: 'sugar' }],
            obstacles: [
                B(0.35, 0.3, 0.1, { moveX: 0.12, period: 2.6 }),
                B(0.55, 0.3, 0.1, { moveY: 0.12, period: 2.6, phase: Math.PI / 2 }),
                B(0.35, 0.6, 0.1, { moveY: -0.12, period: 2.6, phase: Math.PI }),
                B(0.55, 0.6, 0.1, { moveX: -0.12, period: 2.6, phase: -Math.PI / 2 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Speedway',
            description: 'Full throttle through the chicane.',
            timeLimit: 50,
            ants: [{ x: 0.08, y: 0.92, angle: 0 }],
            goals: [{ x: 0.92, y: 0.15, type: 'food' }],
            obstacles: [
                H(0.0, 0.3, 0.7, null),
                H(0.3, 0.55, 0.7, null),
                H(0.0, 0.8, 0.55, null),
            ],
            antSpeed: 3.0,
        },
        {
            name: 'Order Six',
            description: 'Six stops. No mistakes.',
            timeLimit: 110,
            ants: [{ x: 0.5, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.12, y: 0.12, type: 'food', order: 1 },
                { x: 0.88, y: 0.88, type: 'sugar', order: 2 },
                { x: 0.88, y: 0.12, type: 'leaf', order: 3 },
                { x: 0.12, y: 0.88, type: 'friend', order: 4 },
                { x: 0.5, y: 0.12, type: 'food', order: 5 },
                { x: 0.5, y: 0.88, type: 'nest', order: 6 },
            ],
            obstacles: [
                B(0.44, 0.3, 0.12, { moveX: 0.15, period: 4 }),
                B(0.44, 0.58, 0.12, { moveX: -0.15, period: 4 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Piston Hall',
            description: 'Pistons pound from both sides.',
            timeLimit: 70,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [{ x: 0.92, y: 0.5, type: 'nest' }],
            obstacles: [
                V(0.22, 0.0, 0.45, { moveY: 0.18, period: 2.4 }),
                V(0.42, 0.55, 0.45, { moveY: -0.18, period: 2.4, phase: Math.PI / 2 }),
                V(0.62, 0.0, 0.45, { moveY: 0.18, period: 2.4, phase: Math.PI }),
                V(0.82, 0.55, 0.45, { moveY: -0.18, period: 2.4, phase: -Math.PI / 2 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Six Pack',
            description: 'Six ants, six treats, one page.',
            timeLimit: 100,
            ants: [
                { x: 0.1, y: 0.15, angle: 0 },
                { x: 0.1, y: 0.5, angle: 0 },
                { x: 0.1, y: 0.85, angle: 0 },
                { x: 0.9, y: 0.15, angle: Math.PI },
                { x: 0.9, y: 0.5, angle: Math.PI },
                { x: 0.9, y: 0.85, angle: Math.PI },
            ],
            goals: [
                { x: 0.5, y: 0.1, type: 'food' },
                { x: 0.3, y: 0.35, type: 'sugar' },
                { x: 0.7, y: 0.35, type: 'leaf' },
                { x: 0.3, y: 0.65, type: 'friend' },
                { x: 0.7, y: 0.65, type: 'food' },
                { x: 0.5, y: 0.9, type: 'nest' },
            ],
            obstacles: [
                B(0.46, 0.44, 0.08, { moveY: 0.2, period: 5 }),
            ],
            antSpeed: 2.1,
        },
        {
            name: 'Checkpoint Charlie',
            description: 'Papers, please. In order.',
            timeLimit: 85,
            ants: [{ x: 0.08, y: 0.9, angle: -Math.PI / 6 }],
            goals: [
                { x: 0.3, y: 0.15, type: 'food', order: 1 },
                { x: 0.7, y: 0.85, type: 'sugar', order: 2 },
                { x: 0.92, y: 0.15, type: 'nest', order: 3 },
            ],
            obstacles: [
                V(0.48, 0.0, 0.4, { moveY: 0.2, period: 3.4 }),
                V(0.48, 0.6, 0.4, { moveY: -0.2, period: 3.4 }),
                H(0.15, 0.45, 0.2, null),
                H(0.65, 0.45, 0.2, null),
            ],
            antSpeed: 2.6,
        },

        // === 81-90: Chaos engineering ===
        {
            name: 'Minefield',
            description: 'Blocks everywhere. Two ants. Go.',
            timeLimit: 75,
            ants: [
                { x: 0.08, y: 0.3, angle: 0 },
                { x: 0.08, y: 0.7, angle: 0 },
            ],
            goals: [
                { x: 0.92, y: 0.3, type: 'food' },
                { x: 0.92, y: 0.7, type: 'sugar' },
            ],
            obstacles: [
                B(0.2, 0.15, 0.07, null), B(0.35, 0.45, 0.07, null), B(0.25, 0.75, 0.07, null),
                B(0.5, 0.2, 0.07, null), B(0.5, 0.75, 0.07, null), B(0.62, 0.45, 0.07, null),
                B(0.75, 0.15, 0.07, null), B(0.78, 0.6, 0.07, null), B(0.4, 0.6, 0.07, null),
                B(0.65, 0.8, 0.07, null),
            ],
            antSpeed: 2.5,
        },
        {
            name: 'The Long March',
            description: 'Around the world, dodging the sweep.',
            timeLimit: 95,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.9, y: 0.5, type: 'food', order: 1 },
                { x: 0.1, y: 0.15, type: 'leaf', order: 2 },
                { x: 0.9, y: 0.85, type: 'nest', order: 3 },
            ],
            obstacles: [
                B(0.3, 0.28, 0.4, null),
                H(0.3, 0.75, 0.4, { moveX: 0.15, period: 5 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Flood Gates',
            description: 'Three gates, three swimmers.',
            timeLimit: 90,
            ants: [
                { x: 0.08, y: 0.2, angle: 0 },
                { x: 0.08, y: 0.5, angle: 0 },
                { x: 0.08, y: 0.8, angle: 0 },
            ],
            goals: [
                { x: 0.92, y: 0.2, type: 'food' },
                { x: 0.92, y: 0.5, type: 'sugar' },
                { x: 0.92, y: 0.8, type: 'leaf' },
            ],
            obstacles: [
                H(0.2, 0.33, 0.6, null),
                H(0.2, 0.63, 0.6, null),
                V(0.45, 0.0, 0.33, { moveY: 0.1, period: 3 }),
                V(0.45, 0.37, 0.26, { moveY: 0.08, period: 3, phase: Math.PI }),
                V(0.45, 0.67, 0.33, { moveY: -0.1, period: 3 }),
            ],
            antSpeed: 2.2,
        },
        {
            name: 'Pinwheel',
            description: 'The middle churns like a wheel.',
            timeLimit: 70,
            ants: [{ x: 0.1, y: 0.1, angle: Math.PI / 4 }],
            goals: [
                { x: 0.9, y: 0.9, type: 'nest', order: 2 },
                { x: 0.9, y: 0.1, type: 'sugar', order: 1 },
            ],
            obstacles: [
                H(0.3, 0.48, 0.18, { moveX: 0.12, period: 2.5 }),
                H(0.52, 0.48, 0.18, { moveX: -0.12, period: 2.5 }),
                V(0.48, 0.28, 0.18, { moveY: 0.12, period: 2.5, phase: Math.PI / 2 }),
                V(0.48, 0.54, 0.18, { moveY: -0.12, period: 2.5, phase: Math.PI / 2 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Rush Hour',
            description: 'Seven ants against the traffic.',
            timeLimit: 100,
            ants: [
                { x: 0.08, y: 0.12, angle: 0 },
                { x: 0.08, y: 0.31, angle: 0 },
                { x: 0.08, y: 0.5, angle: 0 },
                { x: 0.08, y: 0.69, angle: 0 },
                { x: 0.08, y: 0.88, angle: 0 },
                { x: 0.25, y: 0.1, angle: Math.PI / 3 },
                { x: 0.25, y: 0.9, angle: -Math.PI / 3 },
            ],
            goals: [
                { x: 0.9, y: 0.15, type: 'food' },
                { x: 0.9, y: 0.38, type: 'sugar' },
                { x: 0.9, y: 0.62, type: 'leaf' },
                { x: 0.9, y: 0.85, type: 'friend' },
            ],
            obstacles: [
                V(0.4, 0.1, 0.35, { moveY: 0.12, period: 3.6 }),
                V(0.4, 0.55, 0.35, { moveY: -0.12, period: 3.6 }),
                V(0.65, 0.3, 0.4, { moveY: 0.18, period: 4.4 }),
            ],
            antSpeed: 2.2,
        },
        {
            name: "Needle's Eye",
            description: 'A tiny gap with a bouncing guard.',
            timeLimit: 65,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [{ x: 0.9, y: 0.5, type: 'food' }],
            obstacles: [
                V(0.48, 0.0, 0.46, null),
                V(0.48, 0.54, 0.46, null),
                B(0.42, 0.2, 0.09, { moveY: 0.55, period: 3.6 }),
            ],
            antSpeed: 2.8,
        },
        {
            name: 'Countdown',
            description: '20 seconds. One shot.',
            timeLimit: 20,
            ants: [{ x: 0.1, y: 0.85, angle: -Math.PI / 6 }],
            goals: [{ x: 0.9, y: 0.15, type: 'sugar' }],
            obstacles: [
                B(0.42, 0.4, 0.16, { moveX: 0.1, period: 3 }),
            ],
            antSpeed: 3.0,
        },
        {
            name: 'The Escort',
            description: 'Five stops through moving hazards.',
            timeLimit: 120,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.35, y: 0.12, type: 'food', order: 1 },
                { x: 0.65, y: 0.88, type: 'sugar', order: 2 },
                { x: 0.9, y: 0.12, type: 'leaf', order: 3 },
                { x: 0.35, y: 0.88, type: 'friend', order: 4 },
                { x: 0.9, y: 0.6, type: 'nest', order: 5 },
            ],
            obstacles: [
                V(0.5, 0.25, 0.5, { moveY: 0.15, period: 4 }),
                B(0.26, 0.42, 0.1, { moveX: 0.1, period: 3.2 }),
                B(0.72, 0.35, 0.1, { moveY: 0.12, period: 3.8 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Maze Runner Pro',
            description: 'The Grand Maze, but faster.',
            timeLimit: 80,
            ants: [{ x: 0.08, y: 0.08, angle: Math.PI / 4 }],
            goals: [{ x: 0.92, y: 0.92, type: 'nest' }],
            obstacles: [
                V(0.2, 0.0, 0.5, null),
                V(0.2, 0.65, 0.35, null),
                V(0.35, 0.2, 0.65, null),
                V(0.5, 0.0, 0.35, null),
                V(0.5, 0.5, 0.5, { moveY: 0.06, period: 3 }),
                V(0.65, 0.15, 0.5, null),
                V(0.65, 0.8, 0.2, null),
                V(0.8, 0.0, 0.35, null),
                V(0.8, 0.5, 0.5, { moveY: -0.06, period: 3 }),
            ],
            antSpeed: 2.5,
        },
        {
            name: 'Anthill Assault',
            description: 'Eight ants storm the hill.',
            timeLimit: 110,
            ants: [
                { x: 0.08, y: 0.1, angle: Math.PI / 4 },
                { x: 0.08, y: 0.3, angle: 0 },
                { x: 0.08, y: 0.5, angle: 0 },
                { x: 0.08, y: 0.7, angle: 0 },
                { x: 0.08, y: 0.9, angle: -Math.PI / 4 },
                { x: 0.28, y: 0.1, angle: Math.PI / 3 },
                { x: 0.28, y: 0.9, angle: -Math.PI / 3 },
                { x: 0.48, y: 0.1, angle: Math.PI / 2 },
            ],
            goals: [
                { x: 0.85, y: 0.12, type: 'food' },
                { x: 0.92, y: 0.35, type: 'sugar' },
                { x: 0.92, y: 0.65, type: 'leaf' },
                { x: 0.85, y: 0.88, type: 'friend' },
                { x: 0.8, y: 0.5, type: 'nest' },
            ],
            obstacles: [
                B(0.4, 0.3, 0.08, null),
                B(0.4, 0.62, 0.08, null),
                V(0.55, 0.25, 0.5, { moveX: 0.12, period: 5 }),
            ],
            antSpeed: 2.2,
        },

        // === 91-100: The final exam ===
        {
            name: 'Gauntlet II',
            description: 'The gauntlet learned new tricks.',
            timeLimit: 80,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [{ x: 0.92, y: 0.5, type: 'food' }],
            obstacles: [
                V(0.2, 0.0, 0.4, { moveY: 0.1, period: 2.6 }),
                V(0.2, 0.6, 0.4, { moveY: -0.1, period: 2.6 }),
                V(0.35, 0.3, 0.4, { moveY: 0.14, period: 3.2 }),
                V(0.5, 0.0, 0.4, { moveY: 0.1, period: 2.6, phase: Math.PI }),
                V(0.5, 0.6, 0.4, { moveY: -0.1, period: 2.6, phase: Math.PI }),
                V(0.65, 0.3, 0.4, { moveY: -0.14, period: 3.2 }),
                V(0.8, 0.0, 0.4, { moveY: 0.1, period: 2.6, phase: Math.PI / 2 }),
                V(0.8, 0.6, 0.4, { moveY: -0.1, period: 2.6, phase: Math.PI / 2 }),
            ],
            antSpeed: 2.6,
        },
        {
            name: 'Seven Seals',
            description: 'Seven goals bound in strict order.',
            timeLimit: 140,
            ants: [{ x: 0.5, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.12, y: 0.12, type: 'food', order: 1 },
                { x: 0.88, y: 0.12, type: 'sugar', order: 2 },
                { x: 0.88, y: 0.88, type: 'leaf', order: 3 },
                { x: 0.12, y: 0.88, type: 'friend', order: 4 },
                { x: 0.5, y: 0.12, type: 'food', order: 5 },
                { x: 0.5, y: 0.88, type: 'sugar', order: 6 },
                { x: 0.12, y: 0.5, type: 'nest', order: 7 },
            ],
            obstacles: [
                B(0.3, 0.3, 0.08, { moveX: 0.08, period: 3 }),
                B(0.62, 0.3, 0.08, { moveY: 0.08, period: 3.4 }),
                B(0.3, 0.62, 0.08, { moveY: -0.08, period: 3.8 }),
                B(0.62, 0.62, 0.08, { moveX: -0.08, period: 4.2 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'The Vice',
            description: 'Crushed from every direction.',
            timeLimit: 75,
            ants: [{ x: 0.1, y: 0.1, angle: Math.PI / 4 }],
            goals: [
                { x: 0.5, y: 0.5, type: 'sugar', order: 1 },
                { x: 0.9, y: 0.9, type: 'nest', order: 2 },
            ],
            obstacles: [
                V(0.3, 0.2, 0.6, { moveX: 0.1, period: 3 }),
                V(0.66, 0.2, 0.6, { moveX: -0.1, period: 3 }),
                H(0.2, 0.3, 0.6, { moveY: 0.1, period: 3, phase: Math.PI / 2 }),
                H(0.2, 0.66, 0.6, { moveY: -0.1, period: 3, phase: Math.PI / 2 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Scatterstorm',
            description: 'Six ants in a moving minefield.',
            timeLimit: 110,
            ants: [
                { x: 0.08, y: 0.2, angle: 0 },
                { x: 0.08, y: 0.5, angle: 0 },
                { x: 0.08, y: 0.8, angle: 0 },
                { x: 0.92, y: 0.2, angle: Math.PI },
                { x: 0.92, y: 0.5, angle: Math.PI },
                { x: 0.92, y: 0.8, angle: Math.PI },
            ],
            goals: [
                { x: 0.5, y: 0.1, type: 'food' },
                { x: 0.25, y: 0.5, type: 'sugar' },
                { x: 0.75, y: 0.5, type: 'leaf' },
                { x: 0.5, y: 0.35, type: 'friend' },
                { x: 0.5, y: 0.65, type: 'food' },
                { x: 0.5, y: 0.9, type: 'nest' },
            ],
            obstacles: [
                B(0.35, 0.22, 0.07, { moveX: 0.1, period: 3 }),
                B(0.58, 0.22, 0.07, { moveX: -0.1, period: 3.4 }),
                B(0.35, 0.72, 0.07, { moveX: 0.1, period: 3.8 }),
                B(0.58, 0.72, 0.07, { moveX: -0.1, period: 4.2 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Precision Master',
            description: 'Three tiny gaps, three guards.',
            timeLimit: 80,
            ants: [{ x: 0.5, y: 0.06, angle: Math.PI / 2 }],
            goals: [{ x: 0.5, y: 0.94, type: 'nest' }],
            obstacles: [
                H(0.0, 0.26, 0.46, null),
                H(0.54, 0.26, 0.46, null),
                B(0.45, 0.16, 0.08, { moveX: 0.12, period: 2.8 }),
                H(0.0, 0.5, 0.46, null),
                H(0.54, 0.5, 0.46, null),
                B(0.45, 0.4, 0.08, { moveX: -0.12, period: 3.2 }),
                H(0.0, 0.74, 0.46, null),
                H(0.54, 0.74, 0.46, null),
                B(0.45, 0.64, 0.08, { moveX: 0.12, period: 3.6 }),
            ],
            antSpeed: 2.5,
        },
        {
            name: 'The Hive',
            description: 'Dense pillars, four ordered stops.',
            timeLimit: 120,
            ants: [{ x: 0.08, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.92, y: 0.12, type: 'food', order: 1 },
                { x: 0.12, y: 0.12, type: 'sugar', order: 2 },
                { x: 0.92, y: 0.88, type: 'leaf', order: 3 },
                { x: 0.12, y: 0.88, type: 'nest', order: 4 },
            ],
            obstacles: [
                B(0.24, 0.24, 0.06, null), B(0.44, 0.24, 0.06, null), B(0.64, 0.24, 0.06, null),
                B(0.34, 0.44, 0.06, null), B(0.54, 0.44, 0.06, null), B(0.74, 0.44, 0.06, null),
                B(0.24, 0.64, 0.06, null), B(0.44, 0.64, 0.06, null), B(0.64, 0.64, 0.06, null),
                B(0.14, 0.44, 0.06, { moveY: 0.1, period: 3 }),
                B(0.84, 0.64, 0.06, { moveY: -0.1, period: 3.5 }),
            ],
            antSpeed: 2.3,
        },
        {
            name: 'Lightning Round',
            description: '25 seconds, two treats, warp speed.',
            timeLimit: 25,
            ants: [{ x: 0.1, y: 0.5, angle: 0 }],
            goals: [
                { x: 0.9, y: 0.2, type: 'sugar' },
                { x: 0.9, y: 0.8, type: 'food' },
            ],
            obstacles: [
                V(0.5, 0.3, 0.4, null),
            ],
            antSpeed: 3.5,
        },
        {
            name: 'Grand Sweep',
            description: 'Two giant sweepers rake the maze.',
            timeLimit: 100,
            ants: [{ x: 0.08, y: 0.08, angle: Math.PI / 4 }],
            goals: [
                { x: 0.92, y: 0.92, type: 'nest', order: 2 },
                { x: 0.92, y: 0.08, type: 'food', order: 1 },
            ],
            obstacles: [
                V(0.3, 0.1, 0.8, { moveX: 0.12, period: 6 }),
                V(0.7, 0.1, 0.8, { moveX: -0.12, period: 6 }),
                H(0.35, 0.48, 0.3, null),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'The Impossible',
            description: 'They said it couldn\'t be done.',
            timeLimit: 150,
            ants: [
                { x: 0.08, y: 0.1, angle: Math.PI / 4 },
                { x: 0.08, y: 0.3, angle: 0 },
                { x: 0.08, y: 0.5, angle: 0 },
                { x: 0.08, y: 0.7, angle: 0 },
                { x: 0.08, y: 0.9, angle: -Math.PI / 4 },
                { x: 0.92, y: 0.3, angle: Math.PI },
                { x: 0.92, y: 0.7, angle: Math.PI },
                { x: 0.5, y: 0.92, angle: -Math.PI / 2 },
            ],
            goals: [
                { x: 0.3, y: 0.12, type: 'food', order: 1 },
                { x: 0.7, y: 0.12, type: 'sugar', order: 2 },
                { x: 0.3, y: 0.55, type: 'leaf', order: 3 },
                { x: 0.7, y: 0.55, type: 'friend', order: 4 },
                { x: 0.5, y: 0.3, type: 'food', order: 5 },
                { x: 0.5, y: 0.78, type: 'nest', order: 6 },
            ],
            obstacles: [
                V(0.4, 0.2, 0.25, { moveY: 0.1, period: 3.2 }),
                V(0.56, 0.2, 0.25, { moveY: -0.1, period: 3.2 }),
                H(0.3, 0.66, 0.4, { moveX: 0.12, period: 4.4 }),
                B(0.2, 0.4, 0.08, { moveX: 0.08, period: 2.8 }),
                B(0.72, 0.4, 0.08, { moveX: -0.08, period: 2.8 }),
            ],
            antSpeed: 2.4,
        },
        {
            name: 'Paper Apocalypse',
            description: 'The last page. Everything at once.',
            timeLimit: 180,
            ants: [
                { x: 0.08, y: 0.15, angle: 0 },
                { x: 0.08, y: 0.4, angle: 0 },
                { x: 0.08, y: 0.6, angle: 0 },
                { x: 0.08, y: 0.85, angle: 0 },
                { x: 0.5, y: 0.08, angle: Math.PI / 2 },
            ],
            goals: [
                { x: 0.3, y: 0.12, type: 'food', order: 1 },
                { x: 0.78, y: 0.88, type: 'sugar', order: 2 },
                { x: 0.78, y: 0.12, type: 'leaf', order: 3 },
                { x: 0.3, y: 0.88, type: 'friend', order: 4 },
                { x: 0.56, y: 0.5, type: 'food', order: 5 },
                { x: 0.92, y: 0.35, type: 'sugar', order: 6 },
                { x: 0.92, y: 0.65, type: 'nest', order: 7 },
            ],
            obstacles: [
                V(0.2, 0.0, 0.35, { moveY: 0.08, period: 3 }),
                V(0.2, 0.65, 0.35, { moveY: -0.08, period: 3 }),
                V(0.44, 0.22, 0.25, { moveY: 0.1, period: 3.6 }),
                V(0.44, 0.53, 0.25, { moveY: -0.1, period: 3.6 }),
                V(0.68, 0.0, 0.35, { moveY: 0.08, period: 3, phase: Math.PI }),
                V(0.68, 0.65, 0.35, { moveY: -0.08, period: 3, phase: Math.PI }),
                H(0.28, 0.3, 0.15, { moveX: 0.08, period: 4 }),
                H(0.5, 0.66, 0.15, { moveX: -0.08, period: 4 }),
                V(0.8, 0.42, 0.16, { moveY: 0.12, period: 2.6 }),
            ],
            antSpeed: 2.5,
        },
    ];

    // Append with sequential ids following the base 50
    let nextId = LEVELS.length + 1;
    for (const lvl of EXT_LEVELS) {
        lvl.id = nextId++;
        LEVELS.push(lvl);
    }
})();
