// Actors: Wikipedia title | display | expected birth year | nationality | difficulty | famous films (Wikipedia titles; cast checked on Wikidata) | clues hardest->easiest | alt
export const ACTORS = `
Tom Hanks|Tom Hanks|1956|American|1|Forrest Gump;Cast Away;Toy Story|He won back-to-back Best Actor Oscars in 1994 and 1995;He was stranded on an island with a volleyball called Wilson;He played a man who says life is like a box of chocolates;He is the voice of Woody in Toy Story|Hanks
Meryl Streep|Meryl Streep|1949|American|2|The Devil Wears Prada (film);Mamma Mia! (film);Sophie's Choice (film)|She has more Oscar nominations than any other actor;She played Margaret Thatcher in The Iron Lady;She played a terrifying fashion editor;She sang ABBA songs in Mamma Mia!|Streep
Leonardo DiCaprio|Leonardo DiCaprio|1974|American|1|Titanic (1997 film);Inception;The Revenant (2015 film)|He finally won an Oscar for The Revenant;He played a thief who enters people's dreams in Inception;He starred in The Wolf of Wall Street;He played Jack in Titanic|DiCaprio;Leo DiCaprio
Denzel Washington|Denzel Washington|1954|American|2|Training Day;Glory (1989 film);Malcolm X (1992 film)|He won a supporting actor Oscar for Glory;He played the civil rights leader Malcolm X;He won Best Actor for playing a corrupt detective;He starred in Training Day and The Equalizer|Washington
Morgan Freeman|Morgan Freeman|1937|American|2|The Shawshank Redemption;Million Dollar Baby;Driving Miss Daisy (film)|He won an Oscar for Million Dollar Baby;He played Nelson Mandela in Invictus;He played God in Bruce Almighty;He is famous for his deep narrating voice and played Red in The Shawshank Redemption|Freeman
Julia Roberts|Julia Roberts|1967|American|2|Pretty Woman;Erin Brockovich (film);Notting Hill (film)|She won an Oscar for playing a legal clerk who took on a power company;She played a famous film star in Notting Hill;She starred opposite Richard Gere;She shot to fame in Pretty Woman|Roberts
Will Smith|Will Smith|1968|American|1|Men in Black (1997 film);Independence Day (1996 film);Aladdin (2019 film)|He won an Oscar for playing Venus and Serena Williams's father;He played the Genie in the 2019 Aladdin;He fought aliens in Independence Day;He starred in The Fresh Prince of Bel-Air and Men in Black|Smith
Tom Cruise|Tom Cruise|1962|American|1|Top Gun;Mission: Impossible (film);Top Gun: Maverick|He hung off the side of a flying plane for a stunt;He played a bartender in Cocktail;He plays agent Ethan Hunt;He played Maverick in Top Gun|Cruise
Brad Pitt|Brad Pitt|1963|American|2|Fight Club;Ocean's Eleven;Once Upon a Time in Hollywood|He won an Oscar for playing a stuntman;He played Achilles in Troy;He played Tyler Durden in Fight Club;He starred in Ocean's Eleven with George Clooney|Pitt
Angelina Jolie|Angelina Jolie|1975|American|2|Maleficent (film);Lara Croft: Tomb Raider;Mr. & Mrs. Smith (2005 film)|She won an Oscar for Girl, Interrupted;She has been a special envoy for the UN refugee agency;She played a video-game tomb raider;She played the wicked fairy Maleficent|Jolie
Johnny Depp|Johnny Depp|1963|American|2|Pirates of the Caribbean: The Curse of the Black Pearl;Edward Scissorhands;Charlie and the Chocolate Factory (film)|He first became famous in the TV series 21 Jump Street;He played a man with scissors for hands;He played Willy Wonka in 2005;He played Captain Jack Sparrow|Depp
Scarlett Johansson|Scarlett Johansson|1984|American|2|Lost in Translation (film);The Avengers (2012 film);Lucy (2014 film)|She voiced the computer Samantha in Her;She starred in Lost in Translation with Bill Murray;She starred in Lucy as a woman who unlocks her brain;She played Black Widow in the Marvel films|Johansson
Robert Downey Jr.|Robert Downey Jr.|1965|American|1|Iron Man (2008 film);Sherlock Holmes (2009 film);Oppenheimer (film)|He won an Oscar for playing Lewis Strauss in Oppenheimer;He played Charlie Chaplin in 1992;He played Sherlock Holmes;He played Tony Stark, Iron Man|RDJ;Downey
Emma Watson|Emma Watson|1990|British|1|Harry Potter and the Philosopher's Stone (film);Beauty and the Beast (2017 film);Little Women (2019 film)|She was born in Paris;She is a UN Women Goodwill Ambassador;She played Belle in Beauty and the Beast;She played Hermione Granger|Watson
Daniel Radcliffe|Daniel Radcliffe|1989|British|1|Harry Potter and the Philosopher's Stone (film);Swiss Army Man;The Woman in Black (2012 film)|He played a corpse in Swiss Army Man;He starred in The Woman in Black;He was 11 when cast in his most famous role;He played Harry Potter|Radcliffe
Keanu Reeves|Keanu Reeves|1964|Canadian|2|The Matrix;John Wick (film);Speed (1994 film)|He was born in Beirut;He drove a bus that could not slow down in Speed;He plays a hitman seeking revenge for his dog;He played Neo in The Matrix|Reeves
Harrison Ford|Harrison Ford|1942|American|1|Star Wars (film);Raiders of the Lost Ark;Blade Runner|He worked as a carpenter before fame;He played Rick Deckard in Blade Runner;He played Indiana Jones;He played Han Solo in Star Wars|Ford
Mark Hamill|Mark Hamill|1951|American|2|Star Wars (film);The Empire Strikes Back;Return of the Jedi|He is a famous voice of the Joker in Batman cartoons and games;He returned to his role in The Last Jedi;He played a farm boy who becomes a Jedi;He played Luke Skywalker|Hamill
Carrie Fisher|Carrie Fisher|1956|American|2|Star Wars (film);The Empire Strikes Back;When Harry Met Sally...|Her mother was the actress Debbie Reynolds;She wrote the book Postcards from the Edge;She wore her hair in famous side buns;She played Princess Leia|Fisher
Sigourney Weaver|Sigourney Weaver|1949|American|3|Alien (film);Aliens (film);Avatar (2009 film)|She played a scientist in Avatar;She was in Ghostbusters;She fought a deadly creature aboard the Nostromo;She played Ellen Ripley in Alien|Weaver
Arnold Schwarzenegger|Arnold Schwarzenegger|1947|Austrian-American|1|The Terminator;Terminator 2: Judgment Day;Predator (film)|He won the Mr. Olympia bodybuilding title seven times;He was Governor of California;He said I'll be back;He played the Terminator|Schwarzenegger;Arnie
Sylvester Stallone|Sylvester Stallone|1946|American|2|Rocky;First Blood;The Expendables (2010 film)|He was nominated for an Oscar for writing Rocky;He played the soldier John Rambo;He ran up the steps in Philadelphia;He played the boxer Rocky Balboa|Stallone;Sly Stallone
Bruce Willis|Bruce Willis|1955|American|2|Die Hard;The Sixth Sense;Armageddon (1998 film)|He starred in the TV series Moonlighting;He played a child psychologist in The Sixth Sense;He played John McClane;He fought terrorists in a skyscraper in Die Hard|Willis
Jim Carrey|Jim Carrey|1962|Canadian-American|2|The Mask (1994 film);Ace Ventura: Pet Detective;The Truman Show|He played the Grinch in 2000;He played a man whose life is a TV show;He played a pet detective;He wore a magic green mask|Carrey
Robin Williams|Robin Williams|1951|American|1|Mrs. Doubtfire;Aladdin (1992 Disney film);Good Will Hunting|He won an Oscar for Good Will Hunting;He played an alien in Mork & Mindy;He dressed as an old Scottish nanny in Mrs. Doubtfire;He voiced the Genie in Aladdin|Williams
Eddie Murphy|Eddie Murphy|1961|American|1|Beverly Hills Cop;Shrek;Coming to America|He played many characters in The Nutty Professor;He played a prince who goes to New York in Coming to America;He played a Detroit cop in Beverly Hills Cop;He voiced Donkey in Shrek|Murphy
Cameron Diaz|Cameron Diaz|1972|American|2|There's Something About Mary;Shrek;Charlie's Angels (2000 film)|Her first film was The Mask;She played one of Charlie's Angels;She starred in There's Something About Mary;She voiced Princess Fiona in Shrek|Diaz
Mike Myers|Mike Myers|1963|Canadian|2|Shrek;Austin Powers: International Man of Mystery;Wayne's World (film)|He was a regular on Saturday Night Live;He co-starred in Wayne's World;He played the spy Austin Powers;He voiced Shrek|Myers
Jack Nicholson|Jack Nicholson|1937|American|3|One Flew Over the Cuckoo's Nest (film);The Shining (film);Batman (1989 film)|He has won three Oscars;He played the Joker in 1989;He broke through a door shouting Here's Johnny!;He starred in The Shining|Nicholson
Al Pacino|Al Pacino|1940|American|3|The Godfather;Scarface (1983 film);Scent of a Woman (1992 film)|He won his Oscar for playing a blind army officer;He said Say hello to my little friend;He played Tony Montana in Scarface;He played Michael Corleone in The Godfather|Pacino
Robert De Niro|Robert De Niro|1943|American|3|Taxi Driver;Raging Bull;The Godfather Part II|He won an Oscar for playing the young Vito Corleone;He played boxer Jake LaMotta;He asked You talkin' to me?;He played Travis Bickle in Taxi Driver|De Niro
Marlon Brando|Marlon Brando|1924|American|3|The Godfather;On the Waterfront;A Streetcar Named Desire (1951 film)|He refused his second Oscar in protest;He said I coulda been a contender;He played Stanley Kowalski;He played Vito Corleone in The Godfather|Brando
Audrey Hepburn|Audrey Hepburn|1929|British|2|Breakfast at Tiffany's (film);Roman Holiday;My Fair Lady (film)|She was born in Brussels;She was a UNICEF Goodwill Ambassador;She played Eliza Doolittle in My Fair Lady;She played Holly Golightly in Breakfast at Tiffany's|Hepburn
Marilyn Monroe|Marilyn Monroe|1926|American|2|Some Like It Hot;Gentlemen Prefer Blondes (1953 film);The Seven Year Itch|She was born Norma Jeane Mortenson;She sang Happy Birthday to President Kennedy;Her white dress blew up over a subway grate;She sang Diamonds Are a Girl's Best Friend|Monroe
Humphrey Bogart|Humphrey Bogart|1899|American|3|Casablanca (film);The Maltese Falcon (1941 film);The African Queen (film)|He won his Oscar for The African Queen;He played detective Sam Spade;He married Lauren Bacall;He played Rick in Casablanca|Bogart;Bogie
Judy Garland|Judy Garland|1922|American|2|The Wizard of Oz;A Star Is Born (1954 film);Meet Me in St. Louis|Her daughter Liza Minnelli is also a star;She sang The Trolley Song;She sang Over the Rainbow;She played Dorothy in The Wizard of Oz|Garland
Julie Andrews|Julie Andrews|1935|British|1|Mary Poppins (film);The Sound of Music (film);The Princess Diaries (film)|She played a queen in The Princess Diaries;She has a four-octave voice;She played Maria in The Sound of Music;She played Mary Poppins|Andrews
Clint Eastwood|Clint Eastwood|1930|American|3|The Good, the Bad and the Ugly;Dirty Harry;Unforgiven|He was mayor of Carmel-by-the-Sea;He won Best Director for Unforgiven and Million Dollar Baby;He played the Man with No Name;He played Dirty Harry|Eastwood
Jackie Chan|Jackie Chan|1954|Hong Kong|1|Rush Hour (1998 film);Police Story (1985 film);Kung Fu Panda (film)|He trained at the China Drama Academy as a boy;His films end with blooper reels of failed stunts;He voiced Monkey in Kung Fu Panda;He is a martial arts star who does his own stunts|Chan
Bruce Lee|Bruce Lee|1940|Hong Kong-American|2|Enter the Dragon;The Big Boss;Fist of Fury|He was born in San Francisco;He played Kato in The Green Hornet;He founded a martial art called Jeet Kune Do;He starred in Enter the Dragon|Lee
Michelle Yeoh|Michelle Yeoh|1962|Malaysian|2|Everything Everywhere All at Once;Crouching Tiger, Hidden Dragon;Tomorrow Never Dies|She was a Bond girl in Tomorrow Never Dies;She trained as a ballet dancer;She starred in Crouching Tiger, Hidden Dragon;She was the first Asian woman to win the Best Actress Oscar|Yeoh
Tom Holland|Tom Holland|1996|British|1|Spider-Man: Homecoming;Spider-Man: No Way Home;Uncharted (film)|He started out in Billy Elliot the Musical;He played treasure hunter Nathan Drake;He is British but plays a teenager from Queens;He played Spider-Man in the Marvel films|Holland
Zendaya|Zendaya|1996|American|2|Dune (2021 film);Spider-Man: Homecoming;The Greatest Showman|She won two Emmys for Euphoria;She played a trapeze artist in The Greatest Showman;She played Chani in Dune;She played MJ in the Spider-Man films
Timothée Chalamet|Timothée Chalamet|1995|American|2|Dune (2021 film);Wonka (film);Call Me by Your Name (film)|He has French and American citizenship;He played Bob Dylan in A Complete Unknown;He played Paul Atreides in Dune;He played the young Willy Wonka|Timothee Chalamet;Chalamet
Margot Robbie|Margot Robbie|1990|Australian|1|Barbie (film);The Wolf of Wall Street (2013 film);I, Tonya|She first found fame in the soap opera Neighbours;She played figure skater Tonya Harding;She played Harley Quinn;She played Barbie in 2023|Robbie
Ryan Gosling|Ryan Gosling|1980|Canadian|2|La La Land;Barbie (film);Drive (2011 film)|He was a Mouseketeer on The Mickey Mouse Club;He played a getaway driver in Drive;He played a jazz pianist in La La Land;He played Ken in Barbie|Gosling
Emma Stone|Emma Stone|1988|American|2|La La Land;Poor Things (film);Cruella (film)|She won her second Oscar for Poor Things;She played Gwen Stacy in The Amazing Spider-Man;She played Cruella de Vil;She played an aspiring actress in La La Land|Stone
Jennifer Lawrence|Jennifer Lawrence|1990|American|2|The Hunger Games (film);Silver Linings Playbook;X-Men: First Class|She won an Oscar for Silver Linings Playbook;She played Mystique in the X-Men films;She is from Kentucky;She played Katniss Everdeen|Lawrence
Chris Hemsworth|Chris Hemsworth|1983|Australian|1|Thor (film);The Avengers (2012 film);Extraction (2020 film)|He first found fame in the soap Home and Away;He played racing driver James Hunt in Rush;He has two actor brothers;He plays the thunder god Thor|Hemsworth
Chris Pratt|Chris Pratt|1979|American|1|Guardians of the Galaxy (film);Jurassic World;The Super Mario Bros. Movie|He played Andy in Parks and Recreation;He trained raptors in Jurassic World;He plays Star-Lord;He voiced Mario in The Super Mario Bros. Movie|Pratt
Dwayne Johnson|Dwayne Johnson|1972|American|1|Moana (2016 film);Jumanji: Welcome to the Jungle;Fast Five|He played college football at the University of Miami;He became famous as a wrestler called The Rock;He starred in the Jumanji films;He voiced the demigod Maui in Moana|The Rock
Hugh Jackman|Hugh Jackman|1968|Australian|2|X-Men (film);The Greatest Showman;Les Misérables (2012 film)|He has hosted the Tony Awards several times;He played Jean Valjean in Les Misérables;He played P. T. Barnum in The Greatest Showman;He played Wolverine|Jackman
Ian McKellen|Ian McKellen|1939|English|2|The Lord of the Rings: The Fellowship of the Ring;X-Men (film);Gods and Monsters (film)|He is a celebrated Shakespearean stage actor;He played Magneto in X-Men;He was knighted in 1991;He played Gandalf|McKellen;Sir Ian McKellen
Cate Blanchett|Cate Blanchett|1969|Australian|3|The Lord of the Rings: The Fellowship of the Ring;Elizabeth (film);Blue Jasmine|She won an Oscar for playing Katharine Hepburn;She played Queen Elizabeth I twice;She won Best Actress for Blue Jasmine;She played the elf queen Galadriel|Blanchett
Anthony Hopkins|Anthony Hopkins|1937|Welsh|2|The Silence of the Lambs (film);The Father (2020 film);Thor (film)|He won a second Oscar at the age of 83;He played Odin in Thor;He was born in Port Talbot;He played Hannibal Lecter|Hopkins;Sir Anthony Hopkins
Helen Mirren|Helen Mirren|1945|English|3|The Queen (2006 film);Gosford Park;Red (2010 film)|She starred in the TV series Prime Suspect;She played a retired spy in RED;She has played both Elizabeth I and Elizabeth II;She won an Oscar for The Queen|Mirren
Judi Dench|Judi Dench|1934|English|2|GoldenEye;Shakespeare in Love;Skyfall|She won an Oscar for about eight minutes on screen;She played Queen Elizabeth I in Shakespeare in Love;She played Queen Victoria twice;She played M in the James Bond films|Dench;Dame Judi Dench
Daniel Craig|Daniel Craig|1968|English|2|Casino Royale (2006 film);Skyfall;Knives Out|He played detective Benoit Blanc;He was the first blond actor to play his famous role;He starred in Casino Royale;He played James Bond from 2006 to 2021|Craig
Sean Connery|Sean Connery|1930|Scottish|2|Dr. No (film);Goldfinger (film);The Untouchables (film)|He once worked as a milkman in Edinburgh;He won an Oscar for The Untouchables;He played Indiana Jones's father;He was the first actor to play James Bond in a film|Connery
Kate Winslet|Kate Winslet|1975|English|2|Titanic (1997 film);The Reader (2008 film);Sense and Sensibility (1995 film)|She won an Oscar for The Reader;She learned to free-dive for Avatar: The Way of Water;She was in Sense and Sensibility;She played Rose in Titanic|Winslet
Nicole Kidman|Nicole Kidman|1967|Australian-American|3|Moulin Rouge!;The Hours (film);Paddington (2014 film)|She was born in Hawaii;She played the villain in Paddington;She won an Oscar playing Virginia Woolf;She starred in Moulin Rouge!|Kidman
Natalie Portman|Natalie Portman|1981|Israeli-American|2|Black Swan (film);Star Wars: Episode I – The Phantom Menace;Léon: The Professional|She studied psychology at Harvard;She played Jane Foster in Thor;She won an Oscar for Black Swan;She played Padmé Amidala in Star Wars|Portman
Anne Hathaway|Anne Hathaway|1982|American|2|The Princess Diaries (film);The Devil Wears Prada (film);Les Misérables (2012 film)|She won an Oscar for Les Misérables;She shares her name with Shakespeare's wife;She was an assistant to a fashion editor in The Devil Wears Prada;She played Mia in The Princess Diaries|Hathaway
Sandra Bullock|Sandra Bullock|1964|American|2|Speed (1994 film);Gravity (2013 film);The Blind Side (film)|She won an Oscar for The Blind Side;She voiced Scarlet Overkill in Minions;She drove the runaway bus in Speed;She played an astronaut stranded in space in Gravity|Bullock
Whoopi Goldberg|Whoopi Goldberg|1955|American|2|Ghost (1990 film);Sister Act;The Color Purple (1985 film)|She is one of the few people with an Emmy, Grammy, Oscar and Tony;She played Guinan in Star Trek;She hid as a nun in Sister Act;She won an Oscar for Ghost|Goldberg
Samuel L. Jackson|Samuel L. Jackson|1948|American|2|Pulp Fiction;Jurassic Park;The Avengers (2012 film)|His films have earned more at the box office than almost any other actor's;He played Mace Windu in Star Wars;He was in Pulp Fiction;He plays Nick Fury in the Marvel films|Samuel Jackson
Viola Davis|Viola Davis|1965|American|3|Fences (film);The Help (film);The Woman King|She completed the EGOT with a Grammy in 2023;She played a warrior general in The Woman King;She starred in How to Get Away with Murder;She won an Oscar for Fences|Davis
Lupita Nyong'o|Lupita Nyong'o|1983|Kenyan-Mexican|3|12 Years a Slave (film);Black Panther (film);Us (2019 film)|She was born in Mexico City;She played two roles in Jordan Peele's Us;She played Nakia in Black Panther;She won an Oscar for her first feature film role|Nyong'o
Idris Elba|Idris Elba|1972|English|3|Thor (film);Beasts of No Nation (film);Zootopia|He played detective John Luther on TV;He voiced Chief Bogo in Zootopia;He played Heimdall in Thor;He played Nelson Mandela in Long Walk to Freedom|Elba
Benedict Cumberbatch|Benedict Cumberbatch|1976|English|2|Doctor Strange (2016 film);The Imitation Game;The Power of the Dog (film)|He voiced the dragon Smaug;He played Alan Turing in The Imitation Game;He played Sherlock in the BBC series;He plays Doctor Strange|Cumberbatch
Gal Gadot|Gal Gadot|1985|Israeli|2|Wonder Woman (2017 film);Fast & Furious (2009 film);Red Notice (film)|She was Miss Israel in 2004;She served in the Israel Defense Forces;She played Gisele in the Fast & Furious films;She played Wonder Woman|Gadot
Keira Knightley|Keira Knightley|1985|English|2|Pirates of the Caribbean: The Curse of the Black Pearl;Pride & Prejudice (2005 film);Love Actually|She played Padmé's decoy in The Phantom Menace;She starred in Bend It Like Beckham;She played Elizabeth Bennet;She played Elizabeth Swann in Pirates of the Caribbean|Knightley
Orlando Bloom|Orlando Bloom|1977|English|2|The Lord of the Rings: The Fellowship of the Ring;Pirates of the Caribbean: The Curse of the Black Pearl;Troy (film)|He played Paris in Troy;He studied at the Guildhall School in London;He played Will Turner in Pirates of the Caribbean;He played the elf Legolas|Bloom
Elijah Wood|Elijah Wood|1981|American|2|The Lord of the Rings: The Fellowship of the Ring;The Lord of the Rings: The Return of the King;Happy Feet|He voiced a dancing penguin in Happy Feet;He was a child actor in Flipper;He has large blue eyes;He played the hobbit Frodo Baggins|Wood
Rowan Atkinson|Rowan Atkinson|1955|English|1|Johnny English;Mr. Bean's Holiday;Love Actually|He studied electrical engineering at Oxford;He played a bumbling spy called Johnny English;He starred in Blackadder;He plays Mr. Bean|Atkinson
Hugh Grant|Hugh Grant|1960|English|3|Notting Hill (film);Four Weddings and a Funeral;Paddington 2|He played a vain actor in Paddington 2;He played the British prime minister in Love Actually;He ran a bookshop in Notting Hill;He starred in Four Weddings and a Funeral|Grant
Emma Thompson|Emma Thompson|1959|English|3|Sense and Sensibility (1995 film);Love Actually;Nanny McPhee|She has won Oscars for both acting and writing;She played Professor Trelawney in Harry Potter;She played P. L. Travers in Saving Mr. Banks;She played Nanny McPhee|Thompson
Shirley Temple|Shirley Temple|1928|American|3|Bright Eyes (1934 film);Heidi (1937 film);Curly Top (film)|She later became a US ambassador;She sang On the Good Ship Lollipop;She was famous for her curls;She was the biggest child star of the 1930s|Temple
Paul Newman|Paul Newman|1925|American|3|Butch Cassidy and the Sundance Kid;The Sting;Cars (film)|He founded a food company that gives its profits to charity;He was also a racing driver;He voiced Doc Hudson in Cars;He played Butch Cassidy|Newman
Gene Kelly|Gene Kelly|1912|American|3|Singin' in the Rain;An American in Paris (film);Anchors Aweigh (film)|He danced with Jerry the cartoon mouse;He starred in An American in Paris;He danced while splashing through puddles;He starred in Singin' in the Rain|Kelly
Fred Astaire|Fred Astaire|1899|American|3|Top Hat;Swing Time (film);Funny Face|His most famous dance partner was Ginger Rogers;He danced on the walls and ceiling in Royal Wedding;He wore a top hat and tails;He was a famous dancer of Hollywood musicals|Astaire
Jack Black|Jack Black|1969|American|1|School of Rock;Kung Fu Panda (film);Jumanji: Welcome to the Jungle|He is half of the band Tenacious D;He sang Peaches as Bowser;He played a rock-loving substitute teacher;He voices Po in Kung Fu Panda|Black
Vin Diesel|Vin Diesel|1967|American|2|The Fast and the Furious (2001 film);Guardians of the Galaxy (film);Saving Private Ryan|He was in Saving Private Ryan;He voiced The Iron Giant;He voices Groot;He plays Dominic Toretto in the Fast & Furious films|Diesel
Cillian Murphy|Cillian Murphy|1976|Irish|3|Oppenheimer (film);28 Days Later;Inception|He was born in Cork;He played the Scarecrow in Batman Begins;He played Tommy Shelby in Peaky Blinders;He won an Oscar for playing the father of the atomic bomb|Murphy
`;
