// Books: Wikipedia title | display | author | year | genre | difficulty | kids (1/0) | Gutenberg id ('' if none) | first line ('' if none) | clues hardest->easiest | alt
// First lines ONLY for public-domain books (published before 1930, Gutenberg id given); the builder verifies them against the Gutenberg text and refuses a first line on any later book. Modern books get clues and summaries in our own words, never quoted passages.
export const BOOKS = `
Pride and Prejudice|Pride and Prejudice|Jane Austen|1813|romance|1|0|1342|It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife.|Its working title was First Impressions;The Bennet family has five daughters;Its hero owns an estate called Pemberley;Elizabeth Bennet clashes with the proud Mr Darcy|
Moby-Dick|Moby-Dick|Herman Melville|1851|adventure|2|0|2701|Call me Ishmael.|A coffee chain takes its name from the first mate, Starbuck;The ship is called the Pequod;Its captain lost his leg to a sea creature;Captain Ahab hunts a great white whale|Moby Dick
Alice's Adventures in Wonderland|Alice's Adventures in Wonderland|Lewis Carroll|1865|fantasy|1|1|11|Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do:|Its author was a mathematician at Oxford;A grinning cat can vanish leaving only its smile;A girl attends a mad tea party;A girl follows a White Rabbit down a rabbit hole|Alice in Wonderland
Frankenstein|Frankenstein|Mary Shelley|1818|horror|1|0|84|You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings.|It began as a ghost-story contest at Lake Geneva;Its full title includes The Modern Prometheus;The story opens with letters from an Arctic explorer;A young scientist brings a creature to life|The Modern Prometheus
Dracula|Dracula|Bram Stoker|1897|horror|1|0|345|Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning;|It is told through diaries, letters and newspaper cuttings;Part of it is set in Whitby on the Yorkshire coast;Professor Van Helsing leads the hunt;A vampire count travels from Transylvania to England|
A Tale of Two Cities|A Tale of Two Cities|Charles Dickens|1859|historical|2|0|98|It was the best of times, it was the worst of times,|Madame Defarge knits the names of enemies into her work;A man is recalled to life after 18 years in the Bastille;It is set in London and Paris during the French Revolution;It ends with Sydney Carton going to the guillotine|
Great Expectations|Great Expectations|Charles Dickens|1861|coming-of-age|2|0|1400|My father's family name being Pirrip, and my Christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip.|An escaped convict surprises a boy in a churchyard;A jilted bride still wears her wedding dress years later;Miss Havisham's clocks are all stopped;An orphan named Pip gets a mysterious fortune|
A Christmas Carol|A Christmas Carol|Charles Dickens|1843|ghost story|1|1|46|Marley was dead: to begin with.|Its chapters are called staves;Tiny Tim is the son of a poor clerk;Three spirits visit on Christmas Eve;A miser named Ebenezer Scrooge learns to be kind|
Jane Eyre|Jane Eyre|Charlotte Brontë|1847|romance|2|0|1260|There was no possibility of taking a walk that day.|It was first published under the name Currer Bell;Its heroine is sent to the harsh Lowood School;A secret is hidden in the attic of Thornfield Hall;An orphan governess falls in love with Mr Rochester|
Wuthering Heights|Wuthering Heights|Emily Brontë|1847|romance|2|0|768|1801—I have just returned from a visit to my landlord—the solitary neighbour that I shall be troubled with.|It was its author's only novel;Much of it is narrated by a housekeeper, Nelly Dean;It is set on the Yorkshire moors;It tells of the passion between Heathcliff and Catherine|
Treasure Island|Treasure Island|Robert Louis Stevenson|1883|adventure|1|1|120||It popularised the idea of X marking the spot;A boy finds a map in a sea chest at the Admiral Benbow inn;A one-legged cook has a parrot called Captain Flint;Jim Hawkins sails to find buried pirate gold|
The Hound of the Baskervilles|The Hound of the Baskervilles|Arthur Conan Doyle|1902|mystery|2|0|2852|Mr. Sherlock Holmes, who was usually very late in the mornings, save upon those not infrequent occasions when he was up all night, was seated at the breakfast table.|It was serialised in The Strand Magazine;A family legend tells of a curse;It is set on Dartmoor;A famous detective investigates a monstrous dog|
The Picture of Dorian Gray|The Picture of Dorian Gray|Oscar Wilde|1890|gothic|2|0|174|The studio was filled with the rich odour of roses,|It was its author's only novel;Lord Henry Wotton is a bad influence;A painting ages while its subject stays young;A handsome young man trades his soul for eternal youth|
Adventures of Huckleberry Finn|Adventures of Huckleberry Finn|Mark Twain|1884|adventure|2|0|76|You don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter.|It is written in Southern dialect;Its hero fakes his own death;A boy and a man escaping slavery float down the Mississippi on a raft;Its hero is Tom Sawyer's friend Huck|Huckleberry Finn;Huck Finn
Little Women|Little Women|Louisa May Alcott|1868|coming-of-age|2|1|514|“Christmas won't be Christmas without any presents,” grumbled Jo, lying on the rug.|It was partly based on its author's own family;Its neighbour boy is called Laurie;Jo wants to be a writer;It follows the four March sisters|
Peter and Wendy|Peter Pan|J. M. Barrie|1911|fantasy|1|1|16|All children, except one, grow up.|It grew out of a 1904 stage play;A ticking crocodile chases the villain;A fairy called Tinker Bell sprinkles fairy dust;A boy who never grows up takes Wendy to Neverland|Peter and Wendy
The Wonderful Wizard of Oz|The Wonderful Wizard of Oz|L. Frank Baum|1900|fantasy|1|1|55|Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer's wife.|In the book her magic shoes are silver, not ruby;Its travellers want a brain, a heart and courage;A cyclone carries a girl and her dog Toto away;Dorothy follows the yellow brick road to the Emerald City|The Wizard of Oz
The Jungle Book|The Jungle Book|Rudyard Kipling|1894|adventure|1|1|236|It was seven o'clock of a very warm evening in the Seeonee hills when Father Wolf woke up from his day's rest,|It also includes the story of a mongoose called Rikki-Tikki-Tavi;A tiger called Shere Khan hunts the hero;A bear named Baloo teaches the law of the jungle;A boy named Mowgli is raised by wolves|
The War of the Worlds|The War of the Worlds|H. G. Wells|1898|science fiction|2|0|36|No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man's|A 1938 radio version caused alarm in the United States;Its invaders use heat-rays and tripod machines;The invaders are defeated by germs;Martians invade England|
The Time Machine|The Time Machine|H. G. Wells|1895|science fiction|2|0|35|The Time Traveller (for so it will be convenient to speak of him) was expounding a recondite matter to us.|The far future has gentle Eloi and underground Morlocks;Its hero is known only as the Traveller;It popularised the idea of travelling through time in a vehicle;A Victorian inventor travels to the year 802,701|
Robinson Crusoe|Robinson Crusoe|Daniel Defoe|1719|adventure|2|0|521|I was born in the year 1632, in the city of York, of a good family, though not of that country,|It is often called the first English novel;Its hero spends 28 years on a remote island;He names his companion Friday;A shipwrecked sailor survives alone on an island|
Gulliver's Travels|Gulliver's Travels|Jonathan Swift|1726|satire|2|0|829|My father had a small estate in Nottinghamshire; I was the third of five sons.|It is a satire written by an Irish clergyman;Its hero visits a flying island called Laputa;He meets talking horses called Houyhnhnms;A ship's surgeon is captured by tiny people in Lilliput|
Don Quixote|Don Quixote|Miguel de Cervantes|1605|satire|2|0|996|In a village of La Mancha, the name of which I have no desire to call to mind,|It was published in two parts, in 1605 and 1615;His horse is called Rocinante;His squire is Sancho Panza;An old knight attacks windmills thinking they are giants|
Les Misérables|Les Misérables|Victor Hugo|1862|historical|2|0|135|In 1815, M. Charles-François-Bienvenu Myriel was Bishop of D——|A police inspector named Javert hunts the hero;It includes the June Rebellion in Paris;Its hero was jailed for stealing bread;Jean Valjean is an ex-convict seeking redemption|Les Miserables
Anna Karenina|Anna Karenina|Leo Tolstoy|1878|romance|3|0|1399|Happy families are all alike; every unhappy family is unhappy in its own way.|A landowner called Levin is its other main character;It was first published in instalments in a Russian magazine;Its heroine has an affair with Count Vronsky;A Russian aristocrat leaves her husband for an officer|
Crime and Punishment|Crime and Punishment|Fyodor Dostoevsky|1866|psychological|3|0|2554|On an exceptionally hot evening early in July a young man came out of the garret in which he lodged in S. Place|A detective called Porfiry plays mind games with the hero;It is set in Saint Petersburg;A poor former student murders a pawnbroker;Raskolnikov struggles with his guilt|
War and Peace|War and Peace|Leo Tolstoy|1869|historical|2|0|2600|Well, Prince, so Genoa and Lucca are now just family estates of the Buonapartes.|Its characters include Pierre Bezukhov and Natasha Rostova;It includes the burning of Moscow;It is set during Napoleon's invasion of Russia;It is a famously long Russian novel|
The Count of Monte Cristo|The Count of Monte Cristo|Alexandre Dumas|1844|adventure|2|0|1184|On the 24th of February, 1815, the look-out at Notre-Dame de la Garde signalled the three-master, the Pharaon from Smyrna, Trieste, and Naples.|Its hero escapes by taking the place of a dead prisoner;An old prisoner tells him about treasure;A sailor is wrongly jailed in the Château d'If;Edmond Dantès takes revenge under a new identity|
Emma (novel)|Emma|Jane Austen|1815|romance|2|0|158|Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence;|It is set in the village of Highbury;Mr Knightley is an old family friend;Its heroine plays matchmaker for her friend Harriet;A wealthy young woman meddles in others' love lives|
Oliver Twist|Oliver Twist|Charles Dickens|1838|social|1|0|730|Among other public buildings in a certain town, which for many reasons it will be prudent to refrain from mentioning,|Its villain Bill Sikes has a dog called Bull's-eye;A pickpocket gang is led by Fagin;The Artful Dodger is a young thief;An orphan in a workhouse asks for more|
David Copperfield|David Copperfield|Charles Dickens|1850|coming-of-age|3|0|766|Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.|Its author called it his favourite child;A clerk named Uriah Heep pretends to be humble;Mr Micawber always hopes something will turn up;It is a semi-autobiographical novel about a boy growing up in Victorian England|
Heart of Darkness|Heart of Darkness|Joseph Conrad|1899|adventure|3|0|219|The Nellie, a cruising yawl, swung to her anchor without a flutter of the sails, and was at rest.|It inspired the film Apocalypse Now;Its narrator tells the story on a boat on the Thames;A sailor called Marlow travels up an African river;Marlow searches for the ivory trader Kurtz|
The Great Gatsby|The Great Gatsby|F. Scott Fitzgerald|1925|social|2|0|64317|In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since.|A green light shines at the end of a dock;A pair of eyes watches from an advertising billboard;It is narrated by Nick Carraway;A mysterious millionaire throws lavish parties on Long Island|
The Metamorphosis|The Metamorphosis|Franz Kafka|1915|novella|2|0|||Its hero is a travelling salesman;His family is horrified and locks him in his room;It was written in German by a Prague author;Gregor Samsa wakes up transformed into a giant insect|Metamorphosis
The Secret Garden|The Secret Garden|Frances Hodgson Burnett|1911|children's|1|1|113|When Mary Lennox was sent to Misselthwaite Manor to live with her uncle everybody said she was the most disagreeable-looking child ever seen.|A robin shows the heroine where a key is buried;A boy called Dickon can charm animals;A sickly cousin hidden in the house learns to walk;An orphan girl finds a locked, hidden garden|
Black Beauty|Black Beauty|Anna Sewell|1877|children's|1|1|271|The first place that I can well remember was a large pleasant meadow with a pond of clear water in it.|Its author wrote it to encourage kindness to horses;It is told by an animal;Its narrator's friends include Ginger and Merrylegs;It is the life story of a horse|
Anne of Green Gables|Anne of Green Gables|L. M. Montgomery|1908|children's|1|1|45|Mrs. Rachel Lynde lived just where the Avonlea main road dipped down into a little hollow,|It is set on Prince Edward Island;She breaks a slate over Gilbert Blythe's head;The Cuthberts wanted a boy but got a red-haired girl;A talkative orphan girl is adopted by a brother and sister|
The Wind in the Willows|The Wind in the Willows|Kenneth Grahame|1908|children's|1|1|289|The Mole had been working very hard all the morning, spring-cleaning his little home.|Weasels and stoats take over a grand house;One character is obsessed with motor cars;Its friends include Ratty and Badger;Mole, Rat, Badger and Toad have adventures by the river|
The Call of the Wild|The Call of the Wild|Jack London|1903|adventure|2|1|215|Buck did not read the newspapers, or he would have known that trouble was brewing,|It is set during the Klondike Gold Rush;Its hero is stolen from a home in California;A kind man named John Thornton earns the hero's devotion;A dog becomes a sled dog in the Yukon|
Around the World in Eighty Days|Around the World in Eighty Days|Jules Verne|1872|adventure|1|1|103|Mr. Phileas Fogg lived, in 1872, at No. 7, Saville Row, Burlington Gardens,|A detective named Fix follows the hero;Its hero rescues a widow in India;His valet is called Passepartout;An Englishman makes a bet to circle the globe|
Twenty Thousand Leagues Under the Seas|Twenty Thousand Leagues Under the Seas|Jules Verne|1870|science fiction|2|1|164|The year 1866 was signalised by a remarkable incident, a mysterious and puzzling phenomenon, which doubtless no one has yet forgotten.|A professor is thrown overboard and rescued;Its crew fights a giant squid;The submarine is called the Nautilus;Captain Nemo travels the oceans in a submarine|20,000 Leagues Under the Sea;Twenty Thousand Leagues Under the Sea
Strange Case of Dr Jekyll and Mr Hyde|Strange Case of Dr Jekyll and Mr Hyde|Robert Louis Stevenson|1886|horror|2|0|43|Mr. Utterson the lawyer was a man of a rugged countenance that was never lighted by a smile;|Its author reportedly wrote the first draft in a few days;It is set in Victorian London;A lawyer investigates his friend's will;A doctor drinks a potion that turns him into a monster|Dr Jekyll and Mr Hyde;Jekyll and Hyde
Winnie-the-Pooh (book)|Winnie-the-Pooh|A. A. Milne|1926|children's|1|1|67098|Here is Edward Bear, coming downstairs now, bump, bump, bump, on the back of his head, behind Christopher Robin.|Its illustrator was E. H. Shepard;Its hero was named after a real bear at London Zoo;Its friends include Piglet and Eeyore;A bear of very little brain loves honey|Winnie the Pooh
Kidnapped (novel)|Kidnapped|Robert Louis Stevenson|1886|adventure|3|0|421|I will begin the story of my adventures with a certain morning early in the month of June, the year of grace 1751,|It is set after the Jacobite rising of 1745;Its hero is cheated by his miserly uncle Ebenezer;He travels with the Highlander Alan Breck Stewart;Young David Balfour is seized and put on a ship|
Sense and Sensibility|Sense and Sensibility|Jane Austen|1811|romance|2|0|161|The family of Dashwood had long been settled in Sussex.|It was its author's first published novel;Colonel Brandon loves the younger sister;Marianne falls for the dashing Willoughby;Elinor and Marianne Dashwood face love and money troubles|
Nineteen Eighty-Four|Nineteen Eighty-Four|George Orwell|1949|dystopian|2|0|||It introduced the word doublethink;Room 101 holds a person's worst fear;Winston Smith works at the Ministry of Truth;Big Brother is watching you|1984
Animal Farm|Animal Farm|George Orwell|1945|satire|2|0|||It is an allegory of the Russian Revolution;A horse called Boxer works himself to death;Its pigs end up claiming that some animals are more equal than the rest;Farm animals rebel against their human farmer|
Brave New World|Brave New World|Aldous Huxley|1932|dystopian|3|0|||People take a drug called soma;Babies are grown in hatcheries;Its title comes from Shakespeare's The Tempest;A future society is controlled by pleasure and conditioning|
To Kill a Mockingbird|To Kill a Mockingbird|Harper Lee|1960|social|2|0|||A recluse called Boo Radley leaves gifts in a tree;It won the Pulitzer Prize;It is narrated by a girl called Scout;Atticus Finch defends a Black man in Alabama|
The Catcher in the Rye|The Catcher in the Rye|J. D. Salinger|1951|coming-of-age|3|0|||Its hero wonders where Central Park's ducks go in winter;Its hero has been expelled from Pencey Prep;It is narrated by a teenager in New York;Holden Caulfield wanders around Manhattan|
The Hobbit|The Hobbit|J. R. R. Tolkien|1937|fantasy|1|1|||A riddle contest takes place deep under a mountain;Thirteen dwarves arrive for tea;A dragon called Smaug guards treasure;Bilbo Baggins goes on an unexpected journey|There and Back Again
The Lord of the Rings|The Lord of the Rings|J. R. R. Tolkien|1954|fantasy|1|0|||It was published in three volumes in 1954 and 1955;Its villain is the dark power Sauron;A fellowship of nine sets out from Rivendell;Frodo must cast a dangerous golden band into the fires of Mount Doom|
The Lion, the Witch and the Wardrobe|The Lion, the Witch and the Wardrobe|C. S. Lewis|1950|fantasy|1|1|||Edmund is tempted with Turkish Delight;In the land where it is set, it is always winter and never Christmas;Children find a magical land at the back of a cupboard;Aslan the lion battles the White Witch in Narnia|
Charlotte's Web|Charlotte's Web|E. B. White|1952|children's|1|1|||A rat called Templeton helps for food;A girl named Fern saves a runt piglet;Words like SOME PIG appear in a spider's threads;A spider saves a pig called Wilbur|
The Cat in the Hat|The Cat in the Hat|Dr. Seuss|1957|children's|1|1|||A fish in a bowl warns the children;Thing One and Thing Two cause chaos;Two children are stuck indoors on a rainy day;A tall feline in a red-and-white striped topper comes to visit|
Fahrenheit 451|Fahrenheit 451|Ray Bradbury|1953|dystopian|2|0|||A mechanical hound hunts people down;Rebels memorise whole books to save them;Its title is the temperature at which paper is said to burn;Firemen burn books instead of putting out fires|
Harry Potter and the Philosopher's Stone|Harry Potter and the Philosopher's Stone|J. K. Rowling|1997|fantasy|1|1|||In the US it was called the Sorcerer's Stone;A three-headed dog guards a trapdoor;A boy lives in a cupboard under the stairs;An orphan learns he is a wizard and goes to Hogwarts|Harry Potter and the Sorcerer's Stone
The Hunger Games|The Hunger Games|Suzanne Collins|2008|dystopian|2|0|||A mockingjay pin becomes a symbol of rebellion;Its heroine volunteers to save her younger sister;Teenagers from twelve districts are sent to an arena;Katniss Everdeen fights in a televised battle to the death|
The Very Hungry Caterpillar|The Very Hungry Caterpillar|Eric Carle|1969|picture book|1|1|||Its pages have holes punched in them;On Saturday the hero eats chocolate cake and much more;It eats through more and more food each day of the week;A caterpillar eats and eats and becomes a butterfly|
Matilda (novel)|Matilda|Roald Dahl|1988|children's|1|1|||Miss Honey is a kind teacher;The headmistress Miss Trunchbull throws a girl by her pigtails;Its heroine reads every book in the library;A clever girl discovers she can move things with her mind|
Charlie and the Chocolate Factory|Charlie and the Chocolate Factory|Roald Dahl|1964|children's|1|1|||A girl turns into a giant blueberry;Oompa-Loompas work in the factory;Five children find golden tickets;A poor boy wins a tour of Willy Wonka's factory|
The BFG|The BFG|Roald Dahl|1982|children's|1|1|||Its hero drinks a fizzy drink called frobscottle;He catches dreams in jars and mixes them;He speaks in jumbled, made-up words;A girl named Sophie is carried off from an orphanage;A kind visitor from a faraway land blows good dreams into children's bedrooms|Big Friendly Giant
The Little Prince|The Little Prince|Antoine de Saint-Exupéry|1943|fable|2|1|||Its author was a pilot who disappeared in 1944;A fox teaches the hero about friendship;Its hero cares for a rose on a tiny asteroid;A pilot stranded in the desert meets a boy from another planet|Le Petit Prince
Of Mice and Men|Of Mice and Men|John Steinbeck|1937|novella|3|0|||Its title comes from a poem by Robert Burns;A large man loves to pet soft things;Two migrant ranch workers dream of owning a farm;George looks after his friend Lennie|
The Grapes of Wrath|The Grapes of Wrath|John Steinbeck|1939|social|3|0|||It won the Pulitzer Prize in 1940;It is set during the Dust Bowl;A family drives Route 66 to California;The Joad family flee Oklahoma in search of work|
The Old Man and the Sea|The Old Man and the Sea|Ernest Hemingway|1952|novella|2|0|||It helped win its author the Nobel Prize;A boy named Manolin looks after the hero;Sharks eat the catch on the way home;An aging Cuban fisherman battles a giant marlin|
Lord of the Flies|Lord of the Flies|William Golding|1954|allegory|2|0|||A pig's head on a stick gives it its title;A boy called Piggy has glasses used to start fires;A conch shell is used to call meetings;Schoolboys stranded on an island turn savage|
One Hundred Years of Solitude|One Hundred Years of Solitude|Gabriel García Márquez|1967|magic realism|3|0|||Yellow butterflies follow a character wherever he goes;It is a classic of magic realism;It is set in the town of Macondo;It follows seven generations of the Buendía family|
Beloved (novel)|Beloved|Toni Morrison|1987|historical|3|0|||It won the Pulitzer Prize in 1988;Its story was inspired by Margaret Garner;It is set after the American Civil War in Ohio;A woman who escaped slavery is haunted by her dead daughter|
The Handmaid's Tale|The Handmaid's Tale|Margaret Atwood|1985|dystopian|3|0|||Its sequel is called The Testaments;The women wear red robes and white bonnets;It is set in the Republic of Gilead;A woman called Offred is forced to bear children for the ruling class|
The Da Vinci Code|The Da Vinci Code|Dan Brown|2003|thriller|2|0|||It begins with a murder in the Louvre;A cryptologist named Sophie Neveu helps the hero;Its hero is symbologist Robert Langdon;Clues are hidden in famous artworks|
The Hitchhiker's Guide to the Galaxy|The Hitchhiker's Guide to the Galaxy|Douglas Adams|1979|science fiction|2|0|||The answer to life, the universe and everything is 42;Earth is demolished for a hyperspace bypass;Arthur Dent escapes with his friend Ford Prefect;A guidebook says Don't Panic on the cover|Hitchhiker's Guide
Gone with the Wind (novel)|Gone with the Wind|Margaret Mitchell|1936|historical|3|0|||It won the Pulitzer Prize in 1937;Its heroine's home is a plantation called Tara;It is set during the American Civil War;Scarlett O'Hara loves Ashley but marries others|
Things Fall Apart|Things Fall Apart|Chinua Achebe|1958|historical|3|0|||Its title comes from a poem by W. B. Yeats;Its hero is a wrestling champion;It shows the arrival of British colonialists and missionaries;Okonkwo is a proud leader in an Igbo village|
The Diary of a Young Girl|The Diary of a Young Girl|Anne Frank|1947|memoir|2|0|||She addressed her entries to an imaginary friend called Kitty;It was published by her father, the only one of the family to survive;It was written in a secret annex in Amsterdam;A Jewish teenager writes while hiding from the Nazis|Diary of Anne Frank
Where the Wild Things Are|Where the Wild Things Are|Maurice Sendak|1963|picture book|1|1|||A forest grows in a boy's bedroom;He tames monsters by staring into their eyes;He is sent to bed without supper;A boy in a wolf suit sails to an island of monsters|
The Gruffalo|The Gruffalo|Julia Donaldson|1999|picture book|1|1|||A fox, an owl and a snake all want to eat the hero;It is written in rhyme;The monster has terrible tusks and a poisonous wart;A clever mouse invents a monster to scare off predators|
Diary of a Wimpy Kid|Diary of a Wimpy Kid|Jeff Kinney|2007|children's|1|1|||It first appeared online;Its hero's best friend is Rowley;Its hero insists his notebook is a journal;Greg Heffley writes about middle school|
Watership Down|Watership Down|Richard Adams|1972|adventure|2|1|||A rabbit called Fiver has visions of danger;A seagull called Kehaar helps them;Its villain is General Woundwort;A group of rabbits search for a new home|
Life of Pi|Life of Pi|Yann Martel|2001|adventure|2|0|||It won the Booker Prize in 2002;Its hero's family owns a zoo in Pondicherry;A tiger named Richard Parker shares a lifeboat;A boy survives a shipwreck in the Pacific with a tiger|
The Book Thief|The Book Thief|Markus Zusak|2005|historical|3|0|||Its narrator is Death;Its heroine's foster father plays the accordion;A Jewish man hides in a basement;A foster girl in Nazi Germany steals novels, even from a bonfire|
Slaughterhouse-Five|Slaughterhouse-Five|Kurt Vonnegut|1969|satire|3|0|||The refrain So it goes follows every death;Its hero is abducted by aliens from Tralfamadore;Billy Pilgrim becomes unstuck in time;It centres on the firebombing of Dresden|
Catch-22|Catch-22|Joseph Heller|1961|satire|3|0|||Its hero censors letters in hospital;It is set on an island off Italy during the Second World War;Its title became a phrase for an impossible no-win rule;Bombardier Yossarian tries to escape flying more missions|
Rebecca (novel)|Rebecca|Daphne du Maurier|1938|gothic|2|0|||Its narrator's name is never given;A sinister housekeeper is called Mrs Danvers;A young bride lives in the shadow of her husband's first wife;It is set at a Cornish estate called Manderley|
Murder on the Orient Express|Murder on the Orient Express|Agatha Christie|1934|mystery|2|0|||The train is stopped by a snowdrift;Every suspect has a link to a kidnapping case;A wealthy American is found stabbed in his compartment;Hercule Poirot solves a murder on a famous train|
And Then There Were None|And Then There Were None|Agatha Christie|1939|mystery|2|0|||It is the best-selling mystery novel of all time;A nursery rhyme predicts each death;Ten strangers are invited to an island;The guests die one by one until none are left|
Dune (novel)|Dune|Frank Herbert|1965|science fiction|2|0|||Its hero is trained in a litany for facing fear;Giant sandworms roam the desert;A spice called melange is the most valuable substance in the universe;Paul Atreides moves to the desert planet Arrakis|
Mary Poppins (book)|Mary Poppins|P. L. Travers|1934|children's|1|1|||Its author was born in Australia;A pavement artist called Bert is a friend;The Banks children live at Cherry Tree Lane;A magical nanny arrives on the east wind with an umbrella|
A Bear Called Paddington|A Bear Called Paddington|Michael Bond|1958|children's|1|1|||Its hero's aunt lives in a home for retired bears in Lima;He loves marmalade sandwiches;He is found at a London railway station by the Brown family;A bear from Peru wears a duffel coat and a hat|Paddington
The Tiger Who Came to Tea|The Tiger Who Came to Tea|Judith Kerr|1968|picture book|1|1|||Daddy suggests going out to a café for supper;The visitor drinks all the water in the tap;A girl called Sophie and her mummy have an unexpected guest;A tiger eats all the food in the house|
`;

// One- or two-sentence plot summaries, written in our own words (keyed by display title).
export const SUMMARIES = {
  'Pride and Prejudice': 'Lively Elizabeth Bennet and the haughty Mr Darcy badly misjudge each other before their first impressions give way to love.',
  'Moby-Dick': 'Ishmael joins the whaling ship Pequod, whose captain, Ahab, is obsessed with killing the white whale that took his leg.',
  "Alice's Adventures in Wonderland": 'A bored girl tumbles down a rabbit hole into a nonsense world of shrinking potions, a Cheshire Cat, a Mad Hatter and a furious Queen of Hearts.',
  'Frankenstein': 'A young Swiss scientist builds a living creature from dead matter, then abandons it; the lonely creature turns on its maker and his family.',
  'Dracula': 'Solicitor Jonathan Harker visits a Transylvanian count who turns out to be a vampire bound for England, where Van Helsing and friends hunt him down.',
  'A Tale of Two Cities': 'Families in London and Paris are swept up in the French Revolution, and the cynical Sydney Carton makes the ultimate sacrifice.',
  'Great Expectations': 'Orphan Pip rises from a forge to London society thanks to a secret benefactor, and learns hard lessons about snobbery and loyalty.',
  'A Christmas Carol': 'The miser Ebenezer Scrooge is visited by the ghost of his partner Marley and three spirits, and wakes on 25 December a changed man.',
  'Jane Eyre': 'A plain, principled orphan becomes governess at Thornfield Hall and falls for her employer, Mr Rochester, who is hiding a terrible secret.',
  'Wuthering Heights': 'The fierce love between the foundling Heathcliff and Catherine Earnshaw brings revenge and misery to two families on the Yorkshire moors.',
  'Treasure Island': 'Young Jim Hawkins finds a pirate map and sails with a crew that includes the charming, treacherous cook Long John Silver.',
  'The Hound of the Baskervilles': 'A famous Baker Street detective and Dr Watson investigate a legendary spectral dog said to haunt an old family on Dartmoor.',
  'The Picture of Dorian Gray': 'A beautiful young man stays youthful while his portrait records every sin he commits, growing ever more hideous.',
  'Adventures of Huckleberry Finn': 'Huck fakes his death to escape his father and rafts down the Mississippi with Jim, a man escaping slavery.',
  'Little Women': 'The four March sisters, Meg, Jo, Beth and Amy, grow up in New England while their father is away at the American Civil War.',
  'Peter Pan': 'The boy who will not grow up flies Wendy and her brothers to Neverland, home of the Lost Boys, fairies and Captain Hook.',
  'The Wonderful Wizard of Oz': 'A cyclone carries Dorothy from Kansas to a magical land, where she seeks a great ruler\'s help with a Scarecrow, a Tin Woodman and a Cowardly Lion.',
  'The Jungle Book': 'Stories of Indian forest animals, led by the tale of Mowgli, a boy raised by wolves and taught by Baloo the bear and Bagheera the panther.',
  'The War of the Worlds': 'Martians land in Surrey and lay waste to southern England with heat-rays and fighting machines until an unexpected enemy stops them.',
  'The Time Machine': 'A Victorian inventor travels hundreds of thousands of years into the future and finds humanity split into two strange species.',
  'Robinson Crusoe': 'A shipwrecked mariner survives for decades on a remote island, building a life from almost nothing and later rescuing a man he names Friday.',
  "Gulliver's Travels": 'A ship\'s surgeon voyages to lands of tiny people, giants, floating scientists and wise horses, in a satire of human folly.',
  'Don Quixote': 'An old Spanish gentleman, crazed by tales of chivalry, sets out as a knight with his squire Sancho Panza and mistakes windmills for giants.',
  'Les Misérables': 'Ex-convict Jean Valjean rebuilds his life and raises the orphan Cosette while being pursued for years by the relentless Inspector Javert.',
  'Anna Karenina': 'A married Russian aristocrat begins a passionate affair with Count Vronsky, while the landowner Levin searches for meaning in country life.',
  'Crime and Punishment': 'A desperate former student in Saint Petersburg kills a pawnbroker to prove a theory, then is tormented by guilt and a shrewd investigator.',
  'War and Peace': 'Several aristocratic Russian families live, love and fight through the Napoleonic Wars, including the 1812 invasion of Russia.',
  'The Count of Monte Cristo': 'Betrayed and imprisoned in an island fortress, sailor Edmond Dantès escapes, finds a hidden fortune and returns under a noble title to take revenge.',
  'Emma': 'A clever, wealthy young woman meddles in her neighbours\' love lives in the village of Highbury and misreads her own heart.',
  'Oliver Twist': 'An orphan escapes a cruel workhouse and falls in with Fagin\'s gang of child pickpockets in London.',
  'David Copperfield': 'A mistreated boy grows up to be a successful writer, meeting the hopeful Mr Micawber and the scheming Uriah Heep along the way.',
  'Heart of Darkness': 'Sailor Charles Marlow travels up the Congo River to find Kurtz, an ivory trader who has gone far beyond the bounds of civilisation.',
  'The Great Gatsby': 'Narrator Nick Carraway watches his mysterious Long Island neighbour throw lavish parties to win back his lost love, Daisy Buchanan.',
  'The Metamorphosis': 'Salesman Gregor Samsa wakes to find he has turned into a huge insect, and his family slowly comes to see him as a burden.',
  'The Secret Garden': 'Spoiled orphan Mary Lennox moves to a Yorkshire manor, finds a locked, forgotten walled plot and brings it, and her sickly cousin Colin, back to life.',
  'Black Beauty': 'A horse tells his own life story, from a happy youth through hard years with cruel and kind owners, in a plea for better treatment of horses.',
  'Anne of Green Gables': 'An imaginative red-haired orphan is sent by mistake to an elderly brother and sister on Prince Edward Island, and wins them over.',
  'The Wind in the Willows': 'Mole, Ratty, Badger and the reckless, car-mad Toad share adventures along the riverbank and win back Toad Hall from the weasels.',
  'The Call of the Wild': 'Buck, a pet dog stolen from California, is forced to pull sleds in the Yukon gold rush and gradually returns to his ancestral instincts.',
  'Around the World in Eighty Days': 'Precise Englishman Phileas Fogg bets he can circle the globe against the clock and races off with his valet Passepartout.',
  'Twenty Thousand Leagues Under the Seas': 'Professor Aronnax is captured by the mysterious Captain Nemo and tours the world\'s oceans aboard the submarine Nautilus.',
  'Strange Case of Dr Jekyll and Mr Hyde': 'A London lawyer investigates the link between his respectable friend, a doctor, and a brutal man who seems to have a hold over him.',
  'Winnie-the-Pooh': 'Gentle stories of a honey-loving bear and his friends Piglet, Eeyore, Owl, Rabbit and Christopher Robin in the Hundred Acre Wood.',
  'Kidnapped': 'Cheated of his inheritance by his uncle, David Balfour is seized and put on a ship, then escapes across the Scottish Highlands with the Jacobite Alan Breck.',
  'Sense and Sensibility': 'Sensible Elinor and passionate Marianne Dashwood face heartbreak and money worries after their father\'s death.',
  'Nineteen Eighty-Four': 'In a totalitarian state ruled by the Party and Big Brother, Winston Smith secretly rebels and falls in love, with terrible consequences.',
  'Animal Farm': 'The livestock of an English holding overthrow their human owner, but the pigs who lead them slowly become as tyrannical as the people they replaced.',
  'Brave New World': 'In a future World State, people are bred in hatcheries and kept happy with conditioning and drugs, until an outsider challenges it all.',
  'To Kill a Mockingbird': 'In a small Alabama town, young Scout Finch watches her father, the lawyer Atticus, defend a Black man falsely accused of a crime.',
  'The Catcher in the Rye': 'After being expelled from his school, teenager Holden Caulfield spends a few aimless, lonely days in New York City.',
  'The Hobbit': 'Home-loving Bilbo Baggins joins Gandalf and thirteen dwarves on a quest to reclaim their treasure from the dragon Smaug.',
  'The Lord of the Rings': 'The hobbit Frodo and the Fellowship set out to destroy the One Ring in the fires of Mount Doom before the Dark Lord Sauron can reclaim it.',
  'The Lion, the Witch and the Wardrobe': 'Four children step through a piece of furniture into Narnia, frozen by an evil queen\'s spell, and join Aslan to free it.',
  "Charlotte's Web": 'A clever spider saves her friend Wilbur the pig from slaughter by spelling out words in the threads she spins.',
  'The Cat in the Hat': 'On a rainy day, a mischievous cat in a tall hat turns two children\'s house upside down while their mother is out.',
  'Fahrenheit 451': 'In a future where books are banned, fireman Guy Montag burns them for a living until he starts to read them himself.',
  "Harry Potter and the Philosopher's Stone": 'On his eleventh birthday an orphan learns he is a wizard and goes to Hogwarts, where he uncovers a plot to steal an object that grants eternal life.',
  'The Hunger Games': 'In the nation of Panem, Katniss Everdeen takes her sister\'s place in a televised fight to the death between teenagers.',
  'The Very Hungry Caterpillar': 'A tiny larva eats through more and more food each day of the week, then builds a cocoon and emerges as a butterfly.',
  'Matilda': 'A brilliant girl with awful parents and a tyrannical headmistress discovers she has special powers and helps her kind teacher, Miss Honey.',
  'Charlie and the Chocolate Factory': 'A poor boy finds a golden ticket and joins four badly behaved children on a tour of Willy Wonka\'s magical sweet works.',
  'The BFG': 'An orphan named Sophie is carried off by a giant who turns out to be friendly, and together they stop the child-eating giants.',
  'The Little Prince': 'A pilot stranded in the Sahara meets a small boy from a tiny asteroid, who tells of his rose and the strange grown-ups he has met.',
  'Of Mice and Men': 'Two drifting ranch hands, quick George and strong, gentle Lennie, share a dream of their own farm during the Great Depression.',
  'The Grapes of Wrath': 'The Joad family loses its Oklahoma farm in the Dust Bowl and heads west to California, only to find poverty and exploitation.',
  'The Old Man and the Sea': 'An aging Cuban fisherman, Santiago, hooks a giant marlin far out at sea and fights for days to bring it home.',
  'Lord of the Flies': 'Schoolboys stranded on an island try to govern themselves, but their society quickly collapses into savagery.',
  'One Hundred Years of Solitude': 'The rise and fall of the Buendía family and their town of Macondo, told across generations in a style full of the magical and the everyday.',
  'Beloved': 'In post-Civil War Ohio, Sethe, who escaped slavery, is haunted by the ghost of the daughter she lost.',
  "The Handmaid's Tale": 'In the theocracy of Gilead, Offred is one of a class of women forced to bear children for powerful couples.',
  'The Da Vinci Code': 'Symbologist Robert Langdon and cryptologist Sophie Neveu follow clues in famous artworks after a murder in the Louvre.',
  "The Hitchhiker's Guide to the Galaxy": 'Seconds before Earth is demolished, Arthur Dent is rescued by his alien friend Ford Prefect and thrown into a comic tour of space.',
  'Gone with the Wind': 'Strong-willed Scarlett O\'Hara struggles to survive and keep her plantation through the American Civil War and Reconstruction.',
  'Things Fall Apart': 'Okonkwo, a respected but rigid leader in an Igbo village, sees his world unravel with the arrival of colonial rule and missionaries.',
  'The Diary of a Young Girl': 'The real diary of a Jewish teenager hiding with her family in a secret annex in Amsterdam during the Nazi occupation.',
  'Where the Wild Things Are': 'Sent to bed without supper, Max sails to an island of monsters, becomes their king, then sails home to find his supper waiting.',
  'The Gruffalo': 'A small mouse walking through the woods invents a fearsome monster to scare off hungry animals, then meets the monster for real.',
  'Diary of a Wimpy Kid': 'Middle-schooler Greg Heffley records his schemes, embarrassments and friendship with Rowley in an illustrated journal.',
  'Watership Down': 'Warned by the seer Fiver, a band of rabbits flee their doomed warren and fight to found a new home on the English hills.',
  'Life of Pi': 'After a shipwreck, a teenage boy from India drifts across the Pacific in a small boat with a Bengal tiger called Richard Parker.',
  'The Book Thief': 'In Nazi Germany, foster child Liesel Meminger steals books, learns to read and shares them while her family hides a Jewish man.',
  'Slaughterhouse-Five': 'Billy Pilgrim, an American prisoner of war who survives the bombing of Dresden, comes unstuck in time.',
  'Catch-22': 'Bombardier Yossarian tries every trick to avoid flying more missions in the Second World War, trapped by absurd military rules.',
  'Rebecca': 'A shy young bride arrives at the grand estate of Manderley and lives in the shadow of her husband\'s glamorous dead first wife.',
  'Murder on the Orient Express': 'Hercule Poirot investigates a passenger\'s killing on a snowbound luxury train, where every suspect seems to have an alibi.',
  'And Then There Were None': 'Ten strangers lured to an island are killed one by one, following the verses of a nursery rhyme.',
  'Dune': 'Young Paul Atreides moves with his family to the desert planet Arrakis, the only source of the precious spice, and becomes a leader of its people.',
  'Mary Poppins': 'A strict but magical nanny blows in on the east wind to look after the Banks children of Cherry Tree Lane.',
  'A Bear Called Paddington': 'A polite, marmalade-loving visitor from Peru is found at a London station by the Brown family, who take him home and name him after it.',
  'The Tiger Who Came to Tea': 'A hungry striped big cat turns up at Sophie\'s house in the afternoon and eats and drinks absolutely everything.',
};

// Author questions (DSL in c2_lib.parseQuestions). Facts checked against Wikipedia author articles.
export const AUTHOR_QS = `
mc|1|Which author created the detective Sherlock Holmes?|Arthur Conan Doyle|Agatha Christie;Charles Dickens;Edgar Allan Poe|Arthur Conan Doyle first wrote about Holmes in A Study in Scarlet (1887).
mc|1|Which author created the Belgian detective Hercule Poirot?|Agatha Christie|Arthur Conan Doyle;Dorothy L. Sayers;P. D. James|Poirot first appeared in The Mysterious Affair at Styles (1920).
mc|1|Who wrote the Harry Potter books?|J. K. Rowling|Roald Dahl;Philip Pullman;C. S. Lewis|The first book came out in 1997.
mc|1|Which author wrote Matilda, The BFG and The Twits?|Roald Dahl|Enid Blyton;David Walliams;Michael Morpurgo|Roald Dahl was born in Wales to Norwegian parents.
mc|1|Who wrote the Narnia books?|C. S. Lewis|J. R. R. Tolkien;Lewis Carroll;Philip Pullman|C. S. Lewis was a friend of Tolkien at Oxford.
mc|1|Who wrote The Cat in the Hat and Green Eggs and Ham?|Dr. Seuss|Maurice Sendak;Eric Carle;Shel Silverstein|Dr. Seuss was the pen name of Theodor Seuss Geisel.
mc|1|Which playwright wrote Romeo and Juliet and Hamlet?|William Shakespeare|Christopher Marlowe;Ben Jonson;Charles Dickens|Shakespeare was born in Stratford-upon-Avon in 1564.
tf|1|Lewis Carroll was a pen name.|true|Its owner's real name was Charles Lutwidge Dodgson.
mc|2|Mary Ann Evans wrote Middlemarch under which pen name?|George Eliot|George Sand;Currer Bell;Acton Bell|She used a man's name so her work would be taken seriously.
mc|2|What was Mark Twain's real name?|Samuel Clemens|Samuel Johnson;Walt Whitman;Henry James|Mark Twain is a riverboat term for water two fathoms deep.
mc|2|What was George Orwell's real name?|Eric Arthur Blair|Eric Hobsbawm;Arthur Miller;Evelyn Waugh|He took the name Orwell from a river in Suffolk.
mc|2|The Brontë sisters first published under which surname?|Bell|Brown;Bennet;Blythe|Charlotte, Emily and Anne wrote as Currer, Ellis and Acton Bell.
mc|2|Which author created the Discworld series?|Terry Pratchett|Douglas Adams;Neil Gaiman;Terry Jones|The first Discworld novel, The Colour of Magic, came out in 1983.
mc|2|Which author wrote Oliver Twist, Great Expectations and A Christmas Carol?|Charles Dickens|Thomas Hardy;William Thackeray;Anthony Trollope|Dickens also published most of his novels in monthly or weekly parts.
mc|2|Which author wrote both Emma and Pride and Prejudice?|Jane Austen|Charlotte Brontë;Elizabeth Gaskell;Mary Shelley|Jane Austen's novels were first published anonymously.
mc|2|Which author wrote Treasure Island and Kidnapped?|Robert Louis Stevenson|Walter Scott;Rudyard Kipling;Jules Verne|Stevenson was born in Edinburgh.
mc|2|Who wrote The Lord of the Rings?|J. R. R. Tolkien|C. S. Lewis;Terry Pratchett;George R. R. Martin|Tolkien was a professor of Old English at Oxford.
mc|2|Which author wrote War and Peace and Anna Karenina?|Leo Tolstoy|Fyodor Dostoevsky;Anton Chekhov;Ivan Turgenev|Tolstoy wrote in Russian.
mc|2|Which French author wrote Around the World in Eighty Days?|Jules Verne|Victor Hugo;Alexandre Dumas;Gustave Flaubert|Verne also wrote Journey to the Centre of the Earth.
mc|2|Which author wrote Les Misérables and The Hunchback of Notre-Dame?|Victor Hugo|Alexandre Dumas;Émile Zola;Honoré de Balzac|Hugo's original French title for the second is Notre-Dame de Paris.
mc|2|Which American author wrote The Old Man and the Sea?|Ernest Hemingway|John Steinbeck;F. Scott Fitzgerald;William Faulkner|Hemingway won the Nobel Prize in Literature in 1954.
mc|2|Which author wrote Murder on the Orient Express?|Agatha Christie|Ruth Rendell;Arthur Conan Doyle;Ngaio Marsh|Agatha Christie is the best-selling fiction writer of all time, according to Guinness World Records.
mc|3|Which poet wrote The Raven?|Edgar Allan Poe|Walt Whitman;Henry Wadsworth Longfellow;Emily Dickinson|The Raven was published in 1845.
mc|3|Which author's first published novel was Sense and Sensibility (1811)?|Jane Austen|Mary Shelley;Maria Edgeworth;Fanny Burney|It was credited only to "A Lady".
mc|3|Which Nigerian author wrote Things Fall Apart?|Chinua Achebe|Wole Soyinka;Ben Okri;Chimamanda Ngozi Adichie|Things Fall Apart was published in 1958.
mc|3|Which Colombian author wrote One Hundred Years of Solitude?|Gabriel García Márquez|Jorge Luis Borges;Isabel Allende;Mario Vargas Llosa|García Márquez won the Nobel Prize in Literature in 1982.
mc|3|Which author was the first woman to win the Nobel Prize in Literature, in 1909?|Selma Lagerlöf|Pearl S. Buck;Grazia Deledda;Sigrid Undset|The Swedish author wrote The Wonderful Adventures of Nils.
mc|3|Which author wrote the poem If— and the Just So Stories?|Rudyard Kipling|Robert Louis Stevenson;Thomas Hardy;Alfred Tennyson|Kipling won the Nobel Prize in Literature in 1907.
tf|2|Charles Dickens worked in a boot-blacking factory as a child.|true|He was sent to work there at the age of twelve while his father was in a debtors' prison.
tf|2|J. R. R. Tolkien and C. S. Lewis were friends and colleagues at Oxford.|true|Both belonged to an informal literary group called the Inklings.
tf|3|Mary Shelley was a teenager when she began writing Frankenstein.|true|She started it in 1816, aged 18, during a ghost-story contest with Lord Byron and others.
tf|2|Roald Dahl was a fighter pilot in the Second World War.|true|He flew with the Royal Air Force before becoming a writer.
`;
