// Film details keyed by the exact title used in the Wikipedia box-office tables.
// title | kids (1 = family/animated) | difficulty | emoji plot | quote (verified on Wikiquote by the builder, else dropped) | clues hardest->easiest (;)
// Year, gross and director come from Wikipedia/Wikidata at build time.
export const FILMS = `
Jaws|0|1|🦈🏖️👮‍♂️🚤|You're gonna need a bigger boat.|Its mechanical star was nicknamed Bruce by the crew;It is often called the first summer blockbuster;A police chief, a scientist and a fisherman go hunting;A great white shark terrorises a seaside holiday town
Rocky|0|2|🥊🐔🏃‍♂️🏆|Yo, Adrian!|Its star also wrote the screenplay;Its hero trains by punching sides of beef in a meat locker;A famous scene has him running up museum steps in Philadelphia;A small-time boxer gets a shot at the world heavyweight title
Star Wars|1|1|🚀👦🤖⚔️💥|May the Force be with you.|It was later retitled Episode IV – A New Hope;A farm boy on a desert planet finds a message hidden in a droid;A princess, a smuggler and a Wookiee help destroy a planet-sized battle station;Luke Skywalker joins the fight against Darth Vader
Grease|0|2|🚗💃🏫🎤❤️|Tell me about it, stud.|It is based on a 1971 stage musical;Its songs include You're the One That I Want;It is set at Rydell High in the 1950s;Danny and Sandy fall in love over a summer
Moonraker|0|3|🕵️‍♂️🚀🌌🛰️|I think he's attempting re-entry, sir.|A henchman with steel teeth falls in love in this film;Its villain plans to wipe out humanity from a space station;Its climax takes place in orbit;Roger Moore's James Bond goes to space
The Empire Strikes Back|1|1|❄️🤖🧙‍♂️✋👨‍👦|No, I am your father.|It opens on the ice planet Hoth;A small green Jedi master trains the hero in a swamp;Han Solo is frozen in carbonite;It is the second Star Wars film
Raiders of the Lost Ark|0|2|🤠🐍🏺💀|Snakes. Why'd it have to be snakes?|Its hero is a college professor;It opens with the hero fleeing a giant rolling boulder;Nazis race to find the Ark of the Covenant;It introduces Indiana Jones
E.T. the Extra-Terrestrial|1|1|👽🚲🌕📞🌱|Be good.|A boy lures his new friend with a trail of sweets;Its alien friend gets drunk while the boy is at school;A boy flies his bicycle across the face of the moon;A boy befriends a stranded alien who wants to go home
Return of the Jedi|1|2|🐻🌲⚔️👴💥|It's a trap!|A crime lord named Jabba keeps the hero's friend frozen;Small furry Ewoks help defeat the Empire;Luke faces Darth Vader in front of the Emperor;It is the third Star Wars film
Ghostbusters|0|1|👻🔫🏢🍬|Don't cross the streams.|A giant marshmallow man attacks New York;Its theme song asks who you're gonna call;Its heroes drive a converted ambulance called Ecto-1;Three scientists start a ghost-catching business
Back to the Future|1|1|🚗⚡⏰👩‍👦🎸|Roads? Where we're going, we don't need roads.|Its time machine needs 1.21 gigawatts;A teenager must make sure his parents fall in love;Its time machine is a DeLorean car;Marty McFly travels back to 1955
Top Gun|0|2|✈️😎🏐🏆|I feel the need... the need for speed!|Its soundtrack includes Take My Breath Away;Its pilots play beach volleyball;Its hero's call sign is Maverick;Navy pilots compete at an elite flight school
Fatal Attraction|0|3|💑🔪🐰🏠|I'm not gonna be ignored, Dan!|It gave the phrase bunny boiler to the language;Glenn Close plays a woman who will not let go;A married man's weekend affair turns dangerous;Michael Douglas stars as a New York lawyer
Rain Man|0|3|🚗👬🃏✈️|I'm an excellent driver.|It won the Academy Award for Best Picture;One brother counts cards in Las Vegas;Tom Cruise plays a car dealer who discovers he has an older brother;Dustin Hoffman plays an autistic savant
Indiana Jones and the Last Crusade|0|2|🤠👴🏆✝️|X never, ever marks the spot.|River Phoenix plays the hero as a teenager;Sean Connery plays the hero's father;The heroes search for the Holy Grail;It is the third film about the whip-cracking archaeologist
Ghost|0|3|👻💑🏺🔮||Whoopi Goldberg won an Oscar for playing a fake psychic;A famous pottery-wheel scene uses the song Unchained Melody;A murdered banker tries to protect his girlfriend;Patrick Swayze and Demi Moore star
Terminator 2: Judgment Day|0|2|🤖🏍️👦🔥🕶️|Hasta la vista, baby.|Its villain is made of liquid metal;Its hero rides a motorbike holding a shotgun;A cyborg is sent back in time to protect a boy;Arnold Schwarzenegger plays a reprogrammed Terminator
Aladdin|1|1|🧞‍♂️🪔🐒🕌🧙‍♂️|Phenomenal cosmic powers! Itty-bitty living space.|Robin Williams voiced the scene-stealing magic helper;A parrot named Iago helps the villain;Its songs include A Whole New World;A street boy finds a magic lamp
Jurassic Park|0|1|🦖🦕🏝️🧬🚙|Life, uh, finds a way.|Mosquitoes trapped in amber provide the DNA;A glass of water ripples as something big approaches;Velociraptors stalk two children in a kitchen;Dinosaurs are brought back to life on an island theme park
The Lion King|1|1|🦁👑🐗🦍🌅|Remember who you are.|Its villain is the hero's uncle, Scar;A meerkat and a warthog teach the hero to say no worries;A lion cub runs away after his father dies;Simba must become king of the Pride Lands
Toy Story|1|1|🤠🚀🧸👦|To infinity and beyond!|It was the first feature film made entirely with computer animation;A boy named Andy owns the toys;A cowboy doll is jealous of a new space ranger toy;Woody and Buzz Lightyear are its heroes
Independence Day|0|2|👽🛸🇺🇸💥🎆|Welcome to Earth!|A computer virus is uploaded to the alien mothership;The US President flies a fighter jet into battle;Giant flying saucers destroy famous landmarks;Will Smith fights an alien invasion on the 4th of July
Titanic|0|1|🚢🧊💑🎨💎|I'm the king of the world!|It won 11 Academy Awards;A priceless blue diamond necklace is at the heart of its story;A poor artist and a rich young woman fall in love at sea;It is about a ship that sank in 1912
Armageddon|0|3|☄️👷‍♂️🚀💥🌍||Oil drillers are trained as astronauts;Its theme song is I Don't Want to Miss a Thing by Aerosmith;An asteroid the size of Texas is heading for Earth;Bruce Willis leads a crew to blow up an asteroid
Star Wars: Episode I – The Phantom Menace|1|2|👦🏎️⚔️🐸👑|Now this is podracing!|A clumsy Gungan named Jar Jar Binks joins the heroes;Young Anakin Skywalker wins a podrace;Darth Maul fights with a double-bladed lightsaber;It is the first of the Star Wars prequels
Mission: Impossible 2|0|3|🕵️‍♂️🦠🏍️🧗‍♂️||Its villain steals a deadly virus and its cure;Its hero free-climbs a cliff in its opening;It was directed by John Woo;Tom Cruise returns as agent Ethan Hunt
Harry Potter and the Philosopher's Stone|1|1|⚡🧙‍♂️🦉🏰🧹|It does not do to dwell on dreams|In the US it was called the Sorcerer's Stone;A giant three-headed dog guards a trapdoor;An orphan boy learns he is a wizard on his eleventh birthday;Harry goes to Hogwarts for the first time
The Lord of the Rings: The Two Towers|0|2|🧙‍♂️🌳🏰⚔️💍|Po-tay-toes! Boil 'em, mash 'em, stick 'em in a stew.|Talking tree creatures called Ents march to war;Its climax is the Battle of Helm's Deep;Gollum guides two hobbits towards Mordor;It is the second part of a fantasy trilogy about a ring
The Lord of the Rings: The Return of the King|0|2|💍🌋👑🦅⚔️||It won all 11 Academy Awards it was nominated for;A giant spider called Shelob attacks Frodo;Aragorn becomes king;The One Ring is finally thrown into Mount Doom
Shrek 2|1|1|👹👸🐴🐱🏰|Are we there yet?|A cat in boots tries to assassinate the hero;The hero visits his wife's parents in the kingdom of Far Far Away;A Fairy Godmother plots against the couple;An ogre and Princess Fiona go to meet her parents
Harry Potter and the Goblet of Fire|0|2|🔥🏆🐉🧙‍♂️🌊|Dark and difficult times lie ahead.|Its tasks include an underwater rescue and a hedge maze;A dragon guards a golden egg;A magical cup picks champions for the Triwizard Tournament;It is the fourth film about the boy wizard
Pirates of the Caribbean: Dead Man's Chest|0|2|🏴‍☠️🐙💀📦🦑|I've got a jar of dirt!|A giant sea monster called the Kraken attacks ships;Its villain has a beard of tentacles;Characters search for the chest holding Davy Jones's heart;Captain Jack Sparrow owes a debt to Davy Jones
Pirates of the Caribbean: At World's End|0|3|🏴‍☠️🌍⚓🦀🌀||Its heroes sail off the edge of the world to rescue a friend;Chow Yun-fat plays a pirate lord from Singapore;Keith Richards appears as Jack Sparrow's father;It is the third film about Captain Jack Sparrow
The Dark Knight|0|2|🦇🃏🔥🏙️🚓|Why so serious?|Heath Ledger won a posthumous Oscar for it;A district attorney becomes the villain Two-Face;A villain in clown make-up tries to bring chaos to Gotham;Christian Bale plays Batman
Avatar|0|1|🌳💙👽🐉🪐|I see you.|Its hero is a paralysed former marine;A precious mineral called unobtanium is mined there;Humans use remote bodies to live among the blue Na'vi;It is set on the moon Pandora
Toy Story 3|1|1|🧸🏫🔥👋🤠|So long, partner.|Its villain is a strawberry-scented teddy bear;The toys end up in a daycare centre;Andy leaves home for college;Woody, Buzz and friends face being thrown away
Harry Potter and the Deathly Hallows – Part 2|0|2|⚡🏰⚔️🐍💀||The Battle of Hogwarts is its climax;A dragon escapes from Gringotts bank;Snape's secret is finally revealed;It is the final film in the boy wizard series
The Avengers|0|1|🦸‍♂️🛡️🔨👽🏙️|Puny god.|Its villain is Thor's brother Loki;Aliens invade New York through a portal;Nick Fury brings a team of heroes together;Iron Man, Captain America, Thor and Hulk team up
Frozen|1|1|❄️👭⛄🏰👑|Some people are worth melting for.|A reindeer named Sven helps the heroes;Its big song is Let It Go;A queen with icy powers runs away to the mountains;Elsa and Anna are sisters in the kingdom of Arendelle
Transformers: Age of Extinction|0|3|🤖🚗🦖🔧||Robot dinosaurs called Dinobots join the fight;Mark Wahlberg plays an inventor who finds a truck;Its hero robot transforms into a truck;Optimus Prime leads the Autobots
Star Wars: The Force Awakens|0|1|🌌🤖⚽🪐⚔️|Chewie, we're home.|A rolling droid called BB-8 carries a map;A scavenger named Rey lives on a desert planet;Han Solo returns after more than 30 years;It is the seventh main Star Wars film
Captain America: Civil War|0|2|🛡️🆚🤖🕷️||Spider-Man and Black Panther join the Marvel films here;Heroes argue over government control of their powers;Two teams of Avengers fight at an airport;Captain America and Iron Man turn against each other
Star Wars: The Last Jedi|0|2|⚔️🏝️🐧👴🔥|This is not going to go the way you think.|Small bird-like creatures called porgs appear;Luke Skywalker lives in exile on an island;Rey asks Luke to train her;It is the eighth main Star Wars film
Avengers: Infinity War|0|1|🟣🧤💎💎🫰|Perfectly balanced, as all things should be.|Its villain wants to wipe out half of all life;Its ending turns many heroes to dust;Thanos collects the Infinity Stones;Nearly every Marvel hero teams up against Thanos
Avengers: Endgame|0|1|⏳🦸‍♀️🧤🫰🛡️|I love you 3000.|Its heroes travel through time to collect the Infinity Stones;It was briefly the highest-grossing film of all time;It was the 22nd film in the Marvel Cinematic Universe;The surviving Avengers try to undo Thanos's snap
Demon Slayer: Kimetsu no Yaiba – The Movie: Mugen Train|0|3|🚂👹🗡️🔥🌙||It is a Japanese anime film;It continues a hit TV series;Its heroes fight a demon on a train;Tanjiro and the Flame Hashira face Enmu
Spider-Man: No Way Home|0|1|🕷️🪄🕸️🌀||A spell from Doctor Strange goes wrong;Villains from earlier Spider-Man films return;Three Spider-Men from different worlds team up;Tom Holland's Peter Parker faces the multiverse
Avatar: The Way of Water|0|2|🌊🐋💙👨‍👩‍👧‍👦🏝️||Much of it was filmed using new underwater motion capture;Its whale-like creatures are called tulkun;A family hides with ocean-dwelling clans;It is the second film set on Pandora
Barbie|0|1|💗👠🏖️🌎🎸||Its stereotypical heroine starts thinking about death;Ryan Gosling sings I'm Just Ken;A doll travels from her perfect world to the real world;Margot Robbie plays a famous fashion doll
Inside Out 2|1|1|😊😢😠😰🧠||It introduces Anxiety, Envy, Ennui and Embarrassment;Its heroine goes to an ice hockey camp;Its story takes place inside a teenager's mind;Joy and her friends meet new emotions as Riley turns 13
Ne Zha 2|0|2|🔥👦🐉🪷🇨🇳||It is the highest-grossing animated film of all time;It was the first film from outside Hollywood to earn over 2 billion dollars;It is a Chinese animated film based on mythology;Its hero is a mischievous boy deity with fire powers
Superman|1|2|🦸‍♂️🌍👓📰🚁|You've got me? Who's got you?|Marlon Brando plays the hero's father on Krypton;Its villain is Lex Luthor;Its tagline promised you'll believe a man can fly;Christopher Reeve plays the Man of Steel
The Godfather|0|2|🌹🍊🐴🔫👨‍👦|I'm gonna make him an offer he can't refuse.|A film producer wakes up with a horse's head in his bed;Marlon Brando plays the head of a crime family;Al Pacino plays the youngest son, Michael;It follows the Corleone mafia family
Smokey and the Bandit|0|3|🚚🍺🚓🐶||Its hero drives a black Pontiac Trans Am;A truck is hauling illegal beer across state lines;A sheriff chases the hero across the South;Burt Reynolds plays the Bandit
Animal House|0|3|🎓🍻🏛️🎉|Toga! Toga!|John Belushi plays Bluto;Its rowdy students throw a toga party;A college dean tries to shut down a fraternity;It is a comedy about the Delta house
Close Encounters of the Third Kind|0|3|🛸⛰️🎹👽|This means something. This is important.|A man sculpts a mountain out of mashed potatoes;Humans and aliens talk using a five-note tune;People are drawn to Devils Tower in Wyoming;It is about first contact with aliens
Kramer vs. Kramer|0|3|👨‍👦🍳⚖️💔||It won the Academy Award for Best Picture;A father learns to make French toast for his son;Dustin Hoffman and Meryl Streep star;A divorced couple fight for custody of their son
Enter the Dragon|0|3|🥋🏝️🪞🐉|Don't think. Feel.|Its climax takes place in a hall of mirrors;Its hero enters a martial arts tournament on an island;It was released shortly after its star's death;Bruce Lee stars as a Shaolin martial artist
Batman|0|2|🦇🃏🎨🏙️|Have you ever danced with the devil in the pale moonlight?|Prince wrote songs for its soundtrack;Jack Nicholson plays the Joker;Michael Keaton plays the hero;A masked vigilante protects Gotham City
Indiana Jones and the Temple of Doom|0|3|🤠💎🐍⛏️🔥|Fortune and glory, kid.|The hero's sidekick is a boy called Short Round;A mine-cart chase races through tunnels;Stolen sacred stones are found in an Indian palace;It is the second film about the archaeologist with a whip
Forrest Gump|0|2|🏃‍♂️🍫🪶🏓🦐|Life was like a box of chocolates.|Its hero becomes a shrimp boat captain;Its hero meets several US presidents;Its hero runs across America for over three years;Tom Hanks plays a kind man from Alabama
The Sixth Sense|0|3|👦👻🩺❄️|I see dead people.|Its twist ending made it famous;A child psychologist tries to help a frightened boy;A boy says he can see ghosts;Bruce Willis stars with Haley Joel Osment
The Lost World: Jurassic Park|0|3|🦖🏝️🚐🏙️||A Tyrannosaurus rampages through San Diego;Its heroes visit a second island of dinosaurs;Jeff Goldblum returns as Ian Malcolm;It is the sequel to a 1993 dinosaur film
Men in Black|0|2|🕶️👽🔫🗽||Its agents erase people's memories with a flashing device;A talking pug works with the agents;Agents J and K police aliens living on Earth;Will Smith and Tommy Lee Jones wear black suits
Harry Potter and the Order of the Phoenix|0|2|⚡🦅🏫📜🧙‍♀️||A pink-loving teacher, Dolores Umbridge, takes over the school;Students form a secret group called Dumbledore's Army;Its climax is a battle in the Ministry of Magic;It is the fifth film about the boy wizard
Harry Potter and the Half-Blood Prince|0|2|⚡📕🧪🏰||A mysterious potions book helps the hero;Its characters hunt for memories of the young Voldemort;It ends with the death of the headmaster;It is the sixth film about the boy wizard
Jurassic World|0|2|🦖🏝️🏍️🦕||A genetically engineered dinosaur called Indominus rex escapes;Chris Pratt trains a pack of velociraptors;A dinosaur theme park is finally open to the public;It is set 22 years after the first park film
The Lion King (2019)|1|1|🦁👑🐗🌅💻||Beyoncé voices Nala;Donald Glover voices the hero;It uses photorealistic computer animation;It is a remake of a 1994 animated film about a lion cub
Furious 7|0|2|🚗🪂🏙️🏎️|I don't have friends. I got family.|Cars parachute out of a plane;A supercar jumps between skyscrapers in Abu Dhabi;It was Paul Walker's final film;Dom Toretto's crew are hunted by a vengeful assassin
Frozen II|1|1|❄️🍂🌊🐴👭|Some things never change.|Elsa follows a mysterious voice into an enchanted forest;Its songs include Into the Unknown;A water spirit appears as a horse;Elsa, Anna, Olaf and Kristoff journey north
Avengers: Age of Ultron|0|2|🤖🦸‍♂️🏙️🌋||Twins with super speed and magic join the story;Tony Stark creates an artificial intelligence that goes rogue;A whole city is lifted into the sky;The Avengers fight the robot Ultron
Black Panther|0|2|🐆👑💎🌍|Wakanda forever!|A metal called vibranium makes its country rich;Its villain is Erik Killmonger;A prince returns home to become king;T'Challa rules the hidden African nation of Wakanda
Top Gun: Maverick|0|2|✈️😎🏈🎯|It's not the plane, it's the pilot.|Its pilots play football on the beach;Its mission is to destroy an enemy uranium plant;An ace pilot returns to train young flyers;Tom Cruise returns as Pete Mitchell more than 30 years later
Zootopia 2|1|1|🐰🦊🐍🚓🏙️||It is a sequel to a 2016 Disney animated film;A snake causes a stir in the city;A rabbit police officer and her fox partner return;Judy Hopps and Nick Wilde take on a new case
Avatar: Fire and Ash|0|3|🔥💙🌋🌊🐉||It introduces a fierce Na'vi clan known as the Ash People;Jake and Neytiri's family is still mourning a son;It is the third film set on Pandora;It is a sequel to The Way of Water
The Super Mario Bros. Movie|1|1|🍄🧱🐢👑🏎️||Jack Black voices the villain and sings Peaches;Its heroes are plumbers from Brooklyn;Princess Peach rules the Mushroom Kingdom;Mario and Luigi fall into a world of mushrooms and Bowser
Deadpool & Wolverine|0|3|🗡️🐺🦸‍♂️🌀||A dog version of its hero appears;Its hero is recruited by the Time Variance Authority;Hugh Jackman returns as a clawed mutant;A wisecracking mercenary teams up with Wolverine
`;
