// Landmarks: Wikipedia title | display name | ISO3 | kind | built year ('' if none/fuzzy) | alt names (;) | clues hardest->easiest (;)
// Built years are cross-checked against Wikidata inception/opening dates by the builder; mismatches are dropped.
export const LANDMARKS = `
Eiffel Tower|Eiffel Tower|FRA|tower|1889||Built as the entrance arch for a world's fair;The engineer whose company built it also designed the internal frame of the Statue of Liberty;It is made of wrought iron and was once the tallest structure in the world;It was completed in 1889;It stands on the Champ de Mars in Paris
Statue of Liberty|Statue of Liberty|USA|statue|1886|Lady Liberty|It was a gift from France;Its copper skin has turned green over time;It holds a torch in its raised right hand;It stands on an island in New York Harbor
Great Wall of China|Great Wall of China|CHN|ancient||Great Wall|Parts of it date back more than 2,000 years;Much of the best-known section was built under the Ming dynasty;Its total length with all branches is over 20,000 km;It was built to protect against raids from the northern steppe;It snakes across northern China
Taj Mahal|Taj Mahal|IND|religious|||Its building was ordered by the emperor Shah Jahan;It is a mausoleum for his wife Mumtaz Mahal;It is made of white marble;It stands on the bank of the Yamuna river in Agra
Colosseum|Colosseum|ITA|ancient||Coliseum;Flavian Amphitheatre|It was opened under the emperor Titus;It could seat around 50,000 spectators;Gladiators fought here;It is a huge oval amphitheatre in the centre of Rome
Machu Picchu|Machu Picchu|PER|ancient|||It was brought to international attention by Hiram Bingham in 1911;It was built for the emperor Pachacuti;It sits on a mountain ridge above the Urubamba valley;It is a 15th-century Inca citadel in the Andes
Christ the Redeemer (statue)|Christ the Redeemer|BRA|statue|1931|Cristo Redentor|It was made of reinforced concrete and soapstone;It was completed in 1931;It stands about 30 metres tall with its arms outstretched;It looks over Rio de Janeiro from Corcovado mountain
Petra|Petra|JOR|ancient||Rose City|It was the capital of the Nabataean kingdom;It is reached through a narrow gorge called the Siq;Its most famous facade is the Treasury, carved into rock;It is called the Rose City for the colour of its stone
Great Pyramid of Giza|Great Pyramid of Giza|EGY|ancient||Pyramid of Khufu;Pyramid of Cheops|It is the only one of the Seven Wonders of the Ancient World still largely intact;It was built for the pharaoh Khufu;For about 3,800 years it was the tallest human-made structure;It is the largest of the three pyramids on the plateau outside Cairo
Sydney Opera House|Sydney Opera House|AUS|building|1973||Its Danish architect, Jørn Utzon, left the project before it was finished;It opened in 1973;Its roof is made of shells covered in white tiles;It sits on Bennelong Point in Sydney Harbour
Big Ben|Big Ben|GBR|tower|1859|Elizabeth Tower|Its tower was renamed Elizabeth Tower in 2012;Its name strictly belongs to the great bell inside;Its clock has four faces;It is at the north end of the Palace of Westminster in London
Stonehenge|Stonehenge|GBR|ancient|||Some of its smaller stones were brought from the Preseli Hills in Wales;Its stones line up with the sunrise at the summer solstice;It is a prehistoric ring of standing stones;It stands on Salisbury Plain in England
Leaning Tower of Pisa|Leaning Tower of Pisa|ITA|tower||Tower of Pisa|It is the bell tower of a cathedral;Its lean began during construction in the 12th century because of soft ground;Engineers reduced its tilt in a project that ended in 2001;It is a famously tilting white marble tower in Tuscany
Sagrada Família|Sagrada Família|ESP|religious||Sagrada Familia|Construction began in 1882 and has lasted well over a century;Its main architect is buried in its crypt;It was designed by Antoni Gaudí;It is a giant basilica in Barcelona
Parthenon|Parthenon|GRC|ancient|||It was dedicated to the goddess Athena;Some of its sculptures are in the British Museum;It was completed in the 5th century BC;It is a marble temple on the Acropolis of Athens
Angkor Wat|Angkor Wat|KHM|religious|||It was built in the early 12th century by King Suryavarman II;It was first dedicated to the Hindu god Vishnu;It appears on its country's national flag;It is a vast temple complex near Siem Reap
Mount Fuji|Mount Fuji|JPN|natural||Fuji;Fujisan|It last erupted in 1707;It is 3,776 metres tall;It is an active volcano famous for its snow-capped cone;It is the highest mountain in Japan
Burj Khalifa|Burj Khalifa|ARE|tower|2010||It opened in 2010;It is 828 metres tall;It became the world's tallest building when it opened;It towers over downtown Dubai
Golden Gate Bridge|Golden Gate Bridge|USA|bridge|1937||It opened in 1937;Its colour is called International Orange;It is a suspension bridge;It spans the strait at the entrance to San Francisco Bay
Saint Basil's Cathedral|Saint Basil's Cathedral|RUS|religious|1561|St Basil's Cathedral|It was ordered by Ivan the Terrible;It was completed in 1561;It is famous for its colourful onion domes;It stands on Red Square in Moscow
Neuschwanstein Castle|Neuschwanstein Castle|DEU|castle||Neuschwanstein|It was built for King Ludwig II;It was started in 1869;It is said to have inspired a famous Disney castle;It is a fairy-tale castle in the Bavarian Alps
Brandenburg Gate|Brandenburg Gate|DEU|monument|1791||It is topped by a chariot pulled by four horses;It was completed in 1791;It stood beside the Berlin Wall during the Cold War;It is a neoclassical gate in the centre of Berlin
Chichen Itza|Chichen Itza|MEX|ancient||Chichén Itzá|Its great pyramid is known as El Castillo;At the equinoxes a shadow like a serpent appears on the pyramid's steps;It was a large Maya city;It is on the Yucatán Peninsula
Moai|Moai of Easter Island|CHL|ancient||Moai;Easter Island heads;Easter Island statues|Most of them were carved from volcanic tuff at the Rano Raraku quarry;They were carved by the Rapa Nui people;There are almost a thousand of them;They are giant stone figures with oversized heads on Easter Island
Grand Canyon|Grand Canyon|USA|natural|||It is up to about 1,800 metres deep;Its rocks record nearly two billion years of geological history;It was carved by the Colorado River;It is a huge gorge in Arizona
Uluru|Uluru|AUS|natural||Ayers Rock|Climbing it was banned in 2019;It is sacred to the Aṉangu people;It is a huge sandstone rock that glows red at sunset;It stands in the desert of Australia's Northern Territory
Table Mountain|Table Mountain|ZAF|natural|||A cable car has run to its top since 1929;Its cloud cover is called the tablecloth;It has a flat top about 3 km across;It overlooks Cape Town
Mount Kilimanjaro|Mount Kilimanjaro|TZA|natural||Kilimanjaro|Its highest point is Uhuru Peak;It is a dormant volcano with three cones;At 5,895 metres it is the highest mountain in Africa;It rises above the plains of northern Tanzania
Hagia Sophia|Hagia Sophia|TUR|religious|537|Ayasofya|It was completed in 537 under the emperor Justinian;It was a church, then a mosque, then a museum, and is a mosque again;Its huge dome was an engineering marvel;It stands in Istanbul
Sultan Ahmed Mosque|Blue Mosque|TUR|religious|1616|Sultan Ahmed Mosque|It was completed in 1616;It has six minarets;Its nickname comes from the blue tiles inside;It faces Hagia Sophia in Istanbul
Tower Bridge|Tower Bridge|GBR|bridge|1894||It opened in 1894;Its road deck lifts to let tall ships pass;It has two Gothic towers linked by high walkways;It crosses the River Thames in London
Notre-Dame de Paris|Notre-Dame de Paris|FRA|religious||Notre-Dame Cathedral;Notre Dame|A fire destroyed its roof and spire in 2019;It reopened in December 2024;Victor Hugo set a famous novel about a bell-ringer here;It is a Gothic cathedral on the Île de la Cité
Louvre Pyramid|Louvre Pyramid|FRA|building|1989||It was designed by I. M. Pei;It opened in 1989;It is made of glass and metal;It is the main entrance to the world's most-visited art museum in Paris
Mont-Saint-Michel|Mont-Saint-Michel|FRA|religious||Mont Saint-Michel|Its tides are among the strongest in Europe;An abbey sits at its peak;It becomes an island at high tide;It is a rocky tidal island in Normandy
Arc de Triomphe|Arc de Triomphe|FRA|monument|1836||It was ordered by Napoleon after the Battle of Austerlitz;It was completed in 1836;The Tomb of the Unknown Soldier lies beneath it;Twelve avenues radiate from it at the top of the Champs-Élysées
Alhambra|Alhambra|ESP|castle|||Its name means the red one in Arabic;It was the palace of the Nasrid emirs;Its Court of the Lions is famous;It is a Moorish palace and fortress in Granada
Trevi Fountain|Trevi Fountain|ITA|monument|1762|Fontana di Trevi|It was completed in 1762;Its centre shows the sea god Oceanus;Tradition says throwing a coin in means you will return;It is the largest Baroque fountain in Rome
St. Peter's Basilica|St. Peter's Basilica|VAT|religious|1626|Saint Peter's Basilica|Michelangelo designed its dome;It was consecrated in 1626;It is one of the largest churches in the world;It stands in Vatican City
Atomium|Atomium|BEL|monument|1958||It was built for the 1958 world's fair;It represents an iron crystal magnified 165 billion times;It is made of nine linked steel spheres;It stands in Brussels
The Little Mermaid (statue)|The Little Mermaid|DNK|statue|1913|Little Mermaid|It was unveiled in 1913;It has been beheaded by vandals more than once;It is based on a fairy tale by Hans Christian Andersen;It sits on a rock by the waterside in Copenhagen
CN Tower|CN Tower|CAN|tower|1976||It opened in 1976;It has a glass floor and an outdoor edge walk;It was the world's tallest free-standing structure for over 30 years;It is a communications tower in Toronto
Empire State Building|Empire State Building|USA|tower|1931||It was finished in 1931 after just over a year of building;A giant ape climbs it in a 1933 film;It was the world's tallest building for nearly 40 years;It is an Art Deco skyscraper in Manhattan
Mount Rushmore|Mount Rushmore|USA|monument|1941||It was finished in 1941;Its sculptor was Gutzon Borglum;Each carved face is about 18 metres tall;It shows four US presidents carved into a mountain in South Dakota
Petronas Towers|Petronas Towers|MYS|tower|||They were the world's tallest buildings from 1998 to 2004;A sky bridge joins them on the 41st and 42nd floors;Their floor plan is based on an eight-pointed star;They are twin skyscrapers in Kuala Lumpur
Marina Bay Sands|Marina Bay Sands|SGP|building|2010||It opened in 2010;It has a huge infinity pool on its roof;Its three hotel towers are joined by a giant platform that looks like a ship;It overlooks Marina Bay in Singapore
Forbidden City|Forbidden City|CHN|castle|1420|Palace Museum|It was completed in 1420;It was home to 24 emperors of the Ming and Qing dynasties;It is now the Palace Museum;It is a vast palace complex in the heart of Beijing
Terracotta Army|Terracotta Army|CHN|ancient||Terracotta Warriors|It was discovered by farmers digging a well in 1974;No two soldiers' faces are exactly alike;It was buried with China's first emperor, Qin Shi Huang;It is an army of clay soldiers near Xi'an
Potala Palace|Potala Palace|CHN|castle|||It has more than 1,000 rooms;It stands on Marpo Ri hill at about 3,700 metres;It was the winter home of the Dalai Lamas;It towers over Lhasa in Tibet
Borobudur|Borobudur|IDN|religious|||It was built in the 9th century;It was hidden under volcanic ash and jungle for centuries;It is the world's largest Buddhist temple;It is on the island of Java
Shwedagon Pagoda|Shwedagon Pagoda|MMR|religious|||Its spire is tipped with thousands of diamonds;It is said to hold relics of four Buddhas;It is covered in gold;It is a gilded stupa in Yangon
Ha Long Bay|Ha Long Bay|VNM|natural||Halong Bay|Its name means where the dragon descends;It has around 1,600 islands and islets;Its islands are limestone pillars rising from the sea;It is in the Gulf of Tonkin in northern Vietnam
Golden Temple|Golden Temple|IND|religious||Harmandir Sahib|Its community kitchen serves free meals to tens of thousands of people every day;It is the holiest gurdwara of Sikhism;Its upper floors are covered in gold;It stands in a sacred pool in Amritsar
Gateway of India|Gateway of India|IND|monument|1924||It was completed in 1924;It commemorates the landing of King George V and Queen Mary in 1911;It was designed by George Wittet;It is built of yellow basalt;The last British troops left India through it in 1948;It is an arch on the waterfront in Mumbai
Abu Simbel temples|Abu Simbel|EGY|ancient||Abu Simbel temples|In the 1960s the whole site was cut up and moved to escape a rising reservoir;Its four colossal statues show Ramesses II;Twice a year the sun lights the inner sanctuary;It is a pair of rock temples near Lake Nasser
Great Sphinx of Giza|Great Sphinx of Giza|EGY|ancient||Sphinx;The Sphinx|Its nose has been missing for centuries;It is carved from a single ridge of limestone;It has a lion's body and a human head;It guards the pyramids outside Cairo
Burj Al Arab|Burj Al Arab|ARE|building|1999||It opened in 1999;It stands on its own artificial island;Its shape is designed to look like a ship's sail;It is a luxury hotel on the Dubai coast
Sheikh Zayed Grand Mosque|Sheikh Zayed Grand Mosque|ARE|religious|2007||It opened in 2007;It has one of the world's largest hand-knotted carpets;It has 82 white domes;It is the largest mosque in the United Arab Emirates
Teotihuacan|Teotihuacan|MEX|ancient||Teotihuacán|Its main street is called the Avenue of the Dead;Its builders are still a mystery;Its Pyramid of the Sun is one of the largest in the Americas;It is an ancient city near Mexico City
Tikal|Tikal|GTM|ancient|||It was used as a filming location in Star Wars;Its tallest temple rises about 70 metres;It was one of the largest Maya cities;It lies in the rainforest of northern Guatemala
Panama Canal|Panama Canal|PAN|engineering|1914||It opened in 1914;Ships are raised and lowered by locks;It was controlled by the United States until 1999;It links the Atlantic and Pacific oceans across a narrow isthmus
Galápagos Islands|Galápagos Islands|ECU|natural||Galapagos Islands;Galapagos|Charles Darwin visited them in 1835;They are home to giant tortoises and marine iguanas;They are volcanic islands on the equator;They lie in the Pacific about 900 km west of Ecuador
Salar de Uyuni|Salar de Uyuni|BOL|natural||Uyuni salt flat|After rain it becomes a giant mirror;It holds a large share of the world's known lithium;It is the world's largest salt flat;It is in the Andes of south-west Bolivia
Perito Moreno Glacier|Perito Moreno Glacier|ARG|natural||Perito Moreno|Its ice wall towers about 70 metres above the water;Huge chunks of ice regularly crash from its face into the lake;It is in Los Glaciares National Park in Patagonia
Sugarloaf Mountain|Sugarloaf Mountain|BRA|natural||Pão de Açúcar|A cable car has carried visitors to its top since 1912;It rises 396 metres from the water's edge;It is named after the shape of old sugar moulds;It stands at the mouth of Guanabara Bay in Rio de Janeiro
Hollywood Sign|Hollywood Sign|USA|monument|1923||It was put up in 1923 to advertise a housing development;It originally had extra letters at the end;Each letter is about 14 metres tall;It sits on Mount Lee above Los Angeles
Space Needle|Space Needle|USA|tower|1962||It was built for the 1962 World's Fair;It has a rotating glass floor near the top;Its shape resembles a flying saucer on stilts;It is an observation tower in Seattle
Gateway Arch|Gateway Arch|USA|monument|1965||It was completed in 1965;Small tram pods carry visitors to the top;At 192 metres it is the world's tallest arch;It stands on the banks of the Mississippi in St. Louis
Edinburgh Castle|Edinburgh Castle|GBR|castle|||The One O'Clock Gun is fired from it most days;The Honours of Scotland are kept here;It sits on an extinct volcano called Castle Rock;It towers over the Scottish capital
Buckingham Palace|Buckingham Palace|GBR|castle|||It became the official royal residence when Queen Victoria moved in in 1837;The Changing of the Guard takes place outside;It has 775 rooms;It is the London home of the British monarch
Cliffs of Moher|Cliffs of Moher|IRL|natural|||They appear in Harry Potter and the Half-Blood Prince;They rise up to 214 metres above the Atlantic;They run for about 14 km along the coast of County Clare;They are sea cliffs on the west coast of Ireland
Giant's Causeway|Giant's Causeway|GBR|natural|||Legend says it was built by the giant Finn McCool;It is made of about 40,000 interlocking columns;Its columns are mostly six-sided and formed by cooling lava;It is on the coast of County Antrim in Northern Ireland
Charles Bridge|Charles Bridge|CZE|bridge|||Construction began in 1357;It is lined with 30 Baroque statues;It is open only to people on foot;It crosses the Vltava river in Prague
Hallgrímskirkja|Hallgrímskirkja|ISL|religious|1986|Hallgrimskirkja|It was completed in 1986;Its design was inspired by basalt columns;It is one of the tallest buildings in its country;It is a Lutheran church on a hill in Reykjavík
Bran Castle|Bran Castle|ROU|castle|||It is marketed as Dracula's Castle;It guards a mountain pass in the Carpathians;It was once a residence of Queen Marie;It is a castle in Transylvania
Kinderdijk|Kinderdijk|NLD|engineering|||It has 19 windmills built in the 18th century;Its windmills were used to drain the land;It is a UNESCO World Heritage Site;It is a village near Rotterdam famous for windmills
Wieliczka Salt Mine|Wieliczka Salt Mine|POL|engineering|||It has a chapel with chandeliers carved from salt;It was mined from the 13th century until 1996;It reaches over 300 metres deep;It is near Kraków
Cologne Cathedral|Cologne Cathedral|DEU|religious|||Building started in 1248 and was finished in 1880;It holds a shrine said to contain relics of the Three Kings;Its twin spires are 157 metres tall;It stands beside the Rhine in Cologne
Meteora|Meteora|GRC|religious|||Monks once reached them using nets and rope ladders;Its name means suspended in the air;Six monasteries are still active there;They are monasteries perched on rock pillars in Thessaly
Pamukkale|Pamukkale|TUR|natural|||The ancient city of Hierapolis sits above it;Its name means cotton castle;Its white terraces are formed by mineral-rich hot springs;It is in the province of Denizli in Turkey
Rock-Hewn Churches, Lalibela|Lalibela churches|ETH|religious||Lalibela|They were carved from solid rock;They date from the reign of King Lalibela around 1200;The Church of St George is cross-shaped and sunk into the ground;They are in the highlands of Ethiopia
Great Mosque of Djenné|Great Mosque of Djenné|MLI|religious|1907|Djenné mosque|The current building dates from 1907;Townspeople replaster it each year in a festival;It is the largest mud-brick building in the world;It stands in the town of Djenné in Mali
Milford Sound|Milford Sound|NZL|natural|||Mitre Peak rises from its waters;It is a fjord carved by glaciers;It is in Fiordland on New Zealand's South Island
Great Barrier Reef|Great Barrier Reef|AUS|natural|||It is made of nearly 3,000 individual reefs;It can be seen from space;It is the world's largest coral reef system;It lies off the coast of Queensland
Fushimi Inari-taisha|Fushimi Inari-taisha|JPN|religious||Fushimi Inari|Fox statues guard its grounds;It is dedicated to the god of rice;Thousands of red torii gates line its paths up a mountain;It is a Shinto shrine in Kyoto
Tokyo Skytree|Tokyo Skytree|JPN|tower|2012|Skytree|It opened in 2012;At 634 metres it is the tallest tower in the world;It is a broadcasting and observation tower;It stands in Sumida, Tokyo
Kinkaku-ji|Kinkaku-ji|JPN|religious||Golden Pavilion;Kinkakuji|It was burned down by a monk in 1950 and rebuilt;It was originally a retirement villa for a shogun;Its top two floors are covered in gold leaf;It is a Zen temple in Kyoto
Gyeongbokgung|Gyeongbokgung|KOR|castle||Gyeongbok Palace|It was first built in 1395;It was the main royal palace of the Joseon dynasty;Guards in traditional dress change shifts at its gate;It is a palace in central Seoul
Sydney Harbour Bridge|Sydney Harbour Bridge|AUS|bridge|1932||It opened in 1932;Locals nicknamed it the Coathanger;Visitors can climb over its steel arch;It crosses the harbour beside the Opera House
Lotus Temple|Lotus Temple|IND|religious|1986||It opened in 1986;It is a Baháʼí House of Worship open to people of all religions;Its 27 marble petals form the shape of a flower;It is in New Delhi
Wat Arun|Wat Arun|THA|religious||Temple of Dawn|It is a Buddhist temple facing the Grand Palace area across the river;Its central spire is decorated with broken porcelain;It is named after the Hindu god of dawn;It is known as the Temple of Dawn;It stands on the west bank of the Chao Phraya in Bangkok
Bagan|Bagan|MMR|religious|||It was the capital of the Pagan Kingdom;Over 2,000 temples and pagodas survive on its plain;Hot-air balloons float over it at sunrise;It is an ancient city in central Myanmar
Moscow Kremlin|Moscow Kremlin|RUS|castle||Kremlin|It contains five palaces and four cathedrals;Its red brick walls have 20 towers;It is the official residence of the Russian president;It is a fortress beside Red Square
Winter Palace|Winter Palace|RUS|castle|||It was stormed in the 1917 revolution;Its rooms house part of the Hermitage Museum;It was the official home of the Russian tsars;It stands on the Neva river in Saint Petersburg
Plitvice Lakes National Park|Plitvice Lakes|HRV|natural||Plitvice|Wooden walkways wind between its pools;Its lakes are divided by natural travertine dams;It has 16 terraced lakes joined by waterfalls;It is a national park in Croatia
Persepolis|Persepolis|IRN|ancient|||It was burned by Alexander the Great in 330 BC;Its Gate of All Nations is guarded by winged bulls;It was the ceremonial capital of the Achaemenid Empire;Its ruins are near Shiraz
Sigiriya|Sigiriya|LKA|ancient||Lion Rock|Its walls once held a gallery of painted maidens;Visitors pass between giant lion paws to climb it;A palace once stood on its flat top;It is a rock fortress in central Sri Lanka
Château Frontenac|Château Frontenac|CAN|building|1893|Chateau Frontenac|It opened in 1893 as a railway hotel;It is said to be the most photographed hotel in the world;Its copper roofs have turned green;It overlooks the St. Lawrence River in Quebec City
White House|White House|USA|building|1800||It was set on fire by British troops in 1814;John Adams was the first president to live there;Its address is 1600 Pennsylvania Avenue;It is the home and office of the US president in Washington, D.C.
Ngorongoro Conservation Area|Ngorongoro Crater|TZA|natural||Ngorongoro|It is about 20 km across;Its floor is home to lions, elephants and rhinos;It is the world's largest unbroken volcanic caldera that is not filled with water;It is in northern Tanzania near the Serengeti
Hassan II Mosque|Hassan II Mosque|MAR|religious|1993||It was completed in 1993;Its minaret is about 210 metres tall;Part of its floor is built over the Atlantic Ocean;It is in Casablanca
Carthage|Carthage|TUN|ancient|||Rome destroyed it in 146 BC;Hannibal led its armies over the Alps;It was founded by Phoenicians;Its ruins lie near Tunis
Leptis Magna|Leptis Magna|LBY|ancient|||The emperor Septimius Severus was born here;It was one of the finest cities of the Roman Empire;Its ruins are among the best-preserved Roman sites in the Mediterranean;It is on the coast of Libya
`;
