// Public-domain paintings: Wikipedia title | display | artist | year (completion or main date) | museum / location | difficulty | clues hardest->easiest | alt
// Artist, year and collection are cross-checked against Wikidata; image licence must pass the Commons check.
export const PAINTINGS = `
Mona Lisa|Mona Lisa|Leonardo da Vinci|1503|Louvre, Paris|1|It was stolen in 1911 and missing for two years;It is painted on a poplar wood panel;Its sitter is thought to be Lisa Gherardini;It is famous for a mysterious smile|La Gioconda;La Joconde
The Last Supper (Leonardo)|The Last Supper|Leonardo da Vinci|1498|Santa Maria delle Grazie, Milan|1|It was painted on a monastery's dining-room wall;Its experimental technique began flaking within decades;It shows the moment one follower is about to be named as a betrayer;It shows Jesus at a meal with his twelve apostles
The Starry Night|The Starry Night|Vincent van Gogh|1889|Museum of Modern Art, New York|1|It was painted from memory during the day;A cypress tree rises like a flame in the foreground;It shows the view from an asylum window in Saint-Rémy;Swirling stars fill a deep blue night sky above a village|Starry Night
The Scream|The Scream|Edvard Munch|1893|National Museum, Oslo|1|The artist made several versions, in paint and pastel;The sky above is blood red;A figure stands on a bridge with its hands on its face;It shows a figure screaming in terror|Scream
Girl with a Pearl Earring|Girl with a Pearl Earring|Johannes Vermeer|1665|Mauritshuis, The Hague|1|It is sometimes called the Mona Lisa of the North;It is a tronie, a study of a face rather than a portrait;The girl wears a blue and yellow turban;A girl looks over her shoulder wearing a large pearl
The Birth of Venus|The Birth of Venus|Sandro Botticelli|1485|Uffizi, Florence|1|A wind god blows the goddess towards the shore;It was painted in Florence in the 1480s;It shows a goddess arriving on land;A goddess stands on a giant scallop shell|Birth of Venus
The Night Watch|The Night Watch|Rembrandt|1642|Rijksmuseum, Amsterdam|1|It was cut down on all four sides in 1715 to fit a wall;It was not originally a night scene but darkened varnish made it look like one;It shows a militia company led by Captain Frans Banninck Cocq;It is a huge group portrait full of light and shadow|Night Watch
The Kiss (Klimt)|The Kiss|Gustav Klimt|1908|Belvedere, Vienna|1|The couple kneel on a carpet of flowers at the edge of a cliff;It was bought by the Austrian state in 1908;It is covered in real gold leaf;A couple embrace wrapped in golden robes|The Kiss
The Great Wave off Kanagawa|The Great Wave off Kanagawa|Katsushika Hokusai|1831|Woodblock print (many copies)|1|It is a woodblock print, so many copies exist;It uses an imported blue pigment called Prussian blue;Mount Fuji appears small in the background;A giant claw-like wave towers over three boats|The Great Wave
Impression, Sunrise|Impression, Sunrise|Claude Monet|1872|Musée Marmottan Monet, Paris|2|A critic mocked its title, and the name stuck for a whole art movement;It was stolen in 1985 and recovered in 1990;It shows the port of Le Havre;A small orange sun glows over a misty harbour|Impression Sunrise
The Creation of Adam|The Creation of Adam|Michelangelo|1512|Sistine Chapel, Vatican City|1|It was painted on a ceiling high above the floor;The shape around God has been compared to a human brain;It is part of the Sistine Chapel ceiling;Two fingers almost touch as God gives life to the first man|Creation of Adam
Las Meninas|Las Meninas|Diego Velázquez|1656|Museo del Prado, Madrid|3|The king and queen appear only as reflections in a mirror;The painter shows himself at work on a huge canvas;Its title means The Ladies-in-waiting;It shows the young Spanish princess Margarita with her attendants|The Ladies-in-waiting
The Garden of Earthly Delights|The Garden of Earthly Delights|Hieronymus Bosch|1505|Museo del Prado, Madrid|3|Its outer shutters show the world as a glass sphere;It is a triptych with three panels;Its right panel shows a nightmarish hell with musical instruments used as torture;It is crowded with strange creatures, giant fruit and tiny naked people|Garden of Earthly Delights
A Sunday Afternoon on the Island of La Grande Jatte|A Sunday Afternoon on the Island of La Grande Jatte|Georges Seurat|1886|Art Institute of Chicago|2|A woman in it walks a pet monkey on a lead;It took about two years to complete;It is made of millions of tiny dots;Parisians relax by the river on a sunny day|La Grande Jatte
American Gothic|American Gothic|Grant Wood|1930|Art Institute of Chicago|1|The models were the artist's sister and his dentist;The house behind them has a Gothic-style window;It is one of the most parodied images in American art;A stern farmer with a pitchfork stands beside a woman
Arnolfini Portrait|The Arnolfini Portrait|Jan van Eyck|1434|National Gallery, London|3|The artist signed it on the wall: Jan van Eyck was here;A convex mirror on the back wall reflects two more people;A small dog stands at the couple's feet;A wealthy merchant and his wife stand in a room in Bruges|Arnolfini Wedding
The Hay Wain|The Hay Wain|John Constable|1821|National Gallery, London|2|It won a gold medal at the Paris Salon in 1824;The cottage in it still stands at Flatford Mill;It shows the River Stour in Suffolk;A horse-drawn farm cart stands in a shallow river|Hay Wain
The Fighting Temeraire|The Fighting Temeraire|J. M. W. Turner|1839|National Gallery, London|3|It was voted Britain's favourite painting in 2005;The old ship fought at the Battle of Trafalgar;The sun sets behind the scene, as if marking the end of an era;A small steam tug tows an old sailing warship to be broken up|Fighting Temeraire
Liberty Leading the People|Liberty Leading the People|Eugène Delacroix|1830|Louvre, Paris|2|A boy with two pistols charges beside her;It commemorates the July Revolution of 1830;A woman in a red cap leads people over a barricade;She raises the French tricolour flag
The Third of May 1808|The Third of May 1808|Francisco Goya|1814|Museo del Prado, Madrid|3|A lantern on the ground lights the scene;It shows events after an uprising against Napoleon's troops;A man in a white shirt raises his arms before soldiers;It shows a firing squad executing Spanish civilians|Third of May
Wanderer above the Sea of Fog|Wanderer above the Sea of Fog|Caspar David Friedrich|1818|Hamburger Kunsthalle|2|It is a famous image of German Romanticism;We see the main figure only from behind;He holds a walking stick on a rocky peak;A man stands on a rock gazing over a landscape covered in mist|Wanderer above the Mists
The Raft of the Medusa|The Raft of the Medusa|Théodore Géricault|1819|Louvre, Paris|3|The painter studied corpses in a hospital to get the details right;It is based on a real French shipwreck of 1816;Survivors wave desperately at a distant ship;Shipwreck survivors cling to a crowded raft|Raft of the Medusa
The School of Athens|The School of Athens|Raphael|1511|Apostolic Palace, Vatican City|2|The painter included himself looking out at the viewer;Plato points up while Aristotle gestures towards the ground;It is a fresco in a room of the Pope's palace;It shows the great thinkers of ancient Greece together|School of Athens
The Milkmaid (Vermeer)|The Milkmaid|Johannes Vermeer|1658|Rijksmuseum, Amsterdam|2|A foot warmer sits on the floor behind her;Bread and a blue cloth lie on the table;The light comes from a window on the left;A kitchen maid carefully pours milk from a jug|The Kitchen Maid
Bal du moulin de la Galette|Dance at Le Moulin de la Galette|Pierre-Auguste Renoir|1876|Musée d'Orsay, Paris|3|It sold for over 78 million dollars in 1990, though that was a smaller version;Sunlight dapples through trees onto the crowd;It shows a Sunday afternoon in Montmartre;People dance and chat at an open-air café|Bal du moulin de la Galette
Luncheon of the Boating Party|Luncheon of the Boating Party|Pierre-Auguste Renoir|1881|Phillips Collection, Washington, D.C.|3|The painter's future wife sits in front holding a small dog;It is set at a restaurant on the Seine at Chatou;Some of the figures wear straw boater hats;Friends share lunch on a balcony by the river
Café Terrace at Night|Café Terrace at Night|Vincent van Gogh|1888|Kröller-Müller Museum, Otterlo|1|It was painted on the spot at night in Arles;It was the first painting in which the artist used a starry background;A yellow awning glows under a blue sky;People sit outside a café under the stars|Cafe Terrace at Night
Self-Portrait with Bandaged Ear|Self-Portrait with Bandaged Ear|Vincent van Gogh|1889|Courtauld Gallery, London|1|A Japanese print hangs on the wall behind him;He wears a fur hat and a green coat;He painted it shortly after an incident in Arles;The painter shows himself with a bandage over his ear
The Hunters in the Snow|The Hunters in the Snow|Pieter Bruegel the Elder|1565|Kunsthistorisches Museum, Vienna|2|It is one of a series showing the seasons;Skaters play on frozen ponds in the valley;Weary hunters return with their dogs;It is a winter landscape covered in snow|Hunters in the Snow
The Tower of Babel (Bruegel)|The Tower of Babel|Pieter Bruegel the Elder|1563|Kunsthistorisches Museum, Vienna|3|Its design echoes the Colosseum in Rome;A king inspects stonemasons in the foreground;It shows a Bible story about language;A gigantic unfinished tower rises into the clouds|Tower of Babel
The Ambassadors (Holbein)|The Ambassadors|Hans Holbein the Younger|1533|National Gallery, London|3|A stretched skull can only be seen properly from the side;Scientific instruments sit on a shelf between the men;It was painted in London during the reign of Henry VIII;Two richly dressed French diplomats stand side by side|The Ambassadors
Primavera (Botticelli)|Primavera|Sandro Botticelli|1480|Uffizi, Florence|3|Botanists have identified around 500 plant species in it;Cupid flies above firing an arrow;Venus stands in the centre of an orange grove;Its title means Spring|Allegory of Spring
The Calling of Saint Matthew|The Calling of Saint Matthew|Caravaggio|1600|San Luigi dei Francesi, Rome|3|It hangs in a chapel of a French church in Rome;A beam of light cuts across the dark room;Men sit counting money at a table;Jesus points at a tax collector to follow him|Calling of Saint Matthew
Whistler's Mother|Whistler's Mother|James McNeill Whistler|1871|Musée d'Orsay, Paris|2|It appeared on a US postage stamp in 1934;The painter was an American living in London;Its official title is Arrangement in Grey and Black No. 1;It was bought by the French state in 1891;An older woman sits in profile in a black dress;It shows the painter's mother|Arrangement in Grey and Black No. 1
The Gleaners|The Gleaners|Jean-François Millet|1857|Musée d'Orsay, Paris|3|Wealthier viewers found it a disturbing picture of poverty;A huge harvest is stacked in the background;It shows rural women in the French countryside;Three peasant women stoop to pick up leftover grain|Gleaners
A Bar at the Folies-Bergère|A Bar at the Folies-Bergère|Édouard Manet|1882|Courtauld Gallery, London|3|The legs of a trapeze artist appear in the top corner;Bottles of English beer sit on the counter;A large mirror behind her reflects the crowd;A barmaid stands behind a marble counter in a Paris nightclub
Where Do We Come From? What Are We? Where Are We Going?|Where Do We Come From? What Are We? Where Are We Going?|Paul Gauguin|1898|Museum of Fine Arts, Boston|3|The painter meant it to be read from right to left;Its title is written in the top-left corner in French;It was painted in Tahiti;It is a large frieze of figures under a three-question title
The Sleeping Gypsy|The Sleeping Gypsy|Henri Rousseau|1897|Museum of Modern Art, New York|3|A mandolin and a water jug lie beside the sleeper;The painter was a self-taught former customs clerk;The moon shines over a desert;A lion sniffs at a sleeping woman|Sleeping Gypsy
Surprised!|Tiger in a Tropical Storm (Surprised!)|Henri Rousseau|1891|National Gallery, London|1|The painter never left France and studied plants at the Paris botanical garden;It was the painter's first jungle picture;Lightning flashes as rain lashes the leaves;A tiger crouches in a jungle during a storm|Surprised!;Tiger in a Tropical Storm
The Lady of Shalott (painting)|The Lady of Shalott|John William Waterhouse|1888|Tate Britain, London|3|It illustrates a poem by Alfred, Lord Tennyson;Candles flicker at the front of the boat;A tapestry hangs over the side of the boat;A woman with long red hair sits in a boat drifting down a river|Lady of Shalott
Ophelia (Millais)|Ophelia|John Everett Millais|1852|Tate Britain, London|2|The model, Elizabeth Siddal, posed in a bath of water;Flowers float on the water around her;It shows a character from Hamlet;A young woman floats singing in a stream
The Blue Boy|The Blue Boy|Thomas Gainsborough|1770|Huntington Library, San Marino, California|2|It was sold to an American buyer in 1922 for a record price;It returned to London for an exhibition in 2022, a century after it left;The sitter wears clothes in the style of a century earlier;A boy stands in a shimmering blue satin suit|Blue Boy
Mr and Mrs Andrews|Mr and Mrs Andrews|Thomas Gainsborough|1750|National Gallery, London|3|An unfinished patch sits on the wife's lap;The husband holds a gun and has a dog at his side;Fields of their Suffolk estate stretch behind them;A young married couple pose under an oak tree
The Swing (Fragonard)|The Swing|Jean-Honoré Fragonard|1767|Wallace Collection, London|2|An older man pushes the swing from the shadows;A young man hides in the bushes below;She kicks off a pink slipper into the air;A young woman in a frothy pink dress flies through the air on a swing|Les hasards heureux de l'escarpolette
Washington Crossing the Delaware (1851 painting)|Washington Crossing the Delaware|Emanuel Leutze|1851|Metropolitan Museum of Art, New York|2|It was painted in Düsseldorf by a German-American artist;The flag in it had not yet been adopted at the time of the event;It shows a surprise attack on Christmas night 1776;A general stands boldly in a rowing boat among ice
The Laughing Cavalier|The Laughing Cavalier|Frans Hals|1624|Wallace Collection, London|3|His sleeve is embroidered with symbols of love;He is not actually laughing but smiling;The sitter is 26 years old, according to an inscription;A man with a wide hat and curled moustache smiles at us|Laughing Cavalier
The Anatomy Lesson of Dr. Nicolaes Tulp|The Anatomy Lesson of Dr. Nicolaes Tulp|Rembrandt|1632|Mauritshuis, The Hague|3|It made its painter's name in Amsterdam at age 26;The corpse was a criminal hanged that day;The doctor shows the muscles of the forearm;Surgeons gather to watch a dissection|The Anatomy Lesson
Woman with a Parasol – Madame Monet and Her Son|Woman with a Parasol|Claude Monet|1875|National Gallery of Art, Washington, D.C.|2|The boy is the painter's son Jean;It was painted outdoors in quick strokes;Wind ruffles her veil and dress on a grassy hill;A woman holds a parasol against a bright sky|Madame Monet and Her Son
Portrait of Adele Bloch-Bauer I|Portrait of Adele Bloch-Bauer I|Gustav Klimt|1907|Neue Galerie, New York|3|It was looted by the Nazis and returned to the family after a court case;It sold for a reported 135 million dollars in 2006;It was the subject of the film Woman in Gold;A Viennese society woman sits surrounded by swirls of gold|Woman in Gold;The Lady in Gold
Lady with an Ermine|Lady with an Ermine|Leonardo da Vinci|1490|Czartoryski Museum, Kraków|3|It was taken by the Nazis during the Second World War;It is one of only four surviving female portraits by its painter;The sitter is thought to be Cecilia Gallerani;A young woman holds a white stoat-like animal|Portrait of Cecilia Gallerani
The Harvesters (painting)|The Harvesters|Pieter Bruegel the Elder|1565|Metropolitan Museum of Art, New York|3|It is one of a series of six paintings of the times of year;A man naps under a pear tree;Workers eat lunch in the shade;Peasants cut and gather golden wheat in summer
Irises (painting)|Irises|Vincent van Gogh|1889|J. Paul Getty Museum, Los Angeles|2|It sold in 1987 for a then-record 53.9 million dollars;The artist painted it in his first week at the asylum in Saint-Rémy;A single white flower stands out among the blue;It shows a bed of purple-blue flowers|Irises
The Potato Eaters|The Potato Eaters|Vincent van Gogh|1885|Van Gogh Museum, Amsterdam|3|He painted it in the Netherlands before moving to France;A single lamp lights the dark room;He wanted to show people who had dug the earth with their own hands;A peasant family shares a simple meal|Potato Eaters
The Death of Marat|The Death of Marat|Jacques-Louis David|1793|Royal Museums of Fine Arts of Belgium, Brussels|3|The victim's killer was Charlotte Corday;He still holds the letter she used to get in to see him;It shows a revolutionary leader murdered in his bath;It is a famous image of the French Revolution|Death of Marat
Flaming June|Flaming June|Frederic Leighton|1895|Museo de Arte de Ponce, Puerto Rico|3|In the 1960s it failed to sell at auction for a modest price;A branch of poisonous oleander hangs at top right;Her dress is a glowing orange;A woman sleeps curled up in a sheer orange dress
Young Hare|Young Hare|Albrecht Dürer|1502|Albertina, Vienna|1|A window is reflected in the animal's eye;Every hair of its fur seems to be painted;It is a watercolour and gouache;It is a famous painting of a young hare|The Hare
The Night Café|The Night Café|Vincent van Gogh|1888|Yale University Art Gallery|3|He said he wanted to express the terrible passions of humanity with red and green;He stayed up three nights to paint it;Gas lamps glow over an almost empty room;It shows a billiard table in an all-night café|Night Café
`;
