// People: Wikipedia title | display name | expected birth year ('' = uncertain, not shown) | nationality | field | difficulty | clues hardest->easiest (;) | alt names (;)
// Birth/death years come from Wikidata and are cross-checked against the expected year.
export const PEOPLE = `
Albert Einstein|Albert Einstein|1879|German-born|science|1|He won the Nobel Prize in Physics for explaining the photoelectric effect;He left Germany in 1933 and settled in the United States;His most famous equation links energy and mass;He developed the theory of relativity|Einstein
Isaac Newton|Isaac Newton|1643|English|science|1|He also served as Warden of the Royal Mint;He built one of the first reflecting telescopes;He wrote the Principia, describing three laws of motion;A falling apple is said to have inspired his theory of gravity|Newton;Sir Isaac Newton
Marie Curie|Marie Curie|1867|Polish-French|science|1|She discovered the elements polonium and radium;She was the first person to win Nobel Prizes in two different sciences;She was born Maria Skłodowska in Warsaw;She was a pioneer of research into radioactivity|Madame Curie
Charles Darwin|Charles Darwin|1809|English|science|1|He spent years studying barnacles and earthworms;He sailed around the world on HMS Beagle;He wrote On the Origin of Species;He developed the theory of evolution by natural selection|Darwin
Galileo Galilei|Galileo Galilei|1564|Italian|science|1|He was tried by the Roman Inquisition and kept under house arrest;He discovered the four largest moons of Jupiter;He improved the telescope and used it to study the sky;He supported the idea that the Earth goes around the Sun|Galileo
Nikola Tesla|Nikola Tesla|1856|Serbian-American|science|2|The SI unit of magnetic flux density is named after him;He worked briefly for Thomas Edison;He championed alternating current (AC) electricity;An electric car company is named after him|Tesla
Thomas Edison|Thomas Edison|1847|American|science|1|His laboratory was at Menlo Park, New Jersey;He held over 1,000 patents;He invented the phonograph;He is famous for developing a practical electric light bulb|Edison;Thomas Alva Edison
Stephen Hawking|Stephen Hawking|1942|English|science|1|He held the same Cambridge professorship once held by Isaac Newton;He predicted that black holes give off radiation;He spoke using a computer voice;He wrote A Brief History of Time|Hawking
Ada Lovelace|Ada Lovelace|1815|English|science|2|Her father was the poet Lord Byron;She worked with Charles Babbage on his Analytical Engine;A programming language is named after her;She is often called the first computer programmer|Lovelace;Ada Byron
Alan Turing|Alan Turing|1912|English|science|2|He proposed a test of whether a machine can think;He worked at Bletchley Park during the Second World War;He helped break the German Enigma code;He is a founder of computer science|Turing
Louis Pasteur|Louis Pasteur|1822|French|science|2|He developed a vaccine against rabies;He proved that germs cause disease;A process of heating milk to kill germs is named after him;He was a French chemist and microbiologist|Pasteur
Alexander Fleming|Alexander Fleming|1881|Scottish|science|2|He shared the 1945 Nobel Prize in Medicine;He noticed mould killing bacteria in a dish in 1928;He worked at St Mary's Hospital in London;He discovered penicillin|Fleming
Rosalind Franklin|Rosalind Franklin|1920|English|science|3|She died in 1958 at the age of 37;She worked at King's College London;Her X-ray image called Photo 51 was key to a famous discovery;Her work revealed the double helix structure of DNA|Franklin
Gregor Mendel|Gregor Mendel|1822|Austrian|science|3|He was a monk and later abbot in Brno;His work was ignored until 1900;He bred thousands of pea plants;He is called the father of genetics|Mendel
Dmitri Mendeleev|Dmitri Mendeleev|1834|Russian|science|2|Element 101 is named after him;He left gaps for elements not yet discovered;He was a Russian chemist;He created the periodic table of the elements|Mendeleev
Nicolaus Copernicus|Nicolaus Copernicus|1473|Polish|science|2|He was also a church official and a doctor;His great book was published in the year of his death, 1543;He came from Toruń;He proposed that the Earth goes around the Sun|Copernicus
Michael Faraday|Michael Faraday|1791|English|science|3|He started work as a bookbinder's apprentice;He began the Royal Institution's Christmas Lectures;The unit of electrical capacitance is named after him;He discovered electromagnetic induction|Faraday
Alexander Graham Bell|Alexander Graham Bell|1847|Scottish-born|science|2|He taught deaf students in Boston;The unit used to measure sound levels, the decibel, honours him;He was born in Edinburgh;He is credited with inventing the telephone|Graham Bell
Katherine Johnson|Katherine Johnson|1918|American|science|3|She was awarded the Presidential Medal of Freedom in 2015;Her story is told in the film Hidden Figures;She calculated orbits for NASA's early crewed flights;She was a mathematician who checked John Glenn's flight path
Jane Goodall|Jane Goodall|1934|English|science|2|She began her research at Gombe Stream in Tanzania in 1960;She was the first to observe chimpanzees making tools;She was a UN Messenger of Peace;She spent decades studying wild chimpanzees|Goodall
Carl Sagan|Carl Sagan|1934|American|science|3|He helped design the Golden Records carried by the Voyager probes;He described Earth as a pale blue dot;He presented the TV series Cosmos;He was an American astronomer and science communicator|Sagan
Tim Berners-Lee|Tim Berners-Lee|1955|English|science|2|He was working at CERN when he made his big invention;He wrote the first web browser;He was knighted in 2004;He invented the World Wide Web|Berners-Lee
Edward Jenner|Edward Jenner|1749|English|science|3|He was a country doctor in Gloucestershire;He used cowpox to protect a boy against smallpox;The word vaccine comes from the Latin for cow;He pioneered the first vaccine|Jenner
Florence Nightingale|Florence Nightingale|1820|British|science|1|She was named after the Italian city where she was born;She used statistics and charts to push for better hospitals;She nursed soldiers in the Crimean War;She was known as the Lady with the Lamp|Nightingale
Mary Anning|Mary Anning|1799|English|science|3|A tongue-twister about selling seashells is said to be about her;She found the first ichthyosaur skeleton to be correctly identified;She hunted fossils on the cliffs of Lyme Regis;She was a pioneering fossil collector|Anning
Niels Bohr|Niels Bohr|1885|Danish|science|3|Element 107, bohrium, is named after him;He won the Nobel Prize in Physics in 1922;He founded an institute in Copenhagen;He created a famous model of the atom|Bohr
Richard Feynman|Richard Feynman|1918|American|science|3|He played the bongo drums;He investigated the Challenger space shuttle disaster;He drew diagrams of particle interactions that are named after him;He was an American physicist who won the Nobel Prize in 1965|Feynman
Johannes Kepler|Johannes Kepler|1571|German|science|3|He worked as an assistant to Tycho Brahe;A NASA planet-hunting telescope was named after him;He showed that planets move in ellipses;He described three laws of planetary motion|Kepler
William Shakespeare|William Shakespeare|1564|English|literature|1|He was born and died in Stratford-upon-Avon;His company performed at the Globe Theatre;He wrote about 39 plays and 154 sonnets;He wrote Romeo and Juliet and Hamlet|Shakespeare;The Bard
Jane Austen|Jane Austen|1775|English|literature|2|She lived for a time in Bath;Her books were first published without her name;She appears on the Bank of England £10 note;She wrote Pride and Prejudice|Austen
Charles Dickens|Charles Dickens|1812|English|literature|1|As a boy he worked in a factory pasting labels on pots of boot polish;Many of his novels first came out in monthly parts;He created Ebenezer Scrooge;He wrote Oliver Twist and A Christmas Carol|Dickens
Mark Twain|Mark Twain|1835|American|literature|2|His real name was Samuel Clemens;He once worked as a riverboat pilot on the Mississippi;He wrote Adventures of Huckleberry Finn;He created Tom Sawyer|Samuel Clemens;Samuel Langhorne Clemens
Agatha Christie|Agatha Christie|1890|English|literature|2|She mysteriously disappeared for 11 days in 1926;Her play The Mousetrap has run in London since 1952;She created Miss Marple;She created the Belgian detective Hercule Poirot|Christie
J. K. Rowling|J. K. Rowling|1965|British|literature|1|She wrote crime novels under the name Robert Galbraith;She began her most famous book in Edinburgh cafés;Her first book was rejected by many publishers;She wrote the Harry Potter books|JK Rowling;Joanne Rowling
Hans Christian Andersen|Hans Christian Andersen|1805|Danish|literature|2|He was born in Odense;A statue in Copenhagen harbour honours one of his characters;He wrote The Ugly Duckling;He wrote fairy tales including The Little Mermaid|Andersen
Roald Dahl|Roald Dahl|1916|British|literature|1|He was a fighter pilot in the Second World War;His parents were Norwegian;He wrote The BFG and Matilda;He wrote Charlie and the Chocolate Factory|Dahl
J. R. R. Tolkien|J. R. R. Tolkien|1892|English|literature|1|He was a professor of Anglo-Saxon at Oxford;He invented several languages for his stories;He wrote The Hobbit;He wrote The Lord of the Rings|Tolkien;JRR Tolkien
Maya Angelou|Maya Angelou|1928|American|literature|3|She read a poem at Bill Clinton's 1993 inauguration;She worked with Martin Luther King Jr. and Malcolm X;Her memoir is called I Know Why the Caged Bird Sings;She was an American poet and civil rights activist|Angelou
Dr. Seuss|Dr. Seuss|1904|American|literature|1|His real name was Theodor Seuss Geisel;He wrote one of his books using only 50 different words;He wrote Green Eggs and Ham;He created The Cat in the Hat|Theodor Seuss Geisel
Wolfgang Amadeus Mozart|Wolfgang Amadeus Mozart|1756|Austrian|music|1|He was born in Salzburg;He wrote the operas The Magic Flute and Don Giovanni;He toured Europe as a child prodigy;He was a famous composer of the Classical era|Mozart
Ludwig van Beethoven|Ludwig van Beethoven|1770|German|music|1|He was born in Bonn and lived in Vienna;He wrote Für Elise;His Ninth Symphony includes the Ode to Joy;He kept composing after he became deaf|Beethoven
Johann Sebastian Bach|Johann Sebastian Bach|1685|German|music|2|He had 20 children;He worked as music director in Leipzig;He wrote the Brandenburg Concertos;He was a great Baroque composer and organist|Bach
Antonio Vivaldi|Antonio Vivaldi|1678|Italian|music|2|He was a priest nicknamed the Red Priest for his hair;He taught music at an orphanage in Venice;He was a Baroque composer and violinist;He wrote The Four Seasons|Vivaldi
Pyotr Ilyich Tchaikovsky|Pyotr Ilyich Tchaikovsky|1840|Russian|music|2|He wrote the 1812 Overture;He wrote Sleeping Beauty;He wrote The Nutcracker;He wrote the ballet Swan Lake|Tchaikovsky
Frédéric Chopin|Frédéric Chopin|1810|Polish|music|3|His heart is kept in a church in Warsaw;He lived in Paris for most of his adult life;He wrote many mazurkas, nocturnes and polonaises;He was a Romantic composer famous for piano music|Chopin
Elvis Presley|Elvis Presley|1935|American|music|1|He served in the US Army in Germany;His home in Memphis was called Graceland;He sang Hound Dog and Jailhouse Rock;He was called the King of Rock and Roll|Elvis
John Lennon|John Lennon|1940|English|music|2|He was killed outside his New York apartment in 1980;He married the artist Yoko Ono;He wrote the song Imagine;He was a founding member of the Beatles|Lennon
Paul McCartney|Paul McCartney|1942|English|music|2|He later formed the band Wings;He played bass guitar in his first famous band;He wrote Yesterday;He was a member of the Beatles from Liverpool|McCartney
Michael Jackson|Michael Jackson|1958|American|music|1|He started out singing with his brothers;His signature dance move was the moonwalk;His album Thriller is among the best-selling albums ever;He was called the King of Pop|MJ
Freddie Mercury|Freddie Mercury|1946|British|music|2|He was born Farrokh Bulsara on Zanzibar;His band played a famous set at Live Aid in 1985;He wrote Bohemian Rhapsody;He was the lead singer of Queen|Farrokh Bulsara
Bob Marley|Bob Marley|1945|Jamaican|music|2|His band was called the Wailers;His greatest-hits album is called Legend;He sang One Love and No Woman, No Cry;He made reggae music famous around the world|Marley
Madonna|Madonna|1958|American|music|2|She starred in the film Evita;Her full name is Madonna Louise Ciccone;She sang Like a Virgin and Vogue;She is known as the Queen of Pop
Beyoncé|Beyoncé|1981|American|music|1|Her surname is Knowles;She first found fame with Destiny's Child;She sang Single Ladies and Crazy in Love;She is called Queen Bey|Beyonce
Taylor Swift|Taylor Swift|1989|American|music|1|She re-recorded her early albums;Her fans are known as Swifties;Her Eras Tour became the highest-grossing concert tour ever;She started as a country singer before switching to pop
Louis Armstrong|Louis Armstrong|1901|American|music|2|His nickname was Satchmo;He grew up in New Orleans;He sang What a Wonderful World;He was a famous jazz trumpeter|Satchmo
Dolly Parton|Dolly Parton|1946|American|music|2|She founded a theme park called Dollywood;Her Imagination Library sends free books to children;She wrote 9 to 5 and I Will Always Love You;She is a country music star from Tennessee
Walt Disney|Walt Disney|1901|American|film|1|He opened his first theme park in California in 1955;His company released Snow White and the Seven Dwarfs;He was the original voice of a famous cartoon mouse;He co-created Mickey Mouse|Disney
Charlie Chaplin|Charlie Chaplin|1889|English|film|1|He was born in London and worked in Hollywood;He directed and starred in Modern Times;His best-known character is the Tramp;He was a famous star of silent comedy films|Chaplin
Usain Bolt|Usain Bolt|1986|Jamaican|sport|1|His celebration pose is called the Lightning Bolt;He won the 100 m at three Olympic Games in a row;He set the 100 m world record of 9.58 seconds in 2009;He is the fastest sprinter ever timed|Bolt
Pelé|Pelé|1940|Brazilian|sport|1|His real name was Edson Arantes do Nascimento;He played most of his career for Santos;He won the World Cup three times;He is a Brazilian football legend|Pele
Diego Maradona|Diego Maradona|1960|Argentine|sport|2|He played for Napoli and Barcelona;He scored the Goal of the Century against England;He scored the Hand of God goal in 1986;He captained Argentina to the 1986 World Cup|Maradona
Lionel Messi|Lionel Messi|1987|Argentine|sport|1|He moved to Barcelona as a boy of 13;He won his eighth Ballon d'Or in 2023;He captained Argentina to the 2022 World Cup;He is an Argentine footballer|Messi;Leo Messi
Cristiano Ronaldo|Cristiano Ronaldo|1985|Portuguese|sport|1|He was born on the island of Madeira;He has played for Manchester United, Real Madrid and Juventus;His shirt is often number 7;He is Portugal's record goalscorer|Ronaldo;CR7
Serena Williams|Serena Williams|1981|American|sport|1|She won an Olympic gold medal in singles in 2012;She won 23 Grand Slam singles titles;Her sister Venus is also a champion;She is one of the greatest tennis players ever|Serena
Roger Federer|Roger Federer|1981|Swiss|sport|2|He retired in 2022;He was born in Basel;He won Wimbledon eight times;He is a Swiss tennis great|Federer
Rafael Nadal|Rafael Nadal|1986|Spanish|sport|2|He was born on Mallorca;He retired in 2024;He won the French Open 14 times;He is called the King of Clay|Nadal;Rafa Nadal
Muhammad Ali|Muhammad Ali|1942|American|sport|1|He was born Cassius Clay;He fought in the Rumble in the Jungle;He said he would float like a butterfly, sting like a bee;He was a heavyweight boxing champion|Cassius Clay
Michael Jordan|Michael Jordan|1963|American|sport|1|He briefly played professional baseball;He starred in the film Space Jam;He won six NBA titles with the Chicago Bulls;He is a basketball legend|Jordan
Simone Biles|Simone Biles|1997|American|sport|1|Several gymnastics moves are named after her;She won four gold medals at the 2016 Olympics;She is one of the most decorated gymnasts in history;She is an American gymnast|Biles
Michael Phelps|Michael Phelps|1985|American|sport|1|He won eight gold medals at the 2008 Olympics;He has won 23 Olympic gold medals;He is nicknamed the Baltimore Bullet;He is the most decorated Olympian of all time|Phelps
Tiger Woods|Tiger Woods|1975|American|sport|1|His real first name is Eldrick;He won the Masters in 1997 at age 21;He has won 15 major championships;He is a famous golfer|Eldrick Woods
Jesse Owens|Jesse Owens|1913|American|sport|2|He set three world records in 45 minutes in 1935;He was a star of Ohio State University;He won four gold medals at the 1936 Berlin Olympics;He was an American sprinter and long jumper|Owens
Nadia Comăneci|Nadia Comăneci|1961|Romanian|sport|2|The scoreboard could only show her perfect score as 1.00;She was just 14 at the 1976 Montreal Olympics;She was the first gymnast to score a perfect 10 at the Olympics;She is a Romanian gymnast|Nadia Comaneci
Wayne Gretzky|Wayne Gretzky|1961|Canadian|sport|2|He wore the number 99, now retired across the whole league;He played for the Edmonton Oilers;He is called the Great One;He is an ice hockey legend|Gretzky
Sachin Tendulkar|Sachin Tendulkar|1973|Indian|sport|2|He played his first Test match at 16;He scored 100 international centuries;He is nicknamed the Little Master;He is an Indian cricket legend|Tendulkar
Lewis Hamilton|Lewis Hamilton|1985|British|sport|1|He moved to Ferrari in 2025;He won six of his titles with Mercedes;He has won seven Formula One world titles;He is a British racing driver|Hamilton
Babe Ruth|Babe Ruth|1895|American|sport|2|His real name was George Herman Ruth;He was sold from the Boston Red Sox to the New York Yankees;He was nicknamed the Sultan of Swat;He was a baseball home-run legend|George Herman Ruth
Don Bradman|Don Bradman|1908|Australian|sport|3|He was nicknamed The Don;He needed only four runs in his last innings for an average of 100;His Test batting average was 99.94;He is regarded as the greatest cricket batsman ever|Bradman;Sir Donald Bradman
Martin Luther King Jr.|Martin Luther King Jr.|1929|American|activism|1|He led the Montgomery bus boycott;He won the Nobel Peace Prize in 1964;He gave the I Have a Dream speech;He was a leader of the US civil rights movement|MLK;Martin Luther King
Rosa Parks|Rosa Parks|1913|American|activism|1|She was a secretary of the NAACP in Montgomery;She was arrested in December 1955;She refused to give up her bus seat;She is called the mother of the civil rights movement|Parks
Anne Frank|Anne Frank|1929|German-born|activism|2|Her family moved from Germany to the Netherlands in the 1930s;She hid with her family in a secret annex in Amsterdam;She died in Bergen-Belsen concentration camp;Her diary is one of the most-read books about the Holocaust
Malala Yousafzai|Malala Yousafzai|1997|Pakistani|activism|1|She was shot by the Taliban in 2012;She studied at Oxford University;She became the youngest Nobel Prize winner;She campaigns for girls' education|Malala
Mother Teresa|Mother Teresa|1910|Albanian-Indian|religion|2|She was born in Skopje;She was made a saint in 2016;She won the Nobel Peace Prize in 1979;She cared for the poor in Kolkata|Saint Teresa of Calcutta
Joan of Arc|Joan of Arc|1412|French|history|2|She was burned at the stake in Rouen in 1431;She said she heard the voices of saints;She helped lift the Siege of Orléans;She was a teenage French heroine of the Hundred Years' War|Jeanne d'Arc;Maid of Orléans
Helen Keller|Helen Keller|1880|American|activism|2|She was the first deafblind person to earn a bachelor's degree;Her teacher was Anne Sullivan;She learned to communicate by finger-spelling into her hand;She lost her sight and hearing as a baby
Emmeline Pankhurst|Emmeline Pankhurst|1858|British|activism|3|Her daughters Christabel and Sylvia also campaigned;She founded the Women's Social and Political Union in 1903;Her followers were called suffragettes;She led the fight for women's right to vote in Britain|Pankhurst
Aristotle|Aristotle|-384|Greek|philosophy|2|He set up a school called the Lyceum;He was a student of Plato;He tutored Alexander the Great;He was an ancient Greek philosopher
Confucius|Confucius||Chinese|philosophy|2|His sayings were collected in the Analects;He lived during the Spring and Autumn period;He taught respect for family and elders;He was an ancient Chinese philosopher|Kong Fuzi
Karl Marx|Karl Marx|1818|German|philosophy|3|He is buried in Highgate Cemetery in London;He worked with Friedrich Engels;He wrote Das Kapital;He co-wrote The Communist Manifesto|Marx
Sigmund Freud|Sigmund Freud|1856|Austrian|science|2|He fled Vienna for London in 1938;He wrote The Interpretation of Dreams;He developed psychoanalysis;He is famous for his theories about the unconscious mind|Freud
Steve Jobs|Steve Jobs|1955|American|business|1|He also led the animation studio Pixar;He was pushed out of his own company in 1985 and later returned;He introduced the iPhone in 2007;He co-founded Apple|Jobs
Bill Gates|Bill Gates|1955|American|business|1|He dropped out of Harvard;He set up a huge charitable foundation with his then-wife Melinda;He co-founded his company with Paul Allen;He co-founded Microsoft|Gates
Henry Ford|Henry Ford|1863|American|business|2|He paid workers a then-high five dollars a day;He introduced the moving assembly line;He made the Model T;He founded a famous car company|Ford
Coco Chanel|Coco Chanel|1883|French|business|2|Her real first name was Gabrielle;She made the little black dress popular;She launched the perfume No. 5;She founded a famous French fashion house|Chanel;Gabrielle Chanel
Martin Luther|Martin Luther|1483|German|religion|3|He translated the Bible into German;He was excommunicated in 1521;He is said to have nailed 95 theses to a church door;He started the Protestant Reformation|Luther
`;

export const LEADERS = `
Julius Caesar|Julius Caesar|-100|Roman|leader|1|He was kidnapped by pirates as a young man;He crossed the Rubicon river with his army;He was stabbed to death on the Ides of March;He was a famous Roman general and dictator|Caesar
Cleopatra|Cleopatra|-69|Egyptian|leader|1|She was of Macedonian Greek descent;She had relationships with Julius Caesar and Mark Antony;She was the last active ruler of the Ptolemaic kingdom;She was a queen of ancient Egypt|Cleopatra VII
Alexander the Great|Alexander the Great|-356|Macedonian|leader|1|He was taught by Aristotle;His horse was called Bucephalus;He founded a famous city in Egypt named after himself;He built an empire from Greece to India|Alexander III of Macedon
Augustus|Augustus|-63|Roman|leader|2|He boasted that he found Rome a city of brick and left it a city of marble;His original name was Octavian;He defeated Antony and Cleopatra at Actium;The month of August is named after him;He was the first Roman emperor|Octavian;Caesar Augustus
Qin Shi Huang|Qin Shi Huang|-259|Chinese|leader|2|He standardised writing, coins and measurements;He linked older walls into an early Great Wall;He was buried with the Terracotta Army;He was the first emperor of a unified China|Shi Huangdi
Genghis Khan|Genghis Khan||Mongol|leader|1|He died in 1227;His birth name was Temüjin;He united the Mongol tribes in 1206;His empire became the largest connected land empire in history after his death;He founded the Mongol Empire|Temujin;Chinggis Khan
Charlemagne|Charlemagne||Frankish|leader|2|He died in 814;He was crowned emperor by the Pope on Christmas Day 800;He ruled from Aachen;His name means Charles the Great;He was King of the Franks|Charles the Great
Henry VIII|Henry VIII|1491|English|leader|1|He wrote a book defending the Pope before breaking with Rome;His navy included the warship Mary Rose;He broke away from the Catholic Church;He was a Tudor king who married six times|King Henry VIII
Elizabeth I|Elizabeth I|1533|English|leader|1|Her mother was Anne Boleyn;She never married and was called the Virgin Queen;Her navy defeated the Spanish Armada in 1588;She was the last Tudor monarch|Queen Elizabeth I
Louis XIV|Louis XIV|1638|French|leader|2|He reigned for 72 years, longer than any other European monarch;He moved the court to Versailles;He became king at the age of four;He was called the Sun King|Sun King
Peter the Great|Peter the Great|1672|Russian|leader|2|He defeated Sweden in the Great Northern War;He was over two metres tall;He built Russia's first proper navy;He travelled through Europe in disguise to learn shipbuilding;He taxed men who wore beards;He founded Saint Petersburg;He was a tsar who modernised Russia|Peter I of Russia
Catherine the Great|Catherine the Great|1729|Russian|leader|2|She was born a German princess;She seized the throne from her husband Peter III;She founded the collection of the Hermitage Museum;She was the longest-ruling female leader of Russia|Catherine II
George Washington|George Washington|1732|American|leader|1|He had false teeth made partly from human and animal teeth;He led the Continental Army in the American Revolution;His face is on the one-dollar bill;He was the first president of the United States|Washington
Napoleon|Napoleon Bonaparte|1769|French|leader|1|He was born on Corsica;He sold the Louisiana Territory to the United States;He was defeated at the Battle of Waterloo in 1815;He crowned himself Emperor of the French|Napoleon;Napoleon I
Simón Bolívar|Simón Bolívar|1783|Venezuelan|leader|2|A country is named after him;He was born in Caracas;He is called El Libertador;He led several South American countries to independence from Spain|Simon Bolivar;El Libertador
Queen Victoria|Queen Victoria|1819|British|leader|1|She was also Empress of India;She married her cousin Prince Albert;She reigned for over 63 years;An era of British history is named after her|Victoria
Abraham Lincoln|Abraham Lincoln|1809|American|leader|1|He grew up in a log cabin in Kentucky and Indiana;He gave the Gettysburg Address;He led the Union during the Civil War and abolished slavery;He was the 16th US president, assassinated in 1865|Lincoln;Abe Lincoln
Otto von Bismarck|Otto von Bismarck|1815|German|leader|3|A battleship and a US state capital share his name;He was called the Iron Chancellor;He worked to unify Germany in 1871;He was the first chancellor of the German Empire|Bismarck
Theodore Roosevelt|Theodore Roosevelt|1858|American|leader|2|The teddy bear is named after him;He led the Rough Riders in the Spanish-American War;He became president after William McKinley was assassinated;He was the 26th US president|Teddy Roosevelt;TR
Winston Churchill|Winston Churchill|1874|British|leader|1|He won the Nobel Prize in Literature in 1953;He was famous for his cigars and V-for-victory sign;He promised blood, toil, tears and sweat;He was Britain's prime minister during most of the Second World War|Churchill
Mahatma Gandhi|Mahatma Gandhi|1869|Indian|leader|1|He worked as a lawyer in South Africa;He led the Salt March in 1930;He used non-violent protest;He led India's independence movement against British rule|Gandhi;Mohandas Gandhi
Franklin D. Roosevelt|Franklin D. Roosevelt|1882|American|leader|2|He gave radio talks called fireside chats;He used a wheelchair after polio;He introduced the New Deal;He was the only US president elected four times|FDR;Franklin Roosevelt
Haile Selassie|Haile Selassie|1892|Ethiopian|leader|3|He is revered as a messiah by the Rastafari movement;He spoke at the League of Nations in 1936;His name before he was crowned was Ras Tafari;He was the last emperor of Ethiopia
Mao Zedong|Mao Zedong|1893|Chinese|leader|2|His sayings were collected in the Little Red Book;He led the Long March;He proclaimed the People's Republic of China in 1949;He founded the People's Republic of China|Chairman Mao
Charles de Gaulle|Charles de Gaulle|1890|French|leader|3|Paris's main airport is named after him;He led the Free French from London during the Second World War;He founded the Fifth Republic;He was President of France from 1959 to 1969|De Gaulle
John F. Kennedy|John F. Kennedy|1917|American|leader|1|He wrote Profiles in Courage;He faced the Cuban Missile Crisis;He promised to land a man on the Moon;He was the 35th US president, assassinated in Dallas in 1963|JFK;Kennedy
Nelson Mandela|Nelson Mandela|1918|South African|leader|1|His clan name was Madiba;He spent 27 years in prison, many on Robben Island;He shared the Nobel Peace Prize in 1993;He was South Africa's first Black president|Mandela;Madiba
Indira Gandhi|Indira Gandhi|1917|Indian|leader|3|Her father was India's first prime minister;She declared a state of emergency in 1975;She was assassinated in 1984;She was India's first female prime minister
Golda Meir|Golda Meir|1898|Israeli|leader|3|She was born in Kyiv and grew up in Milwaukee;She was nicknamed the Iron Lady of Israeli politics;She signed Israel's Declaration of Independence;She was Israel's first female prime minister
Margaret Thatcher|Margaret Thatcher|1925|British|leader|2|She trained as a chemist;She was nicknamed the Iron Lady;She led Britain during the Falklands War;She was Britain's first female prime minister|Thatcher
Angela Merkel|Angela Merkel|1954|German|leader|2|She trained as a quantum chemist;She grew up in East Germany;She led Germany from 2005 to 2021;She was Germany's first female chancellor|Merkel
Barack Obama|Barack Obama|1961|American|leader|1|He was born in Hawaii;He won the Nobel Peace Prize in 2009;His campaign slogan was Yes We Can;He was the 44th and first African American US president|Obama
Elizabeth II|Elizabeth II|1926|British|leader|1|She served as a mechanic in the Second World War;She became queen while in Kenya in 1952;She reigned for 70 years;She was the longest-reigning British monarch|Queen Elizabeth II
Akbar|Akbar|1542|Mughal|leader|3|He founded a new capital at Fatehpur Sikri;He held debates between people of different religions;He became emperor at 13;He was the third Mughal emperor of India|Akbar the Great
`;

export const EXPLORERS = `
Marco Polo|Marco Polo|1254|Venetian|explorer|1|He told his stories to a writer while in prison in Genoa;He travelled the Silk Road with his father and uncle;He served the Mongol ruler Kublai Khan;He was a Venetian traveller who wrote about China
Ibn Battuta|Ibn Battuta|1304|Moroccan|explorer|3|He was born in Tangier;He travelled for nearly 30 years;He covered more distance than any known traveller before the steam age;He was a Muslim explorer of Africa and Asia
Zheng He|Zheng He|1371|Chinese|explorer|3|He was a Muslim admiral of the Ming dynasty;His treasure ships were among the largest wooden ships ever built;He led seven voyages to Asia and East Africa;He was a Chinese admiral and explorer
Christopher Columbus|Christopher Columbus|1451|Genoese|explorer|1|He was born in Genoa;He thought he had reached Asia;His ships included the Niña, the Pinta and the Santa María;He sailed across the Atlantic for Spain in 1492|Columbus;Cristoforo Colombo
Ferdinand Magellan|Ferdinand Magellan|1480|Portuguese|explorer|1|He was killed in the Philippines in 1521;A strait at the tip of South America is named after him;He named the Pacific Ocean;He led the first expedition to sail around the world|Magellan
Hernán Cortés|Hernán Cortés|1485|Spanish|explorer|3|He landed on the coast of Mexico in 1519;He met the ruler Moctezuma II;He is called a conquistador;He brought about the fall of the Aztec Empire|Hernan Cortes;Cortez
Abel Tasman|Abel Tasman|1603|Dutch|explorer|3|He worked for the Dutch East India Company;He was the first known European to reach New Zealand;An island state of Australia is named after him;He was a Dutch seafarer|Tasman
James Cook|James Cook|1728|British|explorer|1|He was killed in Hawaii in 1779;He mapped the coast of New Zealand;His ship on his first voyage was HMS Endeavour;He charted the east coast of Australia|Captain Cook
David Livingstone|David Livingstone|1813|Scottish|explorer|1|He was a missionary doctor;He was the first European to see Victoria Falls;A journalist found him with the words Dr Livingstone, I presume?;He was a Scottish explorer of Africa|Dr Livingstone
Matthew Henson|Matthew Henson|1866|American|explorer|3|He spoke the Inuit language;He travelled with Robert Peary for over 20 years;He was part of the 1909 expedition that claimed to reach the North Pole;He was an African American Arctic explorer|Henson
Robert Falcon Scott|Robert Falcon Scott|1868|British|explorer|1|His ship on his first Antarctic expedition was the Discovery;He died on the return journey in 1912;He reached the South Pole a month after Roald Amundsen;He led the doomed Terra Nova expedition|Captain Scott
Roald Amundsen|Roald Amundsen|1872|Norwegian|explorer|1|He was the first to sail through the Northwest Passage;He relied on sled dogs to reach his goal;He reached the South Pole in December 1911;He was the first person to reach the South Pole|Amundsen
Ernest Shackleton|Ernest Shackleton|1874|Irish-born British|explorer|1|He sailed 1,300 km in a small lifeboat to get help;His ship Endurance was crushed by ice;He led an expedition that tried to cross Antarctica;He brought all his men home after their ship sank|Shackleton
Amelia Earhart|Amelia Earhart|1897|American|explorer|1|She vanished over the Pacific in 1937;She tried to fly around the world;She was the first woman to fly solo across the Atlantic;She was a famous American aviator|Earhart
Charles Lindbergh|Charles Lindbergh|1902|American|explorer|2|His aircraft was called the Spirit of St. Louis;He flew from New York to Paris in 1927;He won a large cash prize for his flight;He made the first solo non-stop flight across the Atlantic|Lindbergh
Jacques Cousteau|Jacques Cousteau|1910|French|explorer|2|His ship was called Calypso;He made films about life under the sea;He co-invented the Aqua-Lung;He was a French ocean explorer|Cousteau
Tenzing Norgay|Tenzing Norgay|1914|Nepali|explorer|1|He was a Sherpa from the Khumbu region;He had tried to climb the mountain six times before;He reached the summit in 1953 with Edmund Hillary;He was one of the first two people to climb Everest|Tenzing
Edmund Hillary|Edmund Hillary|1919|New Zealander|explorer|1|He was a beekeeper;He drove a tractor to the South Pole;He reached the top of Everest in 1953 with Tenzing Norgay;He was one of the first two people to climb Mount Everest|Hillary;Sir Edmund Hillary
Neil Armstrong|Neil Armstrong|1930|American|explorer|1|He was a test pilot who flew the X-15 rocket plane;He commanded Gemini 8;He said That's one small step for man;He was the first person to walk on the Moon|Armstrong
Buzz Aldrin|Buzz Aldrin|1930|American|explorer|1|He was born Edwin Aldrin;He was the pilot of the lunar module Eagle;He walked on the Moon with Neil Armstrong;He was the second person to walk on the Moon|Edwin Aldrin
Yuri Gagarin|Yuri Gagarin|1934|Soviet|explorer|1|He died in a jet crash in 1968;His spacecraft was called Vostok 1;He orbited the Earth once in 1961;He was the first human in space|Gagarin
Valentina Tereshkova|Valentina Tereshkova|1937|Soviet|explorer|1|She was a factory worker and amateur parachutist;Her call sign was Chaika, meaning seagull;She flew Vostok 6 in 1963;She was the first woman in space|Tereshkova
Sally Ride|Sally Ride|1951|American|explorer|2|She had a PhD in physics;She flew on the space shuttle Challenger;She was the youngest American in space at the time;She was the first American woman in space|Ride
`;

export const ARTISTS = `
Leonardo da Vinci|Leonardo da Vinci|1452|Italian|Renaissance|1|He wrote his notes in mirror writing;He drew designs for flying machines;He painted The Last Supper;He painted the Mona Lisa|Leonardo;Da Vinci
Michelangelo|Michelangelo|1475|Italian|Renaissance|1|He designed the dome of St Peter's Basilica;He carved the statue of David;He painted the ceiling of the Sistine Chapel;He was a great Italian Renaissance sculptor and painter|Michelangelo Buonarroti
Raphael|Raphael|1483|Italian|Renaissance|1|He died on his 37th birthday;He painted the Sistine Madonna;He painted The School of Athens;He was one of the great painters of the High Renaissance|Raffaello Sanzio
Albrecht Dürer|Albrecht Dürer|1471|German|Renaissance|3|He made a famous woodcut of a rhinoceros he never saw;He painted a famous watercolour of a young hare;He was born in Nuremberg;He was a master of printmaking|Albrecht Durer;Dürer
Caravaggio|Caravaggio|1571|Italian|Baroque|3|He killed a man and fled Rome;He painted The Calling of Saint Matthew;He used dramatic light and shadow;He was a rebellious Baroque painter|Michelangelo Merisi da Caravaggio
Diego Velázquez|Diego Velázquez|1599|Spanish|Baroque|3|He painted Pope Innocent X;He was court painter to King Philip IV;He painted himself at work in Las Meninas;He was a great Spanish painter|Velazquez
Rembrandt|Rembrandt|1606|Dutch|Baroque|1|He painted dozens of self-portraits;He went bankrupt in 1656;He painted The Night Watch;He was a master of the Dutch Golden Age|Rembrandt van Rijn
Johannes Vermeer|Johannes Vermeer|1632|Dutch|Baroque|1|Only around 35 of his paintings survive;He worked in Delft;He painted The Milkmaid;He painted Girl with a Pearl Earring|Vermeer
Francisco Goya|Francisco Goya|1746|Spanish|Romanticism|3|He became deaf after an illness;He painted dark pictures on the walls of his house;He painted The Third of May 1808;He was a Spanish court painter|Goya
Katsushika Hokusai|Katsushika Hokusai|1760|Japanese|Ukiyo-e|1|He used more than 30 different names;He made a series called Thirty-six Views of Mount Fuji;He was a master of woodblock prints;He made The Great Wave off Kanagawa|Hokusai
J. M. W. Turner|J. M. W. Turner|1775|English|Romanticism|3|He is said to have had himself tied to a ship's mast to see a storm;He appears on the Bank of England £20 note;He painted The Fighting Temeraire;He was famous for stormy seas and glowing light|Turner;JMW Turner
John Constable|John Constable|1776|English|Romanticism|3|He painted the countryside around the River Stour;He rarely left England;He painted The Hay Wain;He was an English landscape painter|Constable
Claude Monet|Claude Monet|1840|French|Impressionism|1|His painting Impression, Sunrise gave a movement its name;He painted haystacks and cathedrals at different times of day;He built a garden with a Japanese bridge at Giverny;He painted water lilies|Monet
Pierre-Auguste Renoir|Pierre-Auguste Renoir|1841|French|Impressionism|3|He kept painting with brushes strapped to his hands;He painted Dance at Le Moulin de la Galette;He painted Luncheon of the Boating Party;He was a French Impressionist|Renoir
Edgar Degas|Edgar Degas|1834|French|Impressionism|2|His eyesight failed in later life;He made a sculpture called Little Dancer Aged Fourteen;He painted horse races;He is famous for paintings of ballet dancers|Degas
Paul Cézanne|Paul Cézanne|1839|French|Post-Impressionism|3|He painted Mont Sainte-Victoire many times;He painted The Card Players;He is often called the father of modern art;He was famous for still lifes of apples|Cezanne
Paul Gauguin|Paul Gauguin|1848|French|Post-Impressionism|3|He once worked as a stockbroker;He lived with Van Gogh in Arles for a few weeks;He moved to Tahiti;He painted bright scenes of Polynesian life|Gauguin
Vincent van Gogh|Vincent van Gogh|1853|Dutch|Post-Impressionism|1|His brother Theo supported him;He sold very few paintings in his lifetime;He cut off part of his own ear;He painted The Starry Night and Sunflowers|Van Gogh
Georges Seurat|Georges Seurat|1859|French|Post-Impressionism|3|He died at 31;He painted Bathers at Asnières;He painted A Sunday Afternoon on the Island of La Grande Jatte;He painted with tiny dots of colour|Seurat
Gustav Klimt|Gustav Klimt|1862|Austrian|Art Nouveau|1|He founded the Vienna Secession;He painted a famous portrait of Adele Bloch-Bauer;He used real gold leaf;He painted The Kiss|Klimt
Edvard Munch|Edvard Munch|1863|Norwegian|Expressionism|1|He painted Madonna and The Sick Child;Versions of his most famous work have been stolen twice;He made several versions of the same famous image;He painted The Scream|Munch
Wassily Kandinsky|Wassily Kandinsky|1866|Russian|Abstract|3|He taught at the Bauhaus;He linked colours to musical sounds;He was born in Moscow;He was a pioneer of abstract art|Kandinsky
Henri Matisse|Henri Matisse|1869|French|Fauvism|1|In later life he made art from painted paper cut-outs;He painted The Dance;He led the Fauves, or wild beasts;He was famous for bold, bright colour|Matisse
Pablo Picasso|Pablo Picasso|1881|Spanish|Cubism|1|His full name has more than 20 words;He went through a Blue Period;He painted Guernica;He co-founded Cubism|Picasso
Edward Hopper|Edward Hopper|1882|American|Realism|3|He painted lonely city scenes;He painted Automat;He painted people in a late-night diner;He painted Nighthawks|Hopper
Georgia O'Keeffe|Georgia O'Keeffe|1887|American|Modernism|3|She was married to the photographer Alfred Stieglitz;She lived in New Mexico;She painted animal skulls in the desert;She painted giant close-up flowers|O'Keeffe
Grant Wood|Grant Wood|1891|American|Regionalism|3|He came from Iowa;His most famous models were his sister and his dentist;He painted a farmer holding a pitchfork;He painted American Gothic|Wood
René Magritte|René Magritte|1898|Belgian|Surrealism|2|He painted a pipe with the words This is not a pipe;He painted men in bowler hats;He painted a man with an apple in front of his face;He was a Belgian Surrealist|Magritte;Rene Magritte
Salvador Dalí|Salvador Dalí|1904|Spanish|Surrealism|1|He designed the Chupa Chups logo;He had a long, upturned moustache;He painted melting clocks in The Persistence of Memory;He was a famous Surrealist|Dali;Salvador Dali
Frida Kahlo|Frida Kahlo|1907|Mexican|Surrealism|1|She was badly injured in a bus accident as a teenager;She married the painter Diego Rivera;She lived in the Blue House in Mexico City;She painted many self-portraits with flowers in her hair|Kahlo
Jackson Pollock|Jackson Pollock|1912|American|Abstract Expressionism|3|He was nicknamed Jack the Dripper;He worked with his canvases laid flat on the floor;He dripped and poured paint;He was a leading Abstract Expressionist|Pollock
Roy Lichtenstein|Roy Lichtenstein|1923|American|Pop Art|3|He painted Whaam!;He copied the dots used in cheap printing;He made paintings that look like comic strips;He was an American Pop artist|Lichtenstein
Andy Warhol|Andy Warhol|1928|American|Pop Art|1|His studio was called the Factory;He said everyone would be famous for 15 minutes;He made colourful prints of Marilyn Monroe;He painted Campbell's soup cans|Warhol
Yayoi Kusama|Yayoi Kusama|1929|Japanese|Contemporary|3|She has lived by choice in a psychiatric hospital in Tokyo since 1977;She makes mirror rooms that seem to go on forever;She makes giant pumpkin sculptures;She is famous for polka dots
`;
