import {fillSquad,settleRoster,rank} from './roster.mjs';
import {createWorld,snapTo,fortify} from './world.mjs';
import {beginMission} from './mission.mjs';
import {MISSIONS} from '../data/missions.mjs';
import clearing from '../data/maps/clearing.mjs';
import ravine from '../data/maps/ravine.mjs';
const MAPS={clearing,ravine};
// `taught` is the coaching ledger: once the player has demonstrated a skill it is never
// explained to him again, in this mission or any later one.
export function newCampaign(){return {version:1,mission:0,credits:0,roster:[],slots:[],nextRecruit:0,maps:{},upgrades:{armour:0,rifle:0,slots:1},inProgress:null,history:[],taught:{}};}
export function parseSave(raw){try{const c=typeof raw==='string'?JSON.parse(raw):raw;if(c&&!c.taught)c.taught={};if(!c||c.version!==1||!Number.isInteger(c.mission)||c.mission<0||c.mission>MISSIONS.length||!Array.isArray(c.roster)||!Array.isArray(c.slots)||!c.maps||!c.upgrades)return newCampaign();return c;}catch{return newCampaign();}}
export function campaignWorld(c,{resume=true}={}){const def=MISSIONS[Math.min(c.mission,MISSIONS.length-1)],men=fillSquad(c,def.count),map=MAPS[def.map];const w=createWorld({map,count:def.count,enemies:def.enemies,mix:def.mix,enemyZ:def.enemyZ});const territory=c.maps[def.map];if(territory){for(const id of territory.burned||[]){const t=w.trees[id];if(t){t.dead=true;t.hp=0;t.fallTime=-10;}}if(territory.fortified)fortify(w);w.grid.rebuild();w.forestRevision++;}const kit=['rifle'];if(c.mission>=2&&c.upgrades.slots>=2)kit.push('grenade');if(c.mission>=3&&c.upgrades.slots>=2)kit.push('flamer');w.equipped=kit;w.units.filter(u=>u.team==='blue').forEach((u,i)=>{const man=men[i];u.rosterId=man.id;u.name=rank(man)+' '+man.name;u.veterancy=man.xp;u.hp=u.maxHp=100+c.upgrades.armour*25;u.damageBonus=c.upgrades.rifle*.15;const p=snapTo(w.grid,u.x,def.spawnZ??map.spawn.z+Math.floor(i/2)*1.6);u.x=p.x;u.z=p.z;});beginMission(w,def);
 if(resume&&c.inProgress?.missionId===def.id){const s=c.inProgress;if(s.cover)for(const c of s.cover)Object.assign(w.cover.find(p=>p.id===c.id)||{},c);w.units=s.units;w.time=s.time;w.fireClock=s.fireClock||0;w.target=s.target||null;w.mission=s.mission;w.grenades=s.grenades;w.projectiles=s.projectiles;w.random.setState(s.randomState);for(const t of s.trees)Object.assign(w.trees[t.id],t);w.grid.rebuild();w.forestRevision++;w.fortified=s.fortified;if(s.works)w.works=s.works;w.fires=s.fires||[];w.armed=s.armed||null;w.split=s.split||0;for(const u of w.units)if(u.hp<=0)w.events.push({id:++w.eventId,time:w.time,type:'death',x:u.x,z:u.z,unit:u.id});}
 return w;}
// Instant retry. A mission is ninety seconds and the men are permanent, so a loss has to cost a
// tap rather than a funeral — but only back to the state you deployed in. Everything a lost
// mission changed (dead men, spent credits, burn scars, the mission counter) is rolled back
// together, or retrying becomes a way to farm brass off your own casualties.
export function markDeployment(c){c.rewind={mission:c.mission,credits:c.credits,nextRecruit:c.nextRecruit,slots:[...c.slots],roster:structuredClone(c.roster),upgrades:{...c.upgrades},maps:structuredClone(c.maps)};return c;}
export const canRetry=c=>!!c.rewind;
export function rewind(c){const r=c.rewind;if(!r)return false;c.mission=r.mission;c.credits=r.credits;c.nextRecruit=r.nextRecruit;c.slots=[...r.slots];c.roster=structuredClone(r.roster);c.upgrades={...r.upgrades};c.maps=structuredClone(r.maps);c.inProgress=null;if(c.history.at(-1)&&!c.history.at(-1).win)c.history.pop();return true;}
export function snapshotWorld(w){return {missionId:w.mission.id,time:w.time,fireClock:w.fireClock||0,target:w.target,mission:structuredClone(w.mission),units:structuredClone(w.units),cover:structuredClone(w.cover),trees:w.trees.filter(t=>t.dead||t.burn>0||t.charred).map(t=>({...t})),grenades:structuredClone(w.grenades),projectiles:structuredClone(w.projectiles),randomState:w.random.getState(),fortified:!!w.fortified,works:structuredClone(w.works||null),fires:structuredClone(w.fires||[]),armed:w.armed?{...w.armed}:null,split:w.split||0};}
export function finishMission(c,w){settleRoster(c,w);const win=w.mission.status==='victory';c.maps[w.map.id]={burned:w.trees.filter(t=>t.dead).map(t=>t.id),fortified:win||!!w.fortified};const result={id:w.mission.id,title:w.mission.title,win,kills:w.units.filter(u=>u.team==='red'&&u.hp<=0).length,losses:w.units.filter(u=>u.team==='blue'&&!u.escort&&u.hp<=0).length,seconds:Math.ceil(w.mission.elapsed),reward:win?w.mission.reward:0,reason:w.mission.reason};c.history.push(result);if(win){c.credits+=result.reward;c.mission++;}c.inProgress=null;return result;}
