/**
 * The HUD's ink, and the one drawing rule ART §10 states numerically:
 *
 *   every UI element is drawn TWICE — a 2 px dark outline at alpha 0.55
 *   (offset 0,0, an outline, not a drop shadow), then the element; and
 *   anything whose luminance lands between 0.35 and 0.65 also gets a 1 px
 *   light inner edge.
 *
 * That single rule is what removes every per-act UI exception, so it lives in
 * one primitive (`mark`) and nothing in `js/ui/` draws outside it.
 *
 * NO PIXEL NUMBERS HERE. Weights come from `layout.js`'s METRICS (gate H1).
 * Alphas and colours are not pixel offsets and do live here, because they are
 * the palette.
 *
 * Pure enough for node: `srgb`, `lum`, `contrast` and `composite` are what
 * `tools/hudcheck.mjs` measures H3 with — it imports these, it does not keep a
 * second copy of them (D72).
 */

import { METRICS } from './layout.js';
import { srgb, lum, contrast, composite, rgba } from './colour.js';

export { srgb, hex, lum, contrast, composite, rgba, mixHex } from './colour.js';

/* --------------------------------------------------------------- colour --- */

export const INK = Object.freeze({
  /** The outline. Darker and heavier than ART's literal 0.55 — see H3 in P7_NOTES. */
  outline: '#04060a',
  outlineA: 0.62,

  /** The light inner edge, for fills that land in the 0.35-0.65 luminance trap. */
  inner: '#f4efe2',
  innerA: 0.55,

  bright: '#f2ead8',        // primary marks: the player chevron, numerals
  ink: '#e2d8c2',           // ordinary type
  brass: '#e8c47a',         // the coaming's instruments
  hostile: '#ff8a5c',       // ART's warm red-orange trim
  hostileHot: '#ff5a3c',    // a live firing solution
  friendly: '#cfe4f2',      // pale blue-white
  crate: '#ffd479',         // gold
  objective: '#ffffff',
  warn: '#ffb24d',
  danger: '#ff6a4d',

  tapeBody: '#0d1119',
  tapeBodyA: 0.35,          // ART §10: 0.35 for the ribbon body...
  tapeMarkA: 0.85,          // ...0.85 for the marker and the band boundaries
  coamA: 0.82,
  glassA: 0.72,
  stickA: 0.30,
});

/** Neutral band ramp, used when no act LUT has been handed in. */
export const NEUTRAL_RAMP = Object.freeze({
  key: '#d9d2c0', fill: '#8d8f92', shadow: '#2b3038', accent: '#c2582a',
});

/** Mid-luminance fills lose their edge against both grounds; ART §10's 1 px fix. */
export const needsInner = (c) => { const l = lum(c); return l >= 0.35 && l <= 0.65; };

/* ---------------------------------------------------------------- paint --- */

/**
 * Draw one mark twice. `path(g)` must emit the geometry; it is called up to
 * three times, so it must not have side effects beyond the path.
 *
 * `fill` and `stroke` are exclusive per call in the sense that a filled mark is
 * outlined by STROKING the same path at OUTLINE_W before filling, which is what
 * "drawn twice, offset 0,0" means. A stroked mark is stroked wide-and-dark then
 * narrow-and-light.
 */
export function mark(g, path, o) {
  const col = o.col || INK.bright;
  const a = o.a === undefined ? 1 : o.a;
  const w = o.w || METRICS.HAIRLINE;
  const outlineA = (o.outlineA === undefined ? INK.outlineA : o.outlineA) * (o.dim || 1);

  g.lineJoin = 'round';
  g.lineCap = o.cap || 'round';

  g.beginPath(); path(g);
  g.strokeStyle = rgba(INK.outline, outlineA);
  g.lineWidth = w + METRICS.OUTLINE_W * 2;
  g.stroke();

  if (o.fill) {
    g.fillStyle = rgba(col, a);
    g.fill(o.rule || 'nonzero');
    if (w > 0) { g.strokeStyle = rgba(col, a); g.lineWidth = w; g.stroke(); }
  } else {
    g.strokeStyle = rgba(col, a);
    g.lineWidth = w;
    g.stroke();
  }

  if (needsInner(srgb(col))) {
    g.beginPath(); path(g);
    g.strokeStyle = rgba(INK.inner, INK.innerA * a);
    g.lineWidth = METRICS.INNER_W;
    g.stroke();
  }
}

/** The same rule for text. Stroke the glyphs dark, then fill them. */
export function label(g, text, x, y, o = {}) {
  const col = o.col || INK.ink;
  const a = o.a === undefined ? 1 : o.a;
  g.textAlign = o.align || 'left';
  g.textBaseline = o.baseline || 'middle';
  g.lineJoin = 'round';
  g.strokeStyle = rgba(INK.outline, (o.outlineA === undefined ? INK.outlineA : o.outlineA));
  g.lineWidth = METRICS.OUTLINE_W * 2;
  g.strokeText(text, x, y);
  g.fillStyle = rgba(col, a);
  g.fillText(text, x, y);
}

/**
 * The typeface. ONE vendored stencil face, local WOFF2, never a CDN (D6).
 * `vendor/kitehawk-stencil.woff2` is generated by `art/tools/mkstencil.py` and
 * committed; the fallback stack is entirely local system faces, so a missing
 * font file degrades to a readable HUD rather than to a blank one.
 */
export const FONT_FAMILY = '"Kitehawk Stencil", "DIN Condensed", "Oswald", ui-sans-serif, system-ui, sans-serif';
export const font = (size, weight) =>
  `${weight || 600} ${size}px/1 ${FONT_FAMILY}`;

/**
 * H3, computed rather than eyeballed. An element is a TWO-TONE mark: the dark
 * outline and the light fill. Against white the outline is what separates it;
 * against night the fill is. Returns both readings plus the naive one.
 */
export function markContrast(fillHex, bgHex, outlineHex = INK.outline, outlineA = INK.outlineA, fillA = 1) {
  const bg = srgb(bgHex);
  const ol = composite(srgb(outlineHex), bg, outlineA);
  const fl = composite(srgb(fillHex), ol, fillA);
  return {
    outlineVsBg: contrast(ol, bg),
    fillVsOutline: contrast(fl, ol),
    fillVsBg: contrast(fl, bg),
    best: Math.max(contrast(ol, bg), contrast(fl, bg)),
  };
}
