import { M, T, N, O } from './lib.mjs';

export default [
  // science
  M('sci', 1, "What is the chemical symbol for gold?", "Au", ["Ag", "Gd", "Go"], "Au comes from aurum, the Latin word for gold."),
  M('sci', 2, "What is the chemical symbol for silver?", "Ag", ["Au", "Si", "Sv"], "Ag comes from argentum, Latin for silver."),
  M('sci', 2, "What is the chemical symbol for iron?", "Fe", ["Ir", "In", "I"], "Fe comes from ferrum, Latin for iron."),
  M('sci', 3, "What is the chemical symbol for sodium?", "Na", ["So", "Sd", "S"], "Na comes from natrium, the Latin name for sodium."),
  M('sci', 3, "What is the chemical symbol for potassium?", "K", ["P", "Po", "Pt"], "K comes from kalium, the Latin name for potassium."),
  M('sci', 3, "What is the chemical symbol for lead?", "Pb", ["Ld", "Le", "Pd"], "Pb comes from plumbum, Latin for lead (and the root of 'plumber')."),
  M('sci', 3, "What is the chemical symbol for tin?", "Sn", ["Ti", "Tn", "Sb"], "Sn comes from stannum, Latin for tin."),
  M('sci', 1, "What is the chemical formula for water?", "H2O", ["CO2", "H2O2", "HO2"], "Each water molecule has two hydrogen atoms and one oxygen atom."),
  M('sci', 2, "Which gas makes up most of Earth's atmosphere?", "Nitrogen", ["Oxygen", "Argon", "Carbon dioxide"], "Nitrogen is about 78% of the air; oxygen is about 21%."),
  M('sci', 1, "Which gas do plants take in from the air to make food?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"], "Plants turn carbon dioxide and water into sugar using sunlight."),
  M('sci', 1, "What is the lightest chemical element?", "Hydrogen", ["Helium", "Lithium", "Oxygen"], "Hydrogen has atomic number 1 and is the lightest element."),
  M('sci', 2, "Which element has the atomic number 6?", "Carbon", ["Oxygen", "Nitrogen", "Boron"], "Carbon has six protons; it is the basis of all known life."),
  N('sci', 1, "At sea level, at what temperature in Celsius does water boil?", 100, "°C", 0, "Pure water boils at 100 °C at standard sea-level pressure."),
  N('sci', 2, "At what temperature in Fahrenheit does water freeze?", 32, "°F", 0, "Water freezes at 32 °F, which is 0 °C."),
  N('sci', 3, "Roughly how many kilometres per second does light travel in a vacuum?", 299792, "km/s", 10000, "Light travels at about 299,792 km every second."),
  M('sci', 1, "What is the hardest natural mineral?", "Diamond", ["Quartz", "Topaz", "Corundum"], "Diamond scores 10, the top of the Mohs hardness scale."),
  N('sci', 2, "What is the pH of pure water at 25 °C?", 7, "", 0, "A pH of 7 is neutral: neither acidic nor alkaline."),
  M('sci', 2, "What is the unit of electrical resistance?", "Ohm", ["Volt", "Ampere", "Watt"], "Resistance is measured in ohms, named after Georg Ohm."),
  M('sci', 2, "What is the SI unit of force?", "Newton", ["Joule", "Pascal", "Watt"], "One newton accelerates one kilogram by one metre per second squared."),
  M('sci', 2, "What is the SI unit of energy?", "Joule", ["Newton", "Watt", "Kelvin"], "The joule is named after the physicist James Prescott Joule."),
  M('sci', 2, "Which unit measures frequency?", "Hertz", ["Decibel", "Tesla", "Henry"], "One hertz is one cycle per second."),
  M('sci', 1, "Who proposed the theory of evolution by natural selection in 'On the Origin of Species'?", "Charles Darwin", ["Gregor Mendel", "Louis Pasteur", "Jean-Baptiste Lamarck"], "Darwin published On the Origin of Species in 1859."),
  M('sci', 1, "Who discovered penicillin in 1928?", "Alexander Fleming", ["Louis Pasteur", "Joseph Lister", "Edward Jenner"], "Fleming noticed mould killing bacteria in a dish in his London lab."),
  M('sci', 3, "Who developed the first vaccine, against smallpox, in 1796?", "Edward Jenner", ["Louis Pasteur", "Alexander Fleming", "Robert Koch"], "Jenner used material from cowpox to protect against smallpox."),
  T('sci', 2, "Marie Curie was the first person to win Nobel Prizes in two different sciences.", true, "She won the Physics prize in 1903 and the Chemistry prize in 1911."),
  M('sci', 2, "Which scientist's experiments with pea plants founded the science of genetics?", "Gregor Mendel", ["Charles Darwin", "James Watson", "Louis Pasteur"], "Mendel, a monk, worked out the rules of inheritance in the 1860s."),
  M('sci', 3, "Who published the first widely recognised periodic table in 1869?", "Dmitri Mendeleev", ["Antoine Lavoisier", "John Dalton", "Niels Bohr"], "Mendeleev even left gaps for elements that had not yet been discovered."),
  N('sci', 3, "Absolute zero is about how many degrees Celsius?", -273, "°C", 1, "Absolute zero is −273.15 °C, or 0 kelvin."),
  M('sci', 1, "Which metal is a liquid at room temperature?", "Mercury", ["Lead", "Aluminium", "Tin"], "Mercury melts at about −39 °C, so it is liquid at room temperature."),
  M('sci', 1, "Which gas is used to make party balloons float?", "Helium", ["Oxygen", "Nitrogen", "Carbon dioxide"], "Helium is much lighter than air and does not burn."),
  T('sci', 2, "Sound travels more slowly through water than through air.", false, "Sound moves about four times faster in water than in air."),
  T('sci', 1, "Sound can travel through the vacuum of space.", false, "Sound needs a material such as air or water to travel through."),
  M('sci', 1, "Who formulated the three laws of motion?", "Isaac Newton", ["Galileo Galilei", "Johannes Kepler", "Albert Einstein"], "Newton published his laws of motion in 1687."),
  M('sci', 1, "Which scientist is famous for the equation E = mc²?", "Albert Einstein", ["Isaac Newton", "Niels Bohr", "Max Planck"], "E = mc² says mass and energy are two forms of the same thing."),
  T('sci', 1, "Rust forms when iron reacts with oxygen and water.", true, "Rust is iron oxide, made when iron meets oxygen and moisture."),
  T('sci', 2, "Diamond and graphite are both made of carbon.", true, "The same carbon atoms, arranged differently, give very different materials."),
  T('sci', 3, "A molecule of ozone is made of three oxygen atoms.", true, "Ozone is O3; the oxygen we breathe is O2."),
  T('sci', 1, "A proton carries a negative electric charge.", false, "Protons are positive; electrons are negative; neutrons have no charge."),
  M('sci', 3, "What is the most abundant element in the universe?", "Hydrogen", ["Helium", "Oxygen", "Carbon"], "About three quarters of the normal matter in the universe is hydrogen."),
  M('sci', 3, "What is the most abundant element in Earth's crust?", "Oxygen", ["Silicon", "Iron", "Aluminium"], "Oxygen makes up nearly half of the crust, locked into rocks and minerals."),
  M('sci', 2, "Which colour of visible light has the longest wavelength?", "Red", ["Violet", "Green", "Blue"], "Red light has the longest wavelength we can see; violet the shortest."),
  M('sci', 2, "What does a barometer measure?", "Air pressure", ["Temperature", "Humidity", "Wind speed"], "Falling air pressure on a barometer often means bad weather is coming."),
  M('sci', 2, "Which instrument records earthquakes?", "Seismograph", ["Barometer", "Altimeter", "Odometer"], "A seismograph records the shaking of the ground."),
  M('sci', 3, "Who discovered X-rays in 1895?", "Wilhelm Röntgen", ["Marie Curie", "Niels Bohr", "Ernest Rutherford"], "Röntgen won the first Nobel Prize in Physics, in 1901, for X-rays."),
  M('sci', 2, "What is the chemical formula of table salt?", "NaCl", ["KCl", "NaOH", "CaCO3"], "Table salt is sodium chloride."),
  M('sci', 2, "Dry ice is the solid form of which substance?", "Carbon dioxide", ["Nitrogen", "Water", "Oxygen"], "Dry ice turns straight from solid to gas at about −78 °C."),
  M('sci', 3, "What is the chemical name for baking soda?", "Sodium bicarbonate", ["Sodium chloride", "Calcium carbonate", "Potassium nitrate"], "Baking soda (sodium hydrogen carbonate) releases carbon dioxide when heated or mixed with acid."),
  O('sci', 3, "Put these in order of boiling point, lowest first.", ["Nitrogen", "Ethanol", "Water", "Iron"], "Lowest boiling point first", "Nitrogen boils at −196 °C, ethanol 78 °C, water 100 °C and iron about 2,860 °C."),
  M('sci', 2, "Who first described DNA's double-helix structure in 1953, using Rosalind Franklin's X-ray data?", "James Watson and Francis Crick", ["Pierre and Marie Curie", "Charles Darwin and Alfred Wallace", "Frederick Banting and Charles Best"], "Franklin's X-ray image known as Photo 51 was key to the discovery."),
  T('sci', 2, "Green is one of the three primary colours of light.", true, "The primary colours of light are red, green and blue (RGB)."),
  M('sci', 3, "What is the speed of sound in air at about 20 °C, to the nearest ten?", "343 m/s", ["243 m/s", "443 m/s", "1,235 m/s"], "Sound covers about 343 metres per second in room-temperature air."),

  // space
  M('space', 1, "Which planet is closest to the Sun?", "Mercury", ["Venus", "Mars", "Earth"], "Mercury orbits the Sun once every 88 days."),
  M('space', 2, "Which is the hottest planet in our Solar System?", "Venus", ["Mercury", "Mars", "Jupiter"], "Venus's thick carbon dioxide atmosphere traps heat, making it hotter than Mercury."),
  M('space', 2, "Which planet spins on its side?", "Uranus", ["Neptune", "Saturn", "Venus"], "Uranus is tilted about 98 degrees, so it rolls around the Sun."),
  M('space', 1, "Which planet is farthest from the Sun?", "Neptune", ["Uranus", "Saturn", "Jupiter"], "Neptune is about 4.5 billion km from the Sun."),
  M('space', 3, "In which year was Pluto reclassified as a dwarf planet?", "2006", ["1999", "2010", "2001"], "The International Astronomical Union changed its status in August 2006."),
  N('space', 1, "In which year did humans first land on the Moon?", 1969, "", 2, "Apollo 11 landed on 20 July 1969."),
  M('space', 1, "Who was the first human to travel into space?", "Yuri Gagarin", ["Neil Armstrong", "Alan Shepard", "John Glenn"], "Gagarin orbited Earth in Vostok 1 on 12 April 1961."),
  N('space', 3, "In which year did Yuri Gagarin become the first person in space?", 1961, "", 1, "Vostok 1 launched on 12 April 1961."),
  M('space', 2, "What was the first artificial satellite?", "Sputnik 1", ["Explorer 1", "Vostok 1", "Telstar"], "The Soviet Union launched Sputnik 1 in October 1957."),
  N('space', 3, "In which year was Sputnik 1 launched?", 1957, "", 2, "Sputnik 1 launched on 4 October 1957, starting the Space Age."),
  M('space', 3, "Who was the first woman in space?", "Valentina Tereshkova", ["Sally Ride", "Mae Jemison", "Svetlana Savitskaya"], "Tereshkova flew on Vostok 6 in June 1963."),
  M('space', 1, "What is the name of the galaxy we live in?", "Milky Way", ["Andromeda", "Triangulum", "Whirlpool"], "Our Solar System sits in one of the Milky Way's spiral arms."),
  M('space', 3, "What is the nearest large spiral galaxy to the Milky Way?", "Andromeda", ["Triangulum", "Whirlpool", "Sombrero"], "Andromeda is about 2.5 million light-years away."),
  M('space', 1, "What is the nearest star to Earth?", "The Sun", ["Proxima Centauri", "Sirius", "Polaris"], "The Sun is a star, about 150 million km away."),
  M('space', 3, "After the Sun, what is the nearest known star to Earth?", "Proxima Centauri", ["Sirius", "Vega", "Betelgeuse"], "Proxima Centauri is about 4.2 light-years away."),
  M('space', 2, "What is the brightest star in the night sky?", "Sirius", ["Polaris", "Vega", "Betelgeuse"], "Sirius, the 'Dog Star', is the brightest star after the Sun."),
  M('space', 2, "Which star is known as the North Star?", "Polaris", ["Sirius", "Vega", "Rigel"], "Polaris sits almost directly above Earth's North Pole."),
  N('space', 3, "On average, about how many kilometres away is the Moon?", 384400, "km", 20000, "The Moon averages about 384,400 km from Earth."),
  N('space', 1, "About how many days does Earth take to orbit the Sun?", 365, "days", 1, "One orbit takes about 365.25 days, which is why we have leap years."),
  M('space', 1, "Which planet has a giant storm called the Great Red Spot?", "Jupiter", ["Saturn", "Neptune", "Mars"], "The Great Red Spot is a storm wider than Earth."),
  M('space', 3, "What is the largest moon in the Solar System?", "Ganymede", ["Titan", "Callisto", "The Moon"], "Jupiter's moon Ganymede is even bigger than the planet Mercury."),
  M('space', 3, "What is the largest moon of Saturn?", "Titan", ["Ganymede", "Europa", "Io"], "Titan is the only moon known to have a thick atmosphere."),
  M('space', 2, "Olympus Mons, the tallest volcano in the Solar System, is on which world?", "Mars", ["Venus", "The Moon", "Mercury"], "Olympus Mons rises about 22 km above the Martian plains."),
  N('space', 3, "How many moons does Mars have?", 2, "", 0, "Mars has two small moons, Phobos and Deimos."),
  M('space', 2, "Which gas makes up most of the Sun?", "Hydrogen", ["Helium", "Oxygen", "Carbon"], "The Sun is about three quarters hydrogen, which it fuses into helium."),
  N('space', 3, "About how many years does Halley's Comet take to return?", 76, "years", 3, "Halley's Comet comes back every 75–76 years; it is next due in 2061."),
  M('space', 2, "What does a light-year measure?", "Distance", ["Time", "Brightness", "Speed"], "A light-year is the distance light travels in a year, about 9.5 trillion km."),
  M('space', 3, "What was the name of the Apollo 11 lunar module?", "Eagle", ["Columbia", "Falcon", "Discovery"], "'The Eagle has landed'; Columbia was the command module that stayed in orbit."),
  M('space', 1, "Which space telescope was launched in 1990?", "Hubble", ["James Webb", "Kepler", "Spitzer"], "The Hubble Space Telescope was carried up by the space shuttle Discovery."),
  T('space', 2, "The James Webb Space Telescope was launched in 2021.", true, "It launched on 25 December 2021."),
  T('space', 2, "The main asteroid belt lies between Mars and Jupiter.", true, "Most known asteroids orbit between Mars and Jupiter."),
  T('space', 3, "Venus spins in the opposite direction to most planets.", true, "Venus rotates 'backwards', so on Venus the Sun rises in the west."),
  T('space', 3, "A day on Venus is longer than its year.", true, "Venus takes about 243 Earth days to spin once but only about 225 to orbit the Sun."),
  T('space', 1, "Jupiter is a gas giant.", true, "Jupiter is mostly hydrogen and helium with no solid surface to stand on."),
  T('space', 2, "Mercury has no moons.", true, "Mercury and Venus are the only planets with no moons."),
  O('space', 2, "Put these outer planets in order from the Sun, nearest first.", ["Jupiter", "Saturn", "Uranus", "Neptune"], "Nearest to the Sun first", "Jupiter, Saturn, Uranus, then Neptune."),
  O('space', 2, "Put these planets in order of size, largest first.", ["Jupiter", "Saturn", "Earth", "Mars"], "Largest first", "Jupiter is the largest planet; Mars is about half Earth's width."),
  M('space', 1, "What is a 'shooting star' really?", "A meteor", ["A dying star", "A comet", "A satellite"], "A shooting star is a bit of space rock burning up in our atmosphere."),
  M('space', 3, "Who was the first American in space?", "Alan Shepard", ["John Glenn", "Neil Armstrong", "Gus Grissom"], "Shepard flew in May 1961; John Glenn was the first American to orbit Earth, in 1962."),
  M('space', 2, "Which constellation has a 'belt' of three bright stars in a row?", "Orion", ["Ursa Major", "Cassiopeia", "Leo"], "Orion's Belt is made of the stars Alnitak, Alnilam and Mintaka."),
  M('space', 3, "The Big Dipper (also called the Plough) is part of which constellation?", "Ursa Major", ["Ursa Minor", "Orion", "Draco"], "Ursa Major means 'Great Bear'."),
  M('space', 3, "Which was the first spacecraft to leave the Solar System's bubble of solar wind (the heliosphere)?", "Voyager 1", ["Pioneer 10", "New Horizons", "Voyager 2"], "Voyager 1 crossed into interstellar space in 2012."),
  M('space', 3, "Which planet has the most extreme winds measured in the Solar System, over 2,000 km/h?", "Neptune", ["Jupiter", "Earth", "Mercury"], "Neptune's winds are the fastest recorded on any planet."),
  T('space', 2, "Earth's seasons are caused by its changing distance from the Sun.", false, "Seasons come from Earth's 23.4° tilt; Earth is actually closest to the Sun in early January."),
  T('space', 1, "Ocean tides are caused mainly by the pull of the Moon.", true, "The Moon's gravity raises tides; the Sun adds a smaller effect."),
  N('space', 2, "About how many minutes does sunlight take to reach Earth?", 8, "minutes", 1, "Sunlight takes about 8 minutes 20 seconds to cross the 150 million km."),

  // body
  N('body', 2, "How many bones are there in a typical adult human body?", 206, "bones", 0, "Babies are born with more, but many fuse together as we grow."),
  M('body', 1, "What is the largest organ of the human body?", "Skin", ["Liver", "Brain", "Lungs"], "Skin covers about 2 square metres on an adult."),
  N('body', 1, "How many chambers does the human heart have?", 4, "", 0, "Two atria on top and two ventricles below."),
  N('body', 2, "How many teeth are in a full adult set, including wisdom teeth?", 32, "teeth", 0, "Adults have 32 teeth, including four wisdom teeth."),
  N('body', 2, "How many baby (milk) teeth does a child usually have?", 20, "teeth", 0, "Children have 20 milk teeth, which are replaced by adult teeth."),
  M('body', 3, "What is the smallest bone in the human body?", "Stapes", ["Incus", "Malleus", "Hyoid"], "The stapes, in the middle ear, is only about 3 mm long."),
  M('body', 1, "What is the longest bone in the human body?", "Femur", ["Tibia", "Humerus", "Fibula"], "The femur, or thigh bone, is about a quarter of a person's height."),
  M('body', 2, "Which blood type is known as the universal donor for red blood cells?", "O negative", ["AB positive", "A negative", "B positive"], "O negative red cells can be given to almost anyone in an emergency."),
  M('body', 3, "Which blood type is known as the universal recipient?", "AB positive", ["O negative", "A positive", "B negative"], "People with AB positive blood can receive red cells of any type."),
  M('body', 2, "Which protein in red blood cells carries oxygen?", "Haemoglobin", ["Insulin", "Keratin", "Melanin"], "Haemoglobin contains iron, which gives blood its red colour."),
  M('body', 2, "Which hormone controls the level of sugar in the blood?", "Insulin", ["Adrenaline", "Melatonin", "Oestrogen"], "Insulin helps cells take up sugar from the blood."),
  M('body', 2, "Which organ makes insulin?", "Pancreas", ["Liver", "Kidneys", "Spleen"], "Islet cells in the pancreas release insulin."),
  M('body', 2, "What is the medical name for the kneecap?", "Patella", ["Scapula", "Clavicle", "Sternum"], "The patella protects the front of the knee joint."),
  M('body', 3, "Which bone is commonly called the collarbone?", "Clavicle", ["Scapula", "Patella", "Sternum"], "The clavicle connects the arm to the body at the shoulder."),
  M('body', 1, "In which organ would you find the cornea?", "Eye", ["Ear", "Heart", "Kidney"], "The cornea is the clear front window of the eye."),
  M('body', 1, "Which vitamin does your skin make when exposed to sunlight?", "Vitamin D", ["Vitamin A", "Vitamin C", "Vitamin K"], "Vitamin D helps the body absorb calcium for strong bones."),
  M('body', 2, "A lack of vitamin C causes which disease?", "Scurvy", ["Rickets", "Beriberi", "Anaemia"], "Sailors once got scurvy on long voyages without fresh fruit."),
  N('body', 1, "What is normal human body temperature in degrees Celsius, roughly?", 37, "°C", 0.5, "Normal body temperature is around 37 °C."),
  T('body', 3, "The left lung is slightly smaller than the right lung.", true, "The left lung is smaller to make room for the heart."),
  M('body', 2, "Which blood vessels carry blood away from the heart?", "Arteries", ["Veins", "Capillaries", "Lymph vessels"], "Arteries carry blood away from the heart; veins bring it back."),
  M('body', 2, "What are nerve cells called?", "Neurons", ["Platelets", "Osteocytes", "Alveoli"], "Your brain has about 86 billion neurons."),
  T('body', 3, "Each part of the tongue can taste only one of the basic tastes.", false, "The 'tongue map' is a myth: all areas can sense all basic tastes."),
  T('body', 1, "Humans use only 10% of their brains.", false, "Brain scans show we use virtually all of our brain."),
  M('body', 3, "What protein are fingernails mostly made of?", "Keratin", ["Calcium", "Collagen", "Chitin"], "Keratin is the same tough protein found in hair."),
  M('body', 3, "Where are most red blood cells made in adults?", "Bone marrow", ["Liver", "Heart", "Spleen"], "Bone marrow makes millions of new blood cells every second."),
  T('body', 1, "The 'funny bone' is actually a nerve, not a bone.", true, "It is the ulnar nerve, which runs close to the skin at the elbow."),
  M('body', 3, "Which acid does the stomach produce to help digest food?", "Hydrochloric acid", ["Sulfuric acid", "Citric acid", "Nitric acid"], "Stomach acid is strong enough to kill most germs in food."),
  T('body', 2, "The large intestine is longer than the small intestine.", false, "The small intestine is about 6 m long; the large is about 1.5 m."),
  M('body', 1, "Which organs filter the blood to make urine?", "Kidneys", ["Liver", "Bladder", "Spleen"], "Most people have two kidneys, each about the size of a fist."),
  M('body', 2, "Which muscle does most of the work when you breathe?", "Diaphragm", ["Pectorals", "Abdominals", "Trapezius"], "The diaphragm is a dome of muscle under the lungs."),
  N('body', 3, "How many chromosomes are in a typical human body cell?", 46, "", 0, "Humans have 23 pairs of chromosomes."),
  M('body', 2, "What does DNA stand for?", "Deoxyribonucleic acid", ["Dinucleic acid", "Deoxyribonitric acid", "Diribonucleic acid"], "DNA carries the genetic instructions for living things."),
  T('body', 2, "Newborn babies have fewer bones than adults.", false, "Babies have about 300 bones; many fuse together as they grow."),
  M('body', 1, "What is the coloured part of the eye called?", "Iris", ["Pupil", "Retina", "Cornea"], "The iris controls how much light passes through the pupil."),
  M('body', 1, "Where in the body is the Achilles tendon?", "Back of the ankle", ["Back of the knee", "Inside the elbow", "Front of the wrist"], "It connects the calf muscles to the heel bone."),
  M('body', 3, "What colour is blood plasma?", "Pale yellow", ["Clear blue", "Light red", "White"], "Plasma, the liquid part of blood, is a straw-yellow colour."),
  N('body', 2, "About how many litres of blood does an average adult have?", 5, "litres", 1, "An adult has roughly 5 litres of blood."),
  M('body', 3, "What is the largest artery in the human body?", "Aorta", ["Carotid artery", "Femoral artery", "Pulmonary artery"], "The aorta leaves the heart and is about as wide as a garden hose."),
  M('body', 2, "Which bone runs from the shoulder to the elbow?", "Humerus", ["Radius", "Ulna", "Femur"], "The humerus is the upper arm bone."),
  M('body', 2, "What are the bones of the spine called?", "Vertebrae", ["Phalanges", "Carpals", "Tarsals"], "The spine has 33 vertebrae, some fused together."),
  N('body', 2, "How many pairs of ribs does a typical human have?", 12, "pairs", 0, "Most people have 12 pairs of ribs."),
  M('body', 3, "What are the bones of the fingers and toes called?", "Phalanges", ["Metacarpals", "Vertebrae", "Tarsals"], "Each finger has three phalanges; the thumb has two."),
  O('body', 3, "Put these bones in order of length, longest first.", ["Femur", "Tibia", "Humerus", "Stapes"], "Longest first", "Thigh bone, shin bone, upper arm bone, then the tiny stapes in the ear."),
  M('body', 3, "Which part of the eye turns light into nerve signals?", "Retina", ["Iris", "Lens", "Cornea"], "The retina at the back of the eye is lined with light-sensitive cells."),
  M('body', 3, "What is the medical name for the eardrum?", "Tympanic membrane", ["Cochlea", "Eustachian tube", "Pinna"], "The tympanic membrane vibrates when sound waves hit it."),

  // maths
  N('math', 1, "What is the square root of 144?", 12, "", 0, "12 × 12 = 144."),
  N('math', 1, "What is 7 × 8?", 56, "", 0, "7 × 8 = 56."),
  N('math', 1, "How many degrees do the angles inside a triangle add up to?", 180, "°", 0, "The interior angles of any triangle add up to 180°."),
  N('math', 1, "How many degrees are there in a full circle?", 360, "°", 0, "A full turn is 360°."),
  N('math', 1, "How many sides does an octagon have?", 8, "sides", 0, "Octo means eight, like an octopus's eight arms."),
  N('math', 1, "What is pi to two decimal places?", 3.14, "", 0, "Pi is about 3.14159; it never ends or repeats."),
  N('math', 2, "What is the smallest prime number?", 2, "", 0, "2 is the only even prime number."),
  T('math', 2, "The number 1 is a prime number.", false, "A prime has exactly two factors; 1 has only one, so it is not prime."),
  M('math', 1, "Which of these is a prime number?", "17", ["15", "21", "27"], "17 can only be divided by 1 and itself."),
  N('math', 2, "What comes next in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, …?", 13, "", 0, "Each number is the sum of the two before it: 5 + 8 = 13."),
  N('math', 1, "What is 15% of 200?", 30, "", 0, "10% of 200 is 20 and 5% is 10, so 15% is 30."),
  N('math', 3, "What is 2 to the power of 10?", 1024, "", 0, "2¹⁰ = 1,024."),
  N('math', 1, "How many zeros are there in one million?", 6, "", 0, "One million is 1,000,000."),
  N('math', 2, "How many zeros are there in one billion (short scale)?", 9, "", 0, "A billion, as used today, is 1,000,000,000."),
  N('math', 3, "How many zeros follow the 1 in a googol?", 100, "", 0, "A googol is 10 to the power of 100."),
  M('math', 1, "What is an angle of less than 90 degrees called?", "Acute", ["Obtuse", "Reflex", "Right"], "Acute angles are less than 90°; obtuse are between 90° and 180°."),
  M('math', 1, "What is a five-sided shape called?", "Pentagon", ["Hexagon", "Heptagon", "Octagon"], "Penta means five."),
  M('math', 1, "What is a triangle with all three sides equal called?", "Equilateral", ["Isosceles", "Scalene", "Right-angled"], "An equilateral triangle also has three equal 60° angles."),
  N('math', 2, "A right-angled triangle has shorter sides of 3 and 4. How long is the longest side?", 5, "", 0, "By Pythagoras: 3² + 4² = 9 + 16 = 25, and √25 = 5."),
  M('math', 2, "What is the formula for the area of a circle?", "πr²", ["2πr", "πd", "4πr²"], "2πr is the circumference; 4πr² is a sphere's surface area."),
  N('math', 2, "How many degrees do the angles inside a four-sided shape add up to?", 360, "°", 0, "Any quadrilateral splits into two triangles: 2 × 180° = 360°."),
  N('math', 1, "How many faces does a cube have?", 6, "faces", 0, "A cube has 6 square faces."),
  N('math', 2, "How many edges does a cube have?", 12, "edges", 0, "A cube has 12 edges and 8 corners."),
  N('math', 2, "How many vertices (corners) does a cube have?", 8, "", 0, "A cube has 8 vertices."),
  N('math', 3, "How many sides does a dodecagon have?", 12, "sides", 0, "Dodeca means twelve."),
  N('math', 3, "How many faces does an icosahedron have?", 20, "faces", 0, "The 20-sided die used in tabletop games is an icosahedron."),
  N('math', 1, "How many seconds are in one hour?", 3600, "seconds", 0, "60 seconds × 60 minutes = 3,600."),
  N('math', 2, "How many minutes are in one day?", 1440, "minutes", 0, "24 hours × 60 minutes = 1,440."),
  N('math', 1, "How many days are in a leap year?", 366, "days", 0, "A leap year adds 29 February."),
  M('math', 1, "What is half of a quarter?", "One eighth", ["One sixth", "One third", "One half"], "½ × ¼ = ⅛."),
  M('math', 1, "What is 0.75 as a fraction?", "3/4", ["7/5", "1/4", "3/5"], "0.75 is 75 hundredths, which simplifies to 3/4."),
  T('math', 1, "A negative number multiplied by a negative number gives a positive number.", true, "For example, −3 × −4 = 12."),
  T('math', 2, "Any non-zero number raised to the power of 0 equals 0.", false, "It equals 1: for example, 5⁰ = 1 and 1,000⁰ = 1."),
  M('math', 1, "Which ancient Greek is famous for a theorem about right-angled triangles?", "Pythagoras", ["Archimedes", "Euclid", "Plato"], "a² + b² = c² is called Pythagoras's theorem."),
  M('math', 3, "Which Greek mathematician wrote 'Elements' and is called the father of geometry?", "Euclid", ["Pythagoras", "Archimedes", "Aristotle"], "Euclid's Elements was used as a textbook for over 2,000 years."),
  M('math', 3, "Who finally proved Fermat's Last Theorem in the 1990s?", "Andrew Wiles", ["Alan Turing", "John Nash", "Srinivasa Ramanujan"], "Wiles's proof was completed in 1994–95, over 350 years after Fermat."),
  M('math', 3, "What base does the hexadecimal number system use?", "16", ["6", "8", "12"], "Hexadecimal uses 0–9 and A–F."),
  N('math', 1, "What is the mean (average) of 2, 4, 6 and 8?", 5, "", 0, "(2 + 4 + 6 + 8) ÷ 4 = 20 ÷ 4 = 5."),
  N('math', 2, "What is the median of 3, 7, 9, 12 and 20?", 9, "", 0, "The median is the middle value of the sorted list."),
  O('math', 3, "Put these numbers in order, smallest first.", ["1/4", "0.3", "1/3", "0.35"], "Smallest first", "0.25, 0.3, 0.333… and 0.35."),
  O('math', 2, "Put these in order of value, smallest first.", ["2³", "3²", "√121", "4!"], "Smallest first", "2³ = 8, 3² = 9, √121 = 11, 4! = 24."),
  N('math', 2, "What is 5 factorial (5!)?", 120, "", 0, "5! = 5 × 4 × 3 × 2 × 1 = 120."),
  M('math', 3, "Which of these is a perfect number (equal to the sum of its other divisors)?", "28", ["12", "18", "30"], "1 + 2 + 4 + 7 + 14 = 28."),
  M('math', 1, "Which of these is a square number?", "81", ["72", "90", "99"], "81 = 9 × 9."),
  N('math', 2, "About how many kilometres are in one mile?", 1.6, "km", 0.05, "One mile is about 1.609 km."),
  N('math', 1, "How many inches are in a foot?", 12, "inches", 0, "There are 12 inches in a foot and 3 feet in a yard."),
  N('math', 2, "How many ounces are in a pound?", 16, "ounces", 0, "One pound (avoirdupois) is 16 ounces."),
  N('math', 1, "How many grams are in a kilogram?", 1000, "grams", 0, "Kilo means a thousand."),
  N('math', 1, "What number is X in Roman numerals?", 10, "", 0, "I = 1, V = 5, X = 10."),
  N('math', 2, "What number is XL in Roman numerals?", 40, "", 0, "XL is 10 before 50: 50 − 10 = 40."),
  N('math', 2, "What year is MMXXIV in Roman numerals?", 2024, "", 0, "MM = 2000, XX = 20, IV = 4."),
  N('math', 2, "What number is D in Roman numerals?", 500, "", 0, "D = 500 and M = 1,000."),
  M('math', 2, "What is the name for the longest side of a right-angled triangle?", "Hypotenuse", ["Radius", "Tangent", "Diagonal"], "The hypotenuse is always opposite the right angle."),
  N('math', 3, "What is 13 squared?", 169, "", 0, "13 × 13 = 169."),
  T('math', 2, "The sum of two odd numbers is always odd.", false, "It is always even: for example, 3 + 5 = 8 and 7 + 9 = 16."),

  // technology
  M('tech', 1, "Who was granted the first US patent for the telephone in 1876?", "Alexander Graham Bell", ["Thomas Edison", "Guglielmo Marconi", "Samuel Morse"], "Bell's patent was granted in March 1876."),
  M('tech', 1, "Who invented the World Wide Web?", "Tim Berners-Lee", ["Bill Gates", "Steve Jobs", "Vint Cerf"], "Berners-Lee proposed the web at CERN in 1989."),
  N('tech', 3, "In which year did Tim Berners-Lee first propose the World Wide Web?", 1989, "", 2, "His proposal at CERN was written in March 1989."),
  N('tech', 2, "In which year did the Wright brothers make the first powered aeroplane flight?", 1903, "", 2, "Their Wright Flyer flew on 17 December 1903."),
  M('tech', 3, "Near which town did the Wright brothers make their first powered flight?", "Kitty Hawk", ["Dayton", "Detroit", "Cape Canaveral"], "The flight was at Kill Devil Hills, near Kitty Hawk, North Carolina."),
  M('tech', 1, "Who introduced movable-type printing to Europe around 1440?", "Johannes Gutenberg", ["William Caxton", "Leonardo da Vinci", "Martin Luther"], "Gutenberg's press made books far cheaper and faster to produce."),
  M('tech', 2, "Whose improvements to the steam engine in the 1760s–70s helped drive the Industrial Revolution?", "James Watt", ["George Stephenson", "Isambard Kingdom Brunel", "Michael Faraday"], "The watt, a unit of power, is named after him."),
  M('tech', 2, "Who invented dynamite?", "Alfred Nobel", ["Thomas Edison", "Nikola Tesla", "Robert Oppenheimer"], "Nobel used his fortune to found the Nobel Prizes."),
  M('tech', 3, "Which Italian pioneer of long-distance radio shared the 1909 Nobel Prize in Physics?", "Guglielmo Marconi", ["Alessandro Volta", "Enrico Fermi", "Galileo Galilei"], "Marconi sent radio signals across the Atlantic in 1901."),
  M('tech', 3, "Which Scottish inventor gave the first public demonstration of a working television in 1926?", "John Logie Baird", ["Alexander Graham Bell", "James Clerk Maxwell", "Robert Watson-Watt"], "Baird demonstrated moving television images in London in January 1926."),
  M('tech', 1, "In computing, what does CPU stand for?", "Central Processing Unit", ["Computer Power Unit", "Central Program Utility", "Core Processing Usage"], "The CPU carries out a program's instructions."),
  M('tech', 2, "In computing, what does RAM stand for?", "Random Access Memory", ["Read And Modify", "Rapid Action Memory", "Run Access Mode"], "RAM is fast, temporary working memory."),
  M('tech', 3, "What does URL stand for?", "Uniform Resource Locator", ["Universal Reference Link", "Unified Route Label", "User Resource Location"], "A URL is the address of something on the web."),
  M('tech', 2, "What does HTML stand for?", "HyperText Markup Language", ["High Tech Modern Language", "Hyperlink Text Mode Language", "Home Tool Markup Language"], "HTML describes the structure of web pages."),
  M('tech', 2, "What does USB stand for?", "Universal Serial Bus", ["United System Board", "Universal Signal Bridge", "Unified Storage Base"], "USB was introduced in the mid-1990s."),
  M('tech', 1, "What does GPS stand for?", "Global Positioning System", ["General Path Service", "Geographic Pointing Satellite", "Global Pathway Scanner"], "GPS works out your position using signals from satellites."),
  N('tech', 1, "How many bits are in a byte?", 8, "bits", 0, "A byte is 8 bits, enough for 256 different values."),
  M('tech', 1, "Which number system do computers use to store data at the lowest level?", "Binary", ["Decimal", "Roman", "Hexadecimal"], "Binary uses only 0 and 1."),
  N('tech', 2, "In which year was the first iPhone released?", 2007, "", 1, "The first iPhone went on sale in June 2007."),
  M('tech', 2, "Who co-founded Apple with Steve Jobs in 1976?", "Steve Wozniak", ["Bill Gates", "Paul Allen", "Larry Page"], "Wozniak designed the Apple I and Apple II computers."),
  M('tech', 3, "Who co-founded Microsoft with Bill Gates?", "Paul Allen", ["Steve Wozniak", "Larry Ellison", "Sergey Brin"], "Gates and Allen founded Microsoft in 1975."),
  M('tech', 2, "Who founded Google?", "Larry Page and Sergey Brin", ["Bill Gates and Paul Allen", "Steve Jobs and Steve Wozniak", "Jerry Yang and David Filo"], "They started Google as Stanford students in 1998."),
  M('tech', 2, "Who is often called the first computer programmer?", "Ada Lovelace", ["Grace Hopper", "Alan Turing", "Charles Babbage"], "In 1843 she published an algorithm for Babbage's Analytical Engine."),
  M('tech', 3, "Who designed the Analytical Engine, an early mechanical computer?", "Charles Babbage", ["Alan Turing", "Blaise Pascal", "John von Neumann"], "Babbage designed it in the 1830s, but it was never completed."),
  M('tech', 2, "Which mathematician helped break the Enigma code at Bletchley Park?", "Alan Turing", ["Charles Babbage", "John Nash", "Isaac Newton"], "Turing designed the 'Bombe' machine used to crack Enigma messages."),
  M('tech', 2, "Which programming language is named after a British comedy group?", "Python", ["Ruby", "Java", "Perl"], "Guido van Rossum named it after Monty Python's Flying Circus."),
  T('tech', 3, "Bluetooth is named after a Viking-age king.", true, "It is named after Harald 'Bluetooth', a 10th-century king of Denmark."),
  M('tech', 1, "Which keyboard layout is standard in English-speaking countries?", "QWERTY", ["AZERTY", "QWERTZ", "Dvorak"], "QWERTY is named after the first six letters on the top row."),
  M('tech', 2, "Who co-developed the Morse code used for telegraphs?", "Samuel Morse", ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla"], "Morse and Alfred Vail developed the code in the 1830s–40s."),
  M('tech', 2, "What is SOS in Morse code?", "··· ––– ···", ["––– ··· –––", "·–·–·–", "–·–· –·–·"], "Three dots, three dashes, three dots."),
  T('tech', 2, "Velcro was inspired by burrs sticking to a dog's fur.", true, "Swiss engineer George de Mestral had the idea after a walk in the 1940s."),
  M('tech', 3, "What was the name of the early network that became the forerunner of the internet?", "ARPANET", ["ETHERNET", "USENET", "SKYNET"], "ARPANET sent its first message in 1969."),
  T('tech', 3, "Concorde, the supersonic airliner, made its last passenger flights in 2003.", true, "British Airways and Air France retired Concorde in 2003."),
  M('tech', 2, "Who invented the lightning rod?", "Benjamin Franklin", ["Thomas Edison", "Nikola Tesla", "Michael Faraday"], "Franklin's lightning rods protected buildings from strikes."),
  T('tech', 2, "Thomas Edison invented the phonograph.", true, "Edison invented the phonograph, which recorded and played sound, in 1877."),
  M('tech', 3, "Who invented the stethoscope in 1816?", "René Laennec", ["Louis Pasteur", "Joseph Lister", "Florence Nightingale"], "Laennec's first stethoscope was a simple wooden tube."),
  M('tech', 2, "What does LED stand for?", "Light-Emitting Diode", ["Low-Energy Display", "Laser Electric Device", "Light Energy Disc"], "LEDs make light when electricity passes through a semiconductor."),
  T('tech', 2, "The word 'pixel' is short for 'picture element'.", true, "A pixel is one tiny dot of a digital image."),
  O('tech', 2, "Put these inventions in order, earliest first.", ["Gutenberg printing press", "Steam locomotive", "Telephone", "Powered aeroplane"], "Earliest first", "About 1440, 1804, 1876 and 1903."),
  O('tech', 2, "Put these in order of invention, earliest first.", ["Telephone", "Radio", "Television", "World Wide Web"], "Earliest first", "1876, 1890s, 1920s and 1989."),
  M('tech', 3, "Who sent the first network email between computers, choosing the @ sign for addresses?", "Ray Tomlinson", ["Tim Berners-Lee", "Vint Cerf", "Steve Jobs"], "Tomlinson sent it on ARPANET in 1971."),
  M('tech', 1, "Which company makes the Windows operating system?", "Microsoft", ["Apple", "Google", "IBM"], "Windows 1.0 was released in 1985."),
  T('tech', 2, "Mach 1 means travelling at the speed of light.", false, "Mach 1 is the speed of sound; Mach 2 is twice the speed of sound."),
  M('tech', 3, "In which country was the first atomic clock based on caesium built, in 1955?", "United Kingdom", ["United States", "Switzerland", "Germany"], "Louis Essen and Jack Parry built it at the National Physical Laboratory."),
];
