import { M, T, N, O } from './lib.mjs';

export default [
  // geography
  M('geo', 2, "Which is the smallest of the world's five oceans?", "Arctic Ocean", ["Southern Ocean", "Indian Ocean", "Atlantic Ocean"], "The Arctic Ocean is the smallest and shallowest ocean."),
  M('geo', 1, "Which is the largest continent by area?", "Asia", ["Africa", "North America", "Europe"], "Asia covers about 30% of Earth's land."),
  M('geo', 1, "Which is the largest country in the world by area?", "Russia", ["Canada", "China", "United States"], "Russia spans 11 time zones."),
  M('geo', 2, "Which is the second-largest country in the world by area?", "Canada", ["China", "Brazil", "Australia"], "Canada is just under 10 million square kilometres."),
  M('geo', 1, "Which is the smallest country in the world?", "Vatican City", ["Monaco", "San Marino", "Liechtenstein"], "Vatican City covers less than half a square kilometre."),
  M('geo', 2, "As of 2024, which country had the largest population?", "India", ["China", "United States", "Indonesia"], "India passed China as the most populous country in 2023."),
  N('geo', 3, "How tall is Mount Everest in metres, according to the 2020 survey?", 8849, "m", 50, "China and Nepal jointly measured it at 8,848.86 m in 2020."),
  M('geo', 2, "What is the second-highest mountain on Earth?", "K2", ["Kangchenjunga", "Lhotse", "Makalu"], "K2, on the Pakistan–China border, is 8,611 m tall."),
  M('geo', 3, "What is the longest river in Europe?", "Volga", ["Danube", "Rhine", "Dnieper"], "The Volga flows about 3,500 km through Russia to the Caspian Sea."),
  M('geo', 1, "Which river flows through London?", "Thames", ["Severn", "Trent", "Mersey"], "The Thames runs through the heart of London to the North Sea."),
  M('geo', 1, "Which river flows through Paris?", "Seine", ["Loire", "Rhône", "Rhine"], "The Seine flows through Paris on its way to the English Channel."),
  M('geo', 3, "Which river flows through Baghdad?", "Tigris", ["Euphrates", "Jordan", "Indus"], "Baghdad straddles the Tigris."),
  M('geo', 1, "What is the largest hot desert in the world?", "Sahara", ["Gobi", "Kalahari", "Arabian Desert"], "The Sahara covers much of North Africa."),
  T('geo', 2, "By the scientific definition, the largest desert in the world is Antarctica.", true, "A desert is defined by low precipitation, and Antarctica gets very little."),
  M('geo', 1, "What is the deepest known part of the oceans?", "Mariana Trench", ["Puerto Rico Trench", "Java Trench", "Tonga Trench"], "Its deepest point, Challenger Deep, is nearly 11 km down."),
  M('geo', 2, "What is the largest lake in the world by area?", "Caspian Sea", ["Lake Superior", "Lake Victoria", "Lake Baikal"], "Despite its name, the salty Caspian Sea is classed as a lake."),
  M('geo', 3, "What is the deepest lake in the world?", "Lake Baikal", ["Lake Tanganyika", "Caspian Sea", "Lake Superior"], "Lake Baikal in Siberia is over 1,600 m deep."),
  M('geo', 3, "What is the largest freshwater lake in the world by surface area?", "Lake Superior", ["Lake Victoria", "Lake Huron", "Lake Michigan"], "Lake Superior covers about 82,000 square kilometres."),
  M('geo', 1, "In which country is the Great Barrier Reef?", "Australia", ["Indonesia", "Philippines", "New Zealand"], "It runs for over 2,000 km off Queensland."),
  M('geo', 1, "In which country is Machu Picchu?", "Peru", ["Bolivia", "Mexico", "Chile"], "The Inca site sits high in the Andes."),
  M('geo', 2, "In which country is the temple complex of Angkor Wat?", "Cambodia", ["Thailand", "Vietnam", "Laos"], "Angkor Wat even appears on Cambodia's flag."),
  M('geo', 2, "In which country is the ancient city of Petra?", "Jordan", ["Egypt", "Israel", "Lebanon"], "Petra was carved into rose-red sandstone cliffs."),
  M('geo', 2, "What is the largest island in the world (not counting continents)?", "Greenland", ["New Guinea", "Borneo", "Madagascar"], "Greenland is about 2.2 million square kilometres."),
  M('geo', 1, "Which strait separates Europe from Africa?", "Strait of Gibraltar", ["Bosphorus", "Dardanelles", "Strait of Hormuz"], "At its narrowest it is only about 14 km wide."),
  M('geo', 1, "Which two oceans does the Panama Canal link?", "Atlantic and Pacific", ["Atlantic and Indian", "Pacific and Indian", "Arctic and Atlantic"], "The canal opened in 1914."),
  M('geo', 2, "Which two seas does the Suez Canal connect?", "Mediterranean and Red Sea", ["Black Sea and Mediterranean", "Red Sea and Arabian Sea", "Caspian and Black Sea"], "The Suez Canal opened in 1869."),
  M('geo', 3, "In which country is Mount Kilimanjaro?", "Tanzania", ["Kenya", "Uganda", "Ethiopia"], "Kilimanjaro is Africa's highest mountain at 5,895 m."),
  T('geo', 2, "The Equator passes through Brazil.", true, "The Equator crosses northern Brazil, near the mouth of the Amazon."),
  N('geo', 1, "How many states are there in the United States?", 50, "states", 0, "Hawaii became the 50th state in 1959."),
  M('geo', 2, "Which is the most populous country in Africa?", "Nigeria", ["Ethiopia", "Egypt", "DR Congo"], "Nigeria has over 200 million people."),
  M('geo', 2, "Which of these countries is landlocked?", "Switzerland", ["Portugal", "Croatia", "Belgium"], "Switzerland has no coastline."),
  M('geo', 2, "Which of these South American countries is landlocked?", "Bolivia", ["Peru", "Chile", "Colombia"], "Bolivia lost its coastline to Chile in the 1880s."),
  M('geo', 3, "Which of these is one of only two doubly landlocked countries in the world?", "Uzbekistan", ["Kazakhstan", "Mongolia", "Afghanistan"], "Uzbekistan and Liechtenstein are surrounded only by landlocked countries."),
  M('geo', 3, "Which mountain range is traditionally seen as the border between Europe and Asia?", "Ural Mountains", ["Alps", "Carpathians", "Pyrenees"], "The Urals run north to south through Russia."),
  M('geo', 2, "Which mountains form the border between France and Spain?", "Pyrenees", ["Alps", "Apennines", "Vosges"], "Tiny Andorra sits high in the Pyrenees."),
  T('geo', 2, "The Andes is the longest continental mountain range in the world.", true, "The Andes run about 7,000 km down South America."),
  M('geo', 1, "Which volcano buried the Roman town of Pompeii?", "Vesuvius", ["Etna", "Stromboli", "Krakatoa"], "Vesuvius erupted in AD 79."),
  M('geo', 1, "In which country is Mount Fuji?", "Japan", ["China", "South Korea", "Indonesia"], "Mount Fuji is Japan's highest peak at 3,776 m."),
  M('geo', 1, "Niagara Falls lies on the border of which two countries?", "United States and Canada", ["United States and Mexico", "Canada and Greenland", "Brazil and Argentina"], "The falls sit between Ontario and New York State."),
  M('geo', 3, "Victoria Falls lies on the border of which two countries?", "Zambia and Zimbabwe", ["Kenya and Tanzania", "Zambia and Malawi", "Botswana and Namibia"], "Locally it is called Mosi-oa-Tunya, 'the smoke that thunders'."),
  M('geo', 3, "Angel Falls, the world's tallest uninterrupted waterfall, is in which country?", "Venezuela", ["Brazil", "Colombia", "Peru"], "It drops about 979 m."),
  T('geo', 2, "The shores of the Dead Sea are the lowest land on Earth.", true, "They lie more than 400 m below sea level."),
  T('geo', 2, "Argentina lies entirely in the Southern Hemisphere.", true, "All of Argentina is south of the Equator."),
  O('geo', 2, "Put these countries in order of area, largest first.", ["Russia", "Canada", "Brazil", "Australia"], "Largest first", "Russia 17.1, Canada 10.0, Brazil 8.5 and Australia 7.7 million km²."),
  O('geo', 2, "Put these countries in order of population as of 2024, largest first.", ["India", "China", "United States", "Indonesia"], "Largest population first", "India and China each have over 1.4 billion; the US about 340 million; Indonesia about 280 million."),
  O('geo', 2, "Put these mountains in order of height, tallest first.", ["Everest", "K2", "Kilimanjaro", "Mont Blanc"], "Tallest first", "8,849 m, 8,611 m, 5,895 m and about 4,806 m."),
  M('geo', 3, "The Atacama, one of the driest places on Earth, is mainly in which country?", "Chile", ["Peru", "Argentina", "Bolivia"], "Some Atacama weather stations have never recorded rain."),
  T('geo', 1, "The city of Istanbul lies on two continents.", true, "The Bosphorus strait divides Istanbul between Europe and Asia."),
  T('geo', 1, "Vatican City is completely surrounded by the city of Rome.", true, "It is an independent state inside Rome."),
  M('geo', 3, "Which country is completely surrounded by South Africa?", "Lesotho", ["Eswatini", "Botswana", "Namibia"], "Lesotho is a mountain kingdom; its lowest point is about 1,400 m above sea level."),
  M('geo', 2, "The Prime Meridian (0° longitude) passes through which part of London?", "Greenwich", ["Westminster", "Camden", "Kensington"], "It runs through the Royal Observatory in Greenwich."),
  M('geo', 3, "Which African country was formerly called Abyssinia?", "Ethiopia", ["Eritrea", "Somalia", "Sudan"], "Ethiopia is one of the oldest countries in the world."),
  M('geo', 2, "Which country has the most people who speak Portuguese?", "Brazil", ["Portugal", "Angola", "Mozambique"], "Brazil has over 200 million Portuguese speakers."),
  M('geo', 3, "What is the capital of Canada?", "Ottawa", ["Toronto", "Montreal", "Vancouver"], "Ottawa was chosen as the capital by Queen Victoria in 1857."),
  M('geo', 2, "What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Perth"], "Canberra was purpose-built as a compromise between Sydney and Melbourne."),
  M('geo', 3, "The Great Rift Valley runs mainly through which continent?", "Africa", ["Asia", "South America", "Europe"], "It stretches from the Red Sea down through East Africa."),
  M('geo', 2, "Which sea lies between Europe and Africa, east of Spain?", "Mediterranean Sea", ["Black Sea", "Red Sea", "Caribbean Sea"], "The Mediterranean is almost enclosed by land."),
  M('geo', 2, "Which line of latitude divides Earth into the Northern and Southern Hemispheres?", "The Equator", ["Tropic of Cancer", "Prime Meridian", "Arctic Circle"], "The Equator is at 0° latitude."),

  // history
  N('his', 1, "In which year did the First World War begin?", 1914, "", 1, "War broke out in July–August 1914."),
  N('his', 1, "In which year did the Second World War end?", 1945, "", 1, "It ended with Japan's surrender in September 1945."),
  N('his', 1, "In which year did the Berlin Wall fall?", 1989, "", 1, "The border opened on 9 November 1989."),
  N('his', 1, "In which year did the Titanic sink?", 1912, "", 1, "The Titanic sank on 15 April 1912."),
  N('his', 1, "In which year did Christopher Columbus first reach the Americas?", 1492, "", 2, "He landed in the Bahamas in October 1492."),
  M('his', 2, "Which English king sealed Magna Carta in 1215?", "King John", ["Henry VIII", "Richard I", "Edward I"], "Barons forced John to agree to it at Runnymede."),
  N('his', 2, "In which year did the French Revolution begin?", 1789, "", 3, "The storming of the Bastille was on 14 July 1789."),
  N('his', 1, "In which year was the US Declaration of Independence adopted?", 1776, "", 2, "It was adopted on 4 July 1776."),
  M('his', 1, "Who was the first President of the United States?", "George Washington", ["Thomas Jefferson", "John Adams", "Abraham Lincoln"], "Washington took office in 1789."),
  M('his', 1, "Who was US President during the American Civil War?", "Abraham Lincoln", ["George Washington", "Ulysses S. Grant", "Andrew Jackson"], "Lincoln led the Union from 1861 until he was assassinated in 1865."),
  M('his', 1, "Who was the British Prime Minister for most of the Second World War?", "Winston Churchill", ["Neville Chamberlain", "Clement Attlee", "David Lloyd George"], "Churchill became Prime Minister in May 1940."),
  M('his', 1, "Which of the Seven Wonders of the Ancient World is still standing?", "Great Pyramid of Giza", ["Colossus of Rhodes", "Lighthouse of Alexandria", "Hanging Gardens of Babylon"], "The Great Pyramid is about 4,500 years old."),
  M('his', 2, "Who was the first Roman emperor?", "Augustus", ["Julius Caesar", "Nero", "Caligula"], "Julius Caesar was a dictator; his heir Augustus became the first emperor in 27 BC."),
  N('his', 3, "In which year BC was Julius Caesar assassinated?", 44, "BC", 1, "He was killed on the Ides of March (15 March), 44 BC."),
  M('his', 1, "Cleopatra was the last active ruler of which ancient kingdom?", "Egypt", ["Persia", "Greece", "Carthage"], "She was the last ruler of Ptolemaic Egypt."),
  M('his', 3, "Who led the excavation that found Tutankhamun's tomb in 1922?", "Howard Carter", ["Flinders Petrie", "Heinrich Schliemann", "Arthur Evans"], "Carter found the tomb in the Valley of the Kings."),
  M('his', 2, "The Rosetta Stone was key to deciphering which writing system?", "Egyptian hieroglyphs", ["Cuneiform", "Linear B", "Maya glyphs"], "It carries the same text in hieroglyphs, Demotic and Greek."),
  M('his', 1, "The Vikings came mainly from which region?", "Scandinavia", ["Italy", "Greece", "Iberia"], "Vikings sailed from what are now Norway, Denmark and Sweden."),
  N('his', 2, "In which year was the Battle of Hastings?", 1066, "", 3, "William of Normandy defeated King Harold in October 1066."),
  M('his', 2, "William the Conqueror came from which region of France?", "Normandy", ["Brittany", "Burgundy", "Provence"], "He was Duke of Normandy before he became King of England."),
  N('his', 2, "In which year was the Great Fire of London?", 1666, "", 3, "It burned for four days in September 1666."),
  M('his', 2, "In which century did the Black Death sweep across Europe?", "14th century", ["12th century", "16th century", "10th century"], "The plague peaked in Europe between 1347 and 1351."),
  M('his', 1, "Who was the first woman to become UK Prime Minister?", "Margaret Thatcher", ["Theresa May", "Liz Truss", "Barbara Castle"], "Thatcher became Prime Minister in 1979."),
  N('his', 2, "In which year did Nelson Mandela become President of South Africa?", 1994, "", 2, "He took office after the country's first fully democratic election."),
  M('his', 1, "What was the name of the ship that carried the Pilgrims to America in 1620?", "Mayflower", ["Santa María", "Endeavour", "Beagle"], "The Mayflower sailed from Plymouth, England."),
  M('his', 2, "On which ship did Charles Darwin sail around the world?", "HMS Beagle", ["HMS Endeavour", "HMS Victory", "HMS Bounty"], "The voyage lasted from 1831 to 1836."),
  M('his', 3, "What was the name of Captain James Cook's ship on his first great voyage?", "HMS Endeavour", ["HMS Beagle", "HMS Resolution", "Golden Hind"], "Endeavour reached Australia's east coast in 1770."),
  M('his', 2, "Whose expedition completed the first circumnavigation of the globe (1519–1522)?", "Ferdinand Magellan", ["Vasco da Gama", "Francis Drake", "James Cook"], "Magellan died on the way; Juan Sebastián Elcano brought the last ship home."),
  M('his', 3, "Who led the first voyage from Europe to India around Africa, in 1497–98?", "Vasco da Gama", ["Ferdinand Magellan", "Christopher Columbus", "Bartolomeu Dias"], "Da Gama reached Calicut, India, in 1498."),
  M('his', 2, "Who led the first expedition to reach the South Pole?", "Roald Amundsen", ["Robert Falcon Scott", "Ernest Shackleton", "Edmund Hillary"], "Amundsen's team arrived in December 1911, about a month before Scott."),
  M('his', 1, "Who were the first climbers confirmed to reach the summit of Mount Everest, in 1953?", "Edmund Hillary and Tenzing Norgay", ["George Mallory and Andrew Irvine", "Reinhold Messner and Peter Habeler", "Roald Amundsen and Robert Scott"], "They reached the top on 29 May 1953."),
  T('his', 1, "The Great Wall of China is visible from the Moon with the naked eye.", false, "It is far too narrow to see from the Moon."),
  M('his', 1, "Napoleon's final defeat came at which battle in 1815?", "Waterloo", ["Trafalgar", "Austerlitz", "Leipzig"], "Wellington and Blücher defeated him near Brussels."),
  M('his', 3, "On which island did Napoleon spend his final exile?", "Saint Helena", ["Elba", "Corsica", "Sardinia"], "He died on Saint Helena, in the South Atlantic, in 1821."),
  M('his', 2, "Which admiral commanded the British fleet at the Battle of Trafalgar?", "Horatio Nelson", ["Francis Drake", "Walter Raleigh", "James Cook"], "Nelson won the battle in 1805 but was killed during it."),
  N('his', 3, "For about how many years did Queen Victoria reign?", 63, "years", 1, "She reigned from 1837 to 1901."),
  N('his', 1, "How many wives did King Henry VIII have?", 6, "wives", 0, "Divorced, beheaded, died, divorced, beheaded, survived."),
  M('his', 2, "Who was the father of Queen Elizabeth I?", "Henry VIII", ["Henry VII", "Edward VI", "James I"], "Her mother was Anne Boleyn."),
  N('his', 3, "In which year did the Spanish Armada sail against England?", 1588, "", 3, "The Armada was defeated in the summer of 1588."),
  N('his', 3, "In which year AD did Mount Vesuvius bury Pompeii?", 79, "AD", 0, "The eruption of AD 79 preserved the town under ash."),
  M('his', 1, "Genghis Khan founded which empire?", "Mongol Empire", ["Ottoman Empire", "Persian Empire", "Mughal Empire"], "The Mongol Empire became the largest contiguous land empire in history."),
  M('his', 3, "What was the capital city of the Aztec Empire?", "Tenochtitlan", ["Cusco", "Chichén Itzá", "Teotihuacan"], "Mexico City is built on its ruins."),
  N('his', 2, "In which year did the Soviet Union break up?", 1991, "", 1, "The USSR was formally dissolved in December 1991."),
  M('his', 2, "In which city did Martin Luther King Jr. give his 'I Have a Dream' speech?", "Washington, D.C.", ["Atlanta", "Memphis", "Montgomery"], "He spoke at the Lincoln Memorial in August 1963."),
  N('his', 2, "In which year was the Wall Street Crash?", 1929, "", 1, "Prices collapsed in October 1929, leading into the Great Depression."),
  M('his', 1, "Hadrian's Wall in northern England was built by which empire?", "Roman Empire", ["Viking", "Norman", "Byzantine Empire"], "Building began around AD 122 under Emperor Hadrian."),
  M('his', 1, "Who led the Soviet Union during the Second World War?", "Joseph Stalin", ["Vladimir Lenin", "Nikita Khrushchev", "Leon Trotsky"], "Stalin ruled the USSR from the 1920s until his death in 1953."),
  M('his', 1, "Mahatma Gandhi led the independence movement of which country?", "India", ["Pakistan", "South Africa", "Sri Lanka"], "He championed non-violent protest."),
  N('his', 2, "In which year did India gain independence from Britain?", 1947, "", 1, "Independence came on 15 August 1947."),
  M('his', 2, "The D-Day landings in June 1944 took place on the beaches of which region?", "Normandy", ["Brittany", "Calais", "Flanders"], "Allied troops landed on 6 June 1944."),
  T('his', 1, "The attack on Pearl Harbor took place in 1941.", true, "Japan attacked the US naval base in Hawaii on 7 December 1941."),
  O('his', 2, "Put these events in order, earliest first.", ["Battle of Hastings", "Magna Carta", "Columbus reaches the Americas", "French Revolution begins"], "Earliest first", "1066, 1215, 1492 and 1789."),
  O('his', 1, "Put these 20th-century events in order, earliest first.", ["First World War begins", "Wall Street Crash", "First Moon landing", "Fall of the Berlin Wall"], "Earliest first", "1914, 1929, 1969 and 1989."),
  O('his', 3, "Put these ancient events in order, earliest first.", ["Great Pyramid of Giza built", "Traditional founding of Rome", "Julius Caesar assassinated", "Fall of the Western Roman Empire"], "Earliest first", "About 2560 BC, 753 BC, 44 BC and AD 476."),
  M('his', 1, "Which country gave the Statue of Liberty to the United States?", "France", ["United Kingdom", "Spain", "Italy"], "It was dedicated in New York Harbor in 1886."),
  N('his', 2, "In which year was the Eiffel Tower completed?", 1889, "", 3, "It was built for the 1889 World's Fair in Paris."),
  M('his', 1, "Joan of Arc was a heroine of which country?", "France", ["England", "Spain", "Italy"], "She led French forces in the Hundred Years' War."),
  M('his', 3, "Who was the first emperor of a unified China?", "Qin Shi Huang", ["Kublai Khan", "Sun Yat-sen", "Puyi"], "He unified China in 221 BC; Puyi was the last emperor."),
  M('his', 1, "In which country was the Terracotta Army discovered?", "China", ["Japan", "Korea", "Mongolia"], "Farmers found it near Xi'an in 1974."),
  M('his', 3, "From which English port did the Titanic set sail on its maiden voyage?", "Southampton", ["Liverpool", "Plymouth", "Dover"], "It left Southampton on 10 April 1912."),
  M('his', 1, "In which country did the Renaissance begin?", "Italy", ["France", "England", "Spain"], "It began in Florence in the 14th century."),
  M('his', 2, "Which ancient wonder was a giant bronze statue of the sun god Helios?", "Colossus of Rhodes", ["Temple of Artemis", "Statue of Zeus at Olympia", "Mausoleum at Halicarnassus"], "It stood on the Greek island of Rhodes until an earthquake toppled it around 226 BC."),
  M('his', 3, "Which empire was ruled from Constantinople for about a thousand years?", "Byzantine Empire", ["Mongol Empire", "Holy Roman Empire", "Persian Empire"], "It fell to the Ottomans in 1453."),
  M('his', 3, "Who wrote the 95 Theses in 1517, sparking the Protestant Reformation?", "Martin Luther", ["John Calvin", "Henry VIII", "Thomas More"], "Luther challenged the sale of indulgences."),
  M('his', 3, "Which civilisation built the city of Machu Picchu?", "Inca", ["Aztec", "Maya", "Olmec"], "It was built in the 15th century for the Inca emperor Pachacuti."),
  M('his', 2, "Who was the first person to fly solo non-stop across the Atlantic, in 1927?", "Charles Lindbergh", ["Amelia Earhart", "Louis Blériot", "Orville Wright"], "Lindbergh flew from New York to Paris in the Spirit of St. Louis."),
  M('his', 3, "Who was the first woman to fly solo across the Atlantic, in 1932?", "Amelia Earhart", ["Amy Johnson", "Bessie Coleman", "Valentina Tereshkova"], "She flew from Newfoundland to Northern Ireland."),
  M('his', 1, "The Bastille, stormed in 1789, was in which city?", "Paris", ["Lyon", "Versailles", "Marseille"], "Its fall on 14 July is celebrated as France's national day."),

  // arts
  M('art', 1, "Who painted the Mona Lisa?", "Leonardo da Vinci", ["Michelangelo", "Raphael", "Botticelli"], "It hangs in the Louvre in Paris."),
  M('art', 1, "Who painted the ceiling of the Sistine Chapel?", "Michelangelo", ["Leonardo da Vinci", "Raphael", "Titian"], "He painted it between 1508 and 1512."),
  M('art', 1, "Who painted 'The Starry Night'?", "Vincent van Gogh", ["Claude Monet", "Paul Cézanne", "Paul Gauguin"], "Van Gogh painted it in 1889."),
  T('art', 1, "Vincent van Gogh cut off part of his own ear.", true, "It happened in Arles, France, in December 1888."),
  M('art', 2, "Who painted 'The Scream'?", "Edvard Munch", ["Gustav Klimt", "Egon Schiele", "Wassily Kandinsky"], "Munch was Norwegian; he made several versions."),
  M('art', 3, "Who painted 'Girl with a Pearl Earring'?", "Johannes Vermeer", ["Rembrandt", "Frans Hals", "Jan van Eyck"], "Vermeer was a Dutch painter of the 1600s."),
  M('art', 2, "Who painted 'The Persistence of Memory', with its melting clocks?", "Salvador Dalí", ["René Magritte", "Pablo Picasso", "Joan Miró"], "Dalí was a leading Surrealist."),
  M('art', 2, "Who painted 'Guernica'?", "Pablo Picasso", ["Salvador Dalí", "Joan Miró", "Francisco Goya"], "Picasso painted it in 1937 after the bombing of the Spanish town."),
  M('art', 2, "Who painted the 'Water Lilies' series?", "Claude Monet", ["Édouard Manet", "Pierre-Auguste Renoir", "Edgar Degas"], "Monet painted the pond in his garden at Giverny many times."),
  M('art', 3, "Who painted 'The Birth of Venus'?", "Sandro Botticelli", ["Titian", "Raphael", "Caravaggio"], "It hangs in the Uffizi Gallery in Florence."),
  M('art', 2, "Claude Monet was a founder of which art movement?", "Impressionism", ["Cubism", "Surrealism", "Baroque"], "The movement was named after his painting 'Impression, Sunrise'."),
  M('art', 2, "Pablo Picasso co-founded which art movement?", "Cubism", ["Impressionism", "Pop Art", "Romanticism"], "He developed Cubism with Georges Braque."),
  M('art', 2, "Who carved the giant marble statue of David that stands in Florence's Accademia?", "Michelangelo", ["Raphael", "Auguste Rodin", "Titian"], "He finished it in 1504."),
  M('art', 2, "Who sculpted 'The Thinker'?", "Auguste Rodin", ["Michelangelo", "Donatello", "Henry Moore"], "Rodin was a French sculptor."),
  M('art', 3, "Which architect designed Barcelona's Sagrada Família?", "Antoni Gaudí", ["Le Corbusier", "Frank Lloyd Wright", "Joan Miró"], "Building started in 1882 and is still going on."),
  M('art', 3, "Which architect designed the Sydney Opera House?", "Jørn Utzon", ["Frank Gehry", "Renzo Piano", "Norman Foster"], "Utzon was Danish; the building opened in 1973."),
  M('art', 2, "In which Indian city is the Taj Mahal?", "Agra", ["Delhi", "Jaipur", "Mumbai"], "The Taj Mahal stands on the bank of the Yamuna river."),
  M('art', 3, "Which Mughal emperor built the Taj Mahal as a tomb for his wife?", "Shah Jahan", ["Akbar", "Babur", "Aurangzeb"], "He built it for his wife Mumtaz Mahal."),
  M('art', 1, "In which Italian city is the famous leaning tower?", "Pisa", ["Florence", "Venice", "Rome"], "It started leaning while it was still being built."),
  M('art', 3, "Who painted 'The Night Watch'?", "Rembrandt", ["Johannes Vermeer", "Peter Paul Rubens", "Hieronymus Bosch"], "It is in the Rijksmuseum, Amsterdam."),
  M('art', 2, "Which artist made famous screen prints of soup cans?", "Andy Warhol", ["Roy Lichtenstein", "Keith Haring", "Jackson Pollock"], "Warhol was a leader of Pop Art."),
  M('art', 3, "Which painter was famous for 'drip' paintings made by pouring paint on canvas on the floor?", "Jackson Pollock", ["Mark Rothko", "Andy Warhol", "Henri Matisse"], "Pollock was an Abstract Expressionist."),
  M('art', 1, "Who painted 'The Last Supper' on a wall in Milan?", "Leonardo da Vinci", ["Michelangelo", "Caravaggio", "Giotto"], "Leonardo painted it in the 1490s."),
  M('art', 3, "Who painted the Japanese woodblock print 'The Great Wave off Kanagawa'?", "Hokusai", ["Hiroshige", "Utamaro", "Sesshū"], "It was published around 1831."),

  // music
  M('mus', 1, "Which composer kept writing music after going deaf?", "Ludwig van Beethoven", ["Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frédéric Chopin"], "Beethoven composed his Ninth Symphony when almost completely deaf."),
  M('mus', 2, "Who composed 'The Four Seasons'?", "Antonio Vivaldi", ["George Frideric Handel", "Johann Sebastian Bach", "Joseph Haydn"], "Vivaldi wrote the four violin concertos around 1720."),
  M('mus', 3, "Who composed the opera 'The Magic Flute'?", "Wolfgang Amadeus Mozart", ["Giuseppe Verdi", "Richard Wagner", "Giacomo Puccini"], "It premiered in Vienna in 1791, the year Mozart died."),
  M('mus', 2, "Who composed the music for the ballet 'The Nutcracker'?", "Pyotr Ilyich Tchaikovsky", ["Sergei Prokofiev", "Igor Stravinsky", "Nikolai Rimsky-Korsakov"], "It premiered in St Petersburg in 1892."),
  N('mus', 1, "How many strings does a standard guitar have?", 6, "strings", 0, "Standard tuning is E A D G B E."),
  N('mus', 2, "How many keys does a standard modern piano have?", 88, "keys", 0, "52 white keys and 36 black keys."),
  N('mus', 1, "How many strings does a violin have?", 4, "strings", 0, "They are tuned G, D, A and E."),
  M('mus', 1, "Which family of instruments does the trumpet belong to?", "Brass", ["Woodwind", "Strings", "Percussion"], "You play brass instruments by buzzing your lips."),
  T('mus', 2, "The flute belongs to the brass family because it is usually made of metal.", false, "The flute is a woodwind: instruments are classed by how they are played, not what they are made of."),
  N('mus', 2, "How many lines are there on a standard musical staff?", 5, "lines", 0, "Notes sit on the five lines and in the four spaces between them."),
  M('mus', 1, "Which city were the Beatles from?", "Liverpool", ["London", "Manchester", "Birmingham"], "The band formed in Liverpool in 1960."),
  M('mus', 1, "Which singer was known as 'the King of Rock and Roll'?", "Elvis Presley", ["Chuck Berry", "Little Richard", "Buddy Holly"], "Elvis became famous in the mid-1950s."),
  M('mus', 1, "Which singer was known as 'the King of Pop'?", "Michael Jackson", ["Prince", "Elvis Presley", "Stevie Wonder"], "His 1982 album Thriller is one of the best-selling albums ever."),
  M('mus', 1, "Freddie Mercury was the lead singer of which band?", "Queen", ["The Rolling Stones", "Led Zeppelin", "The Who"], "Queen formed in London in 1970."),
  M('mus', 3, "In which city was Wolfgang Amadeus Mozart born?", "Salzburg", ["Vienna", "Bonn", "Leipzig"], "Mozart was born in Salzburg in 1756."),
  M('mus', 3, "What were the first names of the composer J. S. Bach?", "Johann Sebastian", ["Johann Strauss", "Josef Stefan", "Jan Sebastian"], "Bach lived from 1685 to 1750."),
  O('mus', 2, "Put these composers in order of birth, earliest first.", ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Pyotr Ilyich Tchaikovsky"], "Born earliest first", "1685, 1756, 1770 and 1840."),
  M('mus', 1, "How many musicians play in a quartet?", "Four", ["Three", "Five", "Eight"], "A string quartet has two violins, a viola and a cello."),
  M('mus', 2, "What does 'forte' mean in music?", "Loud", ["Soft", "Fast", "Slow"], "Piano means soft; forte means loud."),
  M('mus', 3, "Which composer wrote the 'Moonlight' Sonata?", "Ludwig van Beethoven", ["Frédéric Chopin", "Franz Schubert", "Claude Debussy"], "The 'Moonlight' nickname was given after Beethoven's death."),
  M('mus', 2, "What is the largest instrument in the string family of an orchestra?", "Double bass", ["Cello", "Viola", "Harp"], "The double bass is the biggest and lowest-pitched member of the string section."),
  M('mus', 3, "Which composer wrote the 'Ode to Joy' melody, now the anthem of the European Union?", "Ludwig van Beethoven", ["Joseph Haydn", "George Frideric Handel", "Franz Liszt"], "It comes from the last movement of his Ninth Symphony."),

  // literature
  M('lit', 1, "Who wrote 'Romeo and Juliet'?", "William Shakespeare", ["Christopher Marlowe", "Charles Dickens", "Geoffrey Chaucer"], "Shakespeare wrote it in the 1590s."),
  M('lit', 1, "Who wrote 'Pride and Prejudice'?", "Jane Austen", ["Charlotte Brontë", "Mary Shelley", "George Eliot"], "It was published in 1813."),
  M('lit', 1, "Who wrote the novel '1984'?", "George Orwell", ["Aldous Huxley", "H. G. Wells", "Ray Bradbury"], "Orwell also wrote Animal Farm."),
  M('lit', 3, "Who wrote 'Don Quixote'?", "Miguel de Cervantes", ["Lope de Vega", "Gabriel García Márquez", "Federico García Lorca"], "It was published in two parts in 1605 and 1615."),
  M('lit', 2, "Who wrote 'War and Peace'?", "Leo Tolstoy", ["Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"], "It follows Russian families during Napoleon's invasion."),
  M('lit', 2, "Which ancient Greek poet is credited with 'The Odyssey'?", "Homer", ["Sophocles", "Virgil", "Aesop"], "The Odyssey follows Odysseus's long journey home from Troy."),
  M('lit', 1, "Who created the detective Sherlock Holmes?", "Arthur Conan Doyle", ["Agatha Christie", "Edgar Allan Poe", "Charles Dickens"], "Holmes first appeared in 1887."),
  M('lit', 1, "Who wrote 'Frankenstein'?", "Mary Shelley", ["Bram Stoker", "Emily Brontë", "Jane Austen"], "She began it as a ghost-story challenge in 1816."),
  M('lit', 2, "Who wrote 'Moby-Dick'?", "Herman Melville", ["Mark Twain", "Nathaniel Hawthorne", "Jack London"], "It was published in 1851."),
  M('lit', 2, "Shakespeare's Hamlet is the prince of which country?", "Denmark", ["Norway", "Scotland", "Sweden"], "The play is set at Elsinore Castle."),
  M('lit', 3, "Who wrote 'The Divine Comedy'?", "Dante Alighieri", ["Giovanni Boccaccio", "Petrarch", "Virgil"], "It describes a journey through Hell, Purgatory and Paradise."),
  M('lit', 2, "Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", ["Ernest Hemingway", "John Steinbeck", "William Faulkner"], "It was published in 1925."),
  M('lit', 1, "Who wrote 'Alice's Adventures in Wonderland'?", "Lewis Carroll", ["Roald Dahl", "J. M. Barrie", "Kenneth Grahame"], "It was published in 1865."),
  M('lit', 1, "Who wrote 'Dracula'?", "Bram Stoker", ["Mary Shelley", "Robert Louis Stevenson", "Oscar Wilde"], "Dracula was published in 1897."),
  M('lit', 2, "Who wrote 'Les Misérables'?", "Victor Hugo", ["Alexandre Dumas", "Gustave Flaubert", "Émile Zola"], "It was published in 1862."),
  M('lit', 2, "In which town was William Shakespeare born?", "Stratford-upon-Avon", ["London", "Oxford", "Canterbury"], "He was born there in 1564."),
  N('lit', 2, "How many syllables does a traditional haiku have in total?", 17, "syllables", 0, "Three lines of 5, 7 and 5 syllables."),
  N('lit', 2, "How many lines does a sonnet have?", 14, "lines", 0, "Shakespeare wrote 154 sonnets."),
  M('lit', 2, "Who wrote 'Treasure Island'?", "Robert Louis Stevenson", ["Daniel Defoe", "Jules Verne", "Jonathan Swift"], "It was published as a book in 1883."),
  M('lit', 1, "Who wrote 'Oliver Twist'?", "Charles Dickens", ["William Thackeray", "Thomas Hardy", "Anthony Trollope"], "It was published as a serial from 1837."),
  M('lit', 2, "Who wrote 'Robinson Crusoe'?", "Daniel Defoe", ["Jonathan Swift", "Robert Louis Stevenson", "Herman Melville"], "It was published in 1719."),
  M('lit', 2, "Who wrote 'Gulliver's Travels'?", "Jonathan Swift", ["Daniel Defoe", "Lewis Carroll", "Henry Fielding"], "It was published in 1726."),
  M('lit', 3, "Who wrote 'Twenty Thousand Leagues Under the Seas'?", "Jules Verne", ["H. G. Wells", "Arthur Conan Doyle", "Victor Hugo"], "It features Captain Nemo and the submarine Nautilus."),
  M('lit', 2, "Who wrote 'The War of the Worlds'?", "H. G. Wells", ["Jules Verne", "Isaac Asimov", "Arthur C. Clarke"], "Martians invade England in the 1898 novel."),
  M('lit', 1, "Who wrote 'The Lord of the Rings'?", "J. R. R. Tolkien", ["C. S. Lewis", "Terry Pratchett", "George R. R. Martin"], "It was published in 1954–55."),
  M('lit', 1, "Who wrote 'The Lion, the Witch and the Wardrobe'?", "C. S. Lewis", ["J. R. R. Tolkien", "Roald Dahl", "Philip Pullman"], "It was the first Narnia book published, in 1950."),
  M('lit', 1, "Who wrote 'Charlie and the Chocolate Factory'?", "Roald Dahl", ["Enid Blyton", "Dr. Seuss", "Beatrix Potter"], "It was published in 1964."),
  M('lit', 2, "Who wrote 'Jane Eyre'?", "Charlotte Brontë", ["Emily Brontë", "Anne Brontë", "Jane Austen"], "Her sister Emily wrote Wuthering Heights."),
  M('lit', 1, "Who wrote 'The Adventures of Tom Sawyer'?", "Mark Twain", ["Herman Melville", "Jack London", "Edgar Allan Poe"], "Mark Twain was the pen name of Samuel Clemens."),
  M('lit', 3, "Who wrote the epic poem 'Paradise Lost'?", "John Milton", ["John Donne", "William Blake", "Geoffrey Chaucer"], "It was first published in 1667."),
  M('lit', 3, "Who wrote 'The Canterbury Tales'?", "Geoffrey Chaucer", ["William Langland", "John Gower", "Thomas Malory"], "Chaucer wrote it in the late 1300s."),
  M('lit', 3, "Who wrote 'Crime and Punishment'?", "Fyodor Dostoevsky", ["Leo Tolstoy", "Nikolai Gogol", "Alexander Pushkin"], "It was published in 1866."),

  // language
  M('lang', 2, "Which language has the most native speakers?", "Mandarin Chinese", ["Spanish", "English", "Hindi"], "Mandarin has over 900 million native speakers."),
  N('lang', 2, "How many national languages does Switzerland have?", 4, "languages", 0, "German, French, Italian and Romansh."),
  N('lang', 1, "How many letters are in the English alphabet?", 26, "letters", 0, "From A to Z there are 26 letters."),
  N('lang', 3, "How many letters are in the modern Greek alphabet?", 24, "letters", 0, "From alpha to omega there are 24 letters."),
  M('lang', 2, "What is the last letter of the Greek alphabet?", "Omega", ["Zeta", "Alpha", "Sigma"], "'Alpha and omega' means the beginning and the end."),
  M('lang', 2, "What does the Latin phrase 'carpe diem' mean?", "Seize the day", ["Love conquers all", "Time flies", "I came, I saw, I conquered"], "The phrase comes from the Roman poet Horace."),
  M('lang', 1, "'Bonjour' means 'hello' in which language?", "French", ["Spanish", "Italian", "Portuguese"], "Bonjour literally means 'good day'."),
  M('lang', 1, "What does 'gracias' mean in Spanish?", "Thank you", ["Please", "Goodbye", "Hello"], "'Muchas gracias' means 'thank you very much'."),
  M('lang', 1, "'Danke' means 'thank you' in which language?", "German", ["Dutch", "Swedish", "Polish"], "'Danke schön' means 'thank you very much'."),
  M('lang', 1, "What is the word for an extreme fear of spiders?", "Arachnophobia", ["Claustrophobia", "Agoraphobia", "Acrophobia"], "Arachne is Greek for spider."),
  M('lang', 3, "What is the word for an extreme fear of heights?", "Acrophobia", ["Claustrophobia", "Agoraphobia", "Hydrophobia"], "Akron is Greek for 'peak' or 'summit'."),
  M('lang', 1, "Which of these words is a palindrome (reads the same backwards)?", "Racecar", ["Radish", "Rocket", "Reader"], "R-A-C-E-C-A-R reads the same in both directions."),
  M('lang', 2, "'Silent' is an anagram of which word?", "Listen", ["Lilies", "Tiles", "Stolen"], "Both words use the letters E, I, L, N, S and T."),
  M('lang', 2, "Words that sound the same but have different meanings, like 'pair' and 'pear', are called…", "Homophones", ["Synonyms", "Antonyms", "Acronyms"], "Homo means 'same' and phone means 'sound'."),
  M('lang', 1, "A word that means the opposite of another word is called…", "An antonym", ["A synonym", "A homonym", "A pronoun"], "Hot and cold are antonyms."),
  M('lang', 3, "In 'NASA', what does the second A stand for?", "Administration", ["Agency", "Association", "Astronomy"], "NASA is the National Aeronautics and Space Administration."),
  T('lang', 2, "The word 'laser' started out as an acronym.", true, "It stands for Light Amplification by Stimulated Emission of Radiation."),
  T('lang', 2, "Esperanto is a constructed language created in the 19th century.", true, "L. L. Zamenhof published it in 1887."),
  N('lang', 3, "How many main scripts are mixed together in written Japanese?", 3, "", 0, "Hiragana, katakana and kanji."),
  M('lang', 3, "What is the main official language of Iran?", "Persian", ["Arabic", "Turkish", "Urdu"], "Persian is also called Farsi."),
  T('lang', 1, "Arabic is written from right to left.", true, "Arabic, like Hebrew, is read from right to left."),
  M('lang', 2, "The word 'kindergarten' comes from which language?", "German", ["Dutch", "Danish", "French"], "It means 'children's garden'."),
  M('lang', 2, "The word 'tsunami' comes from which language?", "Japanese", ["Hawaiian", "Indonesian", "Chinese"], "It means 'harbour wave'."),
  M('lang', 3, "The word 'robot' comes from which language?", "Czech", ["Russian", "German", "Polish"], "It was introduced in Karel Čapek's 1920 play R.U.R."),
  M('lang', 3, "The word 'algebra' comes from which language?", "Arabic", ["Greek", "Latin", "Persian"], "It comes from al-jabr, in a book by al-Khwarizmi."),
  M('lang', 3, "The English word 'shampoo' comes from which language?", "Hindi", ["Japanese", "Portuguese", "Greek"], "It comes from the Hindi word chāmpo, meaning to press or massage."),
  M('lang', 2, "A sentence that uses every letter of the alphabet is called a…", "Pangram", ["Palindrome", "Anagram", "Acrostic"], "'The quick brown fox jumps over the lazy dog' is a famous pangram."),
  M('lang', 2, "Which is the most commonly used letter in written English?", "E", ["A", "T", "S"], "E appears in about one in eight letters of English text."),
  M('lang', 1, "What is the main language spoken in the Canadian province of Quebec?", "French", ["English", "Spanish", "Inuktitut"], "French is Quebec's only official language."),
  M('lang', 2, "Which country has the most native Spanish speakers?", "Mexico", ["Spain", "Colombia", "Argentina"], "Mexico has over 120 million Spanish speakers."),
  M('lang', 1, "What is the official language of Egypt?", "Arabic", ["Turkish", "Coptic", "Hebrew"], "Arabic replaced Coptic as the main language centuries ago."),
  T('lang', 3, "Basque is not known to be related to any other living language.", true, "Basque is a language isolate, spoken in Spain and France."),
  M('lang', 2, "What is the plural of 'crisis'?", "Crises", ["Crisises", "Crisi", "Crisae"], "Words ending in -is from Greek often change to -es: one thesis, two theses."),
  M('lang', 1, "Which language is the main language of Brazil?", "Portuguese", ["Spanish", "Brazilian", "French"], "Brazil was a Portuguese colony."),
  M('lang', 3, "What does the abbreviation 'e.g.' stand for?", "Exempli gratia (for example)", ["Et genus (and type)", "Ergo (therefore)", "Est grande (it is great)"], "'i.e.' is id est, 'that is'."),
  M('lang', 2, "What does 'etc.' stand for?", "Et cetera", ["Et cuius", "Est certum", "Ex tempore"], "Et cetera is Latin for 'and the rest'."),
  M('lang', 2, "Which part of speech describes a noun, like 'big' or 'green'?", "Adjective", ["Adverb", "Verb", "Preposition"], "Adjectives describe nouns; adverbs describe verbs."),
  M('lang', 3, "What is the name of the alphabet used to write Russian?", "Cyrillic", ["Latin", "Greek", "Glagolitic"], "Cyrillic is also used for Bulgarian, Serbian and others."),

  // nature and animals
  M('ani', 2, "What is the fastest bird in a dive?", "Peregrine falcon", ["Golden eagle", "Swift", "Albatross"], "A diving peregrine can top 300 km/h."),
  M('ani', 1, "What is the only mammal capable of true flight?", "Bat", ["Flying squirrel", "Sugar glider", "Colugo"], "Flying squirrels and colugos glide; only bats truly fly."),
  N('ani', 2, "How many hearts does an octopus have?", 3, "hearts", 0, "Two pump blood through the gills and one through the body."),
  M('ani', 2, "What is a group of crows called?", "A murder", ["A parliament", "A gaggle", "A pod"], "A parliament is owls, a gaggle is geese, a pod is dolphins."),
  M('ani', 3, "What is a baby swan called?", "Cygnet", ["Gosling", "Duckling", "Eaglet"], "A gosling is a baby goose."),
  M('ani', 3, "What is a male honeybee called?", "Drone", ["Worker", "Queen", "Soldier"], "Drones' main job is to mate with a queen."),
  M('ani', 1, "What does a koala mostly eat?", "Eucalyptus leaves", ["Bamboo", "Grass", "Insects"], "Koalas sleep up to 20 hours a day to save energy."),
  M('ani', 1, "Which of these mammals lays eggs?", "Platypus", ["Kangaroo", "Koala", "Wombat"], "The platypus and echidnas are the only egg-laying mammals."),
  T('ani', 2, "Snakes use their tongues to smell.", true, "The tongue collects scent particles and passes them to an organ in the mouth."),
  T('ani', 3, "Dolphins can sleep with one half of their brain at a time.", true, "This lets them keep surfacing to breathe."),
  T('ani', 2, "A shark's skeleton is made of cartilage, not bone.", true, "Cartilage is the same flexible material as in your ears."),
  T('ani', 3, "Starfish do not have a brain.", true, "They have a ring of nerves instead of a central brain."),
  T('ani', 1, "Bats are blind.", false, "All bats can see; many also use echolocation."),
  T('ani', 1, "Goldfish have a memory of only three seconds.", false, "Studies show goldfish can remember things for months."),
  M('ani', 2, "What is the largest living reptile?", "Saltwater crocodile", ["Komodo dragon", "Green anaconda", "Leatherback turtle"], "Big male saltwater crocodiles can exceed 6 m long."),
  M('ani', 2, "What is the largest living lizard?", "Komodo dragon", ["Green iguana", "Monitor lizard", "Gila monster"], "Komodo dragons can grow to 3 m long."),
  M('ani', 1, "What is the largest species of cat?", "Tiger", ["Lion", "Jaguar", "Leopard"], "Siberian tigers can weigh over 300 kg."),
  M('ani', 3, "Which animal is the longest-lived vertebrate known?", "Greenland shark", ["Galápagos tortoise", "Bowhead whale", "Koi carp"], "Some Greenland sharks are estimated to be several hundred years old."),
  T('ani', 1, "Camels store water in their humps.", false, "Humps store fat, which camels can use for energy."),
  M('ani', 1, "Bees make honey from which part of flowers?", "Nectar", ["Pollen", "Petals", "Sap"], "Bees turn sugary nectar into honey in the hive."),
  M('ani', 3, "Which animal has the largest eyes in the animal kingdom?", "Colossal squid", ["Blue whale", "Ostrich", "Giant panda"], "Its eyes can be about 27 cm across."),
  T('ani', 1, "Hummingbirds can fly backwards.", true, "They are the only birds that can truly fly backwards."),
  M('ani', 1, "The kiwi bird is native to which country?", "New Zealand", ["Australia", "South Africa", "Chile"], "The kiwi is a flightless bird and a national symbol."),
  T('ani', 2, "A rhino's horn is made of bone.", false, "Rhino horns are solid keratin, like hair and nails."),
  T('ani', 2, "Coral is a plant.", false, "Corals are animals: colonies of tiny creatures called polyps."),
  M('ani', 1, "Which animal is known as the 'ship of the desert'?", "Camel", ["Horse", "Ostrich", "Elephant"], "Camels can go days without drinking."),
  M('ani', 1, "Which bird lays the largest eggs?", "Ostrich", ["Emu", "Albatross", "Penguin"], "An ostrich egg weighs about 1.4 kg."),
  M('ani', 3, "What is a group of owls traditionally called?", "A parliament", ["A murder", "A pride", "A school"], "The name comes from owls' reputation for wisdom."),
  M('ani', 1, "Which animal has black and white fur and lives in the mountains of central China?", "Giant panda", ["Red panda", "Sun bear", "Tapir"], "Wild giant pandas live in bamboo forests in China."),
  M('ani', 2, "Which insect is famous for its 'waggle dance'?", "Honeybee", ["Ant", "Wasp", "Butterfly"], "The dance tells other bees where to find food."),
  M('ani', 3, "How many legs does a lobster have?", "10", ["8", "6", "12"], "Lobsters are decapods, which means 'ten legs'."),

  M('nat', 1, "What is the process by which plants make food from sunlight?", "Photosynthesis", ["Respiration", "Germination", "Pollination"], "Photosynthesis turns light, water and carbon dioxide into sugar."),
  M('nat', 2, "What green pigment helps plants capture sunlight?", "Chlorophyll", ["Melanin", "Carotene", "Haemoglobin"], "Chlorophyll reflects green light, which is why leaves look green."),
  M('nat', 3, "What is the tallest species of tree?", "Coast redwood", ["Giant sequoia", "Douglas fir", "Mountain ash"], "The tallest known redwood is about 116 m tall."),
  M('nat', 3, "Which plant has the largest single flower in the world?", "Rafflesia arnoldii", ["Lotus", "Giant water lily", "Magnolia"], "Its flower can be about 1 m across and smells of rotting meat."),
  T('nat', 2, "Mushrooms and other fungi are plants.", false, "Fungi are a separate kingdom, more closely related to animals than plants."),
  T('nat', 1, "The Venus flytrap catches and digests insects.", true, "Its leaves snap shut when trigger hairs are touched."),
  T('nat', 2, "Bamboo is a type of tree.", false, "Bamboo is a giant grass; some kinds can grow almost a metre in a day."),
  M('nat', 3, "What type of cloud usually brings thunderstorms?", "Cumulonimbus", ["Cirrus", "Stratus", "Altocumulus"], "Cumulonimbus clouds can tower over 10 km high."),
  M('nat', 2, "What does an anemometer measure?", "Wind speed", ["Rainfall", "Air pressure", "Humidity"], "Many anemometers use spinning cups."),
  T('nat', 2, "Lightning is hotter than the surface of the Sun.", true, "A lightning bolt can reach about 30,000 °C, around five times hotter than the Sun's surface."),
  M('nat', 2, "What are hurricanes called in the north-west Pacific Ocean?", "Typhoons", ["Tornadoes", "Monsoons", "Blizzards"], "In the Indian Ocean they are called cyclones."),
  T('nat', 1, "You can tell a tree's age by counting the rings in its trunk.", true, "Most trees in places with seasons add one ring each year."),
  M('nat', 2, "Trees that lose all their leaves each year are called…", "Deciduous", ["Evergreen", "Coniferous", "Perennial"], "Oaks and maples are deciduous."),
  M('nat', 1, "Which part of a plant takes in water from the soil?", "Roots", ["Leaves", "Flowers", "Stem"], "Roots also anchor the plant in the ground."),
  M('nat', 1, "What is the name for an animal that is active mainly at night?", "Nocturnal", ["Diurnal", "Crepuscular", "Dormant"], "Owls and bats are nocturnal."),
  M('nat', 3, "What is the name for animals that are active mainly at dawn and dusk?", "Crepuscular", ["Nocturnal", "Diurnal", "Arboreal"], "Rabbits and deer are often crepuscular."),
  M('nat', 1, "What is the hard outer layer on a tree trunk called?", "Bark", ["Sap", "Pith", "Resin"], "Bark protects the tree."),
  M('nat', 3, "What is the name for a scientist who studies fungi?", "Mycologist", ["Botanist", "Entomologist", "Ornithologist"], "An entomologist studies insects; an ornithologist studies birds."),
  M('nat', 3, "What is a scientist who studies insects called?", "Entomologist", ["Ornithologist", "Herpetologist", "Ichthyologist"], "Herpetologists study reptiles; ichthyologists study fish."),
  M('nat', 1, "Which gas do plants give off during photosynthesis?", "Oxygen", ["Carbon dioxide", "Nitrogen", "Methane"], "Almost all the oxygen in the air comes from photosynthesis."),

  // pop culture (timeless)
  M('pop', 1, "Who created Mickey Mouse?", "Walt Disney", ["Chuck Jones", "Jim Henson", "Stan Lee"], "Disney created him with animator Ub Iwerks."),
  M('pop', 3, "Mickey Mouse first appeared in theatres in which 1928 cartoon with synchronised sound?", "Steamboat Willie", ["Fantasia", "The Band Concert", "Flowers and Trees"], "It premiered in New York in November 1928."),
  M('pop', 1, "What was Disney's first full-length animated feature film, released in 1937?", "Snow White and the Seven Dwarfs", ["Pinocchio", "Cinderella", "Bambi"], "Pinocchio and Bambi followed in the 1940s."),
  M('pop', 1, "What is the name of Superman's home planet?", "Krypton", ["Vulcan", "Tatooine", "Gallifrey"], "Superman was sent to Earth as a baby before Krypton exploded."),
  M('pop', 1, "In which city does Batman fight crime?", "Gotham City", ["Metropolis", "Star City", "Central City"], "Metropolis is Superman's city."),
  M('pop', 1, "What is Spider-Man's real name?", "Peter Parker", ["Bruce Wayne", "Clark Kent", "Tony Stark"], "Peter Parker first appeared in 1962."),
  M('pop', 3, "What is the name of Wonder Woman's home island?", "Themyscira", ["Atlantis", "Asgard", "Krypton"], "It is home to the Amazons."),
  M('pop', 1, "Who wrote the Harry Potter books?", "J. K. Rowling", ["Roald Dahl", "Philip Pullman", "Rick Riordan"], "The first book was published in 1997."),
  M('pop', 1, "Which Hogwarts house is Harry Potter sorted into?", "Gryffindor", ["Slytherin", "Ravenclaw", "Hufflepuff"], "Gryffindor's emblem is a lion."),
  M('pop', 1, "In 'Star Wars', who is Darth Vader's son?", "Luke Skywalker", ["Han Solo", "Obi-Wan Kenobi", "Lando Calrissian"], "Vader reveals the truth in The Empire Strikes Back (1980)."),
  M('pop', 2, "In 'The Lord of the Rings', who forged the One Ring?", "Sauron", ["Saruman", "Gandalf", "Gollum"], "Sauron forged it in the fires of Mount Doom."),
  M('pop', 2, "What is Sherlock Holmes's famous address?", "221B Baker Street", ["10 Downing Street", "12 Grimmauld Place", "4 Privet Drive"], "Holmes shared the rooms with Dr Watson."),
  M('pop', 1, "What is James Bond's code number?", "007", ["001", "009", "070"], "The '00' means he has a licence to kill."),
  M('pop', 2, "Who created James Bond?", "Ian Fleming", ["John le Carré", "Graham Greene", "Arthur Conan Doyle"], "The first Bond novel, Casino Royale, came out in 1953."),
  M('pop', 2, "What is the name of Tintin's dog?", "Snowy", ["Pluto", "Snoopy", "Scooby"], "In the original French he is called Milou."),
  M('pop', 2, "Asterix belongs to which ancient people?", "Gauls", ["Romans", "Britons", "Vikings"], "Asterix's village holds out against the Romans."),
  M('pop', 1, "What is the name of Mario's brother in Nintendo games?", "Luigi", ["Wario", "Toad", "Yoshi"], "Luigi is the taller brother in green."),
  M('pop', 1, "What job is Nintendo's Mario best known for?", "Plumber", ["Chef", "Postman", "Firefighter"], "Mario and Luigi are the Super Mario Bros., plumbers from Brooklyn."),
  N('pop', 2, "How many ghosts chase Pac-Man in the original arcade game?", 4, "ghosts", 0, "Blinky, Pinky, Inky and Clyde."),
  M('pop', 3, "In which country was Tetris created?", "Soviet Union", ["Japan", "United States", "Hungary"], "Alexey Pajitnov created it in Moscow in 1984."),
  M('pop', 1, "What type of Pokémon is Pikachu?", "Electric", ["Fire", "Water", "Grass"], "Pikachu stores electricity in its red cheeks."),
  M('pop', 3, "Minecraft was first created by a developer from which country?", "Sweden", ["Finland", "Denmark", "Norway"], "Markus 'Notch' Persson released the first version in 2009."),
  M('pop', 1, "What colour is Sega's Sonic the Hedgehog?", "Blue", ["Green", "Red", "Yellow"], "Sonic first appeared in 1991."),
  M('pop', 3, "The Rubik's Cube was invented by a professor from which country?", "Hungary", ["Russia", "Japan", "Austria"], "Ernő Rubik invented it in 1974."),
  N('pop', 1, "How many pieces does each player start with in chess?", 16, "pieces", 0, "8 pawns, 2 rooks, 2 knights, 2 bishops, a queen and a king."),
  M('pop', 1, "Which chess piece can jump over other pieces?", "Knight", ["Bishop", "Rook", "Queen"], "The knight moves in an L shape."),
  N('pop', 1, "How many squares are on a chessboard?", 64, "squares", 0, "An 8 × 8 grid."),
  M('pop', 1, "In which town do The Simpsons live?", "Springfield", ["Quahog", "South Park", "Bedrock"], "The show began in 1989."),
  M('pop', 1, "What is the name of the Muppets' famous frog?", "Kermit", ["Gonzo", "Fozzie", "Animal"], "Kermit was created by Jim Henson in 1955."),
  M('pop', 1, "In 'The Wonderful Wizard of Oz', what is the name of Dorothy's dog?", "Toto", ["Rex", "Spot", "Scruffy"], "L. Frank Baum's book was published in 1900."),
  M('pop', 2, "What is the name of the Doctor's time machine in 'Doctor Who'?", "TARDIS", ["DeLorean", "Enterprise", "Millennium Falcon"], "It looks like a 1960s police box."),
  M('pop', 2, "Who was captain of the starship Enterprise in the original 'Star Trek' series?", "James T. Kirk", ["Jean-Luc Picard", "Han Solo", "Kathryn Janeway"], "The original series began in 1966."),
  N('pop', 1, "How many cards are in a standard deck, not counting jokers?", 52, "cards", 0, "Four suits of 13 cards."),
  T('pop', 2, "On a standard die, opposite faces always add up to seven.", true, "1 is opposite 6, 2 opposite 5, and 3 opposite 4."),
  M('pop', 1, "In the 1933 film, which New York building does King Kong climb?", "Empire State Building", ["Chrysler Building", "Statue of Liberty", "Brooklyn Bridge"], "The Empire State Building had opened in 1931."),
  M('pop', 2, "Who directed the 1997 film 'Titanic'?", "James Cameron", ["Steven Spielberg", "Ridley Scott", "Peter Jackson"], "It won 11 Academy Awards."),
  M('pop', 2, "Who directed the 1960 thriller 'Psycho'?", "Alfred Hitchcock", ["Stanley Kubrick", "Orson Welles", "Billy Wilder"], "Hitchcock was known as the 'Master of Suspense'."),
  M('pop', 1, "In 'Wallace & Gromit', what kind of animal is Gromit?", "Dog", ["Cat", "Rabbit", "Sheep"], "Gromit never speaks but says a lot with his eyebrows."),
  M('pop', 2, "In which country was the LEGO toy company founded?", "Denmark", ["Sweden", "Germany", "Netherlands"], "LEGO comes from the Danish 'leg godt', meaning 'play well'."),
  M('pop', 1, "What colour is the Hulk?", "Green", ["Grey", "Red", "Blue"], "The Hulk first appeared grey in 1962 before becoming green."),

  // food
  M('food', 1, "Which country does paella come from?", "Spain", ["Italy", "Mexico", "Portugal"], "Paella comes from Valencia."),
  M('food', 1, "What is the main ingredient of guacamole?", "Avocado", ["Tomato", "Lime", "Pepper"], "Guacamole comes from Mexico."),
  M('food', 1, "Which herb is the main ingredient of traditional pesto?", "Basil", ["Parsley", "Coriander", "Mint"], "Pesto alla genovese comes from Genoa, Italy."),
  M('food', 3, "The spice saffron comes from which plant?", "Crocus", ["Tulip", "Poppy", "Marigold"], "Saffron threads are the dried stigmas of the crocus flower."),
  T('food', 1, "Botanically, a tomato is a fruit.", true, "A fruit grows from a flower and contains seeds."),
  T('food', 2, "Peanuts are a kind of tree nut.", false, "Peanuts are legumes that grow underground in pods, like peas and beans."),
  T('nat', 1, "Lightning never strikes the same place twice.", false, "Tall buildings like the Empire State Building are struck many times every year."),
  T('ani', 2, "The colour red makes bulls angry.", false, "Bulls can't see red well; they react to the movement of the cape."),
  T('ani', 1, "Ostriches bury their heads in the sand when frightened.", false, "They lower their heads to tend eggs or hide, but they don't bury them."),
  T('his', 2, "Napoleon Bonaparte was unusually short for his time.", false, "He was about 1.69 m, roughly average for a Frenchman of his era."),
  T('his', 2, "Viking warriors wore horned helmets into battle.", false, "No horned Viking battle helmet has ever been found; the idea came from 19th-century costume designs."),
  T('sci', 2, "Albert Einstein failed maths at school.", false, "Einstein excelled at maths and had mastered calculus by about 15."),
  T('sci', 3, "Old window glass is thicker at the bottom because glass slowly flows.", false, "Glass is an amorphous solid; uneven old panes come from how they were made."),
];
