import { M, T } from './lib.mjs';

// Kids bank: ages 6–10, short read-aloud prompts, 3 options max. img = English Wikipedia article whose lead image we use.
export default [
  // animals
  M('ani', 1, "Which animal says 'moo'?", "Cow", ["Sheep", "Duck"], "Cows say moo, and they give us milk!"),
  M('ani', 1, "What do bees make?", "Honey", ["Milk", "Jam"], "Bees make honey from the nectar in flowers."),
  M('ani', 1, "How many legs does a spider have?", "8", ["6", "4"], "Spiders have eight legs. Insects have six."),
  M('ani', 1, "How many legs does an insect have?", "6", ["8", "4"], "All insects have six legs, like ants and beetles."),
  M('ani', 1, "Which animal has a long trunk?", "Elephant", ["Giraffe", "Hippo"], "Elephants use their trunks to smell, drink and pick things up."),
  M('ani', 1, "Which is the tallest animal in the world?", "Giraffe", ["Elephant", "Horse"], "A giraffe can be taller than a double-decker bus!"),
  M('ani', 1, "What is the biggest animal that has ever lived?", "Blue whale", ["Elephant", "Polar bear"], "Blue whales are even bigger than the biggest dinosaurs were."),
  M('ani', 1, "What is a baby frog called?", "Tadpole", ["Kitten", "Cub"], "Tadpoles live in water and slowly grow legs."),
  M('ani', 1, "What is a baby dog called?", "Puppy", ["Calf", "Chick"], "Puppies love to play and nap."),
  M('ani', 1, "What is a baby cat called?", "Kitten", ["Puppy", "Foal"], "Kittens are born with their eyes closed."),
  M('ani', 1, "What is a baby cow called?", "Calf", ["Foal", "Lamb"], "A baby cow is a calf. Baby elephants are calves too!"),
  M('ani', 1, "What is a baby horse called?", "Foal", ["Lamb", "Joey"], "A foal can stand up soon after it is born."),
  M('ani', 1, "What is a baby sheep called?", "Lamb", ["Kid", "Piglet"], "Lambs are born in spring on many farms."),
  M('ani', 1, "What is a baby kangaroo called?", "Joey", ["Cub", "Pup"], "A joey grows up safe and snug in its mum's pouch."),
  M('ani', 1, "Which of these animals can fly?", "Eagle", ["Penguin", "Dog"], "Eagles soar high on their big strong wings."),
  M('ani', 1, "Which of these birds cannot fly?", "Penguin", ["Robin", "Parrot"], "Penguins can't fly, but they are super swimmers."),
  M('ani', 1, "Where do most wild penguins live?", "In the southern half of the world", ["In the Arctic", "In the jungle"], "Most penguins live around Antarctica and the southern oceans."),
  M('ani', 1, "Where do wild polar bears live?", "The Arctic", ["Antarctica", "Africa"], "Polar bears live near the North Pole, on the sea ice."),
  M('ani', 1, "What does a caterpillar turn into?", "A butterfly or moth", ["A bee", "A spider"], "A caterpillar makes a chrysalis or cocoon and changes inside it."),
  M('ani', 1, "What do most fish use to breathe under water?", "Gills", ["Feathers", "Their tails"], "Gills take oxygen out of the water."),
  M('ani', 1, "Which animal has black and white stripes?", "Zebra", ["Tiger", "Lion"], "Every zebra has its own stripe pattern, like a fingerprint."),
  M('ani', 1, "Which animal sleeps hanging upside down?", "Bat", ["Owl", "Rabbit"], "Bats hang by their feet to sleep."),
  M('ani', 1, "Which of these animals carries a shell on its back?", "Tortoise", ["Rabbit", "Frog"], "A tortoise can pull its head inside its shell to stay safe."),
  M('ani', 2, "Which is the biggest kind of cat?", "Tiger", ["Lion", "Cheetah"], "Tigers are the biggest cats, just bigger than lions."),
  M('ani', 1, "Which is the fastest animal on land?", "Cheetah", ["Horse", "Lion"], "A cheetah can run as fast as a car on a busy road!"),
  M('ani', 2, "Which of these animals is a mammal?", "Dolphin", ["Shark", "Octopus"], "Dolphins breathe air and feed their babies milk."),
  M('ani', 1, "Which of these animals lays eggs?", "Chicken", ["Cow", "Dog"], "Hens lay eggs, sometimes almost one a day."),
  M('ani', 2, "How many humps does a dromedary camel have?", "1", ["2", "3"], "Dromedaries have one hump. Bactrian camels have two."),
  M('ani', 1, "What colour are flamingos?", "Pink", ["Blue", "Green"], "Flamingos are pink because of the food they eat."),
  T('ani', 2, "Flamingos get their pink colour from the food they eat.", true, "Tiny shrimps and plants in their food turn them pink."),
  T('ani', 1, "Most owls hunt at night.", true, "Big eyes and super hearing help owls find food in the dark."),
  M('ani', 1, "Which animal can change its colour?", "Chameleon", ["Rabbit", "Horse"], "Chameleons change colour to show their mood and stay warm or cool."),
  M('ani', 1, "What do giant pandas mostly eat?", "Bamboo", ["Fish", "Carrots"], "Pandas munch bamboo for about half of every day!"),
  M('ani', 1, "What does a spider spin?", "A web", ["A nest", "A shell"], "Spiders spin silky webs to catch their food."),
  M('ani', 2, "Which of these animals is an amphibian?", "Frog", ["Snake", "Lizard"], "Amphibians, like frogs, start life in water and later live on land too."),
  T('ani', 1, "Snakes have no legs.", true, "Snakes slither along using their strong muscles."),
  T('ani', 1, "A whale is a fish.", false, "Whales are mammals. They breathe air through a blowhole."),
  M('ani', 1, "How many arms does an octopus have?", "8", ["6", "10"], "Octo means eight. An octopus has eight arms."),
  M('ani', 2, "How many arms does a starfish usually have?", "5", ["3", "8"], "Most starfish have five arms. Some have even more!"),
  M('ani', 1, "Which animal builds dams in rivers?", "Beaver", ["Otter", "Duck"], "Beavers chew down trees with their strong front teeth."),
  M('ani', 1, "What is a hedgehog covered in?", "Spines", ["Feathers", "Scales"], "Hedgehogs roll into a prickly ball when they feel scared."),
  M('ani', 1, "What are birds covered in?", "Feathers", ["Fur", "Scales"], "Feathers keep birds warm and help them fly."),
  M('ani', 1, "Which animal hops and carries its baby in a pouch?", "Kangaroo", ["Rabbit", "Frog"], "Kangaroos live in Australia and can hop very fast."),
  M('ani', 1, "Which of these animals sleeps through the winter?", "Bear", ["Giraffe", "Lion"], "Many bears sleep in a den through the cold winter."),
  M('ani', 1, "Which big cat has a shaggy mane?", "Lion", ["Tiger", "Leopard"], "Male lions have big manes around their heads."),
  M('ani', 1, "Which animal says 'quack'?", "Duck", ["Hen", "Goose"], "Ducks quack. Geese honk!"),
  M('ani', 1, "Which animal says 'baa'?", "Sheep", ["Goat", "Horse"], "Sheep say baa, and their wool keeps us warm."),
  M('ani', 1, "What does a cow eat most of?", "Grass", ["Meat", "Fish"], "Cows chew grass all day long."),
  M('ani', 2, "What is a group of lions called?", "A pride", ["A pack", "A herd"], "A pride is a lion family that lives together."),
  M('ani', 2, "What do you call an animal that eats only plants?", "A herbivore", ["A carnivore", "A dinosaur"], "Rabbits, cows and elephants are herbivores."),
  M('ani', 1, "Which bird has a huge, colourful fan of tail feathers?", "Peacock", ["Crow", "Pigeon"], "Male peafowl, called peacocks, show off their tails."),
  M('ani', 1, "Which animal makes a 'hoot' sound?", "Owl", ["Dog", "Frog"], "Many owls hoot to talk to each other at night."),
  M('ani', 2, "What do bats use to find food in the dark?", "Echoes", ["Torches", "Smell only"], "Many bats make squeaks and listen for the echoes."),
  M('ani', 2, "Where does a baby kangaroo grow up?", "In its mum's pouch", ["In a nest", "In an egg"], "The joey stays in the pouch for months."),
  M('ani', 1, "What animal is this?", "Giraffe", ["Zebra", "Camel"], "Giraffes have long necks to reach leaves high in trees.", { img: 'Masai giraffe' }),
  M('ani', 1, "What animal is this?", "Zebra", ["Horse", "Donkey"], "Zebras live in Africa and run in big groups.", { img: 'Plains zebra' }),
  M('ani', 1, "What animal is this?", "Penguin", ["Puffin", "Seagull"], "Penguins waddle on land and zoom through water.", { img: 'Emperor penguin' }),
  M('ani', 1, "What animal is this?", "Koala", ["Panda", "Monkey"], "Koalas live in Australia and love eucalyptus leaves.", { img: 'Koala' }),
  M('ani', 1, "What animal is this?", "Flamingo", ["Swan", "Parrot"], "Flamingos often stand on one leg.", { img: 'American flamingo' }),
  M('ani', 1, "What animal is this?", "Octopus", ["Jellyfish", "Crab"], "An octopus has eight bendy arms.", { img: 'Common octopus' }),
  M('ani', 1, "What animal is this?", "Hedgehog", ["Mouse", "Squirrel"], "Hedgehogs snuffle about at night looking for bugs.", { img: 'European hedgehog' }),
  M('ani', 1, "What animal is this?", "Polar bear", ["Brown bear", "Panda"], "Polar bears have thick white fur to stay warm on the ice.", { img: 'Polar bear' }),
  M('ani', 1, "What animal is this?", "Giant panda", ["Polar bear", "Koala"], "Giant pandas live in the bamboo forests of China.", { img: 'Giant panda' }),
  M('ani', 1, "What animal is this?", "Elephant", ["Rhino", "Hippo"], "Elephants are the biggest animals that live on land.", { img: 'African bush elephant' }),
  M('ani', 1, "What animal is this?", "Kangaroo", ["Rabbit", "Deer"], "Kangaroos use their big tails to balance when they hop.", { img: 'Eastern grey kangaroo' }),
  M('ani', 1, "What animal is this?", "Tiger", ["Lion", "Leopard"], "Tigers have stripes and love to swim.", { img: 'Tiger' }),
  M('ani', 1, "What animal is this?", "Owl", ["Eagle", "Parrot"], "Owls can turn their heads a very long way round.", { img: 'Barn owl' }),
  M('ani', 1, "What animal is this?", "Ladybird", ["Bee", "Ant"], "Ladybirds are little beetles. Gardeners love them!", { img: 'Coccinella septempunctata' }),
  M('ani', 1, "What animal is this?", "Camel", ["Horse", "Llama"], "Camels can walk a long way in the hot desert.", { img: 'Dromedary' }),
  M('ani', 1, "What animal is this?", "Tortoise", ["Crab", "Snail"], "Tortoises live on land and move very slowly.", { img: 'Galápagos tortoise' }),

  // colours
  M('colour', 1, "What colour is a clear sky on a sunny day?", "Blue", ["Green", "Purple"], "Sunlight bounces around in the air and makes the sky look blue."),
  M('colour', 1, "What colour is grass?", "Green", ["Red", "Blue"], "Grass is green because of chlorophyll, which helps it use sunlight."),
  M('colour', 1, "What colour is a ripe banana?", "Yellow", ["Purple", "Blue"], "Bananas start green and turn yellow as they ripen."),
  M('colour', 1, "What colour do you get if you mix blue and yellow paint?", "Green", ["Orange", "Purple"], "Blue and yellow make green."),
  M('colour', 1, "What colour do you get if you mix red and yellow paint?", "Orange", ["Green", "Brown"], "Red and yellow make orange, like a sunset."),
  M('colour', 1, "What colour do you get if you mix red and blue paint?", "Purple", ["Green", "Orange"], "Red and blue make purple."),
  M('colour', 1, "What colour do you get if you mix red and white paint?", "Pink", ["Orange", "Grey"], "Adding white to red makes pink."),
  M('colour', 1, "What colour do you get if you mix black and white paint?", "Grey", ["Brown", "Pink"], "Black and white make grey."),
  M('colour', 1, "How many colours are in a rainbow?", "7", ["5", "10"], "Red, orange, yellow, green, blue, indigo and violet."),
  M('colour', 1, "Which colour is on the outside edge of a rainbow?", "Red", ["Blue", "Green"], "Red is on the outside and violet is on the inside."),
  M('colour', 1, "What colour is snow?", "White", ["Blue", "Yellow"], "Fresh snow looks white because it bounces back all colours of light."),
  M('colour', 1, "What colour is a ripe strawberry?", "Red", ["Blue", "Orange"], "Strawberries even have their seeds on the outside!"),
  M('colour', 1, "What colour are most carrots?", "Orange", ["Blue", "Pink"], "Most carrots are orange, but some are purple, yellow or white."),
  M('colour', 2, "Which of these is a primary colour in painting?", "Blue", ["Green", "Purple"], "Red, yellow and blue are the painters' primary colours."),
  M('colour', 1, "What colour is a fire engine in many countries?", "Red", ["Green", "Purple"], "Bright red helps people see fire engines coming."),
  M('colour', 1, "What colour do traffic lights show to say 'stop'?", "Red", ["Green", "Blue"], "Red means stop, green means go."),

  // shapes
  M('shape', 1, "How many sides does a triangle have?", "3", ["4", "5"], "Tri means three. A triangle has three sides."),
  M('shape', 1, "How many sides does a square have?", "4", ["3", "6"], "A square has four sides, all the same length."),
  M('shape', 1, "How many corners does a circle have?", "0", ["1", "4"], "A circle is perfectly round, with no corners at all."),
  M('shape', 1, "How many sides does a pentagon have?", "5", ["6", "4"], "Penta means five."),
  M('shape', 2, "Honeycomb cells are made of which shape?", "Hexagon", ["Square", "Circle"], "Bees build six-sided hexagons that fit together with no gaps."),
  M('shape', 1, "What shape is a ball?", "Sphere", ["Cube", "Cone"], "A sphere is round all over, like a ball or a bubble."),
  M('shape', 1, "What shape is a dice?", "Cube", ["Sphere", "Pyramid"], "A dice is a cube with six square faces."),
  M('shape', 1, "What shape is a pointy party hat?", "Cone", ["Cube", "Cylinder"], "A cone has a round end and a pointy end."),
  M('shape', 1, "What shape is an egg?", "Oval", ["Square", "Triangle"], "Eggs are oval: like a stretched circle."),
  M('shape', 1, "How many corners does a rectangle have?", "4", ["3", "5"], "A rectangle has four corners and four sides."),
  M('shape', 1, "What shape is a tin of beans?", "Cylinder", ["Cube", "Pyramid"], "A cylinder has two round ends and a curved side."),
  M('shape', 2, "What shape are the famous ancient tombs in Egypt?", "Pyramid", ["Sphere", "Cylinder"], "The pyramids of Giza are over 4,000 years old."),
  M('shape', 1, "How many sides do two triangles have altogether?", "6", ["5", "8"], "3 + 3 = 6."),
  M('shape', 1, "Which shape has three corners?", "Triangle", ["Square", "Circle"], "Triangles have three sides and three corners."),

  // space
  M('space', 1, "Which planet do we live on?", "Earth", ["Mars", "Jupiter"], "Earth is the only planet we know of with living things."),
  T('space', 1, "The Sun is a star.", true, "The Sun is our very own star. It just looks big because it is close."),
  T('space', 1, "The Moon goes around the Earth.", true, "The Moon takes about a month to go round the Earth."),
  M('space', 1, "Which planet is called the Red Planet?", "Mars", ["Venus", "Neptune"], "Mars looks red because of rusty dust on its ground."),
  M('space', 1, "Which planet has big, bright rings?", "Saturn", ["Mars", "Mercury"], "Saturn's rings are made of ice and rock."),
  M('space', 1, "Which is the biggest planet?", "Jupiter", ["Earth", "Mars"], "More than a thousand Earths could fit inside Jupiter!"),
  M('space', 1, "How many planets go around our Sun?", "8", ["5", "12"], "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune."),
  M('space', 2, "Who was the first person to walk on the Moon?", "Neil Armstrong", ["Yuri Gagarin", "Buzz Lightyear"], "Neil Armstrong stepped onto the Moon in 1969."),
  T('space', 2, "The Moon makes its own light.", false, "Moonlight is really sunlight bouncing off the Moon."),
  T('space', 1, "The stars are still in the sky during the day.", true, "The Sun is so bright that we just can't see the other stars."),
  M('space', 1, "In which direction does the Sun rise?", "East", ["West", "North"], "The Sun rises in the east and sets in the west."),
  M('space', 2, "What makes day and night?", "The Earth spinning", ["The Sun switching off", "Clouds covering the Sun"], "When your side of the Earth faces the Sun, it is daytime."),
  M('space', 1, "How long does the Earth take to go round the Sun?", "One year", ["One day", "One week"], "One trip around the Sun takes one year."),
  M('space', 1, "What do astronauts travel into space in?", "A rocket", ["A submarine", "A hot-air balloon"], "Rockets blast off with huge engines."),
  M('space', 1, "What is this planet?", "Saturn", ["Earth", "Mars"], "You can spot Saturn by its beautiful rings.", { img: 'Saturn' }),
  M('space', 1, "What is this?", "The Moon", ["The Sun", "A planet with rings"], "The Moon's grey patches are huge, flat plains of old lava.", { img: 'Moon' }),
  M('space', 2, "What do we call a person who travels into space?", "An astronaut", ["A pilot fish", "A lifeguard"], "Astronauts train for years before they go to space."),

  // body
  M('body', 1, "How many fingers are on one hand, counting the thumb?", "5", ["4", "6"], "Four fingers and a thumb make five."),
  M('body', 1, "How many senses do we usually say people have?", "5", ["3", "10"], "Sight, hearing, smell, taste and touch."),
  M('body', 1, "Which body part do you use to see?", "Eyes", ["Ears", "Nose"], "Your eyes let light in so you can see."),
  M('body', 1, "Which body part do you use to hear?", "Ears", ["Eyes", "Elbows"], "Your ears catch sounds all around you."),
  M('body', 1, "Which body part do you use to smell?", "Nose", ["Ears", "Knees"], "Your nose can tell apart thousands of smells."),
  M('body', 1, "What pumps blood around your body?", "Heart", ["Stomach", "Lungs"], "Your heart beats about 100,000 times a day."),
  M('body', 1, "Which body parts help you breathe?", "Lungs", ["Bones", "Ears"], "Your lungs fill with air every time you breathe in."),
  M('body', 1, "What do we call all the bones in your body together?", "Skeleton", ["Muscle", "Skin"], "Your skeleton holds you up and protects your insides."),
  T('body', 1, "Your heart is about the size of your fist.", true, "Make a fist: your heart is about that big."),
  T('body', 1, "Children's baby teeth fall out and new teeth grow.", true, "Bigger adult teeth push the baby teeth out."),
  M('body', 1, "Which body part do you use to taste?", "Tongue", ["Nose", "Fingers"], "Your tongue is covered in tiny taste buds."),
  M('body', 1, "How many toes do most people have?", "10", ["8", "12"], "Five on each foot."),
  M('body', 1, "Which organ do you think with?", "Brain", ["Heart", "Stomach"], "Your brain controls everything you do."),
  M('body', 1, "What helps you move your bones?", "Muscles", ["Hair", "Nails"], "Muscles pull on your bones to move them."),
  M('body', 1, "What colour is blood?", "Red", ["Blue", "Green"], "Blood is always red, even inside your veins."),
  M('body', 2, "Where in your body is your kneecap?", "In your leg", ["In your arm", "In your head"], "Your kneecap protects the front of your knee."),
  M('body', 1, "Why should you brush your teeth?", "To keep them clean and healthy", ["To make them grow faster", "To change their colour"], "Brushing twice a day keeps germs away."),
  M('body', 1, "What covers the outside of your body?", "Skin", ["Feathers", "Scales"], "Skin keeps germs out and keeps you warm."),

  // countries and continents
  M('world', 1, "On which continent is Egypt?", "Africa", ["Asia", "Europe"], "Egypt is in the north-east corner of Africa."),
  M('world', 1, "Which country do kangaroos come from?", "Australia", ["Canada", "India"], "Wild kangaroos live only in Australia and nearby New Guinea."),
  M('world', 1, "In which country is the Eiffel Tower?", "France", ["Italy", "Spain"], "The Eiffel Tower is in Paris, the capital of France.", { img: 'Eiffel Tower' }),
  M('world', 1, "In which country are these famous pyramids?", "Egypt", ["Mexico", "China"], "The pyramids of Giza are over 4,000 years old.", { img: 'Giza pyramid complex' }),
  M('world', 1, "How many continents are there?", "7", ["5", "10"], "Africa, Antarctica, Asia, Australia, Europe, North America and South America."),
  M('world', 1, "Which is the coldest continent?", "Antarctica", ["Africa", "Europe"], "Antarctica is covered in thick ice all year."),
  M('world', 1, "Which country is shaped like a boot?", "Italy", ["Spain", "Japan"], "On a map, Italy looks like a boot kicking a ball!"),
  M('world', 1, "In which country is the Great Wall?", "China", ["India", "Brazil"], "The Great Wall of China is thousands of kilometres long.", { img: 'Great Wall of China' }),
  M('world', 1, "In which country is the Statue of Liberty?", "United States", ["France", "England"], "The statue stands in New York Harbor.", { img: 'Statue of Liberty' }),
  M('world', 1, "Which country has a red maple leaf on its flag?", "Canada", ["Japan", "Brazil"], "Maple trees grow all over Canada."),
  M('world', 1, "Which is the biggest ocean?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean"], "The Pacific is bigger than all the land on Earth put together."),
  M('world', 1, "On which continent is the Sahara Desert?", "Africa", ["Australia", "South America"], "The Sahara is a huge, hot, sandy desert."),
  M('world', 1, "What is the tallest mountain in the world?", "Mount Everest", ["Mount Fuji", "Ben Nevis"], "Everest is in Asia, on the border of Nepal and China."),
  M('world', 1, "On which continent is the Amazon rainforest?", "South America", ["Africa", "Europe"], "The Amazon is home to millions of kinds of plants and animals."),
  T('world', 1, "Japan is made up of islands.", true, "Japan has thousands of islands, with four big main ones."),
  M('world', 1, "Which country does sushi come from?", "Japan", ["Mexico", "Italy"], "Sushi is rice with fish or vegetables."),
  M('world', 1, "Which country did pizza first come from?", "Italy", ["France", "Mexico"], "Pizza as we know it began in Naples, Italy."),
  M('world', 1, "On which continent is India?", "Asia", ["Africa", "Europe"], "India is in South Asia."),
  M('world', 1, "On which continent is Brazil?", "South America", ["Africa", "Asia"], "Brazil is the biggest country in South America."),
  M('world', 1, "On which continent is the United Kingdom?", "Europe", ["Asia", "North America"], "The UK is a group of islands in north-west Europe."),
  M('world', 1, "On which continent is Mexico?", "North America", ["South America", "Africa"], "Mexico is just south of the United States."),
  M('world', 1, "In which city is the clock tower that holds Big Ben?", "London", ["Paris", "New York"], "Big Ben is really the name of the giant bell inside."),

  // weather
  M('weather', 1, "What falls from the clouds when it is very cold?", "Snow", ["Sand", "Leaves"], "Snow is made of tiny ice crystals."),
  M('weather', 1, "What do you often see when the sun shines during rain?", "A rainbow", ["A snowman", "A tornado"], "Sunlight shining through raindrops makes a rainbow.", { img: 'Rainbow' }),
  M('weather', 1, "Which comes first in a storm, the flash or the bang?", "The lightning flash", ["The thunder bang", "They are always together"], "Light travels faster than sound, so you see the flash first."),
  T('weather', 2, "Sound travels faster than light.", false, "Light is much faster. That's why you see lightning before you hear thunder."),
  M('weather', 1, "What is a tornado?", "A spinning column of wind", ["A kind of rain", "A big wave"], "Tornadoes spin very fast. Stay indoors if one is near!"),
  M('weather', 1, "Which season comes after winter?", "Spring", ["Summer", "Autumn"], "In spring, flowers bloom and baby animals are born."),
  M('weather', 1, "In which season do many trees drop their leaves?", "Autumn", ["Spring", "Summer"], "Leaves turn red, orange and yellow in autumn, also called fall."),
  M('weather', 1, "How many seasons are there in a year in many places?", "4", ["2", "6"], "Spring, summer, autumn and winter."),
  M('weather', 1, "What do we use to measure how hot or cold it is?", "A thermometer", ["A ruler", "A clock"], "A thermometer tells us the temperature."),
  M('weather', 1, "What are rain drops made of?", "Water", ["Milk", "Glass"], "Rain is water falling from the clouds."),
  T('weather', 1, "Clouds are made of tiny drops of water or ice.", true, "Billions of tiny drops float together to make a cloud."),
  T('weather', 2, "Fog is a cloud that is close to the ground.", true, "Walking in fog is like walking through a cloud."),
  M('weather', 1, "What is hail?", "Balls of ice", ["Hot rain", "Falling leaves"], "Hailstones are lumps of ice that fall from storm clouds."),
  M('weather', 1, "Which is usually the coldest season?", "Winter", ["Summer", "Spring"], "Winter brings cold days and long nights."),
  T('weather', 2, "Snowflakes usually have six sides or six points.", true, "Water freezes into six-sided patterns."),
  M('weather', 1, "What do you call the stripes of light you see in a storm?", "Lightning", ["Sunshine", "Moonbeams"], "Lightning is a giant spark of electricity.", { img: 'Lightning' }),
  M('weather', 1, "What do you need on a rainy day to stay dry?", "An umbrella", ["Sunglasses", "A sun hat"], "An umbrella keeps the rain off your head."),
  M('weather', 2, "What is a very strong storm with heavy rain and very fast winds over warm seas called?", "A hurricane", ["A drizzle", "A breeze"], "Hurricanes form over warm oceans."),
  M('weather', 1, "What happens to a snowman when the warm Sun comes out?", "It melts", ["It grows bigger", "It turns blue"], "Warm sunshine melts snow into water."),

  // fairy tales (public domain)
  M('tale', 1, "Who lost a glass slipper at the ball?", "Cinderella", ["Snow White", "Rapunzel"], "The prince used the slipper to find Cinderella."),
  M('tale', 1, "Who was Little Red Riding Hood going to visit?", "Her grandmother", ["Her teacher", "The king"], "She carried a basket of food through the woods."),
  M('tale', 1, "In 'The Three Little Pigs', which house did the wolf NOT blow down?", "The brick house", ["The straw house", "The stick house"], "The brick house was strong, so the third pig was safe."),
  M('tale', 1, "How many bears does Goldilocks meet?", "3", ["2", "7"], "Daddy Bear, Mummy Bear and Baby Bear."),
  M('tale', 1, "Whose porridge was 'just right' for Goldilocks?", "Baby Bear's", ["Daddy Bear's", "Mummy Bear's"], "Baby Bear's porridge was not too hot and not too cold."),
  M('tale', 1, "What did Jack climb to reach the giant's castle?", "A beanstalk", ["A ladder", "A rainbow"], "Jack's magic beans grew into a giant beanstalk."),
  M('tale', 1, "How many dwarfs did Snow White live with?", "7", ["3", "12"], "Snow White lived with seven dwarfs in a cottage in the woods."),
  M('tale', 1, "Which princess had very, very long hair?", "Rapunzel", ["Cinderella", "Sleeping Beauty"], "'Rapunzel, Rapunzel, let down your hair!'"),
  M('tale', 1, "In 'Hansel and Gretel', what was the witch's house made of?", "Sweets and gingerbread", ["Ice", "Straw"], "The children nibbled the yummy house."),
  M('tale', 1, "What happened to Pinocchio's nose when he told a lie?", "It grew longer", ["It turned red", "It fell off"], "Pinocchio is a wooden puppet who wanted to be a real boy."),
  M('tale', 1, "What did the Ugly Duckling grow up to be?", "A swan", ["A goose", "A hen"], "He was never a duckling at all. He was a beautiful swan!"),
  M('tale', 1, "What did Sleeping Beauty prick her finger on?", "A spinning wheel's spindle", ["A rose thorn", "A sewing needle"], "Then she fell asleep for a hundred years."),
  M('tale', 1, "What kind of animal is Puss in Boots?", "A cat", ["A dog", "A fox"], "Puss in Boots is a clever cat who helps his master."),
  M('tale', 1, "Who won the race between the tortoise and the hare?", "The tortoise", ["The hare", "It was a tie"], "Slow and steady wins the race!"),
  M('tale', 1, "In the fable, what did the boy keep crying when there was nothing there?", "Wolf!", ["Fire!", "Help, a bear!"], "When a real wolf came, nobody believed him."),
  M('tale', 1, "Which boy never wanted to grow up?", "Peter Pan", ["Pinocchio", "Jack"], "Peter Pan lives in Neverland."),
  M('tale', 1, "What kind of creature is Tinker Bell?", "A fairy", ["A mermaid", "A witch"], "Tinker Bell is Peter Pan's fairy friend."),
  M('tale', 1, "Which animal does Alice follow down a rabbit hole?", "The White Rabbit", ["The Cheshire Cat", "A black cat"], "The White Rabbit is always late!"),
  M('tale', 1, "In 'The Three Billy Goats Gruff', who lives under the bridge?", "A troll", ["A dragon", "A giant"], "The biggest billy goat sends the troll flying."),
  M('tale', 1, "Where did Humpty Dumpty sit before his great fall?", "On a wall", ["On a chair", "In a tree"], "All the king's horses and men couldn't put him together again."),
  M('tale', 2, "What could Rumpelstiltskin spin straw into?", "Gold", ["Silk", "Candy"], "The miller's daughter had to guess his name."),
  M('tale', 1, "In 'The Princess and the Pea', where was the pea?", "Under lots of mattresses", ["In her soup", "In her shoe"], "Only a real princess could feel such a tiny pea!"),
  M('tale', 1, "What came out of Aladdin's magic lamp?", "A genie", ["A dragon", "A mouse"], "The genie granted wishes."),
  M('tale', 2, "Who caught the Gingerbread Man at the end of the story?", "A fox", ["A cow", "A baker"], "The fox offered him a ride across the river."),

  // counting and maths
  M('count', 1, "What is 2 + 2?", "4", ["3", "5"], "2 + 2 = 4."),
  M('count', 1, "What is 5 + 3?", "8", ["7", "9"], "5 + 3 = 8."),
  M('count', 1, "What is 10 − 4?", "6", ["5", "7"], "10 take away 4 leaves 6."),
  M('count', 2, "What is 3 × 4?", "12", ["7", "10"], "Three groups of four make 12."),
  M('count', 1, "What is half of 10?", "5", ["2", "20"], "Split 10 into two equal halves and you get 5 each."),
  M('count', 1, "What is double 6?", "12", ["8", "10"], "6 + 6 = 12."),
  M('count', 1, "How many days are there in a week?", "7", ["5", "10"], "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday and Sunday."),
  M('count', 1, "How many months are there in a year?", "12", ["10", "7"], "From January to December there are 12 months."),
  M('count', 2, "How many hours are there in a day?", "24", ["12", "60"], "A whole day and night is 24 hours."),
  M('count', 2, "How many minutes are there in an hour?", "60", ["100", "24"], "One hour is 60 minutes."),
  M('count', 1, "How many legs do two dogs have altogether?", "8", ["4", "6"], "Each dog has 4 legs: 4 + 4 = 8."),
  M('count', 1, "Which number comes after 99?", "100", ["98", "1000"], "99 + 1 = 100."),
  M('count', 1, "Which of these numbers is even?", "8", ["3", "7"], "Even numbers can be split into two equal groups."),
  M('count', 1, "How many wheels does a bicycle have?", "2", ["3", "4"], "'Bi' means two."),
  M('count', 1, "How many wheels does a tricycle have?", "3", ["2", "4"], "'Tri' means three."),
  M('count', 1, "What is 10 + 10?", "20", ["15", "100"], "10 + 10 = 20."),
  M('count', 2, "How many is a dozen?", "12", ["10", "20"], "A dozen eggs is 12 eggs."),
  M('count', 1, "Which is the smallest number?", "2", ["12", "20"], "2 is less than 12 and 20."),
  M('count', 1, "What is 9 − 9?", "0", ["9", "1"], "Take away everything and you have zero left."),
  M('count', 2, "What is 7 + 6?", "13", ["12", "14"], "7 + 6 = 13."),
  M('count', 2, "What is 20 − 8?", "12", ["11", "13"], "20 take away 8 is 12."),
  M('count', 2, "What is 5 × 5?", "25", ["10", "20"], "Five groups of five make 25."),
  M('count', 1, "How many sides do a square and a triangle have altogether?", "7", ["6", "8"], "4 + 3 = 7."),
  M('count', 2, "If you have 3 apples and eat 1, how many are left?", "2", ["1", "4"], "3 − 1 = 2."),
  M('count', 1, "How many days are in a weekend?", "2", ["1", "5"], "Saturday and Sunday."),

  // everyday science
  M('sci', 1, "What happens to ice when it gets warm?", "It melts into water", ["It turns into sand", "It gets bigger"], "Ice is frozen water. Warmth melts it."),
  M('sci', 1, "What does water turn into when it gets very cold?", "Ice", ["Steam", "Juice"], "Water freezes into ice at 0 degrees Celsius."),
  M('sci', 1, "Which of these will a magnet pick up?", "A paper clip", ["A plastic spoon", "A wooden block"], "Magnets pull on things made of iron or steel."),
  T('sci', 1, "Plants need sunlight and water to grow.", true, "Plants use sunlight to make their own food."),
  M('sci', 1, "What does a plant take in through its roots?", "Water", ["Sunlight", "Music"], "Roots drink up water from the soil."),
  M('sci', 1, "What makes a shadow?", "Something blocking the light", ["Rain", "Wind"], "When you block the light, you make a dark shape: your shadow."),
  M('sci', 1, "What do seeds grow into?", "Plants", ["Rocks", "Clouds"], "Plant a seed, give it water, and watch it grow."),
  M('sci', 1, "What gives us light and warmth during the day?", "The Sun", ["The Moon", "The clouds"], "The Sun is a giant ball of hot glowing gas."),
  M('sci', 1, "When water boils, what does it turn into?", "Steam", ["Ice", "Sand"], "Boiling water turns into steam, a gas."),
  M('sci', 1, "What pulls things down to the ground when you drop them?", "Gravity", ["Wind", "Magnets"], "Gravity is the pull of the Earth."),
  M('sci', 1, "Which of these can you see through?", "Glass", ["Wood", "Metal"], "Glass is transparent: light goes right through."),
  T('sci', 2, "Butterflies can taste with their feet.", true, "They stand on a leaf to find out if it is good for their eggs."),
  M('sci', 1, "Which of these floats on water?", "A wooden stick", ["A stone", "A metal key"], "Wood is lighter than the same amount of water, so it floats."),
  M('sci', 1, "What do you need to switch on to light up a dark room?", "A light", ["A tap", "A fan"], "Lights use electricity to shine."),
  M('sci', 1, "What do we breathe in to stay alive?", "Air", ["Water", "Sand"], "Air has the oxygen our bodies need."),
  M('sci', 1, "Which of these is a liquid?", "Milk", ["A rock", "A spoon"], "Liquids can be poured, like milk and water."),
  M('sci', 2, "Which of these is a gas?", "Steam", ["Ice", "Wood"], "Steam is water as a gas."),
  M('sci', 1, "What do bees carry from flower to flower?", "Pollen", ["Water", "Sand"], "Carrying pollen helps flowers make seeds."),
  M('sci', 1, "What should you put plastic bottles in so they can be made into new things?", "The recycling bin", ["The garden", "The bath"], "Recycling turns old things into new things."),
  M('sci', 2, "What do we call the force that slows down a sliding sledge?", "Friction", ["Gravity", "Magnetism"], "Friction happens when things rub together."),
  M('sci', 1, "What is this?", "A volcano", ["A mountain of sand", "A waterfall"], "Volcanoes can erupt hot, melted rock called lava.", { img: 'Volcano' }),
  T('ani', 1, "Spiders are insects.", false, "Spiders have eight legs, so they are not insects. They are arachnids."),
  T('space', 1, "The Sun goes around the Earth.", false, "It is the other way round: the Earth goes around the Sun."),
  T('sci', 1, "Plants can grow without any water.", false, "All plants need water to live and grow."),
];
