import { M, T, N, O } from './lib.mjs';

// [year, host city, host country]
export const SUMMER = [
  [1896, 'Athens', 'Greece'], [1900, 'Paris', 'France'], [1904, 'St. Louis', 'United States'], [1908, 'London', 'United Kingdom'],
  [1912, 'Stockholm', 'Sweden'], [1920, 'Antwerp', 'Belgium'], [1924, 'Paris', 'France'], [1928, 'Amsterdam', 'Netherlands'],
  [1932, 'Los Angeles', 'United States'], [1936, 'Berlin', 'Germany'], [1948, 'London', 'United Kingdom'], [1952, 'Helsinki', 'Finland'],
  [1956, 'Melbourne', 'Australia'], [1960, 'Rome', 'Italy'], [1964, 'Tokyo', 'Japan'], [1968, 'Mexico City', 'Mexico'],
  [1972, 'Munich', 'West Germany'], [1976, 'Montreal', 'Canada'], [1980, 'Moscow', 'Soviet Union'], [1984, 'Los Angeles', 'United States'],
  [1988, 'Seoul', 'South Korea'], [1992, 'Barcelona', 'Spain'], [1996, 'Atlanta', 'United States'], [2000, 'Sydney', 'Australia'],
  [2004, 'Athens', 'Greece'], [2008, 'Beijing', 'China'], [2012, 'London', 'United Kingdom'], [2016, 'Rio de Janeiro', 'Brazil'],
  [2020, 'Tokyo', 'Japan'], [2024, 'Paris', 'France'],
];
export const WINTER = [
  [1924, 'Chamonix', 'France'], [1928, 'St. Moritz', 'Switzerland'], [1932, 'Lake Placid', 'United States'],
  [1936, 'Garmisch-Partenkirchen', 'Germany'], [1948, 'St. Moritz', 'Switzerland'], [1952, 'Oslo', 'Norway'],
  [1956, "Cortina d'Ampezzo", 'Italy'], [1960, 'Squaw Valley', 'United States'], [1964, 'Innsbruck', 'Austria'],
  [1968, 'Grenoble', 'France'], [1972, 'Sapporo', 'Japan'], [1976, 'Innsbruck', 'Austria'], [1980, 'Lake Placid', 'United States'],
  [1984, 'Sarajevo', 'Yugoslavia'], [1988, 'Calgary', 'Canada'], [1992, 'Albertville', 'France'], [1994, 'Lillehammer', 'Norway'],
  [1998, 'Nagano', 'Japan'], [2002, 'Salt Lake City', 'United States'], [2006, 'Turin', 'Italy'], [2010, 'Vancouver', 'Canada'],
  [2014, 'Sochi', 'Russia'], [2018, 'Pyeongchang', 'South Korea'], [2022, 'Beijing', 'China'],
];
// [year, winner, runner-up, host]. FIFA counts West Germany's record as Germany's, so we use 'Germany' throughout.
export const WORLD_CUP = [
  [1930, 'Uruguay', 'Argentina', 'Uruguay'], [1934, 'Italy', 'Czechoslovakia', 'Italy'], [1938, 'Italy', 'Hungary', 'France'],
  [1950, 'Uruguay', 'Brazil', 'Brazil'], [1954, 'Germany', 'Hungary', 'Switzerland'], [1958, 'Brazil', 'Sweden', 'Sweden'],
  [1962, 'Brazil', 'Czechoslovakia', 'Chile'], [1966, 'England', 'Germany', 'England'], [1970, 'Brazil', 'Italy', 'Mexico'],
  [1974, 'Germany', 'Netherlands', 'Germany'], [1978, 'Argentina', 'Netherlands', 'Argentina'], [1982, 'Italy', 'Germany', 'Spain'],
  [1986, 'Argentina', 'Germany', 'Mexico'], [1990, 'Germany', 'Argentina', 'Italy'], [1994, 'Brazil', 'Italy', 'United States'],
  [1998, 'France', 'Brazil', 'France'], [2002, 'Brazil', 'Germany', 'South Korea and Japan'], [2006, 'Italy', 'France', 'Germany'],
  [2010, 'Spain', 'Netherlands', 'South Africa'], [2014, 'Germany', 'Argentina', 'Brazil'], [2018, 'France', 'Croatia', 'Russia'],
  [2022, 'Argentina', 'France', 'Qatar'],
];
// [name, sport, country, difficulty, blurb]
export const ATHLETES = [
  ['Usain Bolt', 'Athletics', 'Jamaica', 1, 'Sprinter who set the 100 m and 200 m world records in 2009.'],
  ['Michael Phelps', 'Swimming', 'United States', 1, 'Swimmer with a record 23 Olympic gold medals.'],
  ['Serena Williams', 'Tennis', 'United States', 1, 'Won 23 Grand Slam singles titles.'],
  ['Roger Federer', 'Tennis', 'Switzerland', 1, 'Won a record eight Wimbledon men\'s singles titles.'],
  ['Rafael Nadal', 'Tennis', 'Spain', 1, 'Won the French Open a record 14 times.'],
  ['Novak Djokovic', 'Tennis', 'Serbia', 2, 'Had won a record 24 Grand Slam singles titles by the end of 2024.'],
  ['Pelé', 'Football', 'Brazil', 1, 'The only player to win three World Cups (1958, 1962, 1970).'],
  ['Diego Maradona', 'Football', 'Argentina', 1, 'Led Argentina to the 1986 World Cup.'],
  ['Lionel Messi', 'Football', 'Argentina', 1, 'Won the 2022 World Cup and a record eight Ballon d\'Or awards (as of 2024).'],
  ['Cristiano Ronaldo', 'Football', 'Portugal', 1, 'Led Portugal to the Euro 2016 title.'],
  ['Michael Jordan', 'Basketball', 'United States', 1, 'Won six NBA championships with the Chicago Bulls.'],
  ['LeBron James', 'Basketball', 'United States', 1, 'Became the NBA\'s all-time top points scorer in 2023.'],
  ['Muhammad Ali', 'Boxing', 'United States', 1, 'Three-time world heavyweight champion, nicknamed "The Greatest".'],
  ['Tiger Woods', 'Golf', 'United States', 1, 'Won 15 men\'s major championships.'],
  ['Jack Nicklaus', 'Golf', 'United States', 2, 'Won a record 18 men\'s major championships.'],
  ['Wayne Gretzky', 'Ice hockey', 'Canada', 2, 'Nicknamed "The Great One"; holds the NHL record for career points.'],
  ['Sachin Tendulkar', 'Cricket', 'India', 2, 'The first batter to score 100 international centuries.'],
  ['Don Bradman', 'Cricket', 'Australia', 2, 'Finished with a Test batting average of 99.94.'],
  ['Babe Ruth', 'Baseball', 'United States', 2, 'Baseball\'s great home-run hitter of the 1920s and 1930s.'],
  ['Jesse Owens', 'Athletics', 'United States', 2, 'Won four gold medals at the 1936 Berlin Olympics.'],
  ['Nadia Comăneci', 'Gymnastics', 'Romania', 2, 'Scored the first perfect 10 in Olympic gymnastics, in 1976.'],
  ['Simone Biles', 'Gymnastics', 'United States', 1, 'Has several gymnastics moves named after her.'],
  ['Lewis Hamilton', 'Formula One', 'United Kingdom', 1, 'Won seven Formula One world titles, level with Michael Schumacher.'],
  ['Michael Schumacher', 'Formula One', 'Germany', 2, 'Won seven Formula One world titles, five of them in a row with Ferrari.'],
  ['Ayrton Senna', 'Formula One', 'Brazil', 2, 'Three-time Formula One world champion (1988, 1990, 1991).'],
  ['Eddy Merckx', 'Cycling', 'Belgium', 3, 'Won the Tour de France five times.'],
  ['Jonah Lomu', 'Rugby union', 'New Zealand', 2, 'All Blacks winger who starred at the 1995 Rugby World Cup.'],
  ['Mark Spitz', 'Swimming', 'United States', 3, 'Won seven gold medals at the 1972 Munich Olympics.'],
  ['Ian Thorpe', 'Swimming', 'Australia', 2, 'Won five Olympic gold medals, nicknamed "Thorpedo".'],
  ['Katie Ledecky', 'Swimming', 'United States', 2, 'Distance freestyle swimmer with many Olympic golds.'],
  ['Steffi Graf', 'Tennis', 'Germany', 2, 'Won the "Golden Slam" in 1988: all four majors plus Olympic gold.'],
  ['Björn Borg', 'Tennis', 'Sweden', 2, 'Won five Wimbledon titles in a row (1976–1980).'],
  ['Eliud Kipchoge', 'Athletics', 'Kenya', 2, 'Marathon runner who won Olympic gold in 2016 and 2020.'],
  ['Mikaela Shiffrin', 'Alpine skiing', 'United States', 2, 'Holds the record for most Alpine Skiing World Cup race wins.'],
  ['Yuzuru Hanyu', 'Figure skating', 'Japan', 3, 'Won Olympic figure skating gold in 2014 and 2018.'],
  ['Shaun White', 'Snowboarding', 'United States', 2, 'Won three Olympic halfpipe gold medals.'],
  ['Kelly Slater', 'Surfing', 'United States', 3, 'Won a record 11 surfing world titles.'],
  ['Tony Hawk', 'Skateboarding', 'United States', 2, 'Landed the first widely recognised 900 (two and a half spins) at the 1999 X Games.'],
  ['Chris Hoy', 'Cycling', 'United Kingdom', 3, 'Track cyclist with six Olympic gold medals.'],
  ['Mo Farah', 'Athletics', 'United Kingdom', 2, 'Won the 5,000 m and 10,000 m at both the 2012 and 2016 Olympics.'],
  ['Carl Lewis', 'Athletics', 'United States', 2, 'Won nine Olympic gold medals in sprinting and long jump.'],
  ['Florence Griffith-Joyner', 'Athletics', 'United States', 3, 'Set the women\'s 100 m and 200 m world records in 1988.'],
  ['Magic Johnson', 'Basketball', 'United States', 2, 'Won five NBA championships with the Los Angeles Lakers.'],
  ['Martina Hingis', 'Tennis', 'Switzerland', 3, 'Became world number one at just 16 years old.'],
];

export const QUESTIONS = [
  // team sizes and rules
  N('rules', 1, "How many players does each football (soccer) team have on the pitch?", 11, "players", 0, "Ten outfield players plus a goalkeeper."),
  N('rules', 1, "How many players does each basketball team have on the court?", 5, "players", 0, "Five players per side are on court at once."),
  N('rules', 2, "How many players does each volleyball team have on the court?", 6, "players", 0, "Six players rotate positions on each side."),
  N('rules', 2, "How many players are in a rugby union team on the field?", 15, "players", 0, "Rugby union uses 15 players; rugby league uses 13."),
  N('rules', 3, "How many players are in a rugby league team on the field?", 13, "players", 0, "Rugby league has two fewer players than rugby union."),
  N('rules', 2, "How many players per side are on the ice in ice hockey, including the goaltender?", 6, "players", 0, "Five skaters and a goaltender."),
  N('rules', 2, "How many players are in a baseball team's fielding line-up?", 9, "players", 0, "Nine fielders, including the pitcher and catcher."),
  N('rules', 2, "How many players are on court for each netball team?", 7, "players", 0, "Each of the seven players has a position bib, like GS or WD."),
  N('rules', 1, "How many players are in a cricket team?", 11, "players", 0, "Each side fields eleven players."),
  N('rules', 3, "How many players per team are on court in indoor handball?", 7, "players", 0, "Six court players and a goalkeeper."),
  N('rules', 3, "How many players are on the field for each side in Australian rules football?", 18, "players", 0, "Aussie rules is played 18-a-side on an oval field."),
  N('rules', 1, "How many holes are played in a standard round of golf?", 18, "holes", 0, "A standard course has 18 holes."),
  M('rules', 1, "In tennis, what does 'love' mean?", "Zero", ["A tie", "A winning shot", "A fault"], "A score of 15–love means 15–0."),
  M('rules', 2, "In tennis, what is the score called when both players have 40?", "Deuce", ["Love", "Advantage", "Let"], "From deuce, a player must win two points in a row."),
  N('rules', 1, "How many Grand Slam tournaments are there in tennis each year?", 4, "", 0, "Australian Open, French Open, Wimbledon and the US Open."),
  M('rules', 1, "On what surface is Wimbledon played?", "Grass", ["Clay", "Hard court", "Carpet"], "Wimbledon is the only Grand Slam still played on grass."),
  M('rules', 2, "On what surface is the French Open played?", "Clay", ["Grass", "Hard court", "Carpet"], "Roland-Garros's red clay makes the ball bounce high and slow."),
  M('rules', 1, "In golf, what is a score of one under par on a hole called?", "Birdie", ["Eagle", "Bogey", "Albatross"], "An eagle is two under par; a bogey is one over."),
  M('rules', 2, "In golf, what is a score of two under par on a hole called?", "Eagle", ["Birdie", "Albatross", "Bogey"], "An albatross is three under par."),
  M('rules', 2, "In golf, what is a score of one over par on a hole called?", "Bogey", ["Birdie", "Eagle", "Par"], "A double bogey is two over par."),
  N('rules', 1, "What is the highest score possible with three darts?", 180, "points", 0, "Three treble 20s make 180."),
  N('rules', 2, "How many points is the inner bullseye worth in darts?", 50, "points", 0, "The outer bull is worth 25."),
  N('rules', 2, "What is the maximum break in standard snooker?", 147, "points", 0, "15 reds each with the black, then all the colours."),
  N('rules', 2, "How many red balls are used at the start of a standard snooker frame?", 15, "balls", 0, "Plus six coloured balls and the white cue ball."),
  N('rules', 2, "How many points is the black ball worth in snooker?", 7, "points", 0, "Yellow 2, green 3, brown 4, blue 5, pink 6, black 7."),
  N('rules', 2, "What is a perfect score in ten-pin bowling?", 300, "points", 0, "Twelve strikes in a row."),
  N('rules', 1, "How many pins are used in ten-pin bowling?", 10, "pins", 0, "The clue is in the name."),
  N('rules', 2, "How high is a regulation basketball hoop above the floor, in feet?", 10, "ft", 0, "The rim is 10 feet (3.05 m) high."),
  N('rules', 1, "How many rings are on the Olympic flag?", 5, "rings", 0, "The five rings represent the inhabited continents joined by the Olympics."),
  M('rules', 1, "In which sport would you use a shuttlecock?", "Badminton", ["Squash", "Table tennis", "Tennis"], "Shuttlecocks can fly at over 400 km/h when smashed."),
  M('rules', 1, "In which sport is a puck used?", "Ice hockey", ["Field hockey", "Lacrosse", "Curling"], "A puck is a hard rubber disc."),
  M('rules', 1, "In which sport do teams form a 'scrum'?", "Rugby", ["Basketball", "Baseball", "Volleyball"], "Forwards bind together and push to win the ball."),
  M('rules', 2, "In cricket, how many balls are in a standard over?", "6", ["4", "8", "10"], "A bowler delivers six legal balls in an over."),
  M('rules', 2, "In cricket, what does LBW stand for?", "Leg before wicket", ["Long ball wide", "Low bowled wicket", "Late bat wide"], "A batter can be out if the ball would have hit the stumps but hit their leg."),
  N('rules', 2, "How many stumps make up one wicket in cricket?", 3, "stumps", 0, "Three stumps topped by two bails."),
  N('rules', 2, "How many strikes make an out in baseball?", 3, "strikes", 0, "'Three strikes and you're out!'"),
  N('rules', 2, "How many innings are in a standard professional baseball game?", 9, "innings", 0, "Extra innings are played if the score is tied."),
  N('rules', 2, "How many points is a try worth in rugby union?", 5, "points", 0, "A conversion kick afterwards adds 2 more."),
  N('rules', 2, "How many points is a touchdown worth in American football?", 6, "points", 0, "The extra point or two-point try comes afterwards."),
  N('rules', 1, "How many runs is it when the ball is hit over the boundary in cricket without bouncing?", 6, "runs", 0, "If it bounces first, it's a four."),
  N('rules', 2, "To how many points is a standard game of table tennis played?", 11, "points", 0, "You must win by two clear points."),
  N('rules', 3, "To how many points is a standard game of badminton played?", 21, "points", 0, "Badminton games go to 21, with a two-point lead needed."),
  N('rules', 3, "In indoor volleyball, to how many points are the main sets played?", 25, "points", 0, "A deciding fifth set goes to 15."),
  N('rules', 2, "How many periods are in a standard ice hockey game?", 3, "periods", 0, "Three periods of 20 minutes."),
  N('rules', 1, "How many minutes does a standard football (soccer) match last, not counting added time?", 90, "minutes", 0, "Two halves of 45 minutes."),
  N('rules', 2, "How many minutes does a standard rugby union match last?", 80, "minutes", 0, "Two halves of 40 minutes."),
  N('rules', 3, "How many minutes long is each quarter of an NBA basketball game?", 12, "minutes", 0, "FIBA international games use 10-minute quarters."),
  O('rules', 3, "Put the strokes of an individual medley swimming race in order.", ["Butterfly", "Backstroke", "Breaststroke", "Freestyle"], "First stroke first", "Individual medley order: fly, back, breast, free."),
  N('rules', 1, "How long is an Olympic swimming pool?", 50, "m", 0, "Olympic pools are 50 metres long."),
  N('rules', 2, "How long is a marathon, in kilometres?", 42.195, "km", 0.2, "A marathon is 42.195 km (26.2 miles)."),
  M('rules', 1, "In which order are the three parts of a triathlon?", "Swim, cycle, run", ["Run, swim, cycle", "Cycle, run, swim", "Swim, run, cycle"], "Triathletes swim first, then cycle, then run."),
  N('rules', 2, "How many events are in an Olympic decathlon?", 10, "events", 0, "Deca means ten."),
  N('rules', 3, "How many events are in the heptathlon?", 7, "events", 0, "Hepta means seven."),
  M('rules', 1, "What colour jersey does the overall leader wear in the Tour de France?", "Yellow", ["Green", "Pink", "Red"], "The yellow jersey is called the maillot jaune."),
  M('rules', 3, "In the Tour de France, what does the polka-dot jersey reward?", "Best climber", ["Best young rider", "Points leader", "Most aggressive rider"], "The red-on-white polka-dot jersey goes to the King of the Mountains."),
  M('rules', 2, "Which of these is NOT one of the three Olympic fencing weapons?", "Rapier", ["Foil", "Épée", "Sabre"], "Olympic fencing uses foil, épée and sabre."),
  M('rules', 1, "Which country did judo come from?", "Japan", ["China", "Korea", "Thailand"], "Jigoro Kano founded judo in 1882."),
  M('rules', 2, "Which country did taekwondo come from?", "South Korea", ["Japan", "China", "Vietnam"], "Taekwondo became an Olympic sport in 2000."),
  M('rules', 1, "In which country is sumo wrestling the national sport?", "Japan", ["China", "Mongolia", "Thailand"], "Sumo has been practised in Japan for centuries."),
  N('rules', 2, "How far is the penalty spot from the goal line in football, in metres?", 11, "m", 0, "That's 12 yards."),
  M('rules', 2, "Which flag means a motor race has finished?", "Chequered flag", ["Red flag", "Yellow flag", "Blue flag"], "A red flag stops the race; yellow means danger, slow down."),
  M('rules', 2, "In basketball, how many points is a shot from behind the arc worth?", "3", ["2", "4", "1"], "A free throw is worth 1."),
  M('rules', 1, "In football (soccer), which player may handle the ball inside their own penalty area?", "Goalkeeper", ["Captain", "Defender", "Striker"], "Outfield players may not use their hands or arms."),
  M('rules', 2, "What does a referee show a football player to send them off?", "A red card", ["A yellow card", "A green card", "A blue card"], "Two yellow cards also add up to a red."),
  N('rules', 2, "How many players does each team have on the field in American football?", 11, "players", 0, "Each side has eleven on the field, with separate offence and defence units."),
  M('rules', 3, "In curling, what is the target area called?", "The house", ["The nest", "The pit", "The ring"], "The house is the set of circles at the end of the sheet."),
  N('rules', 3, "How many players are on each polo team?", 4, "players", 0, "Four riders per side."),
  N('rules', 2, "How many players are on a water polo team in the pool?", 7, "players", 0, "Six field players and a goalkeeper."),

  // olympics and events
  M('olympics', 1, "In which country were the ancient Olympic Games held?", "Greece", ["Italy", "Egypt", "Turkey"], "They were held at Olympia from 776 BC."),
  M('olympics', 2, "Who founded the modern Olympic Games?", "Pierre de Coubertin", ["Avery Brundage", "Juan Antonio Samaranch", "Jacques Rogge"], "De Coubertin founded the International Olympic Committee in 1894."),
  M('olympics', 2, "What do the Olympic Latin words 'Citius, Altius, Fortius' mean?", "Faster, Higher, Stronger", ["Bigger, Better, Bolder", "Brave, Strong, True", "Run, Jump, Throw"], "In 2021 'Communiter' (Together) was added."),
  M('olympics', 2, "Which city was the first to host both the Summer and Winter Olympics?", "Beijing", ["Tokyo", "Los Angeles", "Paris"], "Beijing hosted the Summer Games in 2008 and the Winter Games in 2022."),
  M('olympics', 1, "As of 2024, which city was chosen to host the 2028 Summer Olympics?", "Los Angeles", ["Brisbane", "Paris", "Madrid"], "LA will host for the third time, after 1932 and 1984."),
  M('olympics', 2, "As of 2024, which city was chosen to host the 2032 Summer Olympics?", "Brisbane", ["Doha", "Sydney", "Melbourne"], "Brisbane was chosen in 2021."),
  T('olympics', 2, "Skateboarding and surfing made their Olympic debut at the Tokyo 2020 Games.", true, "Sport climbing and karate also debuted in Tokyo."),
  T('olympics', 2, "Breaking (breakdancing) made its Olympic debut at Paris 2024.", true, "Breaking was added for Paris 2024."),
  T('olympics', 3, "The 2020 Tokyo Olympics were actually held in 2021.", true, "They were postponed by a year because of the COVID-19 pandemic."),
  M('olympics', 2, "Which country has won the most Summer Olympic medals overall?", "United States", ["China", "Russia", "United Kingdom"], "The US has won over 2,500 Summer Olympic medals."),
  M('olympics', 3, "In which city were the first official Paralympic Games held, in 1960?", "Rome", ["London", "Tokyo", "Stoke Mandeville"], "They followed the Rome Olympics; the earlier Stoke Mandeville Games inspired them."),
  O('olympics', 3, "Put these Summer Olympic host cities in order of their first Games, earliest first.", ["Berlin", "Rome", "Seoul", "Sydney"], "Hosted first", "Berlin 1936, Rome 1960, Seoul 1988, Sydney 2000."),
  N('olympics', 2, "How many gold medals did Michael Phelps win at the Olympics?", 23, "golds", 0, "He won 28 medals in all, between 2004 and 2016."),
  N('olympics', 3, "How many Olympic gold medals did Usain Bolt finish with?", 8, "golds", 0, "He won nine, but one relay gold was taken away because of a teammate's doping."),
  N('olympics', 2, "How many gold medals did Jesse Owens win at the 1936 Berlin Olympics?", 4, "golds", 0, "100 m, 200 m, long jump and the 4 × 100 m relay."),
  M('olympics', 2, "At which Olympics did Nadia Comăneci score the first perfect 10 in gymnastics?", "Montreal 1976", ["Moscow 1980", "Munich 1972", "Los Angeles 1984"], "She was 14 years old."),
  T('olympics', 3, "Ethiopia's Abebe Bikila won the 1960 Olympic marathon running barefoot.", true, "He won in Rome and won again in Tokyo in 1964, that time in shoes."),
  M('olympics', 2, "In which sport did the 'Miracle on Ice' happen at the 1980 Winter Olympics?", "Ice hockey", ["Figure skating", "Speed skating", "Curling"], "A team of US college players beat the Soviet Union."),
  M('olympics', 3, "Which country topped the medal table at the 2022 Winter Olympics in Beijing?", "Norway", ["China", "Germany", "United States"], "Norway won 16 gold medals."),

  // football
  M('football', 1, "As of 2024, which country had won the men's FIFA World Cup the most times?", "Brazil", ["Germany", "Italy", "Argentina"], "Brazil had five titles: 1958, 1962, 1970, 1994 and 2002."),
  T('football', 2, "Brazil had played in every men's World Cup tournament up to 2022.", true, "Brazil is the only team to have qualified for every World Cup."),
  M('football', 2, "How many teams did FIFA decide would play at the 2026 World Cup?", "48", ["32", "40", "64"], "The tournament grew from 32 to 48 teams."),
  M('football', 2, "Which three countries were chosen to co-host the 2026 FIFA World Cup?", "United States, Canada and Mexico", ["United States, Mexico and Costa Rica", "Canada, United States and Cuba", "Mexico, Colombia and United States"], "It was the first World Cup shared by three countries."),
  M('football', 2, "In which year was the Football Association (FA) founded in England?", "1863", ["1888", "1904", "1823"], "The FA wrote the first widely used rules of football."),
  M('football', 2, "As of 2024, how many Ballon d'Or awards had Lionel Messi won?", "8", ["5", "6", "7"], "His eighth came in 2023."),
  M('football', 1, "What is the name of the trophy given to the winners of the men's World Cup since 1974?", "FIFA World Cup Trophy", ["Jules Rimet Trophy", "Henri Delaunay Trophy", "Copa América"], "The earlier Jules Rimet Trophy was given to Brazil to keep after their third win, in 1970."),
  M('football', 2, "Which country won the first Women's World Cup, in 1991?", "United States", ["Norway", "Germany", "China"], "The final was played in China."),
  M('football', 3, "Which country won the 2023 FIFA Women's World Cup?", "Spain", ["England", "United States", "Sweden"], "Spain beat England 1–0 in the final in Sydney."),
  M('football', 2, "Which country won UEFA Euro 2024?", "Spain", ["England", "France", "Germany"], "Spain beat England 2–1 in the final in Berlin."),
  M('football', 3, "Which country won the European Championship in 2016?", "Portugal", ["France", "Germany", "Spain"], "Portugal beat hosts France 1–0 in the final."),
  M('football', 2, "Who scored a famous goal in the 1986 World Cup that he called the 'Hand of God'?", "Diego Maradona", ["Pelé", "Gary Lineker", "Michel Platini"], "It came against England in the quarter-final."),
  M('football', 2, "Which English club plays home games at Anfield?", "Liverpool", ["Everton", "Manchester United", "Arsenal"], "Everton's stadium is less than a mile away."),
  M('football', 2, "Which club plays home games at the Camp Nou?", "FC Barcelona", ["Real Madrid", "Atlético Madrid", "Valencia"], "Real Madrid plays at the Santiago Bernabéu."),
  M('football', 3, "Who scored a hat-trick in the 1966 World Cup final?", "Geoff Hurst", ["Bobby Charlton", "Bobby Moore", "Martin Peters"], "England beat West Germany 4–2 after extra time."),

  // athletes and records
  M('records', 2, "As of 2024, what was Usain Bolt's 100 m world record time?", "9.58 seconds", ["9.63 seconds", "9.69 seconds", "9.72 seconds"], "He set it in Berlin in 2009."),
  M('records', 3, "Who held the women's 100 m world record as of 2024?", "Florence Griffith-Joyner", ["Shelly-Ann Fraser-Pryce", "Marion Jones", "Elaine Thompson-Herah"], "She ran 10.49 seconds in 1988."),
  M('records', 2, "Who ran the first mile in under four minutes, in 1954?", "Roger Bannister", ["Sebastian Coe", "Steve Ovett", "Hicham El Guerrouj"], "He ran 3:59.4 in Oxford."),
  M('records', 2, "As of the end of 2024, how many Grand Slam singles titles had Novak Djokovic won?", "24", ["20", "22", "23"], "That was the men's record."),
  N('records', 2, "How many Grand Slam singles titles did Serena Williams win?", 23, "titles", 0, "That's the most of any player in the Open Era."),
  N('records', 2, "How many times did Rafael Nadal win the French Open men's singles?", 14, "times", 0, "No player has won any Grand Slam event more often."),
  N('records', 2, "How many men's major golf championships did Jack Nicklaus win?", 18, "majors", 0, "Tiger Woods is second with 15."),
  M('records', 3, "What was Don Bradman's Test batting average?", "99.94", ["89.94", "79.94", "100.00"], "He needed only 4 runs in his last innings to average 100, but was out for 0."),
  T('records', 2, "Pelé is the only player to have won three men's World Cups.", true, "He won in 1958, 1962 and 1970."),
  N('records', 3, "How many Formula One world titles did Lewis Hamilton win by the end of 2024?", 7, "titles", 0, "Level with Michael Schumacher's record of seven."),
  T('records', 3, "As of 2024, the New England Patriots and the Pittsburgh Steelers shared the record for most Super Bowl wins, with six each.", true, "Both had six Lombardi Trophies."),
  M('records', 3, "As of 2024, which country had won the men's Rugby World Cup the most times?", "South Africa", ["New Zealand", "Australia", "England"], "South Africa won in 1995, 2007, 2019 and 2023."),
  M('records', 3, "As of 2024, which country had won the men's Cricket World Cup (one-day) the most times?", "Australia", ["India", "West Indies", "England"], "Australia won its sixth title in 2023."),
  M('records', 3, "Who set the men's marathon world record of 2:00:35 in Chicago in 2023?", "Kelvin Kiptum", ["Eliud Kipchoge", "Kenenisa Bekele", "Haile Gebrselassie"], "It was ratified as the world record in 2024."),

  // competitions and places
  M('rules', 1, "In which sport is the Super Bowl played?", "American football", ["Baseball", "Basketball", "Ice hockey"], "It decides the NFL champion each year."),
  M('rules', 1, "In which sport is the Stanley Cup awarded?", "Ice hockey", ["Baseball", "Golf", "Basketball"], "It is the NHL's championship trophy."),
  M('rules', 2, "Which two sides compete for golf's Ryder Cup?", "Europe and the United States", ["England and Scotland", "Australia and the United States", "Europe and the Rest of the World"], "It is played every two years."),
  M('rules', 2, "In which sport is the America's Cup contested?", "Sailing", ["Rowing", "Polo", "Golf"], "It dates back to 1851 and is the oldest trophy in international sport."),
  M('rules', 2, "Which two countries play cricket for the Ashes?", "England and Australia", ["England and India", "Australia and New Zealand", "India and Pakistan"], "The tiny Ashes urn dates from 1882–83."),
  N('rules', 2, "How many teams compete in rugby union's Six Nations Championship?", 6, "teams", 0, "England, France, Ireland, Italy, Scotland and Wales."),
  M('rules', 1, "In which city is Wimbledon played?", "London", ["Manchester", "Birmingham", "Edinburgh"], "The All England Club is in south-west London."),
  M('rules', 2, "What colour jacket is given to the winner of the Masters golf tournament?", "Green", ["Red", "Blue", "Gold"], "The Masters is played at Augusta, Georgia."),
  M('rules', 2, "In which sport is the Indianapolis 500 raced?", "Motor racing", ["Cycling", "Horse racing", "Running"], "It is 500 miles: 200 laps of a 2.5-mile oval."),
  M('rules', 2, "In which country is the 24 Hours of Le Mans car race held?", "France", ["Belgium", "Italy", "Germany"], "Teams of drivers race for a whole day and night."),
  M('rules', 2, "The Kentucky Derby is a famous race in which sport?", "Horse racing", ["Motor racing", "Rowing", "Cycling"], "It is held each May at Churchill Downs."),
  M('rules', 3, "At which racecourse is the Grand National run?", "Aintree", ["Ascot", "Epsom", "Cheltenham"], "Aintree is near Liverpool."),
  M('rules', 2, "Which Scottish town is known as 'the home of golf'?", "St Andrews", ["Gleneagles", "Troon", "Carnoustie"], "Golf has been played there since the 1400s."),
  M('rules', 2, "Who invented basketball in 1891?", "James Naismith", ["Abner Doubleday", "William Morgan", "Walter Camp"], "He used peach baskets as the first hoops."),
  M('rules', 3, "Who invented volleyball in 1895?", "William G. Morgan", ["James Naismith", "Walter Camp", "Abner Doubleday"], "He first called it 'mintonette'."),
  M('rules', 2, "Which English school is said to have given its name to a sport in the 1800s?", "Rugby School", ["Eton College", "Harrow School", "Winchester College"], "The legend says a pupil picked up the ball and ran with it in 1823."),
  M('rules', 3, "In which year was the first Wimbledon Championship held?", "1877", ["1897", "1867", "1901"], "It is the oldest tennis tournament in the world."),
  M('rules', 3, "In which year was the first Tour de France held?", "1903", ["1913", "1923", "1896"], "It was started by a sports newspaper to boost sales."),
  M('rules', 2, "Which sport uses the terms 'spare' and 'strike'?", "Ten-pin bowling", ["Golf", "Cricket", "Archery"], "Strikes and spares earn bonus points."),
  M('rules', 2, "Which sport uses the terms 'ace', 'let' and 'volley'?", "Tennis", ["Football", "Rugby", "Golf"], "An ace is a serve the opponent cannot touch."),
  M('rules', 3, "How many races make up the US Triple Crown of horse racing?", "3", ["2", "4", "5"], "The Kentucky Derby, the Preakness Stakes and the Belmont Stakes."),
];
