import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {newCampaign,campaignWorld,finishMission,snapshotWorld,parseSave} from '../js/core/save.mjs';
import {orderMove,tick} from '../js/core/world.mjs';
import {damage,throwGrenade} from '../js/core/combat.mjs';
import {MISSIONS} from '../js/data/missions.mjs';
export function pilot(w){const squad=w.units.filter(u=>u.team==='blue'&&u.hp>0&&!u.escort),lead=squad[0];if(!lead)return;const m=w.mission;if(m.type==='clear'){const enemy=w.units.filter(u=>u.team==='red'&&u.hp>0).sort((a,b)=>Math.hypot(a.x-lead.x,a.z-lead.z)-Math.hypot(b.x-lead.x,b.z-lead.z))[0];if(enemy)orderMove(w,enemy.x,enemy.z+5);}if(m.type==='reach')orderMove(w,w.map.goal.x,w.map.goal.z);if(m.type==='escort'){const escort=w.units.find(u=>u.escort);if(escort){if(Math.hypot(lead.x-escort.x,lead.z-escort.z)>5)orderMove(w,escort.x,escort.z-2);else orderMove(w,w.map.goal.x,Math.max(w.map.goal.z,escort.z-4));}}}
const c=newCampaign(),results=[];for(const def of MISSIONS){const w=campaignWorld(c);for(let i=0;i<def.limit*60&&w.mission.status==='active';i++){if(i%60===0)pilot(w);tick(w);}const result=finishMission(c,w);results.push(result);console.log(result);if(!result.win)console.log(w.units.filter(u=>u.team==='blue').map(u=>({id:u.id,x:u.x,z:u.z,hp:u.hp,path:u.path.length})));assert.equal(result.win,true,def.title+' failed');if(def.id===1)assert.equal(w.fortified,true);}
assert.equal(c.mission,6);assert.ok(c.roster.some(m=>m.xp>0));
const saveCampaign=newCampaign(),w=campaignWorld(saveCampaign);orderMove(w,0,0);for(let i=0;i<120;i++)tick(w);saveCampaign.inProgress=snapshotWorld(w);const restored=campaignWorld(parseSave(JSON.stringify(saveCampaign)));assert.deepEqual(restored.units,w.units);for(let i=0;i<600;i++){tick(w);tick(restored);}assert.deepEqual(restored.units,w.units,'save/load preserves deterministic combat');
const deathCampaign=newCampaign(),deathWorld=campaignWorld(deathCampaign);const old=deathWorld.units[0].rosterId;damage(deathWorld,deathWorld.units[0],1000);tick(deathWorld);assert.equal(deathWorld.mission.status,'defeat');finishMission(deathCampaign,deathWorld);const replacement=campaignWorld(deathCampaign);assert.notEqual(replacement.units[0].rosterId,old);assert.equal(deathCampaign.roster.find(m=>m.id===old).alive,false);
const scars=newCampaign(),scarWorld=campaignWorld(scars);scarWorld.trees[0].dead=true;scarWorld.mission.status='victory';finishMission(scars,scarWorld);const next=campaignWorld(scars);assert.equal(next.trees[0].dead,true);assert.equal(next.fortified,true);
const fireSave=newCampaign(),fireWorld=campaignWorld(fireSave);throwGrenade(fireWorld,fireWorld.units[0],8,5);for(let i=0;i<160;i++)tick(fireWorld);fireSave.inProgress=snapshotWorld(fireWorld);const resumedFire=campaignWorld(parseSave(JSON.stringify(fireSave)));for(let i=0;i<500;i++){tick(fireWorld);tick(resumedFire);}assert.deepEqual(resumedFire.trees,fireWorld.trees,'save/load preserves fire propagation timing');
await writeFile(new URL('../docs/evidence/campaign-sim.json',import.meta.url),JSON.stringify({results,saveReplay:true,permadeath:true,territory:true},null,2));
