// Builds js/geo/bands.js: which continents an exact parallel / meridian crosses, at 0.25° steps (line drawn at the row centre).
// Transcontinental countries (cs) and disputed land are left out, so counts err low. Run: node tools/geo2_bands.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { features } from '../js/geo/topo.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const C = JSON.parse(readFileSync(join(ROOT, 'data/geo/countries.json'), 'utf8'));
const world = JSON.parse(readFileSync(join(ROOT, 'data/geo/world.json'), 'utf8'));
export const CODES = ['AF', 'AS', 'EU', 'NA', 'SA', 'OC'];
export const STEP = 0.25;

// Exact crossings for one line, straight from the polygons.
export function crossings(kind, v, feats = defaultFeats()) {
  const out = new Set();
  for (const f of feats) {
    const bit = CODES.indexOf(f.c);
    if (bit < 0 || out.has(f.c)) continue;
    outer: for (const poly of f.polys) for (const ring of poly) for (let i = 1; i < ring.length; i++) {
      const a = ring[i - 1], b = ring[i];
      if (kind === 'lat') { if ((a[1] - v) * (b[1] - v) < 0) { out.add(f.c); break outer; } }
      else if (Math.abs(a[0] - b[0]) < 180 && (a[0] - v) * (b[0] - v) < 0) { out.add(f.c); break outer; }
    }
  }
  return out;
}
let FE = null;
export function defaultFeats() {
  return FE ||= features(world, 'countries').filter(f => C[f.id] && C[f.id].k !== 'x' && !C[f.id].cs).map(f => ({ id: f.id, c: C[f.id].c, polys: f.polys }));
}

const enc = set => String.fromCharCode(48 + CODES.reduce((m, c, i) => m | (set.has(c) ? 1 << i : 0), 0));
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  let lat = '', lon = '';
  for (let i = 0; i < 180 / STEP; i++) lat += enc(crossings('lat', -90 + (i + 0.5) * STEP));
  for (let i = 0; i < 360 / STEP; i++) lon += enc(crossings('lon', -180 + (i + 0.5) * STEP));
  const src = `// Generated by tools/geo2_bands.mjs from data/geo/world.json. Each char = 48 + bitmask of ${CODES.join(' ')} that an exact
// line at the row centre crosses (rows of ${STEP}°). Transcontinental countries are left out.
export const STEP = ${STEP};
export const CODES = ${JSON.stringify(CODES)};
export const LAT = '${lat.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}';
export const LON = '${lon.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}';
`;
  writeFileSync(join(ROOT, 'js/geo/bands.js'), src);
  console.log('wrote js/geo/bands.js', src.length, 'bytes');
}
