// Hand-checked film casts for `chain` (lane F). Only actors who are in data/packs/actors.json are listed, and a
// film's list holds EVERY such actor who appears in it, so a film is a safe wrong answer for any pair it doesn't hold
// both of. Titles carry the year so remakes can't be confused. Add a film only when sure of its full cast overlap.
export const FILMS = {
  'Titanic (1997)': ['Leonardo DiCaprio', 'Kate Winslet'],
  'Sense and Sensibility (1995)': ['Kate Winslet', 'Emma Thompson', 'Hugh Grant'],
  'Love Actually (2003)': ['Hugh Grant', 'Emma Thompson', 'Keira Knightley', 'Rowan Atkinson'],
  'Notting Hill (1999)': ['Julia Roberts', 'Hugh Grant'],
  'Four Weddings and a Funeral (1994)': ['Hugh Grant', 'Rowan Atkinson'],
  "Ocean's Eleven (2001)": ['Julia Roberts', 'Brad Pitt'],
  'Once Upon a Time in Hollywood (2019)': ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie', 'Al Pacino'],
  'Inception (2010)': ['Leonardo DiCaprio', 'Cillian Murphy'],
  'Oppenheimer (2023)': ['Cillian Murphy', 'Robert Downey Jr.'],
  'The Avengers (2012)': ['Robert Downey Jr.', 'Scarlett Johansson', 'Chris Hemsworth', 'Samuel L. Jackson'],
  'Avengers: Infinity War (2018)': ['Robert Downey Jr.', 'Benedict Cumberbatch', 'Chris Hemsworth', 'Scarlett Johansson', 'Chris Pratt', 'Vin Diesel', 'Tom Holland', 'Samuel L. Jackson', 'Idris Elba'],
  'Thor (2011)': ['Chris Hemsworth', 'Natalie Portman', 'Anthony Hopkins', 'Idris Elba', 'Samuel L. Jackson'],
  'Les Misérables (2012)': ['Hugh Jackman', 'Anne Hathaway'],
  'The Devil Wears Prada (2006)': ['Meryl Streep', 'Anne Hathaway'],
  'The Princess Diaries (2001)': ['Julie Andrews', 'Anne Hathaway'],
  'Interstellar (2014)': ['Anne Hathaway', 'Timothée Chalamet'],
  'The Greatest Showman (2017)': ['Hugh Jackman', 'Zendaya'],
  'Spider-Man: Homecoming (2017)': ['Tom Holland', 'Zendaya', 'Robert Downey Jr.'],
  'Dune (2021)': ['Timothée Chalamet', 'Zendaya'],
  'Little Women (2019)': ['Timothée Chalamet', 'Emma Watson', 'Meryl Streep'],
  "Don't Look Up (2021)": ['Leonardo DiCaprio', 'Jennifer Lawrence', 'Meryl Streep', 'Timothée Chalamet', 'Cate Blanchett'],
  'La La Land (2016)': ['Ryan Gosling', 'Emma Stone'],
  'Barbie (2023)': ['Margot Robbie', 'Ryan Gosling', 'Helen Mirren'],
  'The Wolf of Wall Street (2013)': ['Leonardo DiCaprio', 'Margot Robbie'],
  'The Lord of the Rings: The Fellowship of the Ring (2001)': ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 'Cate Blanchett'],
  'Pirates of the Caribbean: The Curse of the Black Pearl (2003)': ['Johnny Depp', 'Orlando Bloom', 'Keira Knightley'],
  'X-Men (2000)': ['Hugh Jackman', 'Ian McKellen'],
  'X-Men: Days of Future Past (2014)': ['Hugh Jackman', 'Jennifer Lawrence', 'Ian McKellen'],
  'Beauty and the Beast (2017)': ['Emma Watson', 'Emma Thompson', 'Ian McKellen'],
  "Harry Potter and the Philosopher's Stone (2001)": ['Daniel Radcliffe', 'Emma Watson'],
  'Star Wars (1977)': ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
  'Indiana Jones and the Last Crusade (1989)': ['Harrison Ford', 'Sean Connery'],
  'Speed (1994)': ['Keanu Reeves', 'Sandra Bullock'],
  'Skyfall (2012)': ['Daniel Craig', 'Judi Dench'],
  'Casino Royale (2006)': ['Daniel Craig', 'Judi Dench'],
  'Notes on a Scandal (2006)': ['Judi Dench', 'Cate Blanchett'],
  'Jumanji: Welcome to the Jungle (2017)': ['Dwayne Johnson', 'Jack Black'],
  'Kung Fu Panda (2008)': ['Jack Black', 'Jackie Chan', 'Angelina Jolie'],
  'Fast Five (2011)': ['Vin Diesel', 'Dwayne Johnson', 'Gal Gadot'],
  'Red Notice (2021)': ['Dwayne Johnson', 'Gal Gadot'],
  'Guardians of the Galaxy (2014)': ['Chris Pratt', 'Vin Diesel'],
  'Shrek (2001)': ['Mike Myers', 'Eddie Murphy', 'Cameron Diaz'],
  'The Mask (1994)': ['Jim Carrey', 'Cameron Diaz'],
  'Se7en (1995)': ['Brad Pitt', 'Morgan Freeman'],
  'Unforgiven (1992)': ['Clint Eastwood', 'Morgan Freeman'],
  'Million Dollar Baby (2004)': ['Clint Eastwood', 'Morgan Freeman'],
  'Catch Me If You Can (2002)': ['Leonardo DiCaprio', 'Tom Hanks'],
  'The Departed (2006)': ['Leonardo DiCaprio', 'Jack Nicholson'],
  'A Few Good Men (1992)': ['Tom Cruise', 'Jack Nicholson'],
  'Eyes Wide Shut (1999)': ['Tom Cruise', 'Nicole Kidman'],
  'Australia (2008)': ['Nicole Kidman', 'Hugh Jackman'],
  'The Color of Money (1986)': ['Paul Newman', 'Tom Cruise'],
  'Pulp Fiction (1994)': ['Samuel L. Jackson', 'Bruce Willis'],
  'The Expendables (2010)': ['Sylvester Stallone', 'Bruce Willis', 'Arnold Schwarzenegger'],
  'Heat (1995)': ['Al Pacino', 'Robert De Niro', 'Natalie Portman'],
  'The Godfather (1972)': ['Marlon Brando', 'Al Pacino'],
  'The Deer Hunter (1978)': ['Robert De Niro', 'Meryl Streep'],
  'Sabrina (1954)': ['Audrey Hepburn', 'Humphrey Bogart'],
  'Easter Parade (1948)': ['Judy Garland', 'Fred Astaire'],
  'Summer Stock (1950)': ['Judy Garland', 'Gene Kelly'],
  'Supercop (1992)': ['Jackie Chan', 'Michelle Yeoh'],
  'Fences (2016)': ['Viola Davis', 'Denzel Washington'],
  // single-star films: wrong answers only
  'Toy Story (1995)': ['Tom Hanks'],
  'Forrest Gump (1994)': ['Tom Hanks'],
  'Mamma Mia! (2008)': ['Meryl Streep'],
  'Men in Black (1997)': ['Will Smith'],
  'Top Gun (1986)': ['Tom Cruise'],
  'Pretty Woman (1990)': ['Julia Roberts'],
  'Gravity (2013)': ['Sandra Bullock'],
  'The Matrix (1999)': ['Keanu Reeves'],
  'Black Swan (2010)': ['Natalie Portman'],
  'The Terminator (1984)': ['Arnold Schwarzenegger'],
  'Rocky (1976)': ['Sylvester Stallone'],
  'Die Hard (1988)': ['Bruce Willis'],
  'Wonder Woman (2017)': ['Gal Gadot'],
  'The Silence of the Lambs (1991)': ['Anthony Hopkins'],
  'Goldfinger (1964)': ['Sean Connery'],
  "Breakfast at Tiffany's (1961)": ['Audrey Hepburn'],
  'Casablanca (1942)': ['Humphrey Bogart'],
  'The Wizard of Oz (1939)': ['Judy Garland'],
  "Singin' in the Rain (1952)": ['Gene Kelly'],
  'Some Like It Hot (1959)': ['Marilyn Monroe'],
  'Mary Poppins (1964)': ['Julie Andrews'],
  'Training Day (2001)': ['Denzel Washington'],
  'Doctor Strange (2016)': ['Benedict Cumberbatch'],
  'Rush Hour (1998)': ['Jackie Chan'],
  'Crazy Rich Asians (2018)': ['Michelle Yeoh'],
};
