#!/usr/bin/env python3
"""Generate VO with the saved Qwen Voice Studio clone voices.
gen_vo.py docs            -> rewrite audio/vo/manifest.json text + docs/VO_LINES.md (no audio)
gen_vo.py [key ...]       -> synthesise missing/changed lines (or exactly the given keys)
gen_vo.py --who jon       -> only one character"""
import json, os, re, subprocess, sys
sys.path.insert(0, os.path.dirname(__file__))
import vo_lines

ROOT = vo_lines.ROOT
OUT = ROOT / "audio/vo"
MF = OUT / "manifest.json"
SCR = ROOT / "tools/media/scratch"
VOICES = json.load(open(ROOT / "tools/media/voices.json")) if (ROOT / "tools/media/voices.json").exists() else {}


# Odie keys → the dog clip in audio/sfx/ that best fits the subtitle (default: <sfx>_1).
ODIE_CLIP = {"o_yip_2": "yip_2", "o_yip_3": "yip_3", "o_yip_long": "yip_long", "o_bark_2": "bark_2", "o_growl_play": "bark_3",
             "o_whine_muffled": "whine_2", "o_shake_off": "pant_1", "o_pant": "pant_loop"}


def tts_text(t):
    t = t.replace("…", "...").replace("—", ", ").replace("–", ", ").replace("’", "'")
    t = re.sub(r"\b([A-Z]{2,})\b", lambda m: m.group(1).capitalize() if m.group(1) not in ("TV", "OK") else m.group(1), t)
    return t


def load_mf():
    return json.load(open(MF)) if MF.exists() else {}


def save_mf(mf):
    MF.write_text(json.dumps(dict(sorted(mf.items())), indent=1, ensure_ascii=False))


def docs(lines, mf):
    fam = {}
    for k, v in lines.items():
        f = re.sub(r"(_nn)$", "", k)
        f = re.sub(r"_?\d+[a-z]?$", "", f) or f
        fam.setdefault(f, []).append(k)
    md = ["# VO lines — Garfield: Hungry Heist", "",
          "Generated by `tools/media/gen_vo.py docs` from `js/game/lines.js` (levels) + `tools/media/vo_lines.py` EXTRAS (media).",
          "Audio: `audio/vo/<key>.mp3`; machine-readable: `audio/vo/manifest.json` (key → who, text, file, dur).",
          "`_nn` = name-free take used when the player sets custom names (`audio.vo(key)` swaps automatically).",
          "Bark families: any key matching `<family>_<n>` belongs to the family; `audio.family(prefix)` lists them.", "",
          "Voices (Qwen Voice Studio, designed then saved as clones; no real-actor imitation):",
          "- **Garfield** (thought voice): `Hungry Heist · Garfield` — lazy, deep, deadpan, warm.",
          "- **Jon** (aloud): `Hungry Heist · Jon (v2 male)` — cheerful, nerdy, adult male, easily flustered.",
          "- **Lyman** (aloud): `Hungry Heist · Lyman` — theatrical, dramatic moocher charm.",
          "- **Delivery man**: `Hungry Heist · Delivery`.",
          "- **Odie** (`o_*`): dog-noise clips from audio/sfx/ (no TTS; text is the subtitle).", "",
          f"Total lines: {len(lines)}", ""]
    for f, keys in fam.items():
        md.append(f"### {f}  ({len(keys)})")
        md.append("| key | who | text | dur | src |")
        md.append("|---|---|---|---|---|")
        for k in keys:
            v = lines[k]; d = mf.get(k, {}).get("dur")
            md.append(f"| `{k}` | {v['who']} | {v['text'].replace('|', '/')} | {d if d else '—'} | {v['src']} |")
        md.append("")
    (ROOT / "docs/VO_LINES.md").write_text("\n".join(md))


def main():
    args = sys.argv[1:]
    lines = vo_lines.all_lines()
    mf = load_mf()
    for k in list(mf):
        if k not in lines:
            del mf[k]
    for k, v in lines.items():
        e = mf.setdefault(k, {})
        e.update(who=v["who"], text=v["text"], file=f"audio/vo/{k}.mp3")
        if v.get("sfx"):
            e.update(file=f"audio/sfx/{ODIE_CLIP.get(k, v['sfx'] + '_1')}.mp3", sfx=v["sfx"])
    if args[:1] == ["docs"]:
        save_mf(mf); docs(lines, mf); print("docs written", len(lines)); return
    who = None
    if args[:1] == ["--who"]:
        who = args[1]; args = args[2:]
    import tts
    only = set(args)
    SCR.mkdir(exist_ok=True)
    for k, v in lines.items():
        if only and k not in only:
            continue
        if who and v["who"] != who:
            continue
        if v.get("sfx"):
            continue
        e = mf[k]; dst = OUT / f"{k}.mp3"
        voice = VOICES[v["who"]]
        if not only and dst.exists() and e.get("gen_text") == v["text"] and e.get("voice") == voice["id"]:
            continue
        wav = SCR / f"{k}.wav"
        st = dict(voice["settings"])
        if os.environ.get("SEED"):
            st["seed"] = int(os.environ["SEED"])
        jid, s = tts.gen(st, tts_text(v["text"]), str(wav))
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(wav), "-af",
                        "silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.04,areverse,"
                        "silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.08,areverse,"
                        "loudnorm=I=-16:TP=-1.5:LRA=11", "-ac", "1", "-ar", "24000", "-b:a", "64k", str(dst)], check=True)
        dur = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(dst)],
                                   capture_output=True, text=True).stdout.strip())
        e.update(dur=round(dur, 2), gen_text=v["text"], job=jid, voice=voice["id"], seed=st["seed"])
        save_mf(mf)
        print(k, round(dur, 2), flush=True)
    docs(lines, mf)
    print("DONE")


if __name__ == "__main__":
    main()
