"""Every voiced line = levels' js/game/lines.js (the keys the game calls) + EXTRAS below (more bark variety in
the same key families, so barks can pick any key of a family from audio.voLines). `_nn` = name-free alternate."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
G, J = "garfield", "jon"


def base_lines():
    src = (ROOT / "js/game/lines.js").read_text()
    out = {}
    for k, who, text in re.findall(r"^\s*(\w+):\s*\{\s*who:\s*'(\w+)',\s*text:\s*\"(.*?)\"\s*\}", src, re.M):
        out[k] = {"who": who, "text": text, "src": "levels"}
    return out


EXTRAS = [
 ("g_intro_2", G, "Ah, the cul-de-sac. Quiet. Peaceful. Home to the world's most magnificent cat."),
 ("g_intro_3", G, "That's me. You're welcome."),
 ("g_intro_4", G, "Somewhere in there, dinner is happening without me. Unacceptable."),
 ("g_intro_5", G, "Worth it."),
 ("j_open_bowl_4", J, "Biscuits are served! Crunchy, nutritious, and only a little bit like cardboard."),
 ("j_open_bowl_5", J, "The vet says these are very good for you, buddy. Very, very good."),
 ("j_open_steak_2", J, "Steak night! With peas! And a mountain of mash! Best night of the week."),
 ("j_open_lasagna_2", J, "Lasagna! Just one scoop for me. Okay, maybe two."),
 ("j_open_meatloaf_2", J, "Ah, my famous meatloaf. Nobody makes a loaf of meat quite like me."),
 ("g_open_spit_5", G, "Bleh! That tastes like a sock that gave up on life."),
 ("g_open_spit_6", G, "That's not food. That's gravel with a marketing team."),
 ("g_open_spit_7", G, "Ptoo! I can taste the disappointment."),
 ("g_open_plan_1", G, "Change of plan. I'm having whatever he's having."),
 ("j_l10_sulk_4", J, "Lalala. Not thinking about lasagna. Not thinking about it at all."),
 ("g_l10_fridge", G, "A fridge is just a lunchbox with a door. And I have paws."),
 ("g_l10_open", G, "Hello, beautiful. Did you miss me?"),
 ("g_l10_end", G, "Chapter complete. Belly complete. Nap... beginning."),
 ("j_leg_4", J, "Ooh! Ah! Ee! Not the shin!"),
 ("j_leg_5", J, "Ow-ow-ow! Why is it always the leg?"),
 ("j_face_4", J, "Agh! Everything is cat!"),
 ("j_face_5", J, "Not the nose! I need that for smelling dinner!"),
 ("j_butt_4", J, "Hey! That's my sitting area!"),
 ("j_paper_4", J, "Read all about it!"),
 ("j_chase_7", J, "That's it! You're in big trouble, mister!"),
 ("j_chase_8", J, "How is something so round so fast?"),
 ("j_chase_9", J, "Stop! Stop in the name of dinner!"),
 ("j_chase_10", J, "Huff... puff... I should really exercise more."),
 ("j_chase_11", J, "Whoa! Watch the lamp! Watch the lamp!"),
 ("j_chase_12", J, "Get back here, you furry orange menace!"),
 ("j_catch_6", J, "Ha! Caught you!"),
 ("j_catch_7", J, "No scratching! Got it?"),
 ("j_glare_4", J, "I'm watching you."),
 ("j_glare_5", J, "You have to come down sometime."),
 ("j_giveup_5", J, "I'm not climbing on the furniture. I have dignity."),
 ("j_giveup_6", J, "Huff... you win this round. This round!"),
 ("j_back_3", J, "Honestly. Every single night."),
 ("j_lost_4", J, "My plate is empty. Again. Why is my plate always empty?"),
 ("j_lost_5", J, "Garfield! You ate my dinner!"),
 ("j_lost_5_nn", J, "Hey! Somebody ate my dinner!"),
 ("j_eat_7", J, "Mmm, compliments to the chef. That's me!"),
 ("j_eat_8", J, "Chew, chew, chew... wonderful."),
 ("j_wander_8", J, "Hmm hmm hmm, la la la..."),
 ("j_wander_9", J, "Dum de dum, dee dum..."),
 ("j_wander_10", J, "I wonder if I should take up the tuba again."),
 ("j_wander_11", J, "Did I leave the oven on? No. Probably. No."),
 ("j_wander_12", J, "Maybe I'll organise my sock drawer tonight. Wild night!"),
 ("j_wander_13", J, "Ooh, I could alphabetise the spice rack!"),
 ("j_wander_14", J, "Doo doo doo... walking, walking, walking..."),
 ("j_wander_15", J, "Why do I feel like I'm being watched?"),
 ("j_wander_16", J, "That cat is up to something. I can feel it."),
 ("j_wander_17", J, "I should call my mum. After dinner. Definitely after dinner."),
 ("j_wander_18", J, "Mmm, I can smell dinner from here."),
 ("j_wander_19", J, "La la la, nobody's going to steal my dinner tonight..."),
 ("j_wander_20", J, "I wonder what the dog next door is doing."),
 ("j_wander_21", J, "Diet biscuits. Healthy cat. Happy me. That's the plan."),
 ("j_wander_22", J, "These floorboards really need polishing."),
 ("j_stunned_2", J, "Who turned the house into a bouncy castle?"),
 ("j_stunned_3", J, "Ooh... I see little lasagnas spinning round my head."),
 ("j_chair_floor_2", J, "Chair's broken. Back's sore. Pride is definitely broken."),
 ("j_faceplant_2", J, "I'm just gonna lie here for a while."),
 ("j_vase_see3", J, "My vase! Who did this? ...Don't answer that."),
 ("j_curtain_see2", J, "They're shredded! These were nearly new!"),
 ("j_cold_4", J, "It's freezing! I'd better shut that window."),
 ("j_bed_see2", J, "My quilt! It's more holes than quilt!"),
 ("j_trapped_4", J, "Locked in my own bedroom. This is a new low."),
 ("j_trapped_5", J, "I hope nobody's eating my dinner out there!"),
 ("j_chair_bounce", J, "Whoa! The chair! It's alive!"),
 ("g_tut_move", G, "Walk around. Slowly. Majestically. Use the keys, or the stick in the corner."),
 ("g_tut_camera", G, "Drag to look around. Admire the house. It's mine, really. The human just pays for it."),
 ("g_tut_jump", G, "Jump! Yes, I can jump. I simply choose not to, most days."),
 ("g_tut_jump_up", G, "Hop up onto things. The higher I am, the further I am from trouble."),
 ("g_tut_scratch", G, "Claws out. Give it a swipe. Scratching is a cat's way of saying hello."),
 ("g_tut_wait", G, "He'll sit down to eat soon. Patience. Ugh, I hate patience."),
 ("g_tut_interact", G, "Standing on the food? Press the button to eat it. That's the best button."),
 ("g_tut_chase", G, "If he chases me, I climb up high. He can't jump. He can barely walk."),
 ("g_tut_newspaper", G, "Watch out for flying newspapers. His aim is terrible, but even he gets lucky."),
 ("g_tut_done", G, "Lesson over. You're a natural. Almost as natural as me."),
 ("g_idle_23", G, "Is it dinner time? It always feels like dinner time."),
 ("g_idle_24", G, "I could take a nap. Or I could take a nap. Tough choice."),
 ("g_idle_25", G, "Mondays. Even the word sounds like a hairball."),
 ("g_idle_26", G, "I'm not fat. I'm just extra huggable."),
 ("g_idle_27", G, "Exercise. Never heard of it. Sounds made up."),
 ("g_idle_28", G, "I love lasagna more than I love sleeping. And I really love sleeping."),
 ("g_idle_29", G, "Hello? Player? I'm not getting any thinner standing here."),
 ("g_idle_30", G, "My belly is rumbling. It's singing a song called 'feed me'."),
 ("g_idle_31", G, "Some cats chase mice. I chase snacks. Slowly."),
 ("g_idle_32", G, "I'd go for a walk, but my legs are on a break."),
 ("g_idle_33", G, "Nap first, plan later. That's my motto. Well, one of them."),
 ("g_idle_34", G, "A balanced diet is a lasagna in each paw."),
 ("g_idle_35", G, "If Mondays were food, they'd be diet biscuits."),
 ("g_idle_36", G, "I see food, I eat it. It's a very simple system."),
 ("g_idle_37", G, "Is this floor heated? It should be heated. I'll file a complaint."),
 ("g_idle_38", G, "I'm just resting my eyes. With my eyes open."),
 ("g_idle_39", G, "Somewhere out there is a lasagna with my name on it."),
 ("g_idle_40", G, "I'm not ignoring you. I'm conserving charm."),
 ("g_idle_41", G, "Hmm. Is that a crumb? No. Just a dust bunny. Tragic."),
 ("g_idle_42", G, "Stretching counts as exercise. I just did a stretch. Workout over."),
 ("g_idle_43", G, "Some call it a weight problem. I call it more of me to love."),
 ("g_idle_44", G, "Thinking about food is my hobby. Eating it is my career."),
 ("g_idle_45", G, "Cats have nine lives. I plan to spend all nine on the sofa."),
 ("g_idle_46", G, "Tick tock. The food isn't going to steal itself."),
 ("g_idle_47", G, "Do I hear a can opener? No. Just my imagination. Again."),
 ("g_idle_48", G, "If you need me, I'll be here. Being adorable."),
 ("g_near_3", G, "There it is. The love of my life. On a plate."),
 ("g_near_4", G, "Steady. Steady. Don't drool on the table."),
 ("g_near_5", G, "Hello, dinner. Did you miss me?"),
 ("g_near_6", G, "Mmm. Smells like victory. And gravy."),
 ("g_eat_1", G, "Nom nom nom nom!"),
 ("g_eat_2", G, "Mmm-hmm! Oh yes. Oh, that's the stuff."),
 ("g_eat_3", G, "Gulp! Gone. Like it was never there."),
 ("g_eat_lasagna", G, "Lasagna! My one true love!"),
 ("g_jumpfail_5", G, "Nobody saw that. Nobody saw that."),
 ("g_jumpfail_6", G, "Maybe I need a run-up. Or a ladder. Or a butler."),
 ("g_scratch_hit_5", G, "Ooh, he's hopping. Like a very sad kangaroo."),
 ("g_scratch_hit_6", G, "Claws: sharp. Aim: perfect. Guilt: none."),
 ("g_scratch_miss_4", G, "Swish. That was a warning shot."),
 ("g_chased_7", G, "This is the most exercise I've done all year."),
 ("g_chased_8", G, "Run now, nap later. Run now, nap later."),
 ("g_chased_9", G, "Why does he always take things so personally?"),
 ("g_chased_10", G, "Wheee! I mean... help!"),
 ("g_escape_4", G, "Safe. The high ground always wins."),
 ("g_escape_5", G, "Phew. Now I need a nap. And a snack. And another nap."),
 ("g_gaveup_4", G, "He'll forget about this in five minutes. He forgets where his keys are."),
 ("g_caught_6", G, "Flattened by the evening news. Classic."),
 ("g_caught_7", G, "I'll be fine. I'm well padded."),
 ("g_caught_8", G, "Round one to the human. The war continues."),
 ("g_paper_hit_4", G, "Bonk. Headline news: cat hit by headline news."),
 ("g_win_7", G, "Another flawless heist. I'd take a bow, but bending is effort."),
 ("g_win_8", G, "Delicious. Ten out of ten. Would steal again."),
 ("g_win_9", G, "And that's how it's done. Now, if you'll excuse me, I have a nap scheduled."),
 ("g_win_10", G, "I'm not saying I'm a genius. But I'm not not saying it."),
 ("g_win_11", G, "That was a team effort. And by team, I mean me."),
 ("g_win_lasagna", G, "Layers of pasta, layers of cheese, layers of happiness."),
 ("g_win_steak", G, "Steak, mash and peas. I even ate the peas. Don't tell anyone."),
 ("g_win_meatloaf", G, "Meatloaf. It's a loaf. Made of meat. Genius."),
 ("g_jon_down_1", G, "Look at him, all stunned. Perfect time for a snack."),
 ("g_jon_down_2", G, "He's busy. Dinner, here I come."),
 ("g_jon_down_3", G, "While he's distracted, dinner is undefended."),
 ("g_belly_1", G, "My belly's getting bigger. My plan is working."),
 ("g_vase_1", G, "Oops. Gravity did that. I just helped."),
 ("g_curtain_1", G, "Rrrrip. Ah, the sweet sound of interior decorating."),
 ("g_window_1", G, "Brrr. Cold air in. Human out. Hopefully."),
 ("g_door_1", G, "And... close. Enjoy your room, Jon."),
 ("g_door_1_nn", G, "And... close. Enjoy your room."),
 ("g_fridge_top", G, "Up here, I'm the king of the kitchen."),
]

# Names said aloud in levels' lines that have no _nn take yet.
NN_FIXES = {
 "g_escape_3_nn": (G, "Enjoy the view, pal."),
 "g_idle_16_nn": (G, "His dinner won't eat itself. That's my job."),
 "g_scratch_hit_2_nn": (G, "Claws: one. Human: zero."),
 "g_chased_6_nn": (G, "Up high! He can't jump!"),
 "g_escape_1_nn": (G, "Ha. Humans can't jump."),
 "g_tut_2_nn": (G, "My human's wandering around. Let's practise on him."),
 "g_l02_frontleg_nn": (G, "Wrong leg. The back ones hold up the human."),
 "l01_hint_1_nn": (G, "His face is up high. I need to be up high too."),
 "l02_hint_2_nn": (G, "If a back leg of his chair broke... timber!"),
 "l02_hint_3_nn": (G, "Scratch the BACK leg of his chair."),
 "l03_hint_3_nn": (G, "Scratch the vase off the sill, then run for the food while he looks."),
 "l04_hint_2_nn": (G, "If I really shred those curtains, he'll have to come and look."),
 "l07_hint_2_nn": (G, "If I open that window, he'll have to close it."),
 "l08_hint_1_nn": (G, "He loves his bed. Almost as much as I love his dinner."),
 "l08_hint_3_nn": (G, "Shred the bed, wait for him to go in, then close the door on him!"),
 "l09_hint_3_nn": (G, "Bump the table three times from below, then walk under his chair!"),
 "l10_hint_1_nn": (G, "That vase is back. He never learns."),
 "l10_hint_2_nn": (G, "If he's busy by the broken vase... a little scratch might trip him up."),
 "l10_hint_3_nn": (G, "Knock the vase off, scratch him next to the pieces, then raid the fridge!"),
}


def all_lines():
    lines = base_lines()
    for k, who, text in EXTRAS:
        if k in lines:
            raise SystemExit(f"extra key collides with lines.js: {k}")
        lines[k] = {"who": who, "text": text, "src": "media"}
    for k, v in NN_FIXES.items():
        if v and k not in lines:
            lines[k] = {"who": v[0], "text": v[1], "src": "media"}
    return lines
