(function () {
  const image = name => `images/${name}.jpg`;

  window.BlackGlassStory = {
    start: "cot_room",
    panicEnding: "ending_observation",
    items: {
      wristband: { name: "Patient wristband", clue: "The printed name is yours. The date is tomorrow." },
      shard: { name: "Black glass shard", clue: "It reflects rooms you have not entered yet." },
      key: { name: "Brass ward key", clue: "Stamped CHILD SLEEP UNIT." },
      matchbook: { name: "Sanitarium matchbook", clue: "Black Glass Sanitarium burned down before you were born." },
      ledger: { name: "Admission ledger", clue: "Your signature appears on every page, in different ages of handwriting." },
      candle: { name: "Black candle", clue: "It gives light only when you are not looking at it." },
      fuse: { name: "Porcelain fuse", clue: "Warm as a pulse. The generator wants it back." },
      chart: { name: "Star chart", clue: "The sky map marks one constellation: The Waking Eye." },
      heart: { name: "Clockwork heart", clue: "It ticks in time with your own chest." },
    },
    endings: {
      clear_morning: { title: "Clear Morning", kind: "good" },
      witness: { title: "The Witness", kind: "strange" },
      black_glass: { title: "Black Glass", kind: "bad" },
      cot: { title: "Under The Cot", kind: "bad" },
      choir: { title: "The Choir Below", kind: "bad" },
      observation: { title: "Kept For Observation", kind: "bad" },
    },
    rooms: {
      cot_room: {
        title: "Cot Room",
        kicker: "You wake",
        image: image("cot_room"),
        text: "Your fingers find cold tile. A cot frame presses lines into your back. The ceiling is too high, the air tastes of rainwater and antiseptic, and someone has written WAKE CLEANLY on the inside of the door.",
        choices: [
          { label: "Read the tag around your wrist", target: "cot_tag", hint: "Take the first clue" },
          { label: "Open the door", target: "artery_hall" },
          { label: "Crawl under the cot and close your eyes", target: "ending_cot", danger: true },
        ],
      },
      cot_tag: {
        title: "Cot Room",
        kicker: "Evidence",
        image: image("cot_room"),
        text: "The wristband is hospital-white and damp. It carries your full name, a room number that changes when you breathe, and tomorrow's date. The clasp breaks before you decide to keep it.",
        gain: ["wristband"],
        history: "Found the patient wristband in the cot room.",
        choices: [
          { label: "Pocket the wristband", target: "cot_room" },
        ],
      },
      artery_hall: {
        title: "Artery Hall",
        kicker: "Upper floor",
        image: image("artery_hall"),
        text: "The hallway bends like something alive. Doors sit in the walls at uneven heights. At the far end, red emergency bulbs blink in a slow rhythm that is almost a heartbeat.",
        choices: [
          { label: "Enter the tiled washroom", target: "washroom" },
          { label: "Follow the music box", target: "nursery" },
          { label: "Take the concrete stairwell", target: "stairwell" },
          { label: "Return to the cot room", target: "cot_room" },
        ],
      },
      washroom: {
        title: "Washroom",
        kicker: "Water memory",
        image: image("washroom"),
        text: "White tiles climb into darkness. Every basin is full, but none overflow. The mirror above the center sink is made from black glass, and your reflection is late by half a second.",
        choices: [
          { label: "Break a corner from the mirror", target: "washroom_shard", hint: "Sharp truth" },
          { label: "Wash your face", target: "washroom_water", danger: true },
          { label: "Leave the taps running", target: "artery_hall", dread: 1 },
        ],
      },
      washroom_shard: {
        title: "Washroom",
        kicker: "Evidence",
        image: image("washroom"),
        text: "The glass comes away without sound. In the shard, the hallway behind you is empty. In the mirror, something tall is standing there with its hand raised.",
        gain: ["shard"],
        dread: 1,
        history: "Took a black glass shard from the washroom mirror.",
        choices: [
          { label: "Do not turn around", target: "washroom" },
        ],
      },
      washroom_water: {
        title: "Washroom",
        kicker: "Cold",
        image: image("washroom"),
        text: "The water smells like a storm drain. For one second you remember headlights under rain. For the next, you forget how to breathe.",
        dread: 2,
        choices: [
          { label: "Grip the basin until the room returns", target: "washroom" },
        ],
      },
      nursery: {
        title: "Nursery Ward",
        kicker: "Child sleep unit",
        image: image("nursery"),
        text: "Rows of tiny beds sit under paper moons. A music box turns on a nurse's desk, playing a lullaby with one missing note. The locked cabinet beside it has your initials scratched into the paint.",
        choices: [
          { label: "Open the music box", target: "nursery_key" },
          { label: "Hide beneath the nearest crib", target: "nursery_hide", danger: true },
          { label: "Return to Artery Hall", target: "artery_hall" },
        ],
      },
      nursery_key: {
        title: "Nursery Ward",
        kicker: "Evidence",
        image: image("nursery"),
        text: "Inside the music box, a small brass key turns in place by itself. When you lift it out, the song finally finds its missing note, and every paper moon looks down.",
        gain: ["key"],
        history: "Found the brass ward key inside the nursery music box.",
        choices: [
          { label: "Close the music box", target: "nursery" },
        ],
      },
      nursery_hide: {
        title: "Nursery Ward",
        kicker: "Too small",
        image: image("nursery"),
        text: "The crib space should not fit you. It does. The mattress above sags lower and lower until your shoulder bones remember being smaller.",
        dread: 3,
        choices: [
          { label: "Kick free", target: "nursery" },
        ],
      },
      stairwell: {
        title: "Concrete Stairwell",
        kicker: "Between floors",
        image: image("stairwell"),
        text: "The stairwell smells of wet concrete. Up is marked RECOVERY. Down is marked OBSERVATION. Someone has scratched a third arrow into the wall: OUT, pointing through solid stone.",
        choices: [
          { label: "Descend to the service floor", target: "kitchen" },
          { label: "Push through the fire door", target: "archive" },
          { label: "Climb back to Artery Hall", target: "artery_hall" },
          { label: "Knock on the stone marked OUT", target: "stairwell_knock", danger: true },
        ],
      },
      stairwell_knock: {
        title: "Concrete Stairwell",
        kicker: "Answer",
        image: image("stairwell"),
        text: "Something knocks back from inside the wall. It uses your rhythm perfectly, then adds one final tap you did not make.",
        dread: 2,
        choices: [
          { label: "Go downstairs", target: "kitchen" },
          { label: "Go upstairs", target: "artery_hall" },
        ],
      },
      kitchen: {
        title: "Night Kitchen",
        kicker: "Service floor",
        image: image("kitchen"),
        text: "A long table is set for one. The soup bowls are dry. The oven light is on, though the oven is not plugged in. A matchbook lies beside a plate of ash.",
        choices: [
          { label: "Take the matchbook", target: "kitchen_matchbook" },
          { label: "Open the walk-in freezer", target: "kitchen_freezer", danger: true },
          { label: "Enter the glass conservatory", target: "conservatory" },
          { label: "Return to the stairwell", target: "stairwell" },
        ],
      },
      kitchen_matchbook: {
        title: "Night Kitchen",
        kicker: "Evidence",
        image: image("kitchen"),
        text: "The matchbook reads BLACK GLASS SANITARIUM. Beneath the logo someone has penciled: Burned down. Still admitting.",
        gain: ["matchbook"],
        history: "Found the Black Glass Sanitarium matchbook.",
        choices: [
          { label: "Leave the table", target: "kitchen" },
        ],
      },
      kitchen_freezer: {
        title: "Night Kitchen",
        kicker: "Cold storage",
        image: image("kitchen"),
        text: "The freezer contains no food. Only shelves of numbered breath, sealed in glass jars. One jar fogs from the inside and writes your room number.",
        dread: 2,
        choices: [
          { label: "Shut the freezer", target: "kitchen" },
        ],
      },
      archive: {
        title: "Records Archive",
        kicker: "Paper remembers",
        image: image("archive"),
        text: "Stacks of folders lean like exhausted patients. A brass desk lamp lights one open ledger. The ink is fresh. It smells like pennies and thunder.",
        choices: [
          { label: "Read the admission ledger", target: "archive_ledger" },
          { label: "Take the star chart from the drawer", target: "archive_chart" },
          { label: "Enter the chapel", target: "chapel" },
          { label: "Return to the stairwell", target: "stairwell" },
        ],
      },
      archive_ledger: {
        title: "Records Archive",
        kicker: "Evidence",
        image: image("archive"),
        text: "The ledger lists you as patient, witness, doctor, next of kin. Your signature changes age with every line. At the bottom: Consent to wake must be freely given.",
        gain: ["ledger"],
        reduceDread: 1,
        history: "Read the admission ledger and learned consent matters.",
        choices: [
          { label: "Close the ledger", target: "archive" },
        ],
      },
      archive_chart: {
        title: "Records Archive",
        kicker: "Evidence",
        image: image("archive"),
        text: "The drawer holds a star chart drawn on surgical paper. It shows no real sky. Still, one constellation burns through the page: The Waking Eye.",
        gain: ["chart"],
        history: "Found the star chart for the roof observatory.",
        choices: [
          { label: "Fold the chart carefully", target: "archive" },
        ],
      },
      chapel: {
        title: "Chapel Of The Ward",
        kicker: "Quiet room",
        image: image("chapel"),
        text: "Twelve chairs face a blank wall. There is no altar, only a black candle on a metal tray. The hymn books are filled with discharge forms.",
        choices: [
          { label: "Take the black candle", target: "chapel_candle" },
          { label: "Kneel and sing from the forms", target: "ending_choir", danger: true },
          { label: "Return to the archive", target: "archive" },
        ],
      },
      chapel_candle: {
        title: "Chapel Of The Ward",
        kicker: "Evidence",
        image: image("chapel"),
        text: "The candle is colder than the room. Its wick glows only when your eyes slide away. You take it because the dark behind the chairs has begun to stand.",
        gain: ["candle"],
        history: "Took the black candle from the chapel.",
        choices: [
          { label: "Back out slowly", target: "chapel" },
        ],
      },
      conservatory: {
        title: "Glass Conservatory",
        kicker: "False outside",
        image: image("conservatory"),
        text: "Rain falls upward over the glass roof. Dead plants press their roots against the panes as if the soil is on the other side. A porcelain fuse sits in the mouth of a stone fountain.",
        choices: [
          { label: "Take the porcelain fuse", target: "conservatory_fuse" },
          { label: "Break a pane and climb out", target: "conservatory_break", danger: true },
          { label: "Enter the generator room", target: "engine_room" },
          { label: "Return to the kitchen", target: "kitchen" },
        ],
      },
      conservatory_fuse: {
        title: "Glass Conservatory",
        kicker: "Evidence",
        image: image("conservatory"),
        text: "The fuse warms in your palm with a human rhythm. Somewhere below, a dead machine coughs once.",
        gain: ["fuse"],
        history: "Found a porcelain fuse in the conservatory fountain.",
        choices: [
          { label: "Listen for the machine", target: "conservatory" },
        ],
      },
      conservatory_break: {
        title: "Glass Conservatory",
        kicker: "Wrong side",
        image: image("conservatory"),
        text: "The pane breaks inward. So does the rain. So does the sky. For a moment you see yourself sleeping below the world.",
        dread: 3,
        choices: [
          { label: "Cover your eyes", target: "conservatory" },
        ],
      },
      engine_room: {
        title: "Generator Room",
        kicker: "Pulse engine",
        image: image("engine_room"),
        text: "The generator is made of brass, wire, and something that might be bone. A round fuse socket waits at its center. The whole room is holding its breath.",
        choices: [
          { label: "Fit the porcelain fuse", target: "engine_power", requires: ["fuse"], hideIfFlag: ["power"] },
          { label: "Follow the powered lenses upward", target: "observatory", requiresFlag: ["power"] },
          { label: "Reach into the socket bare-handed", target: "engine_socket", danger: true },
          { label: "Unlock the lower ward", target: "cellar", requires: ["key"] },
          { label: "Return to the conservatory", target: "conservatory" },
        ],
      },
      engine_power: {
        title: "Generator Room",
        kicker: "Power",
        image: image("engine_room"),
        text: "The fuse seats itself. Lights bloom through the building one floor at a time. High above, glass lenses begin to turn toward a sky you cannot see from here.",
        set: ["power"],
        reduceDread: 1,
        history: "Restored power to the roof lenses.",
        choices: [
          { label: "Follow the turning lenses", target: "observatory", requiresFlag: ["power"] },
          { label: "Unlock the lower ward", target: "cellar", requires: ["key"] },
          { label: "Return to the conservatory", target: "conservatory" },
        ],
      },
      engine_socket: {
        title: "Generator Room",
        kicker: "Live",
        image: image("engine_room"),
        text: "Your hand enters the dark socket. The machine learns your pulse and gives you three others in exchange.",
        dread: 3,
        choices: [
          { label: "Pull free", target: "engine_room" },
        ],
      },
      cellar: {
        title: "Lower Ward",
        kicker: "Observation",
        image: image("cellar"),
        text: "The brass ward key opens a door beneath the generator. Below it, observation rooms sit behind one-way glass. Every bed is empty except the one at the end.",
        choices: [
          { label: "Enter the last observation room", target: "cellar_heart" },
          { label: "Look through the one-way glass", target: "cellar_glass", danger: true },
          { label: "Climb back to the generator", target: "engine_room" },
        ],
      },
      cellar_heart: {
        title: "Lower Ward",
        kicker: "Evidence",
        image: image("cellar"),
        text: "On the pillow is a clockwork heart, clicking calmly. A tag on it reads: returned property. When you hold it, the house misses a beat.",
        gain: ["heart"],
        reduceDread: 1,
        history: "Recovered the clockwork heart from the lower ward.",
        choices: [
          { label: "Leave the room before it notices", target: "cellar" },
        ],
      },
      cellar_glass: {
        title: "Lower Ward",
        kicker: "Watched",
        image: image("cellar"),
        text: "Behind the one-way glass, a crowd of doctors looks back. They all have your face. One writes the word RELAPSE on a clipboard.",
        dread: 3,
        choices: [
          { label: "Step away from the glass", target: "cellar" },
        ],
      },
      observatory: {
        title: "Roof Observatory",
        kicker: "Waking eye",
        image: image("observatory"),
        text: "The roof is a dome of cracked black glass. Powered lenses grind overhead. The star chart trembles in your hand, trying to align with a sky that is not outside but underneath you.",
        choices: [
          { label: "Align the lenses with the chart", target: "observatory_align", requires: ["chart"], requiresFlag: ["power"] },
          { label: "Look through the largest lens", target: "observatory_lens", danger: true },
          { label: "Return to the generator room", target: "engine_room" },
        ],
      },
      observatory_align: {
        title: "Roof Observatory",
        kicker: "Truth",
        image: image("observatory"),
        text: "The lenses lock onto The Waking Eye. Every room below becomes transparent. You see the cot, the ward, the accident, and your own hand reaching for the door in sleep.",
        set: ["aligned"],
        reduceDread: 2,
        history: "Aligned the roof lenses and saw the house as a memory ward.",
        choices: [
          { label: "Descend to the black glass door", target: "black_door" },
        ],
      },
      observatory_lens: {
        title: "Roof Observatory",
        kicker: "Too much sky",
        image: image("observatory"),
        text: "The lens shows the back of your own skull. Something inside turns, notices you watching, and smiles without a mouth.",
        dread: 3,
        choices: [
          { label: "Drop the lens cover", target: "observatory" },
        ],
      },
      black_door: {
        title: "Black Glass Door",
        kicker: "The choice",
        image: image("black_door"),
        text: "The door waits where the stairwell wall said OUT. Its surface reflects every room at once. The handle is warm. Your collected clues hum in your pockets, arguing about whether waking is the same as leaving.",
        choices: [
          { label: "Open it and wake cleanly", target: "ending_clear", requires: ["wristband", "ledger", "heart", "chart"], requiresFlag: ["aligned"], maxDread: 6 },
          { label: "Stay and mark the safe doors for the next sleeper", target: "ending_witness", requires: ["candle", "shard", "ledger"] },
          { label: "Open it without understanding", target: "ending_black_glass" },
          { label: "Step back. Search more rooms.", target: "artery_hall" },
        ],
      },
      ending_clear: {
        ending: "clear_morning",
        title: "Clear Morning",
        kicker: "Ending",
        image: image("black_door"),
        text: "You open the door with your name in one hand and your heart in the other. The house folds itself into a single breath. Morning waits beyond the glass, cold and real.",
      },
      ending_witness: {
        ending: "witness",
        title: "The Witness",
        kicker: "Ending",
        image: image("black_door"),
        text: "You light the black candle and carve arrows into the rooms that lied least. When the next sleeper starts tapping at the dark, you will be the quiet mark beside the correct door.",
      },
      ending_black_glass: {
        ending: "black_glass",
        title: "Black Glass",
        kicker: "Ending",
        image: image("horror"),
        text: "You open the door before the truth can name you. Black glass pours out like water. It fills your mouth with every room you skipped.",
      },
      ending_cot: {
        ending: "cot",
        title: "Under The Cot",
        kicker: "Ending",
        image: image("cot_room"),
        text: "The cot is low, but the dark beneath it is endless. You crawl until your knees forget tile, until the tapping above you belongs to somebody else.",
      },
      ending_choir: {
        ending: "choir",
        title: "The Choir Below",
        kicker: "Ending",
        image: image("chapel"),
        text: "You sing the discharge form. Chairs scrape behind you as unseen patients rise for the chorus. By the second verse, you no longer need a mouth.",
      },
      ending_observation: {
        ending: "observation",
        title: "Kept For Observation",
        kicker: "Ending",
        image: image("horror"),
        text: "Dread reaches the top of the chart. The rooms become clinical. Gentle hands guide you back to bed while a doctor with your face writes: not ready.",
      },
    },
  };
})();
